VREng: src/vreng/log.cpp File Reference
log.cpp File Reference
#include "vreng.hpp"
#include "gui.hpp"
#include "env.hpp"
#include "file.hpp"
#include <iostream>
Functions
void fatal (const char *s,...)
void warning (const char *s,...)
void notice (const char *s,...)
void trace (int dbgmask, const char *s,...)
void trace2 (int dbgmask, const char *s,...)
void error (const char *s,...)
FILE * writelog (const char *s,...)
void closelog (FILE *fl)
void printlog ()
void progression (char c)
void endprogression ()
Variables
const char * e_fork = "can't fork for"
const char * e_exec = "can't exec"
const char * e_tool = "unknown tool"
const char * e_not_implemented = "not implemented"
const char * e_bad_type = "bad type"
static bool infatal = false
Function Documentation
closelog()
void closelog (FILE * fl)
Definition at line 131 of file log.cpp.
References File::closeFile().
Referenced by printlog(), and statLog().
endprogression()
void endprogression ()
Definition at line 158 of file log.cpp.
Referenced by World::enter(), and World::init().
error()
void error (const char * s, ...)
Definition at line 100 of file log.cpp.
Referenced by Avi::add_audio(), Avi::add_frame(), Gui::addCart(), Socket::addMembership(), Gui::addUser(), Vicinity::analyseTopo(), Vicinity::analyseVicinity(), Face::animate(), Aoi::aoiEnter(), Movie::aviInit(), Socket::bindSocket(), Body::Body(), X3d::browseX3dTree(), NetObject::buildNoidFromString(), OClass::builtinInstance(), Face::change(), Movie::changePermanent(), Vnc::changePermanent(), Guide::changePosition(), Texture::check(), World::checkIcons(), Clip::Clip(), World::compute(), Obj::computeNormals(), Socket::connection(), HttpThread::connection(), VjcSocket::connectSend(), Vac::connectThread(), Android::connectToBapServer(), VNCRFBproto::connectToRFBServer(), VNCSockets::ConnectToTcpAddr(), convert_format(), Channel::create(), Channel::createMcastRecvSocket(), Socket::createUcastSocket(), OClass::creatorInstance(), Cache::curl(), NetObject::declareObjDelta(), Channel::deleteFromList(), NetObject::deleteFromList(), Session::deleteSessionBySsrc(), WObject::delFromList(), Vicinity::describeTopo(), Vicinity::describeVisual(), Vnc::disconnectServer(), Solid::displayList(), Reader::downloadInCache(), Dxf::draw(), Md2::draw(), movable::drawAABB(), movable::drawBoundingBox(), X3d::drawMesh(), X3d::drawPrimitive(), Socket::dropMembership(), Gate::enter(), World::enter(), Face::facesHttpReader(), Avi::finish_list(), WObject::generalIntersect(), movable::getAABB(), rigid::getBoundingBox(), Render::getBufferSelection(), Channel::getbysa(), Vjc::getData(), Channel::getfdbysa(), Channel::getGroup(), NetObject::getNetObject(), Noid::getNetObject(), OClass::getOClass(), Payload::getPayload(), Widgets::getPointedObject(), WObject::getProperty(), Channel::getsabysa(), Rtp::getSdesItemBySsrc(), Source::getSource(), Socket::getSrcPort(), Txf::getTCVI(), Body::getTok(), Solid::getTok(), Socket::handleBlocking(), Socket::handleLoopback(), VNCClient::handleRFBServerMessage(), Http::httpOpen(), Http::httpRead(), Book::httpReader(), Lwo::httpReader(), Face::httpReader(), Dxf::httpReader(), Hairs::httpReader(), Txf::httpReader(), Body::httpReader(), Guy::httpReader(), World::httpReader(), Walls::httpReader(), X3d::httpReader(), Icon::Icon(), Img::Img(), _3ds::importModel(), _3ds::importTextures(), Ase::importTextures(), Obj::importTextures(), WObject::imposedMovement(), Cache::inCache(), Payload::incomingCreate(), Payload::incomingDelta(), Payload::incomingOther(), Payload::incomingQuery(), movable::init(), Bvh::init(), Interpolator::initArrays(), VNCRFBproto::initialiseRFBConnection(), WObject::initializeObject(), Android::initReceiver(), Route::initRoute(), TimeSensor::initSensor(), Interpolator::initTarget(), Office::launch(), Pdf::launch(), Ps::launch(), Midi::launch(), Mp3::launch(), Wav::launch(), Au::launch(), Mpeg::launch(), Ps::launcha2ps(), Browser::launchchrome(), Browser::launchmozilla(), Browser::launchnetscape(), Browser::launchsafari(), Texture::listTextures(), Face::load(), Img::loadBMP(), Img::loadDDS(), Hairs::loader(), Text::loadFont(), _3ds::loadFromFile(), Ase::loadFromFile(), Obj::loadFromFile(), Img::loadJPG(), Img::loadPCX(), Img::loadPNG(), Img::loadTIF(), Img::loadXPM(), rigid::makeList(), movable::movable(), movable::move(), Movie::mpegInit(), NetIncoming(), NetTimeout(), Book::nextSheet(), Avi::open_output_file(), Cache::openCache(), Socket::openDatagram(), Sound::opendev(), Socket::openStream(), Pref::parse(), VectorTools::parseCertifiedVectors(), Parse::parseLine(), Solid::parser(), Url::parser(), Solid::parseShape(), Parse::parseSolid(), VectorTools::parseVectors(), Parse::parseVreLines(), WObject::permanentMovement(), Book::prevSheet(), Ogl::printGLError(), Parse::printNumline(), Bvh::process(), _3ds::processNextChunk(), psd_load(), Payload::putPayload(), WObject::putProperty(), World::quit(), Icon::quit(), BoneVertex::read(), Avi::read_data(), Avi::read_header(), Android::readBapFrame(), readDXF(), Bap::readFrame(), VNCSockets::ReadFromRFBServer(), Lwo::readPnts(), Lwo::readPols(), Lwo::readSrfs(), Payload::recvPayload(), Rtp::recvRTCPPacket(), Gui::removeCart(), Gui::removeUser(), NetObject::replicateObject(), OClass::replicatorInstance(), Img::resize(), Vac::resolveWorldUrl(), Socket::reuseAddr(), rigid::rigid(), Img::savePNG(), NetObject::sendDelta(), Rtp::sendPacket(), Payload::sendPayload(), Android::sendPlayToBapServer(), VNCClient::sendRFBEvent(), Session::sendRTCPPacket(), Session::sendSRSDES(), World::setChan(), Texture::setMime(), movable::setName(), Socket::setScope(), X3d::setupInterpolators(), Render::showSolidList(), Parse::skipChar(), Solid::solidParser(), Modeler::start(), Vjc::start(), Audio::start(), Xterm::start(), Video::start(), Wb::start(), Au::start(), Midi::start(), Mp3::start(), Mpeg::start(), Office::start(), Pdf::start(), Wav::start(), Browser::start(), Wget::start(), Avi::start_list(), Solid::statueParser(), File::swapEndian(), Socket::tcpNoDelay(), Payload::tellStrInPayload(), Texture::update(), WObject::update3D(), TimeSensor::updateFraction(), Gui::updateUser(), Interpolator::updateValue(), User::User(), User::userMovement(), Ps::view(), VjcSocket::VjcSocket(), VNCClient::VNCInit(), VNCClientTextured::VNCInit(), VNCSockets::VNCSockets(), Avi::write_header(), and VNCSockets::WriteExact().
fatal()
void fatal (const char * s, ...)
Definition at line 35 of file log.cpp.
References infatal, and Global::quitVreng().
Referenced by OClass::OClass(), and Global::start().
notice()
void notice (const char * s, ...)
Definition at line 65 of file log.cpp.
References g, Global::gui, and Gui::writeMessage().
Referenced by Gui::addCart(), Gui::addUser(), Aoi::aoiEnter(), Capture::captureGl2jpg(), Capture::captureGl2png(), Capture::captureXwd(), World::compute(), Vnc::connectServer(), Bullet::get_hit(), Dart::get_hit(), Gui::gotoWorld(), Board::import(), VNCRFBproto::initialiseRFBConnection(), Carrier::leave(), Vnc::leaveFocus(), Widget::leaveFocus(), VjcSocket::openRecv(), Gui::removeCart(), WObject::removeFromScene(), Gui::removeUser(), Guide::restore(), Icon::save(), Widgets::saveCB(), Capture::startVideo(), Capture::stopVideo(), Carrier::take(), Vnc::takeFocus(), Widget::takeFocus(), User::u_get_ax(), User::u_get_ay(), User::u_get_az(), User::u_get_xy(), User::u_get_z(), Gui::updateUser(), User::User(), Gate::whenIntersect(), Projectile::whenIntersect(), and User::whenIntersect().
printlog()
void printlog ()
Definition at line 136 of file log.cpp.
References closelog(), Env::dir(), Global::env, g, File::openFile(), and PATH_LEN.
Referenced by statLog().
progression()
void progression (char c)
Definition at line 152 of file log.cpp.
Referenced by Http::httpOpen(), Cache::openCache(), Parse::parseVreLines(), Universe::runWheel(), Universe::sigWheel(), Universe::stopWheel(), WObject::updateMySqlPosition(), WObject::updateMySqlPosZ(), and WObject::updateMySqlState().
trace()
void trace (int dbgmask, const char * s, ...)
Definition at line 77 of file log.cpp.
References DBG_FORCE, Global::debug, and g.
Referenced by Vicinity::actionList(), Vrelet::addPoint(), Cart::addToCart(), Face::animate(), Face::animEyeBall(), Face::animEyeBrow(), Face::animEyeLid(), Face::animHead(), Face::animLip(), Face::animNose(), Aoi::aoiEnter(), Ball::Ball(), Hud::bitmap_output(), Travelator::build(), Session::buildBYE(), Session::buildRtpHeader(), Session::buildSDES(), Session::buildSR(), World::call(), Face::change(), Movie::changePermanent(), World::checkIcons(), HttpThread::checkProxy(), Vrelet::click(), World::compute(), Render::computeCameraProjection(), Render::config(), Host::connect(), HttpThread::connection(), Vnc::connectServer(), VNCSockets::ConnectToTcpAddr(), Channel::create(), Session::create(), Session::createMySdes(), Gui::createWidgets(), Channel::deleteFromList(), Session::deleteSessionBySsrc(), Session::deleteSourceBySsrc(), Door::Door(), Cache::download(), Vrelet::draw(), HttpThread::end(), Gate::enter(), World::enter(), Face::facesHttpReader(), Obj::fillInObjectInfo(), VNCClient::fillRect(), functionMenu(), BoneAnimator::generateLinkList(), Icon::get_gname(), Icon::get_tex(), Icon::get_url(), User::get_username(), Channel::getbysa(), Channel::getfdbysa(), Txf::getFromCache(), Md2::getGLCmds(), Channel::getGroup(), Vac::getList(), WObject::getMySqlState(), WObject::getObjectByName(), WObject::getObjectHumanName(), Payload::getPayload(), Widgets::getPointedObject(), Channel::getPort(), Source::getSource(), Channel::getTtl(), gifReadBlocks(), World::goBack(), World::goForward(), Hairs::Hairs(), VNCClient::handleCoRRE32(), VNCClient::handleHextile32(), VNCClient::handleRRE32(), Widgets::homeCB(), Http::httpOpen(), Texture::httpReader(), Hairs::httpReader(), Txf::httpReader(), World::httpReader(), Icon::Icon(), Ase::importTextures(), Payload::incomingCreate(), Payload::incomingDelete(), Payload::incomingDelta(), Payload::incomingOther(), Payload::incomingQuery(), Session::incrSources(), HttpThread::init(), World::init(), Pref::init(), Pref::initEnvPrefs(), World::initGeneralFuncList(), VNCRFBproto::initialiseRFBConnection(), NetObject::initProperties(), Movie::inits(), Water::inits(), Global::initSignals(), Channel::join(), Channel::joinManager(), Cart::leaveIntoWorld(), Img::loadBMP(), Body::loadBodyParts(), Img::loadDDS(), Img::loadPNG(), Img::loadSGI(), _3ds::loadTexture(), Ase::loadTexture(), Img::loadTGA(), Img::loadTIF(), User::makeSolid(), Navig::mousePressB1orB3(), Channel::naming(), NetIncoming(), NetObject::NetObject(), NetTimeout(), Channel::newChanStr(), Scene::paintScene(), Pref::parse(), Gate::parser(), Url::parser(), Parse::parseVreLines(), VNCRFBproto::printPixelFormat(), Vrelet::processClient(), User::put_ray(), HttpThread::putfifo(), Payload::putPayload(), Channel::quit(), World::quit(), Global::quitVreng(), Bap::readFrame(), V3d::readV3Dfile(), Payload::recvPayload(), Rtp::recvRTCPPacket(), Session::refreshMySdes(), BoneAnimator::registerMesh(), BoneAnimator::registerSkeleton(), Cart::removeFromCart(), Hud::render(), Icon::save(), Channel::sendBYE(), NetObject::sendCreate(), NetObject::sendDelete(), NetObject::sendDeleteNoid(), Noid::sendDeleteNoid(), Payload::sendPayload(), NetObject::sendQueryNoid(), Noid::sendQueryNoid(), Session::sendSRSDES(), VNCRFBproto::setFormatAndEncodings(), World::setName(), User::setRtcp(), VNCRFBproto::setVisual32(), WObject::show(), Vicinity::show(), Render::showSolidList(), Render::stat(), statAdjust(), Vjc::stop(), VNCSockets::StringToIPAddr(), World::swap(), Universe::Universe(), WObject::updateLasting(), User::User(), VNCClientTextured::VNCInit(), Water::whenIntersect(), World::World(), Channel::~Channel(), and Session::~Session().
trace2()
void trace2 (int dbgmask, const char * s, ...)
Definition at line 89 of file log.cpp.
References DBG_FORCE, Global::debug, and g.
Referenced by Solid::display3D(), Render::lighting(), Render::solids(), Render::solidsOpaque(), Render::solidsTranslucid(), Render::specificInvisible(), Render::specificMobile(), and Render::specificStill().
warning()
void warning (const char * s, ...)
Definition at line 49 of file log.cpp.
References g, Global::gui, and Gui::writeMessage().
Referenced by Url::abs(), Face::animEyeBall(), Face::animEyeBrow(), Face::animEyeLid(), Face::animHead(), Face::animLip(), Face::animNose(), NetObject::buildNoidFromString(), changeKey(), Vrelet::click(), Button::commut(), Vicinity::computeDistance(), HttpThread::connection(), Vnc::connectServer(), Vnc::convert(), Channel::create(), NetObject::declareDeletion(), WObject::deleteReplica(), Gate::enter(), World::enter(), Vrelet::freeObject2D(), Channel::getGroup(), WObject::getObjectNameById(), Texture::httpReader(), Payload::incomingDelta(), Payload::incomingQuery(), Model::loader(), _3ds::loadFromFile(), Ase::loadFromFile(), Obj::loadFromFile(), Mirage::Mirage(), Channel::newChanStr(), Guide::parser(), Vnc::reconnectServer(), Vrelet::removeObject2D(), Img::resize(), Body::setJointPoint(), and Thing::Thing().
writelog()
FILE* writelog (const char * s, ...)
Definition at line 110 of file log.cpp.
References Env::dir(), Global::env, g, File::openFile(), and PATH_LEN.
Referenced by Session::stat(), and statSessionRTP().
Variable Documentation
e_bad_type
const char* e_bad_type = "bad type"
Definition at line 31 of file log.cpp.
e_exec
const char* e_exec = "can't exec"
Definition at line 28 of file log.cpp.
Referenced by Pdf::launch(), Ps::launch(), Midi::launch(), Mp3::launch(), Wav::launch(), Au::launch(), Mpeg::launch(), Ps::launcha2ps(), Browser::launchchrome(), Browser::launchmozilla(), Browser::launchnetscape(), Browser::launchsafari(), Modeler::start(), Audio::start(), Xterm::start(), Video::start(), Wb::start(), and Wget::start().
e_fork
const char* e_fork = "can't fork for"
Definition at line 27 of file log.cpp.
Referenced by Office::launch(), Pdf::launch(), Ps::launch(), Midi::launch(), Mp3::launch(), Wav::launch(), Au::launch(), Mpeg::launch(), Ps::launcha2ps(), Browser::launchchrome(), Browser::launchmozilla(), Browser::launchnetscape(), Browser::launchsafari(), Modeler::start(), Audio::start(), Xterm::start(), Video::start(), Wb::start(), and Wget::start().
e_not_implemented
const char* e_not_implemented = "not implemented"
Definition at line 30 of file log.cpp.
e_tool
const char* e_tool = "unknown tool"
Definition at line 29 of file log.cpp.
Referenced by Au::start(), Midi::start(), Mp3::start(), Mpeg::start(), Office::start(), Pdf::start(), Wav::start(), Browser::start(), and Ps::view().
infatal
bool infatal = false static
Definition at line 33 of file log.cpp.
Referenced by fatal().