VREng: src/vreng/sound.cpp File Reference
sound.cpp File Reference
#include "vreng.hpp"
#include "sound.hpp"
#include "pref.hpp"
Macros
#define DEVAUDIO "/dev/audio"
#define DEVAUDIOCTL "/dev/audioctl"
Functions
int decodeBase64 (const char *string, char *out)
Variables
int audioactive
Macro Definition Documentation
DEVAUDIO
#define DEVAUDIO "/dev/audio"
Definition at line 26 of file sound.cpp.
DEVAUDIOCTL
#define DEVAUDIOCTL "/dev/audioctl"
Definition at line 27 of file sound.cpp.
Function Documentation
decodeBase64()
int decodeBase64 (const char * string, char * out)
Definition at line 63 of file base64.cpp.
References base64digits, numbits, pin, pout, readchar(), size, and writebits().
Referenced by Sound::sound_thread().
Variable Documentation
audioactive
int audioactive extern
Definition at line 35 of file audio.cpp.
Referenced by Gate::enter(), Gui::gotoWorld(), Widgets::homeCB(), Sound::playSound(), Widgets::setAudioCB(), and Sound::sound_thread().