VREng: src/vreng/matvec.cpp File Reference
matvec.cpp File Reference
#include "vreng.hpp"
#include "matvec.hpp"
Functions
void IdM4 (M4 *a)
M4 MulM4 (M4 a, M4 b)
M4 ScaleM4 (float sx, float sy, float sz)
M4 RotateM4 (float t, int u)
M4 TranslateM4 (float x, float y, float z)
void MulM4V3 (V3 *a, const M4 *b, const V3 *c)
void MulM3V4 (float m[3][4], float v[4], float dest[3])
void MulM3M4 (float m1[3][4], float m2[4][4], float dest[3][4])
void M4toV16 (const M4 *mat, float *_vec)
Transforms a 4x4 matrix to a vec[16].
V3 newV3 (float x, float y, float z)
Create a new vector.
void clearV3 (V3 vec)
Clear a vector.
void copyV3 (V3 *to, V3 from)
Copies a vector into another.
float detV3 (V3 d, V3 v, V3 w)
Compute a determinant for a 3x3 matrix that's useful from time to time.
float calcV3 (V3 c, V3 e, V3 w, V3 v)
Compute an quantity that's used in the line/surface intersection.
Function Documentation
calcV3()
float calcV3 (V3 c, V3 e, V3 w, V3 v)
Compute an quantity that's used in the line/surface intersection.
Definition at line 156 of file matvec.cpp.
References V3::v.
Referenced by Vrelet::click().
clearV3()
void clearV3 (V3 vec)
Clear a vector.
Definition at line 134 of file matvec.cpp.
References V3::v.
Referenced by Door::close(), gotoXYZ(), WObject::moveUserToObject(), Door::open(), Icon::pin(), Web::pivot(), Ball::pull(), Icon::pull(), Sheet::pullNext(), Sheet::pullPrev(), Ball::push(), Icon::push(), Sheet::pushNext(), Sheet::pushPrev(), Sheet::Sheet(), Ball::shoot(), Ball::turn(), Icon::turn(), Sheet::turnNext(), Sheet::turnPrev(), and Ball::up().
copyV3()
void copyV3 (V3 * to, V3 from)
Copies a vector into another.
Definition at line 140 of file matvec.cpp.
References V3::v.
Referenced by Vrelet::addPoint(), Vrelet::newObject2D(), and Vrelet::processClient().
detV3()
float detV3 (V3 d, V3 v, V3 w)
Compute a determinant for a 3x3 matrix that's useful from time to time.
Definition at line 148 of file matvec.cpp.
References d, and V3::v.
Referenced by Board::click(), and Vrelet::click().
IdM4()
void IdM4 (M4 * a)
Definition at line 26 of file matvec.cpp.
References M4::m.
Referenced by Solid::parser(), RotateM4(), ScaleM4(), and TranslateM4().
M4toV16()
void M4toV16 (const M4 * mat, float * _vec)
Transforms a 4x4 matrix to a vec[16].
Definition at line 114 of file matvec.cpp.
References M4::m.
Referenced by Render::cameraPosition(), Render::map(), Board::render(), Vnc::render(), Vrelet::render(), Widget::render(), and Solid::vr2gl().
MulM3M4()
void MulM3M4 (float m1[3][4], float m2[4][4], float dest[3][4])
Definition at line 104 of file matvec.cpp.
Referenced by Guy::computeCurve().
MulM3V4()
void MulM3V4 (float m[3][4], float v[4], float dest[3])
Definition at line 94 of file matvec.cpp.
Referenced by Guy::computeCurve().
MulM4()
M4 MulM4 (M4 a, M4 b)
Definition at line 33 of file matvec.cpp.
References M4::m.
Referenced by Render::cameraPosition(), WObject::getSurfVecs(), Render::map(), WObject::update3D(), WObject::updateAll3D(), and WObject::updateCamera().
MulM4V3()
void MulM4V3 (V3 * a, const M4 * b, const V3 * c)
Definition at line 86 of file matvec.cpp.
References M4::m, and V3::v.
Referenced by Solid::getAbsoluteBB(), and WObject::getSurfVecs().
newV3()
V3 newV3 (float x, float y, float z)
Create a new vector.
Definition at line 123 of file matvec.cpp.
References V3::v.
Referenced by Board::click(), Vrelet::click(), User::defaults(), User::get_ray(), WObject::getSurfVecs(), Render::getVisiblePosition(), World::localGrid(), Solid::parser(), Vrelet::processClient(), resetForm(), Solid::resetRay(), setForm(), Solid::setRay(), User::setRayDirection(), Solid::Solid(), Solid::solidParser(), WObject::WObject(), and World::World().
RotateM4()
M4 RotateM4 (float t, int u)
Definition at line 58 of file matvec.cpp.
References IdM4(), and M4::m.
Referenced by Render::cameraPosition(), WObject::getSurfVecs(), Render::map(), WObject::update3D(), WObject::updateAll3D(), and WObject::updateCamera().
ScaleM4()
M4 ScaleM4 (float sx, float sy, float sz)
Definition at line 47 of file matvec.cpp.
References IdM4(), and M4::m.
TranslateM4()
M4 TranslateM4 (float x, float y, float z)
Definition at line 74 of file matvec.cpp.
References IdM4(), and M4::m.
Referenced by Render::cameraPosition(), Render::map(), WObject::update3D(), WObject::updateAll3D(), and WObject::updateCamera().