VREng: src/vreng/trigo.hpp File Reference
trigo.hpp File Reference
Macros
#define M_PI 3.14159265
#define M_2PI 6.28318530
#define M_PI_2 1.570795
#define M_PI_4 0.785395
#define M_2PI_5 1.256637
#define M_PI_180 0.017453
#define M_1_PI 0.31831
#define M_SQRT2 1.41421
#define M_SQRT1_2 0.70710
#define M_SQRT3 1.732051
#define M_SQRT3_2 0.866025
#define EPSILON 1e-6
#define DEG2RAD(x) ((float) (M_PI/180.)*(x))
#define RAD2DEG(x) ((float) (180./M_PI)*(x))
Functions
void initTrigo ()
Intialialize table of sinus per degree.
float deltaAngle (float a1, float a2)
Returns angular variation modulo 2PI.
int radian2degree (float)
Converts radian ro degree.
float Cos (double)
float Sin (double)
float Tan (double)
Macro Definition Documentation
DEG2RAD
#define DEG2RAD (x) ((float) (M_PI/180.)*(x))
Definition at line 53 of file trigo.hpp.
EPSILON
#define EPSILON 1e-6
Definition at line 51 of file trigo.hpp.
M_1_PI
#define M_1_PI 0.31831
Definition at line 39 of file trigo.hpp.
M_2PI
#define M_2PI 6.28318530
Definition at line 28 of file trigo.hpp.
M_2PI_5
#define M_2PI_5 1.256637
Definition at line 36 of file trigo.hpp.
M_PI
#define M_PI 3.14159265
Definition at line 25 of file trigo.hpp.
M_PI_180
#define M_PI_180 0.017453
Definition at line 37 of file trigo.hpp.
M_PI_2
#define M_PI_2 1.570795
Definition at line 31 of file trigo.hpp.
M_PI_4
#define M_PI_4 0.785395
Definition at line 34 of file trigo.hpp.
M_SQRT1_2
#define M_SQRT1_2 0.70710
Definition at line 45 of file trigo.hpp.
M_SQRT2
#define M_SQRT2 1.41421
Definition at line 42 of file trigo.hpp.
M_SQRT3
#define M_SQRT3 1.732051
Definition at line 48 of file trigo.hpp.
M_SQRT3_2
#define M_SQRT3_2 0.866025
Definition at line 49 of file trigo.hpp.
RAD2DEG
#define RAD2DEG (x) ((float) (180./M_PI)*(x))
Definition at line 54 of file trigo.hpp.
Function Documentation
Cos()
float Cos (double)
Definition at line 68 of file trigo.cpp.
References M_PI, and Sin().
Referenced by Bullet::Bullet(), Clock::changePermanent(), Ball::changePosition(), Icon::changePosition(), User::changePositionOneDir(), Dart::Dart(), Vrelet::draw(), gotoXYZ(), Icon::Icon(), Cart::leaveIntoWorld(), WObject::moveUserToObject(), Icon::pin(), Ball::pull(), Icon::pull(), Ball::push(), Icon::push(), Stars::rotate(), Ball::shoot(), Tan(), Ball::whenIntersect(), and Thing::whenIntersect().
deltaAngle()
float deltaAngle (float a1, float a2)
Returns angular variation modulo 2PI.
Definition at line 29 of file trigo.cpp.
References M_2PI.
Referenced by Book::approach(), Door::close(), gotoXYZ(), WObject::moveUserToObject(), Door::open(), Sheet::pullNext(), Sheet::pullPrev(), Sheet::pushNext(), Sheet::pushPrev(), Sheet::turnNext(), Sheet::turnPrev(), Sheet::updateTime(), Door::updateTime(), and Guide::whenIntersect().
initTrigo()
void initTrigo ()
Intialialize table of sinus per degree.
Definition at line 55 of file trigo.cpp.
References d, M_2PI, and sintab.
Referenced by Global::startCB().
radian2degree()
int radian2degree (float r)
Converts radian ro degree.
Converts radian ro degree.
Definition at line 42 of file trigo.cpp.
References d, and M_2PI.
Referenced by Sin().
Sin()
float Sin (double)
Definition at line 63 of file trigo.cpp.
References radian2degree(), and sintab.
Referenced by Bullet::Bullet(), Ball::changePosition(), Icon::changePosition(), User::changePositionOneDir(), Cos(), Dart::Dart(), Vrelet::draw(), Water::draw(), gotoXYZ(), Icon::Icon(), Cart::leaveIntoWorld(), WObject::moveUserToObject(), Icon::pin(), Ball::pull(), Icon::pull(), Ball::push(), Icon::push(), Stars::rotate(), Ball::shoot(), Tan(), Ball::whenIntersect(), and Thing::whenIntersect().
Tan()
float Tan (double)
Definition at line 73 of file trigo.cpp.
References Cos(), and Sin().