VREng: src/vreng/trigo.cpp File Reference
trigo.cpp File Reference
#include "vreng.hpp"
Functions
float deltaAngle (float a1, float a2)
Returns angular variation modulo 2PI.
int radian2degree (float r)
Converts radian to degree.
void initTrigo ()
Intialialize table of sinus per degree.
float Sin (double r)
float Cos (double r)
float Tan (double r)
Variables
static float sintab [360]
Function Documentation
Cos()
float Cos (double r)
Definition at line 68 of file trigo.cpp.
References M_PI, and Sin().
Referenced by Bullet::Bullet(), Clock::changePermanent(), Ball::changePosition(), Icon::changePosition(), User::changePositionOneDir(), Dart::Dart(), Vrelet::draw(), gotoXYZ(), Icon::Icon(), Cart::leaveIntoWorld(), WObject::moveUserToObject(), Icon::pin(), Ball::pull(), Icon::pull(), Ball::push(), Icon::push(), Stars::rotate(), Ball::shoot(), Tan(), Ball::whenIntersect(), and Thing::whenIntersect().
deltaAngle()
float deltaAngle (float a1, float a2)
Returns angular variation modulo 2PI.
Definition at line 29 of file trigo.cpp.
References M_2PI.
Referenced by Book::approach(), Door::close(), gotoXYZ(), WObject::moveUserToObject(), Door::open(), Sheet::pullNext(), Sheet::pullPrev(), Sheet::pushNext(), Sheet::pushPrev(), Sheet::turnNext(), Sheet::turnPrev(), Sheet::updateTime(), Door::updateTime(), and Guide::whenIntersect().
initTrigo()
void initTrigo ()
Intialialize table of sinus per degree.
Definition at line 55 of file trigo.cpp.
References d, M_2PI, and sintab.
Referenced by Global::startCB().
radian2degree()
int radian2degree (float r)
Converts radian to degree.
Converts radian ro degree.
Definition at line 42 of file trigo.cpp.
References d, and M_2PI.
Referenced by Sin().
Sin()
float Sin (double r)
Definition at line 63 of file trigo.cpp.
References radian2degree(), and sintab.
Referenced by Bullet::Bullet(), Ball::changePosition(), Icon::changePosition(), User::changePositionOneDir(), Cos(), Dart::Dart(), Vrelet::draw(), Water::draw(), gotoXYZ(), Icon::Icon(), Cart::leaveIntoWorld(), WObject::moveUserToObject(), Icon::pin(), Ball::pull(), Icon::pull(), Ball::push(), Icon::push(), Stars::rotate(), Ball::shoot(), Tan(), Ball::whenIntersect(), and Thing::whenIntersect().
Tan()
float Tan (double r)
Definition at line 73 of file trigo.cpp.
References Cos(), and Sin().
Variable Documentation
sintab
float sintab[360] static
Definition at line 25 of file trigo.cpp.
Referenced by initTrigo(), and Sin().