VREng: src/sys/nsl.hpp File Reference
nsl.hpp File Reference
Functions
struct hostent * my_getipnodebyname (const char *hostname, int af)
struct hostent * my_getipnodebyaddr (const char *hostaddr, int af)
struct hostent * my_gethostbyname (const char *hostname, int af)
struct hostent * my_gethostbyaddr (const char *hostaddr, int af)
struct hostent * my_gethostbyname_r (const char *hostname, int af)
struct hostent * my_gethostbyaddr_r (const char *hostaddr, int af)
struct servent * my_getservbyname (const char *servname)
struct servent * my_getservbyname_r (const char *servname)
void my_free_hostent (struct hostent *hp)
const char * my_inet_ntop (int af, const void *addr)
inet_ntop, inet_ntoa
const char * inet4_ntop (const void *addr)
const char * inet6_ntop (const void *addr)
int my_inet_pton (int af, const char *name, void *addr)
inet_pton, inet_addr
int inet4_pton (const char *name, void *addr)
int inet6_pton (const char *name, void *addr)
Function Documentation
inet4_ntop()
const char* inet4_ntop (const void * addr)
Definition at line 216 of file nsl.cpp.
References my_inet_ntop().
Referenced by Android::connectToBapServer(), Payload::incomingDelete(), Payload::incomingDelta(), Payload::incomingQuery(), Channel::initReflector(), NetObject::sendCreate(), NetObject::sendDelete(), NetObject::sendDeleteNoid(), Noid::sendDeleteNoid(), NetObject::sendQueryNoid(), and Noid::sendQueryNoid().
inet4_pton()
int inet4_pton (const char * name, void * addr)
Definition at line 221 of file nsl.cpp.
References my_inet_pton().
Referenced by Channel::create(), and Android::initReceiver().
inet6_ntop()
const char* inet6_ntop (const void * addr)
Definition at line 226 of file nsl.cpp.
References AF_INET6, and my_inet_ntop().
inet6_pton()
int inet6_pton (const char * name, void * addr)
Definition at line 231 of file nsl.cpp.
References AF_INET6, and my_inet_pton().
my_free_hostent()
void my_free_hostent (struct hostent * hp)
Definition at line 184 of file nsl.cpp.
Referenced by HttpThread::connection(), Vac::connectThread(), Android::connectToBapServer(), Rtp::getRtcpEmail(), Channel::initReflector(), Channel::naming(), and HttpThread::resolver().
my_gethostbyaddr()
struct hostent* my_gethostbyaddr (const char * hostaddr, int af)
HAVE_GETIPNODEBYADDR
Definition at line 106 of file nsl.cpp.
References my_getipnodebyaddr().
my_gethostbyaddr_r()
struct hostent* my_gethostbyaddr_r (const char * hostaddr, int af)
HAVE_GETIPNODEBYADDR
HAVE_GETHOSTBYADDR_R
Definition at line 121 of file nsl.cpp.
References my_getipnodebyaddr().
my_gethostbyname()
struct hostent* my_gethostbyname (const char * hostname, int af)
HAVE_GETIPNODEBYNAME
Definition at line 45 of file nsl.cpp.
References my_getipnodebyname().
Referenced by HttpThread::connection(), Vac::connectThread(), Android::connectToBapServer(), Channel::initReflector(), Channel::naming(), VNCSockets::StringToIPAddr(), and VjcSocket::VjcSocket().
my_gethostbyname_r()
struct hostent* my_gethostbyname_r (const char * hostname, int af)
HAVE_GETIPNODEBYNAME
HAVE_GETHOSTBYADDR_R
Definition at line 61 of file nsl.cpp.
References my_getipnodebyname().
Referenced by Rtp::getRtcpEmail(), and HttpThread::resolver().
my_getipnodebyaddr()
struct hostent* my_getipnodebyaddr (const char * hostaddr, int af)
HAVE_GETIPNODEBYADDR
Definition at line 93 of file nsl.cpp.
Referenced by my_gethostbyaddr(), and my_gethostbyaddr_r().
my_getipnodebyname()
struct hostent* my_getipnodebyname (const char * hostname, int af)
HAVE_GETIPNODEBYNAME
Definition at line 33 of file nsl.cpp.
Referenced by my_gethostbyname(), and my_gethostbyname_r().
my_getservbyname()
struct servent* my_getservbyname (const char * servname)
Definition at line 151 of file nsl.cpp.
my_getservbyname_r()
struct servent* my_getservbyname_r (const char * servname)
HAVE_GETSERVBYNAME_R
Definition at line 161 of file nsl.cpp.
my_inet_ntop()
const char* my_inet_ntop (int af, const void * addr)
inet_ntop, inet_ntoa
Definition at line 194 of file nsl.cpp.
References MAXHOSTNAMELEN.
Referenced by inet4_ntop(), and inet6_ntop().
my_inet_pton()
int my_inet_pton (int af, const char * name, void * addr)
inet_pton, inet_addr
Definition at line 206 of file nsl.cpp.
References inet_pton().
Referenced by inet4_pton(), and inet6_pton().