VREng: src/vreng/vector3.hpp File Reference
vector3.hpp File Reference
Classes
class Vector3
Vector3 class.
class Matrix3
Matrix3 class.
Functions
float operator* (const Vector3 &a, const Vector3 &b)
Vector3 operator* (const Vector3 &a, float b)
Vector3 operator* (float b, const Vector3 &a)
Vector3 & operator*= (Vector3 &a, float b)
Vector3 operator^ (const Vector3 &a, const Vector3 &b)
Vector3 operator+ (const Vector3 &pt1, const Vector3 &pt2)
Vector3 operator- (const Vector3 &pt1, const Vector3 &pt2)
Vector3 operator* (float *m, Vector3 &v)
Function Documentation
operator*() [1/4]
float operator* (const Vector3 & a, const Vector3 & b) inline
Definition at line 118 of file vector3.hpp.
References Vector3::dotProduct().
operator*() [2/4]
Vector3 operator* (const Vector3 & a, float b) inline
Definition at line 121 of file vector3.hpp.
References Vector3::x, Vector3::y, and Vector3::z.
operator*() [3/4]
Vector3 operator* (float * m, Vector3 & v) inline
Definition at line 308 of file vector3.hpp.
References Vector3::x, Vector3::y, and Vector3::z.
operator*() [4/4]
Vector3 operator* (float b, const Vector3 & a) inline
Definition at line 124 of file vector3.hpp.
References Vector3::x, Vector3::y, and Vector3::z.
operator*=()
Vector3& operator*= (Vector3 & a, float b) inline
Definition at line 127 of file vector3.hpp.
References Vector3::scale().
operator+()
Vector3 operator+ (const Vector3 & pt1, const Vector3 & pt2) inline
Definition at line 293 of file vector3.hpp.
References Vector3::add().
operator-()
Vector3 operator- (const Vector3 & pt1, const Vector3 & pt2) inline
Definition at line 300 of file vector3.hpp.
References Vector3::subtract().
operator^()
Vector3 operator^ (const Vector3 & a, const Vector3 & b) inline
Definition at line 131 of file vector3.hpp.
References Vector3::crossProduct().