VREng: src/sys/str.hpp File Reference
str.hpp File Reference
Functions
int mystrcasecmp (const char *s1, const char *s2)
int stringcmp (const char *s1, const char *s2)
Function Documentation
mystrcasecmp()
int mystrcasecmp (const char * s1, const char * s2)
Definition at line 28 of file str.cpp.
References mylower().
Referenced by OClass::getOClass().
stringcmp()
int stringcmp (const char * s1, const char * s2)
Definition at line 148 of file str.cpp.
Referenced by Url::abs(), World::checkPersistObjects(), Clip::Clip(), Cache::curl(), Music::format(), Format::getExt(), Solid::getFramesNumber(), Hairs::httpReader(), Icon::Icon(), Pref::initEnvPrefs(), Body::loadBodyParts(), Music::Music(), Web::open_cb(), Parse::parseAttributes(), Parse::parseChannel(), Parse::parseColor(), Parse::parseFloat(), Solid::parseFrame(), Parse::parseInt(), Parse::parseLine(), Parse::parsePath(), Parse::parsePosition(), Parse::parseQuotedString(), Accessory::parser(), Android::parser(), Animator::parser(), AnimX3d::parser(), Aoi::parser(), Bgcolor::parser(), Book::parser(), Bumper::parser(), Button::parser(), Clip::parser(), Clock::parser(), Cloth::parser(), Cloud::parser(), Doc::parser(), Door::parser(), Dress::parser(), Escalator::parser(), Fire::parser(), Firework::parser(), Fountain::parser(), Fractal::parser(), Ftp::parser(), Gate::parser(), Guide::parser(), Guy::parser(), Hairs::parser(), Hat::parser(), Head::parser(), Host::parser(), Icon::parser(), Lift::parser(), Light::parser(), Mech::parser(), Mirage::parser(), Model::parser(), Movie::parser(), Music::parser(), Particle::parser(), Rain::parser(), River::parser(), Slider::parser(), Smoke::parser(), Snow::parser(), Spiral::parser(), Stair::parser(), Stars::parser(), Step::parser(), Sun::parser(), Terrain::parser(), Text::parser(), Thunder::parser(), Travelator::parser(), Vjc::parser(), Vnc::parser(), Vrelet::parser(), Walls::parser(), Water::parser(), Waterfall::parser(), Web::parser(), Wind::parser(), Wings::parser(), Url::parser(), Parse::parseRotation(), Solid::parseShape(), Parse::parseString(), Parse::parseTranslation(), Parse::parseUInt16(), Parse::parseUInt8(), Parse::parseUrl(), Parse::parseVector3f(), Parse::parseVector3fv(), Bap::readFrame(), Wget::start(), and Transform::Transform().