VREng: src/sys/md5.cpp File Reference
md5.cpp File Reference
#include "sysdep.hpp"
#include "md5.hpp"
Macros
#define MD5_BIG_ENDIAN 0
#define MD5_LITTLE_ENDIAN 1
#define SHIFT(X, s) (((X) << (s)) | ((X) >> (32 - (s))))
#define F(X, Y, Z) (((X) & (Y)) | ((~X) & (Z)))
#define G(X, Y, Z) (((X) & (Z)) | ((Y) & (~Z)))
#define H(X, Y, Z) ((X) ^ (Y) ^ (Z))
#define I(X, Y, Z) ((Y) ^ ((X) | (~Z)))
#define ROUND1(a, b, c, d, k, s, i)
#define ROUND2(a, b, c, d, k, s, i)
#define ROUND3(a, b, c, d, k, s, i)
#define ROUND4(a, b, c, d, k, s, i)
#define Sa 7
#define Sb 12
#define Sc 17
#define Sd 22
#define Se 5
#define Sf 9
#define Sg 14
#define Sh 20
#define Si 4
#define Sj 11
#define Sk 16
#define Sl 23
#define Sm 6
#define Sn 10
#define So 15
#define Sp 21
#define MD5_A0 0x67452301
#define MD5_B0 0xefcdab89
#define MD5_C0 0x98badcfe
#define MD5_D0 0x10325476
Functions
static void md5_calc (uint8_t *, md5_ctxt *)
void md5_init (md5_ctxt *ctxt)
void md5_loop (md5_ctxt *ctxt, uint8_t *input, uint32_t len)
void md5_pad (md5_ctxt *ctxt)
void md5_result (uint8_t *digest, md5_ctxt *ctxt)
Variables
static const uint32_t T [65]
static const uint8_t md5_paddat [MD5_BUFLEN]
Macro Definition Documentation
F
#define F (X, Y, Z) (((X) & (Y)) | ((~X) & (Z)))
Definition at line 65 of file md5.cpp.
G
#define G (X, Y, Z) (((X) & (Z)) | ((Y) & (~Z)))
Definition at line 66 of file md5.cpp.
H
#define H (X, Y, Z) ((X) ^ (Y) ^ (Z))
Definition at line 67 of file md5.cpp.
I
#define I (X, Y, Z) ((Y) ^ ((X) | (~Z)))
Definition at line 68 of file md5.cpp.
MD5_A0
#define MD5_A0 0x67452301
Definition at line 114 of file md5.cpp.
MD5_B0
#define MD5_B0 0xefcdab89
Definition at line 115 of file md5.cpp.
MD5_BIG_ENDIAN
#define MD5_BIG_ENDIAN 0
Definition at line 59 of file md5.cpp.
MD5_C0
#define MD5_C0 0x98badcfe
Definition at line 116 of file md5.cpp.
MD5_D0
#define MD5_D0 0x10325476
Definition at line 117 of file md5.cpp.
MD5_LITTLE_ENDIAN
#define MD5_LITTLE_ENDIAN 1
Definition at line 60 of file md5.cpp.
ROUND1
#define ROUND1 (a, b, c, d, k, s, i)
Value:
  { \
  (a) = (a) + F((b), (c), (d)) + X[(k)] + T[(i)]; \
  (a) = SHIFT((a), (s)); \
  (a) = (b) + (a); \
}
Definition at line 70 of file md5.cpp.
ROUND2
#define ROUND2 (a, b, c, d, k, s, i)
Value:
  { \
  (a) = (a) + G((b), (c), (d)) + X[(k)] + T[(i)]; \
  (a) = SHIFT((a), (s)); \
  (a) = (b) + (a); \
}
Definition at line 76 of file md5.cpp.
ROUND3
#define ROUND3 (a, b, c, d, k, s, i)
Value:
  { \
  (a) = (a) + H((b), (c), (d)) + X[(k)] + T[(i)]; \
  (a) = SHIFT((a), (s)); \
  (a) = (b) + (a); \
}
Definition at line 82 of file md5.cpp.
ROUND4
#define ROUND4 (a, b, c, d, k, s, i)
Value:
  { \
  (a) = (a) + I((b), (c), (d)) + X[(k)] + T[(i)]; \
  (a) = SHIFT((a), (s)); \
  (a) = (b) + (a); \
}
Definition at line 88 of file md5.cpp.
Sa
#define Sa 7
Definition at line 94 of file md5.cpp.
Sb
#define Sb 12
Definition at line 95 of file md5.cpp.
Sc
#define Sc 17
Definition at line 96 of file md5.cpp.
Sd
#define Sd 22
Definition at line 97 of file md5.cpp.
Se
#define Se 5
Definition at line 99 of file md5.cpp.
Sf
#define Sf 9
Definition at line 100 of file md5.cpp.
Sg
#define Sg 14
Definition at line 101 of file md5.cpp.
Sh
#define Sh 20
Definition at line 102 of file md5.cpp.
SHIFT
#define SHIFT (X, s) (((X) << (s)) | ((X) >> (32 - (s))))
Definition at line 63 of file md5.cpp.
Si
#define Si 4
Definition at line 104 of file md5.cpp.
Sj
#define Sj 11
Definition at line 105 of file md5.cpp.
Sk
#define Sk 16
Definition at line 106 of file md5.cpp.
Sl
#define Sl 23
Definition at line 107 of file md5.cpp.
Sm
#define Sm 6
Definition at line 109 of file md5.cpp.
Sn
#define Sn 10
Definition at line 110 of file md5.cpp.
So
#define So 15
Definition at line 111 of file md5.cpp.
Sp
#define Sp 21
Definition at line 112 of file md5.cpp.
Function Documentation
md5_calc()
static void md5_calc (uint8_t * b64, md5_ctxt * ctxt) static
Definition at line 251 of file md5.cpp.
References A, B, ROUND1, ROUND2, ROUND3, ROUND4, Sa, Sb, Sc, Sd, Se, Sf, Sg, Sh, Si, Sj, Sk, Sl, Sm, Sn, So, and Sp.
Referenced by md5_loop(), and md5_pad().
md5_init()
void md5_init (md5_ctxt * ctxt)
Definition at line 156 of file md5.cpp.
References MD5_A0, MD5_B0, md5_ctxt::md5_buf, MD5_C0, MD5_D0, and md5_ctxt::md5_i.
md5_loop()
void md5_loop (md5_ctxt * ctxt, uint8_t * input, uint32_t len)
Definition at line 167 of file md5.cpp.
References md5_ctxt::md5_buf, MD5_BUFLEN, md5_calc(), and md5_ctxt::md5_i.
md5_pad()
void md5_pad (md5_ctxt * ctxt)
Definition at line 192 of file md5.cpp.
References md5_ctxt::md5_buf, MD5_BUFLEN, md5_calc(), md5_ctxt::md5_i, and md5_paddat.
md5_result()
void md5_result (uint8_t * digest, md5_ctxt * ctxt)
Definition at line 229 of file md5.cpp.
Variable Documentation
md5_paddat
const uint8_t md5_paddat[MD5_BUFLEN] static
Initial value:
= {
  0x80, 0,  0,  0,  0,  0,  0,  0,
  0,  0,  0,  0,  0,  0,  0,  0,
  0,  0,  0,  0,  0,  0,  0,  0,
  0,  0,  0,  0,  0,  0,  0,  0,
  0,  0,  0,  0,  0,  0,  0,  0,
  0,  0,  0,  0,  0,  0,  0,  0,
  0,  0,  0,  0,  0,  0,  0,  0,
  0,  0,  0,  0,  0,  0,  0,  0,
}
Definition at line 143 of file md5.cpp.
Referenced by md5_pad().
T
const uint32_t T[65] static
Initial value:
= {
  0,
  0xd76aa478,   0xe8c7b756, 0x242070db, 0xc1bdceee,
  0xf57c0faf, 0x4787c62a,   0xa8304613, 0xfd469501,
  0x698098d8, 0x8b44f7af, 0xffff5bb1, 0x895cd7be,
  0x6b901122,   0xfd987193,   0xa679438e, 0x49b40821,
  0xf61e2562, 0xc040b340,   0x265e5a51,   0xe9b6c7aa,
  0xd62f105d, 0x2441453,  0xd8a1e681, 0xe7d3fbc8,
  0x21e1cde6, 0xc33707d6,   0xf4d50d87,   0x455a14ed,
  0xa9e3e905, 0xfcefa3f8,   0x676f02d9,   0x8d2a4c8a,
  0xfffa3942, 0x8771f681,   0x6d9d6122,   0xfde5380c,
  0xa4beea44,   0x4bdecfa9,   0xf6bb4b60,   0xbebfbc70,
  0x289b7ec6,   0xeaa127fa,   0xd4ef3085, 0x4881d05,
  0xd9d4d039,   0xe6db99e5,   0x1fa27cf8,   0xc4ac5665,
  0xf4292244,   0x432aff97,   0xab9423a7,   0xfc93a039,
  0x655b59c3,   0x8f0ccc92,   0xffeff47d,   0x85845dd1,
  0x6fa87e4f,   0xfe2ce6e0,   0xa3014314,   0x4e0811a1,
  0xf7537e82,   0xbd3af235,   0x2ad7d2bb,   0xeb86d391,
}
Definition at line 120 of file md5.cpp.