VREng: src/sys/windoze.hpp File Reference
windoze.hpp File Reference
#include <winsock2.h>
#include <time.h>
#include <sys\timeb.h>
#include <resolv.h>
#include <io.h>
#include <arpa\nameser.h>
Macros
#define pid_t int
#define open _open
#define close _close
#define read _read
#define write _write
#define access _access
#define lseek _lseek
#define getpid _getpid
#define srandom srand
#define random rand
#define strncasecmp _strnicmp
#define strcasecmp _stricmp
#define drand48() ((float)rand()/RAND_MAX)
#define F_OK 0
#define IOSBINARY ios::binary
#define XtPointer int
Functions
int gettimeofday (struct timeval *tv, int *tz)
void initDll (void)
Macro Definition Documentation
access
#define access _access
Definition at line 37 of file windoze.hpp.
close
#define close _close
Definition at line 34 of file windoze.hpp.
drand48
#define drand48 () ((float)rand()/RAND_MAX)
Definition at line 46 of file windoze.hpp.
F_OK
#define F_OK 0
Definition at line 49 of file windoze.hpp.
getpid
#define getpid _getpid
Definition at line 39 of file windoze.hpp.
IOSBINARY
#define IOSBINARY ios::binary
Definition at line 55 of file windoze.hpp.
lseek
#define lseek _lseek
Definition at line 38 of file windoze.hpp.
open
#define open _open
Definition at line 33 of file windoze.hpp.
pid_t
#define pid_t int
Definition at line 32 of file windoze.hpp.
random
#define random rand
Definition at line 41 of file windoze.hpp.
read
#define read _read
Definition at line 35 of file windoze.hpp.
srandom
#define srandom srand
Definition at line 40 of file windoze.hpp.
strcasecmp
#define strcasecmp _stricmp
Definition at line 43 of file windoze.hpp.
strncasecmp
#define strncasecmp _strnicmp
Definition at line 42 of file windoze.hpp.
write
#define write _write
Definition at line 36 of file windoze.hpp.
XtPointer
#define XtPointer int
Definition at line 61 of file windoze.hpp.
Function Documentation
gettimeofday()
int gettimeofday (struct timeval * tv, int * tz)
Referenced by Cloud::build(), Session::buildRtpHeader(), Session::buildSR(), Widgets::callAction(), Movie::changePermanent(), Times::delta(), Pitch::doAction(), Thunder::draw(), Fire::draw(), Smoke::draw(), WObject::enableImposedMovement(), WObject::enablePermanentMovement(), Times::fTime(), Particle::inits(), Navig::keyPressCB(), Motion::move(), NetTimeout(), objectActionCB(), Widgets::processKey(), random32(), Thunder::render(), NetProperty::resetDates(), Widgets::setKey(), ProfileTime::start(), statAdjust(), ProfileTime::stop(), Particle::timedelta(), TimeSensor::TimeSensor(), and TimeSensor::updateFraction().
initDll()
void initDll (void)