VREng: src/sys/random.cpp File Reference
random.cpp File Reference
#include "sysdep.hpp"
#include "md5.hpp"
Functions
static uint32_t md_32 (char *string, int length)
unsigned int random32 (int type)
Function Documentation
md_32()
static uint32_t md_32 (char * string, int length) static
Definition at line 30 of file random.cpp.
References MD5_CTX, MD5Final, MD5Init, and MD5Update.
Referenced by random32().
random32()
unsigned int random32 (int type)
Definition at line 54 of file random.cpp.
References getpid, gettimeofday(), md_32(), pid, and pid_t.
Referenced by Rtp::createSsrc().