VREng: src/sys/thread.hpp File Reference
thread.hpp File Reference
Typedefs
typedef int Vpthread_t
typedef int Vpthread_cond_t
typedef int Vpthread_mutex_t
Functions
void initMutex (Vpthread_mutex_t *pmutex)
void lockMutex (Vpthread_mutex_t *pmutex)
void unlockMutex (Vpthread_mutex_t *pmutex)
Typedef Documentation
Vpthread_cond_t
typedef int Vpthread_cond_t
Definition at line 30 of file thread.hpp.
Vpthread_mutex_t
typedef int Vpthread_mutex_t
Definition at line 31 of file thread.hpp.
Vpthread_t
typedef int Vpthread_t
Definition at line 29 of file thread.hpp.
Function Documentation
initMutex()
void initMutex (Vpthread_mutex_t * pmutex)
Definition at line 25 of file thread.cpp.
Referenced by HttpThread::init(), and Texture::initCache().
lockMutex()
void lockMutex (Vpthread_mutex_t * pmutex)
Definition at line 32 of file thread.cpp.
Referenced by HttpThread::begin(), HttpThread::end(), Texture::httpReader(), HttpThread::putfifo(), and Texture::update().
unlockMutex()
void unlockMutex (Vpthread_mutex_t * pmutex)
Definition at line 39 of file thread.cpp.
Referenced by HttpThread::begin(), HttpThread::end(), Texture::httpReader(), HttpThread::putfifo(), and Texture::update().