VREng: src/vreng/stat.hpp File Reference
stat.hpp File Reference
Functions
void statLog ()
void statTimings ()
void statNetwork ()
void statSendPacket (int len)
uint32_t getSentPackets ()
void setLostPackets (int lost)
void statSendRTP (int len)
void statSendRTCP (int len)
void statReceivePacket (int len)
void statSessionRTP (class Session *session)
void statAdjust ()
Variables
uint32_t pkts_sent
uint32_t sum_pkts_lost
Function Documentation
getSentPackets()
uint32_t getSentPackets ()
Definition at line 69 of file stat.cpp.
References pkts_sent.
Referenced by Payload::sendPayload().
setLostPackets()
void setLostPackets (int lost)
Definition at line 74 of file stat.cpp.
References sum_pkts_lost.
Referenced by Session::deleteSourceBySsrc().
statAdjust()
void statAdjust ()
Definition at line 106 of file stat.cpp.
References bytes_recvd, bytes_sent, d, DBG_NET, Times::diffDates(), gettimeofday(), kbps_recvd, kbps_sent, and trace().
statLog()
void statLog ()
Definition at line 195 of file stat.cpp.
References closelog(), flog, and printlog().
Referenced by Global::printStats().
statNetwork()
void statNetwork ()
Definition at line 155 of file stat.cpp.
References d, Source::dumpAll(), g, Times::net, pkt_max, pkt_min, ProfileTime::stop(), sum_bytes_recvd, sum_bytes_rtcp_sent, sum_bytes_rtp_sent, sum_bytes_sent, sum_pkts_lost, sum_pkts_recvd, sum_pkts_rtcp_sent, sum_pkts_rtp_sent, sum_pkts_sent, and Global::times.
Referenced by Global::printStats().
statReceivePacket()
void statReceivePacket (int len)
Definition at line 95 of file stat.cpp.
References bytes_recvd, MAX, MIN, pkt_max, pkt_min, pkts_recvd, sum_bytes_recvd, and sum_pkts_recvd.
Referenced by Payload::recvPayload().
statSendPacket()
void statSendPacket (int len)
Definition at line 59 of file stat.cpp.
References bytes_sent, MAX, MIN, pkt_max, pkt_min, pkts_sent, sum_bytes_sent, and sum_pkts_sent.
Referenced by Rtp::sendPacket().
statSendRTCP()
void statSendRTCP (int len)
Definition at line 87 of file stat.cpp.
References bytes_rtcp_sent, pkts_rtcp_sent, sum_bytes_rtcp_sent, and sum_pkts_rtcp_sent.
Referenced by Session::sendRTCPPacket(), and Session::sendSRSDES().
statSendRTP()
void statSendRTP (int len)
Definition at line 79 of file stat.cpp.
References bytes_rtp_sent, pkts_rtp_sent, sum_bytes_rtp_sent, and sum_pkts_rtp_sent.
Referenced by Payload::sendPayload().
statSessionRTP()
void statSessionRTP (class Session * session)
Definition at line 123 of file stat.cpp.
References flog, Session::stat(), and writelog().
statTimings()
void statTimings ()
Definition at line 129 of file stat.cpp.
References ProfileTime::cumul_time, d, g, Gui::getCycles(), Times::getRate(), Global::gui, Times::idle, Times::image, Times::init, Times::mysql, Times::net, Times::object, Times::render, Times::simul, ProfileTime::stop(), and Global::times.
Referenced by Global::printStats().
Variable Documentation
pkts_sent
uint32_t pkts_sent extern
Definition at line 30 of file stat.cpp.
Referenced by getSentPackets(), and statSendPacket().
sum_pkts_lost
uint32_t sum_pkts_lost extern
Definition at line 31 of file stat.cpp.
Referenced by setLostPackets(), and statNetwork().