VREng: src/gui/message.cpp File Reference
message.cpp File Reference
#include "vreng.hpp"
#include "widgets.hpp"
#include "scene.hpp"
#include "navig.hpp"
#include "theme.hpp"
#include "message.hpp"
#include "wobject.hpp"
#include "user.hpp"
#include "render.hpp"
#include "cache.hpp"
#include "pref.hpp"
#include "icon.hpp"
#include <iostream>
Functions
static bool string2Coord (const char *positions, float &x, float &y, float &z, float &az)
static void moveSatCamera (char *posbuf)
Function Documentation
moveSatCamera()
static void moveSatCamera (char * posbuf) static
Definition at line 196 of file message.cpp.
References g, Global::render, Render::setCameraScissor(), and string2Coord().
Referenced by Messages::convertTextToLink().
string2Coord()
static bool string2Coord (const char * positions, float & x, float & y, float & z, float & az) static
Definition at line 173 of file message.cpp.
Referenced by moveSatCamera(), and Messages::postRequest().