VREng: src/gui/panels.cpp File Reference
panels.cpp File Reference
#include "vreng.hpp"
#include "widgets.hpp"
#include "panels.hpp"
#include "theme.hpp"
#include "palette.hpp"
#include "navig.hpp"
#include "scene.hpp"
#include "joystick.hpp"
#include "pitch.hpp"
#include "capture.hpp"
#include "user.hpp"
#include "axis.hpp"
#include "grid.hpp"
#include "world.hpp"
#include "channel.hpp"
#include "message.hpp"
Functions
static void toggleHudCB (Widgets *)
static void toggleAxisCB (Widgets *)
static void toggleGridCB (Widgets *, int flag)
static void sandboxCB (Widgets *)
Function Documentation
sandboxCB()
static void sandboxCB (Widgets *) static
Definition at line 82 of file panels.cpp.
References Channel::current(), World::current(), World::enter(), and World::quit().
Referenced by Panels::Panels().
toggleAxisCB()
static void toggleAxisCB (Widgets *) static
Definition at line 54 of file panels.cpp.
References Axis::axis(), and Axis::toggle().
Referenced by Panels::Panels().
toggleGridCB()
static void toggleGridCB (Widgets * , int flag) static
Definition at line 56 of file panels.cpp.
References Grid::grid(), Grid::toggleGrid(), Grid::toggleGrid3d(), and Grid::toggleOverlap().
Referenced by Panels::Panels().
toggleHudCB()
static void toggleHudCB (Widgets *) static
Definition at line 52 of file panels.cpp.
References g, Gui::getScene(), Global::gui, and Scene::toggleHud().
Referenced by Panels::Panels().