VREng: src/wo/clip.cpp File Reference
clip.cpp File Reference
#include "vreng.hpp"
#include "clip.hpp"
#include "world.hpp"
#include "channel.hpp"
#include "cache.hpp"
#include "audio.hpp"
#include "video.hpp"
#include "mpeg.hpp"
Functions
void postCgi (const char *cmd)
Variables
static const char * RTP_URL = "http://avods.enst.fr/"
static const char * PLAY_CGI = "rtpplay.cgi"
static const char * STOP_CGI = "rtpstop.cgi"
static const char * PAUSE_CGI = "rtppause.cgi"
static const char * CONT_CGI = "rtpcont.cgi"
Function Documentation
postCgi()
void postCgi (const char * cmd)
Definition at line 97 of file clip.cpp.
References Cache::download().
Referenced by Clip::contRtp(), Clip::pauseRtp(), Clip::startRtp(), and Clip::stopRtp().
Variable Documentation
CONT_CGI
const char* CONT_CGI = "rtpcont.cgi" static
Definition at line 38 of file clip.cpp.
Referenced by Clip::contRtp().
PAUSE_CGI
const char* PAUSE_CGI = "rtppause.cgi" static
Definition at line 37 of file clip.cpp.
Referenced by Clip::pauseRtp().
PLAY_CGI
const char* PLAY_CGI = "rtpplay.cgi" static
Definition at line 35 of file clip.cpp.
Referenced by Clip::startRtp().
RTP_URL
const char* RTP_URL = "http://avods.enst.fr/" static
Definition at line 34 of file clip.cpp.
Referenced by Clip::contRtp(), Clip::pauseRtp(), Clip::startRtp(), and Clip::stopRtp().
STOP_CGI
const char* STOP_CGI = "rtpstop.cgi" static
Definition at line 36 of file clip.cpp.
Referenced by Clip::stopRtp().