VREng: src/wo/fire.cpp File Reference
fire.cpp File Reference
#include "vreng.hpp"
#include "fire.hpp"
#include "timer.hpp"
#include "sound.hpp"
Functions
static float hrnd (float n)
static float nrnd (float d)
Variables
static struct sParticle particles [FIREMAX]
static Vector3 src (0, 5,-1.5)
static Vector3 ds1 (2, 0, 0)
static Vector3 ds2 (0, 2, 0)
static struct sCyl cyl [3]
Function Documentation
hrnd()
static float hrnd (float n) static
Definition at line 37 of file fire.cpp.
References RAND_MAX.
Referenced by nrnd().
nrnd()
static float nrnd (float d) static
Definition at line 39 of file fire.cpp.
References d, hrnd(), and sCyl::r.
Referenced by Fire::changePermanent().
Variable Documentation
cyl
struct sCyl cyl[3] static
Definition at line 33 of file fire.cpp.
Referenced by Fire::changePermanent(), and Fire::inits().
ds1
Vector3 ds1(2, 0, 0) static
Referenced by Fire::changePermanent(), and Fire::inits().
ds2
Vector3 ds2(0, 2, 0) static
Referenced by Fire::changePermanent(), and Fire::inits().
particles
struct sParticle particles[FIREMAX] static
Definition at line 27 of file fire.cpp.
Referenced by Fire::changePermanent(), and Fire::draw().
src
Vector3 src(0, 5,-1.5) static
Referenced by Fire::changePermanent(), convert_format(), VNCClient::handleCR(), VNCClient::handleRAW32(), Fire::inits(), Vrelet::processClient(), Flare::vcopy(), and Flare::vscale().