VREng: src/wo/hairs.hpp File Reference
hairs.hpp File Reference
#include "wobject.hpp"
#include "vector3.hpp"
#include "lwo.hpp"
Classes
class Color4f
Color4f class.
class HVertex
HVertex class.
class Material
Material class.
class TriFace
TriFace class.
struct Surface
Surface class.
class Object
Object class.
class Node
Node class.
class Line
Line class.
class Hair
CHair class.
class Hairs
Hairs class.
Macros
#define HAIRS_TYPE 77
#define HAIRS_NAME "Hairs"
#define NBHAIR 100
#define HAIRSIZE 4
#define HAIRLENGTH .04
#define HAIRNCOLOR 4
#define LENGTH2 (4. * HAIRLENGTH)
#define MAXL (1.2 * HAIRLENGTH * 1.2 * HAIRLENGTH)
#define MAXL2 (1.1 * HAIRLENGTH)
#define STIFFNESS 0.1
#define STIFF2 0.005
#define FROT 0.1
#define HAIRGRAVITY 0.03
#define OBJSIZE 0.1
#define RANDX (OBJSIZE*0.02)
#define RANDY (OBJSIZE*0.02)
#define RANDZ (OBJSIZE*0.05)
#define PUT_COORD 1
#define PUT_NORMAL 2
Functions
template<class T >
T rnd (T n)
Macro Definition Documentation
FROT
#define FROT 0.1
Definition at line 41 of file hairs.hpp.
HAIRGRAVITY
#define HAIRGRAVITY 0.03
Definition at line 42 of file hairs.hpp.
HAIRLENGTH
#define HAIRLENGTH .04
Definition at line 34 of file hairs.hpp.
HAIRNCOLOR
#define HAIRNCOLOR 4
Definition at line 35 of file hairs.hpp.
HAIRS_NAME
#define HAIRS_NAME "Hairs"
Definition at line 25 of file hairs.hpp.
HAIRS_TYPE
#define HAIRS_TYPE 77
Definition at line 24 of file hairs.hpp.
HAIRSIZE
#define HAIRSIZE 4
Definition at line 33 of file hairs.hpp.
LENGTH2
#define LENGTH2 (4. * HAIRLENGTH)
Definition at line 36 of file hairs.hpp.
MAXL
#define MAXL (1.2 * HAIRLENGTH * 1.2 * HAIRLENGTH)
Definition at line 37 of file hairs.hpp.
MAXL2
#define MAXL2 (1.1 * HAIRLENGTH)
Definition at line 38 of file hairs.hpp.
NBHAIR
#define NBHAIR 100
Definition at line 32 of file hairs.hpp.
OBJSIZE
#define OBJSIZE 0.1
Definition at line 43 of file hairs.hpp.
PUT_COORD
#define PUT_COORD 1
Definition at line 47 of file hairs.hpp.
PUT_NORMAL
#define PUT_NORMAL 2
Definition at line 48 of file hairs.hpp.
RANDX
#define RANDX (OBJSIZE*0.02)
Definition at line 44 of file hairs.hpp.
RANDY
#define RANDY (OBJSIZE*0.02)
Definition at line 45 of file hairs.hpp.
RANDZ
#define RANDZ (OBJSIZE*0.05)
Definition at line 46 of file hairs.hpp.
STIFF2
#define STIFF2 0.005
Definition at line 40 of file hairs.hpp.
STIFFNESS
#define STIFFNESS 0.1
Definition at line 39 of file hairs.hpp.
Function Documentation
rnd()
template<class T > T rnd (T n) inline
Definition at line 51 of file hairs.hpp.
References RAND_MAX.
Referenced by Hairs::changePermanent(), Hair::init(), and Line::init().