VREng: src/wo/initobj.cpp File Reference
initobj.cpp File Reference
#include "vreng.hpp"
#include "wobject.hpp"
#include "world.hpp"
#include "user.hpp"
#include "plane.hpp"
#include "door.hpp"
#include "thing.hpp"
#include "ball.hpp"
#include "step.hpp"
#include "mirage.hpp"
#include "gate.hpp"
#include "wall.hpp"
#include "ground.hpp"
#include "web.hpp"
#include "button.hpp"
#include "cauldron.hpp"
#include "projectile.hpp"
#include "bullet.hpp"
#include "dart.hpp"
#include "host.hpp"
#include "board.hpp"
#include "doc.hpp"
#include "walls.hpp"
#include "entry.hpp"
#include "bgcolor.hpp"
#include "light.hpp"
#include "music.hpp"
#include "movie.hpp"
#include "clip.hpp"
#include "clock.hpp"
#include "ftp.hpp"
#include "mirror.hpp"
#include "stars.hpp"
#include "particle.hpp"
#include "water.hpp"
#include "mech.hpp"
#include "guy.hpp"
#include "vnc.hpp"
#include "vrelet.hpp"
#include "vjc.hpp"
#include "animator.hpp"
#include "text.hpp"
#include "android.hpp"
#include "carrier.hpp"
#include "cart.hpp"
#include "book.hpp"
#include "sheet.hpp"
#include "icon.hpp"
#include "model.hpp"
#include "flag.hpp"
#include "guide.hpp"
#include "area.hpp"
#include "lift.hpp"
#include "transform.hpp"
#include "aoi.hpp"
#include "animx3d.hpp"
#include "wind.hpp"
#include "widget.hpp"
#include "thunder.hpp"
#include "cloud.hpp"
#include "stair.hpp"
#include "escalator.hpp"
#include "travelator.hpp"
#include "spiral.hpp"
#include "waterfall.hpp"
#include "fountain.hpp"
#include "rain.hpp"
#include "snow.hpp"
#include "bubble.hpp"
#include "terrain.hpp"
#include "river.hpp"
#include "sun.hpp"
#include "cloth.hpp"
#include "halo.hpp"
#include "hat.hpp"
#include "dress.hpp"
#include "wings.hpp"
#include "fire.hpp"
#include "smoke.hpp"
#include "hairs.hpp"
#include "slider.hpp"
#include "bumper.hpp"
#include "accessory.hpp"
#include "head.hpp"
#include "firework.hpp"
#include "fractal.hpp"
Functions
void setActionFunc (int type, uint8_t action, void(*action_method)(WObject *o, void *d, time_t s, time_t u), const char *action_name)
Initializes table of action functions.
bool isAction (int type, uint8_t action)
void doAction (int type, uint8_t action, WObject *o, void *d, time_t s, time_t u)
bool isActionName (int type, uint8_t action)
int indexAction (int type, const char *name)
void copyActionName (int type, uint8_t action, char *dest)
char * getActionName (int type, uint8_t action)
void * getActionMethod (int type, uint8_t action)
void setMaxLastings (int type, float maxlast)
float getMaxLastings (int type)
void setPropertiesnumber (int type, uint8_t nbprop)
uint8_t getPropertiesnumber (int type)
void getPropertyFunc (int type, uint8_t prop, void(*getprop_method)(WObject *o, Payload *p))
Initializes table of property functions.
void putPropertyFunc (int type, uint8_t prop, void(*putprop_method)(WObject *o, Payload *p))
bool isGetPropertyFunc (int type, uint8_t prop)
bool isPutPropertyFunc (int type, uint8_t prop)
void runGetPropertyFunc (int type, uint8_t prop, WObject *o, Payload *pp)
void runPutPropertyFunc (int type, uint8_t prop, WObject *o, Payload *pp)
Variables
const struct GeneralInitList generalInitList []
static struct PropertyFuncList putPropertyFuncList [OBJECTSNUMBER+1][PROPSNUMBER]
static struct PropertyFuncList getPropertyFuncList [OBJECTSNUMBER+1][PROPSNUMBER]
static struct GeneralActionList generalActionList [OBJECTSNUMBER+1][ACTIONSNUMBER]
float maxlastings [OBJECTSNUMBER+1]
uint8_t propertiesnumber [OBJECTSNUMBER+1]
Function Documentation
copyActionName()
void copyActionName (int type, uint8_t action, char * dest)
Definition at line 271 of file initobj.cpp.
References generalActionList, and GeneralActionList::name.
Referenced by WObject::getObjectHumanName().
doAction()
void doAction (int type, uint8_t action, WObject * o, void * d, time_t s, time_t u)
Definition at line 252 of file initobj.cpp.
References d, generalActionList, and GeneralActionList::method.
Referenced by World::checkIcons(), User::checkMysql(), World::checkPersistObjects(), Button::commut(), Cauldron::create_cb(), User::createBullet(), User::createDart(), Book::createSheet(), PutInfo::putIcon(), PutInfo::putIconCB(), Cloud::rain(), WObject::runAction(), Cloud::snow(), Cloud::sound(), Model::sound(), User::specialAction(), WObject::specialAction(), and Wall::whenIntersect().
getActionMethod()
void* getActionMethod (int type, uint8_t action)
Definition at line 281 of file initobj.cpp.
References generalActionList, and GeneralActionList::method.
Referenced by Vicinity::actionList().
getActionName()
char* getActionName (int type, uint8_t action)
Definition at line 276 of file initobj.cpp.
References generalActionList, and GeneralActionList::name.
Referenced by Vicinity::actionList(), Vicinity::getTypeFromAction(), and WObject::runAction().
getMaxLastings()
float getMaxLastings (int type)
Definition at line 291 of file initobj.cpp.
References maxlastings.
Referenced by WObject::getLasting().
getPropertiesnumber()
uint8_t getPropertiesnumber (int type)
Definition at line 301 of file initobj.cpp.
References propertiesnumber.
Referenced by NetProperty::getPropertiesNumber().
getPropertyFunc()
void getPropertyFunc (int type, uint8_t prop, void(*)(WObject *o, Payload *p) getprop_method)
Initializes table of property functions.
Definition at line 307 of file initobj.cpp.
References getPropertyFuncList, and PropertyFuncList::method.
Referenced by Animator::funcs(), Ball::funcs(), Book::funcs(), Bullet::funcs(), Button::funcs(), Dart::funcs(), Doc::funcs(), Door::funcs(), Dress::funcs(), Gate::funcs(), Halo::funcs(), Hat::funcs(), Head::funcs(), Host::funcs(), Icon::funcs(), Lift::funcs(), Music::funcs(), Plane::funcs(), Sheet::funcs(), Thing::funcs(), User::funcs(), Web::funcs(), and Wings::funcs().
indexAction()
int indexAction (int type, const char * name)
Definition at line 262 of file initobj.cpp.
References generalActionList, isAction(), GeneralActionList::name, and strcasecmp().
Referenced by Button::parser().
isAction()
bool isAction (int type, uint8_t action)
Definition at line 247 of file initobj.cpp.
References generalActionList, and GeneralActionList::method.
Referenced by World::checkIcons(), Button::commut(), Cauldron::create_cb(), User::createBullet(), User::createDart(), WObject::haveAction(), indexAction(), WObject::numberAction(), Cloud::rain(), Cloud::snow(), Cloud::sound(), User::specialAction(), and WObject::specialAction().
isActionName()
bool isActionName (int type, uint8_t action)
Definition at line 257 of file initobj.cpp.
References generalActionList, and GeneralActionList::name.
Referenced by Vicinity::actionList(), WObject::getObjectHumanName(), and Vicinity::getTypeFromAction().
isGetPropertyFunc()
bool isGetPropertyFunc (int type, uint8_t prop)
Definition at line 317 of file initobj.cpp.
References getPropertyFuncList, and PropertyFuncList::method.
Referenced by WObject::getProperty().
isPutPropertyFunc()
bool isPutPropertyFunc (int type, uint8_t prop)
Definition at line 322 of file initobj.cpp.
References PropertyFuncList::method, and putPropertyFuncList.
Referenced by WObject::putProperty().
putPropertyFunc()
void putPropertyFunc (int type, uint8_t prop, void(*)(WObject *o, Payload *p) putprop_method)
Definition at line 312 of file initobj.cpp.
References PropertyFuncList::method, and putPropertyFuncList.
Referenced by Animator::funcs(), Ball::funcs(), Book::funcs(), Bullet::funcs(), Button::funcs(), Dart::funcs(), Doc::funcs(), Door::funcs(), Dress::funcs(), Gate::funcs(), Halo::funcs(), Hat::funcs(), Head::funcs(), Host::funcs(), Icon::funcs(), Lift::funcs(), Music::funcs(), Plane::funcs(), Sheet::funcs(), Thing::funcs(), User::funcs(), Web::funcs(), and Wings::funcs().
runGetPropertyFunc()
void runGetPropertyFunc (int type, uint8_t prop, WObject * o, Payload * pp)
Definition at line 327 of file initobj.cpp.
References getPropertyFuncList, and PropertyFuncList::method.
Referenced by WObject::getProperty().
runPutPropertyFunc()
void runPutPropertyFunc (int type, uint8_t prop, WObject * o, Payload * pp)
Definition at line 332 of file initobj.cpp.
References PropertyFuncList::method, and putPropertyFuncList.
Referenced by WObject::putProperty().
setActionFunc()
void setActionFunc (int type, uint8_t action, void(*)(WObject *o, void *d, time_t s, time_t u) action_method, const char * action_name)
Initializes table of action functions.
Definition at line 241 of file initobj.cpp.
References generalActionList, GeneralActionList::method, and GeneralActionList::name.
Referenced by Accessory::funcs(), Android::funcs(), Animator::funcs(), AnimX3d::funcs(), Ball::funcs(), Board::funcs(), Book::funcs(), Bullet::funcs(), Bumper::funcs(), Button::funcs(), Carrier::funcs(), Cauldron::funcs(), Clip::funcs(), Cloud::funcs(), Dart::funcs(), Doc::funcs(), Door::funcs(), Dress::funcs(), Escalator::funcs(), Fire::funcs(), Fountain::funcs(), Ftp::funcs(), Gate::funcs(), Ground::funcs(), Guide::funcs(), Guy::funcs(), Halo::funcs(), Hat::funcs(), Head::funcs(), Host::funcs(), Icon::funcs(), Lift::funcs(), Mech::funcs(), Mirage::funcs(), Mirror::funcs(), Model::funcs(), Movie::funcs(), Music::funcs(), Plane::funcs(), Rain::funcs(), Sheet::funcs(), Slider::funcs(), Snow::funcs(), Spiral::funcs(), Stair::funcs(), Step::funcs(), Thing::funcs(), Travelator::funcs(), User::funcs(), Vnc::funcs(), Wall::funcs(), Water::funcs(), Waterfall::funcs(), Web::funcs(), Widget::funcs(), Wings::funcs(), and Guy::Guy().
setMaxLastings()
void setMaxLastings (int type, float maxlast)
Definition at line 286 of file initobj.cpp.
References maxlastings.
Referenced by WObject::setLasting().
setPropertiesnumber()
void setPropertiesnumber (int type, uint8_t nbprop)
Definition at line 296 of file initobj.cpp.
References propertiesnumber.
Referenced by NetProperty::setPropertiesNumber().
Variable Documentation
generalActionList
struct GeneralActionList generalActionList[OBJECTSNUMBER+1][ACTIONSNUMBER] static
Definition at line 1 of file initobj.cpp.
Referenced by copyActionName(), doAction(), getActionMethod(), getActionName(), indexAction(), World::initGeneralFuncList(), isAction(), isActionName(), and setActionFunc().
generalInitList
const struct GeneralInitList generalInitList[]
Definition at line 1 of file initobj.cpp.
Referenced by World::initGeneralFuncList().
getPropertyFuncList
struct PropertyFuncList getPropertyFuncList[OBJECTSNUMBER+1][PROPSNUMBER] static
Definition at line 1 of file initobj.cpp.
Referenced by getPropertyFunc(), World::initGeneralFuncList(), isGetPropertyFunc(), and runGetPropertyFunc().
maxlastings
float maxlastings[OBJECTSNUMBER+1]
Definition at line 205 of file initobj.cpp.
Referenced by getMaxLastings(), World::initGeneralFuncList(), and setMaxLastings().
propertiesnumber
uint8_t propertiesnumber[OBJECTSNUMBER+1]
Definition at line 206 of file initobj.cpp.
Referenced by getPropertiesnumber(), World::initGeneralFuncList(), and setPropertiesnumber().
putPropertyFuncList
struct PropertyFuncList putPropertyFuncList[OBJECTSNUMBER+1][PROPSNUMBER] static
Definition at line 1 of file initobj.cpp.
Referenced by World::initGeneralFuncList(), isPutPropertyFunc(), putPropertyFunc(), and runPutPropertyFunc().