VREng: src/wo/initobj.hpp File Reference
initobj.hpp File Reference
#include "objects.hpp"
#include "wobject.hpp"
Classes
struct GeneralInitList
GeneralInitList struct.
struct PropertyFuncList
PropertyFuncList struct.
struct GeneralActionList
GeneralActionList struct.
Macros
#define UNKNOWN_TYPE -1
#define WO_PAYLOAD (void (*)(WObject *po, class Payload *pp))
#define WO_ACTION (void (*)(WObject *po, void *d, time_t s, time_t u))
Functions
void setActionFunc (int type, uint8_t action, void(*method)(WObject *o, void *d, time_t s, time_t u), const char *action_name)
Initializes table of action functions.
bool isAction (int type, uint8_t action)
void doAction (int type, uint8_t action, WObject *o, void *d, time_t s, time_t u)
bool isActionName (int type, uint8_t action)
int indexAction (int type, const char *name)
void copyActionName (int type, uint8_t action, char *dest)
char * getActionName (int type, uint8_t action)
void * getActionMethod (int type, uint8_t action)
void setMaxLastings (int type, float maxlast)
float getMaxLastings (int type)
void setPropertiesnumber (int type, uint8_t nbprop)
uint8_t getPropertiesnumber (int type)
void getPropertyFunc (int type, uint8_t prop, void(*getprop_method)(WObject *o, Payload *p))
Initializes table of property functions.
void putPropertyFunc (int type, uint8_t prop, void(*putprop_method)(WObject *o, Payload *p))
bool isGetPropertyFunc (int type, uint8_t prop)
bool isPutPropertyFunc (int type, uint8_t prop)
void runGetPropertyFunc (int type, uint8_t prop, WObject *o, Payload *pp)
void runPutPropertyFunc (int type, uint8_t prop, WObject *o, Payload *pp)
Macro Definition Documentation
UNKNOWN_TYPE
#define UNKNOWN_TYPE -1
Definition at line 27 of file initobj.hpp.
WO_ACTION
#define WO_ACTION (void (*)(WObject *po, void *d, time_t s, time_t u))
Definition at line 52 of file initobj.hpp.
WO_PAYLOAD
#define WO_PAYLOAD (void (*)(WObject *po, class Payload *pp))
Definition at line 43 of file initobj.hpp.
Function Documentation
copyActionName()
void copyActionName (int type, uint8_t action, char * dest)
Definition at line 271 of file initobj.cpp.
References generalActionList, and GeneralActionList::name.
Referenced by WObject::getObjectHumanName().
doAction()
void doAction (int type, uint8_t action, WObject * o, void * d, time_t s, time_t u)
Definition at line 252 of file initobj.cpp.
References d, generalActionList, and GeneralActionList::method.
Referenced by World::checkIcons(), User::checkMysql(), World::checkPersistObjects(), Button::commut(), Cauldron::create_cb(), User::createBullet(), User::createDart(), Book::createSheet(), PutInfo::putIcon(), PutInfo::putIconCB(), Cloud::rain(), WObject::runAction(), Cloud::snow(), Cloud::sound(), Model::sound(), User::specialAction(), WObject::specialAction(), and Wall::whenIntersect().
getActionMethod()
void* getActionMethod (int type, uint8_t action)
Definition at line 281 of file initobj.cpp.
References generalActionList, and GeneralActionList::method.
Referenced by Vicinity::actionList().
getActionName()
char* getActionName (int type, uint8_t action)
Definition at line 276 of file initobj.cpp.
References generalActionList, and GeneralActionList::name.
Referenced by Vicinity::actionList(), Vicinity::getTypeFromAction(), and WObject::runAction().
getMaxLastings()
float getMaxLastings (int type)
Definition at line 291 of file initobj.cpp.
References maxlastings.
Referenced by WObject::getLasting().
getPropertiesnumber()
uint8_t getPropertiesnumber (int type)
Definition at line 301 of file initobj.cpp.
References propertiesnumber.
Referenced by NetProperty::getPropertiesNumber().
getPropertyFunc()
void getPropertyFunc (int type, uint8_t prop, void(*)(WObject *o, Payload *p) getprop_method)
Initializes table of property functions.
Definition at line 307 of file initobj.cpp.
References getPropertyFuncList, and PropertyFuncList::method.
Referenced by Animator::funcs(), Ball::funcs(), Book::funcs(), Bullet::funcs(), Button::funcs(), Dart::funcs(), Doc::funcs(), Door::funcs(), Dress::funcs(), Gate::funcs(), Halo::funcs(), Hat::funcs(), Head::funcs(), Host::funcs(), Icon::funcs(), Lift::funcs(), Music::funcs(), Plane::funcs(), Sheet::funcs(), Thing::funcs(), User::funcs(), Web::funcs(), and Wings::funcs().
indexAction()
int indexAction (int type, const char * name)
Definition at line 262 of file initobj.cpp.
References generalActionList, isAction(), GeneralActionList::name, and strcasecmp().
Referenced by Button::parser().
isAction()
bool isAction (int type, uint8_t action)
Definition at line 247 of file initobj.cpp.
References generalActionList, and GeneralActionList::method.
Referenced by World::checkIcons(), Button::commut(), Cauldron::create_cb(), User::createBullet(), User::createDart(), WObject::haveAction(), indexAction(), WObject::numberAction(), Cloud::rain(), Cloud::snow(), Cloud::sound(), User::specialAction(), and WObject::specialAction().
isActionName()
bool isActionName (int type, uint8_t action)
Definition at line 257 of file initobj.cpp.
References generalActionList, and GeneralActionList::name.
Referenced by Vicinity::actionList(), WObject::getObjectHumanName(), and Vicinity::getTypeFromAction().
isGetPropertyFunc()
bool isGetPropertyFunc (int type, uint8_t prop)
Definition at line 317 of file initobj.cpp.
References getPropertyFuncList, and PropertyFuncList::method.
Referenced by WObject::getProperty().
isPutPropertyFunc()
bool isPutPropertyFunc (int type, uint8_t prop)
Definition at line 322 of file initobj.cpp.
References PropertyFuncList::method, and putPropertyFuncList.
Referenced by WObject::putProperty().
putPropertyFunc()
void putPropertyFunc (int type, uint8_t prop, void(*)(WObject *o, Payload *p) putprop_method)
Definition at line 312 of file initobj.cpp.
References PropertyFuncList::method, and putPropertyFuncList.
Referenced by Animator::funcs(), Ball::funcs(), Book::funcs(), Bullet::funcs(), Button::funcs(), Dart::funcs(), Doc::funcs(), Door::funcs(), Dress::funcs(), Gate::funcs(), Halo::funcs(), Hat::funcs(), Head::funcs(), Host::funcs(), Icon::funcs(), Lift::funcs(), Music::funcs(), Plane::funcs(), Sheet::funcs(), Thing::funcs(), User::funcs(), Web::funcs(), and Wings::funcs().
runGetPropertyFunc()
void runGetPropertyFunc (int type, uint8_t prop, WObject * o, Payload * pp)
Definition at line 327 of file initobj.cpp.
References getPropertyFuncList, and PropertyFuncList::method.
Referenced by WObject::getProperty().
runPutPropertyFunc()
void runPutPropertyFunc (int type, uint8_t prop, WObject * o, Payload * pp)
Definition at line 332 of file initobj.cpp.
References PropertyFuncList::method, and putPropertyFuncList.
Referenced by WObject::putProperty().
setActionFunc()
void setActionFunc (int type, uint8_t action, void(*)(WObject *o, void *d, time_t s, time_t u) method, const char * action_name)
Initializes table of action functions.
Definition at line 241 of file initobj.cpp.
References generalActionList, GeneralActionList::method, and GeneralActionList::name.
Referenced by Accessory::funcs(), Android::funcs(), Animator::funcs(), AnimX3d::funcs(), Ball::funcs(), Board::funcs(), Book::funcs(), Bullet::funcs(), Bumper::funcs(), Button::funcs(), Carrier::funcs(), Cauldron::funcs(), Clip::funcs(), Cloud::funcs(), Dart::funcs(), Doc::funcs(), Door::funcs(), Dress::funcs(), Escalator::funcs(), Fire::funcs(), Fountain::funcs(), Ftp::funcs(), Gate::funcs(), Ground::funcs(), Guide::funcs(), Guy::funcs(), Halo::funcs(), Hat::funcs(), Head::funcs(), Host::funcs(), Icon::funcs(), Lift::funcs(), Mech::funcs(), Mirage::funcs(), Mirror::funcs(), Model::funcs(), Movie::funcs(), Music::funcs(), Plane::funcs(), Rain::funcs(), Sheet::funcs(), Slider::funcs(), Snow::funcs(), Spiral::funcs(), Stair::funcs(), Step::funcs(), Thing::funcs(), Travelator::funcs(), User::funcs(), Vnc::funcs(), Wall::funcs(), Water::funcs(), Waterfall::funcs(), Web::funcs(), Widget::funcs(), Wings::funcs(), and Guy::Guy().
setMaxLastings()
void setMaxLastings (int type, float maxlast)
Definition at line 286 of file initobj.cpp.
References maxlastings.
Referenced by WObject::setLasting().
setPropertiesnumber()
void setPropertiesnumber (int type, uint8_t nbprop)
Definition at line 296 of file initobj.cpp.
References propertiesnumber.
Referenced by NetProperty::setPropertiesNumber().