VREng: src/wo/move.cpp File Reference
move.cpp File Reference
#include "vreng.hpp"
#include "wobject.hpp"
#include "move.hpp"
#include "world.hpp"
#include "user.hpp"
#include "carrier.hpp"
#include "netobj.hpp"
#include "guy.hpp"
#include "man.hpp"
Macros
#define MIN_MOVES 20
#define RATIO_GOTO 2
Functions
void changeKey (int k_id, bool pressed, time_t sec, time_t usec)
notify a key has changed key_id = 0..MAXKEYS-1 TRUE for a Key Press and FALSE for a Key Release sec: seconds, usec: micro-seconds
void * endMovement (void *arg)
void gotoXYZ (float gox, float goy, float goz, float az)
Moves the user behind the object.
void gotoFront (WObject *po, void *d, time_t s, time_t u)
pressed is TRUE for a Key Press and FALSE for a Key Release
void gotoBehind (WObject *po, void *d, time_t s, time_t u)
Moves the user in front of the object.
Macro Definition Documentation
MIN_MOVES
#define MIN_MOVES 20
Definition at line 31 of file move.cpp.
RATIO_GOTO
#define RATIO_GOTO 2
Definition at line 32 of file move.cpp.
Function Documentation
changeKey()
void changeKey (int k_id, bool pressed, time_t sec, time_t usec)
notify a key has changed key_id = 0..MAXKEYS-1 TRUE for a Key Press and FALSE for a Key Release sec: seconds, usec: micro-seconds
Definition at line 41 of file move.cpp.
References User::kpdur_s, User::kpdur_u, User::kpressed, User::kpstart_s, User::kpstart_u, localuser, MAXKEYS, and warning().
Referenced by Widgets::flushPostponedKRs(), Motion::move(), Widgets::processKey(), and Widgets::setKey().
endMovement()
void* endMovement (void * arg)
Definition at line 92 of file move.cpp.
References WObject::behavior, COLLIDE_NEVER, User::disableGravity(), WObject::enableBehavior(), User::enableGravity(), localuser, WObject::move, and Move::ttl.
Referenced by WObject::updateLasting().
gotoBehind()
void gotoBehind (WObject * po, void * d, time_t s, time_t u)
Moves the user in front of the object.
Definition at line 555 of file move.cpp.
References WObject::moveUserToObject().
gotoFront()
void gotoFront (WObject * po, void * d, time_t s, time_t u)
pressed is TRUE for a Key Press and FALSE for a Key Release
Definition at line 549 of file move.cpp.
References WObject::moveUserToObject().
Referenced by Bumper::funcs(), Door::funcs(), Escalator::funcs(), Gate::funcs(), Guide::funcs(), Lift::funcs(), Mirage::funcs(), Mirror::funcs(), Slider::funcs(), Spiral::funcs(), Stair::funcs(), Step::funcs(), Thing::funcs(), Travelator::funcs(), Vnc::funcs(), Web::funcs(), and Widget::funcs().
gotoXYZ()
void gotoXYZ (float gox, float goy, float goz, float az)
Moves the user behind the object.
Definition at line 517 of file move.cpp.
References Move::aspeed, Pos::az, clearV3(), Cos(), deltaAngle(), WObject::initImposedMovement(), localuser, User::LSPEED, Move::lspeed, MAX, WObject::move, Move::next, WObject::pos, Sin(), Move::ttl, V3::v, Move::without_col, Pos::x, Pos::y, and Pos::z.