VREng: src/wo/oclass.cpp File Reference
oclass.cpp File Reference
#include "vreng.hpp"
#include "str.hpp"
#include "netobj.hpp"
#include "initobj.hpp"
#include "oclass.hpp"
Macros
#define STL 0
Variables
static const OClass end (0, "End", NULL)
Macro Definition Documentation
STL
#define STL 0
Definition at line 29 of file oclass.cpp.
Variable Documentation
end
const OClass end(0, "End", NULL) static
Referenced by Img::loadDDS(), _3ds::loadTexture(), Ase::loadTexture(), Obj::loadTexture(), Rtp::recvRTCPPacket(), World::setName(), and Clip::startRtp().