VREng: src/net/event.cpp File Reference
event.cpp File Reference
#include "vreng.hpp"
#include "event.hpp"
#include "vrep.hpp"
#include "netobj.hpp"
#include "payload.hpp"
#include "netprop.hpp"
#include "oclass.hpp"
#include "user.hpp"
#include "timer.hpp"
Functions
void NetIncoming (int fd)
Awake the net when data is available on fd.
int NetTimeout ()
Check if some responsibilities must not to be taken when a timeout occurs.
Function Documentation
NetIncoming()
void NetIncoming (int fd)
Awake the net when data is available on fd.
Exported to GUI.
Definition at line 33 of file event.cpp.
References DBG_FORCE, error(), NetObject::getMyHostId(), NetObject::getMyPortId(), Payload::getPayload(), Payload::incomingCreate(), Payload::incomingDelete(), Payload::incomingDelta(), Payload::incomingOther(), Payload::incomingQuery(), Payload::len, Payload::recvPayload(), trace(), VREP_CREATE, VREP_CREATE_V1, VREP_DELETE, VREP_DELETE_V1, VREP_DELTA, VREP_DELTA_V1, VREP_QUERY, and VREP_QUERY_V1.
Referenced by Gui::addChannelSources().
NetTimeout()
int NetTimeout ()
Check if some responsibilities must not to be taken when a timeout occurs.
Do the heatbeat refreshing. Check if some netobjects must not to be deleted. Returns the delay after which we want to be awaked (ms) before recall. Exported to GUI.
Definition at line 109 of file event.cpp.
References NetProperty::assume_at, DBG_FORCE, DBG_NET, DEF_REFRESH_TIMEOUT, Times::diffDates(), error(), NetObject::getList(), NetObject::getPropertiesNumber(), Source::getSourcesNumber(), gettimeofday(), OClass::isValidType(), NetProperty::last_seen, netobjectList, NetObject::next, User::PROPENDVAR, NetProperty::responsible, trace(), USER_TYPE, and NetProperty::version.
Referenced by Scene::netTimeoutCB().