VREng: src/vgl/glu.hpp File Reference
glu.hpp File Reference
Functions
GLint gluProject (GLdouble objx, GLdouble objy, GLdouble objz, const GLdouble model[16], const GLdouble proj[16], const GLint viewport[4], GLdouble *winx, GLdouble *winy, GLdouble *winz)
GLint gluUnProject (GLdouble winx, GLdouble winy, GLdouble winz, const GLdouble model[16], const GLdouble proj[16], const GLint viewport[4], GLdouble *objx, GLdouble *objy, GLdouble *objz)
void gluPerspective (GLfloat fovy, GLfloat ratio, GLfloat near, GLfloat far)
void gluBuild2DMipmaps (GLint components, GLint width, GLint height, GLenum format, const unsigned char *data, int filter)
Function Documentation
gluBuild2DMipmaps()
void gluBuild2DMipmaps (GLint components, GLint width, GLint height, GLenum format, const unsigned char * data, int filter)
Referenced by Txf::establishTexture(), Vnc::setTexture(), and Widget::setTexture().
gluPerspective()
void gluPerspective (GLfloat fovy, GLfloat ratio, GLfloat near, GLfloat far)
Definition at line 325 of file glu.cpp.
References fovy, M_PI, near, and ratio.
gluProject()
GLint gluProject (GLdouble objx, GLdouble objy, GLdouble objz, const GLdouble model[16], const GLdouble proj[16], const GLint viewport[4], GLdouble * winx, GLdouble * winy, GLdouble * winz)
Definition at line 262 of file glu.cpp.
References transform_point().
Referenced by Render::getVisiblePosition().
gluUnProject()
GLint gluUnProject (GLdouble winx, GLdouble winy, GLdouble winz, const GLdouble model[16], const GLdouble proj[16], const GLint viewport[4], GLdouble * objx, GLdouble * objy, GLdouble * objz)
Definition at line 296 of file glu.cpp.
References A, invert_matrix(), matmul(), and transform_point().
Referenced by Render::clickDirection(), Vnc::getVncCoords(), and Solid::setRay().