VREng: src/net/rtp.cpp File Reference
rtp.cpp File Reference
#include "vreng.hpp"
#include "rtp.hpp"
#include "channel.hpp"
#include "nsl.hpp"
#include "session.hpp"
#include "source.hpp"
#include "stat.hpp"
#include "file.hpp"
Functions
uint32_t random32 (int type)
Function Documentation
random32()
uint32_t random32 (int type)
Definition at line 54 of file random.cpp.
References getpid, gettimeofday(), md_32(), pid, and pid_t.
Referenced by Rtp::createSsrc().