VREng: src/vgl/glu.cpp File Reference
glu.cpp File Reference
#include "vreng.hpp"
#include "glu.hpp"
Macros
#define M(row, col) m[col*4+row]
#define A(row, col) a[(col<<2)+row]
#define B(row, col) b[(col<<2)+row]
#define T(row, col) temp[(col<<2)+row]
#define SWAP_ROWS(a, b) { GLdouble *_tmp = a; (a)=(b); (b)=_tmp; }
#define MAT(m, r, c) (m)[(c)*4+(r)]
Functions
static void transform_point (GLdouble out[4], const GLdouble m[16], const GLdouble in[4])
static void matmul (GLdouble *product, const GLdouble *a, const GLdouble *b)
static GLboolean invert_matrix (const GLdouble *m, GLdouble *out)
GLint gluProject (GLdouble objx, GLdouble objy, GLdouble objz, const GLdouble model[16], const GLdouble proj[16], const GLint viewport[4], GLdouble *winx, GLdouble *winy, GLdouble *winz)
GLint gluUnProject (GLdouble winx, GLdouble winy, GLdouble winz, const GLdouble model[16], const GLdouble proj[16], const GLint viewport[4], GLdouble *objx, GLdouble *objy, GLdouble *objz)
void gluPerspective (GLfloat fovy, GLfloat ratio, GLfloat near, GLfloat far)
Macro Definition Documentation
A
#define A (row, col) a[(col<<2)+row]
B
#define B (row, col) b[(col<<2)+row]
M
#define M (row, col) m[col*4+row]
MAT
#define MAT (m, r, c) (m)[(c)*4+(r)]
SWAP_ROWS
#define SWAP_ROWS (a, b) { GLdouble *_tmp = a; (a)=(b); (b)=_tmp; }
T
#define T (row, col) temp[(col<<2)+row]
Function Documentation
gluPerspective()
void gluPerspective (GLfloat fovy, GLfloat ratio, GLfloat near, GLfloat far)
Definition at line 325 of file glu.cpp.
References fovy, M_PI, near, and ratio.
gluProject()
GLint gluProject (GLdouble objx, GLdouble objy, GLdouble objz, const GLdouble model[16], const GLdouble proj[16], const GLint viewport[4], GLdouble * winx, GLdouble * winy, GLdouble * winz)
Definition at line 262 of file glu.cpp.
References transform_point().
Referenced by Render::getVisiblePosition().
gluUnProject()
GLint gluUnProject (GLdouble winx, GLdouble winy, GLdouble winz, const GLdouble model[16], const GLdouble proj[16], const GLint viewport[4], GLdouble * objx, GLdouble * objy, GLdouble * objz)
Definition at line 296 of file glu.cpp.
References A, invert_matrix(), matmul(), and transform_point().
Referenced by Render::clickDirection(), Vnc::getVncCoords(), and Solid::setRay().
invert_matrix()
static GLboolean invert_matrix (const GLdouble * m, GLdouble * out) static
Definition at line 87 of file glu.cpp.
References MAT, and SWAP_ROWS.
Referenced by gluUnProject().
matmul()
static void matmul (GLdouble * product, const GLdouble * a, const GLdouble * b) static
Definition at line 61 of file glu.cpp.
References A, B, and T.
Referenced by gluUnProject().
transform_point()
static void transform_point (GLdouble out[4], const GLdouble m[16], const GLdouble in[4]) static
Definition at line 45 of file glu.cpp.
References M.
Referenced by gluProject(), and gluUnProject().