VREng: src/texture/gif.cpp File Reference
gif.cpp File Reference
#include "vreng.hpp"
#include "img.hpp"
#include "cache.hpp"
#include "file.hpp"
#include "texture.hpp"
Classes
struct GifInfo
Macros
#define MAXBITS 12
#define SIZLZW (1<<MAXBITS)
#define GETCODE(c)
Functions
static void LZWDecodeInit (GifInfo *g, int csize)
static void LZWDecode (GifInfo *g, uint8_t *buf, int len)
static int LZWDecodeEnd (GifInfo *g)
static int gifReadSignature (GifInfo *g)
static int gifReadScreen (GifInfo *g)
static int gifReadBlocks (GifInfo *g)
static int gifread (GifInfo *g, uint8_t *buf, int len)
static int gifGetByte (GifInfo *g)
static int gifReadImage (GifInfo *g)
static void gifReadExtension (GifInfo *g)
Variables
static int offset = 0
Macro Definition Documentation
GETCODE
#define GETCODE (c)
Value:
{         \
  if (bbits>=cursize) {     \
    c=bbuf & curmask;     \
    bbuf>>=cursize;     \
    bbits-=cursize;     \
  } else {        \
    while (bbits<=24) {     \
      sizbuf--;       \
      if (sizbuf<=0) {      \
  if (sizbuf<0) {     \
    sizbuf=0;     \
  } else {      \
    sizbuf=gifGetByte(g);   \
    gifread(g,g->buf,sizbuf); \
  }       \
  pbuf=g->buf;      \
      }         \
      bbuf|=(int)(*pbuf++) << bbits;  \
      bbits+=8;       \
    }         \
    c=bbuf & curmask;     \
    bbuf>>=cursize;     \
    bbits-=cursize;     \
  }         \
}
Definition at line 291 of file gif.cpp.
MAXBITS
#define MAXBITS 12
Definition at line 254 of file gif.cpp.
SIZLZW
#define SIZLZW (1<<MAXBITS)
Definition at line 255 of file gif.cpp.
Function Documentation
gifGetByte()
static int gifGetByte (GifInfo * g) static
Definition at line 86 of file gif.cpp.
References g, gifread(), and offset.
Referenced by gifReadBlocks(), gifReadExtension(), and LZWDecodeEnd().
gifread()
static int gifread (GifInfo * g, uint8_t * buf, int len) inline static
Definition at line 81 of file gif.cpp.
References g.
Referenced by gifGetByte(), gifReadExtension(), gifReadImage(), gifReadScreen(), and gifReadSignature().
gifReadBlocks()
static int gifReadBlocks (GifInfo * g) static
Definition at line 230 of file gif.cpp.
References DBG_IMG, g, gifGetByte(), gifReadExtension(), gifReadImage(), offset, and trace().
Referenced by Img::loadGIF().
gifReadExtension()
static void gifReadExtension (GifInfo * g) static
Definition at line 216 of file gif.cpp.
References g, gifGetByte(), and gifread().
Referenced by gifReadBlocks().
gifReadImage()
static int gifReadImage (GifInfo * g) static
Definition at line 127 of file gif.cpp.
References g, gifread(), Img::height, LZWDecode(), LZWDecodeEnd(), LZWDecodeInit(), and Img::width.
Referenced by gifReadBlocks().
gifReadScreen()
static int gifReadScreen (GifInfo * g) static
Definition at line 107 of file gif.cpp.
References g, gifread(), Img::Img(), and Img::RGB.
Referenced by Img::loadGIF().
gifReadSignature()
static int gifReadSignature (GifInfo * g) static
Definition at line 95 of file gif.cpp.
References g, and gifread().
Referenced by Img::loadGIF().
LZWDecode()
static void LZWDecode (GifInfo * g, uint8_t * buf, int len) static
Definition at line 321 of file gif.cpp.
References g, GETCODE, and MAXBITS.
Referenced by gifReadImage().
LZWDecodeEnd()
static int LZWDecodeEnd (GifInfo * g) static
Definition at line 275 of file gif.cpp.
References g, gifGetByte(), and size.
Referenced by gifReadImage().
LZWDecodeInit()
static void LZWDecodeInit (GifInfo * g, int csize) static
Definition at line 257 of file gif.cpp.
References g, and SIZLZW.
Referenced by gifReadImage().
Variable Documentation
offset
int offset = 0 static
Definition at line 55 of file gif.cpp.
Referenced by gifGetByte(), and gifReadBlocks().