VREng: src/texture/psd.cpp File Reference
psd.cpp File Reference
#include "vreng.hpp"
#include "img.hpp"
#include "cache.hpp"
#include "file.hpp"
#include "texture.hpp"
Classes
struct stbi
Macros
#define COMBO(a, b) ((a)*8+(b))
#define CASE(a, b) case COMBO(a,b): for (int i=x-1; i >= 0; --i, src += a, dst += b)
Functions
static int get8 (stbi *s)
static void skip (stbi *s, int n)
static int get16 (stbi *s)
static uint32_t get32 (stbi *s)
static uint8_t compute_y (int r, int g, int b)
static uint8_t * convert_format (uint8_t *data, uint8_t srccomp, uint8_t dstcomp, uint16_t x, uint16_t y)
static uint8_t * psd_load (stbi *s, uint16_t *x, uint16_t *y, uint8_t *srccomp, uint8_t dstcomp)
Macro Definition Documentation
CASE
#define CASE (a, b) case COMBO(a,b): for (int i=x-1; i >= 0; --i, src += a, dst += b)
COMBO
#define COMBO (a, b) ((a)*8+(b))
Function Documentation
compute_y()
static uint8_t compute_y (int r, int g, int b) static
Definition at line 66 of file psd.cpp.
References g.
Referenced by convert_format().
convert_format()
static uint8_t* convert_format (uint8_t * data, uint8_t srccomp, uint8_t dstcomp, uint16_t x, uint16_t y) static
Definition at line 72 of file psd.cpp.
References CASE, COMBO, compute_y(), error(), and src.
Referenced by psd_load().
get16()
static int get16 (stbi * s) static
Definition at line 54 of file psd.cpp.
References get8().
Referenced by get32(), and psd_load().
get32()
static uint32_t get32 (stbi * s) static
Definition at line 60 of file psd.cpp.
References get16().
Referenced by psd_load().
get8()
static int get8 (stbi * s) static
Definition at line 38 of file psd.cpp.
References stbi::img_buffer, stbi::img_buffer_end, and stbi::img_file.
Referenced by get16(), and psd_load().
psd_load()
static uint8_t* psd_load (stbi * s, uint16_t * x, uint16_t * y, uint8_t * srccomp, uint8_t dstcomp) static
Definition at line 123 of file psd.cpp.
References channel, convert_format(), error(), get16(), get32(), get8(), and skip().
Referenced by Img::loadPSD().
skip()
static void skip (stbi * s, int n) static
Definition at line 49 of file psd.cpp.
References stbi::img_file.
Referenced by psd_load().