VREng: src/model/bonevertex.hpp File Reference
bonevertex.hpp File Reference
#include "bonename.hpp"
#include "vec3.hpp"
#include "bonelist.hpp"
Classes
class BoneVertex
BoneVertex class.
class Vertex
Vertex class.
Functions
char readChar (FILE *in)
short readShort (FILE *in)
int readInt (FILE *in)
float readFloat (FILE *in)
char * readString (FILE *in, char *str)
Function Documentation
readChar()
char readChar (FILE * in) inline
Definition at line 159 of file bonevertex.hpp.
Referenced by readString().
readFloat()
float readFloat (FILE * in) inline
Definition at line 185 of file bonevertex.hpp.
References readInt().
Referenced by BoneVertex::readFromFile(), and V3d::readV3Dfile().
readInt()
int readInt (FILE * in) inline
Definition at line 171 of file bonevertex.hpp.
Referenced by readFloat(), BoneVertex::readFromFile(), and V3d::readV3Dfile().
readShort()
short readShort (FILE * in) inline
Definition at line 164 of file bonevertex.hpp.
readString()
char* readString (FILE * in, char * str) inline
Definition at line 192 of file bonevertex.hpp.
References readChar().
Referenced by BoneVertex::readFromFile(), and V3d::readV3Dfile().