VREng: src/model/dxf.hpp File Reference
dxf.hpp File Reference
Classes
struct Point3D
struct Surface
Surface class.
struct Polygon
struct PolyMeshObj
struct SceneObj
struct DXF_token
struct DXF_file
struct DXF_rule
class Dxf
Dxf class.
Macros
#define FEQ(x, y) (fabs(x-y)<=(float)1e-06)
#define multPoint3D(p1, p2) ((p1!=NULL && p2!=NULL)?((p1->x*p2->x)+(p1->y*p2->y)+(p1->z*p2->z)):0;
#define distPoint3D(p1, p2) ((p1!=NULL && p2!=NULL)?(sqr(sqr(p2->x-p1->x) + sqr(p2->y-p1->y) + sqr(p2->z-p1->z)))?-1)
#define eqPoint3D(p1, p2) ((p1==p2)?TRUE:((p1!=NULL && p2!=NULL) && (FEQ(p1->x,p2->x) && FEQ(p1->y,p2->y) && FEQ(p1->z,p2->z))))
#define SRGB Point3D
#define POL_CLOSED 0
#define POL_OPENED 1
#define POL_POINT_VALS 0
#define POL_POINT_REFS 1
#define TOK_EQ 1
#define TOK_GR_EQ 2
#define TOK_DATA_EQ 3
#define funcRule(f) char (*f)(DXF_file *,DXF_rule *, DXF_token *)
Enumerations
enum DXF_gr_id {
START = 0, TEXT = 1, NAME0 = 2, NAME1 = 3,
NAMEN = 4, ENTITY_HANDLE = 5, LINE_TYPE = 6, TEXT_STYLE = 7,
LAYER_NAME = 8, VAR_NAME = 9, X0 = 10, X1 = 11,
X2 = 12, X3 = 13, X4 = 14, X5 = 15,
X6 = 16, X7 = 17, XN = 18, Y0 = 20,
Y1 = 21, Y2 = 22, Y3 = 23, Y4 = 24,
Y5 = 25, Y6 = 26, Y7 = 27, YN = 28,
Z0 = 30, Z1 = 31, Z2 = 32, Z3 = 33,
Z4 = 34, Z5 = 35, Z6 = 36, ZN = 37,
ELEVATION = 38, THICKNESS = 39, FLOATVAL0 = 40, FLOATVAL1 = 41,
FLOATVAL2 = 42, FLOATVAL3 = 43, FLOATVAL4 = 44, FLOATVAL5 = 45,
FLOATVAL6 = 47, FLOATVAL7 = 47, FLOATVALN = 48, REPEAT = 49,
ANG0 = 50, ANG1 = 51, ANG2 = 52, ANG3 = 53,
ANG4 = 54, ANG5 = 55, ANG6 = 56, ANG7 = 57,
ANGN = 58, COLORNUM = 62, ENTITIES = 66, ENT_SPAC = 67,
VIEWPORT_STATE = 68, VIEWPORT_ID = 69, FLAGS70 = 70, FLAGS71 = 71,
FLAGS72 = 72, FLAGS73 = 73, FLAGS74 = 74, FLAGS75 = 75,
FLAGS76 = 76, FLAGS77 = 77, FLAGS7N = 78, EXTRUC_DIR_X = 210,
EXTRUC_DIR_Y = 210, EXTRUC_DIR_Z = 210, COMMENT = 999, STRING = 1000,
REG_AP_NAME = 1001, EXT_ENTITIE_ST = 1002, EXT_ENTITIE_X_CORD = 1010, EXT_ENTITIE_Y_CORD = 1020,
EXT_ENTITIE_Z_CORD = 1030, EXT_ENTITIE_X_POS = 1011, EXT_ENTITIE_Y_POS = 1021, EXT_ENTITIE_Z_POS = 1031,
EXT_ENTITIE_X_DISP = 1012, EXT_ENTITIE_Y_DISP = 1022, EXT_ENTITIE_Z_DISP = 1032, EXT_ENTITIE_X_DIR = 1013,
EXT_ENTITIE_Y_DIR = 1023, EXT_ENTITIE_Z_DIR = 1033, EXT_ENTITIE_FLOAT = 1040, EXT_ENTITIE_DIST = 1041,
EXT_ENTITIE_SCALE = 1042, EXT_ENTITIE_16INT = 1070, EXT_ENTITIE_32LONG = 1071, DXF_FILE = 9999
}
Functions
Point3D * newPoint3D (float x, float y, float z)
Point3D * deletePoint3D (Point3D *p)
Point3D * setPoint3D (Point3D *p, float x, float y, float z)
Point3D * copyPoint3D (Point3D *p1, Point3D *p2)
Point3D * addPoint3D (Point3D *p1, Point3D *p2)
Point3D * subPoint3D (Point3D *p1, Point3D *p2)
Point3D * addPoint3DFPOINT (Point3D *p, float s)
Point3D * multPoint3DFPOINT (Point3D *p, float f)
Surface * newSurface (float ambient, float diffuse, float brilliance, float specular, float roughness, float reflection, float refraction)
Surface * deleteSurface (Surface *surf)
Surface * setSurface (Surface *surf, float ambient, float diffuse, float brilliance, float specular, float roughness, float reflection, float refraction)
Surface * copySurface (Surface *surf1, Surface *surf2)
char * _xstrclean (char *in, char *tok)
char * _xstrlwr (char *in)
char * _xstrupr (char *in)
Polygon * newPolygon (char pol_type, char points_type, SRGB *color)
Polygon * deletePolygon (Polygon *pol)
int addPolygonPoint (Polygon *pol, Point3D *p)
int delPolygonPoint (Polygon *pol)
int insertPolygonPoint (Polygon *pol, Point3D *p, int pos)
int removePolygonPoint (Polygon *pol, int pos)
bool changePolygonType (Polygon *pol, char pol_type)
bool changePoligonPointsType (Polygon *pol, char points_type)
Point3D * maxPolygon (Polygon *pol)
Point3D * minPolygon (Polygon *pol)
PolyMeshObj * newPolyMesh (char *name, SRGB *color)
PolyMeshObj * deletePolyMesh (PolyMeshObj *pmesh)
PolyMeshObj * changePolyMeshObjName (PolyMeshObj *pmesh, char *name)
int addPolyMeshObjPolygon (PolyMeshObj *pmesh, Polygon *pol)
int delPolyMeshObjPolygon (PolyMeshObj *pmesh)
int insertPolyMeshObjPolygon (PolyMeshObj *pmesh, Polygon *pol, int pos)
int removePolyMeshObjPolygon (PolyMeshObj *pmesh, int pos)
int addPolyMeshObjPoint (PolyMeshObj *pmesh, Point3D *p)
int delPolyMeshObjPoint (PolyMeshObj *pmesh)
int insertPolyMeshObjPoint (PolyMeshObj *pmesh, Point3D *p, int pos)
int removePolyMeshObjPoint (PolyMeshObj *pmesh, int pos)
int addPolyMeshObjPointEx (PolyMeshObj *pmesh, Point3D *p)
int addPolyMeshObjPolygonPoint (PolyMeshObj *pmesh, Point3D *p)
int delPolyMeshObjPolygonPoint (PolyMeshObj *pmesh)
int insertPolyMeshObjPolygonPoint (PolyMeshObj *pmesh, int pol_num, Point3D *p, int point_num)
int removePolyMeshObjPolygonPoint (PolyMeshObj *pmesh, int pol_num, int point_num)
Point3D * maxPolyMeshObj (PolyMeshObj *pmesh)
Point3D * minPolyMeshObj (PolyMeshObj *pmesh)
SceneObj * newScene (char *name, SRGB *color)
SceneObj * deleteScene (SceneObj *scene)
SceneObj * changeSceneObjName (SceneObj *scene, char *name)
int addSceneObjPolyMesh (SceneObj *scene, PolyMeshObj *pmesh)
int delSceneObjPolyMesh (SceneObj *scene)
int insertSceneObjPolyMesh (SceneObj *scene, PolyMeshObj *pmesh, int pos)
int removeSceneObjPolyMesh (SceneObj *scene, int pos)
Point3D * maxSceneObj (SceneObj *scene)
Point3D * minSceneObj (SceneObj *scene)
DXF_token * newTokenDXF (DXF_gr_id gr_id, const char *data, int datalen)
DXF_token * deleteTokenDXF (DXF_token *tok)
DXF_token * readTokenDXF (FILE *fp)
DXF_token * writeTokenDXF (FILE *fp, DXF_token *tok)
char eqTokenDXF (DXF_token *tok1, DXF_token *tok2)
DXF_file * newDXF (char *filename)
DXF_file * deleteDXF (DXF_file *dxf)
DXF_file * openDXF (DXF_file *dxf)
DXF_file * closeDXF (DXF_file *dxf)
DXF_file * readDXF (DXF_file *dxf)
DXF_rule * newRuleDXF (DXF_token *tok, funcRule(parse))
DXF_rule * deleteRuleDXF (DXF_rule *rule)
int addRuleDXF (DXF_rule *rule, DXF_rule *rul)
int delRuleDXF (DXF_rule *rule)
DXF_rule * initParserRulesDXF ()
DXF_file * parseDXF (DXF_file *dxf, DXF_rule *rule)
char parseDXFfile (DXF_file *dxf, DXF_rule *rule, DXF_token *tok)
char parseDXFHEADER (DXF_file *dxf, DXF_rule *rule, DXF_token *tok)
char parseDXFENTITIES (DXF_file *dxf, DXF_rule *rule, DXF_token *tok)
char parseDXFBLOCKS (DXF_file *dxf, DXF_rule *rule, DXF_token *tok)
char parseDXF3DFACE (DXF_file *dxf, DXF_rule *rule, DXF_token *tok)
char parseDXFXVALS (DXF_file *dxf, DXF_rule *rule, DXF_token *tok)
char parseDXFYVALS (DXF_file *dxf, DXF_rule *rule, DXF_token *tok)
char parseDXFZVALS (DXF_file *dxf, DXF_rule *rule, DXF_token *tok)
Macro Definition Documentation
distPoint3D
#define distPoint3D (p1, p2) ((p1!=NULL && p2!=NULL)?(sqr(sqr(p2->x-p1->x) + sqr(p2->y-p1->y) + sqr(p2->z-p1->z)))?-1)
Definition at line 82 of file dxf.hpp.
eqPoint3D
#define eqPoint3D (p1, p2) ((p1==p2)?TRUE:((p1!=NULL && p2!=NULL) && (FEQ(p1->x,p2->x) && FEQ(p1->y,p2->y) && FEQ(p1->z,p2->z))))
Definition at line 83 of file dxf.hpp.
FEQ
#define FEQ (x, y) (fabs(x-y)<=(float)1e-06)
Definition at line 72 of file dxf.hpp.
funcRule
#define funcRule (f) char (*f)(DXF_file *,DXF_rule *, DXF_token *)
Definition at line 328 of file dxf.hpp.
multPoint3D
#define multPoint3D (p1, p2) ((p1!=NULL && p2!=NULL)?((p1->x*p2->x)+(p1->y*p2->y)+(p1->z*p2->z)):0;
Definition at line 79 of file dxf.hpp.
POL_CLOSED
#define POL_CLOSED 0
Definition at line 214 of file dxf.hpp.
POL_OPENED
#define POL_OPENED 1
Definition at line 215 of file dxf.hpp.
POL_POINT_REFS
#define POL_POINT_REFS 1
Definition at line 217 of file dxf.hpp.
POL_POINT_VALS
#define POL_POINT_VALS 0
Definition at line 216 of file dxf.hpp.
SRGB
#define SRGB Point3D
Definition at line 86 of file dxf.hpp.
TOK_DATA_EQ
#define TOK_DATA_EQ 3
Definition at line 311 of file dxf.hpp.
TOK_EQ
#define TOK_EQ 1
Definition at line 309 of file dxf.hpp.
TOK_GR_EQ
#define TOK_GR_EQ 2
Definition at line 310 of file dxf.hpp.
Enumeration Type Documentation
DXF_gr_id
enum DXF_gr_id
Enumerator
START
TEXT
NAME0
NAME1
NAMEN
ENTITY_HANDLE
LINE_TYPE
TEXT_STYLE
LAYER_NAME
VAR_NAME
X0
X1
X2
X3
X4
X5
X6
X7
XN
Y0
Y1
Y2
Y3
Y4
Y5
Y6
Y7
YN
Z0
Z1
Z2
Z3
Z4
Z5
Z6
ZN
ELEVATION
THICKNESS
FLOATVAL0
FLOATVAL1
FLOATVAL2
FLOATVAL3
FLOATVAL4
FLOATVAL5
FLOATVAL6
FLOATVAL7
FLOATVALN
REPEAT
ANG0
ANG1
ANG2
ANG3
ANG4
ANG5
ANG6
ANG7
ANGN
COLORNUM
ENTITIES
ENT_SPAC
VIEWPORT_STATE
VIEWPORT_ID
FLAGS70
FLAGS71
FLAGS72
FLAGS73
FLAGS74
FLAGS75
FLAGS76
FLAGS77
FLAGS7N
EXTRUC_DIR_X
EXTRUC_DIR_Y
EXTRUC_DIR_Z
COMMENT
STRING
REG_AP_NAME
EXT_ENTITIE_ST
EXT_ENTITIE_X_CORD
EXT_ENTITIE_Y_CORD
EXT_ENTITIE_Z_CORD
EXT_ENTITIE_X_POS
EXT_ENTITIE_Y_POS
EXT_ENTITIE_Z_POS
EXT_ENTITIE_X_DISP
EXT_ENTITIE_Y_DISP
EXT_ENTITIE_Z_DISP
EXT_ENTITIE_X_DIR
EXT_ENTITIE_Y_DIR
EXT_ENTITIE_Z_DIR
EXT_ENTITIE_FLOAT
EXT_ENTITIE_DIST
EXT_ENTITIE_SCALE
EXT_ENTITIE_16INT
EXT_ENTITIE_32LONG
DXF_FILE
Definition at line 108 of file dxf.hpp.
Function Documentation
_xstrclean()
char* _xstrclean (char * in, char * tok)
Definition at line 828 of file dxf.cpp.
Referenced by readTokenDXF().
_xstrlwr()
char* _xstrlwr (char * in)
Definition at line 841 of file dxf.cpp.
Referenced by changePolyMeshObjName(), and changeSceneObjName().
_xstrupr()
char* _xstrupr (char * in)
Definition at line 848 of file dxf.cpp.
Referenced by readTokenDXF().
addPoint3D()
Point3D* addPoint3D (Point3D * p1, Point3D * p2)
Definition at line 253 of file dxf.cpp.
References setPoint3D(), Point3D::x, Point3D::y, and Point3D::z.
addPoint3DFPOINT()
Point3D* addPoint3DFPOINT (Point3D * p, float s)
Definition at line 265 of file dxf.cpp.
References setPoint3D(), Point3D::x, Point3D::y, and Point3D::z.
addPolygonPoint()
int addPolygonPoint (Polygon * pol, Point3D * p)
Definition at line 346 of file dxf.cpp.
References copyPoint3D(), Polygon::num_points, Polygon::pnts, Polygon::points, Polygon::points_type, POL_POINT_VALS, and Polygon::refs.
Referenced by addPolyMeshObjPolygonPoint(), and insertPolygonPoint().
addPolyMeshObjPoint()
int addPolyMeshObjPoint (PolyMeshObj * pmesh, Point3D * p)
Definition at line 652 of file dxf.cpp.
References PolyMeshObj::num_points, and PolyMeshObj::points.
Referenced by addPolyMeshObjPointEx(), and insertPolyMeshObjPoint().
addPolyMeshObjPointEx()
int addPolyMeshObjPointEx (PolyMeshObj * pmesh, Point3D * p)
Definition at line 741 of file dxf.cpp.
References addPolyMeshObjPoint(), eqPoint3D, PolyMeshObj::num_points, and PolyMeshObj::points.
Referenced by parseDXF3DFACE().
addPolyMeshObjPolygon()
int addPolyMeshObjPolygon (PolyMeshObj * pmesh, Polygon * pol)
Definition at line 584 of file dxf.cpp.
References PolyMeshObj::num_polygons, and PolyMeshObj::polygons.
Referenced by insertPolyMeshObjPolygon(), and parseDXF3DFACE().
addPolyMeshObjPolygonPoint()
int addPolyMeshObjPolygonPoint (PolyMeshObj * pmesh, Point3D * p)
Definition at line 752 of file dxf.cpp.
References addPolygonPoint(), PolyMeshObj::num_polygons, and PolyMeshObj::polygons.
Referenced by parseDXF3DFACE().
addRuleDXF()
int addRuleDXF (DXF_rule * rule, DXF_rule * rul)
Definition at line 995 of file dxf.cpp.
Referenced by initParserRulesDXF().
addSceneObjPolyMesh()
int addSceneObjPolyMesh (SceneObj * scene, PolyMeshObj * pmesh)
Definition at line 1146 of file dxf.cpp.
References SceneObj::num_objects, and SceneObj::objects.
Referenced by insertSceneObjPolyMesh(), parseDXF3DFACE(), parseDXFBLOCKS(), and parseDXFENTITIES().
changePoligonPointsType()
bool changePoligonPointsType (Polygon * pol, char points_type)
Definition at line 461 of file dxf.cpp.
References copyPoint3D(), newPoint3D(), Polygon::num_points, Polygon::pnts, Polygon::points, Polygon::points_type, POL_POINT_REFS, POL_POINT_VALS, Polygon::refs, Point3D::x, Point3D::y, and Point3D::z.
changePolygonType()
bool changePolygonType (Polygon * pol, char pol_type)
Definition at line 453 of file dxf.cpp.
References Polygon::pol_type.
changePolyMeshObjName()
PolyMeshObj* changePolyMeshObjName (PolyMeshObj * pmesh, char * name)
Definition at line 572 of file dxf.cpp.
References _xstrlwr(), and PolyMeshObj::name.
Referenced by newPolyMesh().
changeSceneObjName()
SceneObj* changeSceneObjName (SceneObj * scene, char * name)
Definition at line 1134 of file dxf.cpp.
References _xstrlwr(), and SceneObj::name.
Referenced by newScene().
closeDXF()
DXF_file* closeDXF (DXF_file * dxf)
Definition at line 950 of file dxf.cpp.
References File::closeFile(), and DXF_file::fp.
copyPoint3D()
Point3D* copyPoint3D (Point3D * p1, Point3D * p2)
Definition at line 247 of file dxf.cpp.
References setPoint3D(), Point3D::x, Point3D::y, and Point3D::z.
Referenced by addPolygonPoint(), changePoligonPointsType(), Dxf::draw(), insertPolygonPoint(), maxPolygon(), maxPolyMeshObj(), maxSceneObj(), minPolygon(), minPolyMeshObj(), minSceneObj(), and removePolygonPoint().
copySurface()
Surface* copySurface (Surface * surf1, Surface * surf2)
Definition at line 308 of file dxf.cpp.
References Surface::ambient, Surface::brilliance, Surface::diffuse, Surface::reflection, Surface::refraction, Surface::roughness, setSurface(), and Surface::specular.
deleteDXF()
DXF_file* deleteDXF (DXF_file * dxf)
Definition at line 930 of file dxf.cpp.
References File::closeFile(), deleteScene(), DXF_file::filename, DXF_file::fp, and DXF_file::objects.
Referenced by Dxf::~Dxf().
deletePoint3D()
Point3D* deletePoint3D (Point3D * p)
Definition at line 231 of file dxf.cpp.
Referenced by deletePolygon(), deletePolyMesh(), delPolyMeshObjPoint(), Dxf::draw(), parseDXF3DFACE(), and removePolyMeshObjPoint().
deletePolygon()
Polygon* deletePolygon (Polygon * pol)
Definition at line 330 of file dxf.cpp.
References Polygon::color, deletePoint3D(), deleteSurface(), Polygon::num_points, Polygon::pnts, Polygon::points, Polygon::points_type, POL_POINT_VALS, Polygon::refs, and Polygon::surface.
Referenced by deletePolyMesh(), delPolyMeshObjPolygon(), and removePolyMeshObjPolygon().
deletePolyMesh()
PolyMeshObj* deletePolyMesh (PolyMeshObj * pmesh)
Definition at line 552 of file dxf.cpp.
References PolyMeshObj::color, deletePoint3D(), deletePolygon(), deleteSurface(), PolyMeshObj::num_points, PolyMeshObj::num_polygons, PolyMeshObj::points, PolyMeshObj::polygons, and PolyMeshObj::surface.
Referenced by deleteScene(), delSceneObjPolyMesh(), and removeSceneObjPolyMesh().
deleteRuleDXF()
DXF_rule* deleteRuleDXF (DXF_rule * rule)
Definition at line 984 of file dxf.cpp.
References deleteRuleDXF(), and deleteTokenDXF().
Referenced by deleteRuleDXF(), delRuleDXF(), and readDXF().
deleteScene()
SceneObj* deleteScene (SceneObj * scene)
Definition at line 1120 of file dxf.cpp.
References deletePolyMesh(), SceneObj::num_objects, and SceneObj::objects.
Referenced by deleteDXF().
deleteSurface()
Surface* deleteSurface (Surface * surf)
Definition at line 285 of file dxf.cpp.
Referenced by deletePolygon(), and deletePolyMesh().
deleteTokenDXF()
DXF_token* deleteTokenDXF (DXF_token * tok)
Definition at line 866 of file dxf.cpp.
References DXF_token::data.
Referenced by deleteRuleDXF(), initParserRulesDXF(), and parseDXFfile().
delPolygonPoint()
int delPolygonPoint (Polygon * pol)
Definition at line 372 of file dxf.cpp.
References Polygon::num_points, Polygon::pnts, Polygon::points, Polygon::points_type, POL_POINT_VALS, and Polygon::refs.
Referenced by delPolyMeshObjPolygonPoint(), and removePolygonPoint().
delPolyMeshObjPoint()
int delPolyMeshObjPoint (PolyMeshObj * pmesh)
Definition at line 666 of file dxf.cpp.
References deletePoint3D(), Polygon::num_points, PolyMeshObj::num_points, PolyMeshObj::num_polygons, Polygon::points, PolyMeshObj::points, POL_POINT_REFS, Polygon::pol_type, PolyMeshObj::polygons, Polygon::refs, and removePolygonPoint().
Referenced by removePolyMeshObjPoint().
delPolyMeshObjPolygon()
int delPolyMeshObjPolygon (PolyMeshObj * pmesh)
Definition at line 599 of file dxf.cpp.
References deletePolygon(), PolyMeshObj::num_polygons, and PolyMeshObj::polygons.
Referenced by removePolyMeshObjPolygon().
delPolyMeshObjPolygonPoint()
int delPolyMeshObjPolygonPoint (PolyMeshObj * pmesh)
Definition at line 761 of file dxf.cpp.
References delPolygonPoint(), PolyMeshObj::num_polygons, and PolyMeshObj::polygons.
delRuleDXF()
int delRuleDXF (DXF_rule * rule)
Definition at line 1009 of file dxf.cpp.
References deleteRuleDXF().
delSceneObjPolyMesh()
int delSceneObjPolyMesh (SceneObj * scene)
Definition at line 1160 of file dxf.cpp.
References deletePolyMesh(), SceneObj::num_objects, and SceneObj::objects.
Referenced by removeSceneObjPolyMesh().
eqTokenDXF()
char eqTokenDXF (DXF_token * tok1, DXF_token * tok2)
Definition at line 906 of file dxf.cpp.
References DXF_token::data, FALSE, TOK_EQ, and TOK_GR_EQ.
Referenced by parseDXF3DFACE(), parseDXFBLOCKS(), parseDXFENTITIES(), parseDXFfile(), and parseDXFHEADER().
initParserRulesDXF()
DXF_rule* initParserRulesDXF ()
Definition at line 1021 of file dxf.cpp.
References addRuleDXF(), deleteTokenDXF(), DXF_FILE, NAME0, newRuleDXF(), newTokenDXF(), parseDXF3DFACE(), parseDXFBLOCKS(), parseDXFENTITIES(), parseDXFfile(), parseDXFHEADER(), parseDXFXVALS(), parseDXFYVALS(), parseDXFZVALS(), START, X0, Y0, and Z0.
Referenced by readDXF().
insertPolygonPoint()
int insertPolygonPoint (Polygon * pol, Point3D * p, int pos)
Definition at line 387 of file dxf.cpp.
References addPolygonPoint(), copyPoint3D(), Polygon::num_points, Polygon::pnts, Polygon::points, Polygon::points_type, POL_POINT_VALS, and Polygon::refs.
Referenced by insertPolyMeshObjPolygonPoint().
insertPolyMeshObjPoint()
int insertPolyMeshObjPoint (PolyMeshObj * pmesh, Point3D * p, int pos)
Definition at line 688 of file dxf.cpp.
References addPolyMeshObjPoint(), PolyMeshObj::num_points, and PolyMeshObj::points.
insertPolyMeshObjPolygon()
int insertPolyMeshObjPolygon (PolyMeshObj * pmesh, Polygon * pol, int pos)
Definition at line 611 of file dxf.cpp.
References addPolyMeshObjPolygon(), PolyMeshObj::num_polygons, and PolyMeshObj::polygons.
insertPolyMeshObjPolygonPoint()
int insertPolyMeshObjPolygonPoint (PolyMeshObj * pmesh, int pol_num, Point3D * p, int point_num)
Definition at line 770 of file dxf.cpp.
References insertPolygonPoint(), PolyMeshObj::num_polygons, and PolyMeshObj::polygons.
insertSceneObjPolyMesh()
int insertSceneObjPolyMesh (SceneObj * scene, PolyMeshObj * pmesh, int pos)
Definition at line 1172 of file dxf.cpp.
References addSceneObjPolyMesh(), SceneObj::num_objects, and SceneObj::objects.
maxPolygon()
Point3D* maxPolygon (Polygon * pol)
Definition at line 488 of file dxf.cpp.
References copyPoint3D(), newPoint3D(), Polygon::num_points, Polygon::pnts, Polygon::points, Polygon::points_type, POL_POINT_VALS, Polygon::refs, Point3D::x, Point3D::y, and Point3D::z.
maxPolyMeshObj()
Point3D* maxPolyMeshObj (PolyMeshObj * pmesh)
Definition at line 800 of file dxf.cpp.
References copyPoint3D(), newPoint3D(), PolyMeshObj::num_points, PolyMeshObj::points, Point3D::x, Point3D::y, and Point3D::z.
Referenced by maxSceneObj().
maxSceneObj()
Point3D* maxSceneObj (SceneObj * scene)
Definition at line 1214 of file dxf.cpp.
References copyPoint3D(), maxPolyMeshObj(), newPoint3D(), SceneObj::num_objects, SceneObj::objects, Point3D::x, Point3D::y, and Point3D::z.
minPolygon()
Point3D* minPolygon (Polygon * pol)
Definition at line 512 of file dxf.cpp.
References copyPoint3D(), newPoint3D(), Polygon::num_points, Polygon::pnts, Polygon::points, Polygon::points_type, POL_POINT_VALS, Polygon::refs, Point3D::x, Point3D::y, and Point3D::z.
minPolyMeshObj()
Point3D* minPolyMeshObj (PolyMeshObj * pmesh)
Definition at line 814 of file dxf.cpp.
References copyPoint3D(), newPoint3D(), PolyMeshObj::num_points, PolyMeshObj::points, Point3D::x, Point3D::y, and Point3D::z.
Referenced by minSceneObj().
minSceneObj()
Point3D* minSceneObj (SceneObj * scene)
Definition at line 1230 of file dxf.cpp.
References copyPoint3D(), minPolyMeshObj(), newPoint3D(), SceneObj::num_objects, SceneObj::objects, Point3D::x, Point3D::y, and Point3D::z.
multPoint3DFPOINT()
Point3D* multPoint3DFPOINT (Point3D * p, float f)
Definition at line 270 of file dxf.cpp.
References setPoint3D(), Point3D::x, Point3D::y, and Point3D::z.
newDXF()
DXF_file* newDXF (char * filename)
Definition at line 921 of file dxf.cpp.
References DXF_file::filename, DXF_file::fp, and DXF_file::objects.
Referenced by Dxf::httpReader().
newPoint3D()
Point3D* newPoint3D (float x, float y, float z)
Definition at line 225 of file dxf.cpp.
References setPoint3D().
Referenced by changePoligonPointsType(), Dxf::draw(), maxPolygon(), maxPolyMeshObj(), maxSceneObj(), minPolygon(), minPolyMeshObj(), minSceneObj(), parseDXF3DFACE(), parseDXFBLOCKS(), parseDXFENTITIES(), parseDXFXVALS(), parseDXFYVALS(), and parseDXFZVALS().
newPolygon()
Polygon* newPolygon (char pol_type, char points_type, SRGB * color)
Definition at line 318 of file dxf.cpp.
References color, Polygon::color, Polygon::num_points, Polygon::pnts, Polygon::points, Polygon::points_type, Polygon::pol_type, and Polygon::surface.
Referenced by parseDXF3DFACE().
newPolyMesh()
PolyMeshObj* newPolyMesh (char * name, SRGB * color)
Definition at line 537 of file dxf.cpp.
References changePolyMeshObjName(), color, PolyMeshObj::color, PolyMeshObj::name, PolyMeshObj::num_points, PolyMeshObj::num_polygons, PolyMeshObj::points, PolyMeshObj::polygons, and PolyMeshObj::surface.
Referenced by parseDXF3DFACE(), parseDXFBLOCKS(), and parseDXFENTITIES().
newRuleDXF()
DXF_rule* newRuleDXF (DXF_token * tok, funcRule(parse))
Definition at line 972 of file dxf.cpp.
References COMMENT, DXF_token::data, DXF_token::datalen, DXF_token::gr_id, newTokenDXF(), and parse.
Referenced by initParserRulesDXF().
newScene()
SceneObj* newScene (char * name, SRGB * color)
Definition at line 1108 of file dxf.cpp.
References changeSceneObjName(), color, SceneObj::color, SceneObj::name, SceneObj::num_objects, and SceneObj::objects.
Referenced by parseDXF3DFACE(), parseDXFBLOCKS(), and parseDXFENTITIES().
newSurface()
Surface* newSurface (float ambient, float diffuse, float brilliance, float specular, float roughness, float reflection, float refraction)
Definition at line 276 of file dxf.cpp.
References setSurface().
newTokenDXF()
DXF_token* newTokenDXF (DXF_gr_id gr_id, const char * data, int datalen)
Definition at line 856 of file dxf.cpp.
References DXF_token::data, DXF_token::datalen, and DXF_token::gr_id.
Referenced by initParserRulesDXF(), newRuleDXF(), parseDXFfile(), and readTokenDXF().
openDXF()
DXF_file* openDXF (DXF_file * dxf)
Definition at line 942 of file dxf.cpp.
References DXF_file::filename, DXF_file::fp, and File::openFile().
parseDXF()
DXF_file* parseDXF (DXF_file * dxf, DXF_rule * rule)
Definition at line 1092 of file dxf.cpp.
References DXF_file::fp, SceneObj::num_objects, DXF_file::objects, readTokenDXF(), and TRUE.
Referenced by readDXF().
parseDXF3DFACE()
char parseDXF3DFACE (DXF_file * dxf, DXF_rule * rule, DXF_token * tok)
Definition at line 1357 of file dxf.cpp.
References __CountCoordTok, __PointActTok, addPolyMeshObjPointEx(), addPolyMeshObjPolygon(), addPolyMeshObjPolygonPoint(), addSceneObjPolyMesh(), DXF_token::data, deletePoint3D(), eqTokenDXF(), FALSE, DXF_file::filename, newPoint3D(), newPolygon(), newPolyMesh(), newScene(), SceneObj::num_objects, PolyMeshObj::num_points, SceneObj::objects, DXF_file::objects, PolyMeshObj::points, POL_CLOSED, POL_POINT_REFS, TOK_DATA_EQ, TOK_EQ, and TRUE.
Referenced by initParserRulesDXF().
parseDXFBLOCKS()
char parseDXFBLOCKS (DXF_file * dxf, DXF_rule * rule, DXF_token * tok)
Definition at line 1324 of file dxf.cpp.
References addSceneObjPolyMesh(), DXF_token::data, eqTokenDXF(), FALSE, DXF_file::filename, newPoint3D(), newPolyMesh(), newScene(), DXF_file::objects, TOK_EQ, and TRUE.
Referenced by initParserRulesDXF().
parseDXFENTITIES()
char parseDXFENTITIES (DXF_file * dxf, DXF_rule * rule, DXF_token * tok)
Definition at line 1295 of file dxf.cpp.
References addSceneObjPolyMesh(), DXF_token::data, eqTokenDXF(), FALSE, DXF_file::filename, newPoint3D(), newPolyMesh(), newScene(), DXF_file::objects, TOK_EQ, and TRUE.
Referenced by initParserRulesDXF().
parseDXFfile()
char parseDXFfile (DXF_file * dxf, DXF_rule * rule, DXF_token * tok)
Definition at line 1248 of file dxf.cpp.
References deleteTokenDXF(), eqTokenDXF(), FALSE, newTokenDXF(), START, TOK_EQ, tokendsect, tokeof, toksect, and TRUE.
Referenced by initParserRulesDXF().
parseDXFHEADER()
char parseDXFHEADER (DXF_file * dxf, DXF_rule * rule, DXF_token * tok)
Definition at line 1283 of file dxf.cpp.
References eqTokenDXF(), FALSE, TOK_EQ, and TRUE.
Referenced by initParserRulesDXF().
parseDXFXVALS()
char parseDXFXVALS (DXF_file * dxf, DXF_rule * rule, DXF_token * tok)
Definition at line 1403 of file dxf.cpp.
References __CountCoordTok, __PointActTok, DXF_token::data, FALSE, DXF_token::gr_id, newPoint3D(), TRUE, Point3D::x, X0, and XN.
Referenced by initParserRulesDXF().
parseDXFYVALS()
char parseDXFYVALS (DXF_file * dxf, DXF_rule * rule, DXF_token * tok)
Definition at line 1416 of file dxf.cpp.
References __CountCoordTok, __PointActTok, DXF_token::data, FALSE, DXF_token::gr_id, newPoint3D(), TRUE, Point3D::y, Y0, and YN.
Referenced by initParserRulesDXF().
parseDXFZVALS()
char parseDXFZVALS (DXF_file * dxf, DXF_rule * rule, DXF_token * tok)
Definition at line 1429 of file dxf.cpp.
References __CountCoordTok, __PointActTok, DXF_token::data, FALSE, DXF_token::gr_id, newPoint3D(), TRUE, Point3D::z, Z0, and ZN.
Referenced by initParserRulesDXF().
readDXF()
DXF_file* readDXF (DXF_file * dxf)
Definition at line 958 of file dxf.cpp.
References deleteRuleDXF(), error(), initParserRulesDXF(), and parseDXF().
Referenced by Dxf::httpReader().
readTokenDXF()
DXF_token* readTokenDXF (FILE * fp)
Definition at line 875 of file dxf.cpp.
References _xstrclean(), _xstrupr(), and newTokenDXF().
Referenced by parseDXF().
removePolygonPoint()
int removePolygonPoint (Polygon * pol, int pos)
Definition at line 422 of file dxf.cpp.
References copyPoint3D(), delPolygonPoint(), Polygon::num_points, Polygon::pnts, Polygon::points, Polygon::points_type, POL_POINT_VALS, and Polygon::refs.
Referenced by delPolyMeshObjPoint(), removePolyMeshObjPoint(), and removePolyMeshObjPolygonPoint().
removePolyMeshObjPoint()
int removePolyMeshObjPoint (PolyMeshObj * pmesh, int pos)
Definition at line 709 of file dxf.cpp.
References deletePoint3D(), delPolyMeshObjPoint(), Polygon::num_points, PolyMeshObj::num_points, PolyMeshObj::num_polygons, Polygon::points, PolyMeshObj::points, POL_POINT_REFS, Polygon::pol_type, PolyMeshObj::polygons, Polygon::refs, and removePolygonPoint().
removePolyMeshObjPolygon()
int removePolyMeshObjPolygon (PolyMeshObj * pmesh, int pos)
Definition at line 631 of file dxf.cpp.
References deletePolygon(), delPolyMeshObjPolygon(), PolyMeshObj::num_polygons, and PolyMeshObj::polygons.
removePolyMeshObjPolygonPoint()
int removePolyMeshObjPolygonPoint (PolyMeshObj * pmesh, int pol_num, int point_num)
Definition at line 785 of file dxf.cpp.
References PolyMeshObj::num_polygons, PolyMeshObj::polygons, and removePolygonPoint().
removeSceneObjPolyMesh()
int removeSceneObjPolyMesh (SceneObj * scene, int pos)
Definition at line 1193 of file dxf.cpp.
References deletePolyMesh(), delSceneObjPolyMesh(), SceneObj::num_objects, and SceneObj::objects.
setPoint3D()
Point3D* setPoint3D (Point3D * p, float x, float y, float z)
Definition at line 237 of file dxf.cpp.
References Point3D::x, Point3D::y, and Point3D::z.
Referenced by addPoint3D(), addPoint3DFPOINT(), copyPoint3D(), multPoint3DFPOINT(), newPoint3D(), and subPoint3D().
setSurface()
Surface* setSurface (Surface * surf, float ambient, float diffuse, float brilliance, float specular, float roughness, float reflection, float refraction)
Definition at line 292 of file dxf.cpp.
References Surface::ambient, Surface::brilliance, Surface::diffuse, Surface::reflection, Surface::refraction, Surface::roughness, and Surface::specular.
Referenced by copySurface(), and newSurface().
subPoint3D()
Point3D* subPoint3D (Point3D * p1, Point3D * p2)
Definition at line 259 of file dxf.cpp.
References setPoint3D(), Point3D::x, Point3D::y, and Point3D::z.
Referenced by Dxf::draw().
writeTokenDXF()
DXF_token* writeTokenDXF (FILE * fp, DXF_token * tok)
Definition at line 893 of file dxf.cpp.
References DXF_token::data, and DXF_token::gr_id.