VREng: src/model/boneanim.cpp File Reference
boneanim.cpp File Reference
#include "vreng.hpp"
#include "boneanim.hpp"
Macros
#define __AXIS_SIZE__ 0.5f
Functions
void getDistanceFromAndOnBone (Vertex *vertex, BoneVertex *a, BoneVertex *b, float *time, float *dist)
void normalize (BoneLink **temporaryLink, int temporaryLinks)
void renderLocalCoordinate1 ()
void renderLocalCoordinate2 ()
void renderOneBone (BoneVertex *node)
Variables
int plainRendering = 1
int boneEditing = 0
int axisRendering = 0
char * selectedNodeName = NULL
Macro Definition Documentation
__AXIS_SIZE__
#define __AXIS_SIZE__ 0.5f
Definition at line 278 of file boneanim.cpp.
Function Documentation
getDistanceFromAndOnBone()
void getDistanceFromAndOnBone (Vertex * vertex, BoneVertex * a, BoneVertex * b, float * time, float * dist) inline
Definition at line 117 of file boneanim.cpp.
References CROP, dist, Vect3D::dotProduct(), BoneVertex::initialMatrix, and Vertex::initialPosition.
Referenced by BoneAnimator::getWeight().
normalize()
void normalize (BoneLink ** temporaryLink, int temporaryLinks)
Definition at line 156 of file boneanim.cpp.
References BoneLink::weight.
Referenced by BoneAnimator::generateLinkList(), and movable::init().
renderLocalCoordinate1()
void renderLocalCoordinate1 ()
Definition at line 285 of file boneanim.cpp.
References __AXIS_SIZE__.
Referenced by BoneAnimator::renderSkeletonNode().
renderLocalCoordinate2()
void renderLocalCoordinate2 ()
Definition at line 305 of file boneanim.cpp.
References __AXIS_SIZE__.
Referenced by BoneAnimator::renderSkeletonNode().
renderOneBone()
void renderOneBone (BoneVertex * node)
Definition at line 325 of file boneanim.cpp.
References BoneVertex::child, BoneVertex::children, BoneVertex::currentMatrix, BoneVertex::father, Vect3D::x, Vect3D::y, and Vect3D::z.
Referenced by BoneAnimator::render().
Variable Documentation
axisRendering
int axisRendering = 0
Definition at line 37 of file boneanim.cpp.
Referenced by BoneAnimator::render().
boneEditing
int boneEditing = 0
Definition at line 36 of file boneanim.cpp.
Referenced by BoneAnimator::animate(), and BoneAnimator::render().
plainRendering
int plainRendering = 1
Definition at line 35 of file boneanim.cpp.
Referenced by BoneAnimator::render().
selectedNodeName
char* selectedNodeName = NULL
Definition at line 38 of file boneanim.cpp.
Referenced by BoneAnimator::renderSkeletonNode().