VREng: src/model/bvh.cpp File Reference
bvh.cpp File Reference
#include <iostream>
#include <fstream>
#include <iterator>
#include <string>
#include <vector>
#include "vreng.hpp"
#include "bvh.hpp"
#include "http.hpp"
#include "cache.hpp"
#include "file.hpp"
#include "obj.hpp"
Functions
float dotProduct (const vector3f &v1, const vector3f &v2)
vector3f crossProduct (const vector3f &v1, const vector3f &v2)
bool operator== (const vector3f &v1, const vector3f &v2)
bool operator<= (const vector3f &v1, const vector3f &v2)
bool operator>= (const vector3f &v1, const vector3f &v2)
bool operator< (const vector3f &v1, const vector3f &v2)
bool operator> (const vector3f &v1, const vector3f &v2)
vector3f operator+ (const vector3f &v1, const vector3f &v2)
vector3f operator+ (const vector3f &v1, const float scalar)
vector3f operator- (const vector3f &v1, const vector3f &v2)
vector3f operator- (const vector3f &v1, const float scalar)
vector3f operator* (const vector3f &v1, const float scalar)
vector3f operator* (const vector3f &v1, const vector3f &v2)
vector3f operator/ (const vector3f &v1, const vector3f &v2)
vector3f operator/ (const vector3f &v1, const float scalar)
matrix16f operator+ (const matrix16f &m1, const matrix16f &m2)
matrix16f operator+ (const matrix16f &m1, const vector3f &v2)
matrix16f operator- (const matrix16f &m1, const matrix16f &m2)
matrix16f operator* (const matrix16f &m1, const float scalar)
matrix16f operator* (const matrix16f &m1, const matrix16f &m2)
matrix16f operator/ (const matrix16f &m1, const float scalar)
bool operator== (const matrix16f &m1, const matrix16f &m2)
float det (float f0, float f1, float f2, float f3)
matrix9f Star (vector3f a)
matrix9f operator+ (const matrix9f &m1, const matrix9f &m2)
matrix16f operator+ (const matrix16f &m1, const matrix9f &m2)
matrix9f operator- (const matrix9f &m1, const matrix9f &m2)
matrix9f operator* (const matrix9f &m1, const float scalar)
vector3f operator* (const matrix9f &m1, const vector3f &v2)
matrix9f operator* (const matrix9f &m1, const matrix9f &m2)
matrix9f operator* (const matrix9f &m1, const matrix16f &m2)
matrix9f operator* (const matrix16f &m1, const matrix9f &m2)
matrix9f operator/ (const matrix9f &m1, const float scalar)
bool operator== (const matrix9f &m1, const matrix9f &m2)
Function Documentation
crossProduct()
vector3f crossProduct (const vector3f & v1, const vector3f & v2)
Definition at line 812 of file bvh.cpp.
References vector3f::vertex.
Referenced by matrix16f::normalize().
det()
float det (float f0, float f1, float f2, float f3)
Definition at line 1363 of file bvh.cpp.
Referenced by Board::click(), Vrelet::click(), and matrix9f::inverse().
dotProduct()
float dotProduct (const vector3f & v1, const vector3f & v2)
Definition at line 807 of file bvh.cpp.
References vector3f::vertex.
operator*() [1/9]
matrix16f operator* (const matrix16f & m1, const float scalar)
Definition at line 1307 of file bvh.cpp.
References matrix16f::matrix.
operator*() [2/9]
matrix16f operator* (const matrix16f & m1, const matrix16f & m2)
Definition at line 1316 of file bvh.cpp.
References matrix16f::matrix.
operator*() [3/9]
matrix9f operator* (const matrix16f & m1, const matrix9f & m2)
Definition at line 1577 of file bvh.cpp.
References matrix16f::matrix, and matrix9f::matrix.
operator*() [4/9]
matrix9f operator* (const matrix9f & m1, const float scalar)
Definition at line 1518 of file bvh.cpp.
References matrix9f::matrix.
operator*() [5/9]
matrix9f operator* (const matrix9f & m1, const matrix16f & m2)
Definition at line 1557 of file bvh.cpp.
References matrix16f::matrix, and matrix9f::matrix.
operator*() [6/9]
matrix9f operator* (const matrix9f & m1, const matrix9f & m2)
Definition at line 1537 of file bvh.cpp.
References matrix9f::matrix.
operator*() [7/9]
vector3f operator* (const matrix9f & m1, const vector3f & v2)
Definition at line 1527 of file bvh.cpp.
References matrix9f::matrix, and vector3f::vertex.
operator*() [8/9]
vector3f operator* (const vector3f & v1, const float scalar)
Definition at line 922 of file bvh.cpp.
References vector3f::vertex.
operator*() [9/9]
vector3f operator* (const vector3f & v1, const vector3f & v2)
Definition at line 932 of file bvh.cpp.
References vector3f::vertex.
operator+() [1/6]
matrix16f operator+ (const matrix16f & m1, const matrix16f & m2)
Definition at line 1277 of file bvh.cpp.
References matrix16f::matrix.
operator+() [2/6]
matrix16f operator+ (const matrix16f & m1, const matrix9f & m2)
Definition at line 1488 of file bvh.cpp.
References matrix16f::matrix, and matrix9f::matrix.
operator+() [3/6]
matrix16f operator+ (const matrix16f & m1, const vector3f & v2)
Definition at line 1287 of file bvh.cpp.
References matrix16f::matrix, and vector3f::vertex.
operator+() [4/6]
matrix9f operator+ (const matrix9f & m1, const matrix9f & m2)
Definition at line 1479 of file bvh.cpp.
References matrix9f::matrix.
operator+() [5/6]
vector3f operator+ (const vector3f & v1, const float scalar)
Definition at line 892 of file bvh.cpp.
References vector3f::vertex.
operator+() [6/6]
vector3f operator+ (const vector3f & v1, const vector3f & v2)
Definition at line 882 of file bvh.cpp.
References vector3f::vertex.
operator-() [1/4]
matrix16f operator- (const matrix16f & m1, const matrix16f & m2)
Definition at line 1298 of file bvh.cpp.
References matrix16f::matrix.
operator-() [2/4]
matrix9f operator- (const matrix9f & m1, const matrix9f & m2)
Definition at line 1509 of file bvh.cpp.
References matrix9f::matrix.
operator-() [3/4]
vector3f operator- (const vector3f & v1, const float scalar)
Definition at line 912 of file bvh.cpp.
References vector3f::vertex.
operator-() [4/4]
vector3f operator- (const vector3f & v1, const vector3f & v2)
Definition at line 902 of file bvh.cpp.
References vector3f::vertex.
operator/() [1/4]
matrix16f operator/ (const matrix16f & m1, const float scalar)
Definition at line 1344 of file bvh.cpp.
References matrix16f::matrix.
operator/() [2/4]
matrix9f operator/ (const matrix9f & m1, const float scalar)
Definition at line 1597 of file bvh.cpp.
References matrix9f::matrix.
operator/() [3/4]
vector3f operator/ (const vector3f & v1, const float scalar)
Definition at line 952 of file bvh.cpp.
References vector3f::vertex.
operator/() [4/4]
vector3f operator/ (const vector3f & v1, const vector3f & v2)
Definition at line 942 of file bvh.cpp.
References vector3f::vertex.
operator<()
bool operator< (const vector3f & v1, const vector3f & v2)
Definition at line 868 of file bvh.cpp.
References vector3f::vertex.
operator<=()
bool operator<= (const vector3f & v1, const vector3f & v2)
Definition at line 854 of file bvh.cpp.
References vector3f::vertex.
operator==() [1/3]
bool operator== (const matrix16f & m1, const matrix16f & m2)
Definition at line 1353 of file bvh.cpp.
References matrix16f::matrix.
operator==() [2/3]
bool operator== (const matrix9f & m1, const matrix9f & m2)
Definition at line 1606 of file bvh.cpp.
References matrix9f::matrix.
operator==() [3/3]
bool operator== (const vector3f & v1, const vector3f & v2)
Definition at line 847 of file bvh.cpp.
References vector3f::vertex.
operator>()
bool operator> (const vector3f & v1, const vector3f & v2)
Definition at line 875 of file bvh.cpp.
References vector3f::vertex.
operator>=()
bool operator>= (const vector3f & v1, const vector3f & v2)
Definition at line 861 of file bvh.cpp.
References vector3f::vertex.
Star()
matrix9f Star (vector3f a)
Definition at line 1416 of file bvh.cpp.
References matrix9f::matrix, and vector3f::vertex.