VREng: src/model/bvh.hpp File Reference
bvh.hpp File Reference
Classes
class fileNotFound
class vector3f
Three floats in a array, lots of overloaded operators.
class matrix16f
Array of 16 floats in OpenGL conformant style.
class matrix9f
Smaller matrix for storing orientation but no location information.
struct triangleV
class movable
Mostly virtual class for any entity in the scene.
class triangleInd
class camera
Hold location, orientation, and mode of the viewer.
class light
Simple light point source.
class material
UVs and textures aren't supported, as I'm not really interested in them, being literally superficial in addition to me not having any easy-to-use UV mappers (lithunwrap is a pain).
class objloader
Parse in .obj's.
class rigid
Hold rigid body data, use objloader to load obj's.
class bvhPart
class Bvh
Macros
#define ROTATE_SLOWNESS 8
Functions
float det (float f0, float f1, float f2, float f3)
vector3f crossProduct (const vector3f &v1, const vector3f &v2)
Macro Definition Documentation
ROTATE_SLOWNESS
#define ROTATE_SLOWNESS 8
Definition at line 4 of file bvh.hpp.
Function Documentation
crossProduct()
vector3f crossProduct (const vector3f & v1, const vector3f & v2)
Definition at line 43 of file bvh.cpp.
References vector3f::vertex.
Referenced by matrix16f::normalize().
det()
float det (float f0, float f1, float f2, float f3)
Definition at line 1363 of file bvh.cpp.
Referenced by Board::click(), Vrelet::click(), and matrix9f::inverse().