VREng: src/model/vec3.cpp File Reference
vec3.cpp File Reference
#include "vreng.hpp"
#include "vec3.hpp"
Functions
Vec3 Vector (Vec3 p1, Vec3 p2)
calculates a vector between 2 points and returns the result
Vec3 AddVector (Vec3 v1, Vec3 v2)
adds 2 vectors together and returns the result
Vec3 DivideVectorByScaler (Vec3 v1, float val)
divides a vector by a single number (scalar) and returns the result
Vec3 Cross (Vec3 v1, Vec3 v2)
returns the cross product between 2 vectors
Vec3 Normalize (Vec3 v)
returns the normal of a vector
Function Documentation
AddVector()
Vec3 AddVector (Vec3 v1, Vec3 v2)
adds 2 vectors together and returns the result
Definition at line 43 of file vec3.cpp.
References Vec3::x, Vec3::y, and Vec3::z.
Referenced by _3ds::computeNormals(), Ase::computeNormals(), and Obj::computeNormals().
Cross()
Vec3 Cross (Vec3 v1, Vec3 v2)
returns the cross product between 2 vectors
Definition at line 65 of file vec3.cpp.
References Vec3::x, Vec3::y, and Vec3::z.
Referenced by _3ds::computeNormals(), Ase::computeNormals(), and Obj::computeNormals().
DivideVectorByScaler()
Vec3 DivideVectorByScaler (Vec3 v1, float val)
divides a vector by a single number (scalar) and returns the result
Definition at line 54 of file vec3.cpp.
References Vec3::x, Vec3::y, and Vec3::z.
Referenced by _3ds::computeNormals(), Ase::computeNormals(), and Obj::computeNormals().
Normalize()
Vec3 Normalize (Vec3 v)
returns the normal of a vector
Definition at line 76 of file vec3.cpp.
References Mag, Vec3::x, Vec3::y, and Vec3::z.
Referenced by _3ds::computeNormals(), Ase::computeNormals(), and Obj::computeNormals().
Vector()
Vec3 Vector (Vec3 p1, Vec3 p2)
calculates a vector between 2 points and returns the result
Definition at line 32 of file vec3.cpp.
References Vec3::x, Vec3::y, and Vec3::z.
Referenced by _3ds::computeNormals(), Ase::computeNormals(), and Obj::computeNormals().