VREng: Color Class Reference
Color Class Reference
Color class.
#include <color.hpp>
Public Member Functions
Color (const float *_color)
Color (float r, float g, float b, float a)
virtual ~Color ()
operator const GLfloat *const () const
bool operator== (const Color &) const
Static Public Member Functions
static void getRGB (const char *name, float *v)
Static Public Attributes
static const Color black
static const Color white
static const Color red
static const Color green
static const Color blue
static const Color grey
static const Color yellow
static const Color cyan
static const Color magenta
static const Color orange
static const Color pink
Private Attributes
GLfloat color [4]
Detailed Description
Color class.
Definition at line 28 of file color.hpp.
Constructor & Destructor Documentation
Color() [1/2]
Color::Color (const float * _color)
Definition at line 185 of file color.cpp.
References color.
Color() [2/2]
Color::Color (float r, float g, float b, float a)
Definition at line 191 of file color.cpp.
References color, and g.
~Color()
virtual Color::~Color () inline virtual
Definition at line 37 of file color.hpp.
Member Function Documentation
getRGB()
void Color::getRGB (const char * name, float * v) static
Definition at line 205 of file color.cpp.
References sRgb::color, sRgb::name, rgb, and strcasecmp().
Referenced by User::makeSolid(), and Parse::parseVector3f().
operator const GLfloat *const()
Color::operator const GLfloat *const () const inline
Definition at line 39 of file color.hpp.
References color.
operator==()
bool Color::operator== (const Color & c) const
Definition at line 196 of file color.cpp.
References color.
Member Data Documentation
black
const Color Color::black static
Definition at line 45 of file color.hpp.
blue
const Color Color::blue static
Definition at line 45 of file color.hpp.
color
GLfloat Color::color[4] private
Definition at line 30 of file color.hpp.
Referenced by Color(), operator const GLfloat *const(), and operator==().
cyan
const Color Color::cyan static
Definition at line 45 of file color.hpp.
green
const Color Color::green static
Definition at line 45 of file color.hpp.
Referenced by Draw::ray().
grey
const Color Color::grey static
Definition at line 45 of file color.hpp.
magenta
const Color Color::magenta static
Definition at line 45 of file color.hpp.
orange
const Color Color::orange static
Definition at line 45 of file color.hpp.
pink
const Color Color::pink static
Definition at line 45 of file color.hpp.
red
const Color Color::red static
Definition at line 45 of file color.hpp.
white
const Color Color::white static
Definition at line 45 of file color.hpp.
Referenced by Solid::setRay(), and User::setRayDirection().
yellow
const Color Color::yellow static
Definition at line 45 of file color.hpp.
The documentation for this class was generated from the following files:
src/vreng/color.hpp
src/vreng/color.cpp