VREng: Cache Class Reference
Cache Class Reference
#include <cache.hpp>
Static Public Member Functions
static int curl (const char *url, char *filename, const char opts[]=(char *)"cache")
Launchs curl on this url.
static int download (const char *url, char *filename, const char opts[]=(char *)"cache")
Launchs curl or wget on this url.
static int check (const char *url)
Checks url existence.
static int setCacheName (const char *url, char *cachefile)
Changes url name to cache filename.
static FILE * openCache (const char *url, Http *http)
Saves file into cache and opens it.
static bool inCache (const char *url)
Checks weither url is cached.
static void file (const char *url, char *filename)
Changes url name to filename.
static void file2url (const char *filename, char *url)
Change filename to urlname.
static void getCacheName (const char *url, std::string &cachename)
Gets absolute file name.
static char * getFilePath (const char *url)
Gets relative file name.
Detailed Description
Definition at line 32 of file cache.hpp.
Member Function Documentation
check()
int Cache::check (const char * url) static
Checks url existence.
Definition at line 225 of file cache.cpp.
References download().
Referenced by Gui::gotoWorld(), and Widgets::putMessage().
curl()
int Cache::curl (const char * url, char * filename, const char opts[] = (char *)"cache") static
Launchs curl on this url.
Definition at line 145 of file cache.cpp.
References File::closeFile(), error(), File::openFile(), size, and stringcmp().
Referenced by download().
download()
int Cache::download (const char * url, char * filename, const char opts[] = (char *)"cache") static
Launchs curl or wget on this url.
Definition at line 199 of file cache.cpp.
References Url::abs(), curl(), DBG_TOOL, setCacheName(), Wget::start(), trace(), and URL_LEN.
Referenced by check(), Ftp::get(), Icon::Icon(), Movie::mpegInit(), Icon::open(), postCgi(), Ps::print(), Icon::save(), Au::start(), Mpeg::start(), Office::start(), Pdf::start(), and Ps::view().
file()
void Cache::file (const char * url, char * filename) static
Changes url name to filename.
Definition at line 118 of file cache.cpp.
Referenced by Icon::destroy(), and Icon::quit().
file2url()
void Cache::file2url (const char * filename, char * url) static
Change filename to urlname.
Definition at line 131 of file cache.cpp.
Referenced by World::checkIcons().
getCacheName()
void Cache::getCacheName (const char * url, std::string & cachename) static
Gets absolute file name.
Definition at line 46 of file cache.cpp.
References Env::cache(), Global::env, and g.
Referenced by Bvh::Bvh(), and rigid::rigid().
getFilePath()
char * Cache::getFilePath (const char * url) static
Gets relative file name.
Definition at line 55 of file cache.cpp.
Referenced by Img::loadDDS(), Img::loadXPM(), and rigid::rigid().
inCache()
bool Cache::inCache (const char * url) static
Checks weither url is cached.
Definition at line 100 of file cache.cpp.
References File::closeFile(), error(), File::openFile(), PATH_LEN, and setCacheName().
Referenced by Http::httpOpen().
openCache()
FILE * Cache::openCache (const char * url, Http * http) static
Saves file into cache and opens it.
Definition at line 64 of file cache.cpp.
References File::closeFile(), error(), g, Http::getChar(), File::openFile(), PATH_LEN, Global::pref, progression(), Pref::refresh, and setCacheName().
Referenced by Reader::downloadInCache(), Book::httpReader(), _3ds::httpReader(), Avi::httpReader(), Bvh::httpReader(), Lwo::httpReader(), Md2::httpReader(), rigid::httpReader(), Face::httpReader(), Ase::httpReader(), Dxf::httpReader(), Hairs::httpReader(), Obj::httpReader(), Off::httpReader(), Txf::httpReader(), Body::httpReader(), Guy::httpReader(), Walls::httpReader(), Img::loadBMP(), Img::loadDDS(), Img::loadGIF(), Img::loadJPG(), Img::loadPCX(), Img::loadPGM(), Img::loadPNG(), Img::loadPPM(), Img::loadPSD(), Img::loadSGI(), Img::loadTGA(), Img::loadXBM(), Img::loadXPM(), and sourceHttpReader().
setCacheName()
int Cache::setCacheName (const char * url, char * cachefile) static
Changes url name to cache filename.
Definition at line 33 of file cache.cpp.
References Env::cache(), Global::env, and g.
Referenced by download(), Reader::getFilename(), Dxf::httpReader(), World::httpReader(), X3d::httpReader(), inCache(), Face::load(), openCache(), Widgets::saveCB(), and Wget::start().
The documentation for this class was generated from the following files:
src/vreng/cache.hpp
src/vreng/cache.cpp