VREng: src/vnc/auth.h File Reference
auth.h File Reference
#include "d3des.h"
Macros
#define MAXPWLEN 8
#define CHALLENGESIZE 16
Functions
int vncEncryptAndStorePasswd (char *passwd, char *fname)
char * vncDecryptPasswdFromFile (char *fname)
void vncEncryptBytes (unsigned char *bytes, char *passwd)
Macro Definition Documentation
CHALLENGESIZE
#define CHALLENGESIZE 16
Definition at line 44 of file auth.h.
MAXPWLEN
#define MAXPWLEN 8
Definition at line 43 of file auth.h.
Function Documentation
vncDecryptPasswdFromFile()
char* vncDecryptPasswdFromFile (char * fname)
Definition at line 88 of file auth.cpp.
References File::closeFile(), DE1, des(), deskey(), fixedkey, and File::openFile().
Referenced by VNCRFBproto::initialiseRFBConnection().
vncEncryptAndStorePasswd()
int vncEncryptAndStorePasswd (char * passwd, char * fname)
Definition at line 58 of file auth.cpp.
References File::closeFile(), des(), deskey(), EN0, fixedkey, and File::openFile().
Referenced by Vnc::convert(), and Vnc::parser().
vncEncryptBytes()
void vncEncryptBytes (unsigned char * bytes, char * passwd)