VREng: src/vnc/d3des.cpp File Reference
d3des.cpp File Reference
#include "d3des.h"
Functions
static void scrunch (unsigned char *, unsigned long *)
static void unscrun (unsigned long *, unsigned char *)
static void desfunc (unsigned long *, unsigned long *)
static void cookey (unsigned long *)
void deskey (unsigned char *key, int edf)
static void cookey (register unsigned long *raw1)
void cpkey (register unsigned long *into)
void usekey (register unsigned long *from)
void des (unsigned char *inblock, unsigned char *outblock)
static void scrunch (register unsigned char *outof, register unsigned long *into)
static void unscrun (register unsigned long *outof, register unsigned char *into)
static void desfunc (register unsigned long *block, register unsigned long *keys)
Variables
static unsigned long KnL [32] = { 0L }
static unsigned short bytebit [8]
static unsigned long bigbyte [24]
static unsigned char pc1 [56]
static unsigned char totrot [16]
static unsigned char pc2 [48]
static unsigned long SP1 [64]
static unsigned long SP2 [64]
static unsigned long SP3 [64]
static unsigned long SP4 [64]
static unsigned long SP5 [64]
static unsigned long SP6 [64]
static unsigned long SP7 [64]
static unsigned long SP8 [64]
Function Documentation
cookey() [1/2]
static void cookey (register unsigned long * raw1) static
Definition at line 102 of file d3des.cpp.
References usekey().
cookey() [2/2]
static void cookey (unsigned long *) static
Referenced by deskey().
cpkey()
void cpkey (register unsigned long * into)
Definition at line 124 of file d3des.cpp.
References KnL.
des()
void des (unsigned char * inblock, unsigned char * outblock)
Definition at line 142 of file d3des.cpp.
References desfunc(), KnL, scrunch(), and unscrun().
Referenced by vncDecryptPasswdFromFile(), vncEncryptAndStorePasswd(), and vncEncryptBytes().
desfunc() [1/2]
static void desfunc (register unsigned long * block, register unsigned long * keys) static
Definition at line 322 of file d3des.cpp.
References SP1, SP2, SP3, SP4, SP5, SP6, SP7, and SP8.
desfunc() [2/2]
static void desfunc (unsigned long * , unsigned long *) static
Referenced by des().
deskey()
void deskey (unsigned char * key, int edf)
Definition at line 67 of file d3des.cpp.
References bigbyte, bytebit, cookey(), DE1, pc1, pc2, and totrot.
Referenced by vncDecryptPasswdFromFile(), vncEncryptAndStorePasswd(), and vncEncryptBytes().
scrunch() [1/2]
static void scrunch (register unsigned char * outof, register unsigned long * into) static
Definition at line 152 of file d3des.cpp.
scrunch() [2/2]
static void scrunch (unsigned char * , unsigned long *) static
Referenced by des().
unscrun() [1/2]
static void unscrun (register unsigned long * outof, register unsigned char * into) static
Definition at line 165 of file d3des.cpp.
unscrun() [2/2]
static void unscrun (unsigned long * , unsigned char *) static
Referenced by des().
usekey()
void usekey (register unsigned long * from)
Definition at line 133 of file d3des.cpp.
References KnL.
Referenced by cookey().
Variable Documentation
bigbyte
unsigned long bigbyte[24] static
Initial value:
= {
  0x800000L,  0x400000L,  0x200000L,  0x100000L,
  0x80000L, 0x40000L, 0x20000L, 0x10000L,
  0x8000L,  0x4000L,  0x2000L,  0x1000L,
  0x800L,   0x400L,   0x200L,   0x100L,
  0x80L,    0x40L,    0x20L,    0x10L,
  0x8L,   0x4L,   0x2L,   0x1L  }
Definition at line 42 of file d3des.cpp.
Referenced by deskey().
bytebit
unsigned short bytebit[8] static
Initial value:
= {
  01, 02, 04, 010, 020, 040, 0100, 0200 }
Definition at line 39 of file d3des.cpp.
Referenced by deskey().
KnL
unsigned long KnL[32] = { 0L } static
Definition at line 35 of file d3des.cpp.
Referenced by cpkey(), des(), and usekey().
pc1
unsigned char pc1[56] static
Initial value:
= {
  56, 48, 40, 32, 24, 16,  8,  0, 57, 49, 41, 33, 25, 17,
   9,  1, 58, 50, 42, 34, 26, 18, 10,  2, 59, 51, 43, 35,
  62, 54, 46, 38, 30, 22, 14,  6, 61, 53, 45, 37, 29, 21,
  13,  5, 60, 52, 44, 36, 28, 20, 12,  4, 27, 19, 11,  3 }
Definition at line 52 of file d3des.cpp.
Referenced by deskey().
pc2
unsigned char pc2[48] static
Initial value:
= {
  13, 16, 10, 23,  0,  4,  2, 27, 14,  5, 20,  9,
  22, 18, 11,  3, 25,  7, 15,  6, 26, 19, 12,  1,
  40, 51, 30, 36, 46, 54, 29, 39, 50, 44, 32, 47,
  43, 48, 38, 55, 33, 52, 45, 41, 49, 35, 28, 31 }
Definition at line 61 of file d3des.cpp.
Referenced by deskey().
SP1
unsigned long SP1[64] static
Initial value:
= {
  0x01010400L, 0x00000000L, 0x00010000L, 0x01010404L,
  0x01010004L, 0x00010404L, 0x00000004L, 0x00010000L,
  0x00000400L, 0x01010400L, 0x01010404L, 0x00000400L,
  0x01000404L, 0x01010004L, 0x01000000L, 0x00000004L,
  0x00000404L, 0x01000400L, 0x01000400L, 0x00010400L,
  0x00010400L, 0x01010000L, 0x01010000L, 0x01000404L,
  0x00010004L, 0x01000004L, 0x01000004L, 0x00010004L,
  0x00000000L, 0x00000404L, 0x00010404L, 0x01000000L,
  0x00010000L, 0x01010404L, 0x00000004L, 0x01010000L,
  0x01010400L, 0x01000000L, 0x01000000L, 0x00000400L,
  0x01010004L, 0x00010000L, 0x00010400L, 0x01000004L,
  0x00000400L, 0x00000004L, 0x01000404L, 0x00010404L,
  0x01010404L, 0x00010004L, 0x01010000L, 0x01000404L,
  0x01000004L, 0x00000404L, 0x00010404L, 0x01010400L,
  0x00000404L, 0x01000400L, 0x01000400L, 0x00000000L,
  0x00010004L, 0x00010400L, 0x00000000L, 0x01010004L }
Definition at line 178 of file d3des.cpp.
Referenced by desfunc().
SP2
unsigned long SP2[64] static
Initial value:
= {
  0x80108020L, 0x80008000L, 0x00008000L, 0x00108020L,
  0x00100000L, 0x00000020L, 0x80100020L, 0x80008020L,
  0x80000020L, 0x80108020L, 0x80108000L, 0x80000000L,
  0x80008000L, 0x00100000L, 0x00000020L, 0x80100020L,
  0x00108000L, 0x00100020L, 0x80008020L, 0x00000000L,
  0x80000000L, 0x00008000L, 0x00108020L, 0x80100000L,
  0x00100020L, 0x80000020L, 0x00000000L, 0x00108000L,
  0x00008020L, 0x80108000L, 0x80100000L, 0x00008020L,
  0x00000000L, 0x00108020L, 0x80100020L, 0x00100000L,
  0x80008020L, 0x80100000L, 0x80108000L, 0x00008000L,
  0x80100000L, 0x80008000L, 0x00000020L, 0x80108020L,
  0x00108020L, 0x00000020L, 0x00008000L, 0x80000000L,
  0x00008020L, 0x80108000L, 0x00100000L, 0x80000020L,
  0x00100020L, 0x80008020L, 0x80000020L, 0x00100020L,
  0x00108000L, 0x00000000L, 0x80008000L, 0x00008020L,
  0x80000000L, 0x80100020L, 0x80108020L, 0x00108000L }
Definition at line 196 of file d3des.cpp.
Referenced by desfunc().
SP3
unsigned long SP3[64] static
Initial value:
= {
  0x00000208L, 0x08020200L, 0x00000000L, 0x08020008L,
  0x08000200L, 0x00000000L, 0x00020208L, 0x08000200L,
  0x00020008L, 0x08000008L, 0x08000008L, 0x00020000L,
  0x08020208L, 0x00020008L, 0x08020000L, 0x00000208L,
  0x08000000L, 0x00000008L, 0x08020200L, 0x00000200L,
  0x00020200L, 0x08020000L, 0x08020008L, 0x00020208L,
  0x08000208L, 0x00020200L, 0x00020000L, 0x08000208L,
  0x00000008L, 0x08020208L, 0x00000200L, 0x08000000L,
  0x08020200L, 0x08000000L, 0x00020008L, 0x00000208L,
  0x00020000L, 0x08020200L, 0x08000200L, 0x00000000L,
  0x00000200L, 0x00020008L, 0x08020208L, 0x08000200L,
  0x08000008L, 0x00000200L, 0x00000000L, 0x08020008L,
  0x08000208L, 0x00020000L, 0x08000000L, 0x08020208L,
  0x00000008L, 0x00020208L, 0x00020200L, 0x08000008L,
  0x08020000L, 0x08000208L, 0x00000208L, 0x08020000L,
  0x00020208L, 0x00000008L, 0x08020008L, 0x00020200L }
Definition at line 214 of file d3des.cpp.
Referenced by desfunc().
SP4
unsigned long SP4[64] static
Initial value:
= {
  0x00802001L, 0x00002081L, 0x00002081L, 0x00000080L,
  0x00802080L, 0x00800081L, 0x00800001L, 0x00002001L,
  0x00000000L, 0x00802000L, 0x00802000L, 0x00802081L,
  0x00000081L, 0x00000000L, 0x00800080L, 0x00800001L,
  0x00000001L, 0x00002000L, 0x00800000L, 0x00802001L,
  0x00000080L, 0x00800000L, 0x00002001L, 0x00002080L,
  0x00800081L, 0x00000001L, 0x00002080L, 0x00800080L,
  0x00002000L, 0x00802080L, 0x00802081L, 0x00000081L,
  0x00800080L, 0x00800001L, 0x00802000L, 0x00802081L,
  0x00000081L, 0x00000000L, 0x00000000L, 0x00802000L,
  0x00002080L, 0x00800080L, 0x00800081L, 0x00000001L,
  0x00802001L, 0x00002081L, 0x00002081L, 0x00000080L,
  0x00802081L, 0x00000081L, 0x00000001L, 0x00002000L,
  0x00800001L, 0x00002001L, 0x00802080L, 0x00800081L,
  0x00002001L, 0x00002080L, 0x00800000L, 0x00802001L,
  0x00000080L, 0x00800000L, 0x00002000L, 0x00802080L }
Definition at line 232 of file d3des.cpp.
Referenced by desfunc().
SP5
unsigned long SP5[64] static
Initial value:
= {
  0x00000100L, 0x02080100L, 0x02080000L, 0x42000100L,
  0x00080000L, 0x00000100L, 0x40000000L, 0x02080000L,
  0x40080100L, 0x00080000L, 0x02000100L, 0x40080100L,
  0x42000100L, 0x42080000L, 0x00080100L, 0x40000000L,
  0x02000000L, 0x40080000L, 0x40080000L, 0x00000000L,
  0x40000100L, 0x42080100L, 0x42080100L, 0x02000100L,
  0x42080000L, 0x40000100L, 0x00000000L, 0x42000000L,
  0x02080100L, 0x02000000L, 0x42000000L, 0x00080100L,
  0x00080000L, 0x42000100L, 0x00000100L, 0x02000000L,
  0x40000000L, 0x02080000L, 0x42000100L, 0x40080100L,
  0x02000100L, 0x40000000L, 0x42080000L, 0x02080100L,
  0x40080100L, 0x00000100L, 0x02000000L, 0x42080000L,
  0x42080100L, 0x00080100L, 0x42000000L, 0x42080100L,
  0x02080000L, 0x00000000L, 0x40080000L, 0x42000000L,
  0x00080100L, 0x02000100L, 0x40000100L, 0x00080000L,
  0x00000000L, 0x40080000L, 0x02080100L, 0x40000100L }
Definition at line 250 of file d3des.cpp.
Referenced by desfunc().
SP6
unsigned long SP6[64] static
Initial value:
= {
  0x20000010L, 0x20400000L, 0x00004000L, 0x20404010L,
  0x20400000L, 0x00000010L, 0x20404010L, 0x00400000L,
  0x20004000L, 0x00404010L, 0x00400000L, 0x20000010L,
  0x00400010L, 0x20004000L, 0x20000000L, 0x00004010L,
  0x00000000L, 0x00400010L, 0x20004010L, 0x00004000L,
  0x00404000L, 0x20004010L, 0x00000010L, 0x20400010L,
  0x20400010L, 0x00000000L, 0x00404010L, 0x20404000L,
  0x00004010L, 0x00404000L, 0x20404000L, 0x20000000L,
  0x20004000L, 0x00000010L, 0x20400010L, 0x00404000L,
  0x20404010L, 0x00400000L, 0x00004010L, 0x20000010L,
  0x00400000L, 0x20004000L, 0x20000000L, 0x00004010L,
  0x20000010L, 0x20404010L, 0x00404000L, 0x20400000L,
  0x00404010L, 0x20404000L, 0x00000000L, 0x20400010L,
  0x00000010L, 0x00004000L, 0x20400000L, 0x00404010L,
  0x00004000L, 0x00400010L, 0x20004010L, 0x00000000L,
  0x20404000L, 0x20000000L, 0x00400010L, 0x20004010L }
Definition at line 268 of file d3des.cpp.
Referenced by desfunc().
SP7
unsigned long SP7[64] static
Initial value:
= {
  0x00200000L, 0x04200002L, 0x04000802L, 0x00000000L,
  0x00000800L, 0x04000802L, 0x00200802L, 0x04200800L,
  0x04200802L, 0x00200000L, 0x00000000L, 0x04000002L,
  0x00000002L, 0x04000000L, 0x04200002L, 0x00000802L,
  0x04000800L, 0x00200802L, 0x00200002L, 0x04000800L,
  0x04000002L, 0x04200000L, 0x04200800L, 0x00200002L,
  0x04200000L, 0x00000800L, 0x00000802L, 0x04200802L,
  0x00200800L, 0x00000002L, 0x04000000L, 0x00200800L,
  0x04000000L, 0x00200800L, 0x00200000L, 0x04000802L,
  0x04000802L, 0x04200002L, 0x04200002L, 0x00000002L,
  0x00200002L, 0x04000000L, 0x04000800L, 0x00200000L,
  0x04200800L, 0x00000802L, 0x00200802L, 0x04200800L,
  0x00000802L, 0x04000002L, 0x04200802L, 0x04200000L,
  0x00200800L, 0x00000000L, 0x00000002L, 0x04200802L,
  0x00000000L, 0x00200802L, 0x04200000L, 0x00000800L,
  0x04000002L, 0x04000800L, 0x00000800L, 0x00200002L }
Definition at line 286 of file d3des.cpp.
Referenced by desfunc().
SP8
unsigned long SP8[64] static
Initial value:
= {
  0x10001040L, 0x00001000L, 0x00040000L, 0x10041040L,
  0x10000000L, 0x10001040L, 0x00000040L, 0x10000000L,
  0x00040040L, 0x10040000L, 0x10041040L, 0x00041000L,
  0x10041000L, 0x00041040L, 0x00001000L, 0x00000040L,
  0x10040000L, 0x10000040L, 0x10001000L, 0x00001040L,
  0x00041000L, 0x00040040L, 0x10040040L, 0x10041000L,
  0x00001040L, 0x00000000L, 0x00000000L, 0x10040040L,
  0x10000040L, 0x10001000L, 0x00041040L, 0x00040000L,
  0x00041040L, 0x00040000L, 0x10041000L, 0x00001000L,
  0x00000040L, 0x10040040L, 0x00001000L, 0x00041040L,
  0x10001000L, 0x00000040L, 0x10000040L, 0x10040000L,
  0x10040040L, 0x10000000L, 0x00040000L, 0x10001040L,
  0x00000000L, 0x10041040L, 0x00040040L, 0x10000040L,
  0x10040000L, 0x10001000L, 0x10001040L, 0x00000000L,
  0x10041040L, 0x00041000L, 0x00041000L, 0x00001040L,
  0x00001040L, 0x00040040L, 0x10000000L, 0x10041000L }
Definition at line 304 of file d3des.cpp.
Referenced by desfunc().
totrot
unsigned char totrot[16] static
Initial value:
= {
  1,2,4,6,8,10,12,14,15,17,19,21,23,25,27,28 }
Definition at line 58 of file d3des.cpp.
Referenced by deskey().