VREng: src/vnc/auth.cpp File Reference
auth.cpp File Reference
#include "vreng.hpp"
#include "auth.h"
#include "file.hpp"
Functions
int vncEncryptAndStorePasswd (char *passwd, char *fname)
char * vncDecryptPasswdFromFile (char *fname)
void vncEncryptBytes (uint8_t *bytes, char *passwd)
Variables
uint8_t fixedkey [8] = {23,82,107,6,35,78,88,7}
Function Documentation
vncDecryptPasswdFromFile()
char* vncDecryptPasswdFromFile (char * fname)
Definition at line 88 of file auth.cpp.
References File::closeFile(), DE1, des(), deskey(), fixedkey, and File::openFile().
Referenced by VNCRFBproto::initialiseRFBConnection().
vncEncryptAndStorePasswd()
int vncEncryptAndStorePasswd (char * passwd, char * fname)
Definition at line 58 of file auth.cpp.
References File::closeFile(), des(), deskey(), EN0, fixedkey, and File::openFile().
Referenced by Vnc::convert(), and Vnc::parser().
vncEncryptBytes()
void vncEncryptBytes (uint8_t * bytes, char * passwd)
Definition at line 114 of file auth.cpp.
References CHALLENGESIZE, des(), deskey(), and EN0.
Referenced by VNCRFBproto::initialiseRFBConnection().
Variable Documentation
fixedkey
uint8_t fixedkey[8] = {23,82,107,6,35,78,88,7}
Definition at line 52 of file auth.cpp.
Referenced by vncDecryptPasswdFromFile(), and vncEncryptAndStorePasswd().