VREng: Env Class Reference
Env Class Reference
Env class.
#include <env.hpp>
Public Member Functions
Env ()
constructor
char * cwd ()
char * dir ()
char * prefs ()
char * cache ()
char * passwd ()
char * icons ()
char * menu ()
char * worldmarks ()
char * sysname ()
char * relname ()
char * machname ()
void cleanCacheByExt (const char *ext)
void cleanCacheByTime (time_t cachetime)
Private Member Functions
void sysinfo ()
void initDirs ()
Private Attributes
char vrengdir [PATH_LEN]
char vrengcwd [PATH_LEN]
char vrengprefs [PATH_LEN]
char vrengmenu [PATH_LEN]
char vrengicons [PATH_LEN]
char vrengworldmarks [PATH_LEN]
char vrengpasswd [PATH_LEN]
char vrengcache [PATH_LEN]
char systemname [9]
char releasename [9]
char machinename [32]
Detailed Description
Env class.
Definition at line 28 of file env.hpp.
Constructor & Destructor Documentation
Env()
Env::Env ()
constructor
Definition at line 25 of file env.cpp.
References initDirs(), machinename, releasename, sysinfo(), and systemname.
Member Function Documentation
cache()
char * Env::cache ()
Definition at line 59 of file env.cpp.
References vrengcache.
Referenced by Cache::getCacheName(), and Cache::setCacheName().
cleanCacheByExt()
void Env::cleanCacheByExt (const char * ext)
Definition at line 162 of file env.cpp.
References dirent, vrengcache, and vrengcwd.
Referenced by World::init().
cleanCacheByTime()
void Env::cleanCacheByTime (time_t cachetime)
Definition at line 191 of file env.cpp.
References dirent, vrengcache, and vrengcwd.
Referenced by Pref::parse().
cwd()
char * Env::cwd ()
Definition at line 49 of file env.cpp.
References vrengcwd.
Referenced by World::checkIcons(), Icon::destroy(), Icon::quit(), and Icon::save().
dir()
char * Env::dir ()
Definition at line 54 of file env.cpp.
References vrengdir.
Referenced by printlog(), and writelog().
icons()
char * Env::icons ()
Definition at line 69 of file env.cpp.
References vrengicons.
Referenced by World::checkIcons(), Icon::destroy(), and Icon::quit().
initDirs()
void Env::initDirs () private
Definition at line 120 of file env.cpp.
References PATH_LEN, vrengcache, vrengcwd, vrengdir, vrengicons, vrengmenu, vrengpasswd, vrengprefs, and vrengworldmarks.
Referenced by Env().
machname()
char * Env::machname ()
Definition at line 99 of file env.cpp.
References machinename.
Referenced by HttpThread::connection().
menu()
char * Env::menu ()
Definition at line 74 of file env.cpp.
References vrengmenu.
Referenced by Widgets::createMenubar().
passwd()
char * Env::passwd ()
Definition at line 84 of file env.cpp.
References vrengpasswd.
Referenced by Vnc::parser().
prefs()
char * Env::prefs ()
Definition at line 64 of file env.cpp.
References vrengprefs.
Referenced by Widgets::createPrefsDialog(), and Global::start().
relname()
char * Env::relname ()
Definition at line 94 of file env.cpp.
References releasename.
Referenced by HttpThread::connection().
sysinfo()
void Env::sysinfo () private
Definition at line 104 of file env.cpp.
References machinename, releasename, and systemname.
Referenced by Env().
sysname()
char * Env::sysname ()
Definition at line 89 of file env.cpp.
References systemname.
Referenced by HttpThread::connection().
worldmarks()
char * Env::worldmarks ()
Definition at line 79 of file env.cpp.
References vrengworldmarks.
Referenced by Widgets::addMarkCB(), and Widgets::createMarkMenu().
Member Data Documentation
machinename
char Env::machinename[32] private
Definition at line 59 of file env.hpp.
Referenced by Env(), machname(), and sysinfo().
releasename
char Env::releasename[9] private
Definition at line 58 of file env.hpp.
Referenced by Env(), relname(), and sysinfo().
systemname
char Env::systemname[9] private
Definition at line 57 of file env.hpp.
Referenced by Env(), sysinfo(), and sysname().
vrengcache
char Env::vrengcache[PATH_LEN] private
Definition at line 55 of file env.hpp.
Referenced by cache(), cleanCacheByExt(), cleanCacheByTime(), and initDirs().
vrengcwd
char Env::vrengcwd[PATH_LEN] private
Definition at line 49 of file env.hpp.
Referenced by cleanCacheByExt(), cleanCacheByTime(), cwd(), and initDirs().
vrengdir
char Env::vrengdir[PATH_LEN] private
Definition at line 48 of file env.hpp.
Referenced by dir(), and initDirs().
vrengicons
char Env::vrengicons[PATH_LEN] private
Definition at line 52 of file env.hpp.
Referenced by icons(), and initDirs().
vrengmenu
char Env::vrengmenu[PATH_LEN] private
Definition at line 51 of file env.hpp.
Referenced by initDirs(), and menu().
vrengpasswd
char Env::vrengpasswd[PATH_LEN] private
Definition at line 54 of file env.hpp.
Referenced by initDirs(), and passwd().
vrengprefs
char Env::vrengprefs[PATH_LEN] private
Definition at line 50 of file env.hpp.
Referenced by initDirs(), and prefs().
vrengworldmarks
char Env::vrengworldmarks[PATH_LEN] private
Definition at line 53 of file env.hpp.
Referenced by initDirs(), and worldmarks().
The documentation for this class was generated from the following files:
src/vreng/env.hpp
src/vreng/env.cpp