VREng: src/vnc/d3des.h File Reference
d3des.h File Reference
Macros
#define EN0 0 /* MODE == encrypt */
#define DE1 1 /* MODE == decrypt */
Functions
void deskey (unsigned char *, int)
void usekey (unsigned long *)
void cpkey (unsigned long *)
void des (unsigned char *, unsigned char *)
Macro Definition Documentation
DE1
#define DE1 1 /* MODE == decrypt */
Definition at line 24 of file d3des.h.
EN0
#define EN0 0 /* MODE == encrypt */
Definition at line 23 of file d3des.h.
Function Documentation
cpkey()
void cpkey (unsigned long *)
des()
void des (unsigned char * , unsigned char *)
Definition at line 142 of file d3des.cpp.
References desfunc(), KnL, scrunch(), and unscrun().
Referenced by vncDecryptPasswdFromFile(), vncEncryptAndStorePasswd(), and vncEncryptBytes().
deskey()
void deskey (unsigned char * , int)
Definition at line 67 of file d3des.cpp.
References bigbyte, bytebit, cookey(), DE1, pc1, pc2, and totrot.
Referenced by vncDecryptPasswdFromFile(), vncEncryptAndStorePasswd(), and vncEncryptBytes().
usekey()
void usekey (unsigned long *)