VREng: Url Class Reference
Url Class Reference
Url class.
#include <url.hpp>
Public Types
enum { URLBAD, URLHTTP, URLFILE }
Static Public Member Functions
static int parser (char *url, char *host, char *scheme, char *path)
Parse url.
static void abs (const char *oldurl, char *newurl)
Change relative url to absolute.
Detailed Description
Url class.
Definition at line 28 of file url.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
URLBAD
URLHTTP
URLFILE
Definition at line 32 of file url.hpp.
Member Function Documentation
abs()
void Url::abs (const char * oldurl, char * newurl) static
Change relative url to absolute.
Definition at line 98 of file url.cpp.
References Universe::current(), stringcmp(), URL_LEN, and warning().
Referenced by Cache::download(), Vrelet::parser(), Au::start(), Midi::start(), Mp3::start(), Mpeg::start(), Wav::start(), Browser::start(), Wget::start(), and World::worldByUrl().
parser()
int Url::parser (char * url, char * host, char * scheme, char * path) static
Parse url.
Definition at line 32 of file url.cpp.
References Universe::current(), DBG_HTTP, error(), MAXHOSTNAMELEN, stringcmp(), trace(), URLBAD, URLFILE, and URLHTTP.
Referenced by HttpThread::connection().
The documentation for this class was generated from the following files:
src/vreng/url.hpp
src/vreng/url.cpp