VREng: Http Class Reference
Http Class Reference
Http Class I/O methods.
#include <http.hpp>
Public Member Functions
Http ()
constructor
virtual ~Http ()
destructor
virtual void reset ()
Reset read buffer.
virtual int httpRead (char *buf, int size)
Reads a block.
virtual int tell ()
Returns current position.
virtual int getChar ()
Gets a char.
virtual uint8_t read_char ()
Gets a byte.
virtual int32_t read_short ()
Gets a short.
virtual int32_t read_int ()
Gets an integer.
virtual int32_t read_long ()
Gets a short.
virtual float read_float ()
Gets a float.
virtual GLfloat read_GLfloat ()
Gets a GLfloat.
virtual int read_string (char *s, int maxlen)
Gets a string.
virtual bool nextLine (char *line)
Gets nextline.
virtual bool getLine (char *line)
Gets a line.
virtual int fread (char *ptr, int size, int nitems)
Emulates fread.
virtual uint32_t read_buf (char *buf, int maxlen)
Gets a block.
virtual uint32_t skip (int32_t skiplen)
Skips a length.
Static Public Member Functions
static int httpOpen (const char *url, void(*httpReader)(void *h, Http *httpio), void *hdl, int _thread)
Opens an url and gives which reader to use and tells whether the connection is threaded or not.
Public Attributes
int fd
http fd
int off
offset in buf
int len
length
char * url
url
char * buf
buffer
Detailed Description
Http Class I/O methods.
Definition at line 118 of file http.hpp.
Constructor & Destructor Documentation
Http()
Http::Http ()
constructor
Definition at line 508 of file http.cpp.
References buf, fd, HTTP_BUFSIZ, len, new_http, off, reset(), url, and URL_LEN.
Referenced by httpOpen().
~Http()
Http::~Http () virtual
destructor
Definition at line 518 of file http.cpp.
References buf, Socket::closeStream(), del_http, fd, and url.
Member Function Documentation
fread()
int Http::fread (char * ptr, int size, int nitems) virtual
Emulates fread.
returns an item
Definition at line 701 of file http.cpp.
References htbuf, htbuf_len, htbuf_pos, httpRead(), and size.
getChar()
int Http::getChar () virtual
Gets a char.
returns a byte or an error
Definition at line 572 of file http.cpp.
References htbuf, htbuf_len, htbuf_pos, and httpRead().
Referenced by nextLine(), and Cache::openCache().
getLine()
bool Http::getLine (char * line) virtual
Gets a line.
return a line non empty without comments
Definition at line 692 of file http.cpp.
References isEmptyLine(), and nextLine().
Referenced by Face::facesHttpReader().
httpOpen()
int Http::httpOpen (const char * url, void(*)(void *h, Http *httpio) httpReader, void * hdl, int _thread) static
Opens an url and gives which reader to use and tells whether the connection is threaded or not.
Open a new HTTP connection, returns -1 if error.
Definition at line 465 of file http.cpp.
References HttpThread::connection(), DBG_HTTP, error(), g, HttpThread::http, Http(), HttpThread::httpReader, Times::image, Cache::inCache(), HttpThread::modethr, progression(), HttpThread::putfifo(), ProfileTime::start(), ProfileTime::stop(), HttpThread::thrhdl, Global::times, trace(), HttpThread::url, and url.
Referenced by _3ds::_3ds(), Ase::Ase(), Book::Book(), Widgets::destinationsDialog(), rigid::download(), Bvh::download(), Avi::download(), Dxf::Dxf(), World::enter(), Face::Face(), Texture::getFromCache(), Txf::getFromCache(), World::init(), Guy::inits(), Body::load(), Face::load(), Body::loadBodyParts(), Hairs::loader(), Lwo::Lwo(), Md2::Md2(), Obj::Obj(), Off::Off(), Widgets::openSourceDialog(), Widgets::openWorldsDialog(), Texture::Texture(), Walls::Walls(), and X3d::X3d().
httpRead()
int Http::httpRead (char * buf, int size) virtual
Reads a block.
Definition at line 527 of file http.cpp.
References buf, error(), fd, len, off, and read.
Referenced by fread(), getChar(), World::httpReader(), X3d::httpReader(), read_buf(), read_char(), read_int(), readImg(), and skip().
nextLine()
bool Http::nextLine (char * line) virtual
Gets nextline.
returns true and the line else returns false
Definition at line 664 of file http.cpp.
References getChar().
Referenced by destinationsHttpReader(), getLine(), and universeHttpReader().
read_buf()
uint32_t Http::read_buf (char * buf, int maxlen) virtual
Gets a block.
returns a block and the length
Definition at line 721 of file http.cpp.
References htbuf, htbuf_len, htbuf_pos, and httpRead().
Referenced by Md2::getFrames(), and Md2::loadFromHttp().
read_char()
uint8_t Http::read_char () virtual
Gets a byte.
returns a byte
Definition at line 585 of file http.cpp.
References htbuf, htbuf_len, htbuf_pos, and httpRead().
Referenced by Md2::getFrames(), read_long(), read_short(), and read_string().
read_float()
float Http::read_float () virtual
Gets a float.
returns a float
Definition at line 633 of file http.cpp.
References read_long().
Referenced by Md2::getFrames(), and Md2::getGLCmds().
read_GLfloat()
GLfloat Http::read_GLfloat () virtual
Gets a GLfloat.
Definition at line 639 of file http.cpp.
References read_long().
read_int()
int32_t Http::read_int () virtual
Gets an integer.
returns an int
Definition at line 595 of file http.cpp.
References htbuf, htbuf_len, htbuf_pos, and httpRead().
Referenced by Md2::getGLCmds(), and Md2::loadFromHttp().
read_long()
int32_t Http::read_long () virtual
Gets a short.
Definition at line 627 of file http.cpp.
References read_char().
Referenced by read_float(), and read_GLfloat().
read_short()
int32_t Http::read_short () virtual
Gets a short.
Definition at line 622 of file http.cpp.
References read_char().
read_string()
int Http::read_string (char * s, int maxlen) virtual
Gets a string.
Definition at line 645 of file http.cpp.
References read_char().
reset()
void Http::reset () virtual
Reset read buffer.
Definition at line 560 of file http.cpp.
References htbuf_len, and htbuf_pos.
Referenced by HttpThread::connection(), Face::facesHttpReader(), and Http().
skip()
uint32_t Http::skip (int32_t skiplen) virtual
Skips a length.
skips an offset
Definition at line 739 of file http.cpp.
References htbuf, htbuf_len, htbuf_pos, and httpRead().
Referenced by Md2::loadFromHttp().
tell()
int Http::tell () virtual
Returns current position.
returns current position
Definition at line 566 of file http.cpp.
References htbuf_pos.
Member Data Documentation
buf
char* Http::buf
buffer
Definition at line 124 of file http.hpp.
Referenced by HttpThread::connection(), Http(), httpRead(), and ~Http().
fd
int Http::fd
http fd
Definition at line 120 of file http.hpp.
Referenced by HttpThread::connection(), Http(), httpRead(), and ~Http().
len
int Http::len
length
Definition at line 122 of file http.hpp.
Referenced by HttpThread::connection(), Http(), and httpRead().
off
int Http::off
offset in buf
Definition at line 121 of file http.hpp.
Referenced by HttpThread::connection(), Http(), and httpRead().
url
char* Http::url
url
Definition at line 123 of file http.hpp.
Referenced by Http(), httpOpen(), sourceHttpReader(), and ~Http().
The documentation for this class was generated from the following files:
src/vreng/http.hpp
src/vreng/http.cpp