VREng: Scene Class Reference
Scene Class Reference
#include <scene.hpp>
Public Member Functions
Scene (class Widgets *)
bool isInitialized ()
checks whether the scene is initialized.
void setNetDelay (int msec)
int getNetDelay () const
void getCoords (GLint coords[4])
void getCoords (GLint &x, GLint &y, GLsizei &w, GLsizei &h)
void setViewport (GLint x, GLint y, GLsizei width, GLsizei height)
void setBackground (UColor &)
void toggleHud ()
Public Attributes
bool hudvisible
Private Member Functions
void init ()
void paintScene ()
Inits the scene.
void resizeScene (UResizeEvent &, int width, int height)
Paints the scene.
void updateHud ()
Resizes the scene.
void netTimeoutCB ()
void paintCB (UPaintEvent &)
void resizeCB (UResizeEvent &)
Private Attributes
class Widgets & gw
bool is_visible
true if visible (not iconified).
bool is_initialized
bool is_startCB_launched
int net_delay
default is 500ms
int cycles
UTimer render_timer
UTimer net_timer
ULabel message
UBox hudbox
UStr hud_line1
UStr hud_line2
UStr hud_line3
UStr hud_line4
UStr hud_line5
UBackground background
class Hud * hud
Friends
class Gui
Detailed Description
Definition at line 36 of file scene.hpp.
Constructor & Destructor Documentation
Scene()
Scene::Scene (class Widgets * _gw)
Definition at line 44 of file scene.cpp.
References background, g, Pref::height3D, hud_line1, hud_line2, hud_line3, hud_line4, hud_line5, hudbox, hudvisible, message, paintCB(), Global::pref, resizeCB(), and Pref::width3D.
Member Function Documentation
getCoords() [1/2]
void Scene::getCoords (GLint & x, GLint & y, GLsizei & w, GLsizei & h)
Definition at line 93 of file scene.cpp.
getCoords() [2/2]
void Scene::getCoords (GLint coords[4])
Definition at line 80 of file scene.cpp.
Referenced by Render::clickDirection(), Render::getVisiblePosition(), Render::map(), Render::satellite(), and Solid::setRay().
getNetDelay()
int Scene::getNetDelay () const inline
Definition at line 46 of file scene.hpp.
References net_delay.
init()
void Scene::init () private
Definition at line 145 of file scene.cpp.
References Render::config(), Pref::frame_delay, g, is_initialized, message, net_delay, net_timer, netTimeoutCB(), Global::pref, Pref::quality3D, Global::render, render_timer, and Global::startCB().
Referenced by paintScene().
isInitialized()
bool Scene::isInitialized () inline
checks whether the scene is initialized.
Definition at line 43 of file scene.hpp.
References is_initialized.
Referenced by Grid::draw().
netTimeoutCB()
void Scene::netTimeoutCB () private
Definition at line 140 of file scene.cpp.
References NetTimeout().
Referenced by init().
paintCB()
void Scene::paintCB (UPaintEvent & e) private
Definition at line 125 of file scene.cpp.
References Render::camera(), g, is_initialized, paintScene(), and Global::render.
Referenced by Scene().
paintScene()
void Scene::paintScene () private
Inits the scene.
Definition at line 179 of file scene.cpp.
References Widgets::capture, World::compute(), World::current(), cycles, DBG_WO, Widgets::flushPostponedKRs(), g, gw, hudbox, hudvisible, init(), is_initialized, is_startCB_launched, is_visible, Capture::isCapturingVideo(), Widgets::pendingPostponedKRs(), Render::render(), Times::render, Global::render, Times::simul, ProfileTime::start(), ProfileTime::start_time, ProfileTime::stop(), Global::times, trace(), updateHud(), and Capture::writeVideoFrame().
Referenced by paintCB().
resizeCB()
void Scene::resizeCB (UResizeEvent & e) private
Definition at line 133 of file scene.cpp.
References resizeScene().
Referenced by Scene().
resizeScene()
void Scene::resizeScene (UResizeEvent & e, int width, int height) private
Paints the scene.
Definition at line 169 of file scene.cpp.
References g, Pref::height3D, Global::pref, and Pref::width3D.
Referenced by resizeCB().
setBackground()
void Scene::setBackground (UColor & c)
Definition at line 75 of file scene.cpp.
References background.
Referenced by Render::clearGLBuffer().
setNetDelay()
void Scene::setNetDelay (int msec) inline
Definition at line 45 of file scene.hpp.
References net_delay.
setViewport()
void Scene::setViewport (GLint x, GLint y, GLsizei width, GLsizei height)
Definition at line 106 of file scene.cpp.
Referenced by Render::map(), and Render::satellite().
toggleHud()
void Scene::toggleHud ()
Definition at line 247 of file scene.cpp.
References hudvisible.
Referenced by toggleHudCB().
updateHud()
void Scene::updateHud () private
Resizes the scene.
Definition at line 217 of file scene.cpp.
References Pos::az, dist, g, Times::getRate(), Global::gui, hud_line1, hud_line2, hud_line3, hud_line4, hud_line5, localuser, obj, WObject::pos, RAD2DEG, Gui::selected_object, Global::times, Pos::x, Pos::y, and Pos::z.
Referenced by paintScene().
Friends And Related Function Documentation
Gui
friend class Gui friend
Definition at line 55 of file scene.hpp.
Member Data Documentation
background
UBackground Scene::background private
Definition at line 66 of file scene.hpp.
Referenced by Scene(), and setBackground().
cycles
int Scene::cycles private
Definition at line 61 of file scene.hpp.
Referenced by Gui::getCycles(), and paintScene().
gw
class Widgets& Scene::gw private
Definition at line 56 of file scene.hpp.
Referenced by paintScene().
hud
class Hud* Scene::hud private
Definition at line 67 of file scene.hpp.
hud_line1
UStr Scene::hud_line1 private
Definition at line 65 of file scene.hpp.
Referenced by Scene(), and updateHud().
hud_line2
UStr Scene::hud_line2 private
Definition at line 65 of file scene.hpp.
Referenced by Scene(), and updateHud().
hud_line3
UStr Scene::hud_line3 private
Definition at line 65 of file scene.hpp.
Referenced by Scene(), and updateHud().
hud_line4
UStr Scene::hud_line4 private
Definition at line 65 of file scene.hpp.
Referenced by Scene(), and updateHud().
hud_line5
UStr Scene::hud_line5 private
Definition at line 65 of file scene.hpp.
Referenced by Scene(), and updateHud().
hudbox
UBox Scene::hudbox private
Definition at line 64 of file scene.hpp.
Referenced by paintScene(), and Scene().
hudvisible
bool Scene::hudvisible
Definition at line 39 of file scene.hpp.
Referenced by paintScene(), Scene(), and toggleHud().
is_initialized
bool Scene::is_initialized private
Definition at line 58 of file scene.hpp.
Referenced by init(), isInitialized(), paintCB(), and paintScene().
is_startCB_launched
bool Scene::is_startCB_launched private
Definition at line 59 of file scene.hpp.
Referenced by paintScene().
is_visible
bool Scene::is_visible private
true if visible (not iconified).
Definition at line 57 of file scene.hpp.
Referenced by paintScene().
message
ULabel Scene::message private
Definition at line 63 of file scene.hpp.
Referenced by init(), and Scene().
net_delay
int Scene::net_delay private
default is 500ms
Definition at line 60 of file scene.hpp.
Referenced by getNetDelay(), init(), and setNetDelay().
net_timer
UTimer Scene::net_timer private
Definition at line 62 of file scene.hpp.
Referenced by init().
render_timer
UTimer Scene::render_timer private
Definition at line 62 of file scene.hpp.
Referenced by init().
The documentation for this class was generated from the following files:
src/vreng/scene.hpp
src/vreng/scene.cpp