VREng: ProfileTime Class Reference
ProfileTime Class Reference
ProfileTime class.
#include <timer.hpp>
Public Member Functions
ProfileTime ()
void start ()
double stop ()
double diff ()
Public Attributes
struct timeval start_time
struct timeval stop_time
double cumul_time
double diff_time
Detailed Description
ProfileTime class.
Definition at line 27 of file timer.hpp.
Constructor & Destructor Documentation
ProfileTime()
ProfileTime::ProfileTime ()
Definition at line 27 of file timer.cpp.
References cumul_time, diff_time, start_time, and stop_time.
Member Function Documentation
diff()
double ProfileTime::diff ()
Definition at line 48 of file timer.cpp.
References diff_time.
start()
void ProfileTime::start ()
Definition at line 34 of file timer.cpp.
References gettimeofday(), and start_time.
Referenced by Http::httpOpen(), Channel::init(), Scene::paintScene(), Parse::parseVreLines(), Global::start(), Capture::startVideo(), WObject::updateMySqlPosition(), WObject::updateMySqlPosZ(), and WObject::updateMySqlState().
stop()
double ProfileTime::stop ()
Definition at line 39 of file timer.cpp.
References cumul_time, d, diff_time, Times::diffDates(), gettimeofday(), start_time, and stop_time.
Referenced by Http::httpOpen(), Scene::paintScene(), Parse::parseVreLines(), Global::startCB(), statNetwork(), statTimings(), Capture::stopVideo(), WObject::updateMySqlPosition(), WObject::updateMySqlPosZ(), and WObject::updateMySqlState().
Member Data Documentation
cumul_time
double ProfileTime::cumul_time
Definition at line 38 of file timer.hpp.
Referenced by Times::getRate(), ProfileTime(), statTimings(), and stop().
diff_time
double ProfileTime::diff_time
Definition at line 39 of file timer.hpp.
Referenced by diff(), ProfileTime(), and stop().
start_time
struct timeval ProfileTime::start_time
Definition at line 34 of file timer.hpp.
Referenced by Scene::paintScene(), ProfileTime(), start(), and stop().
stop_time
struct timeval ProfileTime::stop_time
Definition at line 34 of file timer.hpp.
Referenced by ProfileTime(), and stop().
The documentation for this class was generated from the following files:
src/vreng/timer.hpp
src/vreng/timer.cpp