VREng: Format Class Reference
Format Class Reference
Format class.
#include <format.hpp>
Static Public Member Functions
static uint8_t getLoaderByMime (const char *str)
static uint8_t getLoaderByUrl (char *url)
static uint8_t getModelByMime (const char *str)
static uint8_t getModelByUrl (char *url)
static uint8_t getPlayerByUrl (char *url)
static uint8_t getPlayerByExt (const char *str)
static bool getExt (char *str, char *ext)
static void getImgByExt (const char *str, char *img)
Detailed Description
Format class.
Definition at line 263 of file format.hpp.
Member Function Documentation
getExt()
bool Format::getExt (char * str, char * ext) static
Definition at line 180 of file format.cpp.
References _icons::ext, EXT_GZ, EXT_HTML, and stringcmp().
Referenced by Icon::Icon(), and Icon::open().
getImgByExt()
void Format::getImgByExt (const char * str, char * img) static
Definition at line 210 of file format.cpp.
References _icons::ext, icons, _icons::img, and strcasecmp().
Referenced by Icon::Icon().
getLoaderByMime()
uint8_t Format::getLoaderByMime (const char * str) static
Definition at line 111 of file format.cpp.
References _file::ext, imgs, _file::loader, and _file::mime.
Referenced by Texture::httpReader().
getLoaderByUrl()
uint8_t Format::getLoaderByUrl (char * url) static
Definition at line 121 of file format.cpp.
References _file::ext, imgs, and _file::loader.
Referenced by Texture::getFromCache(), Texture::httpReader(), and Texture::Texture().
getModelByMime()
uint8_t Format::getModelByMime (const char * str) static
Definition at line 137 of file format.cpp.
References _file::ext, _file::loader, _file::mime, and models.
getModelByUrl()
uint8_t Format::getModelByUrl (char * url) static
Definition at line 147 of file format.cpp.
References _file::ext, _file::loader, and models.
Referenced by Head::inits(), Body::loadBodyParts(), Model::loader(), and Solid::statueParser().
getPlayerByExt()
uint8_t Format::getPlayerByExt (const char * str) static
Definition at line 221 of file format.cpp.
References _icons::ext, icons, _icons::player, and strcasecmp().
Referenced by Icon::open().
getPlayerByUrl()
uint8_t Format::getPlayerByUrl (char * url) static
Definition at line 163 of file format.cpp.
References _icons::ext, icons, and _icons::player.
Referenced by Movie::inits().
The documentation for this class was generated from the following files:
src/vreng/format.hpp
src/vreng/format.cpp