VREng: Sound Class Reference
Sound Class Reference
Sound class.
#include <sound.hpp>
Public Member Functions
Sound ()
~Sound ()
Static Public Member Functions
static void playSound (const char *snd)
Play this encrypted base64 sound.
Static Private Member Functions
static int opendev ()
Open audio device.
static void * sound_thread (void *snd)
Thread.
Detailed Description
Sound class.
Definition at line 30 of file sound.hpp.
Constructor & Destructor Documentation
Sound()
Sound::Sound () inline
Definition at line 34 of file sound.hpp.
~Sound()
Sound::~Sound () inline
Definition at line 35 of file sound.hpp.
Member Function Documentation
opendev()
int Sound::opendev () static private
Open audio device.
Definition at line 36 of file sound.cpp.
References DEVAUDIO, error(), and open.
Referenced by sound_thread().
playSound()
void Sound::playSound (const char * snd) static
Play this encrypted base64 sound.
Definition at line 69 of file sound.cpp.
References audioactive, g, Global::pref, Pref::silent, and sound_thread().
Referenced by Bullet::Bullet(), Dart::Dart(), Gate::enter(), Bullet::get_hit(), Dart::get_hit(), Fire::inits(), Door::open(), Water::sound(), Fire::sound_continue(), Rain::sound_continue(), Water::sound_continue(), Door::updateTime(), User::userWriting(), User::whenIntersect(), Capture::writeGIFImage(), Capture::writeJPGImage(), and Capture::writePNGImage().
sound_thread()
void * Sound::sound_thread (void * snd) static private
Thread.
Definition at line 48 of file sound.cpp.
References audioactive, close, decodeBase64(), getpid, opendev(), and write.
Referenced by playSound().
The documentation for this class was generated from the following files:
src/vreng/sound.hpp
src/vreng/sound.cpp