VREng: Socket Class Reference
Socket Class Reference
Socket class.
#include <socket.hpp>
Static Public Member Functions
static int openDatagram ()
Open a datagram socket.
static int openStream ()
Open a stream socket.
static void closeDatagram (int sock)
Close a socket datagram.
static void closeStream (int sock)
Close a socket stream.
static int connection (int sock, const sockaddr_in *sa)
static int reuseAddr (int sock)
Do REUSEADDR on the socket return sock if OK, else -1.
static int tcpNoDelay (int sock)
static uint16_t getSrcPort (int sock)
static int handleBlocking (int sock, bool block)
Control blocking(1)/non blocking(0) return sock if OK, else -1.
static int setBlocking (int sock)
static int setNoBlocking (int sock)
static int setLoopback (int sock)
static int setNoLoopback (int sock)
static int setScope (int sock, uint8_t ttl)
Set the ttl return sock if OK, else -1.
static int addMembership (int sock, const void *pmreq)
static int dropMembership (int sock, const void *pmreq)
static int bindSocket (int sock, uint32_t uni_addr, uint16_t port)
bind
static int createUcastSocket (uint32_t uni_addr, uint16_t port)
Create an Unicast socket return fd, -1 if problem.
static int createSendSocket (uint8_t ttl)
Create an UDP socket Prevue pour emettre (uni et mcast) et recevoir (unicast donc) Do setScope (ttl) and setLoopback (off) return sock if OK, else -1.
static bool isMulticastAddress (uint32_t address)
Static Private Member Functions
static void setSendSocket (int sock, uint8_t ttl)
Set a Multicast socket.
static int handleLoopback (int sock, uint8_t loop)
Set loopback: active (1) either inactive (0) return sock if OK, else -1.
Detailed Description
Socket class.
Definition at line 28 of file socket.hpp.
Member Function Documentation
addMembership()
int Socket::addMembership (int sock, const void * pmreq) static
Definition at line 204 of file socket.cpp.
References error().
Referenced by Android::initReceiver(), and Channel::joinGroup().
bindSocket()
int Socket::bindSocket (int sock, uint32_t uni_addr, uint16_t port) static
bind
Definition at line 264 of file socket.cpp.
References error(), and reuseAddr().
Referenced by createUcastSocket(), Android::initReceiver(), and VjcSocket::openRecv().
closeDatagram()
void Socket::closeDatagram (int sock) static
Close a socket datagram.
Definition at line 49 of file socket.cpp.
References close, and cnt_close_socket.
Referenced by Channel::closeMcastSocket(), Channel::closeUcastSocket(), Android::disconnectFromBapServer(), VjcSocket::openRecv(), Channel::~Channel(), and VjcSocket::~VjcSocket().
closeStream()
void Socket::closeStream (int sock) static
Close a socket stream.
Definition at line 58 of file socket.cpp.
References close, and cnt_close_socket.
Referenced by VNCSockets::ConnectToTcpAddr(), Android::disconnectFromBapServer(), Vac::getList(), Vac::resolveWorldUrl(), and Http::~Http().
connection()
int Socket::connection (int sock, const sockaddr_in * sa) static
Definition at line 66 of file socket.cpp.
References close, cnt_close_socket, and error().
Referenced by HttpThread::connect().
createSendSocket()
int Socket::createSendSocket (uint8_t ttl) static
Create an UDP socket Prevue pour emettre (uni et mcast) et recevoir (unicast donc) Do setScope (ttl) and setLoopback (off) return sock if OK, else -1.
Definition at line 253 of file socket.cpp.
References openDatagram(), and setSendSocket().
Referenced by Channel::create().
createUcastSocket()
int Socket::createUcastSocket (uint32_t uni_addr, uint16_t port) static
Create an Unicast socket return fd, -1 if problem.
Definition at line 284 of file socket.cpp.
References bindSocket(), error(), openDatagram(), and reuseAddr().
dropMembership()
int Socket::dropMembership (int sock, const void * pmreq) static
Definition at line 216 of file socket.cpp.
References error().
Referenced by Android::disconnectFromBapServer(), and Channel::leaveGroup().
getSrcPort()
uint16_t Socket::getSrcPort (int sock) static
Definition at line 105 of file socket.cpp.
References error().
Referenced by Channel::naming().
handleBlocking()
int Socket::handleBlocking (int sock, bool block) static
Control blocking(1)/non blocking(0) return sock if OK, else -1.
Definition at line 124 of file socket.cpp.
References error().
Referenced by setBlocking(), and setNoBlocking().
handleLoopback()
int Socket::handleLoopback (int sock, uint8_t loop) static private
Set loopback: active (1) either inactive (0) return sock if OK, else -1.
Definition at line 180 of file socket.cpp.
References error().
Referenced by setLoopback(), and setNoLoopback().
isMulticastAddress()
bool Socket::isMulticastAddress (uint32_t address) static
Definition at line 306 of file socket.cpp.
openDatagram()
int Socket::openDatagram () static
Open a datagram socket.
Definition at line 27 of file socket.cpp.
References cnt_open_socket, and error().
Referenced by Channel::createMcastRecvSocket(), createSendSocket(), createUcastSocket(), Android::initReceiver(), VjcSocket::openRecv(), and VjcSocket::openSend().
openStream()
int Socket::openStream () static
Open a stream socket.
Definition at line 38 of file socket.cpp.
References cnt_open_socket, and error().
Referenced by HttpThread::connect(), Vac::connectThread(), Android::connectToBapServer(), and VNCSockets::ConnectToTcpAddr().
reuseAddr()
int Socket::reuseAddr (int sock) static
Do REUSEADDR on the socket return sock if OK, else -1.
Definition at line 81 of file socket.cpp.
References error().
Referenced by bindSocket(), Channel::createMcastRecvSocket(), and createUcastSocket().
setBlocking()
int Socket::setBlocking (int sock) static
Definition at line 145 of file socket.cpp.
References handleBlocking().
setLoopback()
int Socket::setLoopback (int sock) static
Definition at line 194 of file socket.cpp.
References handleLoopback().
Referenced by setSendSocket().
setNoBlocking()
int Socket::setNoBlocking (int sock) static
Definition at line 150 of file socket.cpp.
References handleBlocking().
Referenced by VjcSocket::openSend(), VNCSockets::SetNonBlocking(), and setSendSocket().
setNoLoopback()
int Socket::setNoLoopback (int sock) static
Definition at line 199 of file socket.cpp.
References handleLoopback().
Referenced by setSendSocket().
setScope()
int Socket::setScope (int sock, uint8_t ttl) static
Set the ttl return sock if OK, else -1.
Definition at line 159 of file socket.cpp.
References error(), and TTL_TYPE.
Referenced by setSendSocket().
setSendSocket()
void Socket::setSendSocket (int sock, uint8_t ttl) static private
Set a Multicast socket.
Definition at line 229 of file socket.cpp.
References setLoopback(), setNoBlocking(), setNoLoopback(), and setScope().
Referenced by createSendSocket().
tcpNoDelay()
int Socket::tcpNoDelay (int sock) static
Definition at line 93 of file socket.cpp.
References error(), and TCP_NODELAY.
Referenced by VNCSockets::ConnectToTcpAddr().
The documentation for this class was generated from the following files:
src/vreng/socket.hpp
src/vreng/socket.cpp