VREng: HttpThread Class Reference
HttpThread Class Reference
HttpThread Class.
#include <http.hpp>
Public Member Functions
HttpThread ()
Constructor.
virtual ~HttpThread ()
Destructor.
Static Public Member Functions
static void init ()
Initializes Http thread.
static void * connection (void *_ht)
Makes an http connection.
static int resolver (char *hoststr, char *portstr, struct sockaddr_in *sa)
Resolves a hostname.
static int openFile (const char *path)
Opens a local file.
Public Attributes
void(* httpReader)(void *thrhdl, class Http *http)
Http reader.
Private Types
enum {
TCPEOF, BADSEND, BADSOCKET, BADCONNECT,
BADNAME, BADSERV
}
Private Member Functions
void begin ()
Begins a thread.
void end ()
Ends a thread.
virtual int putfifo ()
Puts thread into a wait fifo.
Static Private Member Functions
static int send (int fd, const char *buf, int size)
Send a http request.
static int answer (int s, char *rep, int max)
Receives a response from the http server.
static void checkProxy ()
Checks proxy environment variables.
static int connect (const struct sockaddr_in *sa)
Establishes a connection to the http server.
Private Attributes
tWaitFifo * waitfifo
fifo
void * thrhdl
thread handle
bool modethr
thread or not
class Http * http
http handle
char url [URL_LEN]
url
Friends
class Http
Detailed Description
HttpThread Class.
Definition at line 50 of file http.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
TCPEOF
BADSEND
BADSOCKET
BADCONNECT
BADNAME
BADSERV
Definition at line 55 of file http.hpp.
Constructor & Destructor Documentation
HttpThread()
HttpThread::HttpThread ()
Constructor.
Definition at line 45 of file http.cpp.
References begin(), new_httpthread, and waitfifo.
~HttpThread()
HttpThread::~HttpThread () virtual
Destructor.
Definition at line 52 of file http.cpp.
References del_httpthread, and end().
Member Function Documentation
answer()
int HttpThread::answer (int s, char * rep, int max) static private
Receives a response from the http server.
Fill buffer rep.
Definition at line 145 of file http.cpp.
Referenced by connection().
begin()
void HttpThread::begin () private
Begins a thread.
Definition at line 65 of file http.cpp.
References tWaitFifo::cond, fifofirst, lockMutex(), modethr, nbsimcon, nbsimcon_mutex, tWaitFifo::next, unlockMutex(), and waitfifo.
Referenced by HttpThread().
checkProxy()
void HttpThread::checkProxy () static private
Checks proxy environment variables.
Check if http proxy.
Definition at line 210 of file http.cpp.
References DBG_HTTP, domnoproxy, g, hostproxy, HTTP_PROXY, Pref::httpproxystr, NO_PROXY, noproxy, Pref::noproxystr, portproxy, Global::pref, proxy, and trace().
Referenced by connection().
connect()
int HttpThread::connect (const struct sockaddr_in * sa) static private
Establishes a connection to the http server.
Connect to server defined by sa.
Definition at line 165 of file http.cpp.
References BADCONNECT, BADSOCKET, Socket::connection(), and Socket::openStream().
Referenced by connection().
connection()
void * HttpThread::connection (void * _ht) static
Makes an http connection.
make an http connection
Definition at line 248 of file http.cpp.
References answer(), Http::buf, checkProxy(), connect(), DBG_HTTP, domnoproxy, Global::env, error(), Http::fd, g, hostproxy, http, HTTP_200, HTTP_202, HTTP_301, HTTP_302, HTTP_307, HTTP_503, HTTP_BUFSIZ, httpReader, Http::len, Env::machname(), MAXHOSTNAMELEN, MIME_LEN, my_free_hostent(), my_gethostbyname(), noproxy, Http::off, openFile(), Url::parser(), portproxy, proxy, Env::relname(), Http::reset(), resolver(), send(), Texture::setMime(), Env::sysname(), thrhdl, trace(), Global::universe, url, Global::url, URL_LEN, Url::URLFILE, Url::URLHTTP, Global::user, and warning().
Referenced by Http::httpOpen(), and putfifo().
end()
void HttpThread::end () private
Ends a thread.
Definition at line 87 of file http.cpp.
References tWaitFifo::cond, DBG_HTTP, fifofirst, lockMutex(), modethr, nbsimcon, nbsimcon_mutex, trace(), unlockMutex(), and url.
Referenced by ~HttpThread().
init()
void HttpThread::init () static
Initializes Http thread.
Definition at line 58 of file http.cpp.
References DBG_INIT, initMutex(), nbsimcon, nbsimcon_mutex, and trace().
Referenced by Global::startCB().
openFile()
int HttpThread::openFile (const char * path) static
Opens a local file.
Definition at line 242 of file http.cpp.
References open.
Referenced by connection().
putfifo()
int HttpThread::putfifo () private virtual
Puts thread into a wait fifo.
Definition at line 105 of file http.cpp.
References tWaitFifo::cond, connection(), DBG_HTTP, fifofirst, fifolast, g, lockMutex(), Pref::maxsimcon, nbsimcon, nbsimcon_mutex, tWaitFifo::next, Global::pref, trace(), unlockMutex(), url, and waitfifo.
Referenced by Http::httpOpen().
resolver()
int HttpThread::resolver (char * hoststr, char * portstr, struct sockaddr_in * sa) static
Resolves a hostname.
Converts host/port into sockaddr.
Definition at line 179 of file http.cpp.
References BADNAME, BADSERV, HTTP_PORT, my_free_hostent(), and my_gethostbyname_r().
Referenced by connection().
send()
int HttpThread::send (int fd, const char * buf, int size) static private
Send a http request.
Send request to the http server.
Definition at line 151 of file http.cpp.
References BADSEND, size, and write.
Referenced by connection().
Friends And Related Function Documentation
Http
friend class Http friend
Definition at line 51 of file http.hpp.
Member Data Documentation
http
class Http* HttpThread::http private
http handle
Definition at line 68 of file http.hpp.
Referenced by connection(), and Http::httpOpen().
httpReader
void(* HttpThread::httpReader) (void *thrhdl, class Http *http)
Http reader.
Definition at line 97 of file http.hpp.
Referenced by connection(), and Http::httpOpen().
modethr
bool HttpThread::modethr private
thread or not
Definition at line 67 of file http.hpp.
Referenced by begin(), end(), and Http::httpOpen().
thrhdl
void* HttpThread::thrhdl private
thread handle
Definition at line 66 of file http.hpp.
Referenced by connection(), and Http::httpOpen().
url
char HttpThread::url[URL_LEN] private
url
Definition at line 69 of file http.hpp.
Referenced by connection(), end(), Http::httpOpen(), and putfifo().
waitfifo
tWaitFifo* HttpThread::waitfifo private
fifo
Definition at line 64 of file http.hpp.
Referenced by begin(), HttpThread(), and putfifo().
The documentation for this class was generated from the following files:
src/vreng/http.hpp
src/vreng/http.cpp