VREng: File Class Reference
File Class Reference
File class.
#include <file.hpp>
Static Public Member Functions
static FILE * openFile (const char *filename, const char *param)
static void closeFile (FILE *f)
static bool bigEndian ()
check that this machine is big endian return 1 if big endian else 0 if little endian
static bool littleEndian ()
check that this machine is little endian return 1 if little endian else 0 if big endian
static void * swapEndian (void *addr, int nb)
static void localEndian (void *addr, int nb)
static void convertShort (uint16_t *array, long length)
static void convertLong (uint32_t *array, long length)
static int read_char (FILE *f)
static int read_short (FILE *f)
static int read_long (FILE *f)
static float read_float (FILE *f)
static int read_short_le (FILE *f)
static int read_long_le (FILE *f)
static float read_float_le (FILE *f)
static int read_string (FILE *f, char *s, int maxlen)
static void read_buf (FILE *f, char *s, int len)
static void skip_byte (FILE *f, int skiplen)
Detailed Description
File class.
Definition at line 28 of file file.hpp.
Member Function Documentation
bigEndian()
bool File::bigEndian () static
check that this machine is big endian return 1 if big endian else 0 if little endian
Definition at line 46 of file file.cpp.
Referenced by littleEndian(), and localEndian().
closeFile()
void File::closeFile (FILE * f) static
Definition at line 36 of file file.cpp.
References cnt_close.
Referenced by Widgets::addDynamicMenus(), Widgets::addMarkCB(), Movie::changePermanent(), World::checkIcons(), closeDXF(), closelog(), Widgets::createMarkMenu(), Widgets::createPrefsDialog(), Cache::curl(), deleteDXF(), Reader::downloadInCache(), Rtp::getRtpName(), Book::httpReader(), Bvh::httpReader(), Lwo::httpReader(), rigid::httpReader(), Face::httpReader(), Hairs::httpReader(), Obj::httpReader(), Off::httpReader(), Txf::httpReader(), Guy::httpReader(), World::httpReader(), Walls::httpReader(), X3d::httpReader(), Icon::Icon(), _3ds::importModel(), Ase::importModel(), Cache::inCache(), Pref::initEnvPrefs(), Img::loadBMP(), Body::loadBodyParts(), Img::loadDDS(), Img::loadGIF(), Img::loadJPG(), Img::loadPCX(), Img::loadPGM(), Img::loadPNG(), Img::loadPPM(), Img::loadPSD(), Img::loadSGI(), Img::loadTGA(), Img::loadXBM(), Img::loadXPM(), Cache::openCache(), Icon::quit(), BoneVertex::read(), V3d::readV3Dfile(), Widgets::saveCB(), Img::saveJPG(), Img::savePNG(), Img::savePPM(), Img::saveTGA(), Movie::stop(), vncDecryptPasswdFromFile(), vncEncryptAndStorePasswd(), Avi::write_header(), and Avi::~Avi().
convertLong()
void File::convertLong (uint32_t * array, long length) static
Definition at line 137 of file file.cpp.
Referenced by Img::loadSGI().
convertShort()
void File::convertShort (uint16_t * array, long length) static
Definition at line 124 of file file.cpp.
Referenced by Img::loadSGI().
littleEndian()
bool File::littleEndian () static
check that this machine is little endian return 1 if little endian else 0 if big endian
Definition at line 61 of file file.cpp.
References bigEndian().
Referenced by Movie::changePermanent(), Hairs::httpReader(), and Img::loadSGI().
localEndian()
void File::localEndian (void * addr, int nb) static
Definition at line 116 of file file.cpp.
References bigEndian(), and swapEndian().
Referenced by _3ds::processNextChunk(), _3ds::readChunk(), _3ds::readUVCoordinates(), _3ds::readVertexIndices(), and _3ds::readVertices().
openFile()
FILE * File::openFile (const char * filename, const char * param) static
Definition at line 27 of file file.cpp.
References cnt_open.
Referenced by Widgets::addDynamicMenus(), Widgets::addMarkCB(), World::checkIcons(), Widgets::createMarkMenu(), Widgets::createPrefsDialog(), Cache::curl(), Reader::downloadInCache(), Rtp::getRtpName(), World::httpReader(), X3d::httpReader(), Icon::Icon(), Cache::inCache(), Pref::initEnvPrefs(), Movie::mpegInit(), Avi::open_output_file(), Cache::openCache(), openDXF(), printlog(), Icon::quit(), BoneVertex::read(), V3d::readV3Dfile(), Widgets::saveCB(), Img::saveJPG(), Img::savePNG(), Img::savePPM(), Img::saveTGA(), vncDecryptPasswdFromFile(), vncEncryptAndStorePasswd(), and writelog().
read_buf()
void File::read_buf (FILE * f, char * s, int len) static
Definition at line 215 of file file.cpp.
References read_char().
Referenced by Md2::getFrames(), and Md2::loadFromFile().
read_char()
int File::read_char (FILE * f) static
Definition at line 152 of file file.cpp.
Referenced by Md2::getFrames(), read_buf(), read_long(), read_long_le(), read_short(), read_short_le(), read_string(), and Lwo::readSurf().
read_float()
float File::read_float (FILE * f) static
Definition at line 182 of file file.cpp.
References read_long().
Referenced by Lwo::readPnts().
read_float_le()
float File::read_float_le (FILE * f) static
Definition at line 188 of file file.cpp.
References read_long_le().
Referenced by Md2::getFrames(), and Md2::getGLCmds().
read_long()
int File::read_long (FILE * f) static
Definition at line 172 of file file.cpp.
References read_char().
Referenced by Lwo::httpReader(), read_float(), and Lwo::readSurf().
read_long_le()
int File::read_long_le (FILE * f) static
Definition at line 177 of file file.cpp.
References read_char().
Referenced by Md2::getGLCmds(), Md2::loadFromFile(), and read_float_le().
read_short()
int File::read_short (FILE * f) static
Definition at line 162 of file file.cpp.
References read_char().
Referenced by Lwo::readPols(), and Lwo::readSurf().
read_short_le()
int File::read_short_le (FILE * f) static
Definition at line 167 of file file.cpp.
References read_char().
read_string()
int File::read_string (FILE * f, char * s, int maxlen) static
Definition at line 194 of file file.cpp.
References read_char().
Referenced by Lwo::readSrfs(), and Lwo::readSurf().
skip_byte()
void File::skip_byte (FILE * f, int skiplen) static
Definition at line 227 of file file.cpp.
Referenced by Lwo::httpReader(), Md2::loadFromFile(), Lwo::readPols(), and Lwo::readSurf().
swapEndian()
void * File::swapEndian (void * addr, int nb) static
Definition at line 66 of file file.cpp.
References error().
Referenced by localEndian().
The documentation for this class was generated from the following files:
src/vreng/file.hpp
src/vreng/file.cpp