VREng: Times Class Reference
Times Class Reference
Times class.
#include <timer.hpp>
Public Member Functions
float getRate ()
Returns actual rate.
bool checkRate (uint16_t rate)
Static Public Member Functions
static double fTime ()
Returns float time in milliseconds.
static double diffDates (struct timeval t1, struct timeval t2)
Computes t2-t1 in seconds.
static float delta ()
Returns the number of seconds that have elapsed since the previous call to this function.
Public Attributes
ProfileTime init
ProfileTime net
ProfileTime simul
ProfileTime render
ProfileTime idle
ProfileTime capture
ProfileTime mysql
ProfileTime object
ProfileTime image
Detailed Description
Times class.
Definition at line 46 of file timer.hpp.
Member Function Documentation
checkRate()
bool Times::checkRate (uint16_t rate)
Definition at line 74 of file timer.cpp.
References g, Gui::getCycles(), getRate(), Global::gui, and ratio.
Referenced by Water::changePermanent(), and Guy::render().
delta()
float Times::delta () static
Returns the number of seconds that have elapsed since the previous call to this function.
Definition at line 82 of file timer.cpp.
References diffDates(), first, and gettimeofday().
diffDates()
double Times::diffDates (struct timeval t1, struct timeval t2) static
Computes t2-t1 in seconds.
Definition at line 62 of file timer.cpp.
Referenced by delta(), NetTimeout(), statAdjust(), ProfileTime::stop(), and Particle::timedelta().
fTime()
double Times::fTime () static
Returns float time in milliseconds.
Return float time in milliseconds.
Definition at line 53 of file timer.cpp.
References gettimeofday().
getRate()
float Times::getRate ()
Returns actual rate.
Definition at line 68 of file timer.cpp.
References ProfileTime::cumul_time, g, Gui::getCycles(), Global::gui, idle, render, and simul.
Referenced by Render::cameraPosition(), Mirage::changePermanent(), Icon::changePosition(), checkRate(), Android::connectToBapServer(), statTimings(), and Scene::updateHud().
Member Data Documentation
capture
ProfileTime Times::capture
Definition at line 49 of file timer.hpp.
Referenced by Capture::startVideo(), and Capture::stopVideo().
idle
ProfileTime Times::idle
Definition at line 49 of file timer.hpp.
Referenced by getRate(), and statTimings().
image
ProfileTime Times::image
Definition at line 49 of file timer.hpp.
Referenced by Http::httpOpen(), and statTimings().
init
ProfileTime Times::init
Definition at line 49 of file timer.hpp.
Referenced by Global::start(), Global::startCB(), and statTimings().
mysql
ProfileTime Times::mysql
Definition at line 49 of file timer.hpp.
Referenced by statTimings(), WObject::updateMySqlPosition(), WObject::updateMySqlPosZ(), and WObject::updateMySqlState().
net
ProfileTime Times::net
Definition at line 49 of file timer.hpp.
Referenced by Channel::init(), statNetwork(), and statTimings().
object
ProfileTime Times::object
Definition at line 49 of file timer.hpp.
Referenced by Parse::parseVreLines(), and statTimings().
render
ProfileTime Times::render
Definition at line 49 of file timer.hpp.
Referenced by getRate(), Scene::paintScene(), and statTimings().
simul
ProfileTime Times::simul
Definition at line 49 of file timer.hpp.
Referenced by getRate(), Scene::paintScene(), and statTimings().
The documentation for this class was generated from the following files:
src/vreng/timer.hpp
src/vreng/timer.cpp