VREng: Reader Class Reference
Reader Class Reference
Reader class.
#include <reader.hpp>
Public Types
enum { KEEP_OPEN, KEEP_CLOSE }
Public Member Functions
Reader (void *tex, ImageReader read_func)
Constructor.
virtual ~Reader ()
virtual FILE * downloadInCache (class Texture *tex)
Destructor.
virtual FILE * downloadInCache (void *tex, bool flagclo)
Downloads a file into the cache.
virtual FILE * downloadInCache (const char *url, char *filename)
Downloads a file into the cache.
virtual char * getFilename (void *tex)
Gets filename.
virtual uint8_t getChar (FILE *fp)
virtual uint8_t getChar ()
Gets next char.
virtual uint8_t getChar1 (FILE *fp)
virtual uint8_t getChar1 ()
Gets next usable char.
virtual int16_t getShort (FILE *fp)
Gets short integer.
virtual uint32_t getUInt (FILE *fp)
Gets unsigned integer.
virtual int32_t getInt (FILE *fp)
virtual int32_t getInt ()
Gets next integer.
virtual void skipSpaces (FILE *fp)
virtual void skipSpaces ()
Skips spaces.
virtual void reset ()
Resets buffer.
virtual uint8_t getByte (void *texhdl, ImageReader read_func)
Reads and returns a byte.
Public Attributes
void * img_hdl
handle (tex).
ImageReader read_func
http read function.
int ch
current char.
Detailed Description
Reader class.
Definition at line 32 of file reader.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
KEEP_OPEN
KEEP_CLOSE
Definition at line 36 of file reader.hpp.
Constructor & Destructor Documentation
Reader()
Reader::Reader (void * tex, ImageReader read_func)
Constructor.
Definition at line 28 of file reader.cpp.
References img_hdl, new_imgreader, and read_func.
~Reader()
virtual Reader::~Reader () inline virtual
Definition at line 48 of file reader.hpp.
References del_imgreader.
Member Function Documentation
downloadInCache() [1/3]
FILE * Reader::downloadInCache (class Texture * tex) virtual
Destructor.
Definition at line 46 of file reader.cpp.
References error(), Texture::http, Cache::openCache(), and Texture::url.
Referenced by downloadInCache(), and Img::loadTIF().
downloadInCache() [2/3]
FILE * Reader::downloadInCache (const char * url, char * filename) virtual
Downloads a file into the cache.
Definition at line 56 of file reader.cpp.
References error(), img_hdl, File::openFile(), and read_func.
downloadInCache() [3/3]
FILE * Reader::downloadInCache (void * tex, bool flagclo) virtual
Downloads a file into the cache.
Definition at line 35 of file reader.cpp.
References File::closeFile(), and downloadInCache().
getByte()
uint8_t Reader::getByte (void * texhdl, ImageReader read_func) virtual
Reads and returns a byte.
Definition at line 183 of file reader.cpp.
References imgbuf, imgbuf_len, imgbuf_pos, and read_func.
getChar() [1/2]
uint8_t Reader::getChar () virtual
Gets next char.
Definition at line 82 of file reader.cpp.
References ch, img_hdl, and read_func.
Referenced by getChar1().
getChar() [2/2]
uint8_t Reader::getChar (FILE * fp) virtual
Definition at line 91 of file reader.cpp.
References ch.
getChar1() [1/2]
uint8_t Reader::getChar1 () virtual
Gets next usable char.
Definition at line 97 of file reader.cpp.
References ch, and getChar().
Referenced by getInt(), and skipSpaces().
getChar1() [2/2]
uint8_t Reader::getChar1 (FILE * fp) virtual
Definition at line 109 of file reader.cpp.
References ch, and getChar().
getFilename()
char * Reader::getFilename (void * tex) virtual
Gets filename.
Definition at line 73 of file reader.cpp.
References PATH_LEN, Cache::setCacheName(), and Texture::url.
Referenced by Img::loadBMP(), and Img::loadTIF().
getInt() [1/2]
int32_t Reader::getInt () virtual
Gets next integer.
Definition at line 138 of file reader.cpp.
References ch, and getChar1().
getInt() [2/2]
int32_t Reader::getInt (FILE * fp) virtual
Definition at line 161 of file reader.cpp.
References ch, and getChar1().
getShort()
int16_t Reader::getShort (FILE * fp) virtual
Gets short integer.
Definition at line 131 of file reader.cpp.
Referenced by Img::loadBMP().
getUInt()
uint32_t Reader::getUInt (FILE * fp) virtual
Gets unsigned integer.
Definition at line 150 of file reader.cpp.
Referenced by Img::loadBMP().
reset()
void Reader::reset () virtual
Resets buffer.
Definition at line 178 of file reader.cpp.
References imgbuf_len, and imgbuf_pos.
skipSpaces() [1/2]
void Reader::skipSpaces () virtual
Skips spaces.
Definition at line 121 of file reader.cpp.
References ch, and getChar1().
skipSpaces() [2/2]
void Reader::skipSpaces (FILE * fp) virtual
Definition at line 126 of file reader.cpp.
References ch, and getChar1().
Member Data Documentation
ch
int Reader::ch
current char.
Definition at line 43 of file reader.hpp.
Referenced by getChar(), getChar1(), getInt(), and skipSpaces().
img_hdl
void* Reader::img_hdl
handle (tex).
Definition at line 41 of file reader.hpp.
Referenced by downloadInCache(), getChar(), and Reader().
read_func
ImageReader Reader::read_func
http read function.
Definition at line 42 of file reader.hpp.
Referenced by downloadInCache(), getByte(), getChar(), and Reader().
The documentation for this class was generated from the following files:
src/vreng/reader.hpp
src/vreng/reader.cpp