VREng: Universe Class Reference
Universe Class Reference
Universe class.
#include <universe.hpp>
Public Member Functions
Universe ()
Constructor.
virtual ~Universe ()
Destructor.
virtual void getUrl (char *_url)
gets url string
virtual void startWheel ()
Starts the wheel progression indicator.
virtual void stopWheel ()
Stops the wheel progression indicator.
Static Public Member Functions
static Universe * current ()
pointer
static void init ()
create the "manager"
static void sigWheel (int sig)
Intercepts signal SIGTERM.
static void * runWheel (void *arg)
Runs the wheel progression indicator.
Public Attributes
char * universe_name
http server name
char * url
url
char * group
group addr
char * urlpfx
url prefix
uint16_t port
port
uint8_t ttl
scope
uint8_t version
vre version
uint8_t prop
notused
uint16_t worldcnt
world counter
World * worldList
list of worlds
User * localuser
current player
class Wheel * wheel
wheel instance
Detailed Description
Universe class.
Definition at line 34 of file universe.hpp.
Constructor & Destructor Documentation
Universe()
Universe::Universe ()
Constructor.
Definition at line 37 of file universe.cpp.
References Global::channel, DBG_INIT, DEF_HTTP_SERVER, DEF_MANAGER_CHANNEL, DEF_URL_PFX, g, Channel::getGroup(), Channel::getTtl(), group, GROUP_LEN, localuser, Pref::new_universe, port, Global::pref, prop, trace(), ttl, Global::universe, universe_name, url, Global::url, urlpfx, version, VRE_VERSION, VRENG_MPORT_BASE, wheel, worldcnt, and worldList.
Referenced by current().
~Universe()
Universe::~Universe () virtual
Destructor.
Definition at line 81 of file universe.cpp.
References group, localuser, universe_name, url, urlpfx, wheel, and worldList.
Member Function Documentation
current()
Universe * Universe::current () static
pointer
Definition at line 92 of file universe.cpp.
References Universe().
Referenced by Url::abs(), Channel::currentTtl(), Widgets::destinationsDialog(), Gate::enter(), Wind::getHttp(), Widgets::helpCB(), Widgets::homeCB(), World::init(), Widgets::openWorldsDialog(), Vrelet::parser(), Url::parser(), Global::startCB(), and World::World().
getUrl()
void Universe::getUrl (char * _url) virtual
gets url string
Definition at line 101 of file universe.cpp.
References url, and URL_LEN.
init()
void Universe::init () static
create the "manager"
Initialization from vreng.cc - static.
Definition at line 107 of file universe.cpp.
References DEF_MANAGER_CHANNEL, manager, MANAGER_NAME, World::setManagerChanAndJoin(), and World::setName().
Referenced by Global::startCB().
runWheel()
void * Universe::runWheel (void * arg) static
Runs the wheel progression indicator.
Definition at line 131 of file universe.cpp.
References Wheel::current(), new_world, progress, progression(), and Wheel::render().
Referenced by startWheel().
sigWheel()
void Universe::sigWheel (int sig) static
Intercepts signal SIGTERM.
Definition at line 116 of file universe.cpp.
References progress, and progression().
Referenced by startWheel().
startWheel()
void Universe::startWheel () virtual
Starts the wheel progression indicator.
Definition at line 122 of file universe.cpp.
References runWheel(), and sigWheel().
Referenced by World::enter(), and World::init().
stopWheel()
void Universe::stopWheel () virtual
Stops the wheel progression indicator.
Definition at line 149 of file universe.cpp.
References progress, and progression().
Referenced by World::enter(), and World::init().
Member Data Documentation
group
char* Universe::group
group addr
Definition at line 39 of file universe.hpp.
Referenced by World::init(), Universe(), and ~Universe().
localuser
User* Universe::localuser
current player
Definition at line 47 of file universe.hpp.
Referenced by World::init(), Universe(), and ~Universe().
port
uint16_t Universe::port
port
Definition at line 41 of file universe.hpp.
Referenced by World::init(), and Universe().
prop
uint8_t Universe::prop
notused
Definition at line 44 of file universe.hpp.
Referenced by Universe().
ttl
uint8_t Universe::ttl
scope
Definition at line 42 of file universe.hpp.
Referenced by Channel::currentTtl(), and Universe().
universe_name
char* Universe::universe_name
http server name
Definition at line 37 of file universe.hpp.
Referenced by Universe(), and ~Universe().
url
char* Universe::url
url
Definition at line 38 of file universe.hpp.
Referenced by Gate::enter(), getUrl(), Universe(), and ~Universe().
urlpfx
char* Universe::urlpfx
url prefix
Definition at line 40 of file universe.hpp.
Referenced by Universe(), and ~Universe().
version
uint8_t Universe::version
vre version
Definition at line 43 of file universe.hpp.
Referenced by Universe().
wheel
class Wheel* Universe::wheel
wheel instance
Definition at line 48 of file universe.hpp.
Referenced by Universe(), and ~Universe().
worldcnt
uint16_t Universe::worldcnt
world counter
Definition at line 45 of file universe.hpp.
Referenced by Universe().
worldList
World* Universe::worldList
list of worlds
Definition at line 46 of file universe.hpp.
Referenced by Universe(), and ~Universe().
The documentation for this class was generated from the following files:
src/vreng/universe.hpp
src/vreng/universe.cpp