VREng: Navig Class Reference
Navig Class Reference
Navig class.
#include <navig.hpp>
Public Member Functions
Navig (Widgets *, class Scene &)
UBox & createManipulator ()
void selectObject (ObjInfo *, int button_no)
void startMotion (UMouseEvent &, Motion *mvt_x, Motion *mvt_y)
void doMotion (UMouseEvent &)
void stopMotion ()
Private Member Functions
void initNavigMenu ()
void setMouseRef (UMouseEvent &e)
void mousePressB1orB3 (UMouseEvent &, int x, int y, int button_no)
void mousePressB2 (UMouseEvent &, int x, int y, int button_no)
void mousePressCB (UMouseEvent &)
void mouseReleaseCB (UMouseEvent &)
void mouseDragCB (UMouseEvent &)
void mouseMoveCB (UMouseEvent &)
void keyPressCB (UKeyEvent &)
void keyReleaseCB (UKeyEvent &)
Private Attributes
Widgets & gw
float xref
float yref
bool followMouseMode
flag to follow mouse.
int depthsel
UStr selected_object_url
UStr object_name
UStr object_class
ULabel object_infos
UPopmenu object_menu
UCtlmenu navig_menu
uptr< UMenu > opened_menu
Friends
class Widgets
Detailed Description
Navig class.
Definition at line 32 of file navig.hpp.
Constructor & Destructor Documentation
Navig()
Navig::Navig (Widgets * _gw, class Scene & scene)
Definition at line 54 of file navig.cpp.
References initNavigMenu(), keyPressCB(), keyReleaseCB(), mouseDragCB(), mouseMoveCB(), mousePressCB(), mouseReleaseCB(), navig_menu, object_class, object_infos, object_menu, and object_name.
Member Function Documentation
createManipulator()
UBox & Navig::createManipulator ()
Definition at line 375 of file navig.cpp.
References g, mouseDragCB(), mouseReleaseCB(), Theme::Rotxleft, Theme::Rotxright, Theme::Rotydown, Theme::Rotyup, Theme::Rotzleft, Theme::Rotzright, setMouseRef(), startMotion(), Global::theme, Motion::trans_forw, Motion::trans_left, Motion::trans_up, Theme::Transx, Theme::Transy, Theme::Transz, Motion::xrot_left, Motion::xrot_right, Motion::yrot_down, Motion::yrot_up, Motion::zrot_left, and Motion::zrot_right.
doMotion()
void Navig::doMotion (UMouseEvent & e)
Definition at line 292 of file navig.cpp.
References motionx, motiony, Motion::move(), xref, and yref.
Referenced by Joystick::dragCanvasCB(), initNavigMenu(), and Joystick::Joystick().
initNavigMenu()
void Navig::initNavigMenu () private
Definition at line 312 of file navig.cpp.
References Theme::Backward, doMotion(), Theme::Forward, g, Theme::Left, Theme::LeftTrans, navig_menu, Theme::Right, Theme::RightTrans, startMotion(), stopMotion(), Global::theme, Theme::UpDown, Motion::xtrans, Motion::ytrans, Motion::zrot, and Motion::ztrans.
Referenced by Navig().
keyPressCB()
void Navig::keyPressCB (UKeyEvent & e) private
Definition at line 154 of file navig.cpp.
References User::ASPEED, gettimeofday(), Widgets::gui, gw, Vnc::keyEvent(), localuser, User::LSPEED, Widgets::processKey(), User::specialAction(), UserAction::UA_SETASPEED, UserAction::UA_SETLSPEED, and Gui::vnc.
Referenced by Navig().
keyReleaseCB()
void Navig::keyReleaseCB (UKeyEvent & e) private
Definition at line 176 of file navig.cpp.
References Widgets::gui, gw, Vnc::keyEvent(), Widgets::processKey(), and Gui::vnc.
Referenced by Navig().
mouseDragCB()
void Navig::mouseDragCB (UMouseEvent & e) private
Definition at line 124 of file navig.cpp.
References Widgets::gui, gw, WObject::isValid(), localuser, WObject::resetFlashy(), WObject::resetRay(), and Gui::selected_object.
Referenced by createManipulator(), and Navig().
mouseMoveCB()
void Navig::mouseMoveCB (UMouseEvent & e) private
Definition at line 136 of file navig.cpp.
References depthsel, followMouseMode, Widgets::getPointedObject(), Widgets::gui, gw, WObject::isValid(), Vnc::mouseEvent(), objinfo, WObject::resetFlashy(), WObject::resetRay(), Gui::selected_object, selectObject(), and Gui::vnc.
Referenced by Navig().
mousePressB1orB3()
void Navig::mousePressB1orB3 (UMouseEvent & e, int x, int y, int button_no) private
Definition at line 189 of file navig.cpp.
References Gui::board, DBG_GUI, depthsel, WObject::getInstance(), Widgets::getPointedObject(), Gui::getSelectedObject(), Widgets::gui, gw, WObject::isValid(), Widgets::messages, WObject::names, navig_menu, object_menu, objinfo, opened_menu, Messages::performRequest(), WObject::resetFlashy(), WObject::resetRay(), Gui::selected_object, selected_object_url, selectObject(), Widgets::setRayDirection(), WObject::solid, trace(), Names::url, and Gui::vrelet.
Referenced by mousePressCB().
mousePressB2()
void Navig::mousePressB2 (UMouseEvent & , int x, int y, int button_no) private
Definition at line 234 of file navig.cpp.
References depthsel, Widgets::getPointedObject(), Widgets::gui, gw, WObject::isValid(), objinfo, WObject::resetFlashy(), Gui::selected_object, selectObject(), Widgets::setRayDirection(), and WObject::solid.
Referenced by mousePressCB().
mousePressCB()
void Navig::mousePressCB (UMouseEvent & e) private
Definition at line 83 of file navig.cpp.
References Gui::board, Gui::carrier, Widgets::gui, gw, Board::isDrawing(), Carrier::isTaking(), Vnc::mouseEvent(), Carrier::mouseEvent(), mousePressB1orB3(), mousePressB2(), Widgets::scene, and Gui::vnc.
Referenced by Navig().
mouseReleaseCB()
void Navig::mouseReleaseCB (UMouseEvent & e) private
Definition at line 110 of file navig.cpp.
References Widgets::gui, gw, localuser, Vnc::mouseEvent(), opened_menu, WObject::resetRay(), Gui::selected_object, stopMotion(), and Gui::vnc.
Referenced by createManipulator(), and Navig().
selectObject()
void Navig::selectObject (ObjInfo * objinfo, int button_no)
Definition at line 250 of file navig.cpp.
References gw, Widgets::infos, ObjInfo::name, object_class, object_infos, object_menu, object_name, and objinfo.
Referenced by Gui::clearInfoBar(), mouseMoveCB(), mousePressB1orB3(), and mousePressB2().
setMouseRef()
void Navig::setMouseRef (UMouseEvent & e) private
Definition at line 464 of file navig.cpp.
Referenced by createManipulator().
startMotion()
void Navig::startMotion (UMouseEvent & e, Motion * mvt_x, Motion * mvt_y)
Definition at line 282 of file navig.cpp.
References motionx, motiony, Motion::stop(), xref, and yref.
Referenced by createManipulator(), initNavigMenu(), Joystick::Joystick(), and Joystick::pressCanvasCB().
stopMotion()
void Navig::stopMotion ()
Definition at line 300 of file navig.cpp.
References motionx, motiony, and Motion::stop().
Referenced by initNavigMenu(), Joystick::Joystick(), mouseReleaseCB(), and Joystick::releaseCanvasCB().
Friends And Related Function Documentation
Widgets
friend class Widgets friend
Definition at line 43 of file navig.hpp.
Member Data Documentation
depthsel
int Navig::depthsel private
Definition at line 47 of file navig.hpp.
Referenced by mouseMoveCB(), mousePressB1orB3(), and mousePressB2().
followMouseMode
bool Navig::followMouseMode private
flag to follow mouse.
Definition at line 46 of file navig.hpp.
Referenced by mouseMoveCB().
gw
Widgets& Navig::gw private
Definition at line 44 of file navig.hpp.
Referenced by keyPressCB(), keyReleaseCB(), mouseDragCB(), mouseMoveCB(), mousePressB1orB3(), mousePressB2(), mousePressCB(), mouseReleaseCB(), and selectObject().
navig_menu
UCtlmenu Navig::navig_menu private
Definition at line 52 of file navig.hpp.
Referenced by initNavigMenu(), mousePressB1orB3(), and Navig().
object_class
UStr Navig::object_class private
Definition at line 49 of file navig.hpp.
Referenced by Navig(), and selectObject().
object_infos
ULabel Navig::object_infos private
Definition at line 50 of file navig.hpp.
Referenced by Navig(), and selectObject().
object_menu
UPopmenu Navig::object_menu private
Definition at line 51 of file navig.hpp.
Referenced by mousePressB1orB3(), Navig(), and selectObject().
object_name
UStr Navig::object_name private
Definition at line 49 of file navig.hpp.
Referenced by Navig(), and selectObject().
opened_menu
uptr<UMenu> Navig::opened_menu private
Definition at line 53 of file navig.hpp.
Referenced by mousePressB1orB3(), and mouseReleaseCB().
selected_object_url
UStr Navig::selected_object_url private
Definition at line 48 of file navig.hpp.
Referenced by mousePressB1orB3().
xref
float Navig::xref private
Definition at line 45 of file navig.hpp.
Referenced by doMotion(), and startMotion().
yref
float Navig::yref private
Definition at line 45 of file navig.hpp.
Referenced by doMotion(), and startMotion().
The documentation for this class was generated from the following files:
src/gui/navig.hpp
src/gui/navig.cpp