VREng: Pitch Class Reference
Pitch Class Reference
Pitch class.
#include <pitch.hpp>
Public Member Functions
Pitch (Widgets *, GLint radius)
Public Attributes
Widgets & gw
bool is_drawing
Private Member Functions
void doAction ()
void paintCB (UPaintEvent &)
void dragCB (UMouseEvent &)
void doubleClickCB (UMouseEvent &)
Private Attributes
UBox canvas
USize canvas_size
GLfloat circle_radius
GLfloat current_radius
GLfloat delta
GLfloat angle
UPoint arrow_point
Detailed Description
Pitch class.
Definition at line 31 of file pitch.hpp.
Constructor & Destructor Documentation
Pitch()
Pitch::Pitch (Widgets * _gw, GLint radius)
Definition at line 41 of file pitch.cpp.
References angle, arrow_point, canvas_size, circle_radius, current_radius, delta, doubleClickCB(), dragCB(), and paintCB().
Member Function Documentation
doAction()
void Pitch::doAction () private
Definition at line 61 of file pitch.cpp.
References angle, gettimeofday(), localuser, User::specialAction(), and UserAction::UA_SETPITCH.
Referenced by doubleClickCB(), and dragCB().
doubleClickCB()
void Pitch::doubleClickCB (UMouseEvent & e) private
Definition at line 93 of file pitch.cpp.
References angle, delta, and doAction().
Referenced by Pitch().
dragCB()
void Pitch::dragCB (UMouseEvent & e) private
Definition at line 72 of file pitch.cpp.
References angle, arrow_point, current_radius, delta, doAction(), and M_PI.
Referenced by Pitch().
paintCB()
void Pitch::paintCB (UPaintEvent & e) private
Definition at line 102 of file pitch.cpp.
References arrow_point, circle_radius, delta, g, Theme::joystickArmColor, Theme::joystickColor, M_PI, and Global::theme.
Referenced by Pitch().
Member Data Documentation
angle
GLfloat Pitch::angle private
Definition at line 43 of file pitch.hpp.
Referenced by doAction(), doubleClickCB(), dragCB(), and Pitch().
arrow_point
UPoint Pitch::arrow_point private
Definition at line 44 of file pitch.hpp.
Referenced by dragCB(), paintCB(), and Pitch().
canvas
UBox Pitch::canvas private
Definition at line 39 of file pitch.hpp.
canvas_size
USize Pitch::canvas_size private
Definition at line 40 of file pitch.hpp.
Referenced by Pitch().
circle_radius
GLfloat Pitch::circle_radius private
Definition at line 41 of file pitch.hpp.
Referenced by paintCB(), and Pitch().
current_radius
GLfloat Pitch::current_radius private
Definition at line 41 of file pitch.hpp.
Referenced by dragCB(), and Pitch().
delta
GLfloat Pitch::delta private
Definition at line 42 of file pitch.hpp.
Referenced by doubleClickCB(), dragCB(), paintCB(), and Pitch().
gw
Widgets& Pitch::gw
Definition at line 35 of file pitch.hpp.
is_drawing
bool Pitch::is_drawing
Definition at line 36 of file pitch.hpp.
The documentation for this class was generated from the following files:
src/gui/pitch.hpp
src/gui/pitch.cpp