VREng: Capture Class Reference
Capture Class Reference
#include <capture.hpp>
Public Member Functions
Capture ()
void writeGIFImage ()
Capture and save one image in GIF.
void writeJPGImage ()
Capture and save one image in JPG.
void writePNGImage ()
Capture and save one image in PNG.
void startVideo ()
Start capture video.
void stopVideo ()
Stop capture video.
void writeVideoFrame ()
Make capture video.
bool isCapturingVideo () const
Static Public Attributes
static const unsigned int MAX_CAPTURE_COUNT = 1000
Private Member Functions
void captureXwd (const char *ext)
Capture and save one image by xwd.
void captureGl2jpg (const char *ext)
Capture and save one image in JPEG.
void captureGl2png (const char *ext)
Capture and save one image in PNG.
Private Attributes
bool is_capturing
is capturing video.
unsigned int capture_no
Detailed Description
Definition at line 31 of file capture.hpp.
Constructor & Destructor Documentation
Capture()
Capture::Capture ()
Definition at line 41 of file capture.cpp.
Member Function Documentation
captureGl2jpg()
void Capture::captureGl2jpg (const char * ext) private
Capture and save one image in JPEG.
capture JPEG (only 3D)
Definition at line 46 of file capture.cpp.
References Ogl::copyPixels(), notice(), and Img::saveJPG().
Referenced by writeJPGImage(), and writeVideoFrame().
captureGl2png()
void Capture::captureGl2png (const char * ext) private
Capture and save one image in PNG.
capture PNG (only 3D)
Definition at line 65 of file capture.cpp.
References notice(), and Img::savePNG().
Referenced by writePNGImage().
captureXwd()
void Capture::captureXwd (const char * ext) private
Capture and save one image by xwd.
capture XWD (whole window)
Definition at line 80 of file capture.cpp.
References World::current(), World::getName(), and notice().
Referenced by writeGIFImage().
isCapturingVideo()
bool Capture::isCapturingVideo () const inline
Definition at line 55 of file capture.hpp.
References is_capturing.
Referenced by Scene::paintScene().
startVideo()
void Capture::startVideo ()
Start capture video.
Definition at line 181 of file capture.cpp.
References Times::capture, capture_no, g, is_capturing, notice(), ProfileTime::start(), and Global::times.
Referenced by Panels::Panels().
stopVideo()
void Capture::stopVideo ()
Stop capture video.
Definition at line 190 of file capture.cpp.
References Times::capture, capture_no, World::current(), g, is_capturing, MAX_CAPTURE_COUNT, notice(), ProfileTime::stop(), Global::times, and World::WORLD_LEN.
Referenced by Panels::Panels(), and writeVideoFrame().
writeGIFImage()
void Capture::writeGIFImage ()
Capture and save one image in GIF.
callback capture GIF
Definition at line 164 of file capture.cpp.
References CAMERASND, captureXwd(), and Sound::playSound().
writeJPGImage()
void Capture::writeJPGImage ()
Capture and save one image in JPG.
callback capture JPG
Definition at line 153 of file capture.cpp.
References CAMERASND, captureGl2jpg(), World::current(), g, Sound::playSound(), Global::render, Render::setFlash(), and World::WORLD_LEN.
Referenced by Panels::Panels().
writePNGImage()
void Capture::writePNGImage ()
Capture and save one image in PNG.
callback capture PNG
Definition at line 171 of file capture.cpp.
References CAMERASND, captureGl2png(), World::current(), Sound::playSound(), and World::WORLD_LEN.
Referenced by Panels::Panels().
writeVideoFrame()
void Capture::writeVideoFrame ()
Make capture video.
Definition at line 209 of file capture.cpp.
References capture_no, captureGl2jpg(), MAX_CAPTURE_COUNT, and stopVideo().
Referenced by Scene::paintScene().
Member Data Documentation
capture_no
unsigned int Capture::capture_no private
Definition at line 59 of file capture.hpp.
Referenced by startVideo(), stopVideo(), and writeVideoFrame().
is_capturing
bool Capture::is_capturing private
is capturing video.
Definition at line 58 of file capture.hpp.
Referenced by isCapturingVideo(), startVideo(), and stopVideo().
MAX_CAPTURE_COUNT
const unsigned int Capture::MAX_CAPTURE_COUNT = 1000 static
Definition at line 33 of file capture.hpp.
Referenced by stopVideo(), and writeVideoFrame().
The documentation for this class was generated from the following files:
src/gui/capture.hpp
src/gui/capture.cpp