VREng: Messages Class Reference
Messages Class Reference
#include <message.hpp>
Public Member Functions
Messages (class Widgets *)
UBox & createMessagePanel (bool transparent)
void writeMessage (const char *mode, const char *from, const char *mess)
adds a new message to the messages box.
void performRequest (WObject *)
void initClicked ()
void getClicked (int *click, float clicked[])
get clicked object for the request.
Protected Member Functions
void actionCB ()
void getHistoryCB (int go)
void performRequest (const UStr &req)
void postRequest (const std::string &mess, std::string &result)
void convertTextToLink (const std::string &text, char **listeObjets, int size)
Protected Attributes
class Widgets & gw
UBox messages
UScrollpane scrollpane
UStr entry
std::vector< UStr > history
history log
int history_pos
float clicked [7]
Ocaml.
int nclicks
Ocaml.
Detailed Description
Definition at line 26 of file message.hpp.
Constructor & Destructor Documentation
Messages()
Messages::Messages (class Widgets * _gw)
Definition at line 53 of file message.cpp.
References history, history_pos, and messages.
Member Function Documentation
actionCB()
void Messages::actionCB () protected
Definition at line 93 of file message.cpp.
References entry, g, history, performRequest(), Global::user, User::userWriting(), and writeMessage().
Referenced by createMessagePanel().
convertTextToLink()
void Messages::convertTextToLink (const std::string & text, char ** listeObjets, int size) protected
Definition at line 204 of file message.cpp.
References messages, moveSatCamera(), size, and strcasecmp().
Referenced by postRequest().
createMessagePanel()
UBox & Messages::createMessagePanel (bool transparent)
Definition at line 61 of file message.cpp.
References actionCB(), entry, getHistoryCB(), messages, and scrollpane.
Referenced by Panels::Panels().
getClicked()
void Messages::getClicked (int * click, float clicked[])
get clicked object for the request.
Definition at line 165 of file message.cpp.
References clicked, and nclicks.
Referenced by Gui::getClicked().
getHistoryCB()
void Messages::getHistoryCB (int go) protected
Definition at line 107 of file message.cpp.
References entry, history, and history_pos.
Referenced by createMessagePanel().
initClicked()
void Messages::initClicked ()
Definition at line 157 of file message.cpp.
References clicked, MAXFLOAT, and nclicks.
Referenced by Gui::initClicked().
performRequest() [1/2]
void Messages::performRequest (const UStr & req) protected
Definition at line 113 of file message.cpp.
References clicked, entry, g, Global::gui, MAXFLOAT, nclicks, and Gui::writeMessage().
performRequest() [2/2]
void Messages::performRequest (WObject * object)
Definition at line 142 of file message.cpp.
References clicked, entry, and nclicks.
Referenced by actionCB(), and Navig::mousePressB1orB3().
postRequest()
void Messages::postRequest (const std::string & mess, std::string & result) protected
Definition at line 249 of file message.cpp.
References Render::calculateFov(), convertTextToLink(), g, Global::render, and string2Coord().
Referenced by writeMessage().
writeMessage()
void Messages::writeMessage (const char * mode, const char * from, const char * mess)
adds a new message to the messages box.
Definition at line 322 of file message.cpp.
References Theme::chatColor, g, messages, Theme::messColor, Theme::noticeColor, postRequest(), Theme::requestColor, Global::theme, and Theme::warningColor.
Referenced by actionCB(), and Gui::writeMessage().
Member Data Documentation
clicked
float Messages::clicked[7] protected
Ocaml.
Definition at line 54 of file message.hpp.
Referenced by getClicked(), initClicked(), and performRequest().
entry
UStr Messages::entry protected
Definition at line 51 of file message.hpp.
Referenced by actionCB(), createMessagePanel(), getHistoryCB(), and performRequest().
gw
class Widgets& Messages::gw protected
Definition at line 48 of file message.hpp.
history
std::vector<UStr> Messages::history protected
history log
Definition at line 52 of file message.hpp.
Referenced by actionCB(), getHistoryCB(), and Messages().
history_pos
int Messages::history_pos protected
Definition at line 53 of file message.hpp.
Referenced by getHistoryCB(), and Messages().
messages
UBox Messages::messages protected
Definition at line 49 of file message.hpp.
Referenced by convertTextToLink(), createMessagePanel(), Messages(), and writeMessage().
nclicks
int Messages::nclicks protected
Ocaml.
Definition at line 55 of file message.hpp.
Referenced by getClicked(), initClicked(), and performRequest().
scrollpane
UScrollpane Messages::scrollpane protected
Definition at line 50 of file message.hpp.
Referenced by createMessagePanel().
The documentation for this class was generated from the following files:
src/gui/message.hpp
src/gui/message.cpp