VREng: Joystick Class Reference
Joystick Class Reference
GUI Joystick.
#include <joystick.hpp>
Public Member Functions
Joystick (Widgets *, int radius)
Private Member Functions
void paintCanvasCB (UPaintEvent &)
void pressCanvasCB (UMouseEvent &)
void dragCanvasCB (UMouseEvent &)
void releaseCanvasCB (UMouseEvent &)
Private Attributes
Widgets & gw
bool is_drawing
float radius
UBox canvas
USize canvas_size
UPoint center_point
UPoint current_point
Detailed Description
GUI Joystick.
Definition at line 31 of file joystick.hpp.
Constructor & Destructor Documentation
Joystick()
Joystick::Joystick (Widgets * _gw, int radius)
Definition at line 41 of file joystick.cpp.
References Widgets::callAction(), canvas, canvas_size, center_point, Navig::doMotion(), dragCanvasCB(), g, Widgets::getNavig(), gw, Theme::joystickArmColor, Theme::joystickColor, Theme::JoystickLeftRight, Theme::JoystickUpDown, paintCanvasCB(), pressCanvasCB(), radius, releaseCanvasCB(), Navig::startMotion(), Navig::stopMotion(), Global::theme, UserAction::UA_PAUSE, Motion::xtrans, and Motion::ztrans.
Member Function Documentation
dragCanvasCB()
void Joystick::dragCanvasCB (UMouseEvent & e) private
Definition at line 90 of file joystick.cpp.
References current_point, Navig::doMotion(), Widgets::getNavig(), and gw.
Referenced by Joystick().
paintCanvasCB()
void Joystick::paintCanvasCB (UPaintEvent & e) private
Definition at line 105 of file joystick.cpp.
References center_point, current_point, g, is_drawing, Theme::joystickArmColor, Theme::joystickColor, radius, and Global::theme.
Referenced by Joystick().
pressCanvasCB()
void Joystick::pressCanvasCB (UMouseEvent & e) private
Definition at line 82 of file joystick.cpp.
References current_point, Widgets::getNavig(), gw, is_drawing, Navig::startMotion(), Motion::ytrans, and Motion::zrot.
Referenced by Joystick().
releaseCanvasCB()
void Joystick::releaseCanvasCB (UMouseEvent & e) private
Definition at line 97 of file joystick.cpp.
References current_point, Widgets::getNavig(), gw, is_drawing, and Navig::stopMotion().
Referenced by Joystick().
Member Data Documentation
canvas
UBox Joystick::canvas private
Definition at line 40 of file joystick.hpp.
Referenced by Joystick().
canvas_size
USize Joystick::canvas_size private
Definition at line 41 of file joystick.hpp.
Referenced by Joystick().
center_point
UPoint Joystick::center_point private
Definition at line 42 of file joystick.hpp.
Referenced by Joystick(), and paintCanvasCB().
current_point
UPoint Joystick::current_point private
Definition at line 42 of file joystick.hpp.
Referenced by dragCanvasCB(), paintCanvasCB(), pressCanvasCB(), and releaseCanvasCB().
gw
Widgets& Joystick::gw private
Definition at line 36 of file joystick.hpp.
Referenced by dragCanvasCB(), Joystick(), pressCanvasCB(), and releaseCanvasCB().
is_drawing
bool Joystick::is_drawing private
Definition at line 38 of file joystick.hpp.
Referenced by paintCanvasCB(), pressCanvasCB(), and releaseCanvasCB().
radius
float Joystick::radius private
Definition at line 39 of file joystick.hpp.
Referenced by Joystick(), and paintCanvasCB().
The documentation for this class was generated from the following files:
src/gui/joystick.hpp
src/gui/joystick.cpp