VREng: World Class Reference
World Class Reference
World class.
#include <world.hpp>
Public Types
enum { OLD, NEW }
Public Member Functions
World ()
Constructor.
virtual ~World ()
virtual void compute (time_t sec, time_t usec)
Destructor.
virtual void quit ()
Quits current world.
virtual const char * getName () const
Gets current world name.
virtual void setName (const char *name)
Builds world name from url.
virtual int getState () const
Gets the world state.
virtual void setState (int _state)
Sets a world state.
virtual bool isDead () const
Checks if world is dead.
virtual const char * getChan () const
Current channel string.
virtual bool setChan (const char *chanstr)
Sets the channel name.
virtual void setChanAndJoin (char *chanstr)
Sets and joins the channel.
virtual const char * getUrl () const
Gets the world url.
virtual void setUrl (const char *_url)
Sets the world url.
virtual void setGround (float level)
Sets the world level.
virtual float getGround () const
Gets the world level.
virtual bool isPersistent () const
virtual void setPersistent (bool persistent)
virtual bool isLinked () const
virtual void linked ()
virtual struct GuiItem * getGui () const
virtual bool isGui () const
virtual void resetGui ()
virtual uint32_t getGroupAdr () const
virtual uint32_t getSsrc () const
virtual void setGroupAdr (uint32_t _group)
virtual void setSsrc (uint32_t _ssrc)
virtual uint16_t number () const
virtual User * localUser () const
virtual Bgcolor * backgroundColor () const
void localGrid ()
Sets locals for the current world.
void initGrid ()
Inits the grid by default.
void initGrid (const uint8_t dim[3], const V3 &sl)
Inits the grid.
class OList **** allocGrid ()
Allocs memory for the grid.
void clearGrid ()
Clears the grid.
void freeGrid ()
Frees the grid.
Static Public Member Functions
static World * current ()
Return the current world.
static World * goBack ()
Go to the previous world and return it.
static World * goForward ()
Go to the next world and return it.
static World * swap (World *w)
Exchanges Worlds in the list.
static World * worldByUrl (const char *_url)
Gets world by url.
static World * worldByGroup (uint32_t group)
Gets world by group addr.
static World * worldBySsrc (uint32_t ssrc)
Gets world by ssrc RTP.
static World * enter (const char *_url, const char *_chanstr, bool _new_one)
New World initialization.
static void init (const char *urlvre)
General initialization of WO module.
static void httpReader (void *urlvre, class Http *http)
World reader.
static void deleteObjects ()
Deletes all objects dropped in the todeletelist.
static void initObjectsName ()
Initializes hashcode table of names.
static void initGeneralFuncList ()
Initializes table of general functions.
static void setManagerChanAndJoin (const char *chanstr)
Sets the manager channel name and joins it.
static const char * getManagerChan ()
Gets the channel name of the manager.
static void clearLists ()
Clears lists.
static void funcs ()
Inits functions.
Public Attributes
class OList **** grid
matrix grid pointer.
int namecnt
name counter.
V3 bbcenter
bb center of the world.
V3 bbsize
bb size of the world.
struct GuiItem * guip
gui handle.
class Clock * clock
internal clock.
class Vjc * vjc
vjc.
class Wind * wind
wind.
Static Public Attributes
static const uint8_t GRIDX = 4
static const uint8_t GRIDY = 4
static const uint8_t GRIDZ = 2
static const float DISTX = 2.
static const float DISTY = 2.
static const float DISTZ = 2.
static const uint8_t WORLD_LEN = 32
static class OList * gridList [4][4][2]
Protected Attributes
char * url
url of world description.
char * name
world name.
char * chan
channel string addr/port/ttl.
uint8_t state
current state.
uint32_t group
current group addr.
uint32_t ssrc
current ssrc id.
bool islinked
linked world or not.
bool persistent
persistent world or not.
uint16_t num
world number.
V3 bbmin
bb min of the world.
V3 bbmax
bb max of the world.
V3 slice
slice units of the grid.
float ground
ground level
uint8_t dimgrid [3]
grid dimensions.
class Universe * universe
universe pointer.
class User * plocaluser
local user pointer.
class Bgcolor * bgcolor
background color.
World * prev
prev world.
World * next
next world.
Private Types
enum { LOADING, LOADED, SIMULATION, STOPPED }
Private Member Functions
virtual void addToList ()
Adds world into world list.
virtual bool call (World *wprev)
Switches channels.
virtual void checkIcons ()
Checks whether Icon objects are locally presents.
virtual void checkPersistObjects ()
Checks whether objects are persistents.
Static Private Attributes
static class World * worldList = NULL
Detailed Description
World class.
Definition at line 33 of file world.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
LOADING
LOADED
SIMULATION
STOPPED
Definition at line 44 of file world.hpp.
anonymous enum
anonymous enum
Enumerator
OLD
NEW
Definition at line 132 of file world.hpp.
Constructor & Destructor Documentation
World()
World::World ()
Constructor.
Definition at line 88 of file world.cpp.
References Universe::current(), DBG_WO, new_world, newV3(), OList::next, and trace().
~World()
virtual World::~World () inline virtual
Definition at line 101 of file world.hpp.
Member Function Documentation
addToList()
void World::addToList () private virtual
Adds world into world list.
Definition at line 130 of file world.cpp.
References OList::next.
allocGrid()
OList **** World::allocGrid ()
Allocs memory for the grid.
Definition at line 630 of file world.cpp.
backgroundColor()
Bgcolor * World::backgroundColor () const virtual
Definition at line 292 of file world.cpp.
Referenced by Bgcolor::Bgcolor(), and Render::clearGLBuffer().
call()
bool World::call (World * wprev) private virtual
Switches channels.
deleteChannel -> enter() -> join()
Definition at line 491 of file world.cpp.
References chan, Channel::current(), DBG_IPMC, DBG_WO, g, Channel::getGroup(), GROUP_LEN, Global::gui, islinked, Channel::join(), trace(), and Gui::updateWorld().
Referenced by goBack(), and goForward().
checkIcons()
void World::checkIcons () private virtual
Checks whether Icon objects are locally presents.
Definition at line 686 of file world.cpp.
References File::closeFile(), Icon::CREATE, Env::cwd(), DBG_WO, dirent, doAction(), Global::env, error(), Cache::file2url(), g, ICON_TYPE, Env::icons(), isAction(), File::openFile(), trace(), and URL_LEN.
Referenced by enter(), and init().
checkPersistObjects()
void World::checkPersistObjects () private virtual
Checks whether objects are persistents.
Definition at line 732 of file world.cpp.
References BALL_NAME, BALL_TYPE, doAction(), MIRAGE_NAME, MIRAGE_TYPE, Ball::RECREATE, Mirage::RECREATE, Thing::RECREATE, stringcmp(), THING_NAME, and THING_TYPE.
Referenced by enter(), and init().
clearGrid()
void World::clearGrid ()
Clears the grid.
clear all pointers in the grid
Definition at line 646 of file world.cpp.
clearLists()
void World::clearLists () static
Clears lists.
Definition at line 1096 of file world.cpp.
References deleteList, invisibleList, lightList, mobileList, and stillList.
compute()
void World::compute (time_t sec, time_t usec) virtual
Destructor.
Computes the World (Simulation) : The Heart of Vreng called by gui/scene.cpp.
Processes the world.
Definition at line 368 of file world.cpp.
References Axis::axis(), OList::clearIspointedFlag(), COLLIDE_NEVER, DBG_WO, Pref::dbgtrace, error(), g, Grid::grid(), Axis::init(), Grid::init(), WObject::isValid(), localuser, MAX, MIN, mobileList, WObject::move, WObject::named(), notice(), OBJECTSNUMBER, Move::perm_sec, Move::perm_usec, Global::pref, stillList, trace(), WObject::typeName(), and User::userMovement().
Referenced by Scene::paintScene().
current()
World * World::current () static
Return the current world.
Definition at line 143 of file world.cpp.
Referenced by Widgets::addMarkCB(), Aoi::aoiEnter(), Bgcolor::Bgcolor(), Capture::captureXwd(), User::changePosition(), Render::clearGLBuffer(), Android::connectToBapServer(), Clip::contRtp(), Channel::create(), Session::createMySdes(), Fountain::defaults(), Particle::defaults(), Rain::defaults(), Snow::defaults(), Waterfall::defaults(), WObject::deleteFromGrid(), Gate::enter(), WObject::getObjectByName(), Widgets::getPointedObject(), WObject::getVicinityList(), Gui::gotoWorld(), Ground::Ground(), Widgets::homeCB(), WObject::imposedMovement(), initObjectsName(), Android::initReceiver(), Android::inits(), Cloud::inits(), Flag::inits(), WObject::insertIntoGrid(), Render::map(), Widgets::openSourceDialog(), Scene::paintScene(), Vrelet::parser(), Parse::parseVreLines(), Clip::pauseRtp(), WObject::permanentMovement(), Clip::play(), Global::quitVreng(), Session::refreshMySdes(), Gui::removeCart(), sandboxCB(), Widgets::saveCB(), Widgets::setAudioCB(), WObject::setObjectName(), Widgets::setVideoCB(), Widgets::setWhiteboardCB(), Clip::startRtp(), Session::stat(), Clip::stopRtp(), Capture::stopVideo(), WObject::updateGrid(), WObject::updateNames(), Board::wb_cb(), Wind::Wind(), Capture::writeJPGImage(), and Capture::writePNGImage().
deleteObjects()
void World::deleteObjects () static
Deletes all objects dropped in the todeletelist.
Definition at line 1080 of file world.cpp.
References COLLIDE_NEVER, deleteList, and mobileList.
enter()
World * World::enter (const char * _url, const char * _chanstr, bool _new_one) static
New World initialization.
Definition at line 974 of file world.cpp.
References Gui::addWorld(), bgcolor, checkIcons(), checkPersistObjects(), clock, DBG_FORCE, DBG_WO, Pref::dbgtrace, endprogression(), error(), g, Parse::getParse(), Global::gui, guip, Http::httpOpen(), User::inits(), localuser, name, Parse::parseVreLines(), Global::pref, sandbox_vre, setChan(), setName(), setState(), Universe::startWheel(), Universe::stopWheel(), trace(), universe, Gui::updateWorld(), url, URL_LEN, and warning().
Referenced by Gate::enter(), Gui::gotoWorld(), Widgets::homeCB(), and sandboxCB().
freeGrid()
void World::freeGrid ()
Frees the grid.
free all the grid (static)
Definition at line 659 of file world.cpp.
funcs()
void World::funcs () static
Inits functions.
Definition at line 1105 of file world.cpp.
getChan()
const char * World::getChan () const virtual
Current channel string.
Definition at line 282 of file world.cpp.
Referenced by Clip::contRtp(), init(), Clip::pauseRtp(), setWorld(), and Clip::stopRtp().
getGround()
float World::getGround () const virtual
Gets the world level.
Definition at line 324 of file world.cpp.
Referenced by User::changePosition(), Fountain::defaults(), Particle::defaults(), Rain::defaults(), Snow::defaults(), and Waterfall::defaults().
getGroupAdr()
uint32_t World::getGroupAdr () const virtual
Definition at line 339 of file world.cpp.
getGui()
struct GuiItem * World::getGui () const virtual
Definition at line 148 of file world.cpp.
Referenced by Widgets::removeWorld(), and Widgets::updateWorld().
getManagerChan()
const char * World::getManagerChan () static
Gets the channel name of the manager.
Definition at line 248 of file world.cpp.
References chan, and manager.
getName()
const char * World::getName () const virtual
Gets current world name.
Definition at line 184 of file world.cpp.
Referenced by Aoi::aoiEnter(), Capture::captureXwd(), Session::createMySdes(), Widgets::getPointedObject(), init(), Session::refreshMySdes(), Widgets::saveCB(), setWorld(), and WObject::updateNames().
getSsrc()
uint32_t World::getSsrc () const virtual
Definition at line 329 of file world.cpp.
Referenced by Channel::create().
getState()
int World::getState () const virtual
Gets the world state.
Definition at line 227 of file world.cpp.
getUrl()
const char * World::getUrl () const virtual
Gets the world url.
Definition at line 302 of file world.cpp.
Referenced by init(), Widgets::openSourceDialog(), Widgets::saveCB(), and setWorld().
goBack()
World * World::goBack () static
Go to the previous world and return it.
Definition at line 522 of file world.cpp.
References call(), DBG_WO, next, prev, quit(), and trace().
Referenced by Widgets::backCB().
goForward()
World * World::goForward () static
Go to the next world and return it.
Definition at line 550 of file world.cpp.
References call(), DBG_WO, next, prev, quit(), and trace().
Referenced by Widgets::forwardCB().
httpReader()
void World::httpReader (void * urlvre, class Http * http) static
World reader.
Definition at line 782 of file world.cpp.
References File::closeFile(), DBG_WO, error(), Http::httpRead(), Parse::numline, File::openFile(), Parse::parseVreLines(), Cache::setCacheName(), and trace().
init()
void World::init (const char * urlvre) static
General initialization of WO module.
Definition at line 830 of file world.cpp.
References Gui::addWorld(), bgcolor, User::bubble, Bubble::BUBBLEBACK, Global::channel, checkIcons(), checkPersistObjects(), Env::cleanCacheByExt(), clock, Universe::current(), DBG_INIT, DBG_WO, endprogression(), Global::env, g, getChan(), Channel::getGroup(), WObject::getInstance(), getName(), Channel::getPort(), getUrl(), Pref::gravity, Universe::group, Global::gui, guip, Http::httpOpen(), initGrid(), Pref::keep, Universe::localuser, Gui::pauseUser(), plocaluser, Universe::port, Global::pref, setChanAndJoin(), setName(), setState(), setUrl(), Universe::startWheel(), Universe::stopWheel(), trace(), and universe.
Referenced by Global::startCB().
initGeneralFuncList()
void World::initGeneralFuncList () static
Initializes table of general functions.
initialization array of functions pointers
Definition at line 210 of file initobj.cpp.
References ACTIONSNUMBER, DBG_WO, generalActionList, generalInitList, getPropertyFuncList, GeneralInitList::initfunc, MAXFLOAT, maxlastings, PropertyFuncList::method, GeneralActionList::method, GeneralActionList::name, OBJECTSNUMBER, propertiesnumber, PROPSNUMBER, putPropertyFuncList, and trace().
initGrid() [1/2]
void World::initGrid ()
Inits the grid by default.
Definition at line 600 of file world.cpp.
Referenced by init().
initGrid() [2/2]
void World::initGrid (const uint8_t dim[3], const V3 & sl)
Inits the grid.
Definition at line 616 of file world.cpp.
References V3::v.
initObjectsName()
void World::initObjectsName () static
Initializes hashcode table of names.
Definition at line 42 of file names.cpp.
References current(), hashtable, name, NAME_HASH_SIZE, namecnt, and OBJNAME_LEN.
isDead()
bool World::isDead () const virtual
Checks if world is dead.
Definition at line 237 of file world.cpp.
isGui()
bool World::isGui () const virtual
Definition at line 153 of file world.cpp.
Referenced by Gui::removeWorld(), Gui::updateWorld(), and Widgets::updateWorld().
isLinked()
bool World::isLinked () const virtual
Definition at line 349 of file world.cpp.
isPersistent()
bool World::isPersistent () const virtual
Definition at line 359 of file world.cpp.
linked()
void World::linked () virtual
Definition at line 354 of file world.cpp.
Referenced by Gate::enter().
localGrid()
void World::localGrid ()
Sets locals for the current world.
Definition at line 391 of file col.cpp.
References dim, dimgrid, dist, newV3(), slice, and V3::v.
localUser()
User * World::localUser () const virtual
Definition at line 287 of file world.cpp.
References localuser.
number()
uint16_t World::number () const virtual
Definition at line 314 of file world.cpp.
quit()
void World::quit () virtual
Quits current world.
Definition at line 903 of file world.cpp.
References DBG_WO, NetObject::declareDeletion(), NetObject::deleteFromList(), error(), g, Parse::getParse(), Global::gui, invisibleList, localuser, mobileList, WObject::noh, App::quitTools(), WObject::resetObjectsNumber(), User::resetPosition(), Gui::showNavigator(), sigctx, stillList, trace(), and Gui::updateWorld().
Referenced by Gate::enter(), goBack(), goForward(), Gui::gotoWorld(), Widgets::homeCB(), Global::quitVreng(), and sandboxCB().
resetGui()
void World::resetGui () virtual
Definition at line 158 of file world.cpp.
Referenced by Widgets::removeWorld().
setChan()
bool World::setChan (const char * chanstr) virtual
Sets the channel name.
Definition at line 254 of file world.cpp.
References CHAN_LEN, and error().
Referenced by enter().
setChanAndJoin()
void World::setChanAndJoin (char * chanstr) virtual
Sets and joins the channel.
Definition at line 276 of file world.cpp.
References Channel::join().
Referenced by Gui::gotoWorld(), Widgets::homeCB(), and init().
setGround()
void World::setGround (float level) virtual
Sets the world level.
Definition at line 319 of file world.cpp.
Referenced by Ground::Ground().
setGroupAdr()
void World::setGroupAdr (uint32_t _group) virtual
Definition at line 344 of file world.cpp.
Referenced by Channel::create().
setManagerChanAndJoin()
void World::setManagerChanAndJoin (const char * chanstr) static
Sets the manager channel name and joins it.
Definition at line 242 of file world.cpp.
References chan, Channel::joinManager(), and manager.
Referenced by Universe::init().
setName()
void World::setName (const char * name) virtual
Builds world name from url.
Definition at line 164 of file world.cpp.
References DBG_WO, end, and trace().
Referenced by enter(), Universe::init(), and init().
setPersistent()
void World::setPersistent (bool persistent) virtual
Definition at line 297 of file world.cpp.
Referenced by Parse::parseVreLines().
setSsrc()
void World::setSsrc (uint32_t _ssrc) virtual
Definition at line 334 of file world.cpp.
Referenced by Channel::create().
setState()
void World::setState (int _state) virtual
Sets a world state.
Definition at line 232 of file world.cpp.
Referenced by enter(), and init().
setUrl()
void World::setUrl (const char * _url) virtual
Sets the world url.
Definition at line 307 of file world.cpp.
Referenced by init().
swap()
World * World::swap (World * w) static
Exchanges Worlds in the list.
Definition at line 576 of file world.cpp.
References DBG_WO, next, prev, and trace().
worldByGroup()
World * World::worldByGroup (uint32_t group) static
Gets world by group addr.
Definition at line 209 of file world.cpp.
References next.
Referenced by Channel::create().
worldBySsrc()
World * World::worldBySsrc (uint32_t ssrc) static
Gets world by ssrc RTP.
Definition at line 218 of file world.cpp.
References next.
worldByUrl()
World * World::worldByUrl (const char * _url) static
Gets world by url.
Definition at line 190 of file world.cpp.
References Url::abs(), next, and URL_LEN.
Member Data Documentation
bbcenter
V3 World::bbcenter
bb center of the world.
Definition at line 90 of file world.hpp.
bbmax
V3 World::bbmax protected
bb max of the world.
Definition at line 62 of file world.hpp.
bbmin
V3 World::bbmin protected
bb min of the world.
Definition at line 61 of file world.hpp.
bbsize
V3 World::bbsize
bb size of the world.
Definition at line 91 of file world.hpp.
Referenced by Render::map().
bgcolor
class Bgcolor* World::bgcolor protected
background color.
Definition at line 68 of file world.hpp.
Referenced by enter(), and init().
chan
char* World::chan protected
channel string addr/port/ttl.
Definition at line 54 of file world.hpp.
Referenced by call(), getManagerChan(), and setManagerChanAndJoin().
clock
class Clock* World::clock
internal clock.
Definition at line 94 of file world.hpp.
Referenced by enter(), and init().
dimgrid
uint8_t World::dimgrid[3] protected
grid dimensions.
Definition at line 65 of file world.hpp.
Referenced by localGrid().
DISTX
const float World::DISTX = 2. static
Definition at line 76 of file world.hpp.
DISTY
const float World::DISTY = 2. static
Definition at line 77 of file world.hpp.
DISTZ
const float World::DISTZ = 2. static
Definition at line 78 of file world.hpp.
grid
class OList**** World::grid
matrix grid pointer.
Definition at line 86 of file world.hpp.
Referenced by WObject::deleteFromGrid(), WObject::insertIntoGrid(), and WObject::updateGrid().
gridList
class OList * World::gridList static
Definition at line 85 of file world.hpp.
Referenced by WObject::deleteFromGrid(), WObject::getVicinityList(), WObject::insertIntoGrid(), and WObject::updateGrid().
GRIDX
const uint8_t World::GRIDX = 4 static
Definition at line 73 of file world.hpp.
GRIDY
const uint8_t World::GRIDY = 4 static
Definition at line 74 of file world.hpp.
GRIDZ
const uint8_t World::GRIDZ = 2 static
Definition at line 75 of file world.hpp.
ground
float World::ground protected
ground level
Definition at line 64 of file world.hpp.
group
uint32_t World::group protected
current group addr.
Definition at line 56 of file world.hpp.
guip
struct GuiItem* World::guip
gui handle.
Definition at line 93 of file world.hpp.
Referenced by enter(), and init().
islinked
bool World::islinked protected
linked world or not.
Definition at line 58 of file world.hpp.
Referenced by call().
name
char* World::name protected
world name.
Definition at line 53 of file world.hpp.
Referenced by enter(), and initObjectsName().
namecnt
int World::namecnt
name counter.
Definition at line 89 of file world.hpp.
Referenced by initObjectsName(), and WObject::setObjectName().
next
World* World::next protected
next world.
Definition at line 70 of file world.hpp.
Referenced by goBack(), goForward(), swap(), worldByGroup(), worldBySsrc(), and worldByUrl().
num
uint16_t World::num protected
world number.
Definition at line 60 of file world.hpp.
persistent
bool World::persistent protected
persistent world or not.
Definition at line 59 of file world.hpp.
plocaluser
class User* World::plocaluser protected
local user pointer.
Definition at line 67 of file world.hpp.
Referenced by init().
prev
World* World::prev protected
prev world.
Definition at line 69 of file world.hpp.
Referenced by goBack(), goForward(), and swap().
slice
V3 World::slice protected
slice units of the grid.
Definition at line 63 of file world.hpp.
Referenced by localGrid().
ssrc
uint32_t World::ssrc protected
current ssrc id.
Definition at line 57 of file world.hpp.
state
uint8_t World::state protected
current state.
Definition at line 55 of file world.hpp.
universe
class Universe* World::universe protected
universe pointer.
Definition at line 66 of file world.hpp.
Referenced by enter(), and init().
url
char* World::url protected
url of world description.
Definition at line 52 of file world.hpp.
Referenced by enter().
vjc
class Vjc* World::vjc
vjc.
Definition at line 95 of file world.hpp.
wind
class Wind* World::wind
wind.
Definition at line 96 of file world.hpp.
Referenced by Cloud::inits(), Flag::inits(), and Wind::Wind().
WORLD_LEN
const uint8_t World::WORLD_LEN = 32 static
Definition at line 79 of file world.hpp.
Referenced by Capture::stopVideo(), Capture::writeJPGImage(), and Capture::writePNGImage().
worldList
World * World::worldList = NULL static private
Definition at line 40 of file world.hpp.
The documentation for this class was generated from the following files:
src/vreng/world.hpp
src/vreng/world.cpp
src/wo/col.cpp
src/wo/initobj.cpp
src/wo/names.cpp