VREng: Matrix3 Class Reference
Matrix3 Class Reference
Matrix3 class.
#include <vector3.hpp>
Public Member Functions
Matrix3 ()
void fromAngle (float ax, float ay, float az)
constructor.
void apply (const Vector3 &v, Vector3 *out)
void rapply (Vector3 const &v, Vector3 *out)
void apply (Vector3 *v)
void rapply (Vector3 *v)
Public Attributes
Vector3 vx
Vector3 vy
Vector3 vz
Detailed Description
Matrix3 class.
Definition at line 331 of file vector3.hpp.
Constructor & Destructor Documentation
Matrix3()
Matrix3::Matrix3 () inline
Definition at line 335 of file vector3.hpp.
Member Function Documentation
apply() [1/2]
void Matrix3::apply (const Vector3 & v, Vector3 * out) inline
Definition at line 348 of file vector3.hpp.
References vx, vy, vz, Vector3::x, Vector3::y, and Vector3::z.
Referenced by apply(), Smoke::changePermanent(), and Fire::changePermanent().
apply() [2/2]
void Matrix3::apply (Vector3 * v) inline
Definition at line 360 of file vector3.hpp.
References apply().
fromAngle()
void Matrix3::fromAngle (float ax, float ay, float az) inline
constructor.
Definition at line 337 of file vector3.hpp.
References vx, vy, vz, Vector3::x, Vector3::y, and Vector3::z.
rapply() [1/2]
void Matrix3::rapply (Vector3 * v) inline
Definition at line 365 of file vector3.hpp.
References rapply().
rapply() [2/2]
void Matrix3::rapply (Vector3 const & v, Vector3 * out) inline
Definition at line 354 of file vector3.hpp.
References vx, vy, vz, Vector3::x, Vector3::y, and Vector3::z.
Referenced by rapply().
Member Data Documentation
vx
Vector3 Matrix3::vx
Definition at line 333 of file vector3.hpp.
Referenced by apply(), fromAngle(), and rapply().
vy
Vector3 Matrix3::vy
Definition at line 333 of file vector3.hpp.
Referenced by apply(), fromAngle(), and rapply().
vz
Vector3 Matrix3::vz
Definition at line 333 of file vector3.hpp.
Referenced by apply(), fromAngle(), and rapply().
The documentation for this class was generated from the following file:
src/vreng/vector3.hpp