VREng: Panels Class Reference
Panels Class Reference
Panels class.
#include <panels.hpp>
Public Member Functions
Panels (class Widgets *, class Scene &)
void showManipulator (bool state)
void showCartDialog (bool state)
Static Public Attributes
static int RIGHT_PANEL_WIDTH
static int CONTROL_PANEL_HEIGHT
static int LIST_PALETTE_WIDTH
static int LIST_PALETTE_HEIGHT
static int MESSAGE_PALETTE_WIDTH
static int MESSAGE_PALETTE_HEIGHT
Private Attributes
Widgets & gw
class Joystick * joystick
class Pitch * pitch
UBox & manipulator
UBox right_panel
UBox control_panel
UBox main_panel
UBar control_bar
Friends
class Widgets
Detailed Description
Panels class.
Definition at line 27 of file panels.hpp.
Constructor & Destructor Documentation
Panels()
Panels::Panels (class Widgets * _gw, class Scene & scene)
Definition at line 90 of file panels.cpp.
References Theme::AddObj, Widgets::addobj_dialog, Widgets::avatars, Theme::Axis, Theme::BigEye, Widgets::callAction(), Theme::Camera, Widgets::capture, Theme::Cart, Widgets::carts, control_bar, control_panel, Theme::controlPanelHeight, Theme::Counter, Messages::createMessagePanel(), Theme::Exit, Theme::Eyes, Theme::Folder, g, Theme::Grid2D, Theme::Grid3D, gw, joystick, Theme::Jumelles, main_panel, manipulator, Theme::messagePaletteWidth, Widgets::messages, Theme::Movie, Theme::paletteHeight, Theme::paletteStyle, Theme::paletteWidth, Theme::panelStyle, Theme::Person, pitch, right_panel, sandboxCB(), Theme::scrollpaneStyle, Palette::setPos(), Palette::setTitle(), Capture::startVideo(), Capture::stopVideo(), Global::theme, toggleAxisCB(), toggleGridCB(), toggleHudCB(), UserAction::UA_BULLET, UserAction::UA_DART, UserAction::UA_FIRSTVIEW, UserAction::UA_MAPVIEW, UserAction::UA_SWITCHVIEW, UserAction::UA_THIRDVIEWFAR, Theme::World, Widgets::worlds, Capture::writeJPGImage(), and Capture::writePNGImage().
Member Function Documentation
showCartDialog()
void Panels::showCartDialog (bool state)
Definition at line 71 of file panels.cpp.
Referenced by Gui::showCartDialog().
showManipulator()
void Panels::showManipulator (bool state)
Definition at line 64 of file panels.cpp.
References joystick, manipulator, and pitch.
Referenced by Gui::showManipulator(), and Gui::showNavigator().
Friends And Related Function Documentation
Widgets
friend class Widgets friend
Definition at line 42 of file panels.hpp.
Member Data Documentation
control_bar
UBar Panels::control_bar private
Definition at line 48 of file panels.hpp.
Referenced by Panels().
control_panel
UBox Panels::control_panel private
Definition at line 47 of file panels.hpp.
Referenced by Panels().
CONTROL_PANEL_HEIGHT
int Panels::CONTROL_PANEL_HEIGHT static
Definition at line 31 of file panels.hpp.
gw
Widgets& Panels::gw private
Definition at line 43 of file panels.hpp.
Referenced by Panels().
joystick
class Joystick* Panels::joystick private
Definition at line 44 of file panels.hpp.
Referenced by Panels(), and showManipulator().
LIST_PALETTE_HEIGHT
int Panels::LIST_PALETTE_HEIGHT static
Definition at line 33 of file panels.hpp.
LIST_PALETTE_WIDTH
int Panels::LIST_PALETTE_WIDTH static
Definition at line 32 of file panels.hpp.
main_panel
UBox Panels::main_panel private
Definition at line 47 of file panels.hpp.
Referenced by Panels(), and Widgets::Widgets().
manipulator
UBox& Panels::manipulator private
Definition at line 46 of file panels.hpp.
Referenced by Panels(), and showManipulator().
MESSAGE_PALETTE_HEIGHT
int Panels::MESSAGE_PALETTE_HEIGHT static
Definition at line 35 of file panels.hpp.
MESSAGE_PALETTE_WIDTH
int Panels::MESSAGE_PALETTE_WIDTH static
Definition at line 34 of file panels.hpp.
pitch
class Pitch* Panels::pitch private
Definition at line 45 of file panels.hpp.
Referenced by Panels(), and showManipulator().
right_panel
UBox Panels::right_panel private
Definition at line 47 of file panels.hpp.
Referenced by Panels(), and Widgets::Widgets().
RIGHT_PANEL_WIDTH
int Panels::RIGHT_PANEL_WIDTH static
Definition at line 30 of file panels.hpp.
The documentation for this class was generated from the following files:
src/gui/panels.hpp
src/gui/panels.cpp