VREng: Gui Class Reference
Gui Class Reference
Gui Class.
#include <gui.hpp>
Classes
struct ChannelSources
Public Member Functions
Gui ()
void createWidgets ()
void showWidgets (bool=true)
class Scene * getScene ()
returns a pointer to the scene.
int getCycles ()
returns the current number of frames.
void gotoWorld (const UStr &url_or_name)
go to this world.
void showNavigator ()
void showManipulator ()
void clearInfoBar (class WObject *)
void writeMessage (const char *mode, const char *from, const char *mess)
writes a message.
void addChannelSources (int canal, int table[], int table_size)
void removeChannelSources (int canal)
NB: canal=0 for tab_fd / canal=1 for tab_manager_fd.
GuiItem * addUser (class User *)
void updateUser (class User *)
void removeUser (class User *)
void pauseUser ()
GuiItem * addWorld (class World *world, bool isCurrent)
void updateWorld (class World *world, bool isCurrent)
void removeWorld (class World *world)
void showCartDialog (bool flag)
GuiItem * addCart (class WObject *po)
void removeCart (class WObject *po, int target)
void updateCart (class WObject *)
Updates the infoBar when a cart item is selected.
void launchVncConnect (class Vnc *)
Lauches vnc dialog.
void setToVnc (class Vnc *)
Redirects events to vnc object.
void setToVrelet (class Vrelet *)
Redirects events to vrelet object.
void setToCarrier (class Carrier *)
Redirects events to carrier object.
void setToBoard (class Board *)
Redirects events to board object.
void initClicked ()
void getClicked (int *click, float clicked[])
WObject * getSelectedObject ()
Private Attributes
std::vector< ChannelSources * > channel_sources
table of network events
class Widgets * widgets
the widgets of the GUI
class WObject * selected_object
the solid that is currently selected
class Vnc * vnc
vnc pointer
class Carrier * carrier
carrier pointer
class Vrelet * vrelet
vrelet pointer
class Board * board
board pointer
Friends
class Widgets
class Scene
class Navig
class Panel
Detailed Description
Gui Class.
Definition at line 41 of file gui.hpp.
Constructor & Destructor Documentation
Gui()
Gui::Gui ()
Definition at line 53 of file gui.cpp.
Member Function Documentation
addCart()
GuiItem * Gui::addCart (class WObject * po)
Definition at line 139 of file gui.cpp.
References Widgets::carts, error(), WObject::getInstance(), NN, notice(), Widgets::setInfobar(), updateCart(), and widgets.
Referenced by Cart::addToCart().
addChannelSources()
void Gui::addChannelSources (int canal, int table[], int table_size)
Definition at line 106 of file gui.cpp.
References channel, channel_sources, and NetIncoming().
Referenced by Channel::join(), and Channel::joinManager().
addUser()
GuiItem * Gui::addUser (class User * user)
Definition at line 191 of file gui.cpp.
References Widgets::addUser(), error(), WObject::getInstance(), NN, notice(), widgets, and WObject::worldName().
Referenced by User::addGui().
addWorld()
GuiItem * Gui::addWorld (class World * world, bool isCurrent)
Definition at line 255 of file gui.cpp.
References Widgets::addWorld(), and widgets.
Referenced by World::enter(), and World::init().
clearInfoBar()
void Gui::clearInfoBar (class WObject * obj)
Definition at line 320 of file gui.cpp.
References Widgets::navig, obj, selected_object, Navig::selectObject(), and widgets.
Referenced by WObject::clearObjectBar().
createWidgets()
void Gui::createWidgets ()
Definition at line 61 of file gui.cpp.
References DBG_INIT, trace(), Widgets, and widgets.
Referenced by Global::start().
getClicked()
void Gui::getClicked (int * click, float clicked[])
Definition at line 94 of file gui.cpp.
References Messages::getClicked(), Widgets::messages, and widgets.
getCycles()
int Gui::getCycles ()
returns the current number of frames.
Definition at line 77 of file gui.cpp.
References Scene::cycles, Widgets::scene, and widgets.
Referenced by Times::checkRate(), Times::getRate(), and statTimings().
getScene()
Scene * Gui::getScene ()
returns a pointer to the scene.
Definition at line 72 of file gui.cpp.
References Widgets::scene, and widgets.
Referenced by Render::clearGLBuffer(), Render::clickDirection(), Grid::draw(), Render::getVisiblePosition(), Render::map(), Render::satellite(), Solid::setRay(), and toggleHudCB().
getSelectedObject()
WObject * Gui::getSelectedObject ()
Definition at line 304 of file gui.cpp.
References selected_object.
Referenced by Navig::mousePressB1orB3(), and objectActionCB().
gotoWorld()
void Gui::gotoWorld (const UStr & url_or_name)
go to this world.
Definition at line 226 of file gui.cpp.
References audioactive, CHAN_LEN, Cache::check(), Channel::current(), Vac::current(), World::current(), DEF_VRE_CHANNEL, World::enter(), Vac::getUrlAndChannel(), notice(), World::quit(), Vac::resolveWorldUrl(), World::setChanAndJoin(), Audio::start(), URL_LEN, and vac.
Referenced by Widgets::createFileMenu(), Widgets::createMarkMenu(), destinationsHttpReader(), Widgets::openMessage(), and universeHttpReader().
initClicked()
void Gui::initClicked ()
Definition at line 88 of file gui.cpp.
References Messages::initClicked(), Widgets::messages, and widgets.
launchVncConnect()
void Gui::launchVncConnect (class Vnc * _vnc)
Lauches vnc dialog.
Definition at line 281 of file gui.cpp.
References VncDialog::create(), and widgets.
Referenced by Vnc::reconnectServer().
pauseUser()
void Gui::pauseUser ()
Definition at line 218 of file gui.cpp.
References Widgets::callAction(), UserAction::UA_PAUSE, and widgets.
Referenced by World::init().
removeCart()
void Gui::removeCart (class WObject * po, int target)
Definition at line 152 of file gui.cpp.
References User::cart, Widgets::carts, World::current(), error(), WObject::getGui(), WObject::getInstance(), WObject::isGui(), Cart::LEAVE, Cart::leaveIntoWorld(), localuser, NN, notice(), Cart::REMOVE, Cart::removeFromCart(), WObject::resetGui(), Widgets::setInfobar(), and widgets.
Referenced by updateCart().
removeChannelSources()
void Gui::removeChannelSources (int canal)
NB: canal=0 for tab_fd / canal=1 for tab_manager_fd.
Definition at line 119 of file gui.cpp.
References channel, and channel_sources.
Referenced by Channel::~Channel().
removeUser()
void Gui::removeUser (class User * user)
Definition at line 198 of file gui.cpp.
References error(), WObject::getGui(), WObject::getInstance(), WObject::isGui(), NN, notice(), Widgets::removeUser(), WObject::resetGui(), widgets, and WObject::worldName().
Referenced by Aoi::aoiQuit(), WObject::deleteReplica(), and User::~User().
removeWorld()
void Gui::removeWorld (class World * world)
Definition at line 261 of file gui.cpp.
References World::isGui(), Widgets::removeWorld(), and widgets.
setToBoard()
void Gui::setToBoard (class Board * _board)
Redirects events to board object.
Definition at line 291 of file gui.cpp.
References board.
Referenced by Board::defaults(), and Board::leave().
setToCarrier()
void Gui::setToCarrier (class Carrier * _carrier)
Redirects events to carrier object.
Definition at line 296 of file gui.cpp.
References carrier, motion, Motion::pointer(), and Motion::setToCarrier().
Referenced by Carrier::Carrier().
setToVnc()
void Gui::setToVnc (class Vnc * _vnc)
Redirects events to vnc object.
Definition at line 276 of file gui.cpp.
References vnc.
Referenced by Vnc::disconnectServer(), Vnc::leaveFocus(), and Vnc::takeFocus().
setToVrelet()
void Gui::setToVrelet (class Vrelet * _vrelet)
Redirects events to vrelet object.
Definition at line 286 of file gui.cpp.
References vrelet.
Referenced by Vrelet::quit(), and Vrelet::Vrelet().
showCartDialog()
void Gui::showCartDialog (bool flag)
Definition at line 134 of file gui.cpp.
References Widgets::panels, Panels::showCartDialog(), and widgets.
Referenced by Cart::addToCart(), Cart::leaveIntoWorld(), and Cart::removeFromCart().
showManipulator()
void Gui::showManipulator ()
Definition at line 314 of file gui.cpp.
References Widgets::panels, Panels::showManipulator(), and widgets.
Referenced by Carrier::take().
showNavigator()
void Gui::showNavigator ()
Definition at line 309 of file gui.cpp.
References Widgets::panels, Panels::showManipulator(), and widgets.
Referenced by Carrier::leave(), and World::quit().
showWidgets()
void Gui::showWidgets (bool state = true)
Definition at line 67 of file gui.cpp.
References widgets.
Referenced by Global::start().
updateCart()
void Gui::updateCart (class WObject * po)
Updates the infoBar when a cart item is selected.
Definition at line 175 of file gui.cpp.
References g, WObject::getInstance(), Cart::LEAVE, WObject::names, Theme::objectNameStyle, Theme::objectTypeStyle, Cart::REMOVE, removeCart(), Widgets::setInfobar(), Global::theme, Names::type, and widgets.
Referenced by addCart().
updateUser()
void Gui::updateUser (class User * user)
Definition at line 211 of file gui.cpp.
References error(), WObject::getGui(), WObject::getInstance(), WObject::isGui(), NN, notice(), Widgets::updateUser(), widgets, and WObject::worldName().
Referenced by Aoi::aoiEnter().
updateWorld()
void Gui::updateWorld (class World * world, bool isCurrent)
Definition at line 267 of file gui.cpp.
References World::isGui(), Widgets::updateWorld(), and widgets.
Referenced by World::call(), World::enter(), and World::quit().
writeMessage()
void Gui::writeMessage (const char * mode, const char * from, const char * mess)
writes a message.
Definition at line 82 of file gui.cpp.
References Widgets::messages, widgets, and Messages::writeMessage().
Referenced by User::get_msg(), notice(), Messages::performRequest(), and warning().
Friends And Related Function Documentation
Navig
friend class Navig friend
Definition at line 101 of file gui.hpp.
Panel
friend class Panel friend
Definition at line 102 of file gui.hpp.
Scene
friend class Scene friend
Definition at line 100 of file gui.hpp.
Widgets
friend class Widgets friend
Definition at line 99 of file gui.hpp.
Referenced by createWidgets().
Member Data Documentation
board
class Board* Gui::board private
board pointer
Definition at line 112 of file gui.hpp.
Referenced by Navig::mousePressB1orB3(), Navig::mousePressCB(), and setToBoard().
carrier
class Carrier* Gui::carrier private
carrier pointer
Definition at line 110 of file gui.hpp.
Referenced by Navig::mousePressCB(), and setToCarrier().
channel_sources
std::vector<ChannelSources*> Gui::channel_sources private
table of network events
Definition at line 105 of file gui.hpp.
Referenced by addChannelSources(), and removeChannelSources().
selected_object
class WObject* Gui::selected_object private
the solid that is currently selected
Definition at line 108 of file gui.hpp.
Referenced by clearInfoBar(), getSelectedObject(), Navig::mouseDragCB(), Navig::mouseMoveCB(), Navig::mousePressB1orB3(), Navig::mousePressB2(), Navig::mouseReleaseCB(), and Scene::updateHud().
vnc
class Vnc* Gui::vnc private
vnc pointer
Definition at line 109 of file gui.hpp.
Referenced by Navig::keyPressCB(), Navig::keyReleaseCB(), Navig::mouseMoveCB(), Navig::mousePressCB(), Navig::mouseReleaseCB(), and setToVnc().
vrelet
class Vrelet* Gui::vrelet private
vrelet pointer
Definition at line 111 of file gui.hpp.
Referenced by Navig::mousePressB1orB3(), and setToVrelet().
widgets
class Widgets* Gui::widgets private
the widgets of the GUI
Definition at line 107 of file gui.hpp.
Referenced by addCart(), addUser(), addWorld(), clearInfoBar(), createWidgets(), getClicked(), getCycles(), getScene(), initClicked(), launchVncConnect(), pauseUser(), removeCart(), removeUser(), removeWorld(), showCartDialog(), showManipulator(), showNavigator(), showWidgets(), updateCart(), updateUser(), updateWorld(), and writeMessage().
The documentation for this class was generated from the following files:
src/gui/gui.hpp
src/gui/gui.cpp