VREng: VncDialog Class Reference
VncDialog Class Reference
VncDialog class.
#include <widgets.hpp>
Static Public Member Functions
static void create (Widgets *, class Vnc *)
Private Member Functions
VncDialog (class Widgets *, class Vnc *)
virtual void convert ()
Private Attributes
class Vnc * vnc
vnc pointer.
UStr vnc_server
vnc server string.
UStr vnc_port
vnc port string.
UStr vnc_passwd
vnc passwd string.
Static Private Attributes
static VncDialog * vnc_dialog = null
Detailed Description
VncDialog class.
Definition at line 197 of file widgets.hpp.
Constructor & Destructor Documentation
VncDialog()
VncDialog::VncDialog (class Widgets * _gw, class Vnc * _vnc) private
Definition at line 1492 of file widgets.cpp.
References convert(), vnc_dialog, vnc_passwd, vnc_port, and vnc_server.
Referenced by create().
Member Function Documentation
convert()
void VncDialog::convert () private virtual
Definition at line 1509 of file widgets.cpp.
References Vnc::convert(), vnc, vnc_passwd, vnc_port, and vnc_server.
Referenced by VncDialog().
create()
void VncDialog::create (Widgets * gw, class Vnc * vnc) static
Definition at line 1481 of file widgets.cpp.
References vnc, vnc_dialog, and VncDialog().
Referenced by Gui::launchVncConnect().
Member Data Documentation
vnc
class Vnc* VncDialog::vnc private
vnc pointer.
Definition at line 203 of file widgets.hpp.
Referenced by convert(), and create().
vnc_dialog
VncDialog * VncDialog::vnc_dialog = null static private
Definition at line 202 of file widgets.hpp.
Referenced by create(), and VncDialog().
vnc_passwd
UStr VncDialog::vnc_passwd private
vnc passwd string.
Definition at line 207 of file widgets.hpp.
Referenced by convert(), and VncDialog().
vnc_port
UStr VncDialog::vnc_port private
vnc port string.
Definition at line 206 of file widgets.hpp.
Referenced by convert(), and VncDialog().
vnc_server
UStr VncDialog::vnc_server private
vnc server string.
Definition at line 205 of file widgets.hpp.
Referenced by convert(), and VncDialog().
The documentation for this class was generated from the following files:
src/gui/widgets.hpp
src/gui/widgets.cpp