VREng: Widgets Class Reference
Widgets Class Reference
Widgets class.
#include <widgets.hpp>
Public Member Functions
Widgets (Gui *)
constructor.
Navig * getNavig ()
void alertDialog (const char *message)
opens alert box if arg is not null, closes it if arg is null.
void setInfobar (UBox *content)
GuiItem * addUser (User *)
Adds an avatar name.
void updateUser (GuiItem *, User *)
Updates an avatar.
void removeUser (GuiItem *)
Removes an avatar name.
GuiItem * addWorld (World *, bool isCurrentWorld)
Adds a world name.
void updateWorld (World *, bool isCurrentWorld)
Updates a world name.
void removeWorld (World *)
Removes a world name.
class WObject * getPointedObject (int x, int y, ObjInfo *obji, int depthsel)
returns info about the pointed object but do NOT select it
void processKey (long keysym, int keychar, bool is_pressed)
Use this callback function for handling AUTOREPEAT Key event Autorepeat is logically suppressed by annulating corresponding Press and Release events.
void flushPostponedKRs ()
bool pendingPostponedKRs ()
Static Public Member Functions
static void showInfoDialog (const char *title, const char *message)
static void callAction (int numaction)
static void setKey (int key, int is_pressed)
Static Public Attributes
static const int MESSAGES_BOX_WIDTH = 320
static const int MESSAGES_BOX_HEIGHT = 150
static const int GW_DEFAULT_SCROLL = 50
static const int GW_ZOOM_SCROLL = 35
Private Member Functions
void openSourceDialog ()
Dialog box for vre source.
void destinationsDialog ()
Dialog box for worlds list.
void openWorldsDialog ()
Dialog box for worlds list.
UDialog & createPrefsDialog ()
Displays preferences.
UDialog & createSettingsDialog ()
UDialog & createGridDialog ()
UDialog & createToolDialog ()
UDialog & createAddobjDialog ()
UMenu & createFileMenu ()
UMenu & createMarkMenu ()
void addDynamicMenus (UMenubar &, const char *filename)
UBox & createInfobar ()
UBox & createMenubar ()
void openMessage (UMessageEvent &)
void putMessage (UMessageEvent &)
void getMessage (UMessageEvent &)
void moveMessage (UMessageEvent &)
void backCB ()
void forwardCB ()
void homeCB ()
void saveCB ()
void helpCB ()
void setPrefCB (int tool)
void setAudioCB (bool on)
void setVideoCB (bool on)
void setWhiteboardCB (bool on)
void setModelerCB (bool on)
void addMarkCB ()
void addNewObjectCB ()
void setRayDirection (int x, int y)
Private Attributes
Gui & gui
reference to the GUI object
class PutInfo & putinfo
class Capture & capture
UBox infos
UElem worlds
UElem carts
UElem avatars
class Scene & scene
OpenGL Drawing Zone.
class Navig & navig
navigation
UOptionDialog & source_dialog
UOptionDialog & worlds_dialog
UDialog & prefs_dialog
UDialog & settings_dialog
UDialog & grid_dialog
UDialog & tool_dialog
UDialog & addobj_dialog
class Messages & messages
class Panels & panels
UBox & infobar
UBox & menubar
long postponedKRmask
mask of all postponed Key Release events
long postponedKRcount
count in the KRbuf
KRKey postponedKRbuf [KRKey::KRBUF_MAX]
kbd bufs
Friends
class Gui
class Scene
class Navig
class Panels
Detailed Description
Widgets class.
Definition at line 77 of file widgets.hpp.
Constructor & Destructor Documentation
Widgets()
Widgets::Widgets (Gui * _gui)
constructor.
Definition at line 99 of file widgets.cpp.
References avatars, backCB(), carts, forwardCB(), g, getMessage(), homeCB(), infobar, Panels::main_panel, Theme::mainStyle, menubar, moveMessage(), openMessage(), panels, putMessage(), Panels::right_panel, scene, Global::theme, and worlds.
Member Function Documentation
addDynamicMenus()
void Widgets::addDynamicMenus (UMenubar & menu_bar, const char * filename) private
Definition at line 226 of file widgets.cpp.
References File::closeFile(), functionMenu(), g, Theme::menuStyle, File::openFile(), and Global::theme.
Referenced by createMenubar().
addMarkCB()
void Widgets::addMarkCB () private
Definition at line 475 of file widgets.cpp.
References CHAN_LEN, File::closeFile(), createMarkMenu(), World::current(), Global::env, g, File::openFile(), URL_LEN, and Env::worldmarks().
Referenced by createMarkMenu().
addNewObjectCB()
void Widgets::addNewObjectCB () private
Definition at line 1148 of file widgets.cpp.
References alpha, BALL, chair_wood, color, GROUND, localuser, MIRAGE, MODEL, obj, resetForm(), shape, size, STEP, table_glass, table_metal, table_wood, texture, THING, V3::v, and WALL.
Referenced by createAddobjDialog().
addUser()
GuiItem * Widgets::addUser (User * user)
Adds an avatar name.
Definition at line 311 of file widgets.cpp.
References avatars, and setUser().
Referenced by Gui::addUser().
addWorld()
GuiItem * Widgets::addWorld (World * world, bool isCurrentWorld)
Adds a world name.
Definition at line 346 of file widgets.cpp.
References setWorld(), and worlds.
Referenced by Gui::addWorld().
alertDialog()
void Widgets::alertDialog (const char * message)
opens alert box if arg is not null, closes it if arg is null.
backCB()
void Widgets::backCB () private
Definition at line 392 of file widgets.cpp.
References World::goBack().
Referenced by createInfobar(), createMenubar(), and Widgets().
callAction()
void Widgets::callAction (int numaction) static
Definition at line 505 of file widgets.cpp.
References gettimeofday(), localuser, and User::specialAction().
Referenced by convertKey(), Joystick::Joystick(), Panels::Panels(), and Gui::pauseUser().
createAddobjDialog()
UDialog & Widgets::createAddobjDialog () private
Definition at line 1236 of file widgets.cpp.
References addNewObjectCB(), BALL, BIG, BLACK, BLUE, BRICK, CAR, CHAIR_WOOD, CHECK, CLOUD, CONE, CUBE, CYAN, CYLINDER, DISK, GRASS, GREEN, GROUND, HUGE, MAN, MARBLE, MEDIUM, MIRAGE, OPAQUE, OPAQUE0, OPAQUE2, OPAQUE4, OPAQUE6, OPAQUE8, PAPER, PENGUIN, PURPLE, RED, setForm(), SHRUB, SMALL, SPHERE, STEP, STUC, TABLE_GLASS, TABLE_METAL, TABLE_WOOD, THING, TINY, TORUS, TREE, WALL, WATER, WHITE, WOOD, and YELLOW.
createFileMenu()
UMenu & Widgets::createFileMenu () private
Definition at line 1410 of file widgets.cpp.
References Theme::Book, Theme::Doc, Theme::Exit, PutInfo::file, g, Gui::gotoWorld(), gui, PutInfo::icon, PutInfo::name, PutInfo::ofile, PutInfo::putIconCB(), putinfo, Global::quitVreng(), Theme::Save, saveCB(), Global::theme, PutInfo::url, and Theme::World.
Referenced by createMenubar().
createGridDialog()
UDialog & Widgets::createGridDialog () private
Definition at line 996 of file widgets.cpp.
References Grid::grid().
createInfobar()
UBox & Widgets::createInfobar () private
Definition at line 143 of file widgets.cpp.
References backCB(), forwardCB(), homeCB(), and infos.
createMarkMenu()
UMenu & Widgets::createMarkMenu () private
Definition at line 253 of file widgets.cpp.
References addMarkCB(), CHAN_LEN, File::closeFile(), Global::env, g, Gui::gotoWorld(), gui, Theme::menuStyle, File::openFile(), Global::theme, URL_LEN, and Env::worldmarks().
Referenced by addMarkCB(), and createMenubar().
createMenubar()
UBox & Widgets::createMenubar () private
Definition at line 165 of file widgets.cpp.
References addDynamicMenus(), Theme::AddObj, addobj_dialog, backCB(), createFileMenu(), createMarkMenu(), destinationsDialog(), Theme::Edit, Global::env, forwardCB(), g, Theme::Grid2D, grid_dialog, helpCB(), homeCB(), Theme::List, Env::menu(), Theme::menuStyle, openSourceDialog(), openWorldsDialog(), Theme::Prefs, prefs_dialog, settings_dialog, showInfoDialog(), Global::theme, tool_dialog, Theme::Tools, and worlds.
createPrefsDialog()
UDialog & Widgets::createPrefsDialog () private
Displays preferences.
Definition at line 712 of file widgets.cpp.
References File::closeFile(), Global::env, g, File::openFile(), Env::prefs(), and prefs_dialog.
createSettingsDialog()
UDialog & Widgets::createSettingsDialog () private
Definition at line 870 of file widgets.cpp.
References ACROBAT_TOOL, CHROME_TOOL, EVINCE_TOOL, FIREFOX_TOOL, FPHONE_TOOL, FREEAMP_TOOL, GHOSTVIEW_TOOL, GV_TOOL, IEXPLORER_TOOL, LIBROFFICE_TOOL, MPEGPLAY_TOOL, MPG123_TOOL, MSOFFICE_TOOL, NTE_TOOL, OPENOFFICE_TOOL, OPERA_TOOL, QUICKTIME_TOOL, RAT_TOOL, SAFARI_TOOL, setPrefCB(), SSH_TOOL, STAROFFICE_TOOL, TELNET_TOOL, VAT_TOOL, VIC_TOOL, VLC_TOOL, VLCMC_TOOL, VRED_TOOL, VREM_TOOL, WB_TOOL, WBD_TOOL, and XPDF_TOOL.
createToolDialog()
UDialog & Widgets::createToolDialog () private
Definition at line 1001 of file widgets.cpp.
References setAudioCB(), setModelerCB(), setVideoCB(), and setWhiteboardCB().
destinationsDialog()
void Widgets::destinationsDialog () private
Dialog box for worlds list.
Definition at line 831 of file widgets.cpp.
References Universe::current(), destinationsHttpReader(), g, Http::httpOpen(), Theme::scrollpaneStyle, Global::theme, URL_LEN, and worlds_dialog.
Referenced by createMenubar().
flushPostponedKRs()
void Widgets::flushPostponedKRs ()
Definition at line 638 of file widgets.cpp.
References changeKey(), postponedKRbuf, postponedKRcount, postponedKRmask, KRKey::time, and KRKey::vrkey.
Referenced by Scene::paintScene(), and processKey().
forwardCB()
void Widgets::forwardCB () private
Definition at line 397 of file widgets.cpp.
References World::goForward().
Referenced by createInfobar(), createMenubar(), and Widgets().
getMessage()
void Widgets::getMessage (UMessageEvent & e) private
Definition at line 423 of file message.cpp.
Referenced by Widgets().
getNavig()
Navig* Widgets::getNavig () inline
Definition at line 87 of file widgets.hpp.
Referenced by Joystick::dragCanvasCB(), Joystick::Joystick(), Joystick::pressCanvasCB(), and Joystick::releaseCanvasCB().
getPointedObject()
WObject * Widgets::getPointedObject (int x, int y, ObjInfo * obji, int depthsel)
returns info about the pointed object but do NOT select it
Definition at line 526 of file widgets.cpp.
References ACTIONNAME_LEN, ACTIONSNUMBER, WObject::byNum(), World::current(), DBG_FORCE, DBG_GUI, Pref::dbgtrace, error(), ObjInfo::farg, ObjInfo::fun, g, Render::getBufferSelection(), World::getName(), WObject::isVisible(), ObjInfo::name, objectActionCB(), objinfo, Global::pref, Global::render, and trace().
Referenced by Navig::mouseMoveCB(), Navig::mousePressB1orB3(), and Navig::mousePressB2().
helpCB()
void Widgets::helpCB () private
Definition at line 422 of file widgets.cpp.
References Universe::current().
Referenced by createMenubar().
homeCB()
void Widgets::homeCB () private
Definition at line 378 of file widgets.cpp.
References audioactive, CHAN_LEN, Channel::current(), Universe::current(), World::current(), Channel::currentTtl(), DBG_IPMC, World::enter(), World::quit(), World::setChanAndJoin(), Audio::start(), and trace().
Referenced by createInfobar(), createMenubar(), and Widgets().
moveMessage()
void Widgets::moveMessage (UMessageEvent & e) private
Definition at line 399 of file message.cpp.
References FALSE, KEY_AR, KEY_AV, KEY_DR, KEY_GA, KEY_JD, KEY_JU, KEY_SD, KEY_SG, setKey(), and TRUE.
Referenced by Widgets().
openMessage()
void Widgets::openMessage (UMessageEvent & e) private
Definition at line 392 of file message.cpp.
References Gui::gotoWorld(), and gui.
Referenced by Widgets().
openSourceDialog()
void Widgets::openSourceDialog () private
Dialog box for vre source.
Definition at line 816 of file widgets.cpp.
References World::current(), World::getUrl(), Http::httpOpen(), source_dialog, and sourceHttpReader().
Referenced by createMenubar().
openWorldsDialog()
void Widgets::openWorldsDialog () private
Dialog box for worlds list.
Definition at line 852 of file widgets.cpp.
References Universe::current(), Http::httpOpen(), universeHttpReader(), URL_LEN, and worlds_dialog.
Referenced by createMenubar().
pendingPostponedKRs()
bool Widgets::pendingPostponedKRs () inline
Definition at line 126 of file widgets.hpp.
Referenced by Scene::paintScene().
processKey()
void Widgets::processKey (long keysym, int keychar, bool press)
Use this callback function for handling AUTOREPEAT Key event Autorepeat is logically suppressed by annulating corresponding Press and Release events.
Principle: Release events are postponed and temporarily stored in KRmask They are processed when coming back to the RenderingWorkProc of the mainLoop if not annulated in the meantime by subsequent Press events.
Definition at line 589 of file widgets.cpp.
References changeKey(), convertKey(), flushPostponedKRs(), gettimeofday(), KRKey::KRBUF_MAX, MAXKEYS, postponedKRbuf, postponedKRcount, postponedKRmask, and KRKey::vrkey.
Referenced by Navig::keyPressCB(), and Navig::keyReleaseCB().
putMessage()
void Widgets::putMessage (UMessageEvent & e) private
Definition at line 378 of file message.cpp.
References Cache::check(), PutInfo::putIcon(), and putinfo.
Referenced by Widgets().
removeUser()
void Widgets::removeUser (GuiItem * gu)
Removes an avatar name.
Definition at line 327 of file widgets.cpp.
References avatars.
Referenced by Gui::removeUser().
removeWorld()
void Widgets::removeWorld (World * world)
Removes a world name.
Definition at line 367 of file widgets.cpp.
References World::getGui(), World::resetGui(), and worlds.
Referenced by Gui::removeWorld().
saveCB()
void Widgets::saveCB () private
Definition at line 402 of file widgets.cpp.
References File::closeFile(), World::current(), World::getName(), World::getUrl(), notice(), File::openFile(), PATH_LEN, and Cache::setCacheName().
Referenced by createFileMenu().
setAudioCB()
void Widgets::setAudioCB (bool on) private
Definition at line 445 of file widgets.cpp.
References audioactive, World::current(), Audio::quit(), and Audio::start().
Referenced by createToolDialog().
setInfobar()
void Widgets::setInfobar (UBox * content)
Definition at line 158 of file widgets.cpp.
References infos.
Referenced by Gui::addCart(), Gui::removeCart(), and Gui::updateCart().
setKey()
void Widgets::setKey (int key, int is_pressed) static
Definition at line 498 of file widgets.cpp.
References changeKey(), and gettimeofday().
Referenced by moveMessage().
setModelerCB()
void Widgets::setModelerCB (bool on) private
Definition at line 469 of file widgets.cpp.
References Modeler::quit(), and Modeler::start().
Referenced by createToolDialog().
setPrefCB()
void Widgets::setPrefCB (int tool) private
Definition at line 430 of file widgets.cpp.
References AUDIO_MASK, HTML_MASK, Audio::init(), Browser::init(), Modeler::init(), Mp3::init(), Mpeg::init(), Office::init(), Pdf::init(), Ps::init(), Video::init(), Wav::init(), Wb::init(), MODELER_MASK, MP3_MASK, MPEG_MASK, OFFICE_MASK, PDF_MASK, PS_MASK, VIDEO_MASK, and WHITEBOARD_MASK.
Referenced by createSettingsDialog().
setRayDirection()
void Widgets::setRayDirection (int x, int y) private
Definition at line 568 of file widgets.cpp.
References localuser, and User::setRayDirection().
Referenced by Navig::mousePressB1orB3(), and Navig::mousePressB2().
setVideoCB()
void Widgets::setVideoCB (bool on) private
Definition at line 457 of file widgets.cpp.
References World::current(), Video::quit(), and Video::start().
Referenced by createToolDialog().
setWhiteboardCB()
void Widgets::setWhiteboardCB (bool on) private
Definition at line 463 of file widgets.cpp.
References World::current(), Wb::quit(), and Wb::start().
Referenced by createToolDialog().
showInfoDialog()
void Widgets::showInfoDialog (const char * title, const char * message) static
Definition at line 285 of file widgets.cpp.
Referenced by createMenubar().
updateUser()
void Widgets::updateUser (GuiItem * gu, User * user)
Updates an avatar.
Definition at line 320 of file widgets.cpp.
References setUser().
Referenced by Gui::updateUser().
updateWorld()
void Widgets::updateWorld (World * world, bool isCurrentWorld)
Updates a world name.
Definition at line 355 of file widgets.cpp.
References World::getGui(), World::isGui(), and setWorld().
Referenced by Gui::updateWorld().
Friends And Related Function Documentation
Gui
friend class Gui friend
Definition at line 130 of file widgets.hpp.
Navig
friend class Navig friend
Definition at line 132 of file widgets.hpp.
Panels
friend class Panels friend
Definition at line 133 of file widgets.hpp.
Scene
friend class Scene friend
Definition at line 131 of file widgets.hpp.
Member Data Documentation
addobj_dialog
UDialog & Widgets::addobj_dialog private
Definition at line 144 of file widgets.hpp.
Referenced by createMenubar(), and Panels::Panels().
avatars
UElem Widgets::avatars private
Definition at line 140 of file widgets.hpp.
Referenced by addUser(), Panels::Panels(), removeUser(), and Widgets().
capture
class Capture& Widgets::capture private
Definition at line 138 of file widgets.hpp.
Referenced by Scene::paintScene(), and Panels::Panels().
carts
UElem Widgets::carts private
Definition at line 140 of file widgets.hpp.
Referenced by Gui::addCart(), Panels::Panels(), Gui::removeCart(), and Widgets().
grid_dialog
UDialog & Widgets::grid_dialog private
Definition at line 144 of file widgets.hpp.
Referenced by createMenubar().
gui
Gui& Widgets::gui private
reference to the GUI object
Definition at line 136 of file widgets.hpp.
Referenced by createFileMenu(), createMarkMenu(), Navig::keyPressCB(), Navig::keyReleaseCB(), Navig::mouseDragCB(), Navig::mouseMoveCB(), Navig::mousePressB1orB3(), Navig::mousePressB2(), Navig::mousePressCB(), Navig::mouseReleaseCB(), and openMessage().
GW_DEFAULT_SCROLL
const int Widgets::GW_DEFAULT_SCROLL = 50 static
Definition at line 81 of file widgets.hpp.
GW_ZOOM_SCROLL
const int Widgets::GW_ZOOM_SCROLL = 35 static
Definition at line 82 of file widgets.hpp.
infobar
UBox& Widgets::infobar private
Definition at line 147 of file widgets.hpp.
Referenced by Widgets().
infos
UBox Widgets::infos private
Definition at line 139 of file widgets.hpp.
Referenced by createInfobar(), Navig::selectObject(), and setInfobar().
menubar
UBox & Widgets::menubar private
Definition at line 147 of file widgets.hpp.
Referenced by Widgets().
messages
class Messages& Widgets::messages private
Definition at line 145 of file widgets.hpp.
Referenced by Gui::getClicked(), Gui::initClicked(), Navig::mousePressB1orB3(), Panels::Panels(), and Gui::writeMessage().
MESSAGES_BOX_HEIGHT
const int Widgets::MESSAGES_BOX_HEIGHT = 150 static
Definition at line 80 of file widgets.hpp.
MESSAGES_BOX_WIDTH
const int Widgets::MESSAGES_BOX_WIDTH = 320 static
Definition at line 79 of file widgets.hpp.
navig
class Navig& Widgets::navig private
navigation
Definition at line 142 of file widgets.hpp.
Referenced by Gui::clearInfoBar().
panels
class Panels& Widgets::panels private
Definition at line 146 of file widgets.hpp.
Referenced by Gui::showCartDialog(), Gui::showManipulator(), Gui::showNavigator(), and Widgets().
postponedKRbuf
KRKey Widgets::postponedKRbuf[KRKey::KRBUF_MAX] private
kbd bufs
Definition at line 150 of file widgets.hpp.
Referenced by flushPostponedKRs(), and processKey().
postponedKRcount
long Widgets::postponedKRcount private
count in the KRbuf
Definition at line 149 of file widgets.hpp.
Referenced by flushPostponedKRs(), and processKey().
postponedKRmask
long Widgets::postponedKRmask private
mask of all postponed Key Release events
Definition at line 148 of file widgets.hpp.
Referenced by flushPostponedKRs(), and processKey().
prefs_dialog
UDialog& Widgets::prefs_dialog private
Definition at line 144 of file widgets.hpp.
Referenced by createMenubar(), and createPrefsDialog().
putinfo
class PutInfo& Widgets::putinfo private
Definition at line 137 of file widgets.hpp.
Referenced by createFileMenu(), and putMessage().
scene
class Scene& Widgets::scene private
OpenGL Drawing Zone.
Definition at line 141 of file widgets.hpp.
Referenced by Gui::getCycles(), Gui::getScene(), Navig::mousePressCB(), and Widgets().
settings_dialog
UDialog & Widgets::settings_dialog private
Definition at line 144 of file widgets.hpp.
Referenced by createMenubar().
source_dialog
UOptionDialog& Widgets::source_dialog private
Definition at line 143 of file widgets.hpp.
Referenced by openSourceDialog().
tool_dialog
UDialog & Widgets::tool_dialog private
Definition at line 144 of file widgets.hpp.
Referenced by createMenubar().
worlds
UElem Widgets::worlds private
Definition at line 140 of file widgets.hpp.
Referenced by addWorld(), createMenubar(), Panels::Panels(), removeWorld(), and Widgets().
worlds_dialog
UOptionDialog & Widgets::worlds_dialog private
Definition at line 143 of file widgets.hpp.
Referenced by destinationsDialog(), and openWorldsDialog().
The documentation for this class was generated from the following files:
src/gui/widgets.hpp
src/gui/message.cpp
src/gui/widgets.cpp