VREng: Carrier Class Reference
Carrier Class Reference
Carrier class.
#include <carrier.hpp>
Public Types
enum { SETLSPEED, SETASPEED }
Public Types inherited from WObject
enum {
STILL, MOBILE, EPHEMERAL, INVISIBLE,
MOBILEINVISIBLE, MODE_MAX
}
enum {
DELETED = -1, NONE = 0, INACTIVE = 0, ACTIVE,
PLAYING, TAKEN, DROPPED, MOVED,
CARRYING, IN_CART, ENDSTATE
}
enum { RENDER_LOW, RENDER_NORMAL, RENDER_HIGH }
typedef std::list< class Solid * > solidList
Public Member Functions
virtual const OClass * getOClass ()
virtual inst. method
Carrier ()
Constructor.
virtual bool isTaking () const
Accessor: is something taking ?
virtual void take (WObject *po)
handle position changes Takes control of the object to manipulate it.
virtual void set (WObject *po)
Sets taking.
virtual void leave (WObject *po)
Leaves control of the mouse to enter in navigation mode.
virtual void leave ()
called when we release an object Releases the carried object, put it into the mobile-list and desactivates the carrier
virtual void mouseEvent (int8_t vkey, float last)
Mouse event called by Motion::move (navig.cpp)
virtual void mouseEvent (uint16_t x, uint16_t y, uint8_t button)
called by mpress in navig.cpp to redirect mouse clics when we move the object left button leaves the object rigth button changes the motion mode
virtual void keyEvent (uint8_t vkey, float last)
called by userChangePositionOneType from move.cc to redirect arrow keys to move the object and handle intersects of this object
Public Member Functions inherited from WObject
WObject ()
Constructor.
virtual ~WObject ()
Destructor.
virtual uint8_t typeId ()
Abstrct class.
virtual const char * typeName ()
WCreator * getCreator ()
WReplicator * getReplicator ()
virtual bool isMoving ()
Checks weither object is moving.
virtual void changePosition (float lasting)
Changes the position after a triggered movement.
virtual void changePermanent (float lasting)
Changes the position during a permanent movement.
virtual void updateTime (time_t sec, time_t usec, float *lasting)
Updates remaining times of the movement.
virtual bool updateToNetwork (const Pos &oldpos)
Publishes changes to the network.
virtual bool updatePosToNetwork (const Pos &oldpos, int propxy, int propz, int propaz, int propax, int propay)
Publishes position changes to the network.
virtual bool whenIntersect (WObject *pcur, WObject *pold)
Handles an ingoing collision with another object.
virtual bool whenIntersectOut (WObject *pcur, WObject *pold)
Handles an outgoing collision with another object.
virtual void whenWallsIntersect (WObject *pold, V3 *norm)
Handles collisions with walls.
virtual void render ()
Makes special rendering.
virtual void lighting ()
Makes special lighting.
virtual void quit ()
Makes all thing when leaving the object.
const solidList & solids () const
solidlist address.
uint32_t countOfSolids () const
virtual class Solid * getSolid () const
Returns first solid.
virtual void addSolid (class Solid *solid)
Adds to solidList.
virtual void deleteSolids ()
Deletes solids from solidList.
virtual int interAABB (WObject *o1, WObject *o2)
virtual bool haveAction ()
Checks weither have actions.
virtual uint8_t numberAction ()
Number of actions.
virtual bool runAction (const char *action)
Runs action everwhere if available.
virtual void setType (int type)
Sets object type.
virtual int getType ()
Gets object type.
virtual int getNumber ()
Gets object number.
virtual uint16_t getNum ()
Gets a new object number.
virtual void getPosition (M4 &mpos)
Gives solid's position.
virtual void getRelativeBB (V3 &center, V3 &size)
virtual void getDim (V3 &dim)
virtual void getCenter (V3 &center)
virtual void getAbsoluteBB (V3 &center, V3 &size)
Gets relative or absolute center and size of solid.
virtual uint8_t getFrames ()
Gets number of frames of this solid.
virtual uint8_t getFrame ()
Gets index of current frame of this solid.
virtual void setFrame (uint8_t _frame)
Sets current frame.
virtual bool isValid () const
Checks if valid object type.
virtual bool isPermanent () const
Checks if permanent object.
virtual const char * named () const
Gets names.named.
virtual const char * getInstance () const
Gets names.instance.
virtual const char * urlName () const
Gets names.url.
virtual const char * ownerName () const
Gets names.owner.
virtual const char * worldName () const
Gets names.owner.
virtual bool explicitName () const
Checks wether the object is explicitly named.
virtual void toDelete ()
Delete this object latter.
virtual bool removeFromScene ()
Removes an object.
virtual bool isOwner () const
Returns true if owner.
virtual void setOwner (const char *_owner)
Initialize owner.
virtual void setOwner ()
Initialize local user as owner.
virtual void click (GLint x, GLint y)
Execute an object's click method if it's defined.
virtual void click (V3 norm)
Intercepts a click.
virtual char * tokenize (char *l)
Tokenizes the line <object ...
virtual Parse * parse ()
Gets current parse.
void setWObjectId ()
Sets the WObjectid.
void copyNoid (class Noid _noid)
Copies the NetObjectid in WObjectId.
void setSrcId (uint32_t src_id)
Sets the SrcId.
void setPortId (uint16_t port_id)
Sets the PortId.
void setObjId (uint16_t obj_id)
Sets the ObjId.
uint32_t getSrcId () const
Gets the SrcId.
uint16_t getPortId () const
Gets the PortId.
uint16_t getObjId () const
Gets the ObjId.
virtual void update3D (Pos &pos)
Updates object in the 3D.
virtual void updateAll3D (Pos &pos)
Updates object in the 3D.
virtual void updateCamera (Pos &pos)
Updates camera in the 3D.
virtual void getSurfVecs (Pos &pos, V3 *v, V3 *w, V3 *norm)
Returns two vectors that describe the object's surface and a normal vector to that surface.
virtual void updateBB ()
Updates object's Bounding Box.
virtual void getMaterials (GLfloat *dif, GLfloat *amb, GLfloat *spe, GLfloat *emi, GLint *shi, GLfloat *alpha)
virtual void insertIntoGrid ()
Adds an object into the grid.
virtual void deleteFromGrid ()
Deletes an object from the grid.
virtual void updateGrid (const float *bbminnew, const float *bbmaxnew, const float *bbminold, const float *bbmaxold)
Updates an object in the grid.
virtual void updateGrid (const Pos &oldpos)
virtual void updateGrid (const WObject *pold)
Updates an object into the grid.
virtual void addToList (std::list< WObject * > &olist)
virtual OList * addToList (OList *olist)
Adds an object pointer into a olist.
virtual void addToList ()
Adds an object pointer into a olist.
virtual void addToStill ()
Adds an object pointer into stillList.
virtual void addToMobile ()
Adds an object pointer into mobileList.
virtual void addToInvisible ()
Adds an object pointer into invisibleList.
virtual void addToRender ()
Adds an object pointer into renderList.
virtual void delFromMobile ()
Deletes an object pointer from mobileList.
virtual void clearList ()
Clears an olist.
virtual void clearList (std::list< WObject * > &olist)
Clears an olist.
virtual void addToListOnce (std::list< WObject * > &olist)
virtual OList * addToListOnce (OList *olist)
Adds an object pointer into a list only once time.
virtual void delFromList (std::list< WObject * > &olist)
virtual OList * delFromList (OList *olist)
Deletes an object pointer from a olist.
virtual void delFromList ()
Deletes an object pointer from a olist.
virtual OList * getVicinityList (const WObject *pold)
Returns list of pointers on objects touching cell where is the object.
virtual OList * addListToList (OList *list1, OList *list2)
Concatenation (test of "ispointed") of list pointers on an object.
virtual bool isStill ()
Checks an object exists in the stilllist.
virtual bool isMobile ()
virtual bool isEphemeral ()
Checks an object exists in the mobilelist.
virtual WObject * byWObject (WObject *po)
Gets a WObject from the lists.
virtual void checkVicinity (WObject *pold)
< Gets an object by its num.
virtual void imposedMovement (time_t sec, time_t usec)
Handles an object movement.
virtual void elementaryImposedMovement (float lasting)
Handles an elementary object movement.
virtual void enableImposedMovement ()
Enables movement on an object.
virtual void enablePermanentMovement ()
Enables permanent movement on an object.
virtual void disablePermanentMovement ()
Disables movement on an object.
virtual void enablePermanentMovement (float speed)
Enables permanent movement on an object.
virtual void initImposedMovement (float lasting)
Initializes movement on an object.
virtual float diffTime (time_t sec, time_t usec)
Updates times on an object.
virtual void stopImposedMovement ()
Stops a movement on an object.
virtual void permanentMovement (time_t sec, time_t usec)
Handles a permanent object movement.
virtual void elementaryPermanentMovement (float lasting)
Handles an elementary permanent object movement.
virtual void setLasting (float maxlast)
Sets the max lasting time of an object.
virtual float getLasting () const
Gets the lasting time of an object.
virtual bool testMoving ()
Tests if object is moving.
virtual bool updateLasting (time_t sec, time_t usec, float *lasting)
Updates remaining times of the movement.
virtual void moveUserToObject (float val, float _lttl, float _attl)
Moves the user to the object.
virtual void setObjectName (const char *str)
Sets an object name.
virtual WObject * getObjectByName (const char *str)
Gets an object by its name.
virtual void updateNames ()
Updates names.
virtual void initializeObject (uint8_t mode)
Initializes object.
virtual void initializeMobileObject (float last)
virtual void initializeEphemeralObject (float last)
Initializes mobile object.
virtual void initializeStillObject ()
Initializes still object.
void createPermanentNetObject (uint8_t props, uint16_t oid)
Creates local permanent NetObject.
void createVolatileNetObject (uint8_t props)
Creates local volatile NetObject.
void replicateVolatileNetObject (uint8_t props, class Noid _noid)
Replicate distant volatile NetObject.
virtual void enableBehavior (uint32_t flag)
Enables behavior.
virtual void disableBehavior (uint32_t flag)
Disables behavior.
virtual bool isBehavior (uint32_t flag) const
Checks weither this behavior is on.
virtual bool bbBehavior () const
Checks weither BBox behavior is on.
virtual bool isSeen ()
Checks weither the object is in the sight view of the user.
virtual void setVisible (bool flag)
Sets visible or not the 3D object.
virtual bool isVisible ()
Checks weither the object is visible.
virtual void setFlashy (float *color)
Sets flashy the 3D object.
virtual void setFlashy ()
Sets flashy the 3D object.
virtual void resetFlashy ()
Resets flashy the 3D object.
virtual void setRay (GLint wx, GLint wy)
virtual void resetRay ()
Resets Ray on the 3D object.
virtual void setReflexive (bool flag)
virtual bool isSelectable () const
Checks weither 3D selectable behavior is on.
virtual uint32_t collideBehavior () const
Returns collide behavior.
virtual void setRenderPrior (uint8_t _prior)
Sets render priority.
virtual uint8_t getRenderPrior () const
Gets render priority.
void generalIntersect (WObject *pold, OList *vicinityList)
General intersection of objects.
bool ingoingNeighbor (WObject *pold, WObject *neighbor)
bool outgoingNeighbor (WObject *pold, WObject *neighbor)
Checks ingoing intersection with a neighbor.
void ingoingWalls (WObject *pold)
Checks outgoing intersection with a neighbor.
virtual void copyPosAndBB (Pos &newpos)
Checks ingoing intersection with walls.
virtual void copyPositionAndBB (WObject *o)
Copy object position and Bounding Box.
virtual bool projectPosition (WObject *pcur, WObject *pold)
Projects object position.
virtual int projectPositionOnObstacle (Pos &pcur, Pos &pold, Pos &obstacle)
Projects object position on an obstacle.
virtual void initPosition ()
Init 3D and grid position.
virtual void updatePosition ()
Updating 3D.
virtual void updatePositionAndGrid (Pos &oldpos)
Updating 3D and grid position.
virtual void updatePositionAndGrid (WObject *pold)
Updating 3D and grid position.
virtual void computeNormal (WObject *mobil, V3 *normal)
Computes the normal of an object.
virtual void computeNormal (Pos &mobil, Pos &stil, V3 *normal)
Computes the normal of still object.
virtual void bounceTrajectory (WObject *pold, V3 *norm)
Intersects with wall.
void getProperty (uint8_t prop_id, class Payload *pp)
Gets the local copy property from the payload (pp->data).
void putProperty (uint8_t prop_id, class Payload *pp)
Puts the local copy property in the payload.
virtual void deleteReplica ()
Deletes a replicated object.
virtual struct GuiItem * getGui () const
Gets the GUI handle.
virtual bool isGui () const
Checks the GUI handle.
virtual void resetGui ()
Resets the GUI handle.
virtual void clearObjectBar ()
Clears the ObjectBar in the GUI.
virtual void specialAction (int action, void *data, time_t sec, time_t usec)
Calls methods dedicated to each object.
void getObjectHumanName (char **classname, char **instancename, char **actionnames)
Gives object's class_name & action names.
virtual void getMySqlPosition ()
Checks if position is managed by MySql and get it.
virtual void updateMySqlPosition ()
Checks if position is managed by MySql and update it.
virtual int16_t getMySqlState ()
Gets state from MySql.
virtual void updateMySqlPosZ ()
Checks if posZ is managed by MySql.
virtual void updateMySqlState (int16_t state)
Updates state for MySql.
virtual void flushMySqlPosition ()
Flushes position for MySql.
virtual void quitMySql ()
Quits MySql.
Static Public Member Functions
static void funcs ()
init funclist
Static Public Member Functions inherited from WObject
static int interAABB (V3 center1, V3 size1, V3 center2, V3 size2)
Computes intersection between 2 AABB (Axis Aligned Bounding Box).
static int interAABBVertical (V3 center1, V3 size1, V3 center2, V3 size2)
static int interAABBHorizontal (V3 center1, V3 size1, V3 center2, V3 size2)
static void show (const char *name)
Snaps position (debug).
static WObject * byNum (uint16_t num)
static void moveObject (WObject *po, void *d, time_t s, time_t u)
User moves the object.
static void getObjectNameById (uint8_t type_id, char *name)
Gets a name by its id.
static void resetObjectsNumber ()
Resets object seq.
static uint32_t getObjectsNumber ()
Gets current object sequence number.
Static Public Attributes
static const float LSPEED = 0.5
linear speed
static const float ASPEED = 0.5
angular speed
static const OClass oclass
class variable
Private Member Functions
virtual void defaults ()
Sets default values.
Static Private Member Functions
static void takeControl (WObject *po, void *d, time_t s, time_t u)
called when we take an object puts the object into the carrier and realizes all needed operations to pass in transport mode
static void leaveControl (WObject *po, void *d, time_t s, time_t u)
called when we leave an object
static void setLspeed (Carrier *pc, void *d, time_t s, time_t u)
static void setAspeed (Carrier *pc, void *d, time_t s, time_t u)
Private Attributes
class WObject * carriedObject
object ptr
float lspeed
linear speed
float aspeed
angular speed
bool taking
flag true/false
Additional Inherited Members
Public Attributes inherited from WObject
solidList _solids
list of solids.
class NetObject * noh
reserved field for network.
struct GuiItem * guip
reserved field for GUI.
uint8_t type
object type.
uint8_t mode
object world mode.
uint16_t num
object sequence number.
uint32_t behavior
behavior flags.
Names names
names.
Pos pos
position in the space.
Move move
movement specific.
class WObjectId noid
WObject Id.
bool is_in_a_list
true if it is already in an OList.
bool removed
flag removed or not.
int16_t state
current state.
int8_t prior
render priority.
char * geometry
geometry string.
class Solid * solid
solid pointer
char chan [CHAN_LEN]
channel.
class Flare * flare
flare instance
Static Protected Member Functions inherited from WObject
static void get_xy (WObject *po, class Payload *pp)
static void get_z (WObject *po, class Payload *pp)
static void get_az (WObject *po, class Payload *pp)
static void get_ay (WObject *po, class Payload *pp)
static void get_ax (WObject *po, class Payload *pp)
static void get_hname (WObject *po, class Payload *pp)
static void put_xy (WObject *po, class Payload *pp)
static void put_z (WObject *po, class Payload *pp)
static void put_az (WObject *po, class Payload *pp)
static void put_ay (WObject *po, class Payload *pp)
static void put_ax (WObject *po, class Payload *pp)
static void put_hname (WObject *po, class Payload *pp)
Protected Attributes inherited from WObject
bool objectbar
true if object bar is active.
Detailed Description
Carrier class.
Used to move an object. The object, deleted from mobile-list, is managed by the Carrier. The motion is done :
either by the mouse in the manipulator menu
either by arrow keys -> Obsoleted . button 1 leaves the object . button 3 changes the mode of motion : mode 1: translation along X/Y axis (coordoninates relative to avatar) mode 2: translation along Y/Z axis mode 3: rotation around X and Z axis mode 4: rotation around Y axis
Definition at line 45 of file carrier.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
SETLSPEED
SETASPEED
Definition at line 59 of file carrier.hpp.
Constructor & Destructor Documentation
Carrier()
Carrier::Carrier ()
Constructor.
Definition at line 41 of file carrier.cpp.
References CARRIER_TYPE, defaults(), g, Global::gui, Gui::setToCarrier(), and WObject::type.
Member Function Documentation
defaults()
void Carrier::defaults () private virtual
Sets default values.
Definition at line 32 of file carrier.cpp.
References aspeed, ASPEED, carriedObject, lspeed, LSPEED, and taking.
Referenced by Carrier(), and leave().
funcs()
void Carrier::funcs () static
init funclist
Definition at line 167 of file carrier.cpp.
References CARRIER_TYPE, setActionFunc(), SETASPEED, setAspeed(), SETLSPEED, setLspeed(), and WO_ACTION.
getOClass()
virtual const OClass* Carrier::getOClass () inline virtual
virtual inst. method
Reimplemented from WObject.
Definition at line 66 of file carrier.hpp.
References oclass.
isTaking()
bool Carrier::isTaking () const virtual
Accessor: is something taking ?
Accessor.
Definition at line 49 of file carrier.cpp.
References taking.
Referenced by User::changePositionOneDir(), Navig::mousePressCB(), Motion::move(), and User::specialAction().
keyEvent()
void Carrier::keyEvent (uint8_t vkey, float last) virtual
called by userChangePositionOneType from move.cc to redirect arrow keys to move the object and handle intersects of this object
Key event: called by changePositionOneDir (move.cc)
Definition at line 154 of file carrier.cpp.
leave() [1/2]
void Carrier::leave () virtual
called when we release an object Releases the carried object, put it into the mobile-list and desactivates the carrier
Definition at line 85 of file carrier.cpp.
References carriedObject, defaults(), g, Global::gui, Pos::moved, notice(), WObject::pos, and Gui::showNavigator().
Referenced by leave(), and mouseEvent().
leave() [2/2]
void Carrier::leave (WObject * po) virtual
Leaves control of the mouse to enter in navigation mode.
Definition at line 80 of file carrier.cpp.
References leave().
Referenced by leaveControl().
leaveControl()
void Carrier::leaveControl (WObject * po, void * d, time_t s, time_t u) static private
called when we leave an object
Definition at line 59 of file carrier.cpp.
References User::carrier, leave(), and localuser.
mouseEvent() [1/2]
void Carrier::mouseEvent (int8_t vkey, float last) virtual
Mouse event called by Motion::move (navig.cpp)
Definition at line 113 of file carrier.cpp.
References Pos::ax, Pos::ay, Pos::az, carriedObject, COLLIDE_NEVER, WObject::copyPositionAndBB(), WObject::generalIntersect(), WObject::getVicinityList(), WObject::isBehavior(), KEY_AR, KEY_AV, KEY_DE, KEY_DR, KEY_GA, KEY_JD, KEY_JU, KEY_MT, KEY_SD, KEY_SG, KEY_TL, KEY_TR, lspeed, WObject::names, WObject::pos, Names::type, WObject::updateGrid(), WObject::updatePositionAndGrid(), WObject::WObject(), Pos::x, Pos::y, and Pos::z.
Referenced by User::changePositionOneDir(), and Navig::mousePressCB().
mouseEvent() [2/2]
void Carrier::mouseEvent (uint16_t x, uint16_t y, uint8_t button) virtual
called by mpress in navig.cpp to redirect mouse clics when we move the object left button leaves the object rigth button changes the motion mode
Mouse event called by mpress (navig.cpp)
Definition at line 105 of file carrier.cpp.
References leave().
set()
void Carrier::set (WObject * po) virtual
Sets taking.
Definition at line 96 of file carrier.cpp.
References carriedObject, and taking.
setAspeed()
void Carrier::setAspeed (Carrier * pc, void * d, time_t s, time_t u) static private
Definition at line 162 of file carrier.cpp.
References aspeed, and d.
Referenced by funcs().
setLspeed()
void Carrier::setLspeed (Carrier * pc, void * d, time_t s, time_t u) static private
Definition at line 157 of file carrier.cpp.
References d, and lspeed.
Referenced by funcs().
take()
void Carrier::take (WObject * po) virtual
handle position changes Takes control of the object to manipulate it.
Takes control of the mouse to enter in manipulation mode.
The position/orientation of the object will be changed by changePosition and the object will be updated in the 3D
Definition at line 65 of file carrier.cpp.
References Move::aspeed, carriedObject, g, WObject::getInstance(), Global::gui, WObject::initImposedMovement(), Move::lspeed, WObject::MOBILE, WObject::mode, WObject::move, notice(), Gui::showManipulator(), taking, and V3::v.
Referenced by WObject::moveObject(), and takeControl().
takeControl()
void Carrier::takeControl (WObject * po, void * d, time_t s, time_t u) static private
called when we take an object puts the object into the carrier and realizes all needed operations to pass in transport mode
Definition at line 54 of file carrier.cpp.
References User::carrier, localuser, and take().
Member Data Documentation
aspeed
float Carrier::aspeed private
angular speed
Definition at line 50 of file carrier.hpp.
Referenced by defaults(), and setAspeed().
ASPEED
const float Carrier::ASPEED = 0.5 static
angular speed
Definition at line 56 of file carrier.hpp.
Referenced by defaults().
carriedObject
class WObject* Carrier::carriedObject private
object ptr
Definition at line 48 of file carrier.hpp.
Referenced by defaults(), leave(), mouseEvent(), set(), and take().
lspeed
float Carrier::lspeed private
linear speed
Definition at line 49 of file carrier.hpp.
Referenced by defaults(), mouseEvent(), and setLspeed().
LSPEED
const float Carrier::LSPEED = 0.5 static
linear speed
Definition at line 55 of file carrier.hpp.
Referenced by defaults(), and Motion::move().
oclass
const OClass Carrier::oclass static
class variable
Definition at line 64 of file carrier.hpp.
Referenced by getOClass().
taking
bool Carrier::taking private
flag true/false
Definition at line 51 of file carrier.hpp.
Referenced by defaults(), isTaking(), set(), and take().
The documentation for this class was generated from the following files:
src/wo/carrier.hpp
src/wo/carrier.cpp