VREng: Ball Class Reference
Ball Class Reference
Ball class.
#include <ball.hpp>
Public Types
enum {
PROPHNAME, PROPXY, PROPZ, PROPAZ,
PROPAX, PROPAY, PROPS
}
enum {
PUSH, PULL, SHOOT, UP,
TAKE, DROP, TURN, KILL,
CREATE, RECREATE, NONE
}
Public Types inherited from WObject
enum {
STILL, MOBILE, EPHEMERAL, INVISIBLE,
MOBILEINVISIBLE, MODE_MAX
}
enum {
DELETED = -1, NONE = 0, INACTIVE = 0, ACTIVE,
PLAYING, TAKEN, DROPPED, MOVED,
CARRYING, IN_CART, ENDSTATE
}
enum { RENDER_LOW, RENDER_NORMAL, RENDER_HIGH }
typedef std::list< class Solid * > solidList
Public Member Functions
virtual const OClass * getOClass ()
Ball (class WObject *o, void *d, time_t s, time_t u)
constructor: called by cauldron.
Ball (class World *w, void *d, time_t s, time_t u)
constructor: called by world.
Ball (uint8_t type_id, Noid noid, Payload *pp)
constructor: network replication.
Ball (WObject *user, char *form)
constructor: created by user.
Ball (char *l)
constructor: fileline.
virtual bool isMoving ()
Checks if object is moving.
virtual void changePosition (float lasting)
Does any position changes.
virtual void changePermanent (float lasting)
Does permanent position changes.
virtual void updateTime (time_t s, time_t u, float *lasting)
Updates times.
virtual bool updateToNetwork (const Pos &oldpos)
Publishes to network.
virtual bool whenIntersect (WObject *pcur, WObject *pold)
Handles collisions.
virtual void whenWallsIntersect (WObject *pold, V3 *norm)
Handles collisions with a wall.
virtual void quit ()
Quits.
Public Member Functions inherited from WObject
WObject ()
Constructor.
virtual ~WObject ()
Destructor.
virtual uint8_t typeId ()
Abstrct class.
virtual const char * typeName ()
WCreator * getCreator ()
WReplicator * getReplicator ()
virtual bool updatePosToNetwork (const Pos &oldpos, int propxy, int propz, int propaz, int propax, int propay)
Publishes position changes to the network.
virtual bool whenIntersectOut (WObject *pcur, WObject *pold)
Handles an outgoing collision with another object.
virtual void render ()
Makes special rendering.
virtual void lighting ()
Makes special lighting.
const solidList & solids () const
solidlist address.
uint32_t countOfSolids () const
virtual class Solid * getSolid () const
Returns first solid.
virtual void addSolid (class Solid *solid)
Adds to solidList.
virtual void deleteSolids ()
Deletes solids from solidList.
virtual int interAABB (WObject *o1, WObject *o2)
virtual bool haveAction ()
Checks weither have actions.
virtual uint8_t numberAction ()
Number of actions.
virtual bool runAction (const char *action)
Runs action everwhere if available.
virtual void setType (int type)
Sets object type.
virtual int getType ()
Gets object type.
virtual int getNumber ()
Gets object number.
virtual uint16_t getNum ()
Gets a new object number.
virtual void getPosition (M4 &mpos)
Gives solid's position.
virtual void getRelativeBB (V3 &center, V3 &size)
virtual void getDim (V3 &dim)
virtual void getCenter (V3 &center)
virtual void getAbsoluteBB (V3 &center, V3 &size)
Gets relative or absolute center and size of solid.
virtual uint8_t getFrames ()
Gets number of frames of this solid.
virtual uint8_t getFrame ()
Gets index of current frame of this solid.
virtual void setFrame (uint8_t _frame)
Sets current frame.
virtual bool isValid () const
Checks if valid object type.
virtual bool isPermanent () const
Checks if permanent object.
virtual const char * named () const
Gets names.named.
virtual const char * getInstance () const
Gets names.instance.
virtual const char * urlName () const
Gets names.url.
virtual const char * ownerName () const
Gets names.owner.
virtual const char * worldName () const
Gets names.owner.
virtual bool explicitName () const
Checks wether the object is explicitly named.
virtual void toDelete ()
Delete this object latter.
virtual bool removeFromScene ()
Removes an object.
virtual bool isOwner () const
Returns true if owner.
virtual void setOwner (const char *_owner)
Initialize owner.
virtual void setOwner ()
Initialize local user as owner.
virtual void click (GLint x, GLint y)
Execute an object's click method if it's defined.
virtual void click (V3 norm)
Intercepts a click.
virtual char * tokenize (char *l)
Tokenizes the line <object ...
virtual Parse * parse ()
Gets current parse.
void setWObjectId ()
Sets the WObjectid.
void copyNoid (class Noid _noid)
Copies the NetObjectid in WObjectId.
void setSrcId (uint32_t src_id)
Sets the SrcId.
void setPortId (uint16_t port_id)
Sets the PortId.
void setObjId (uint16_t obj_id)
Sets the ObjId.
uint32_t getSrcId () const
Gets the SrcId.
uint16_t getPortId () const
Gets the PortId.
uint16_t getObjId () const
Gets the ObjId.
virtual void update3D (Pos &pos)
Updates object in the 3D.
virtual void updateAll3D (Pos &pos)
Updates object in the 3D.
virtual void updateCamera (Pos &pos)
Updates camera in the 3D.
virtual void getSurfVecs (Pos &pos, V3 *v, V3 *w, V3 *norm)
Returns two vectors that describe the object's surface and a normal vector to that surface.
virtual void updateBB ()
Updates object's Bounding Box.
virtual void getMaterials (GLfloat *dif, GLfloat *amb, GLfloat *spe, GLfloat *emi, GLint *shi, GLfloat *alpha)
virtual void insertIntoGrid ()
Adds an object into the grid.
virtual void deleteFromGrid ()
Deletes an object from the grid.
virtual void updateGrid (const float *bbminnew, const float *bbmaxnew, const float *bbminold, const float *bbmaxold)
Updates an object in the grid.
virtual void updateGrid (const Pos &oldpos)
virtual void updateGrid (const WObject *pold)
Updates an object into the grid.
virtual void addToList (std::list< WObject * > &olist)
virtual OList * addToList (OList *olist)
Adds an object pointer into a olist.
virtual void addToList ()
Adds an object pointer into a olist.
virtual void addToStill ()
Adds an object pointer into stillList.
virtual void addToMobile ()
Adds an object pointer into mobileList.
virtual void addToInvisible ()
Adds an object pointer into invisibleList.
virtual void addToRender ()
Adds an object pointer into renderList.
virtual void delFromMobile ()
Deletes an object pointer from mobileList.
virtual void clearList ()
Clears an olist.
virtual void clearList (std::list< WObject * > &olist)
Clears an olist.
virtual void addToListOnce (std::list< WObject * > &olist)
virtual OList * addToListOnce (OList *olist)
Adds an object pointer into a list only once time.
virtual void delFromList (std::list< WObject * > &olist)
virtual OList * delFromList (OList *olist)
Deletes an object pointer from a olist.
virtual void delFromList ()
Deletes an object pointer from a olist.
virtual OList * getVicinityList (const WObject *pold)
Returns list of pointers on objects touching cell where is the object.
virtual OList * addListToList (OList *list1, OList *list2)
Concatenation (test of "ispointed") of list pointers on an object.
virtual bool isStill ()
Checks an object exists in the stilllist.
virtual bool isMobile ()
virtual bool isEphemeral ()
Checks an object exists in the mobilelist.
virtual WObject * byWObject (WObject *po)
Gets a WObject from the lists.
virtual void checkVicinity (WObject *pold)
< Gets an object by its num.
virtual void imposedMovement (time_t sec, time_t usec)
Handles an object movement.
virtual void elementaryImposedMovement (float lasting)
Handles an elementary object movement.
virtual void enableImposedMovement ()
Enables movement on an object.
virtual void enablePermanentMovement ()
Enables permanent movement on an object.
virtual void disablePermanentMovement ()
Disables movement on an object.
virtual void enablePermanentMovement (float speed)
Enables permanent movement on an object.
virtual void initImposedMovement (float lasting)
Initializes movement on an object.
virtual float diffTime (time_t sec, time_t usec)
Updates times on an object.
virtual void stopImposedMovement ()
Stops a movement on an object.
virtual void permanentMovement (time_t sec, time_t usec)
Handles a permanent object movement.
virtual void elementaryPermanentMovement (float lasting)
Handles an elementary permanent object movement.
virtual void setLasting (float maxlast)
Sets the max lasting time of an object.
virtual float getLasting () const
Gets the lasting time of an object.
virtual bool testMoving ()
Tests if object is moving.
virtual bool updateLasting (time_t sec, time_t usec, float *lasting)
Updates remaining times of the movement.
virtual void moveUserToObject (float val, float _lttl, float _attl)
Moves the user to the object.
virtual void setObjectName (const char *str)
Sets an object name.
virtual WObject * getObjectByName (const char *str)
Gets an object by its name.
virtual void updateNames ()
Updates names.
virtual void initializeObject (uint8_t mode)
Initializes object.
virtual void initializeMobileObject (float last)
virtual void initializeEphemeralObject (float last)
Initializes mobile object.
virtual void initializeStillObject ()
Initializes still object.
void createPermanentNetObject (uint8_t props, uint16_t oid)
Creates local permanent NetObject.
void createVolatileNetObject (uint8_t props)
Creates local volatile NetObject.
void replicateVolatileNetObject (uint8_t props, class Noid _noid)
Replicate distant volatile NetObject.
virtual void enableBehavior (uint32_t flag)
Enables behavior.
virtual void disableBehavior (uint32_t flag)
Disables behavior.
virtual bool isBehavior (uint32_t flag) const
Checks weither this behavior is on.
virtual bool bbBehavior () const
Checks weither BBox behavior is on.
virtual bool isSeen ()
Checks weither the object is in the sight view of the user.
virtual void setVisible (bool flag)
Sets visible or not the 3D object.
virtual bool isVisible ()
Checks weither the object is visible.
virtual void setFlashy (float *color)
Sets flashy the 3D object.
virtual void setFlashy ()
Sets flashy the 3D object.
virtual void resetFlashy ()
Resets flashy the 3D object.
virtual void setRay (GLint wx, GLint wy)
virtual void resetRay ()
Resets Ray on the 3D object.
virtual void setReflexive (bool flag)
virtual bool isSelectable () const
Checks weither 3D selectable behavior is on.
virtual uint32_t collideBehavior () const
Returns collide behavior.
virtual void setRenderPrior (uint8_t _prior)
Sets render priority.
virtual uint8_t getRenderPrior () const
Gets render priority.
void generalIntersect (WObject *pold, OList *vicinityList)
General intersection of objects.
bool ingoingNeighbor (WObject *pold, WObject *neighbor)
bool outgoingNeighbor (WObject *pold, WObject *neighbor)
Checks ingoing intersection with a neighbor.
void ingoingWalls (WObject *pold)
Checks outgoing intersection with a neighbor.
virtual void copyPosAndBB (Pos &newpos)
Checks ingoing intersection with walls.
virtual void copyPositionAndBB (WObject *o)
Copy object position and Bounding Box.
virtual bool projectPosition (WObject *pcur, WObject *pold)
Projects object position.
virtual int projectPositionOnObstacle (Pos &pcur, Pos &pold, Pos &obstacle)
Projects object position on an obstacle.
virtual void initPosition ()
Init 3D and grid position.
virtual void updatePosition ()
Updating 3D.
virtual void updatePositionAndGrid (Pos &oldpos)
Updating 3D and grid position.
virtual void updatePositionAndGrid (WObject *pold)
Updating 3D and grid position.
virtual void computeNormal (WObject *mobil, V3 *normal)
Computes the normal of an object.
virtual void computeNormal (Pos &mobil, Pos &stil, V3 *normal)
Computes the normal of still object.
virtual void bounceTrajectory (WObject *pold, V3 *norm)
Intersects with wall.
void getProperty (uint8_t prop_id, class Payload *pp)
Gets the local copy property from the payload (pp->data).
void putProperty (uint8_t prop_id, class Payload *pp)
Puts the local copy property in the payload.
virtual void deleteReplica ()
Deletes a replicated object.
virtual struct GuiItem * getGui () const
Gets the GUI handle.
virtual bool isGui () const
Checks the GUI handle.
virtual void resetGui ()
Resets the GUI handle.
virtual void clearObjectBar ()
Clears the ObjectBar in the GUI.
virtual void specialAction (int action, void *data, time_t sec, time_t usec)
Calls methods dedicated to each object.
void getObjectHumanName (char **classname, char **instancename, char **actionnames)
Gives object's class_name & action names.
virtual void getMySqlPosition ()
Checks if position is managed by MySql and get it.
virtual void updateMySqlPosition ()
Checks if position is managed by MySql and update it.
virtual int16_t getMySqlState ()
Gets state from MySql.
virtual void updateMySqlPosZ ()
Checks if posZ is managed by MySql.
virtual void updateMySqlState (int16_t state)
Updates state for MySql.
virtual void flushMySqlPosition ()
Flushes position for MySql.
virtual void quitMySql ()
Quits MySql.
Static Public Member Functions
static void funcs ()
init funclist
static WObject * replicator (uint8_t type_id, Noid noid, Payload *pp)
Replicates a ball coming from the Network.
static WObject *() creator (char *l)
Creates a ball defined in a file.
Static Public Member Functions inherited from WObject
static int interAABB (V3 center1, V3 size1, V3 center2, V3 size2)
Computes intersection between 2 AABB (Axis Aligned Bounding Box).
static int interAABBVertical (V3 center1, V3 size1, V3 center2, V3 size2)
static int interAABBHorizontal (V3 center1, V3 size1, V3 center2, V3 size2)
static void show (const char *name)
Snaps position (debug).
static WObject * byNum (uint16_t num)
static void moveObject (WObject *po, void *d, time_t s, time_t u)
User moves the object.
static void getObjectNameById (uint8_t type_id, char *name)
Gets a name by its id.
static void resetObjectsNumber ()
Resets object seq.
static uint32_t getObjectsNumber ()
Gets current object sequence number.
Static Public Attributes
static const float LSPEED = 5.0
static const float ZSPEED = 3.0
static const float ASPEED = -1.5
static const float ORIGZ = 1.0
static const float DENSITY = 0.1
static const float RADIUS = 0.1
static const float SHIFTX = 1.0
static const float SHIFTY = 1.0
static const float DELTAZ = 0.02
static const float TTL = 3.0
static const OClass oclass
class variable
Private Member Functions
virtual void defaults ()
Sets defaults values.
virtual void parser (char *l)
Parses fileline.
virtual void makeSolid ()
Builds solid geometry.
virtual void setName ()
Sets an implicited name.
virtual void push ()
virtual void pull ()
virtual void shoot ()
virtual void up ()
virtual void take ()
virtual void drop ()
virtual void turn ()
virtual void destroy ()
Static Private Member Functions
static void push_cb (Ball *o, void *d, time_t s, time_t u)
static void pull_cb (Ball *o, void *d, time_t s, time_t u)
static void shoot_cb (Ball *o, void *d, time_t s, time_t u)
static void up_cb (Ball *o, void *d, time_t s, time_t u)
static void take_cb (Ball *o, void *d, time_t s, time_t u)
static void drop_cb (Ball *o, void *d, time_t s, time_t u)
static void turn_cb (Ball *o, void *d, time_t s, time_t u)
static void destroy_cb (Ball *o, void *d, time_t s, time_t u)
static void create_cb (class Cauldron *c, void *d, time_t s, time_t u)
Creation: this method is invisible: called by the cauldron or user.
static void recreate_cb (class World *w, void *d, time_t s, time_t u)
Creation: this method is invisible: called by the World.
Private Attributes
float lspeed
linear speed in xy
float aspeed
angular speed
float zspeed
linear speed in z
float gravity
gravity in z
float ttl
time to live
float origz
position at creation
bool taken
taken or not by an user
Additional Inherited Members
Public Attributes inherited from WObject
solidList _solids
list of solids.
class NetObject * noh
reserved field for network.
struct GuiItem * guip
reserved field for GUI.
uint8_t type
object type.
uint8_t mode
object world mode.
uint16_t num
object sequence number.
uint32_t behavior
behavior flags.
Names names
names.
Pos pos
position in the space.
Move move
movement specific.
class WObjectId noid
WObject Id.
bool is_in_a_list
true if it is already in an OList.
bool removed
flag removed or not.
int16_t state
current state.
int8_t prior
render priority.
char * geometry
geometry string.
class Solid * solid
solid pointer
char chan [CHAN_LEN]
channel.
class Flare * flare
flare instance
Static Protected Member Functions inherited from WObject
static void get_xy (WObject *po, class Payload *pp)
static void get_z (WObject *po, class Payload *pp)
static void get_az (WObject *po, class Payload *pp)
static void get_ay (WObject *po, class Payload *pp)
static void get_ax (WObject *po, class Payload *pp)
static void get_hname (WObject *po, class Payload *pp)
static void put_xy (WObject *po, class Payload *pp)
static void put_z (WObject *po, class Payload *pp)
static void put_az (WObject *po, class Payload *pp)
static void put_ay (WObject *po, class Payload *pp)
static void put_ax (WObject *po, class Payload *pp)
static void put_hname (WObject *po, class Payload *pp)
Protected Attributes inherited from WObject
bool objectbar
true if object bar is active.
Detailed Description
Ball class.
Definition at line 33 of file ball.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
PROPHNAME
PROPXY
PROPZ
PROPAZ
PROPAX
PROPAY
PROPS
Definition at line 57 of file ball.hpp.
anonymous enum
anonymous enum
Enumerator
PUSH
forward
PULL
backward
SHOOT
shoot
UP
move up
TAKE
take
DROP
drop
TURN
turn
KILL
destroy
CREATE
create
RECREATE
create
NONE
Definition at line 68 of file ball.hpp.
Constructor & Destructor Documentation
Ball() [1/5]
Ball::Ball (class WObject * o, void * d, time_t s, time_t u)
constructor: called by cauldron.
Created by the cauldron or user.
Definition at line 119 of file ball.cpp.
References WObject::createVolatileNetObject(), defaults(), drand48, WObject::enableBehavior(), WObject::enablePermanentMovement(), WObject::initializeMobileObject(), makeSolid(), origz, ORIGZ, PERSISTENT, WObject::pos, PROPS, WObject::RENDER_HIGH, setName(), WObject::setRenderPrior(), TTL, Pos::x, Pos::y, and Pos::z.
Referenced by create_cb(), creator(), recreate_cb(), and replicator().
Ball() [2/5]
Ball::Ball (class World * w, void * d, time_t s, time_t u)
constructor: called by world.
Recreated by the world.
Definition at line 143 of file ball.cpp.
References WObject::createVolatileNetObject(), d, DBG_SQL, defaults(), WObject::enableBehavior(), WObject::enablePermanentMovement(), WObject::initializeMobileObject(), makeSolid(), Names::named, WObject::names, oid, PERSISTENT, PROPS, trace(), and TTL.
Ball() [3/5]
Ball::Ball (uint8_t type_id, Noid noid, Payload * pp)
constructor: network replication.
Definition at line 193 of file ball.cpp.
References WObject::copyNoid(), defaults(), NetObject::getAllProperties(), WObject::initializeMobileObject(), makeSolid(), WObject::noh, PROPS, WObject::replicateVolatileNetObject(), and WObject::setType().
Ball() [4/5]
Ball::Ball (WObject * user, char * form)
constructor: created by user.
Created by the user.
Definition at line 167 of file ball.cpp.
References WObject::createVolatileNetObject(), defaults(), WObject::enableBehavior(), WObject::initializeMobileObject(), WObject::parse(), Parse::parseSolid(), PERSISTENT, WObject::pos, PROPS, SEP, setName(), TTL, WObject::updatePosition(), Pos::x, Pos::y, and Pos::z.
Ball() [5/5]
Ball::Ball (char * l)
constructor: fileline.
Create from fileline.
Definition at line 107 of file ball.cpp.
References WObject::createVolatileNetObject(), WObject::enableBehavior(), WObject::initializeMobileObject(), parser(), PERSISTENT, PROPS, WObject::RENDER_NORMAL, and WObject::setRenderPrior().
Member Function Documentation
changePermanent()
void Ball::changePermanent (float lasting) virtual
Does permanent position changes.
Permanent movements.
Reimplemented from WObject.
Definition at line 243 of file ball.cpp.
References gravity, WObject::pos, and Pos::z.
changePosition()
void Ball::changePosition (float lasting) virtual
Does any position changes.
Imposed movements.
Reimplemented from WObject.
Definition at line 218 of file ball.cpp.
References Move::aspeed, Pos::ax, Pos::az, Cos(), localuser, Move::lspeed, WObject::move, WObject::pos, ratio, Sin(), taken, V3::v, Pos::x, Pos::y, and Pos::z.
create_cb()
void Ball::create_cb (class Cauldron * c, void * d, time_t s, time_t u) static private
Creation: this method is invisible: called by the cauldron or user.
Definition at line 52 of file ball.cpp.
References Ball(), and d.
Referenced by funcs().
creator()
WObject * Ball::creator (char * l) static
Creates a ball defined in a file.
Definition at line 64 of file ball.cpp.
References Ball().
defaults()
void Ball::defaults () private virtual
Sets defaults values.
Definition at line 69 of file ball.cpp.
References aspeed, ASPEED, gravity, GRAVITY, lspeed, LSPEED, taken, ttl, TTL, zspeed, and ZSPEED.
Referenced by Ball(), and parser().
destroy()
void Ball::destroy () private virtual
Definition at line 367 of file ball.cpp.
References WObject::clearObjectBar(), taken, and WObject::toDelete().
Referenced by destroy_cb().
destroy_cb()
void Ball::destroy_cb (Ball * o, void * d, time_t s, time_t u) static private
Definition at line 389 of file ball.cpp.
References destroy().
Referenced by funcs().
drop()
void Ball::drop () private virtual
Definition at line 349 of file ball.cpp.
References WObject::enablePermanentMovement(), WObject::initImposedMovement(), taken, and ttl.
Referenced by drop_cb().
drop_cb()
void Ball::drop_cb (Ball * o, void * d, time_t s, time_t u) static private
Definition at line 387 of file ball.cpp.
References drop().
Referenced by funcs().
funcs()
void Ball::funcs () static
init funclist
Definition at line 391 of file ball.cpp.
References BALL_TYPE, CREATE, create_cb(), destroy_cb(), DROP, drop_cb(), WObject::get_ax(), WObject::get_ay(), WObject::get_az(), WObject::get_hname(), WObject::get_xy(), WObject::get_z(), getPropertyFunc(), KILL, PROPAX, PROPAY, PROPAZ, PROPHNAME, PROPXY, PROPZ, PULL, pull_cb(), PUSH, push_cb(), WObject::put_ax(), WObject::put_ay(), WObject::put_az(), WObject::put_hname(), WObject::put_xy(), WObject::put_z(), putPropertyFunc(), RECREATE, recreate_cb(), setActionFunc(), SHOOT, shoot_cb(), TAKE, take_cb(), TURN, turn_cb(), UP, up_cb(), WO_ACTION, and WO_PAYLOAD.
getOClass()
virtual const OClass* Ball::getOClass () inline virtual
Reimplemented from WObject.
Definition at line 86 of file ball.hpp.
References oclass.
isMoving()
bool Ball::isMoving () virtual
Checks if object is moving.
Reimplemented from WObject.
Definition at line 211 of file ball.cpp.
References taken, and WObject::testMoving().
makeSolid()
void Ball::makeSolid () private virtual
Builds solid geometry.
Solid geometry.
Definition at line 87 of file ball.cpp.
References DEF_URL_BALL, WObject::parse(), Parse::parseSolid(), RADIUS, and SEP.
Referenced by Ball().
parser()
void Ball::parser (char * l) private virtual
Parses fileline.
Parse fileline.
Definition at line 95 of file ball.cpp.
References begin_while_parse, defaults(), end_while_parse, WObject::parse(), Parse::parseAttributes(), and WObject::tokenize().
Referenced by Ball().
pull()
void Ball::pull () private virtual
Definition at line 304 of file ball.cpp.
References aspeed, Move::aspeed, Pos::az, clearV3(), Cos(), WObject::initImposedMovement(), localuser, lspeed, Move::lspeed, WObject::move, WObject::pos, ratio, Sin(), taken, ttl, TTL, and V3::v.
Referenced by pull_cb().
pull_cb()
void Ball::pull_cb (Ball * o, void * d, time_t s, time_t u) static private
Definition at line 383 of file ball.cpp.
References pull().
Referenced by funcs().
push()
void Ball::push () private virtual
Definition at line 291 of file ball.cpp.
References aspeed, Move::aspeed, Pos::az, clearV3(), Cos(), WObject::initImposedMovement(), localuser, lspeed, Move::lspeed, WObject::move, WObject::pos, ratio, Sin(), taken, ttl, TTL, and V3::v.
Referenced by push_cb().
push_cb()
void Ball::push_cb (Ball * o, void * d, time_t s, time_t u) static private
Definition at line 382 of file ball.cpp.
References push().
Referenced by funcs().
quit()
void Ball::quit () virtual
Quits.
Reimplemented from WObject.
Definition at line 377 of file ball.cpp.
References WObject::flushMySqlPosition().
recreate_cb()
void Ball::recreate_cb (class World * w, void * d, time_t s, time_t u) static private
Creation: this method is invisible: called by the World.
Definition at line 58 of file ball.cpp.
References Ball(), and d.
Referenced by funcs().
replicator()
WObject * Ball::replicator (uint8_t type_id, Noid noid, Payload * pp) static
Replicates a ball coming from the Network.
Replication from the network.
Definition at line 188 of file ball.cpp.
References Ball(), and WObject::noid.
setName()
void Ball::setName () private virtual
Sets an implicited name.
Sets name.
Definition at line 80 of file ball.cpp.
References BALL_NAME, WObject::getInstance(), localuser, Names::named, WObject::names, and oid.
Referenced by Ball().
shoot()
void Ball::shoot () private virtual
Definition at line 317 of file ball.cpp.
References aspeed, Move::aspeed, Pos::az, clearV3(), Cos(), WObject::initImposedMovement(), localuser, lspeed, Move::lspeed, WObject::move, WObject::pos, ratio, Sin(), taken, ttl, TTL, V3::v, and zspeed.
Referenced by shoot_cb().
shoot_cb()
void Ball::shoot_cb (Ball * o, void * d, time_t s, time_t u) static private
Definition at line 384 of file ball.cpp.
References shoot().
Referenced by funcs().
take()
void Ball::take () private virtual
Definition at line 341 of file ball.cpp.
References WObject::disablePermanentMovement(), WObject::initImposedMovement(), MAXFLOAT, taken, and ttl.
Referenced by take_cb().
take_cb()
void Ball::take_cb (Ball * o, void * d, time_t s, time_t u) static private
Definition at line 386 of file ball.cpp.
References take().
Referenced by funcs().
turn()
void Ball::turn () private virtual
Definition at line 357 of file ball.cpp.
References aspeed, Move::aspeed, clearV3(), WObject::initImposedMovement(), Move::lspeed, WObject::move, ratio, ttl, TTL, and V3::v.
Referenced by turn_cb().
turn_cb()
void Ball::turn_cb (Ball * o, void * d, time_t s, time_t u) static private
Definition at line 388 of file ball.cpp.
References turn().
Referenced by funcs().
up()
void Ball::up () private virtual
Definition at line 330 of file ball.cpp.
References aspeed, Move::aspeed, clearV3(), WObject::initImposedMovement(), Move::lspeed, WObject::move, ratio, ttl, TTL, V3::v, and zspeed.
Referenced by up_cb().
up_cb()
void Ball::up_cb (Ball * o, void * d, time_t s, time_t u) static private
Definition at line 385 of file ball.cpp.
References up().
Referenced by funcs().
updateTime()
void Ball::updateTime (time_t s, time_t u, float * lasting) virtual
Updates times.
Reimplemented from WObject.
Definition at line 206 of file ball.cpp.
References WObject::updateLasting().
updateToNetwork()
bool Ball::updateToNetwork (const Pos & oldpos) virtual
Publishes to network.
Updates to the network.
Reimplemented from WObject.
Definition at line 249 of file ball.cpp.
References PROPAX, PROPAY, PROPAZ, PROPXY, PROPZ, and WObject::updatePosToNetwork().
whenIntersect()
bool Ball::whenIntersect (WObject * pcur, WObject * pold) virtual
Handles collisions.
Intersects with an other object.
Reimplemented from WObject.
Definition at line 255 of file ball.cpp.
References Pos::az, BALL_TYPE, WObject::copyPositionAndBB(), Cos(), drand48, WObject::initImposedMovement(), lspeed, Move::lspeed, WObject::move, WObject::pos, RADIUS, Sin(), STEP_TYPE, taken, ttl, WObject::type, WObject::updatePositionAndGrid(), USER_TYPE, V3::v, Pos::x, and Pos::y.
whenWallsIntersect()
void Ball::whenWallsIntersect (WObject * pold, V3 * norm) virtual
Handles collisions with a wall.
Intersects with walls.
Reimplemented from WObject.
Definition at line 285 of file ball.cpp.
References WObject::bounceTrajectory(), COLLIDE_ONCE, and WObject::enableBehavior().
Member Data Documentation
aspeed
float Ball::aspeed private
angular speed
Definition at line 37 of file ball.hpp.
Referenced by defaults(), pull(), push(), shoot(), turn(), and up().
ASPEED
const float Ball::ASPEED = -1.5 static
Definition at line 47 of file ball.hpp.
Referenced by defaults().
DELTAZ
const float Ball::DELTAZ = 0.02 static
Definition at line 53 of file ball.hpp.
Referenced by Water::whenIntersect().
DENSITY
const float Ball::DENSITY = 0.1 static
Definition at line 49 of file ball.hpp.
gravity
float Ball::gravity private
gravity in z
Definition at line 39 of file ball.hpp.
Referenced by changePermanent(), and defaults().
lspeed
float Ball::lspeed private
linear speed in xy
Definition at line 36 of file ball.hpp.
Referenced by defaults(), pull(), push(), shoot(), and whenIntersect().
LSPEED
const float Ball::LSPEED = 5.0 static
Definition at line 45 of file ball.hpp.
Referenced by defaults().
oclass
const OClass Ball::oclass static
class variable
Definition at line 82 of file ball.hpp.
Referenced by getOClass().
origz
float Ball::origz private
position at creation
Definition at line 41 of file ball.hpp.
Referenced by Ball().
ORIGZ
const float Ball::ORIGZ = 1.0 static
Definition at line 48 of file ball.hpp.
Referenced by Ball().
RADIUS
const float Ball::RADIUS = 0.1 static
Definition at line 50 of file ball.hpp.
Referenced by makeSolid(), whenIntersect(), and Cauldron::whenIntersect().
SHIFTX
const float Ball::SHIFTX = 1.0 static
Definition at line 51 of file ball.hpp.
Referenced by User::whenIntersect().
SHIFTY
const float Ball::SHIFTY = 1.0 static
Definition at line 52 of file ball.hpp.
Referenced by User::whenIntersect().
taken
bool Ball::taken private
taken or not by an user
Definition at line 42 of file ball.hpp.
Referenced by changePosition(), defaults(), destroy(), drop(), isMoving(), pull(), push(), shoot(), take(), and whenIntersect().
ttl
float Ball::ttl private
time to live
Definition at line 40 of file ball.hpp.
Referenced by defaults(), drop(), pull(), push(), shoot(), take(), turn(), up(), and whenIntersect().
TTL
const float Ball::TTL = 3.0 static
Definition at line 54 of file ball.hpp.
Referenced by Ball(), defaults(), pull(), push(), shoot(), turn(), and up().
zspeed
float Ball::zspeed private
linear speed in z
Definition at line 38 of file ball.hpp.
Referenced by defaults(), shoot(), and up().
ZSPEED
const float Ball::ZSPEED = 3.0 static
Definition at line 46 of file ball.hpp.
Referenced by defaults().
The documentation for this class was generated from the following files:
src/wo/ball.hpp
src/wo/ball.cpp