VREng: TriFace Class Reference
TriFace Class Reference
TriFace class.
#include <hairs.hpp>
Public Member Functions
void normal ()
void put (int pdata)
void draw (int pdata)
Public Attributes
HVertex * v [3]
Vector3 n
Material * m
Detailed Description
TriFace class.
Definition at line 108 of file hairs.hpp.
Member Function Documentation
draw()
void TriFace::draw (int pdata)
Definition at line 635 of file hairs.cpp.
References put().
normal()
void TriFace::normal ()
Definition at line 721 of file hairs.cpp.
References Vector3::crossProduct(), n, Vector3::normalize(), HVertex::p, and v.
Referenced by Hairs::httpReader().
put()
void TriFace::put (int pdata)
Definition at line 628 of file hairs.cpp.
References HVertex::put(), and v.
Referenced by Surface::draw(), and draw().
Member Data Documentation
m
Material* TriFace::m
Definition at line 112 of file hairs.hpp.
Referenced by Hairs::httpReader().
n
Vector3 TriFace::n
Definition at line 111 of file hairs.hpp.
Referenced by Hairs::httpReader(), and normal().
v
HVertex* TriFace::v[3]
Definition at line 110 of file hairs.hpp.
Referenced by Surface::draw(), Hairs::httpReader(), Hair::init(), normal(), and put().
The documentation for this class was generated from the following files:
src/wo/hairs.hpp
src/wo/hairs.cpp