VREng: Icon Class Reference
Icon Class Reference
Icon class.
#include <icon.hpp>
Public Types
enum {
PROPHNAME, PROPXY, PROPZ, PROPAZ,
PROPAX, PROPAY, PROPURL, PROPTEX,
PROPGNAME, PROPS
}
enum {
OPEN, SAVE, PIN, LEAVE,
CARRY, KILL, PUSH, PULL,
DROP, TURN, MOVE, CREATE,
STICK, NONE
}
Public Types inherited from WObject
enum {
STILL, MOBILE, EPHEMERAL, INVISIBLE,
MOBILEINVISIBLE, MODE_MAX
}
enum {
DELETED = -1, NONE = 0, INACTIVE = 0, ACTIVE,
PLAYING, TAKEN, DROPPED, MOVED,
CARRYING, IN_CART, ENDSTATE
}
enum { RENDER_LOW, RENDER_NORMAL, RENDER_HIGH }
typedef std::list< class Solid * > solidList
Public Member Functions
virtual const OClass * getOClass ()
Icon (class User *pu, void *data)
constructor: called by GUI
Icon (uint8_t type_id, Noid noid, Payload *pp)
constructor: network replication
virtual bool isMoving ()
Checks if object is moving.
virtual void changePosition (float lasting)
Does any position changes.
virtual void changePermanent (float lasting)
Does permanent position changes.
virtual void updateTime (time_t, time_t, float *)
Updates times.
virtual bool updateToNetwork (const Pos &oldpos)
Publishes to network.
virtual bool whenIntersect (WObject *pcur, WObject *pold)
Handles collisions.
virtual void quit ()
Quits.
Public Member Functions inherited from WObject
WObject ()
Constructor.
virtual ~WObject ()
Destructor.
virtual uint8_t typeId ()
Abstrct class.
virtual const char * typeName ()
WCreator * getCreator ()
WReplicator * getReplicator ()
virtual bool updatePosToNetwork (const Pos &oldpos, int propxy, int propz, int propaz, int propax, int propay)
Publishes position changes to the network.
virtual bool whenIntersectOut (WObject *pcur, WObject *pold)
Handles an outgoing collision with another object.
virtual void whenWallsIntersect (WObject *pold, V3 *norm)
Handles collisions with walls.
virtual void render ()
Makes special rendering.
virtual void lighting ()
Makes special lighting.
const solidList & solids () const
solidlist address.
uint32_t countOfSolids () const
virtual class Solid * getSolid () const
Returns first solid.
virtual void addSolid (class Solid *solid)
Adds to solidList.
virtual void deleteSolids ()
Deletes solids from solidList.
virtual int interAABB (WObject *o1, WObject *o2)
virtual bool haveAction ()
Checks weither have actions.
virtual uint8_t numberAction ()
Number of actions.
virtual bool runAction (const char *action)
Runs action everwhere if available.
virtual void setType (int type)
Sets object type.
virtual int getType ()
Gets object type.
virtual int getNumber ()
Gets object number.
virtual uint16_t getNum ()
Gets a new object number.
virtual void getPosition (M4 &mpos)
Gives solid's position.
virtual void getRelativeBB (V3 &center, V3 &size)
virtual void getDim (V3 &dim)
virtual void getCenter (V3 &center)
virtual void getAbsoluteBB (V3 &center, V3 &size)
Gets relative or absolute center and size of solid.
virtual uint8_t getFrames ()
Gets number of frames of this solid.
virtual uint8_t getFrame ()
Gets index of current frame of this solid.
virtual void setFrame (uint8_t _frame)
Sets current frame.
virtual bool isValid () const
Checks if valid object type.
virtual bool isPermanent () const
Checks if permanent object.
virtual const char * named () const
Gets names.named.
virtual const char * getInstance () const
Gets names.instance.
virtual const char * urlName () const
Gets names.url.
virtual const char * ownerName () const
Gets names.owner.
virtual const char * worldName () const
Gets names.owner.
virtual bool explicitName () const
Checks wether the object is explicitly named.
virtual void toDelete ()
Delete this object latter.
virtual bool removeFromScene ()
Removes an object.
virtual bool isOwner () const
Returns true if owner.
virtual void setOwner (const char *_owner)
Initialize owner.
virtual void setOwner ()
Initialize local user as owner.
virtual void click (GLint x, GLint y)
Execute an object's click method if it's defined.
virtual void click (V3 norm)
Intercepts a click.
virtual char * tokenize (char *l)
Tokenizes the line <object ...
virtual Parse * parse ()
Gets current parse.
void setWObjectId ()
Sets the WObjectid.
void copyNoid (class Noid _noid)
Copies the NetObjectid in WObjectId.
void setSrcId (uint32_t src_id)
Sets the SrcId.
void setPortId (uint16_t port_id)
Sets the PortId.
void setObjId (uint16_t obj_id)
Sets the ObjId.
uint32_t getSrcId () const
Gets the SrcId.
uint16_t getPortId () const
Gets the PortId.
uint16_t getObjId () const
Gets the ObjId.
virtual void update3D (Pos &pos)
Updates object in the 3D.
virtual void updateAll3D (Pos &pos)
Updates object in the 3D.
virtual void updateCamera (Pos &pos)
Updates camera in the 3D.
virtual void getSurfVecs (Pos &pos, V3 *v, V3 *w, V3 *norm)
Returns two vectors that describe the object's surface and a normal vector to that surface.
virtual void updateBB ()
Updates object's Bounding Box.
virtual void getMaterials (GLfloat *dif, GLfloat *amb, GLfloat *spe, GLfloat *emi, GLint *shi, GLfloat *alpha)
virtual void insertIntoGrid ()
Adds an object into the grid.
virtual void deleteFromGrid ()
Deletes an object from the grid.
virtual void updateGrid (const float *bbminnew, const float *bbmaxnew, const float *bbminold, const float *bbmaxold)
Updates an object in the grid.
virtual void updateGrid (const Pos &oldpos)
virtual void updateGrid (const WObject *pold)
Updates an object into the grid.
virtual void addToList (std::list< WObject * > &olist)
virtual OList * addToList (OList *olist)
Adds an object pointer into a olist.
virtual void addToList ()
Adds an object pointer into a olist.
virtual void addToStill ()
Adds an object pointer into stillList.
virtual void addToMobile ()
Adds an object pointer into mobileList.
virtual void addToInvisible ()
Adds an object pointer into invisibleList.
virtual void addToRender ()
Adds an object pointer into renderList.
virtual void delFromMobile ()
Deletes an object pointer from mobileList.
virtual void clearList ()
Clears an olist.
virtual void clearList (std::list< WObject * > &olist)
Clears an olist.
virtual void addToListOnce (std::list< WObject * > &olist)
virtual OList * addToListOnce (OList *olist)
Adds an object pointer into a list only once time.
virtual void delFromList (std::list< WObject * > &olist)
virtual OList * delFromList (OList *olist)
Deletes an object pointer from a olist.
virtual void delFromList ()
Deletes an object pointer from a olist.
virtual OList * getVicinityList (const WObject *pold)
Returns list of pointers on objects touching cell where is the object.
virtual OList * addListToList (OList *list1, OList *list2)
Concatenation (test of "ispointed") of list pointers on an object.
virtual bool isStill ()
Checks an object exists in the stilllist.
virtual bool isMobile ()
virtual bool isEphemeral ()
Checks an object exists in the mobilelist.
virtual WObject * byWObject (WObject *po)
Gets a WObject from the lists.
virtual void checkVicinity (WObject *pold)
< Gets an object by its num.
virtual void imposedMovement (time_t sec, time_t usec)
Handles an object movement.
virtual void elementaryImposedMovement (float lasting)
Handles an elementary object movement.
virtual void enableImposedMovement ()
Enables movement on an object.
virtual void enablePermanentMovement ()
Enables permanent movement on an object.
virtual void disablePermanentMovement ()
Disables movement on an object.
virtual void enablePermanentMovement (float speed)
Enables permanent movement on an object.
virtual void initImposedMovement (float lasting)
Initializes movement on an object.
virtual float diffTime (time_t sec, time_t usec)
Updates times on an object.
virtual void stopImposedMovement ()
Stops a movement on an object.
virtual void permanentMovement (time_t sec, time_t usec)
Handles a permanent object movement.
virtual void elementaryPermanentMovement (float lasting)
Handles an elementary permanent object movement.
virtual void setLasting (float maxlast)
Sets the max lasting time of an object.
virtual float getLasting () const
Gets the lasting time of an object.
virtual bool testMoving ()
Tests if object is moving.
virtual bool updateLasting (time_t sec, time_t usec, float *lasting)
Updates remaining times of the movement.
virtual void moveUserToObject (float val, float _lttl, float _attl)
Moves the user to the object.
virtual void setObjectName (const char *str)
Sets an object name.
virtual WObject * getObjectByName (const char *str)
Gets an object by its name.
virtual void updateNames ()
Updates names.
virtual void initializeObject (uint8_t mode)
Initializes object.
virtual void initializeMobileObject (float last)
virtual void initializeEphemeralObject (float last)
Initializes mobile object.
virtual void initializeStillObject ()
Initializes still object.
void createPermanentNetObject (uint8_t props, uint16_t oid)
Creates local permanent NetObject.
void createVolatileNetObject (uint8_t props)
Creates local volatile NetObject.
void replicateVolatileNetObject (uint8_t props, class Noid _noid)
Replicate distant volatile NetObject.
virtual void enableBehavior (uint32_t flag)
Enables behavior.
virtual void disableBehavior (uint32_t flag)
Disables behavior.
virtual bool isBehavior (uint32_t flag) const
Checks weither this behavior is on.
virtual bool bbBehavior () const
Checks weither BBox behavior is on.
virtual bool isSeen ()
Checks weither the object is in the sight view of the user.
virtual void setVisible (bool flag)
Sets visible or not the 3D object.
virtual bool isVisible ()
Checks weither the object is visible.
virtual void setFlashy (float *color)
Sets flashy the 3D object.
virtual void setFlashy ()
Sets flashy the 3D object.
virtual void resetFlashy ()
Resets flashy the 3D object.
virtual void setRay (GLint wx, GLint wy)
virtual void resetRay ()
Resets Ray on the 3D object.
virtual void setReflexive (bool flag)
virtual bool isSelectable () const
Checks weither 3D selectable behavior is on.
virtual uint32_t collideBehavior () const
Returns collide behavior.
virtual void setRenderPrior (uint8_t _prior)
Sets render priority.
virtual uint8_t getRenderPrior () const
Gets render priority.
void generalIntersect (WObject *pold, OList *vicinityList)
General intersection of objects.
bool ingoingNeighbor (WObject *pold, WObject *neighbor)
bool outgoingNeighbor (WObject *pold, WObject *neighbor)
Checks ingoing intersection with a neighbor.
void ingoingWalls (WObject *pold)
Checks outgoing intersection with a neighbor.
virtual void copyPosAndBB (Pos &newpos)
Checks ingoing intersection with walls.
virtual void copyPositionAndBB (WObject *o)
Copy object position and Bounding Box.
virtual bool projectPosition (WObject *pcur, WObject *pold)
Projects object position.
virtual int projectPositionOnObstacle (Pos &pcur, Pos &pold, Pos &obstacle)
Projects object position on an obstacle.
virtual void initPosition ()
Init 3D and grid position.
virtual void updatePosition ()
Updating 3D.
virtual void updatePositionAndGrid (Pos &oldpos)
Updating 3D and grid position.
virtual void updatePositionAndGrid (WObject *pold)
Updating 3D and grid position.
virtual void computeNormal (WObject *mobil, V3 *normal)
Computes the normal of an object.
virtual void computeNormal (Pos &mobil, Pos &stil, V3 *normal)
Computes the normal of still object.
virtual void bounceTrajectory (WObject *pold, V3 *norm)
Intersects with wall.
void getProperty (uint8_t prop_id, class Payload *pp)
Gets the local copy property from the payload (pp->data).
void putProperty (uint8_t prop_id, class Payload *pp)
Puts the local copy property in the payload.
virtual void deleteReplica ()
Deletes a replicated object.
virtual struct GuiItem * getGui () const
Gets the GUI handle.
virtual bool isGui () const
Checks the GUI handle.
virtual void resetGui ()
Resets the GUI handle.
virtual void clearObjectBar ()
Clears the ObjectBar in the GUI.
virtual void specialAction (int action, void *data, time_t sec, time_t usec)
Calls methods dedicated to each object.
void getObjectHumanName (char **classname, char **instancename, char **actionnames)
Gives object's class_name & action names.
virtual void getMySqlPosition ()
Checks if position is managed by MySql and get it.
virtual void updateMySqlPosition ()
Checks if position is managed by MySql and update it.
virtual int16_t getMySqlState ()
Gets state from MySql.
virtual void updateMySqlPosZ ()
Checks if posZ is managed by MySql.
virtual void updateMySqlState (int16_t state)
Updates state for MySql.
virtual void flushMySqlPosition ()
Flushes position for MySql.
virtual void quitMySql ()
Quits MySql.
Static Public Member Functions
static void funcs ()
init funclist
static WObject * replicator (uint8_t type_id, Noid noid, Payload *pp)
Replicates a icon coming from the Network.
Static Public Member Functions inherited from WObject
static int interAABB (V3 center1, V3 size1, V3 center2, V3 size2)
Computes intersection between 2 AABB (Axis Aligned Bounding Box).
static int interAABBVertical (V3 center1, V3 size1, V3 center2, V3 size2)
static int interAABBHorizontal (V3 center1, V3 size1, V3 center2, V3 size2)
static void show (const char *name)
Snaps position (debug).
static WObject * byNum (uint16_t num)
static void moveObject (WObject *po, void *d, time_t s, time_t u)
User moves the object.
static void getObjectNameById (uint8_t type_id, char *name)
Gets a name by its id.
static void resetObjectsNumber ()
Resets object seq.
static uint32_t getObjectsNumber ()
Gets current object sequence number.
Public Attributes
enum Icon:: { ... } actions
Public Attributes inherited from WObject
solidList _solids
list of solids.
class NetObject * noh
reserved field for network.
struct GuiItem * guip
reserved field for GUI.
uint8_t type
object type.
uint8_t mode
object world mode.
uint16_t num
object sequence number.
uint32_t behavior
behavior flags.
Names names
names.
Pos pos
position in the space.
Move move
movement specific.
class WObjectId noid
WObject Id.
bool is_in_a_list
true if it is already in an OList.
bool removed
flag removed or not.
int16_t state
current state.
int8_t prior
render priority.
char * geometry
geometry string.
class Solid * solid
solid pointer
char chan [CHAN_LEN]
channel.
class Flare * flare
flare instance
Static Public Attributes
static const OClass oclass
class variable
Private Member Functions
virtual void parser (char *l)
Parses.
virtual void defaults ()
icon defaults
virtual void makeSolid ()
Builds solid geometry.
virtual char * getParam (char *ptok)
gets parameter
Static Private Member Functions
static void create (User *pu, void *d, time_t s, time_t u)
creation: this method is invisible: called by GUI::putIcon
static void stick (Wall *pwall, void *_picon, time_t s, time_t u)
static void pin (Icon *o, void *d, time_t s, time_t u)
static void push (Icon *o, void *d, time_t s, time_t u)
static void pull (Icon *o, void *d, time_t s, time_t u)
static void carry (Icon *o, void *d, time_t s, time_t u)
static void leave (Icon *o, void *d, time_t s, time_t u)
static void drop (Icon *o, void *d, time_t s, time_t u)
static void open (Icon *o, void *d, time_t s, time_t u)
static void save (Icon *o, void *d, time_t s, time_t u)
static void turn (Icon *o, void *d, time_t s, time_t u)
static void destroy (Icon *o, void *d, time_t s, time_t u)
static void get_url (Icon *o, Payload *pp)
static void put_url (Icon *o, Payload *pp)
static void get_tex (Icon *o, Payload *pp)
static void put_tex (Icon *o, Payload *pp)
static void get_gname (Icon *o, Payload *pp)
static void put_gname (Icon *o, Payload *pp)
Private Attributes
char * ifile
local input file
char * ofile
public output file
char * vref
vref entry to restore
float lspeed
linear speed in xy
float aspeed
angular speed
float zspeed
linear speed in z
bool remove
flag to remove
float ttl
time to live
bool taken
taken or not by an user
char * tex
texture of the icon
Static Private Attributes
static const float DEPTH = 0.03
static const float LSPEED = 1.0
static const float ZSPEED = 1.0
static const float ASPEED = M_PI_4
static const float TTL = 1.0
static const float WIDTH = 0.32
static const float HEIGHT = 0.32
Additional Inherited Members
Static Protected Member Functions inherited from WObject
static void get_xy (WObject *po, class Payload *pp)
static void get_z (WObject *po, class Payload *pp)
static void get_az (WObject *po, class Payload *pp)
static void get_ay (WObject *po, class Payload *pp)
static void get_ax (WObject *po, class Payload *pp)
static void get_hname (WObject *po, class Payload *pp)
static void put_xy (WObject *po, class Payload *pp)
static void put_z (WObject *po, class Payload *pp)
static void put_az (WObject *po, class Payload *pp)
static void put_ay (WObject *po, class Payload *pp)
static void put_ax (WObject *po, class Payload *pp)
static void put_hname (WObject *po, class Payload *pp)
Protected Attributes inherited from WObject
bool objectbar
true if object bar is active.
Detailed Description
Icon class.
Definition at line 35 of file icon.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
PROPHNAME
PROPXY
PROPZ
PROPAZ
PROPAX
PROPAY
PROPURL
PROPTEX
PROPGNAME
PROPS
last item = properties number
Definition at line 61 of file icon.hpp.
anonymous enum
anonymous enum
Enumerator
OPEN
open document
SAVE
save document
PIN
throw icon
LEAVE
leave here
CARRY
carry icon
KILL
remove icon
PUSH
push icon
PULL
pull icon
DROP
drop icon
TURN
turn
MOVE
position manipulation
CREATE
create icon
STICK
stick icon
NONE
Definition at line 75 of file icon.hpp.
Constructor & Destructor Documentation
Icon() [1/2]
Icon::Icon (class User * pu, void * data)
constructor: called by GUI
Definition at line 144 of file icon.cpp.
References access, Pos::az, carry(), File::closeFile(), Cos(), WObject::createVolatileNetObject(), d, DBG_WO, DEF_HTTP_SERVER, defaults(), WObject::disablePermanentMovement(), Cache::download(), WObject::enableBehavior(), error(), Texture::getEntryById(), Format::getExt(), Texture::getIdByUrl(), Format::getImgByExt(), WObject::getInstance(), getParam(), ICO_DEF, ifile, WObject::initializeMobileObject(), WObject::initImposedMovement(), M_PI_2, makeSolid(), MAXFLOAT, Names::named, WObject::names, NO_ELEMENTARY_MOVE, ofile, File::openFile(), WObject::ownerName(), parser(), pin(), WObject::pos, PROPS, push(), REMOVABLE, WObject::RENDER_HIGH, WObject::setOwner(), WObject::setRenderPrior(), Sin(), stringcmp(), taken, tex, trace(), ttl, Texture::url, Names::url, URL_LEN, WObject::urlName(), vref, Pos::x, Pos::y, and Pos::z.
Referenced by create(), and replicator().
Icon() [2/2]
Icon::Icon (uint8_t type_id, Noid noid, Payload * pp)
constructor: network replication
Definition at line 290 of file icon.cpp.
References WObject::copyNoid(), defaults(), NetObject::getAllProperties(), WObject::initializeMobileObject(), makeSolid(), Names::named, WObject::names, WObject::noh, WObject::parse(), Parse::parseName(), PROPS, WObject::replicateVolatileNetObject(), WObject::setType(), and taken.
Member Function Documentation
carry()
void Icon::carry (Icon * o, void * d, time_t s, time_t u) static private
Definition at line 395 of file icon.cpp.
References COLLIDE_NEVER, WObject::disableBehavior(), WObject::disablePermanentMovement(), WObject::initImposedMovement(), MAXFLOAT, WObject::resetFlashy(), taken, and ttl.
Referenced by funcs(), and Icon().
changePermanent()
void Icon::changePermanent (float lasting) virtual
Does permanent position changes.
permanent movements
Reimplemented from WObject.
Definition at line 88 of file icon.cpp.
References GRAVITY, WObject::pos, and Pos::z.
changePosition()
void Icon::changePosition (float lasting) virtual
Does any position changes.
Reimplemented from WObject.
Definition at line 68 of file icon.cpp.
References Move::aspeed, Pos::ax, Pos::az, Cos(), g, Times::getRate(), localuser, Move::lspeed, M_PI_2, MAX, WObject::move, WObject::pos, ratio, Sin(), taken, Global::times, V3::v, Pos::x, Pos::y, and Pos::z.
create()
void Icon::create (User * pu, void * d, time_t s, time_t u) static private
creation: this method is invisible: called by GUI::putIcon
Definition at line 94 of file icon.cpp.
References d, and Icon().
Referenced by funcs().
defaults()
void Icon::defaults () private virtual
icon defaults
Definition at line 99 of file icon.cpp.
References ASPEED, aspeed, LSPEED, lspeed, remove, TTL, ttl, ZSPEED, and zspeed.
Referenced by Icon().
destroy()
void Icon::destroy (Icon * o, void * d, time_t s, time_t u) static private
Definition at line 471 of file icon.cpp.
References Env::cwd(), Global::env, Cache::file(), g, Env::icons(), WObject::names, WObject::removeFromScene(), Names::url, URL_LEN, and WObject::worldName().
Referenced by funcs().
drop()
void Icon::drop (Icon * o, void * d, time_t s, time_t u) static private
Definition at line 416 of file icon.cpp.
References COLLIDE_ONCE, WObject::enableBehavior(), WObject::enablePermanentMovement(), WObject::initImposedMovement(), taken, and ttl.
Referenced by funcs().
funcs()
void Icon::funcs () static
init funclist
Definition at line 566 of file icon.cpp.
References CARRY, carry(), CREATE, create(), destroy(), DROP, drop(), WObject::get_ax(), WObject::get_ay(), WObject::get_az(), get_gname(), WObject::get_hname(), get_tex(), get_url(), WObject::get_xy(), WObject::get_z(), getPropertyFunc(), ICON_TYPE, KILL, LEAVE, leave(), MOVE, WObject::moveObject(), OPEN, open(), PIN, pin(), PROPAX, PROPAY, PROPAZ, PROPGNAME, PROPHNAME, PROPTEX, PROPURL, PROPXY, PROPZ, PULL, pull(), PUSH, push(), WObject::put_ax(), WObject::put_ay(), WObject::put_az(), put_gname(), WObject::put_hname(), put_tex(), put_url(), WObject::put_xy(), WObject::put_z(), putPropertyFunc(), SAVE, save(), setActionFunc(), STICK, stick(), TURN, turn(), WO_ACTION, and WO_PAYLOAD.
get_gname()
void Icon::get_gname (Icon * o, Payload * pp) static private
Definition at line 512 of file icon.cpp.
References DBG_WO, Payload::getPayload(), WObject::named(), and trace().
Referenced by funcs().
get_tex()
void Icon::get_tex (Icon * o, Payload * pp) static private
Definition at line 498 of file icon.cpp.
References DBG_WO, Payload::getPayload(), tex, trace(), and URL_LEN.
Referenced by funcs().
get_url()
void Icon::get_url (Icon * o, Payload * pp) static private
Definition at line 485 of file icon.cpp.
References DBG_WO, Payload::getPayload(), WObject::names, trace(), and Names::url.
Referenced by funcs().
getOClass()
virtual const OClass* Icon::getOClass () inline virtual
Reimplemented from WObject.
Definition at line 96 of file icon.hpp.
References oclass.
getParam()
char * Icon::getParam (char * ptok) private virtual
gets parameter
Definition at line 128 of file icon.cpp.
Referenced by Icon().
isMoving()
bool Icon::isMoving () virtual
Checks if object is moving.
Reimplemented from WObject.
Definition at line 61 of file icon.cpp.
References taken, and WObject::testMoving().
leave()
void Icon::leave (Icon * o, void * d, time_t s, time_t u) static private
Definition at line 407 of file icon.cpp.
References WObject::initImposedMovement(), taken, and ttl.
Referenced by funcs().
makeSolid()
void Icon::makeSolid () private virtual
Builds solid geometry.
document's geometry
Definition at line 109 of file icon.cpp.
References COLOR, DEPTH, HEIGHT, WObject::parse(), Parse::parseSolid(), SEP, tex, and WIDTH.
Referenced by Icon().
open()
void Icon::open (Icon * o, void * d, time_t s, time_t u) static private
Definition at line 426 of file icon.cpp.
References Cache::download(), Format::getExt(), Format::getPlayerByExt(), WObject::names, PLAYER_MIDI, PLAYER_MP3, PLAYER_OFFICE, PLAYER_PDF, PLAYER_PS, PLAYER_WGET, Midi::start(), Mp3::start(), Office::start(), Pdf::start(), Browser::start(), Names::url, and Ps::view().
Referenced by funcs().
parser()
void Icon::parser (char * l) private virtual
Parses.
Definition at line 117 of file icon.cpp.
References begin_while_parse, end_while_parse, WObject::names, Names::owner, WObject::parse(), Parse::parseAttributes(), Parse::parseString(), stringcmp(), WObject::tokenize(), and vref.
Referenced by Icon().
pin()
void Icon::pin (Icon * o, void * d, time_t s, time_t u) static private
Definition at line 353 of file icon.cpp.
References Move::aspeed, Pos::az, clearV3(), COLLIDE_ONCE, Cos(), WObject::disablePermanentMovement(), WObject::enableBehavior(), WObject::initImposedMovement(), localuser, lspeed, Move::lspeed, WObject::move, WObject::pos, Sin(), taken, TTL, ttl, and V3::v.
Referenced by funcs(), and Icon().
pull()
void Icon::pull (Icon * o, void * d, time_t s, time_t u) static private
Definition at line 379 of file icon.cpp.
References Move::aspeed, Pos::az, clearV3(), COLLIDE_ONCE, Cos(), WObject::disablePermanentMovement(), WObject::enableBehavior(), WObject::initImposedMovement(), localuser, lspeed, Move::lspeed, WObject::move, WObject::pos, WObject::resetFlashy(), Sin(), taken, TTL, ttl, and V3::v.
Referenced by funcs().
push()
void Icon::push (Icon * o, void * d, time_t s, time_t u) static private
Definition at line 366 of file icon.cpp.
References Move::aspeed, Pos::az, clearV3(), COLLIDE_ONCE, Cos(), WObject::disablePermanentMovement(), WObject::enableBehavior(), WObject::initImposedMovement(), localuser, lspeed, Move::lspeed, WObject::move, WObject::pos, Sin(), taken, TTL, ttl, and V3::v.
Referenced by funcs(), and Icon().
put_gname()
void Icon::put_gname (Icon * o, Payload * pp) static private
Definition at line 520 of file icon.cpp.
References WObject::getInstance(), and Payload::putPayload().
Referenced by funcs().
put_tex()
void Icon::put_tex (Icon * o, Payload * pp) static private
Definition at line 507 of file icon.cpp.
References Payload::putPayload(), and tex.
Referenced by funcs().
put_url()
void Icon::put_url (Icon * o, Payload * pp) static private
Definition at line 493 of file icon.cpp.
References WObject::names, Payload::putPayload(), and Names::url.
Referenced by funcs().
quit()
void Icon::quit () virtual
Quits.
Reimplemented from WObject.
Definition at line 525 of file icon.cpp.
References Pos::ax, Pos::az, File::closeFile(), COLOR, Env::cwd(), DEPTH, Global::env, error(), Cache::file(), g, WObject::getInstance(), HEIGHT, Env::icons(), ifile, WObject::names, ofile, File::openFile(), Names::owner, WObject::pos, remove, taken, tex, Names::url, URL_LEN, vref, WIDTH, WObject::worldName(), Pos::x, Pos::y, and Pos::z.
replicator()
WObject * Icon::replicator (uint8_t type_id, Noid noid, Payload * pp) static
Replicates a icon coming from the Network.
Definition at line 285 of file icon.cpp.
References Icon(), and WObject::noid.
save()
void Icon::save (Icon * o, void * d, time_t s, time_t u) static private
Definition at line 446 of file icon.cpp.
References Env::cwd(), DBG_FORCE, Cache::download(), Global::env, g, WObject::names, notice(), trace(), and Names::url.
Referenced by funcs().
stick()
void Icon::stick (Wall * pwall, void * _picon, time_t s, time_t u) static private
Definition at line 336 of file icon.cpp.
References Pos::az, COLLIDE_ONCE, WObject::enableBehavior(), WObject::pos, WObject::setFlashy(), taken, and WObject::updatePosition().
Referenced by funcs().
turn()
void Icon::turn (Icon * o, void * d, time_t s, time_t u) static private
Definition at line 461 of file icon.cpp.
References aspeed, Move::aspeed, clearV3(), WObject::disablePermanentMovement(), WObject::initImposedMovement(), Move::lspeed, WObject::move, TTL, ttl, and V3::v.
Referenced by funcs().
updateTime()
void Icon::updateTime (time_t sec, time_t usec, float * lasting) virtual
Updates times.
Reimplemented from WObject.
Definition at line 56 of file icon.cpp.
References WObject::updateLasting().
updateToNetwork()
bool Icon::updateToNetwork (const Pos & oldpos) virtual
Publishes to network.
Updates to the network.
Reimplemented from WObject.
Definition at line 305 of file icon.cpp.
References PROPAX, PROPAY, PROPAZ, PROPXY, PROPZ, and WObject::updatePosToNetwork().
whenIntersect()
bool Icon::whenIntersect (WObject * pcur, WObject * pold) virtual
Handles collisions.
Reimplemented from WObject.
Definition at line 310 of file icon.cpp.
References Pos::ax, Pos::az, WObject::copyPositionAndBB(), ICON_TYPE, WObject::pos, WObject::projectPosition(), WObject::type, WObject::updatePositionAndGrid(), USER_TYPE, WALL_TYPE, Pos::x, Pos::y, and Pos::z.
Member Data Documentation
actions
enum { ... } Icon::actions
ASPEED
const float Icon::ASPEED = M_PI_4 static private
Definition at line 41 of file icon.hpp.
Referenced by defaults().
aspeed
float Icon::aspeed private
angular speed
Definition at line 52 of file icon.hpp.
Referenced by defaults(), and turn().
DEPTH
const float Icon::DEPTH = 0.03 static private
Definition at line 38 of file icon.hpp.
Referenced by makeSolid(), and quit().
HEIGHT
const float Icon::HEIGHT = 0.32 static private
Definition at line 49 of file icon.hpp.
Referenced by makeSolid(), and quit().
ifile
char* Icon::ifile private
local input file
Definition at line 43 of file icon.hpp.
Referenced by Icon(), and quit().
LSPEED
const float Icon::LSPEED = 1.0 static private
Definition at line 39 of file icon.hpp.
Referenced by defaults().
lspeed
float Icon::lspeed private
linear speed in xy
Definition at line 51 of file icon.hpp.
Referenced by defaults(), pin(), pull(), and push().
oclass
const OClass Icon::oclass static
class variable
Definition at line 92 of file icon.hpp.
Referenced by getOClass().
ofile
char* Icon::ofile private
public output file
Definition at line 44 of file icon.hpp.
Referenced by Icon(), and quit().
remove
bool Icon::remove private
flag to remove
Definition at line 54 of file icon.hpp.
Referenced by defaults(), and quit().
taken
bool Icon::taken private
taken or not by an user
Definition at line 56 of file icon.hpp.
Referenced by carry(), changePosition(), drop(), Icon(), isMoving(), leave(), pin(), pull(), push(), quit(), and stick().
tex
char* Icon::tex private
texture of the icon
Definition at line 57 of file icon.hpp.
Referenced by get_tex(), Icon(), makeSolid(), put_tex(), and quit().
TTL
const float Icon::TTL = 1.0 static private
Definition at line 47 of file icon.hpp.
Referenced by defaults(), pin(), pull(), push(), and turn().
ttl
float Icon::ttl private
time to live
Definition at line 55 of file icon.hpp.
Referenced by carry(), defaults(), drop(), Icon(), leave(), pin(), pull(), push(), and turn().
vref
char* Icon::vref private
vref entry to restore
Definition at line 45 of file icon.hpp.
Referenced by Icon(), parser(), and quit().
WIDTH
const float Icon::WIDTH = 0.32 static private
Definition at line 48 of file icon.hpp.
Referenced by makeSolid(), and quit().
ZSPEED
const float Icon::ZSPEED = 1.0 static private
Definition at line 40 of file icon.hpp.
Referenced by defaults().
zspeed
float Icon::zspeed private
linear speed in z
Definition at line 53 of file icon.hpp.
Referenced by defaults().
The documentation for this class was generated from the following files:
src/wo/icon.hpp
src/wo/icon.cpp