VREng: Hair Class Reference
Hair Class Reference
CHair class.
#include <hairs.hpp>
Public Member Functions
Hair ()
void init (Object *o, Surface *s, float scale)
Constructor.
void draw ()
Draws hair.
void animate (float dt, Vector3 depl)
Animates hair.
Public Attributes
Object * o
Surface * s
Material m
Color4f c [HAIRNCOLOR]
Line ln [NBHAIR]
Detailed Description
CHair class.
Definition at line 177 of file hairs.hpp.
Constructor & Destructor Documentation
Hair()
Hair::Hair () inline
Definition at line 185 of file hairs.hpp.
Member Function Documentation
animate()
void Hair::animate (float dt, Vector3 depl)
Animates hair.
Definition at line 195 of file hairs.cpp.
References FROT, HAIRGRAVITY, HAIRLENGTH, HAIRSIZE, Vector3::length2(), LENGTH2, ln, MAXL, MAXL2, NBHAIR, Node::p, Line::pt, STIFF2, STIFFNESS, Node::v, and Vector3::z.
Referenced by Hairs::changePermanent().
draw()
void Hair::draw ()
Draws hair.
Definition at line 179 of file hairs.cpp.
References c, Line::draw(), HAIRNCOLOR, ln, m, NBHAIR, and Material::put().
Referenced by Hairs::render().
init()
void Hair::init (Object * o, Surface * s, float scale)
Constructor.
Initializations.
Definition at line 102 of file hairs.cpp.
References c, Material::diffuse, Surface::fc, Material::flag, HAIRNCOLOR, Line::init(), ln, m, HVertex::n, Surface::nbf, NBHAIR, o, HVertex::p, rnd(), s, Vector3::scale(), and TriFace::v.
Referenced by Hairs::loader().
Member Data Documentation
c
Color4f Hair::c[HAIRNCOLOR]
Definition at line 182 of file hairs.hpp.
Referenced by draw(), and init().
ln
Line Hair::ln[NBHAIR]
Definition at line 183 of file hairs.hpp.
Referenced by animate(), draw(), and init().
m
Material Hair::m
Definition at line 181 of file hairs.hpp.
Referenced by draw(), and init().
o
Object* Hair::o
Definition at line 179 of file hairs.hpp.
Referenced by init().
s
Surface* Hair::s
Definition at line 180 of file hairs.hpp.
Referenced by init().
The documentation for this class was generated from the following files:
src/wo/hairs.hpp
src/wo/hairs.cpp