VREng: Model Class Reference
Model Class Reference
Model class.
#include <model.hpp>
Public Member Functions
virtual const OClass * getOClass ()
Model (char *l)
Constructor.
Model (WObject *user, char *_url, float _scale)
Constructor from GUI.
virtual bool isMoving ()
Checks if is moving.
virtual void changePermanent (float lasting)
Imposed movement.
virtual void quit ()
Quits.
virtual void render ()
Makes special rendering.
virtual void render (const Pos &pos)
virtual void render (const Pos &pos, float *color)
Renders the model.
Public Member Functions inherited from WObject
WObject ()
Constructor.
virtual ~WObject ()
Destructor.
virtual uint8_t typeId ()
Abstrct class.
virtual const char * typeName ()
WCreator * getCreator ()
WReplicator * getReplicator ()
virtual void changePosition (float lasting)
Changes the position after a triggered movement.
virtual void updateTime (time_t sec, time_t usec, float *lasting)
Updates remaining times of the movement.
virtual bool updateToNetwork (const Pos &oldpos)
Publishes changes to the network.
virtual bool updatePosToNetwork (const Pos &oldpos, int propxy, int propz, int propaz, int propax, int propay)
Publishes position changes to the network.
virtual bool whenIntersect (WObject *pcur, WObject *pold)
Handles an ingoing collision with another object.
virtual bool whenIntersectOut (WObject *pcur, WObject *pold)
Handles an outgoing collision with another object.
virtual void whenWallsIntersect (WObject *pold, V3 *norm)
Handles collisions with walls.
virtual void lighting ()
Makes special lighting.
const solidList & solids () const
solidlist address.
uint32_t countOfSolids () const
virtual class Solid * getSolid () const
Returns first solid.
virtual void addSolid (class Solid *solid)
Adds to solidList.
virtual void deleteSolids ()
Deletes solids from solidList.
virtual int interAABB (WObject *o1, WObject *o2)
virtual bool haveAction ()
Checks weither have actions.
virtual uint8_t numberAction ()
Number of actions.
virtual bool runAction (const char *action)
Runs action everwhere if available.
virtual void setType (int type)
Sets object type.
virtual int getType ()
Gets object type.
virtual int getNumber ()
Gets object number.
virtual uint16_t getNum ()
Gets a new object number.
virtual void getPosition (M4 &mpos)
Gives solid's position.
virtual void getRelativeBB (V3 &center, V3 &size)
virtual void getDim (V3 &dim)
virtual void getCenter (V3 &center)
virtual void getAbsoluteBB (V3 &center, V3 &size)
Gets relative or absolute center and size of solid.
virtual uint8_t getFrames ()
Gets number of frames of this solid.
virtual uint8_t getFrame ()
Gets index of current frame of this solid.
virtual void setFrame (uint8_t _frame)
Sets current frame.
virtual bool isValid () const
Checks if valid object type.
virtual bool isPermanent () const
Checks if permanent object.
virtual const char * named () const
Gets names.named.
virtual const char * getInstance () const
Gets names.instance.
virtual const char * urlName () const
Gets names.url.
virtual const char * ownerName () const
Gets names.owner.
virtual const char * worldName () const
Gets names.owner.
virtual bool explicitName () const
Checks wether the object is explicitly named.
virtual void toDelete ()
Delete this object latter.
virtual bool removeFromScene ()
Removes an object.
virtual bool isOwner () const
Returns true if owner.
virtual void setOwner (const char *_owner)
Initialize owner.
virtual void setOwner ()
Initialize local user as owner.
virtual void click (GLint x, GLint y)
Execute an object's click method if it's defined.
virtual void click (V3 norm)
Intercepts a click.
virtual char * tokenize (char *l)
Tokenizes the line <object ...
virtual Parse * parse ()
Gets current parse.
void setWObjectId ()
Sets the WObjectid.
void copyNoid (class Noid _noid)
Copies the NetObjectid in WObjectId.
void setSrcId (uint32_t src_id)
Sets the SrcId.
void setPortId (uint16_t port_id)
Sets the PortId.
void setObjId (uint16_t obj_id)
Sets the ObjId.
uint32_t getSrcId () const
Gets the SrcId.
uint16_t getPortId () const
Gets the PortId.
uint16_t getObjId () const
Gets the ObjId.
virtual void update3D (Pos &pos)
Updates object in the 3D.
virtual void updateAll3D (Pos &pos)
Updates object in the 3D.
virtual void updateCamera (Pos &pos)
Updates camera in the 3D.
virtual void getSurfVecs (Pos &pos, V3 *v, V3 *w, V3 *norm)
Returns two vectors that describe the object's surface and a normal vector to that surface.
virtual void updateBB ()
Updates object's Bounding Box.
virtual void getMaterials (GLfloat *dif, GLfloat *amb, GLfloat *spe, GLfloat *emi, GLint *shi, GLfloat *alpha)
virtual void insertIntoGrid ()
Adds an object into the grid.
virtual void deleteFromGrid ()
Deletes an object from the grid.
virtual void updateGrid (const float *bbminnew, const float *bbmaxnew, const float *bbminold, const float *bbmaxold)
Updates an object in the grid.
virtual void updateGrid (const Pos &oldpos)
virtual void updateGrid (const WObject *pold)
Updates an object into the grid.
virtual void addToList (std::list< WObject * > &olist)
virtual OList * addToList (OList *olist)
Adds an object pointer into a olist.
virtual void addToList ()
Adds an object pointer into a olist.
virtual void addToStill ()
Adds an object pointer into stillList.
virtual void addToMobile ()
Adds an object pointer into mobileList.
virtual void addToInvisible ()
Adds an object pointer into invisibleList.
virtual void addToRender ()
Adds an object pointer into renderList.
virtual void delFromMobile ()
Deletes an object pointer from mobileList.
virtual void clearList ()
Clears an olist.
virtual void clearList (std::list< WObject * > &olist)
Clears an olist.
virtual void addToListOnce (std::list< WObject * > &olist)
virtual OList * addToListOnce (OList *olist)
Adds an object pointer into a list only once time.
virtual void delFromList (std::list< WObject * > &olist)
virtual OList * delFromList (OList *olist)
Deletes an object pointer from a olist.
virtual void delFromList ()
Deletes an object pointer from a olist.
virtual OList * getVicinityList (const WObject *pold)
Returns list of pointers on objects touching cell where is the object.
virtual OList * addListToList (OList *list1, OList *list2)
Concatenation (test of "ispointed") of list pointers on an object.
virtual bool isStill ()
Checks an object exists in the stilllist.
virtual bool isMobile ()
virtual bool isEphemeral ()
Checks an object exists in the mobilelist.
virtual WObject * byWObject (WObject *po)
Gets a WObject from the lists.
virtual void checkVicinity (WObject *pold)
< Gets an object by its num.
virtual void imposedMovement (time_t sec, time_t usec)
Handles an object movement.
virtual void elementaryImposedMovement (float lasting)
Handles an elementary object movement.
virtual void enableImposedMovement ()
Enables movement on an object.
virtual void enablePermanentMovement ()
Enables permanent movement on an object.
virtual void disablePermanentMovement ()
Disables movement on an object.
virtual void enablePermanentMovement (float speed)
Enables permanent movement on an object.
virtual void initImposedMovement (float lasting)
Initializes movement on an object.
virtual float diffTime (time_t sec, time_t usec)
Updates times on an object.
virtual void stopImposedMovement ()
Stops a movement on an object.
virtual void permanentMovement (time_t sec, time_t usec)
Handles a permanent object movement.
virtual void elementaryPermanentMovement (float lasting)
Handles an elementary permanent object movement.
virtual void setLasting (float maxlast)
Sets the max lasting time of an object.
virtual float getLasting () const
Gets the lasting time of an object.
virtual bool testMoving ()
Tests if object is moving.
virtual bool updateLasting (time_t sec, time_t usec, float *lasting)
Updates remaining times of the movement.
virtual void moveUserToObject (float val, float _lttl, float _attl)
Moves the user to the object.
virtual void setObjectName (const char *str)
Sets an object name.
virtual WObject * getObjectByName (const char *str)
Gets an object by its name.
virtual void updateNames ()
Updates names.
virtual void initializeObject (uint8_t mode)
Initializes object.
virtual void initializeMobileObject (float last)
virtual void initializeEphemeralObject (float last)
Initializes mobile object.
virtual void initializeStillObject ()
Initializes still object.
void createPermanentNetObject (uint8_t props, uint16_t oid)
Creates local permanent NetObject.
void createVolatileNetObject (uint8_t props)
Creates local volatile NetObject.
void replicateVolatileNetObject (uint8_t props, class Noid _noid)
Replicate distant volatile NetObject.
virtual void enableBehavior (uint32_t flag)
Enables behavior.
virtual void disableBehavior (uint32_t flag)
Disables behavior.
virtual bool isBehavior (uint32_t flag) const
Checks weither this behavior is on.
virtual bool bbBehavior () const
Checks weither BBox behavior is on.
virtual bool isSeen ()
Checks weither the object is in the sight view of the user.
virtual void setVisible (bool flag)
Sets visible or not the 3D object.
virtual bool isVisible ()
Checks weither the object is visible.
virtual void setFlashy (float *color)
Sets flashy the 3D object.
virtual void setFlashy ()
Sets flashy the 3D object.
virtual void resetFlashy ()
Resets flashy the 3D object.
virtual void setRay (GLint wx, GLint wy)
virtual void resetRay ()
Resets Ray on the 3D object.
virtual void setReflexive (bool flag)
virtual bool isSelectable () const
Checks weither 3D selectable behavior is on.
virtual uint32_t collideBehavior () const
Returns collide behavior.
virtual void setRenderPrior (uint8_t _prior)
Sets render priority.
virtual uint8_t getRenderPrior () const
Gets render priority.
void generalIntersect (WObject *pold, OList *vicinityList)
General intersection of objects.
bool ingoingNeighbor (WObject *pold, WObject *neighbor)
bool outgoingNeighbor (WObject *pold, WObject *neighbor)
Checks ingoing intersection with a neighbor.
void ingoingWalls (WObject *pold)
Checks outgoing intersection with a neighbor.
virtual void copyPosAndBB (Pos &newpos)
Checks ingoing intersection with walls.
virtual void copyPositionAndBB (WObject *o)
Copy object position and Bounding Box.
virtual bool projectPosition (WObject *pcur, WObject *pold)
Projects object position.
virtual int projectPositionOnObstacle (Pos &pcur, Pos &pold, Pos &obstacle)
Projects object position on an obstacle.
virtual void initPosition ()
Init 3D and grid position.
virtual void updatePosition ()
Updating 3D.
virtual void updatePositionAndGrid (Pos &oldpos)
Updating 3D and grid position.
virtual void updatePositionAndGrid (WObject *pold)
Updating 3D and grid position.
virtual void computeNormal (WObject *mobil, V3 *normal)
Computes the normal of an object.
virtual void computeNormal (Pos &mobil, Pos &stil, V3 *normal)
Computes the normal of still object.
virtual void bounceTrajectory (WObject *pold, V3 *norm)
Intersects with wall.
void getProperty (uint8_t prop_id, class Payload *pp)
Gets the local copy property from the payload (pp->data).
void putProperty (uint8_t prop_id, class Payload *pp)
Puts the local copy property in the payload.
virtual void deleteReplica ()
Deletes a replicated object.
virtual struct GuiItem * getGui () const
Gets the GUI handle.
virtual bool isGui () const
Checks the GUI handle.
virtual void resetGui ()
Resets the GUI handle.
virtual void clearObjectBar ()
Clears the ObjectBar in the GUI.
virtual void specialAction (int action, void *data, time_t sec, time_t usec)
Calls methods dedicated to each object.
void getObjectHumanName (char **classname, char **instancename, char **actionnames)
Gives object's class_name & action names.
virtual void getMySqlPosition ()
Checks if position is managed by MySql and get it.
virtual void updateMySqlPosition ()
Checks if position is managed by MySql and update it.
virtual int16_t getMySqlState ()
Gets state from MySql.
virtual void updateMySqlPosZ ()
Checks if posZ is managed by MySql.
virtual void updateMySqlState (int16_t state)
Updates state for MySql.
virtual void flushMySqlPosition ()
Flushes position for MySql.
virtual void quitMySql ()
Quits MySql.
Static Public Member Functions
static void funcs ()
init funclist.
static WObject *() creator (char *l)
Creates from fileline.
Static Public Member Functions inherited from WObject
static int interAABB (V3 center1, V3 size1, V3 center2, V3 size2)
Computes intersection between 2 AABB (Axis Aligned Bounding Box).
static int interAABBVertical (V3 center1, V3 size1, V3 center2, V3 size2)
static int interAABBHorizontal (V3 center1, V3 size1, V3 center2, V3 size2)
static void show (const char *name)
Snaps position (debug).
static WObject * byNum (uint16_t num)
static void moveObject (WObject *po, void *d, time_t s, time_t u)
User moves the object.
static void getObjectNameById (uint8_t type_id, char *name)
Gets a name by its id.
static void resetObjectsNumber ()
Resets object seq.
static uint32_t getObjectsNumber ()
Gets current object sequence number.
Static Public Attributes
static const OClass oclass
class variable.
Private Member Functions
virtual void parser (char *l)
Parses file line.
virtual void defaults ()
Sets default values.
virtual void makeSolid ()
Builds solid geometry.
virtual void setName ()
Sets an implicited name.
virtual void behavior ()
Sets behavior flags.
virtual void loader ()
Loads the model.
virtual void scaler ()
Scales or not the model.
virtual void drawer ()
Draws the model.
virtual void preRender ()
Makes translations ans rotations.
virtual void postRender ()
Makes glPopMatrix.
Static Private Member Functions
static void sound (Model *o, void *d, time_t s, time_t u)
Private Attributes
float lspeed
linear speed.
float aspeed
angular speed.
uint8_t model_t
type of model.
float scale
scale to apply.
bool taken
taken or not by user.
bool rendered
rendered or not by user.
bool transform
transform or not.
int texid
texture number.
char * texurl
texture url.
char * sndurl
sound url.
char * bvhurl
bvh url.
float color [3]
main color.
class Lwo * lwo
Lwo Model pointer.
class _3ds * ds3
3ds Model pointer.
class Ase * ase
Ase Model pointer.
class Obj * obj
Obj Model pointer.
class Md2 * md2
Md2 Model pointer.
class Dxf * dxf
Dxf Model pointer.
class Off * off
Off Model pointer.
class X3d * x3d
X3d Model pointer.
class Bvh * bvh
Bvh Model pointer.
Static Private Attributes
static const float LSPEED = 0.25
default linear speed
static const float DEF_SCALE = 1
default scale
Additional Inherited Members
Public Types inherited from WObject
enum {
STILL, MOBILE, EPHEMERAL, INVISIBLE,
MOBILEINVISIBLE, MODE_MAX
}
enum {
DELETED = -1, NONE = 0, INACTIVE = 0, ACTIVE,
PLAYING, TAKEN, DROPPED, MOVED,
CARRYING, IN_CART, ENDSTATE
}
enum { RENDER_LOW, RENDER_NORMAL, RENDER_HIGH }
typedef std::list< class Solid * > solidList
Public Attributes inherited from WObject
solidList _solids
list of solids.
class NetObject * noh
reserved field for network.
struct GuiItem * guip
reserved field for GUI.
uint8_t type
object type.
uint8_t mode
object world mode.
uint16_t num
object sequence number.
uint32_t behavior
behavior flags.
Names names
names.
Pos pos
position in the space.
Move move
movement specific.
class WObjectId noid
WObject Id.
bool is_in_a_list
true if it is already in an OList.
bool removed
flag removed or not.
int16_t state
current state.
int8_t prior
render priority.
char * geometry
geometry string.
class Solid * solid
solid pointer
char chan [CHAN_LEN]
channel.
class Flare * flare
flare instance
Static Protected Member Functions inherited from WObject
static void get_xy (WObject *po, class Payload *pp)
static void get_z (WObject *po, class Payload *pp)
static void get_az (WObject *po, class Payload *pp)
static void get_ay (WObject *po, class Payload *pp)
static void get_ax (WObject *po, class Payload *pp)
static void get_hname (WObject *po, class Payload *pp)
static void put_xy (WObject *po, class Payload *pp)
static void put_z (WObject *po, class Payload *pp)
static void put_az (WObject *po, class Payload *pp)
static void put_ay (WObject *po, class Payload *pp)
static void put_ax (WObject *po, class Payload *pp)
static void put_hname (WObject *po, class Payload *pp)
Protected Attributes inherited from WObject
bool objectbar
true if object bar is active.
Detailed Description
Model class.
Definition at line 33 of file model.hpp.
Constructor & Destructor Documentation
Model() [1/2]
Model::Model (char * l)
Constructor.
Definition at line 129 of file model.cpp.
References behavior(), bvh, bvhurl, drawer(), loader(), makeSolid(), parser(), WObject::pos, WObject::RENDER_HIGH, scaler(), WObject::setRenderPrior(), transform, Pos::x, Pos::y, and Pos::z.
Referenced by creator().
Model() [2/2]
Model::Model (WObject * user, char * _url, float _scale)
Constructor from GUI.
Definition at line 147 of file model.cpp.
References behavior(), bvh, bvhurl, defaults(), drawer(), DYNAMIC, WObject::enableBehavior(), loader(), localuser, makeSolid(), WObject::names, WObject::pos, WObject::RENDER_NORMAL, scale, scaler(), setName(), WObject::setOwner(), WObject::setRenderPrior(), taken, WObject::updatePosition(), Names::url, Pos::x, Pos::y, and Pos::z.
Member Function Documentation
behavior()
void Model::behavior () private virtual
Sets behavior flags.
Definition at line 119 of file model.cpp.
References COLLIDE_NEVER, WObject::enableBehavior(), WObject::initializeMobileObject(), PERSISTENT, and SPECIFIC_RENDER.
Referenced by Model().
changePermanent()
void Model::changePermanent (float lasting) virtual
Imposed movement.
Reimplemented from WObject.
Definition at line 238 of file model.cpp.
References Pos::az, localuser, WObject::pos, Pos::x, Pos::y, and Pos::z.
creator()
WObject * Model::creator (char * l) static
Creates from fileline.
Definition at line 50 of file model.cpp.
References Model().
defaults()
void Model::defaults () private virtual
Sets default values.
Definition at line 55 of file model.cpp.
References ase, bvh, bvhurl, color, DEF_SCALE, ds3, dxf, WObject::INACTIVE, LSPEED, lspeed, lwo, md2, obj, off, rendered, scale, sndurl, WObject::state, taken, texid, texurl, transform, and x3d.
Referenced by Model(), and parser().
drawer()
void Model::drawer () private virtual
Draws the model.
Definition at line 218 of file model.cpp.
References Dxf::displaylist(), Lwo::displaylist(), Off::displaylist(), Md2::displaylist(), dxf, lwo, md2, MODEL_3DS, MODEL_ASE, MODEL_DXF, MODEL_LWO, MODEL_MD2, MODEL_OBJ, MODEL_OFF, model_t, MODEL_X3D, off, and texid.
Referenced by Model().
funcs()
void Model::funcs () static
init funclist.
Definition at line 339 of file model.cpp.
References MODEL_TYPE, WObject::moveObject(), setActionFunc(), sound(), and WO_ACTION.
getOClass()
virtual const OClass* Model::getOClass () inline virtual
Reimplemented from WObject.
Definition at line 66 of file model.hpp.
References oclass.
isMoving()
bool Model::isMoving () virtual
Checks if is moving.
Reimplemented from WObject.
Definition at line 232 of file model.cpp.
References taken, and WObject::testMoving().
loader()
void Model::loader () private virtual
Loads the model.
Definition at line 173 of file model.cpp.
References ase, ds3, dxf, Format::getModelByUrl(), lwo, md2, MODEL_3DS, MODEL_ASE, MODEL_DXF, MODEL_LWO, MODEL_MD2, MODEL_OBJ, MODEL_OFF, model_t, MODEL_X3D, WObject::names, obj, off, Names::url, warning(), and x3d.
Referenced by Model().
makeSolid()
void Model::makeSolid () private virtual
Builds solid geometry.
solid geometry
Definition at line 80 of file model.cpp.
References WObject::parse(), Parse::parseSolid(), and SEP.
Referenced by Model().
parser()
void Model::parser (char * l) private virtual
Parses file line.
Definition at line 92 of file model.cpp.
References begin_while_parse, bvhurl, color, defaults(), end_while_parse, Texture::getFromCache(), WObject::names, WObject::parse(), Parse::parseAttributes(), Parse::parseFloat(), Parse::parseString(), Parse::parseUrl(), Parse::parseVector3f(), scale, sndurl, stringcmp(), texid, texurl, WObject::tokenize(), Names::url, and URL_LEN.
Referenced by Model().
postRender()
void Model::postRender () private virtual
Makes glPopMatrix.
Definition at line 265 of file model.cpp.
References texid, and transform.
Referenced by render().
preRender()
void Model::preRender () private virtual
Makes translations ans rotations.
Definition at line 246 of file model.cpp.
References Pos::ax, Pos::az, color, WObject::pos, RAD2DEG, texid, transform, Pos::x, Pos::y, and Pos::z.
Referenced by render().
quit()
void Model::quit () virtual
Quits.
Reimplemented from WObject.
Definition at line 312 of file model.cpp.
References ase, bvhurl, ds3, dxf, WObject::flushMySqlPosition(), lwo, md2, MODEL_3DS, MODEL_ASE, MODEL_DXF, MODEL_LWO, MODEL_MD2, MODEL_OBJ, MODEL_OFF, model_t, MODEL_X3D, obj, off, oid, sndurl, texurl, and x3d.
render() [1/3]
void Model::render () virtual
Makes special rendering.
Reimplemented from WObject.
Definition at line 274 of file model.cpp.
References ase, color, ds3, dxf, lwo, md2, MODEL_3DS, MODEL_ASE, MODEL_DXF, MODEL_LWO, MODEL_MD2, MODEL_OBJ, MODEL_OFF, model_t, MODEL_X3D, obj, off, WObject::pos, postRender(), preRender(), Ase::render(), Dxf::render(), Lwo::render(), _3ds::render(), Obj::render(), Off::render(), Md2::render(), and rendered.
Referenced by Head::render().
render() [2/3]
void Model::render (const Pos & pos) virtual
Definition at line 290 of file model.cpp.
References color, ds3, lwo, MODEL_3DS, MODEL_LWO, MODEL_OBJ, MODEL_OFF, model_t, obj, off, WObject::pos, Lwo::render(), _3ds::render(), Obj::render(), Off::render(), and rendered.
render() [3/3]
void Model::render (const Pos & pos, float * color) virtual
Renders the model.
Definition at line 301 of file model.cpp.
References color, ds3, lwo, MODEL_3DS, MODEL_LWO, MODEL_OBJ, MODEL_OFF, model_t, obj, off, WObject::pos, Lwo::render(), _3ds::render(), Obj::render(), Off::render(), and rendered.
scaler()
void Model::scaler () private virtual
Scales or not the model.
Definition at line 190 of file model.cpp.
References ase, ds3, dxf, _3ds::getRadius(), Ase::getRadius(), Dxf::getRadius(), Lwo::getRadius(), Md2::getRadius(), Obj::getRadius(), lwo, md2, MODEL_3DS, MODEL_ASE, MODEL_DXF, MODEL_LWO, MODEL_MD2, MODEL_OBJ, MODEL_OFF, model_t, MODEL_X3D, obj, off, scale, Off::setScale(), _3ds::setScale(), Ase::setScale(), Dxf::setScale(), Lwo::setScale(), Md2::setScale(), and Obj::setScale().
Referenced by Model().
setName()
void Model::setName () private virtual
Sets an implicited name.
Definition at line 87 of file model.cpp.
References MODEL_NAME, Names::named, WObject::names, and oid.
Referenced by Model().
sound()
void Model::sound (Model * o, void * d, time_t s, time_t u) static private
Definition at line 331 of file model.cpp.
References d, doAction(), MUSIC_TYPE, Music::PLAY, and sndurl.
Referenced by funcs().
Member Data Documentation
ase
class Ase* Model::ase private
Ase Model pointer.
Definition at line 55 of file model.hpp.
Referenced by defaults(), loader(), quit(), render(), and scaler().
aspeed
float Model::aspeed private
angular speed.
Definition at line 40 of file model.hpp.
bvh
class Bvh* Model::bvh private
Bvh Model pointer.
Definition at line 61 of file model.hpp.
Referenced by defaults(), and Model().
bvhurl
char* Model::bvhurl private
bvh url.
Definition at line 49 of file model.hpp.
Referenced by defaults(), Model(), parser(), and quit().
color
float Model::color[3] private
main color.
Definition at line 50 of file model.hpp.
Referenced by defaults(), parser(), preRender(), and render().
DEF_SCALE
const float Model::DEF_SCALE = 1 static private
default scale
1
Definition at line 37 of file model.hpp.
Referenced by defaults().
ds3
class _3ds* Model::ds3 private
3ds Model pointer.
Definition at line 54 of file model.hpp.
Referenced by defaults(), loader(), quit(), render(), and scaler().
dxf
class Dxf* Model::dxf private
Dxf Model pointer.
Definition at line 58 of file model.hpp.
Referenced by defaults(), drawer(), loader(), quit(), render(), and scaler().
LSPEED
const float Model::LSPEED = 0.25 static private
default linear speed
0.25 m/s
Definition at line 36 of file model.hpp.
Referenced by defaults().
lspeed
float Model::lspeed private
linear speed.
Definition at line 39 of file model.hpp.
Referenced by defaults().
lwo
class Lwo* Model::lwo private
Lwo Model pointer.
Definition at line 53 of file model.hpp.
Referenced by defaults(), drawer(), loader(), quit(), render(), and scaler().
md2
class Md2* Model::md2 private
Md2 Model pointer.
Definition at line 57 of file model.hpp.
Referenced by defaults(), drawer(), loader(), quit(), render(), and scaler().
model_t
uint8_t Model::model_t private
type of model.
Definition at line 41 of file model.hpp.
Referenced by drawer(), loader(), quit(), render(), and scaler().
obj
class Obj* Model::obj private
Obj Model pointer.
Definition at line 56 of file model.hpp.
Referenced by defaults(), loader(), quit(), render(), and scaler().
oclass
const OClass Model::oclass static
class variable.
Definition at line 64 of file model.hpp.
Referenced by getOClass().
off
class Off* Model::off private
Off Model pointer.
Definition at line 59 of file model.hpp.
Referenced by defaults(), drawer(), loader(), quit(), render(), and scaler().
rendered
bool Model::rendered private
rendered or not by user.
Definition at line 44 of file model.hpp.
Referenced by defaults(), and render().
scale
float Model::scale private
scale to apply.
Definition at line 42 of file model.hpp.
Referenced by defaults(), Model(), parser(), and scaler().
sndurl
char* Model::sndurl private
sound url.
Definition at line 48 of file model.hpp.
Referenced by defaults(), parser(), quit(), and sound().
taken
bool Model::taken private
taken or not by user.
Definition at line 43 of file model.hpp.
Referenced by defaults(), isMoving(), and Model().
texid
int Model::texid private
texture number.
Definition at line 46 of file model.hpp.
Referenced by defaults(), drawer(), parser(), postRender(), and preRender().
texurl
char* Model::texurl private
texture url.
Definition at line 47 of file model.hpp.
Referenced by defaults(), parser(), and quit().
transform
bool Model::transform private
transform or not.
Definition at line 45 of file model.hpp.
Referenced by defaults(), Model(), postRender(), and preRender().
x3d
class X3d* Model::x3d private
X3d Model pointer.
Definition at line 60 of file model.hpp.
Referenced by defaults(), loader(), and quit().
The documentation for this class was generated from the following files:
src/wo/model.hpp
src/wo/model.cpp