VREng: GeneralActionList Struct Reference
GeneralActionList Struct Reference
GeneralActionList struct.
#include <initobj.hpp>
Public Attributes
char name [ACTIONNAME_LEN]
void(* method)(WObject *po, void *d, time_t s, time_t u)
Detailed Description
GeneralActionList struct.
Definition at line 48 of file initobj.hpp.
Member Data Documentation
method
void(* GeneralActionList::method) (WObject *po, void *d, time_t s, time_t u)
Definition at line 50 of file initobj.hpp.
Referenced by doAction(), getActionMethod(), World::initGeneralFuncList(), isAction(), and setActionFunc().
name
char GeneralActionList::name[ACTIONNAME_LEN]
Definition at line 49 of file initobj.hpp.
Referenced by copyActionName(), getActionName(), indexAction(), World::initGeneralFuncList(), isActionName(), and setActionFunc().
The documentation for this struct was generated from the following file:
src/wo/initobj.hpp