VREng: OClass Class Reference
OClass Class Reference
OClass Class.
#include <oclass.hpp>
Public Member Functions
OClass (uint8_t type_id, const char *type_name, WCreator *, WReplicator *=NULL, WBuiltin *=NULL)
Constructor.
Static Public Member Functions
static WObject * creatorInstance (uint8_t type_id, char *l)
Creator from fileline.
static void builtinInstance (uint8_t type_id)
Creator from internal.
static class WObject * replicatorInstance (uint8_t type_id, class Noid noid, class Payload *pp)
Creator from network.
static const OClass * getOClass (uint8_t type_id)
Gets oclass by id.
static const OClass * getOClass (const char *type_name)
Gets oclass by name.
static void dumpTable ()
Dump table.
static bool isValidType (int type_id)
Check if a type is valid, exists.
Public Attributes
const uint8_t type_id
class id
const char *const type_name
class name
WCreator *const creator
create from file
WReplicator *const replicator
create from network
WBuiltin *const builtin
create from internal
Static Protected Attributes
static OClass ** otable = NULL
objects table
static uint16_t otable_size = 0
table size
Detailed Description
OClass Class.
WObject factory system
Definition at line 37 of file oclass.hpp.
Constructor & Destructor Documentation
OClass()
OClass::OClass (uint8_t type_id, const char * type_name, WCreator * , WReplicator * = NULL, WBuiltin * = NULL)
Constructor.
OClass constructor.
Definition at line 44 of file oclass.cpp.
References fatal(), otable, otable_size, and type_id.
Member Function Documentation
builtinInstance()
void OClass::builtinInstance (uint8_t type_id) static
Creator from internal.
Definition at line 115 of file oclass.cpp.
References builtin, error(), isValidType(), otable, and type_id.
creatorInstance()
WObject * OClass::creatorInstance (uint8_t type_id, char * l) static
Creator from fileline.
Definition at line 108 of file oclass.cpp.
References creator, dumpTable(), error(), isValidType(), otable, and type_id.
Referenced by Parse::parseVreLines().
dumpTable()
void OClass::dumpTable () static
Dump table.
Definition at line 128 of file oclass.cpp.
References otable, otable_size, type_id, and type_name.
Referenced by creatorInstance(), getOClass(), and replicatorInstance().
getOClass() [1/2]
const OClass * OClass::getOClass (const char * type_name) static
Gets oclass by name.
Definition at line 69 of file oclass.cpp.
References error(), mystrcasecmp(), otable, otable_size, and type_name.
getOClass() [2/2]
const OClass * OClass::getOClass (uint8_t type_id) static
Gets oclass by id.
Definition at line 97 of file oclass.cpp.
References dumpTable(), error(), isValidType(), otable, otable_size, and type_id.
Referenced by WObject::getObjectNameById(), Parse::parseLine(), and Parse::parseVreLines().
isValidType()
bool OClass::isValidType (int type_id) static
Check if a type is valid, exists.
Definition at line 138 of file oclass.cpp.
References OBJECTSNUMBER, and type_id.
Referenced by builtinInstance(), creatorInstance(), NetObject::getNetObject(), Noid::getNetObject(), getOClass(), WObject::isValid(), NetTimeout(), Parse::parseLine(), Parse::parseVreLines(), and replicatorInstance().
replicatorInstance()
WObject * OClass::replicatorInstance (uint8_t type_id, class Noid noid, class Payload * pp) static
Creator from network.
Definition at line 121 of file oclass.cpp.
References dumpTable(), error(), isValidType(), otable, replicator, and type_id.
Referenced by NetObject::replicateObject().
Member Data Documentation
builtin
WBuiltin* const OClass::builtin
create from internal
Definition at line 52 of file oclass.hpp.
Referenced by builtinInstance().
creator
WCreator* const OClass::creator
create from file
Definition at line 50 of file oclass.hpp.
Referenced by creatorInstance(), and WObject::getCreator().
otable
OClass ** OClass::otable = NULL static protected
objects table
Definition at line 43 of file oclass.hpp.
Referenced by builtinInstance(), creatorInstance(), dumpTable(), getOClass(), OClass(), and replicatorInstance().
otable_size
uint16_t OClass::otable_size = 0 static protected
table size
Definition at line 44 of file oclass.hpp.
Referenced by dumpTable(), getOClass(), and OClass().
replicator
WReplicator* const OClass::replicator
create from network
Definition at line 51 of file oclass.hpp.
Referenced by WObject::getReplicator(), and replicatorInstance().
type_id
const uint8_t OClass::type_id
class id
Definition at line 48 of file oclass.hpp.
Referenced by builtinInstance(), creatorInstance(), dumpTable(), getOClass(), isValidType(), OClass(), Parse::parseLine(), Parse::parseVreLines(), replicatorInstance(), and WObject::typeId().
type_name
const char* const OClass::type_name
class name
Definition at line 49 of file oclass.hpp.
Referenced by dumpTable(), WObject::getObjectNameById(), getOClass(), and WObject::typeName().
The documentation for this class was generated from the following files:
src/wo/oclass.hpp
src/wo/oclass.cpp