VREng: Line Class Reference
Line Class Reference
Line class.
#include <hairs.hpp>
Public Member Functions
void init (Vector3 p0, Vector3 dp)
void draw (int pdata)
Public Attributes
Vector3 n
Node pt [HAIRSIZE]
Detailed Description
Line class.
Definition at line 164 of file hairs.hpp.
Member Function Documentation
draw()
void Line::draw (int pdata)
Definition at line 161 of file hairs.cpp.
References HAIRSIZE, n, pt, and Node::put().
Referenced by Hair::draw().
init()
void Line::init (Vector3 p0, Vector3 dp)
Definition at line 135 of file hairs.cpp.
References HAIRSIZE, n, Vector3::normalize(), Node::p, pt, rnd(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by Hair::init().
Member Data Documentation
n
Vector3 Line::n
Definition at line 166 of file hairs.hpp.
Referenced by draw(), and init().
pt
Node Line::pt[HAIRSIZE]
Definition at line 167 of file hairs.hpp.
Referenced by Hair::animate(), draw(), and init().
The documentation for this class was generated from the following files:
src/wo/hairs.hpp
src/wo/hairs.cpp