VREng: Parse Class Reference
Parse Class Reference
Parse class.
#include <parse.hpp>
Public Member Functions
Parse ()
Constructor.
virtual ~Parse ()
Destructor.
virtual char * nextToken ()
Gets the next token.
virtual char * skipChar (char *p, char c, bool flag)
Skip this character.
virtual char * skipEqual (char *p)
Skip equal character.
virtual char * skipOpenBracket (char *p)
Skip open-bracket character.
virtual char * skipOpenParenthesis (char *p)
Skip open-parenthesis character.
virtual char * skipCloseParenthesis (char *p)
Skip close-parenthesis character.
virtual char * skipQuotes (char *p, bool flag=true)
Skip double quotes or single quote.
virtual char * nextSpace (char *p)
find next space or next endtag
virtual char * skipSpace (char *p)
Skip space character.
virtual char * skipComma (char *p)
Skip comma character.
virtual char * parseName (char *l, char *name)
Returns a named name.
virtual char * parseDescr (char *l, char *infos)
Returns a description in infos.
virtual char * skipAttribute (char *l)
Skip the following attribute="value".
virtual char * parseAttributes (char *l, class WObject *po)
Parses attribute="value".
virtual char * parseSolid (char *ptok, class WObject *po)
Creates a new solid.
virtual char * parseSolid (char *geom, const char *separ, class WObject *po)
Parses a builtin solid.
virtual void parseSolids (char *geom, const char *separ, class WObject *po)
Parses several solids.
virtual char * parsePosition (char *ptok, Pos &p)
Returns the spacial positions x y z az ax.
virtual char * parseColor (char *ptok, Pos &p)
Returns a color under r,g,b,a format.
virtual char * parseRotation (char *ptok, Pos &p)
Returns a rotation under r,X,Y,Z format.
virtual char * parseTranslation (char *ptok, Pos &p)
Returns a translation under tx,ty,tz format.
virtual char * parseUrl (char *ptok, char *url)
Returns an url.
virtual char * parseWorldAndChannel (char *ptok, char *url, char *chan)
Returns a world url and a numeric string.
virtual char * parseChannel (char *ptok, char *channel)
Returns a channel under addr/port/ttl format.
virtual char * parseString (char *ptok, char *str)
Returns a string.
virtual char * parseString (char *ptok, char *str, const char *attrstr)
Returns a string under attr=string format.
virtual char * parseQuotedString (char *ptok, char *str)
Returns a string under "string ..." format.
virtual char * parseQuotedString (char *ptok, char *str, const char *attrstr)
Returns a string under attr="string ..." format.
virtual char * parseInt (char *ptok, int *value)
Returns an integer.
virtual char * parseInt (char *ptok, int *value, const char *attrstr)
Returns an integer under attr=value format.
virtual char * parseUInt8 (char *ptok, uint8_t *value)
Returns an 8 bits integer.
virtual char * parseUInt8 (char *ptok, uint8_t *value, const char *attrstr)
Returns an 8 bits integer under attr=value format.
virtual char * parseUInt16 (char *ptok, uint16_t *value)
Returns an 16 bits integer.
virtual char * parseUInt16 (char *ptok, uint16_t *value, const char *attrstr)
Returns an 16 bits integer under attr=value format.
virtual char * parseFloat (char *ptok, float *value)
Returns a float.
virtual char * parseFloat (char *ptok, float *value, const char *attrstr)
Returns a float under attr=value format.
virtual char * parseVector3f (char *ptok, float *vector)
Returns a vector under vx,vy,vz format.
virtual char * parseVector3f (char *ptok, float *vector, const char *attrstr)
Returns a vector under attr=vx,vy,vz format.
virtual char * parseVector3fv (char *ptok, V3 *vector)
Returns a vector under vx,vy,vz format.
virtual char * parseVector3fv (char *ptok, V3 *vector, const char *attrstr)
Returns a vector under attr=vx,vy,vz format.
virtual char * parseVector5f (char *ptok, float *vector)
Returns a vector under vx,vy,vz,vaz,vax format.
virtual char * parsePath (char *ptok, float path[][5], uint16_t *segs)
Returns an array of position describing the path.
virtual int parseVreLines (char *buf, int bufsiz)
parse vre data, called by vreHttpReader
void printNumline ()
prints numline where an error occurs
Static Public Member Functions
static Parse * getParse ()
Gets the parse instance.
Public Attributes
int numline
line number
char tagobj [TAG_LEN]
tag
Static Public Attributes
static const int TAG_LEN = 16
Private Types
enum {
TAG_DOCTYPE, TAG_BEGINFILE, TAG_HEAD, TAG_META,
TAG_COMMENT, TAG_SCENE, TAG_OBJECT, TAG_LOCAL,
TAG_ENDFILE
}
Tags enum.
Private Member Functions
virtual int parseLine (char *_line, int *ptag_type)
parse begin of line
bool isFloat (const char *p)
Check if string begins with a float.
bool isInt (const char *p)
Check if string begins with an integer.
virtual char * parseVectorf (char *ptok, float *vector, int n)
Returns a vector of dimension n.
Private Attributes
enum Parse:: { ... } tags
Tags enum.
int tag_type
tag type
bool commented
flag commented or not
Detailed Description
Parse class.
Definition at line 48 of file parse.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Tags enum.
Enumerator
TAG_DOCTYPE
<!DOCTYPE ... >
TAG_BEGINFILE
<vre ... >
TAG_HEAD
<head> ... </head>
TAG_META
<meta ... />
TAG_COMMENT
TAG_SCENE
<scene> ... </scene>
TAG_OBJECT
<object ... </object>
TAG_LOCAL
<local> ... </local>
TAG_ENDFILE
</vre>
Definition at line 55 of file parse.hpp.
Constructor & Destructor Documentation
Parse()
Parse::Parse ()
Constructor.
Definition at line 67 of file parse.cpp.
References commented, numline, parse, tag_type, and tagobj.
Referenced by getParse().
~Parse()
Parse::~Parse () virtual
Destructor.
Definition at line 76 of file parse.cpp.
References parse.
Member Function Documentation
getParse()
Parse * Parse::getParse () static
Gets the parse instance.
Gets parse pointer : accessor.
Definition at line 82 of file parse.cpp.
References parse, and Parse().
Referenced by World::enter(), WObject::parse(), and World::quit().
isFloat()
bool Parse::isFloat (const char * p) inline private
Check if string begins with a float.
Definition at line 156 of file parse.cpp.
Referenced by parseFloat(), parsePosition(), parseVector3f(), and parseVectorf().
isInt()
bool Parse::isInt (const char * p) inline private
Check if string begins with an integer.
Definition at line 161 of file parse.cpp.
Referenced by parseInt().
nextSpace()
char * Parse::nextSpace (char * p) virtual
find next space or next endtag
Definition at line 139 of file parse.cpp.
Referenced by parseLine(), and parseVreLines().
nextToken()
char * Parse::nextToken () virtual
Gets the next token.
Goto next token, a token is a string separated by a space.
Definition at line 91 of file parse.cpp.
References SEP.
Referenced by parseAttributes(), parseChannel(), parseColor(), parseDescr(), parseFloat(), Solid::parseFrame(), parseInt(), parsePath(), parsePosition(), parseQuotedString(), Solid::parser(), parseRotation(), parseSolid(), parseString(), parseTranslation(), parseUInt16(), parseUInt8(), parseVector3f(), parseVector3fv(), parseVector5f(), parseVectorf(), parseWorldAndChannel(), skipAttribute(), skipComma(), and skipOpenParenthesis().
parseAttributes()
char * Parse::parseAttributes (char * l, class WObject * po) virtual
Parses attribute="value".
Definition at line 572 of file parse.cpp.
References Names::category, Names::infos, Names::named, WObject::names, nextToken(), parseDescr(), parseName(), parsePosition(), parseSolid(), WObject::pos, and stringcmp().
Referenced by Accessory::parser(), Android::parser(), Animator::parser(), AnimX3d::parser(), Aoi::parser(), Area::parser(), Ball::parser(), Board::parser(), Book::parser(), Bumper::parser(), Button::parser(), Cauldron::parser(), Clip::parser(), Clock::parser(), Cloth::parser(), Cloud::parser(), Doc::parser(), Door::parser(), Dress::parser(), Entry::parser(), Escalator::parser(), Fire::parser(), Firework::parser(), Flag::parser(), Fountain::parser(), Fractal::parser(), Ftp::parser(), Gate::parser(), Ground::parser(), Guide::parser(), Guy::parser(), Hairs::parser(), Halo::parser(), Hat::parser(), Head::parser(), Host::parser(), Icon::parser(), Lift::parser(), Light::parser(), Mech::parser(), Mirage::parser(), Mirror::parser(), Model::parser(), Movie::parser(), Music::parser(), Particle::parser(), Plane::parser(), Rain::parser(), River::parser(), Sheet::parser(), Slider::parser(), Smoke::parser(), Snow::parser(), Spiral::parser(), Stair::parser(), Stars::parser(), Step::parser(), Sun::parser(), Template::parser(), Terrain::parser(), Text::parser(), Thing::parser(), Thunder::parser(), Travelator::parser(), Vjc::parser(), Vnc::parser(), Vrelet::parser(), Wall::parser(), Walls::parser(), Water::parser(), Waterfall::parser(), Web::parser(), Widget::parser(), Wind::parser(), and Wings::parser().
parseChannel()
char * Parse::parseChannel (char * ptok, char * channel) virtual
Returns a channel under addr/port/ttl format.
Definition at line 781 of file parse.cpp.
References channel, nextToken(), skipEqual(), skipQuotes(), and stringcmp().
Referenced by Aoi::parser(), and parseWorldAndChannel().
parseColor()
char * Parse::parseColor (char * ptok, Pos & p) virtual
Returns a color under r,g,b,a format.
Definition at line 659 of file parse.cpp.
References Pos::az, nextToken(), skipComma(), skipEqual(), skipQuotes(), stringcmp(), Pos::x, Pos::y, and Pos::z.
parseDescr()
char * Parse::parseDescr (char * l, char * infos) virtual
Returns a description in infos.
Definition at line 587 of file parse.cpp.
References nextToken(), and skipEqual().
Referenced by parseAttributes().
parseFloat() [1/2]
char * Parse::parseFloat (char * ptok, float * value) virtual
Returns a float.
Definition at line 890 of file parse.cpp.
References isFloat(), nextToken(), and skipQuotes().
Referenced by Body::loadBodyParts(), parseFloat(), Accessory::parser(), Animator::parser(), AnimX3d::parser(), Book::parser(), Bumper::parser(), Cloud::parser(), Door::parser(), Escalator::parser(), Fire::parser(), Firework::parser(), Fountain::parser(), Hairs::parser(), Head::parser(), Lift::parser(), Light::parser(), Mirage::parser(), Model::parser(), Movie::parser(), Particle::parser(), Rain::parser(), River::parser(), Slider::parser(), Smoke::parser(), Snow::parser(), Spiral::parser(), Stair::parser(), Stars::parser(), Step::parser(), Sun::parser(), Terrain::parser(), Text::parser(), Thunder::parser(), Travelator::parser(), Vrelet::parser(), Water::parser(), Waterfall::parser(), Wind::parser(), Solid::solidParser(), and Solid::statueParser().
parseFloat() [2/2]
char * Parse::parseFloat (char * ptok, float * value, const char * attrstr) virtual
Returns a float under attr=value format.
Definition at line 899 of file parse.cpp.
References nextToken(), parseFloat(), skipEqual(), and stringcmp().
parseInt() [1/2]
char * Parse::parseInt (char * ptok, int * value) virtual
Returns an integer.
Definition at line 836 of file parse.cpp.
References isInt(), nextToken(), and skipQuotes().
Referenced by parseInt(), Lift::parser(), Vrelet::parser(), and Solid::solidParser().
parseInt() [2/2]
char * Parse::parseInt (char * ptok, int * value, const char * attrstr) virtual
Returns an integer under attr=value format.
Definition at line 845 of file parse.cpp.
References nextToken(), parseInt(), skipEqual(), and stringcmp().
parseLine()
int Parse::parseLine (char * _line, int * ptag_type) private virtual
parse begin of line
Definition at line 192 of file parse.cpp.
References commented, error(), FREE, OClass::getOClass(), OClass::isValidType(), nextSpace(), numline, skipSpace(), stringcmp(), TAG_BEGINFILE, TAG_COMMENT, TAG_DOCTYPE, TAG_ENDFILE, TAG_HEAD, TAG_LEN, TAG_LOCAL, TAG_META, TAG_OBJECT, TAG_SCENE, tagobj, and OClass::type_id.
Referenced by parseVreLines().
parseName()
char * Parse::parseName (char * l, char * name) virtual
Returns a named name.
Definition at line 607 of file parse.cpp.
References parseQuotedString().
Referenced by Icon::Icon(), parseAttributes(), and Cart::parser().
parsePath()
char * Parse::parsePath (char * ptok, float path[][5], uint16_t * segs) virtual
Returns an array of position describing the path.
Definition at line 678 of file parse.cpp.
References nextToken(), skipEqual(), skipQuotes(), and stringcmp().
Referenced by Guide::parser().
parsePosition()
char * Parse::parsePosition (char * ptok, Pos & p) virtual
Returns the spacial positions x y z az ax.
Definition at line 613 of file parse.cpp.
References Pos::ax, Pos::az, isFloat(), nextToken(), skipComma(), skipEqual(), skipQuotes(), stringcmp(), Pos::x, Pos::y, and Pos::z.
Referenced by parseAttributes().
parseQuotedString() [1/2]
char * Parse::parseQuotedString (char * ptok, char * str) virtual
Returns a string under "string ..." format.
Definition at line 812 of file parse.cpp.
References nextToken().
Referenced by parseName(), parseQuotedString(), Button::parser(), and Text::parser().
parseQuotedString() [2/2]
char * Parse::parseQuotedString (char * ptok, char * str, const char * attrstr) virtual
Returns a string under attr="string ..." format.
Definition at line 827 of file parse.cpp.
References parseQuotedString(), skipEqual(), and stringcmp().
parseRotation()
char * Parse::parseRotation (char * ptok, Pos & p) virtual
Returns a rotation under r,X,Y,Z format.
Definition at line 733 of file parse.cpp.
References Pos::az, nextToken(), skipComma(), skipEqual(), skipQuotes(), stringcmp(), Pos::x, Pos::y, and Pos::z.
Referenced by Transform::Transform().
parseSolid() [1/2]
char * Parse::parseSolid (char * geom, const char * separ, class WObject * po) virtual
Parses a builtin solid.
Definition at line 720 of file parse.cpp.
References parseSolid().
parseSolid() [2/2]
char * Parse::parseSolid (char * ptok, class WObject * po) virtual
Creates a new solid.
string 'solid' gives the solid's geometry
Definition at line 700 of file parse.cpp.
References WObject::addSolid(), error(), nextToken(), numline, and Solid::parser().
Referenced by AnimX3d::AnimX3d(), Ball::Ball(), Gate::Gate(), Ground::Ground(), Android::makeSolid(), Ball::makeSolid(), Bubble::makeSolid(), Bullet::makeSolid(), Cloth::makeSolid(), Cloud::makeSolid(), Dart::makeSolid(), Dress::makeSolid(), Fire::makeSolid(), Firework::makeSolid(), Fractal::makeSolid(), Guy::makeSolid(), Halo::makeSolid(), Hat::makeSolid(), Head::makeSolid(), Icon::makeSolid(), Mech::makeSolid(), Model::makeSolid(), Plane::makeSolid(), Sun::makeSolid(), Text::makeSolid(), User::makeSolid(), Wings::makeSolid(), parseAttributes(), parseSolid(), parseSolids(), Step::Step(), and User::User().
parseSolids()
void Parse::parseSolids (char * geom, const char * separ, class WObject * po) virtual
Parses several solids.
Definition at line 727 of file parse.cpp.
References parseSolid().
Referenced by Mirage::Mirage(), Thing::Thing(), and Wall::Wall().
parseString() [1/2]
char * Parse::parseString (char * ptok, char * str) virtual
Returns a string.
Definition at line 792 of file parse.cpp.
References nextToken(), and skipQuotes().
Referenced by Body::loadBodyParts(), Android::parser(), Button::parser(), Clock::parser(), Cloth::parser(), Dress::parser(), Escalator::parser(), Gate::parser(), Guide::parser(), Hat::parser(), Head::parser(), Host::parser(), Icon::parser(), Mirage::parser(), Model::parser(), Music::parser(), Particle::parser(), Step::parser(), Text::parser(), Vjc::parser(), Vnc::parser(), Vrelet::parser(), Wings::parser(), Solid::parseShape(), parseString(), parseUrl(), parseVector3f(), parseWorldAndChannel(), Solid::solidParser(), Solid::statueParser(), and Transform::Transform().
parseString() [2/2]
char * Parse::parseString (char * ptok, char * str, const char * attrstr) virtual
Returns a string under attr=string format.
Definition at line 803 of file parse.cpp.
References nextToken(), parseString(), skipEqual(), and stringcmp().
parseTranslation()
char * Parse::parseTranslation (char * ptok, Pos & p) virtual
Returns a translation under tx,ty,tz format.
Definition at line 747 of file parse.cpp.
References nextToken(), skipComma(), skipEqual(), skipQuotes(), stringcmp(), Pos::x, Pos::y, and Pos::z.
Referenced by Transform::Transform().
parseUInt16() [1/2]
char * Parse::parseUInt16 (char * ptok, uint16_t * value) virtual
Returns an 16 bits integer.
Definition at line 872 of file parse.cpp.
References nextToken(), and skipQuotes().
Referenced by Solid::getFramesNumber(), Animator::parser(), Cloud::parser(), Fire::parser(), Firework::parser(), Fountain::parser(), Fractal::parser(), Particle::parser(), Rain::parser(), Smoke::parser(), Snow::parser(), Stars::parser(), Thunder::parser(), Vnc::parser(), Waterfall::parser(), Wind::parser(), parseUInt16(), and Solid::statueParser().
parseUInt16() [2/2]
char * Parse::parseUInt16 (char * ptok, uint16_t * value, const char * attrstr) virtual
Returns an 16 bits integer under attr=value format.
Definition at line 881 of file parse.cpp.
References nextToken(), parseUInt16(), skipEqual(), and stringcmp().
parseUInt8() [1/2]
char * Parse::parseUInt8 (char * ptok, uint8_t * value) virtual
Returns an 8 bits integer.
Definition at line 854 of file parse.cpp.
References nextToken(), and skipQuotes().
Referenced by Animator::parser(), Book::parser(), Button::parser(), Fire::parser(), Firework::parser(), Fountain::parser(), Guy::parser(), Mech::parser(), Mirage::parser(), Particle::parser(), Rain::parser(), River::parser(), Snow::parser(), Terrain::parser(), Text::parser(), Waterfall::parser(), parseUInt8(), and Solid::solidParser().
parseUInt8() [2/2]
char * Parse::parseUInt8 (char * ptok, uint8_t * value, const char * attrstr) virtual
Returns an 8 bits integer under attr=value format.
Definition at line 863 of file parse.cpp.
References nextToken(), parseUInt8(), skipEqual(), and stringcmp().
parseUrl()
char * Parse::parseUrl (char * ptok, char * url) virtual
Returns an url.
Definition at line 760 of file parse.cpp.
References parseString(), and stringcmp().
Referenced by AnimX3d::parser(), Book::parser(), Clip::parser(), Doc::parser(), Ftp::parser(), Gate::parser(), Guy::parser(), Hairs::parser(), Head::parser(), Model::parser(), Movie::parser(), Music::parser(), Walls::parser(), and Web::parser().
parseVector3f() [1/2]
char * Parse::parseVector3f (char * ptok, float * vector) virtual
Returns a vector under vx,vy,vz format.
Definition at line 923 of file parse.cpp.
References Color::getRGB(), isFloat(), nextToken(), parseString(), and parseVectorf().
Referenced by Body::loadBodyParts(), Android::parser(), Bgcolor::parser(), Firework::parser(), Fountain::parser(), Fractal::parser(), Gate::parser(), Guide::parser(), Guy::parser(), Head::parser(), Light::parser(), Mirage::parser(), Model::parser(), Particle::parser(), Rain::parser(), River::parser(), Snow::parser(), Terrain::parser(), Text::parser(), Waterfall::parser(), parseVector3f(), Solid::solidParser(), and Solid::statueParser().
parseVector3f() [2/2]
char * Parse::parseVector3f (char * ptok, float * vector, const char * attrstr) virtual
Returns a vector under attr=vx,vy,vz format.
Definition at line 963 of file parse.cpp.
References nextToken(), parseVector3f(), skipEqual(), and stringcmp().
parseVector3fv() [1/2]
char * Parse::parseVector3fv (char * ptok, V3 * vector) virtual
Returns a vector under vx,vy,vz format.
Definition at line 949 of file parse.cpp.
References nextToken(), skipComma(), skipQuotes(), and V3::v.
Referenced by parseVector3fv(), and Solid::solidParser().
parseVector3fv() [2/2]
char * Parse::parseVector3fv (char * ptok, V3 * vector, const char * attrstr) virtual
Returns a vector under attr=vx,vy,vz format.
Definition at line 972 of file parse.cpp.
References nextToken(), parseVector3fv(), skipEqual(), and stringcmp().
parseVector5f()
char * Parse::parseVector5f (char * ptok, float * vector) virtual
Returns a vector under vx,vy,vz,vaz,vax format.
Definition at line 941 of file parse.cpp.
References nextToken(), and parseVectorf().
Referenced by Solid::solidParser().
parseVectorf()
char * Parse::parseVectorf (char * ptok, float * vector, int n) private virtual
Returns a vector of dimension n.
Definition at line 908 of file parse.cpp.
References isFloat(), nextToken(), skipComma(), and skipQuotes().
Referenced by parseVector3f(), and parseVector5f().
parseVreLines()
int Parse::parseVreLines (char * buf, int bufsiz) virtual
parse vre data, called by vreHttpReader
Definition at line 298 of file parse.cpp.
References commented, OClass::creatorInstance(), World::current(), DBG_FORCE, Pref::dbgtrace, error(), g, OClass::getOClass(), OClass::isValidType(), new_world, nextSpace(), numline, Times::object, parseLine(), Global::pref, progression(), Render::render(), Global::render, World::setPersistent(), skipSpace(), ProfileTime::start(), ProfileTime::stop(), TAG_BEGINFILE, TAG_COMMENT, TAG_DOCTYPE, TAG_ENDFILE, TAG_HEAD, TAG_LEN, TAG_LOCAL, TAG_META, TAG_OBJECT, TAG_SCENE, tag_type, tagobj, Global::times, trace(), OClass::type_id, and UNKNOWN_TYPE.
Referenced by World::enter(), and World::httpReader().
parseWorldAndChannel()
char * Parse::parseWorldAndChannel (char * ptok, char * url, char * chan) virtual
Returns a world url and a numeric string.
Definition at line 766 of file parse.cpp.
References nextToken(), parseChannel(), and parseString().
printNumline()
void Parse::printNumline ()
prints numline where an error occurs
Definition at line 506 of file parse.cpp.
References error(), and numline.
Referenced by Solid::parser().
skipAttribute()
char * Parse::skipAttribute (char * l) virtual
Skip the following attribute="value".
Definition at line 556 of file parse.cpp.
References nextToken(), and skipQuotes().
Referenced by Web::parser().
skipChar()
char * Parse::skipChar (char * p, char c, bool flag) virtual
Skip this character.
Definition at line 96 of file parse.cpp.
References error(), and numline.
Referenced by skipCloseParenthesis(), skipEqual(), skipOpenBracket(), and skipOpenParenthesis().
skipCloseParenthesis()
char * Parse::skipCloseParenthesis (char * p) virtual
Skip close-parenthesis character.
Definition at line 126 of file parse.cpp.
References skipChar().
skipComma()
char * Parse::skipComma (char * p) virtual
Skip comma character.
Definition at line 151 of file parse.cpp.
References nextToken().
Referenced by parseColor(), parsePosition(), parseRotation(), parseTranslation(), parseVector3fv(), and parseVectorf().
skipEqual()
char * Parse::skipEqual (char * p) virtual
Skip equal character.
Definition at line 106 of file parse.cpp.
References skipChar().
Referenced by parseChannel(), parseColor(), parseDescr(), parseFloat(), parseInt(), parsePath(), parsePosition(), parseQuotedString(), AnimX3d::parser(), parseRotation(), parseString(), parseTranslation(), parseUInt16(), parseUInt8(), parseVector3f(), and parseVector3fv().
skipOpenBracket()
char * Parse::skipOpenBracket (char * p) virtual
Skip open-bracket character.
Definition at line 111 of file parse.cpp.
References skipChar().
skipOpenParenthesis()
char * Parse::skipOpenParenthesis (char * p) virtual
Skip open-parenthesis character.
Definition at line 116 of file parse.cpp.
References nextToken(), and skipChar().
skipQuotes()
char * Parse::skipQuotes (char * p, bool flag = true) virtual
Skip double quotes or single quote.
Definition at line 132 of file parse.cpp.
Referenced by parseChannel(), parseColor(), parseFloat(), parseInt(), parsePath(), parsePosition(), AnimX3d::parser(), parseRotation(), parseString(), parseTranslation(), parseUInt16(), parseUInt8(), parseVector3fv(), parseVectorf(), and skipAttribute().
skipSpace()
char * Parse::skipSpace (char * p) virtual
Skip space character.
Definition at line 145 of file parse.cpp.
Referenced by parseLine(), and parseVreLines().
Member Data Documentation
commented
bool Parse::commented private
flag commented or not
Definition at line 68 of file parse.hpp.
Referenced by Parse(), parseLine(), and parseVreLines().
numline
int Parse::numline
line number
Definition at line 73 of file parse.hpp.
Referenced by World::httpReader(), Parse(), parseLine(), parseSolid(), parseVreLines(), printNumline(), and skipChar().
TAG_LEN
const int Parse::TAG_LEN = 16 static
Definition at line 71 of file parse.hpp.
Referenced by parseLine(), parseVreLines(), and WObject::tokenize().
tag_type
int Parse::tag_type private
tag type
Definition at line 67 of file parse.hpp.
Referenced by Parse(), and parseVreLines().
tagobj
char Parse::tagobj[TAG_LEN]
tag
Definition at line 74 of file parse.hpp.
Referenced by Parse(), parseLine(), parseVreLines(), and WObject::tokenize().
tags
enum { ... } Parse::tags
Tags enum.
The documentation for this class was generated from the following files:
src/wo/parse.hpp
src/wo/parse.cpp