VREng: ParticleSmoke Class Reference
ParticleSmoke Class Reference
ParticleSmoke class.
#include <smoke_new.hpp>
Public Member Functions
ParticleSmoke ()
ParticleSmoke (Vector3 l)
void run ()
void update ()
void display ()
bool isDead ()
float random (float upper, float lower)
Public Attributes
Pos pos
Static Public Attributes
static const float sz = 0.005
static const float pi = 3.141592
static const float a [10] = { pi*1/5, pi*2/5, pi*3/5, pi*4/5, pi*5/5, pi*6/5, pi*7/5, pi*8/5, pi*9/5, 2*pi }
static const float _cos [10] = { sz*cos(a[0]), sz*cos(a[1]), sz*cos(a[2]), sz*cos(a[3]), sz*cos(a[4]), sz*cos(a[5]), sz*cos(a[6]), sz*cos(a[7]), sz*cos(a[8]), sz*cos(a[9]) }
static const float _sin [10] = { sz*sin(a[0]), sz*sin(a[1]), sz*sin(a[2]), sz*sin(a[3]), sz*sin(a[4]), sz*sin(a[5]), sz*sin(a[6]), sz*sin(a[7]), sz*sin(a[8]), sz*sin(a[9]) }
Private Attributes
Vector3 loc
Vector3 vel
Vector3 acc
float life
Detailed Description
ParticleSmoke class.
Definition at line 34 of file smoke_new.hpp.
Constructor & Destructor Documentation
ParticleSmoke() [1/2]
ParticleSmoke::ParticleSmoke ()
Definition at line 37 of file smoke_new.cpp.
ParticleSmoke() [2/2]
ParticleSmoke::ParticleSmoke (Vector3 l)
Definition at line 41 of file smoke_new.cpp.
References life, loc, pos, vel, Vector3::x, Pos::x, Vector3::y, Pos::y, Vector3::z, and Pos::z.
Member Function Documentation
display()
void ParticleSmoke::display ()
Definition at line 78 of file smoke_new.cpp.
References _cos, _sin, life, loc, pos, Vector3::x, Pos::x, Vector3::y, Pos::y, Vector3::z, and Pos::z.
Referenced by run().
isDead()
bool ParticleSmoke::isDead ()
Definition at line 96 of file smoke_new.cpp.
References life.
random()
float ParticleSmoke::random (float upper, float lower)
Definition at line 58 of file smoke_new.cpp.
References RAND_MAX.
Referenced by update().
run()
void ParticleSmoke::run ()
Definition at line 52 of file smoke_new.cpp.
References display(), and update().
update()
void ParticleSmoke::update ()
Definition at line 65 of file smoke_new.cpp.
References acc, Vector3::add(), life, loc, random(), and vel.
Referenced by run().
Member Data Documentation
_cos
const float ParticleSmoke::_cos = { sz*cos(a[0]), sz*cos(a[1]), sz*cos(a[2]), sz*cos(a[3]), sz*cos(a[4]), sz*cos(a[5]), sz*cos(a[6]), sz*cos(a[7]), sz*cos(a[8]), sz*cos(a[9]) } static
Definition at line 50 of file smoke_new.hpp.
Referenced by display().
_sin
const float ParticleSmoke::_sin = { sz*sin(a[0]), sz*sin(a[1]), sz*sin(a[2]), sz*sin(a[3]), sz*sin(a[4]), sz*sin(a[5]), sz*sin(a[6]), sz*sin(a[7]), sz*sin(a[8]), sz*sin(a[9]) } static
Definition at line 51 of file smoke_new.hpp.
Referenced by display().
a
const float ParticleSmoke::a = { pi*1/5, pi*2/5, pi*3/5, pi*4/5, pi*5/5, pi*6/5, pi*7/5, pi*8/5, pi*9/5, 2*pi } static
Definition at line 49 of file smoke_new.hpp.
acc
Vector3 ParticleSmoke::acc private
Definition at line 38 of file smoke_new.hpp.
Referenced by update().
life
float ParticleSmoke::life private
Definition at line 39 of file smoke_new.hpp.
Referenced by display(), isDead(), ParticleSmoke(), and update().
loc
Vector3 ParticleSmoke::loc private
Definition at line 36 of file smoke_new.hpp.
Referenced by display(), ParticleSmoke(), and update().
pi
const float ParticleSmoke::pi = 3.141592 static
Definition at line 48 of file smoke_new.hpp.
pos
Pos ParticleSmoke::pos
Definition at line 42 of file smoke_new.hpp.
Referenced by display(), and ParticleSmoke().
sz
const float ParticleSmoke::sz = 0.005 static
Definition at line 47 of file smoke_new.hpp.
vel
Vector3 ParticleSmoke::vel private
Definition at line 37 of file smoke_new.hpp.
Referenced by ParticleSmoke(), and update().
The documentation for this class was generated from the following files:
src/wo/smoke_new.hpp
src/wo/smoke_new.cpp