VREng: VjcMessage Class Reference
VjcMessage Class Reference
VjcMessage class.
#include <vjc.hpp>
Public Member Functions
VjcMessage (WObject *sender, int type, int val)
Outgoing constructor WObject sender should be set to the object sending the data int type is the message type (VJC_MSGT_) int val is the message value (subtype) (VJC_MSGV_*)
VjcMessage (WObject *sender, uint32_t ssrc, int type, int val)
This constructor is used by Vjc for special update messages.
VjcMessage (uint8_t *data, int datalen)
Incoming constructor Rebuilds a message from the data.
virtual ~VjcMessage ()
Destructor: frees the internal buffer.
virtual tVjcHeader getHeader ()
Returns this message's header.
virtual bool isForObject (WObject *po)
Checks wether this message is for the object *po.
virtual void put8 (int val)
Add a 8bit int to the message.
virtual void put16 (int val)
Add a 16bit int to the message.
virtual void put32 (int val)
Add a 32bit int to the message.
virtual void putOID (WObject *po)
Puts an object's net id.
virtual void putPos (WObject *po)
Puts an object position.
virtual void putStr (const char *str)
Adds a string to the message.
virtual uint8_t * toBytes (int *len)
Packs this message into an uint8_t array.
virtual int sendData ()
Sends data over to the server.
virtual int8_t read8 ()
Reads an 8 bit signed int.
virtual int16_t read16 ()
Reads an 16 bit signed int.
virtual int32_t read32 ()
Reads an 32 bit signed int.
virtual V3 readPoint2D ()
2D point (2*32bit)
virtual V3 readPoint3D ()
3D point (3*32bit)
virtual V3 readDelta ()
Reads three 32bit ints, converted to floats by division by 1000, and returns them in a V3.
virtual tVjcHeader readHeader ()
Reads a message header.
virtual bool hasData (int size)
Data availability.
Static Public Attributes
static const uint8_t VERS = 0
static const uint32_t MAGIC = 0xABCD
static const uint16_t MAX_PACKET = 512
Private Member Functions
virtual void putHeader ()
Writes the header.
virtual void setup (WObject *po, uint32_t ssrc, int type, int id)
Creates the buffer and the header.
void dumpHeader (tVjcHeader hdr)
Private Attributes
uint8_t * data
tVjcHeader header
class WObject * sender
int cursor
int maxlen
Detailed Description
VjcMessage class.
This class is used to receive/transmit data between Vreng and the external server.
Definition at line 208 of file vjc.hpp.
Constructor & Destructor Documentation
VjcMessage() [1/3]
VjcMessage::VjcMessage (WObject * sender, int type, int val)
Outgoing constructor WObject sender should be set to the object sending the data int type is the message type (VJC_MSGT_) int val is the message value (subtype) (VJC_MSGV_*)
Definition at line 358 of file vjc.cpp.
References NetObject::getMySsrcId(), Vjc::getServer(), and setup().
Referenced by sendData().
VjcMessage() [2/3]
VjcMessage::VjcMessage (WObject * sender, uint32_t ssrc, int type, int val)
This constructor is used by Vjc for special update messages.
The additional ssrc int is used to force the message header's ssrc to something else than the current value.
Definition at line 352 of file vjc.cpp.
References setup().
VjcMessage() [3/3]
VjcMessage::VjcMessage (uint8_t * data, int datalen)
Incoming constructor Rebuilds a message from the data.
uint8_t *data should point to a valid memory area, of lenght int datalen. The data is copied into an internal buffer so the orginal data can be freed once the message is constructed.
Definition at line 392 of file vjc.cpp.
References cursor, data, header, maxlen, readHeader(), and sender.
~VjcMessage()
VjcMessage::~VjcMessage () virtual
Destructor: frees the internal buffer.
Definition at line 406 of file vjc.cpp.
References data.
Member Function Documentation
dumpHeader()
void VjcMessage::dumpHeader (tVjcHeader hdr) private
Definition at line 426 of file vjc.cpp.
getHeader()
tVjcHeader VjcMessage::getHeader () virtual
Returns this message's header.
For outgoing messages, the header's data_len field is not set.
Definition at line 420 of file vjc.cpp.
References header.
Referenced by Vjc::getData(), Vrelet::processClient(), and sendData().
hasData()
bool VjcMessage::hasData (int size) virtual
Data availability.
Returns true if there are at least size bytes left
Definition at line 730 of file vjc.cpp.
References cursor, maxlen, and size.
Referenced by Vrelet::processClient().
isForObject()
bool VjcMessage::isForObject (WObject * po) virtual
Checks wether this message is for the object *po.
Definition at line 412 of file vjc.cpp.
References WObject::getObjId(), WObject::getPortId(), WObject::getSrcId(), header, tVjcHeader::obj_id, tVjcHeader::port_id, and tVjcHeader::src_id.
Referenced by Vjc::getData().
put16()
void VjcMessage::put16 (int val) virtual
Add a 16bit int to the message.
Definition at line 447 of file vjc.cpp.
References cursor, and data.
Referenced by putHeader(), putOID(), putStr(), Vrelet::sendPosError(), Vjc::startApp(), and toBytes().
put32()
void VjcMessage::put32 (int val) virtual
Add a 32bit int to the message.
Definition at line 456 of file vjc.cpp.
References cursor, and data.
Referenced by Vrelet::answerTypeQuery(), putHeader(), putOID(), putPos(), Vrelet::sendClick(), sendData(), Vrelet::sendPosError(), Vjc::startApp(), and toBytes().
put8()
void VjcMessage::put8 (int val) virtual
Add a 8bit int to the message.
Definition at line 439 of file vjc.cpp.
References cursor, and data.
Referenced by putHeader(), putOID(), and Vrelet::sendPosError().
putHeader()
void VjcMessage::putHeader () private virtual
Writes the header.
Definition at line 506 of file vjc.cpp.
References tVjcHeader::app_ssrc, tVjcHeader::data_len, header, tVjcHeader::msg_id, tVjcHeader::msg_type, tVjcHeader::proto, put16(), put32(), put8(), putOID(), sender, and tVjcHeader::version.
Referenced by setup().
putOID()
void VjcMessage::putOID (WObject * po) virtual
Puts an object's net id.
8bit type, 32bit src id, 16bit port id, 16bit obj id. Special case: the id passed in is the same as the sender's. We set the type identifier to 0. Special case: NULL is passed as a parameter. We set all the fields to 0.
Definition at line 478 of file vjc.cpp.
References WObject::getObjId(), WObject::getPortId(), WObject::getSrcId(), put16(), put32(), put8(), sender, and WObject::type.
Referenced by Vrelet::answerTypeQuery(), putHeader(), Vrelet::sendIntersect(), and Vrelet::sendPos().
putPos()
void VjcMessage::putPos (WObject * po) virtual
Puts an object position.
6*32bit ((x,y,z),(az,ax,0)). This includes (x,y,z) coordinates, as well as angle data (az, ax, 0) (Y angle never used). All values are rounded to the 3rd decimal, and multiplied by 1000 so as not to have to worry about marshalling floating point values.
Definition at line 495 of file vjc.cpp.
References Pos::ax, Pos::az, WObject::pos, put32(), Pos::x, Pos::y, and Pos::z.
Referenced by Vrelet::sendIntersect(), and Vrelet::sendPos().
putStr()
void VjcMessage::putStr (const char * str) virtual
Adds a string to the message.
A 16b length field is set, followed by the caracters. This method is pretty bad. No encoding is taken into account. Results across heterogenous platforms are undefined. Behavior on platforms where a char is more than 8 bits is completly out of control.
Definition at line 467 of file vjc.cpp.
References cursor, data, put16(), and VJC_CHECK_OVERFLOW_1.
Referenced by Vjc::startApp().
read16()
int16_t VjcMessage::read16 () virtual
Reads an 16 bit signed int.
Definition at line 658 of file vjc.cpp.
References cursor, and data.
Referenced by Vrelet::processClient(), and readHeader().
read32()
int32_t VjcMessage::read32 () virtual
Reads an 32 bit signed int.
Definition at line 667 of file vjc.cpp.
References cursor, and data.
Referenced by Vrelet::processClient(), readHeader(), readPoint2D(), and readPoint3D().
read8()
int8_t VjcMessage::read8 () virtual
Reads an 8 bit signed int.
Definition at line 649 of file vjc.cpp.
References cursor, and data.
Referenced by Vrelet::processClient(), and readHeader().
readDelta()
V3 VjcMessage::readDelta () virtual
Reads three 32bit ints, converted to floats by division by 1000, and returns them in a V3.
Definition at line 719 of file vjc.cpp.
References readPoint3D().
Referenced by Vrelet::processClient().
readHeader()
tVjcHeader VjcMessage::readHeader () virtual
Reads a message header.
Definition at line 680 of file vjc.cpp.
References tVjcHeader::app_ssrc, tVjcHeader::data_len, tVjcHeader::msg_id, tVjcHeader::msg_type, tVjcHeader::obj_id, tVjcHeader::obj_type, tVjcHeader::port_id, tVjcHeader::proto, read16(), read32(), read8(), tVjcHeader::src_id, tVjcHeader::version, and VJC_TYPE.
Referenced by VjcMessage().
readPoint2D()
V3 VjcMessage::readPoint2D () virtual
2D point (2*32bit)
Definition at line 698 of file vjc.cpp.
References read32().
Referenced by Vrelet::processClient(), and readPoint3D().
readPoint3D()
V3 VjcMessage::readPoint3D () virtual
3D point (3*32bit)
Definition at line 709 of file vjc.cpp.
References read32(), and readPoint2D().
Referenced by Vrelet::processClient(), and readDelta().
sendData()
int VjcMessage::sendData () virtual
Sends data over to the server.
The message is not deleted.
Definition at line 537 of file vjc.cpp.
References getHeader(), NetObject::getMySsrcId(), Vjc::getServer(), VjcSocket::isConnected(), put32(), VjcSocket::sdw, Vjc::sock, VjcSocket::SOCK_CONNECT, VjcSocket::SOCK_OPEN, Vjc::ssrc, VjcSocket::statecon, toBytes(), VJC_MSGT_CTRL, VJC_MSGV_REGISTER, VJC_MSGV_UPDATE, and VjcMessage().
Referenced by Vrelet::answerTypeQuery(), Vrelet::sendClick(), Vjc::sendCommand(), Vrelet::sendIntersect(), Vrelet::sendPos(), Vrelet::sendPosError(), Vjc::start(), and Vjc::startApp().
setup()
void VjcMessage::setup (WObject * po, uint32_t ssrc, int type, int id) private virtual
Creates the buffer and the header.
Definition at line 379 of file vjc.cpp.
References cursor, data, header, MAX_PACKET, putHeader(), sender, and vjcNewHeader().
Referenced by VjcMessage().
toBytes()
uint8_t * VjcMessage::toBytes (int * len) virtual
Packs this message into an uint8_t array.
The total length of the array is stored in the len parameter. DO NOT free the returned data. Free the message object when you're done with it. Used to transmit the message on a socket. The return value is the binary representation of this message, and the total length of that array is stored in *len
Definition at line 521 of file vjc.cpp.
References cursor, data, Vjc::getServer(), put16(), put32(), VJC_HDR_DATALEN_IDX, VJC_HDR_LEN, and VJC_HDR_SSRC_IDX.
Referenced by sendData().
Member Data Documentation
cursor
int VjcMessage::cursor private
Definition at line 343 of file vjc.hpp.
Referenced by hasData(), put16(), put32(), put8(), putStr(), read16(), read32(), read8(), setup(), toBytes(), and VjcMessage().
data
uint8_t* VjcMessage::data private
Definition at line 340 of file vjc.hpp.
Referenced by put16(), put32(), put8(), putStr(), read16(), read32(), read8(), setup(), toBytes(), VjcMessage(), and ~VjcMessage().
header
tVjcHeader VjcMessage::header private
Definition at line 341 of file vjc.hpp.
Referenced by getHeader(), isForObject(), putHeader(), setup(), and VjcMessage().
MAGIC
const uint32_t VjcMessage::MAGIC = 0xABCD static
Definition at line 212 of file vjc.hpp.
Referenced by vjcNewHeader().
MAX_PACKET
const uint16_t VjcMessage::MAX_PACKET = 512 static
Definition at line 213 of file vjc.hpp.
Referenced by Vjc::getData(), and setup().
maxlen
int VjcMessage::maxlen private
Definition at line 344 of file vjc.hpp.
Referenced by hasData(), and VjcMessage().
sender
class WObject* VjcMessage::sender private
Definition at line 342 of file vjc.hpp.
Referenced by putHeader(), putOID(), setup(), and VjcMessage().
VERS
const uint8_t VjcMessage::VERS = 0 static
Definition at line 211 of file vjc.hpp.
Referenced by vjcNewHeader().
The documentation for this class was generated from the following files:
src/wo/vjc.hpp
src/wo/vjc.cpp