VREng: VjcSocket Class Reference
VjcSocket Class Reference
VjcSocket class in-out socket holder.
#include <vjc.hpp>
Public Types
enum { SOCK_CLOSED, SOCK_RCVOPEN, SOCK_CONNECT, SOCK_OPEN }
Public Member Functions
VjcSocket (uint16_t listenPort, const char *destHost, uint16_t destPort)
Initialize a pair of sockets for communicating with the child app.
virtual ~VjcSocket ()
Closes and frees an VjcSocket.
virtual int openSocket ()
Opens an VjcSocket.
virtual int openRecv ()
Open the receiver socket for this socket pair.
virtual int openSend ()
Opens the sender socket.
virtual int connectSend ()
Tries a connect to the client app.
virtual bool isConnected ()
Check if the non-blocking connect call on the send socket finished or not.
virtual bool isOpen ()
Is socket opened ?.
virtual bool isClosed ()
Is socket closed ?.
Public Attributes
uint16_t listenPort
Local port.
uint16_t destPort
Server port.
int statecon
Connection state.
int sdr
read fd
int sdw
write fd
struct sockaddr_in * sadest
socket for Vjs
Detailed Description
VjcSocket class in-out socket holder.
Definition at line 101 of file vjc.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
SOCK_CLOSED
SOCK_RCVOPEN
SOCK_CONNECT
SOCK_OPEN
Definition at line 112 of file vjc.hpp.
Constructor & Destructor Documentation
VjcSocket()
VjcSocket::VjcSocket (uint16_t listenPort, const char * destHost, uint16_t destPort)
Initialize a pair of sockets for communicating with the child app.
The sockets aren't actually opened. The addresses are initialized.
Definition at line 205 of file vjc.cpp.
References destPort, error(), listenPort, my_gethostbyname(), sadest, sdr, sdw, SOCK_CLOSED, and statecon.
~VjcSocket()
VjcSocket::~VjcSocket () virtual
Closes and frees an VjcSocket.
The handle is invalidated by this call.
Definition at line 318 of file vjc.cpp.
References Socket::closeDatagram(), sadest, sdr, sdw, SOCK_CONNECT, SOCK_RCVOPEN, and statecon.
Member Function Documentation
connectSend()
int VjcSocket::connectSend () virtual
Tries a connect to the client app.
Since the IO mode is NONBLOCK, two types of errors can happen:
EINPROGRESS : the connect didn't complet - the child app is not ready, but is not dead either. The connect will have to be tried again.
Other : the child app is not in a good state. Not worth retrying.
Definition at line 262 of file vjc.cpp.
References error(), sadest, sdw, SOCK_OPEN, and statecon.
Referenced by openSocket().
isClosed()
bool VjcSocket::isClosed () virtual
Is socket closed ?.
Definition at line 340 of file vjc.cpp.
References SOCK_CLOSED, and statecon.
isConnected()
bool VjcSocket::isConnected () virtual
Check if the non-blocking connect call on the send socket finished or not.
Definition at line 285 of file vjc.cpp.
References sdw, SOCK_OPEN, and statecon.
Referenced by VjcMessage::sendData().
isOpen()
bool VjcSocket::isOpen () virtual
Is socket opened ?.
Definition at line 335 of file vjc.cpp.
References SOCK_OPEN, and statecon.
openRecv()
int VjcSocket::openRecv () virtual
Open the receiver socket for this socket pair.
The socket is bound to the local port passed in when it was initialized.
Definition at line 235 of file vjc.cpp.
References Socket::bindSocket(), Socket::closeDatagram(), listenPort, notice(), Socket::openDatagram(), sdr, SOCK_RCVOPEN, and statecon.
Referenced by openSocket().
openSend()
int VjcSocket::openSend () virtual
Opens the sender socket.
IO is set to non-blocking on this one so that the connect (done in the next step) does not lock up the whole VRENG app.
Definition at line 252 of file vjc.cpp.
References Socket::openDatagram(), sdw, Socket::setNoBlocking(), SOCK_CONNECT, and statecon.
Referenced by openSocket().
openSocket()
int VjcSocket::openSocket () virtual
Opens an VjcSocket.
This call is 'non-blocking' : if the connect does not work because the client is not ready yet, this function returns 0. In this case, it should be called again to finish the connection. If the socket is completly open, it returns 1. If an error occured, it returns -1.
Definition at line 302 of file vjc.cpp.
References connectSend(), openRecv(), openSend(), SOCK_CLOSED, SOCK_CONNECT, SOCK_OPEN, SOCK_RCVOPEN, and statecon.
Referenced by Vjc::start().
Member Data Documentation
destPort
uint16_t VjcSocket::destPort
Server port.
Definition at line 105 of file vjc.hpp.
Referenced by VjcSocket().
listenPort
uint16_t VjcSocket::listenPort
Local port.
Definition at line 104 of file vjc.hpp.
Referenced by openRecv(), Vjc::start(), and VjcSocket().
sadest
struct sockaddr_in* VjcSocket::sadest
socket for Vjs
Definition at line 109 of file vjc.hpp.
Referenced by connectSend(), VjcSocket(), and ~VjcSocket().
sdr
int VjcSocket::sdr
read fd
Definition at line 107 of file vjc.hpp.
Referenced by Vjc::getData(), openRecv(), VjcSocket(), and ~VjcSocket().
sdw
int VjcSocket::sdw
write fd
Definition at line 108 of file vjc.hpp.
Referenced by connectSend(), isConnected(), openSend(), VjcMessage::sendData(), VjcSocket(), and ~VjcSocket().
statecon
int VjcSocket::statecon
Connection state.
Definition at line 106 of file vjc.hpp.
Referenced by connectSend(), Vjc::getData(), isClosed(), isConnected(), isOpen(), openRecv(), openSend(), openSocket(), VjcMessage::sendData(), VjcSocket(), and ~VjcSocket().
The documentation for this class was generated from the following files:
src/wo/vjc.hpp
src/wo/vjc.cpp