VREng: User Class Reference
User Class Reference
User class.
#include <user.hpp>
Public Types
enum {
PROPHNAME, PROPMAPFRONT, PROPMAPBACK, PROPXY,
PROPZ, PROPAZ, PROPAY, PROPAX,
PROPMSG, PROPMENSURATION, PROPMAPLEFT, PROPMAPRIGHT,
PROPVRE, PROPWEB, PROPSSRC, PROPRTCPNAME,
PROPRTCPEMAIL, PROPMODEL, PROPFACE, PROPSEX,
PROPHEAD, PROPSKIN, PROPBUST, PROPRAY,
PROPS
}
enum { PROPBEGINVAR = PROPXY, PROPENDVAR = PROPMSG }
Public Types inherited from WObject
enum {
STILL, MOBILE, EPHEMERAL, INVISIBLE,
MOBILEINVISIBLE, MODE_MAX
}
enum {
DELETED = -1, NONE = 0, INACTIVE = 0, ACTIVE,
PLAYING, TAKEN, DROPPED, MOVED,
CARRYING, IN_CART, ENDSTATE
}
enum { RENDER_LOW, RENDER_NORMAL, RENDER_HIGH }
typedef std::list< class Solid * > solidList
Public Member Functions
virtual const OClass * getOClass ()
User ()
Returns instance of this class.
User (uint8_t type_id, Noid noid, Payload *pp)
Constructor replicator.
virtual ~User ()
Destructor.
virtual void inits ()
Does needed initializations.
virtual void resetBubble ()
Resets bubble text.
virtual Bubble * getBubble () const
Gets bubble text.
virtual void changePosition (float lasting)
Imposed movement.
virtual void changePermanent (float lasting)
Permanent movement.
virtual void updateTime (time_t sec, time_t usec, float *last)
Updates times.
virtual bool updateToNetwork (const Pos &oldpos)
Publishes position to the network.
virtual bool whenIntersect (WObject *pcur, WObject *pold)
When an other object intersects.
virtual void clearKeyTab ()
Clears keys times array.
virtual void updateKeysTimes (time_t sec, time_t usec)
Updates the keydifftime arrays.
virtual void changePositionOneDir (const int move_type, const float last)
Modifies user position in one direction.
virtual void updateTime (float lasting[])
Fills delays's array for each user motion direction.
virtual void changePosition (const float lasting[])
Does the motion in each direction.
virtual void elementaryUserMovement (const float lastings[])
User motion limited by the maxlast.
virtual void userMovement (time_t sec, time_t usec)
User general motion.
virtual void setRayDirection (GLint x, GLint y)
Lanche a ray in thar direction.
virtual void specialAction (int act_id, void *data, time_t sec, time_t usec)
Special action to do.
virtual void enableGravity ()
enables gravity.
virtual void disableGravity ()
disables gravity.
virtual void resetPosition ()
Resets user position.
virtual void setPosition ()
Sets user position.
virtual bool hasHead ()
Returns boolean.
Public Member Functions inherited from WObject
WObject ()
Constructor.
virtual ~WObject ()
Destructor.
virtual uint8_t typeId ()
Abstrct class.
virtual const char * typeName ()
WCreator * getCreator ()
WReplicator * getReplicator ()
virtual bool isMoving ()
Checks weither object is moving.
virtual bool updatePosToNetwork (const Pos &oldpos, int propxy, int propz, int propaz, int propax, int propay)
Publishes position changes to the network.
virtual bool whenIntersectOut (WObject *pcur, WObject *pold)
Handles an outgoing collision with another object.
virtual void whenWallsIntersect (WObject *pold, V3 *norm)
Handles collisions with walls.
virtual void render ()
Makes special rendering.
virtual void lighting ()
Makes special lighting.
virtual void quit ()
Makes all thing when leaving the object.
const solidList & solids () const
solidlist address.
uint32_t countOfSolids () const
virtual class Solid * getSolid () const
Returns first solid.
virtual void addSolid (class Solid *solid)
Adds to solidList.
virtual void deleteSolids ()
Deletes solids from solidList.
virtual int interAABB (WObject *o1, WObject *o2)
virtual bool haveAction ()
Checks weither have actions.
virtual uint8_t numberAction ()
Number of actions.
virtual bool runAction (const char *action)
Runs action everwhere if available.
virtual void setType (int type)
Sets object type.
virtual int getType ()
Gets object type.
virtual int getNumber ()
Gets object number.
virtual uint16_t getNum ()
Gets a new object number.
virtual void getPosition (M4 &mpos)
Gives solid's position.
virtual void getRelativeBB (V3 &center, V3 &size)
virtual void getDim (V3 &dim)
virtual void getCenter (V3 &center)
virtual void getAbsoluteBB (V3 &center, V3 &size)
Gets relative or absolute center and size of solid.
virtual uint8_t getFrames ()
Gets number of frames of this solid.
virtual uint8_t getFrame ()
Gets index of current frame of this solid.
virtual void setFrame (uint8_t _frame)
Sets current frame.
virtual bool isValid () const
Checks if valid object type.
virtual bool isPermanent () const
Checks if permanent object.
virtual const char * named () const
Gets names.named.
virtual const char * getInstance () const
Gets names.instance.
virtual const char * urlName () const
Gets names.url.
virtual const char * ownerName () const
Gets names.owner.
virtual const char * worldName () const
Gets names.owner.
virtual bool explicitName () const
Checks wether the object is explicitly named.
virtual void toDelete ()
Delete this object latter.
virtual bool removeFromScene ()
Removes an object.
virtual bool isOwner () const
Returns true if owner.
virtual void setOwner (const char *_owner)
Initialize owner.
virtual void setOwner ()
Initialize local user as owner.
virtual void click (GLint x, GLint y)
Execute an object's click method if it's defined.
virtual void click (V3 norm)
Intercepts a click.
virtual char * tokenize (char *l)
Tokenizes the line <object ...
virtual Parse * parse ()
Gets current parse.
void setWObjectId ()
Sets the WObjectid.
void copyNoid (class Noid _noid)
Copies the NetObjectid in WObjectId.
void setSrcId (uint32_t src_id)
Sets the SrcId.
void setPortId (uint16_t port_id)
Sets the PortId.
void setObjId (uint16_t obj_id)
Sets the ObjId.
uint32_t getSrcId () const
Gets the SrcId.
uint16_t getPortId () const
Gets the PortId.
uint16_t getObjId () const
Gets the ObjId.
virtual void update3D (Pos &pos)
Updates object in the 3D.
virtual void updateAll3D (Pos &pos)
Updates object in the 3D.
virtual void updateCamera (Pos &pos)
Updates camera in the 3D.
virtual void getSurfVecs (Pos &pos, V3 *v, V3 *w, V3 *norm)
Returns two vectors that describe the object's surface and a normal vector to that surface.
virtual void updateBB ()
Updates object's Bounding Box.
virtual void getMaterials (GLfloat *dif, GLfloat *amb, GLfloat *spe, GLfloat *emi, GLint *shi, GLfloat *alpha)
virtual void insertIntoGrid ()
Adds an object into the grid.
virtual void deleteFromGrid ()
Deletes an object from the grid.
virtual void updateGrid (const float *bbminnew, const float *bbmaxnew, const float *bbminold, const float *bbmaxold)
Updates an object in the grid.
virtual void updateGrid (const Pos &oldpos)
virtual void updateGrid (const WObject *pold)
Updates an object into the grid.
virtual void addToList (std::list< WObject * > &olist)
virtual OList * addToList (OList *olist)
Adds an object pointer into a olist.
virtual void addToList ()
Adds an object pointer into a olist.
virtual void addToStill ()
Adds an object pointer into stillList.
virtual void addToMobile ()
Adds an object pointer into mobileList.
virtual void addToInvisible ()
Adds an object pointer into invisibleList.
virtual void addToRender ()
Adds an object pointer into renderList.
virtual void delFromMobile ()
Deletes an object pointer from mobileList.
virtual void clearList ()
Clears an olist.
virtual void clearList (std::list< WObject * > &olist)
Clears an olist.
virtual void addToListOnce (std::list< WObject * > &olist)
virtual OList * addToListOnce (OList *olist)
Adds an object pointer into a list only once time.
virtual void delFromList (std::list< WObject * > &olist)
virtual OList * delFromList (OList *olist)
Deletes an object pointer from a olist.
virtual void delFromList ()
Deletes an object pointer from a olist.
virtual OList * getVicinityList (const WObject *pold)
Returns list of pointers on objects touching cell where is the object.
virtual OList * addListToList (OList *list1, OList *list2)
Concatenation (test of "ispointed") of list pointers on an object.
virtual bool isStill ()
Checks an object exists in the stilllist.
virtual bool isMobile ()
virtual bool isEphemeral ()
Checks an object exists in the mobilelist.
virtual WObject * byWObject (WObject *po)
Gets a WObject from the lists.
virtual void checkVicinity (WObject *pold)
< Gets an object by its num.
virtual void imposedMovement (time_t sec, time_t usec)
Handles an object movement.
virtual void elementaryImposedMovement (float lasting)
Handles an elementary object movement.
virtual void enableImposedMovement ()
Enables movement on an object.
virtual void enablePermanentMovement ()
Enables permanent movement on an object.
virtual void disablePermanentMovement ()
Disables movement on an object.
virtual void enablePermanentMovement (float speed)
Enables permanent movement on an object.
virtual void initImposedMovement (float lasting)
Initializes movement on an object.
virtual float diffTime (time_t sec, time_t usec)
Updates times on an object.
virtual void stopImposedMovement ()
Stops a movement on an object.
virtual void permanentMovement (time_t sec, time_t usec)
Handles a permanent object movement.
virtual void elementaryPermanentMovement (float lasting)
Handles an elementary permanent object movement.
virtual void setLasting (float maxlast)
Sets the max lasting time of an object.
virtual float getLasting () const
Gets the lasting time of an object.
virtual bool testMoving ()
Tests if object is moving.
virtual bool updateLasting (time_t sec, time_t usec, float *lasting)
Updates remaining times of the movement.
virtual void moveUserToObject (float val, float _lttl, float _attl)
Moves the user to the object.
virtual void setObjectName (const char *str)
Sets an object name.
virtual WObject * getObjectByName (const char *str)
Gets an object by its name.
virtual void updateNames ()
Updates names.
virtual void initializeObject (uint8_t mode)
Initializes object.
virtual void initializeMobileObject (float last)
virtual void initializeEphemeralObject (float last)
Initializes mobile object.
virtual void initializeStillObject ()
Initializes still object.
void createPermanentNetObject (uint8_t props, uint16_t oid)
Creates local permanent NetObject.
void createVolatileNetObject (uint8_t props)
Creates local volatile NetObject.
void replicateVolatileNetObject (uint8_t props, class Noid _noid)
Replicate distant volatile NetObject.
virtual void enableBehavior (uint32_t flag)
Enables behavior.
virtual void disableBehavior (uint32_t flag)
Disables behavior.
virtual bool isBehavior (uint32_t flag) const
Checks weither this behavior is on.
virtual bool bbBehavior () const
Checks weither BBox behavior is on.
virtual bool isSeen ()
Checks weither the object is in the sight view of the user.
virtual void setVisible (bool flag)
Sets visible or not the 3D object.
virtual bool isVisible ()
Checks weither the object is visible.
virtual void setFlashy (float *color)
Sets flashy the 3D object.
virtual void setFlashy ()
Sets flashy the 3D object.
virtual void resetFlashy ()
Resets flashy the 3D object.
virtual void setRay (GLint wx, GLint wy)
virtual void resetRay ()
Resets Ray on the 3D object.
virtual void setReflexive (bool flag)
virtual bool isSelectable () const
Checks weither 3D selectable behavior is on.
virtual uint32_t collideBehavior () const
Returns collide behavior.
virtual void setRenderPrior (uint8_t _prior)
Sets render priority.
virtual uint8_t getRenderPrior () const
Gets render priority.
void generalIntersect (WObject *pold, OList *vicinityList)
General intersection of objects.
bool ingoingNeighbor (WObject *pold, WObject *neighbor)
bool outgoingNeighbor (WObject *pold, WObject *neighbor)
Checks ingoing intersection with a neighbor.
void ingoingWalls (WObject *pold)
Checks outgoing intersection with a neighbor.
virtual void copyPosAndBB (Pos &newpos)
Checks ingoing intersection with walls.
virtual void copyPositionAndBB (WObject *o)
Copy object position and Bounding Box.
virtual bool projectPosition (WObject *pcur, WObject *pold)
Projects object position.
virtual int projectPositionOnObstacle (Pos &pcur, Pos &pold, Pos &obstacle)
Projects object position on an obstacle.
virtual void initPosition ()
Init 3D and grid position.
virtual void updatePosition ()
Updating 3D.
virtual void updatePositionAndGrid (Pos &oldpos)
Updating 3D and grid position.
virtual void updatePositionAndGrid (WObject *pold)
Updating 3D and grid position.
virtual void computeNormal (WObject *mobil, V3 *normal)
Computes the normal of an object.
virtual void computeNormal (Pos &mobil, Pos &stil, V3 *normal)
Computes the normal of still object.
virtual void bounceTrajectory (WObject *pold, V3 *norm)
Intersects with wall.
void getProperty (uint8_t prop_id, class Payload *pp)
Gets the local copy property from the payload (pp->data).
void putProperty (uint8_t prop_id, class Payload *pp)
Puts the local copy property in the payload.
virtual void deleteReplica ()
Deletes a replicated object.
virtual struct GuiItem * getGui () const
Gets the GUI handle.
virtual bool isGui () const
Checks the GUI handle.
virtual void resetGui ()
Resets the GUI handle.
virtual void clearObjectBar ()
Clears the ObjectBar in the GUI.
void getObjectHumanName (char **classname, char **instancename, char **actionnames)
Gives object's class_name & action names.
virtual void getMySqlPosition ()
Checks if position is managed by MySql and get it.
virtual void updateMySqlPosition ()
Checks if position is managed by MySql and update it.
virtual int16_t getMySqlState ()
Gets state from MySql.
virtual void updateMySqlPosZ ()
Checks if posZ is managed by MySql.
virtual void updateMySqlState (int16_t state)
Updates state for MySql.
virtual void flushMySqlPosition ()
Flushes position for MySql.
virtual void quitMySql ()
Quits MySql.
Static Public Member Functions
static void funcs ()
init funclist.
static void updateTime2 (WObject *pu, time_t sec, time_t usec, float *lasting)
Updates times array.
static WObject * replicator (uint8_t type_id, Noid noid, Payload *pp)
Replicates a remote avatar.
static void userWriting (const char *usermsg)
Signals a message sent by an user.
static void userRequesting (const char *usermsg)
Signals a message sent by an user.
static void bulletPutHit (class Bullet *po, Payload *pp)
static void dartPutHit (class Dart *po, Payload *pp)
Static Public Member Functions inherited from WObject
static int interAABB (V3 center1, V3 size1, V3 center2, V3 size2)
Computes intersection between 2 AABB (Axis Aligned Bounding Box).
static int interAABBVertical (V3 center1, V3 size1, V3 center2, V3 size2)
static int interAABBHorizontal (V3 center1, V3 size1, V3 center2, V3 size2)
static void show (const char *name)
Snaps position (debug).
static WObject * byNum (uint16_t num)
static void moveObject (WObject *po, void *d, time_t s, time_t u)
User moves the object.
static void getObjectNameById (uint8_t type_id, char *name)
Gets a name by its id.
static void resetObjectsNumber ()
Resets object seq.
static uint32_t getObjectsNumber ()
Gets current object sequence number.
Public Attributes
class Man * man
Man avatar model.
class Guy * guy
Guy avatar model.
class Android * android
Android avatar model.
class Head * head
Head avatar model.
char * web
url web.
char * cname
RTP cname.
char * rtcpname
RTCP name.
char * email
user's email.
char * tool
tool used.
float height
body height.
V3 ray
ray extremity.
uint8_t hit
hit.
Carrier * carrier
Carrier.
Cart * cart
Cart.
Bubble * bubble
bubble text.
uint8_t current_view
current_view.
bool kpressed [MAXKEYS]
is the key pressed ?
time_t kpstart_s [MAXKEYS]
key press starting time (sec).
time_t kpstart_u [MAXKEYS]
key press starting time (usec).
time_t kpdur_s [MAXKEYS]
key press duration from starting time sec.
time_t kpdur_u [MAXKEYS]
key press duration from starting time usec.
Public Attributes inherited from WObject
solidList _solids
list of solids.
class NetObject * noh
reserved field for network.
struct GuiItem * guip
reserved field for GUI.
uint8_t type
object type.
uint8_t mode
object world mode.
uint16_t num
object sequence number.
uint32_t behavior
behavior flags.
Names names
names.
Pos pos
position in the space.
Move move
movement specific.
class WObjectId noid
WObject Id.
bool is_in_a_list
true if it is already in an OList.
bool removed
flag removed or not.
int16_t state
current state.
int8_t prior
render priority.
char * geometry
geometry string.
class Solid * solid
solid pointer
char chan [CHAN_LEN]
channel.
class Flare * flare
flare instance
Static Public Attributes
static const float LASTING = 0.015
static const float DEFAULTWIDTH = 0.26
static const float DEFAULTDEPTH = 0.16
static const float DEFAULTHEIGHT = 1.70
static const float LSPEED = 2.
static const float ASPEED = 1.
static const float DELTAZ = 0.02
static const float GOTHROUGH = 0.05
static const float FOVY = 26.
static const float NEAR = 0.1
static const float FAR = 300.
static const float DENSITY = 1.
static const uint8_t MESS_LEN = 255
static const uint8_t MENSURATIONLEN = 64
static const OClass oclass
class variable.
Protected Attributes
float lspeed
linear speed.
float aspeed
angular speed.
float width
body width.
float depth
body depth.
uint32_t ssrc
ssrc id.
char * front
url body front.
char * back
url body back.
char * left
url body left.
char * right
url body right.
char * vre
url vre.
char * host
url host.
char * model
url model.
char * face
url face.
char * sex
sex.
char * headurl
url head.
char * skin
skin color.
char * bust
bust color.
char * color
color.
char * baps
vaps server.
WObject * lastSelected
float lastDistance
char mensuration [MENSURATIONLEN]
char message [MESS_LEN]
message buffer.
char request [MESS_LEN]
int lastmess
last message number.
int lastrequest
bool goingup
flag go up.
Protected Attributes inherited from WObject
bool objectbar
true if object bar is active.
Private Member Functions
virtual void setView (uint8_t view)
User View managment.
virtual void setGravity (bool flag)
enables/disables gravity.
void setGoingup (bool flag)
sets flog goingup.
void getMemory ()
Gets needed memory.
virtual void defaults ()
Sets default values.
virtual void makeSolid ()
User geometry.
virtual void setName ()
Sets user name.
virtual void checkMysql ()
Checks Mysql objects.
virtual void setCamera ()
Sets user camera.
virtual void setRtcp ()
Sets RTCP parameters.
virtual void addGui ()
Adds user to GUI.
Static Private Member Functions
static void createBullet (User *pu, void *d, time_t s, time_t u)
static void createDart (User *pu, void *d, time_t s, time_t u)
static void defaultZoom (User *pu, void *d, time_t s, time_t u)
static void increaseZoom (User *pu, void *d, time_t s, time_t u)
static void decreaseZoom (User *pu, void *d, time_t s, time_t u)
static void setZoom (User *pu, void *d, time_t s, time_t u)
static void defaultLinearSpeed (User *pu, void *d, time_t s, time_t u)
static void decreaseLinearSpeed (User *pu, void *d, time_t s, time_t u)
static void increaseLinearSpeed (User *pu, void *d, time_t s, time_t u)
static void setLspeed (User *pu, void *d, time_t s, time_t u)
static void defaultAngularSpeed (User *pu, void *d, time_t s, time_t u)
static void decreaseAngularSpeed (User *pu, void *d, time_t s, time_t u)
static void increaseAngularSpeed (User *pu, void *d, time_t s, time_t u)
static void setAspeed (User *pu, void *d, time_t s, time_t u)
static void switchView (User *pu, void *d, time_t s, time_t u)
static void papView (User *pu, void *d, time_t s, time_t u)
static void firstPersonView (User *pu, void *d, time_t s, time_t u)
static void thirdPersonViewFar (User *pu, void *d, time_t s, time_t u)
static void thirdPersonView_RotL (User *pu, void *d, time_t s, time_t u)
static void thirdPersonView_RotR (User *pu, void *d, time_t s, time_t u)
static void thirdPersonView_RotU (User *pu, void *d, time_t s, time_t u)
static void thirdPersonView_RotD (User *pu, void *d, time_t s, time_t u)
static void thirdPersonView_Near (User *pu, void *d, time_t s, time_t u)
static void thirdPersonView_Far (User *pu, void *d, time_t s, time_t u)
static void pause (User *pu, void *d, time_t s, time_t u)
static void pauseOn (User *pu, void *d, time_t s, time_t u)
static void pauseOff (User *pu, void *d, time_t s, time_t u)
static void mapView (User *pu, void *d, time_t s, time_t u)
static void setRoll (User *pu, void *d, time_t s, time_t u)
static void setPitch (User *pu, void *d, time_t s, time_t u)
static void increasePitch (User *pu, void *d, time_t s, time_t u)
static void decreasePitch (User *pu, void *d, time_t s, time_t u)
static void increaseRoll (User *pu, void *d, time_t s, time_t u)
static void decreaseRoll (User *pu, void *d, time_t s, time_t u)
static void flyaway (User *pu, void *d, time_t s, time_t u)
static void toland (User *pu, void *d, time_t s, time_t u)
static void get_username (User *pu, Payload *pp)
static void u_get_xy (WObject *po, Payload *pp)
static void u_get_z (WObject *po, Payload *pp)
static void u_get_ax (WObject *po, Payload *pp)
static void u_get_ay (WObject *po, Payload *pp)
static void u_get_az (WObject *po, Payload *pp)
static void get_msg (User *pu, Payload *pp)
static void get_infos (User *pu, Payload *pp)
static void get_mensuration (User *pu, Payload *pp)
static void get_mapfront (User *pu, Payload *pp)
static void get_mapback (User *pu, Payload *pp)
static void get_mapleft (User *pu, Payload *pp)
static void get_mapright (User *pu, Payload *pp)
static void get_vre (User *pu, Payload *pp)
static void get_web (User *pu, Payload *pp)
static void get_model (User *pu, Payload *pp)
static void get_face (User *pu, Payload *pp)
static void get_sex (User *pu, Payload *pp)
static void get_head (User *pu, Payload *pp)
static void get_skin (User *pu, Payload *pp)
static void get_bust (User *pu, Payload *pp)
static void get_color (User *pu, Payload *pp)
static void get_ssrc (User *pu, Payload *pp)
static void get_rtcpname (User *pu, Payload *pp)
static void get_rtcpemail (User *pu, Payload *pp)
static void get_ray (User *pu, Payload *pp)
static void put_username (User *pu, Payload *pp)
static void put_msg (User *pu, Payload *pp)
static void put_infos (User *pu, Payload *pp)
static void put_mensuration (User *pu, Payload *pp)
static void put_mapfront (User *pu, Payload *pp)
static void put_mapback (User *pu, Payload *pp)
static void put_mapleft (User *pu, Payload *pp)
static void put_mapright (User *pu, Payload *pp)
static void put_vre (User *pu, Payload *pp)
static void put_web (User *pu, Payload *pp)
static void put_model (User *pu, Payload *pp)
static void put_face (User *pu, Payload *pp)
static void put_sex (User *pu, Payload *pp)
static void put_head (User *pu, Payload *pp)
static void put_skin (User *pu, Payload *pp)
static void put_bust (User *pu, Payload *pp)
static void put_color (User *pu, Payload *pp)
static void put_ssrc (User *pu, Payload *pp)
static void put_rtcpname (User *pu, Payload *pp)
static void put_rtcpemail (User *pu, Payload *pp)
static void put_ray (User *pu, Payload *pp)
Friends
class WObject
Additional Inherited Members
Static Protected Member Functions inherited from WObject
static void get_xy (WObject *po, class Payload *pp)
static void get_z (WObject *po, class Payload *pp)
static void get_az (WObject *po, class Payload *pp)
static void get_ay (WObject *po, class Payload *pp)
static void get_ax (WObject *po, class Payload *pp)
static void get_hname (WObject *po, class Payload *pp)
static void put_xy (WObject *po, class Payload *pp)
static void put_z (WObject *po, class Payload *pp)
static void put_az (WObject *po, class Payload *pp)
static void put_ay (WObject *po, class Payload *pp)
static void put_ax (WObject *po, class Payload *pp)
static void put_hname (WObject *po, class Payload *pp)
Detailed Description
User class.
Definition at line 42 of file user.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
PROPHNAME
PROPMAPFRONT
PROPMAPBACK
PROPXY
PROPZ
PROPAZ
PROPAY
PROPAX
PROPMSG
PROPMENSURATION
PROPMAPLEFT
PROPMAPRIGHT
PROPVRE
PROPWEB
PROPSSRC
PROPRTCPNAME
PROPRTCPEMAIL
PROPMODEL
PROPFACE
PROPSEX
PROPHEAD
PROPSKIN
PROPBUST
PROPRAY
PROPS
Definition at line 125 of file user.hpp.
anonymous enum
anonymous enum
Enumerator
PROPBEGINVAR
PROPENDVAR
Definition at line 152 of file user.hpp.
Constructor & Destructor Documentation
User() [1/2]
User::User ()
Returns instance of this class.
Constructor builtin.
Definition at line 325 of file user.cpp.
References defaults(), inits(), and localuser.
Referenced by replicator().
User() [2/2]
User::User (uint8_t type_id, Noid noid, Payload * pp)
Constructor replicator.
Definition at line 338 of file user.cpp.
References addGui(), back, WObject::copyNoid(), DBG_WO, DEFAULTDEPTH, DEFAULTHEIGHT, defaults(), DEFAULTWIDTH, email, error(), face, front, WObject::getInstance(), getMemory(), NetObject::getPropertiesNumber(), NetObject::getProperty(), WObject::initializeMobileObject(), mensuration, model, Names::named, WObject::names, WObject::noh, notice(), WObject::parse(), Parse::parseSolid(), PROPBEGINVAR, PROPBUST, PROPENDVAR, PROPFACE, PROPHEAD, PROPHNAME, PROPMAPBACK, PROPMAPFRONT, PROPMAPLEFT, PROPMAPRIGHT, PROPMENSURATION, PROPMODEL, PROPRAY, PROPRTCPEMAIL, PROPRTCPNAME, PROPS, PROPSEX, PROPSKIN, PROPSSRC, PROPVRE, PROPWEB, WObject::replicateVolatileNetObject(), rtcpname, Payload::seekPayload(), SEP, ssrc, Payload::tellPayload(), Payload::tellStrInPayload(), trace(), Names::type, WObject::type, vre, and web.
~User()
User::~User () virtual
Destructor.
Definition at line 444 of file user.cpp.
References back, bust, color, NetObject::declareDeletion(), face, front, g, Global::gui, headurl, left, localuser, model, WObject::noh, Gui::removeUser(), right, sex, skin, vre, and web.
Member Function Documentation
addGui()
void User::addGui () private virtual
Adds user to GUI.
Definition at line 246 of file user.cpp.
References Gui::addUser(), g, Global::gui, and WObject::guip.
Referenced by inits(), and User().
bulletPutHit()
void User::bulletPutHit (class Bullet * po, Payload * pp) static
Definition at line 556 of file user.cpp.
References Projectile::hit, and Payload::putPayload().
Referenced by Bullet::funcs().
changePermanent()
void User::changePermanent (float lasting) virtual
Permanent movement.
Reimplemented from WObject.
Definition at line 541 of file user.cpp.
References GRAVITY, pause_gravity, WObject::pos, and Pos::z.
changePosition() [1/2]
void User::changePosition (const float lasting[]) virtual
Does the motion in each direction.
Definition at line 216 of file move.cpp.
References Pos::ax, Pos::ay, changePositionOneDir(), World::current(), World::getGround(), guy, KEY_VI, kpressed, M_PI, M_PI_4, man, MAXKEYS, MIN, MIN_KEYLASTING, Man::pos, WObject::pos, Guy::setAniming(), Guy::setFlying(), and Pos::z.
changePosition() [2/2]
void User::changePosition (float lasting) virtual
Imposed movement.
Reimplemented from WObject.
Definition at line 527 of file user.cpp.
References Move::aspeed, Pos::az, Move::lspeed, WObject::move, WObject::pos, V3::v, Pos::x, Pos::y, and Pos::z.
Referenced by elementaryUserMovement().
changePositionOneDir()
void User::changePositionOneDir (const int move_type, const float last) virtual
Modifies user position in one direction.
Definition at line 149 of file move.cpp.
References aspeed, Pos::ax, Pos::ay, Pos::az, carrier, Cos(), Carrier::isTaking(), KEY_AR, KEY_AV, KEY_DE, KEY_DR, KEY_GA, KEY_HZ, KEY_JD, KEY_JU, KEY_MT, KEY_SD, KEY_SG, KEY_TL, KEY_TR, lspeed, M_2PI, M_2PI_5, MAX, MIN, Carrier::mouseEvent(), WObject::pos, Sin(), Pos::x, Pos::y, and Pos::z.
Referenced by changePosition().
checkMysql()
void User::checkMysql () private virtual
Checks Mysql objects.
Definition at line 251 of file user.cpp.
References doAction(), DRESS_NAME, DRESS_TYPE, WObject::getInstance(), HALO_NAME, HALO_TYPE, HAT_NAME, HAT_TYPE, Dress::RECREATE, Halo::RECREATE, Hat::RECREATE, Wings::RECREATE, WINGS_NAME, and WINGS_TYPE.
Referenced by inits().
clearKeyTab()
void User::clearKeyTab () virtual
Clears keys times array.
Definition at line 64 of file move.cpp.
References kpdur_s, kpdur_u, kpressed, kpstart_s, kpstart_u, and MAXKEYS.
Referenced by inits().
createBullet()
void User::createBullet (User * pu, void * d, time_t s, time_t u) static private
Definition at line 662 of file user.cpp.
References BULLET_TYPE, Projectile::CREATE, d, doAction(), and isAction().
Referenced by funcs().
createDart()
void User::createDart (User * pu, void * d, time_t s, time_t u) static private
Definition at line 667 of file user.cpp.
References Projectile::CREATE, d, DART_TYPE, doAction(), and isAction().
Referenced by funcs().
dartPutHit()
void User::dartPutHit (class Dart * po, Payload * pp) static
Definition at line 561 of file user.cpp.
References Projectile::hit, and Payload::putPayload().
Referenced by Dart::funcs().
decreaseAngularSpeed()
void User::decreaseAngularSpeed (User * pu, void * d, time_t s, time_t u) static private
Definition at line 790 of file user.cpp.
References aspeed.
Referenced by funcs().
decreaseLinearSpeed()
void User::decreaseLinearSpeed (User * pu, void * d, time_t s, time_t u) static private
Definition at line 769 of file user.cpp.
References lspeed.
Referenced by funcs().
decreasePitch()
void User::decreasePitch (User * pu, void * d, time_t s, time_t u) static private
Definition at line 756 of file user.cpp.
References Pos::ay, M_PI, M_PI_2, WObject::pos, WObject::updatePosition(), and Pos::z.
Referenced by funcs().
decreaseRoll()
void User::decreaseRoll (User * pu, void * d, time_t s, time_t u) static private
Definition at line 716 of file user.cpp.
References Pos::ax, M_PI, M_PI_2, WObject::pos, WObject::updatePosition(), and Pos::z.
Referenced by funcs().
decreaseZoom()
void User::decreaseZoom (User * pu, void * d, time_t s, time_t u) static private
Definition at line 686 of file user.cpp.
References Render::cameraProjection(), FAR, fovy, g, near, and Global::render.
Referenced by funcs().
defaultAngularSpeed()
void User::defaultAngularSpeed (User * pu, void * d, time_t s, time_t u) static private
Definition at line 785 of file user.cpp.
References ASPEED, and aspeed.
Referenced by funcs().
defaultLinearSpeed()
void User::defaultLinearSpeed (User * pu, void * d, time_t s, time_t u) static private
Definition at line 764 of file user.cpp.
References LSPEED, and lspeed.
Referenced by funcs().
defaults()
void User::defaults () private virtual
Sets default values.
Definition at line 79 of file user.cpp.
References android, ASPEED, aspeed, bubble, carrier, cart, current_view, DEFAULTDEPTH, DEFAULTHEIGHT, DEFAULTWIDTH, depth, goingup, guy, head, height, hit, LSPEED, lspeed, man, newV3(), WObject::pos, ray, width, and Pos::z.
Referenced by User().
defaultZoom()
void User::defaultZoom (User * pu, void * d, time_t s, time_t u) static private
Definition at line 672 of file user.cpp.
References Render::cameraProjection(), FAR, fovy, FOVY, g, near, NEAR, and Global::render.
Referenced by funcs().
disableGravity()
void User::disableGravity () virtual
disables gravity.
Definition at line 894 of file user.cpp.
References pause_gravity.
Referenced by endMovement().
elementaryUserMovement()
void User::elementaryUserMovement (const float lastings[]) virtual
User motion limited by the maxlast.
Definition at line 318 of file move.cpp.
References changePosition(), WObject::checkVicinity(), WObject::copyPositionAndBB(), WObject::updatePosition(), and WObject.
Referenced by userMovement().
enableGravity()
void User::enableGravity () virtual
enables gravity.
Definition at line 889 of file user.cpp.
References pause_gravity.
Referenced by endMovement().
firstPersonView()
void User::firstPersonView (User * pu, void * d, time_t s, time_t u) static private
Definition at line 816 of file user.cpp.
References setView(), and Render::VIEW_FIRST_PERSON.
Referenced by funcs().
flyaway()
void User::flyaway (User * pu, void * d, time_t s, time_t u) static private
Definition at line 724 of file user.cpp.
References Pos::ay, M_PI, pause_gravity, WObject::pos, WObject::updatePosition(), and Pos::z.
Referenced by funcs().
funcs()
void User::funcs () static
init funclist.
user functions initialization
Definition at line 1111 of file user.cpp.
References createBullet(), createDart(), decreaseAngularSpeed(), decreaseLinearSpeed(), decreasePitch(), decreaseRoll(), decreaseZoom(), defaultAngularSpeed(), defaultLinearSpeed(), defaultZoom(), firstPersonView(), flyaway(), get_bust(), get_face(), get_head(), get_mapback(), get_mapfront(), get_mapleft(), get_mapright(), get_mensuration(), get_model(), get_msg(), get_ray(), get_rtcpemail(), get_rtcpname(), get_sex(), get_skin(), get_ssrc(), get_username(), get_vre(), get_web(), getPropertyFunc(), increaseAngularSpeed(), increaseLinearSpeed(), increasePitch(), increaseRoll(), increaseZoom(), mapView(), pause(), pauseOff(), pauseOn(), PROPAX, PROPAY, PROPAZ, PROPBUST, PROPFACE, PROPHEAD, PROPHNAME, PROPMAPBACK, PROPMAPFRONT, PROPMAPLEFT, PROPMAPRIGHT, PROPMENSURATION, PROPMODEL, PROPMSG, PROPRAY, PROPRTCPEMAIL, PROPRTCPNAME, PROPSEX, PROPSKIN, PROPSSRC, PROPVRE, PROPWEB, PROPXY, PROPZ, WObject::put_ax(), WObject::put_ay(), WObject::put_az(), put_bust(), put_face(), put_head(), put_mapback(), put_mapfront(), put_mapleft(), put_mapright(), put_mensuration(), put_model(), put_msg(), put_ray(), put_rtcpemail(), put_rtcpname(), put_sex(), put_skin(), put_ssrc(), put_username(), put_vre(), put_web(), WObject::put_xy(), WObject::put_z(), putPropertyFunc(), setActionFunc(), setAspeed(), setLspeed(), setPitch(), setRoll(), setZoom(), switchView(), thirdPersonView_Far(), thirdPersonView_Near(), thirdPersonView_RotD(), thirdPersonView_RotL(), thirdPersonView_RotR(), thirdPersonView_RotU(), thirdPersonViewFar(), toland(), u_get_ax(), u_get_ay(), u_get_az(), u_get_xy(), u_get_z(), UserAction::UA_ASPEEDDEF, UserAction::UA_ASPEEDLESS, UserAction::UA_ASPEEDMORE, UserAction::UA_BULLET, UserAction::UA_DART, UserAction::UA_FIRSTVIEW, UserAction::UA_FLYAWAY, UserAction::UA_FOVYDEF, UserAction::UA_FOVYLESS, UserAction::UA_FOVYMORE, UserAction::UA_FOVYSET, UserAction::UA_LSPEEDDEF, UserAction::UA_LSPEEDLESS, UserAction::UA_LSPEEDMORE, UserAction::UA_MAPVIEW, UserAction::UA_PAUSE, UserAction::UA_PAUSEOFF, UserAction::UA_PAUSEON, UserAction::UA_PITCHLESS, UserAction::UA_PITCHMORE, UserAction::UA_ROLLLESS, UserAction::UA_ROLLMORE, UserAction::UA_SETASPEED, UserAction::UA_SETLSPEED, UserAction::UA_SETPITCH, UserAction::UA_SETROLL, UserAction::UA_SWITCHVIEW, UserAction::UA_THIRDVIEWFAR, UserAction::UA_TOLAND, UserAction::UA_TPVIEWROTD, UserAction::UA_TPVIEWROTF, UserAction::UA_TPVIEWROTL, UserAction::UA_TPVIEWROTN, UserAction::UA_TPVIEWROTR, UserAction::UA_TPVIEWROTU, USER_TYPE, WO_ACTION, and WO_PAYLOAD.
get_bust()
void User::get_bust (User * pu, Payload * pp) static private
Definition at line 1007 of file user.cpp.
References bust, and Payload::getPayload().
Referenced by funcs().
get_color()
void User::get_color (User * pu, Payload * pp) static private
Definition at line 1010 of file user.cpp.
References color, and Payload::getPayload().
get_face()
void User::get_face (User * pu, Payload * pp) static private
Definition at line 995 of file user.cpp.
References face, and Payload::getPayload().
Referenced by funcs().
get_head()
void User::get_head (User * pu, Payload * pp) static private
Definition at line 1001 of file user.cpp.
References Payload::getPayload(), and head.
Referenced by funcs().
get_infos()
void User::get_infos (User * pu, Payload * pp) static private
Definition at line 968 of file user.cpp.
References Payload::getPayload(), Names::infos, and WObject::names.
get_mapback()
void User::get_mapback (User * pu, Payload * pp) static private
Definition at line 977 of file user.cpp.
References back, and Payload::getPayload().
Referenced by funcs().
get_mapfront()
void User::get_mapfront (User * pu, Payload * pp) static private
Definition at line 974 of file user.cpp.
References front, and Payload::getPayload().
Referenced by funcs().
get_mapleft()
void User::get_mapleft (User * pu, Payload * pp) static private
Definition at line 980 of file user.cpp.
References Payload::getPayload(), and left.
Referenced by funcs().
get_mapright()
void User::get_mapright (User * pu, Payload * pp) static private
Definition at line 983 of file user.cpp.
References Payload::getPayload(), and right.
Referenced by funcs().
get_mensuration()
void User::get_mensuration (User * pu, Payload * pp) static private
Definition at line 971 of file user.cpp.
References Payload::getPayload(), and mensuration.
Referenced by funcs().
get_model()
void User::get_model (User * pu, Payload * pp) static private
Definition at line 992 of file user.cpp.
References Payload::getPayload(), and model.
Referenced by funcs().
get_msg()
void User::get_msg (User * pu, Payload * pp) static private
Definition at line 950 of file user.cpp.
References bubble, Bubble::BUBBLEFRONT, g, getBubble(), WObject::getInstance(), Payload::getPayload(), Global::gui, lastmess, MESS_LEN, WObject::toDelete(), and Gui::writeMessage().
Referenced by funcs().
get_ray()
void User::get_ray (User * pu, Payload * pp) static private
Definition at line 1022 of file user.cpp.
References Payload::getPayload(), WObject::getSolid(), newV3(), Draw::ray(), ray, and Solid::ray_dlist.
Referenced by funcs().
get_rtcpemail()
void User::get_rtcpemail (User * pu, Payload * pp) static private
Definition at line 1019 of file user.cpp.
References email, and Payload::getPayload().
Referenced by funcs().
get_rtcpname()
void User::get_rtcpname (User * pu, Payload * pp) static private
Definition at line 1016 of file user.cpp.
References Payload::getPayload(), and rtcpname.
Referenced by funcs().
get_sex()
void User::get_sex (User * pu, Payload * pp) static private
Definition at line 998 of file user.cpp.
References Payload::getPayload(), and sex.
Referenced by funcs().
get_skin()
void User::get_skin (User * pu, Payload * pp) static private
Definition at line 1004 of file user.cpp.
References Payload::getPayload(), and skin.
Referenced by funcs().
get_ssrc()
void User::get_ssrc (User * pu, Payload * pp) static private
Definition at line 1013 of file user.cpp.
References Payload::getPayload(), and ssrc.
Referenced by funcs().
get_username()
void User::get_username (User * pu, Payload * pp) static private
Definition at line 899 of file user.cpp.
References DBG_WO, Payload::getPayload(), WObject::named(), and trace().
Referenced by funcs().
get_vre()
void User::get_vre (User * pu, Payload * pp) static private
Definition at line 986 of file user.cpp.
References Payload::getPayload(), and vre.
Referenced by funcs().
get_web()
void User::get_web (User * pu, Payload * pp) static private
Definition at line 989 of file user.cpp.
References Payload::getPayload(), and web.
Referenced by funcs().
getBubble()
Bubble * User::getBubble () const virtual
Gets bubble text.
Definition at line 551 of file user.cpp.
References bubble.
Referenced by get_msg(), and userWriting().
getMemory()
void User::getMemory () private
Gets needed memory.
Definition at line 423 of file user.cpp.
References back, baps, bust, color, email, Rtp::EMAIL_LEN, face, front, headurl, left, model, right, rtcpname, Rtp::RTPNAME_LEN, sex, skin, tool, Rtp::TOOL_LEN, URL_LEN, vre, and web.
Referenced by User().
getOClass()
virtual const OClass* User::getOClass () inline virtual
Reimplemented from WObject.
Definition at line 161 of file user.hpp.
References oclass.
hasHead()
bool User::hasHead () virtual
Returns boolean.
Definition at line 647 of file user.cpp.
References head.
Referenced by Guy::display_head().
increaseAngularSpeed()
void User::increaseAngularSpeed (User * pu, void * d, time_t s, time_t u) static private
Definition at line 795 of file user.cpp.
References aspeed.
Referenced by funcs().
increaseLinearSpeed()
void User::increaseLinearSpeed (User * pu, void * d, time_t s, time_t u) static private
Definition at line 774 of file user.cpp.
References lspeed.
Referenced by funcs().
increasePitch()
void User::increasePitch (User * pu, void * d, time_t s, time_t u) static private
Definition at line 748 of file user.cpp.
References Pos::ay, M_PI, M_PI_2, WObject::pos, WObject::updatePosition(), and Pos::z.
Referenced by funcs().
increaseRoll()
void User::increaseRoll (User * pu, void * d, time_t s, time_t u) static private
Definition at line 708 of file user.cpp.
References Pos::ax, M_PI, M_PI_2, WObject::pos, WObject::updatePosition(), and Pos::z.
Referenced by funcs().
increaseZoom()
void User::increaseZoom (User * pu, void * d, time_t s, time_t u) static private
Definition at line 679 of file user.cpp.
References Render::cameraProjection(), FAR, fovy, g, near, and Global::render.
Referenced by funcs().
inits()
void User::inits () virtual
Does needed initializations.
Definition at line 292 of file user.cpp.
References addGui(), carrier, cart, checkMysql(), clearKeyTab(), WObject::createVolatileNetObject(), current_view, WObject::enablePermanentMovement(), WObject::initializeMobileObject(), LASTING, makeSolid(), PROPS, WObject::RENDER_HIGH, setCamera(), setName(), setPosition(), WObject::setRenderPrior(), setRtcp(), setView(), WObject::updateNames(), WObject::updatePosition(), and Render::VIEW_FIRST_PERSON.
Referenced by World::enter(), and User().
makeSolid()
void User::makeSolid () private virtual
User geometry.
Definition at line 150 of file user.cpp.
References android, back, baps, bust, color, DBG_WO, depth, face, front, g, Color::getRGB(), guy, head, headurl, height, left, man, mensuration, model, Pref::my_avatar, Pref::my_bapsstr, Pref::my_buststr, Pref::my_colorstr, Pref::my_depthstr, Pref::my_facestr, Pref::my_headstr, Pref::my_heightstr, Pref::my_mapbackstr, Pref::my_mapfrontstr, Pref::my_sexstr, Pref::my_skinstr, Pref::my_vrestr, Pref::my_webstr, Pref::my_widthstr, WObject::parse(), Parse::parseSolid(), Global::pref, right, SEP, sex, skin, Global::skinb, Global::skinf, trace(), vre, web, and width.
Referenced by inits().
mapView()
void User::mapView (User * pu, void * d, time_t s, time_t u) static private
Definition at line 806 of file user.cpp.
References g, Global::render, and Render::switchViewMap().
Referenced by funcs().
papView()
static void User::papView (User * pu, void * d, time_t s, time_t u) static private
pause()
void User::pause (User * pu, void * d, time_t s, time_t u) static private
Definition at line 869 of file user.cpp.
References pause_gravity.
Referenced by funcs().
pauseOff()
void User::pauseOff (User * pu, void * d, time_t s, time_t u) static private
Definition at line 879 of file user.cpp.
References pause_gravity.
Referenced by funcs().
pauseOn()
void User::pauseOn (User * pu, void * d, time_t s, time_t u) static private
Definition at line 874 of file user.cpp.
References pause_gravity.
Referenced by funcs().
put_bust()
void User::put_bust (User * pu, Payload * pp) static private
Definition at line 1086 of file user.cpp.
References bust, and Payload::putPayload().
Referenced by funcs().
put_color()
void User::put_color (User * pu, Payload * pp) static private
Definition at line 1089 of file user.cpp.
References color, and Payload::putPayload().
put_face()
void User::put_face (User * pu, Payload * pp) static private
Definition at line 1074 of file user.cpp.
References face, and Payload::putPayload().
Referenced by funcs().
put_head()
void User::put_head (User * pu, Payload * pp) static private
Definition at line 1080 of file user.cpp.
References head, and Payload::putPayload().
Referenced by funcs().
put_infos()
void User::put_infos (User * pu, Payload * pp) static private
Definition at line 1047 of file user.cpp.
References Names::infos, WObject::names, and Payload::putPayload().
put_mapback()
void User::put_mapback (User * pu, Payload * pp) static private
Definition at line 1056 of file user.cpp.
References back, and Payload::putPayload().
Referenced by funcs().
put_mapfront()
void User::put_mapfront (User * pu, Payload * pp) static private
Definition at line 1053 of file user.cpp.
References front, and Payload::putPayload().
Referenced by funcs().
put_mapleft()
void User::put_mapleft (User * pu, Payload * pp) static private
Definition at line 1059 of file user.cpp.
References left, and Payload::putPayload().
Referenced by funcs().
put_mapright()
void User::put_mapright (User * pu, Payload * pp) static private
Definition at line 1062 of file user.cpp.
References Payload::putPayload(), and right.
Referenced by funcs().
put_mensuration()
void User::put_mensuration (User * pu, Payload * pp) static private
Definition at line 1050 of file user.cpp.
References mensuration, and Payload::putPayload().
Referenced by funcs().
put_model()
void User::put_model (User * pu, Payload * pp) static private
Definition at line 1071 of file user.cpp.
References model, and Payload::putPayload().
Referenced by funcs().
put_msg()
void User::put_msg (User * pu, Payload * pp) static private
Definition at line 1044 of file user.cpp.
References lastmess, message, and Payload::putPayload().
Referenced by funcs().
put_ray()
void User::put_ray (User * pu, Payload * pp) static private
Definition at line 1101 of file user.cpp.
References DBG_WO, height, WObject::pos, Payload::putPayload(), ray, trace(), V3::v, Pos::x, Pos::y, and Pos::z.
Referenced by funcs().
put_rtcpemail()
void User::put_rtcpemail (User * pu, Payload * pp) static private
Definition at line 1098 of file user.cpp.
References email, and Payload::putPayload().
Referenced by funcs().
put_rtcpname()
void User::put_rtcpname (User * pu, Payload * pp) static private
Definition at line 1095 of file user.cpp.
References Payload::putPayload(), and rtcpname.
Referenced by funcs().
put_sex()
void User::put_sex (User * pu, Payload * pp) static private
Definition at line 1077 of file user.cpp.
References Payload::putPayload(), and sex.
Referenced by funcs().
put_skin()
void User::put_skin (User * pu, Payload * pp) static private
Definition at line 1083 of file user.cpp.
References Payload::putPayload(), and skin.
Referenced by funcs().
put_ssrc()
void User::put_ssrc (User * pu, Payload * pp) static private
Definition at line 1092 of file user.cpp.
References Payload::putPayload(), and ssrc.
Referenced by funcs().
put_username()
void User::put_username (User * pu, Payload * pp) static private
Definition at line 1041 of file user.cpp.
References WObject::named(), and Payload::putPayload().
Referenced by funcs().
put_vre()
void User::put_vre (User * pu, Payload * pp) static private
Definition at line 1065 of file user.cpp.
References Payload::putPayload(), and vre.
Referenced by funcs().
put_web()
void User::put_web (User * pu, Payload * pp) static private
Definition at line 1068 of file user.cpp.
References Payload::putPayload(), and web.
Referenced by funcs().
replicator()
WObject * User::replicator (uint8_t type_id, Noid noid, Payload * pp) static
Replicates a remote avatar.
Definition at line 333 of file user.cpp.
References User().
resetBubble()
void User::resetBubble () virtual
Resets bubble text.
Definition at line 546 of file user.cpp.
References bubble.
Referenced by Bubble::updateTime().
resetPosition()
void User::resetPosition () virtual
Resets user position.
Definition at line 108 of file user.cpp.
References Pos::ax, Pos::az, height, WObject::pos, Pos::x, Pos::y, and Pos::z.
Referenced by World::quit(), and setPosition().
setAspeed()
void User::setAspeed (User * pu, void * d, time_t s, time_t u) static private
Definition at line 800 of file user.cpp.
References aspeed, and d.
Referenced by funcs().
setCamera()
void User::setCamera () private virtual
Sets user camera.
Definition at line 241 of file user.cpp.
References Render::cameraProjection(), FAR, FOVY, g, NEAR, and Global::render.
Referenced by inits().
setGoingup()
void User::setGoingup (bool flag) private
sets flog goingup.
Definition at line 535 of file user.cpp.
References goingup.
setGravity()
void User::setGravity (bool flag) private virtual
enables/disables gravity.
Definition at line 884 of file user.cpp.
References pause_gravity.
setLspeed()
void User::setLspeed (User * pu, void * d, time_t s, time_t u) static private
Definition at line 779 of file user.cpp.
References d, and lspeed.
Referenced by funcs().
setName()
void User::setName () private virtual
Sets user name.
Definition at line 100 of file user.cpp.
References WObject::explicitName(), g, Names::instance, Names::named, WObject::names, and Global::user.
Referenced by inits().
setPitch()
void User::setPitch (User * pu, void * d, time_t s, time_t u) static private
Definition at line 742 of file user.cpp.
References d, DEG2RAD, g, Global::render, and Render::setPitch().
Referenced by funcs().
setPosition()
void User::setPosition () virtual
Sets user position.
Definition at line 117 of file user.cpp.
References Entry::current(), Entry::query(), and resetPosition().
Referenced by inits().
setRayDirection()
void User::setRayDirection (GLint x, GLint y) virtual
Lanche a ray in thar direction.
Definition at line 615 of file user.cpp.
References Render::clickDirection(), d, NetObject::declareObjDelta(), FAR, g, WObject::getSolid(), height, MAX, MIN, near, newV3(), WObject::noh, WObject::pos, PROPRAY, Draw::ray(), ray, Global::render, Color::white, Pos::x, Pos::y, and Pos::z.
Referenced by Widgets::setRayDirection().
setRoll()
void User::setRoll (User * pu, void * d, time_t s, time_t u) static private
Definition at line 702 of file user.cpp.
References Pos::ax, d, DEG2RAD, and WObject::pos.
Referenced by funcs().
setRtcp()
void User::setRtcp () private virtual
Sets RTCP parameters.
Definition at line 229 of file user.cpp.
References DBG_WO, email, Rtp::EMAIL_LEN, WObject::getInstance(), NetObject::getMySsrcId(), Rtp::getRtcpEmail(), Rtp::getRtcpName(), Rtp::getRtcpTool(), rtcpname, Rtp::RTPNAME_LEN, ssrc, tool, Rtp::TOOL_LEN, and trace().
Referenced by inits().
setView()
void User::setView (uint8_t view) private virtual
User View managment.
Definition at line 128 of file user.cpp.
References current_view, WObject::disableBehavior(), WObject::enableBehavior(), g, head, Global::render, Render::setViewMode(), UNVISIBLE, Render::VIEW_FIRST_PERSON, Render::VIEW_THIRD_PERSON, Render::VIEW_THIRD_PERSON_FAR, Render::VIEW_TURN_AROUND, Render::VIEW_VERTICAL, Render::VIEW_VERTICAL_FAR, and Head::visibility().
Referenced by firstPersonView(), inits(), switchView(), and thirdPersonViewFar().
setZoom()
void User::setZoom (User * pu, void * d, time_t s, time_t u) static private
Definition at line 693 of file user.cpp.
References Render::cameraProjection(), d, FAR, fovy, g, near, and Global::render.
Referenced by funcs().
specialAction()
void User::specialAction (int act_id, void * data, time_t sec, time_t usec) virtual
Special action to do.
Reimplemented from WObject.
Definition at line 652 of file user.cpp.
References carrier, d, doAction(), isAction(), Carrier::isTaking(), and WObject::type.
Referenced by Widgets::callAction(), Pitch::doAction(), Navig::keyPressCB(), and Motion::move().
switchView()
void User::switchView (User * pu, void * d, time_t s, time_t u) static private
Definition at line 811 of file user.cpp.
References g, Render::getViewMode(), Global::render, setView(), and Render::VIEW_NUMBER.
Referenced by funcs().
thirdPersonView_Far()
void User::thirdPersonView_Far (User * pu, void * d, time_t s, time_t u) static private
Definition at line 862 of file user.cpp.
References g, Global::render, WObject::render(), and Render::VIEW_THIRD_PERSON.
Referenced by funcs().
thirdPersonView_Near()
void User::thirdPersonView_Near (User * pu, void * d, time_t s, time_t u) static private
Definition at line 854 of file user.cpp.
References g, Global::render, WObject::render(), and Render::VIEW_THIRD_PERSON.
Referenced by funcs().
thirdPersonView_RotD()
void User::thirdPersonView_RotD (User * pu, void * d, time_t s, time_t u) static private
Definition at line 846 of file user.cpp.
References g, M_PI, M_PI_2, Global::render, WObject::render(), and Render::VIEW_THIRD_PERSON.
Referenced by funcs().
thirdPersonView_RotL()
void User::thirdPersonView_RotL (User * pu, void * d, time_t s, time_t u) static private
Definition at line 826 of file user.cpp.
References g, Render::getViewMode(), M_PI, Global::render, Render::thirdPerson_xRot, and Render::VIEW_THIRD_PERSON.
Referenced by funcs().
thirdPersonView_RotR()
void User::thirdPersonView_RotR (User * pu, void * d, time_t s, time_t u) static private
Definition at line 832 of file user.cpp.
References g, Render::getViewMode(), M_PI, Global::render, Render::thirdPerson_xRot, and Render::VIEW_THIRD_PERSON.
Referenced by funcs().
thirdPersonView_RotU()
void User::thirdPersonView_RotU (User * pu, void * d, time_t s, time_t u) static private
Definition at line 838 of file user.cpp.
References g, M_PI, M_PI_2, Global::render, WObject::render(), and Render::VIEW_THIRD_PERSON.
Referenced by funcs().
thirdPersonViewFar()
void User::thirdPersonViewFar (User * pu, void * d, time_t s, time_t u) static private
Definition at line 821 of file user.cpp.
References setView(), and Render::VIEW_THIRD_PERSON_FAR.
Referenced by funcs().
toland()
void User::toland (User * pu, void * d, time_t s, time_t u) static private
Definition at line 732 of file user.cpp.
References Pos::ay, g, Render::getViewMode(), M_PI, pause_gravity, WObject::pos, Global::render, WObject::updatePosition(), and Render::VIEW_FIRST_PERSON.
Referenced by funcs().
u_get_ax()
void User::u_get_ax (WObject * po, Payload * pp) static private
Definition at line 923 of file user.cpp.
References WObject::get_ax(), localuser, notice(), WObject::pos, and WObject::updateCamera().
Referenced by funcs().
u_get_ay()
void User::u_get_ay (WObject * po, Payload * pp) static private
Definition at line 932 of file user.cpp.
References WObject::get_ay(), localuser, notice(), WObject::pos, and WObject::updateCamera().
Referenced by funcs().
u_get_az()
void User::u_get_az (WObject * po, Payload * pp) static private
Definition at line 941 of file user.cpp.
References WObject::get_az(), localuser, notice(), WObject::pos, and WObject::updateCamera().
Referenced by funcs().
u_get_xy()
void User::u_get_xy (WObject * po, Payload * pp) static private
Definition at line 905 of file user.cpp.
References WObject::get_xy(), localuser, notice(), WObject::pos, and WObject::updateCamera().
Referenced by funcs().
u_get_z()
void User::u_get_z (WObject * po, Payload * pp) static private
Definition at line 914 of file user.cpp.
References WObject::get_z(), localuser, notice(), WObject::pos, and WObject::updateCamera().
Referenced by funcs().
updateKeysTimes()
void User::updateKeysTimes (time_t sec, time_t usec) virtual
Updates the keydifftime arrays.
Definition at line 74 of file move.cpp.
References kpdur_s, kpdur_u, kpressed, kpstart_s, kpstart_u, and MAXKEYS.
Referenced by userMovement().
updateTime() [1/2]
void User::updateTime (float lasting[]) virtual
Fills delays's array for each user motion direction.
Definition at line 207 of file move.cpp.
References kpdur_s, kpdur_u, and MAXKEYS.
updateTime() [2/2]
void User::updateTime (time_t sec, time_t usec, float * last) virtual
Updates times.
Reimplemented from WObject.
Definition at line 491 of file user.cpp.
References WObject::updateLasting().
Referenced by userMovement().
updateTime2()
static void User::updateTime2 (WObject * pu, time_t sec, time_t usec, float * lasting) static
Updates times array.
updateToNetwork()
bool User::updateToNetwork (const Pos & oldpos) virtual
Publishes position to the network.
Reimplemented from WObject.
Definition at line 474 of file user.cpp.
References ABSF, Pos::az, NetObject::declareObjDelta(), DELTAZ, WObject::noh, WObject::pos, PROPAZ, PROPXY, PROPZ, Pos::x, Pos::y, and Pos::z.
Referenced by userMovement().
userMovement()
void User::userMovement (time_t sec, time_t usec) virtual
User general motion.
Definition at line 329 of file move.cpp.
References WObject::copyPosAndBB(), elementaryUserMovement(), error(), WObject::getLasting(), WObject::isValid(), MAXKEYS, MIN_LASTING, WObject::pos, WObject::type, WObject::updateCamera(), updateKeysTimes(), WObject::updatePositionAndGrid(), updateTime(), and updateToNetwork().
Referenced by World::compute().
userRequesting()
void User::userRequesting (const char * usermsg) static
Signals a message sent by an user.
Definition at line 516 of file user.cpp.
References NetObject::declareObjDelta(), lastmess, localuser, MESS_LEN, WObject::noh, PROPMSG, and request.
userWriting()
void User::userWriting (const char * usermsg) static
Signals a message sent by an user.
Definition at line 497 of file user.cpp.
References bubble, Bubble::BUBBLEBACK, NetObject::declareObjDelta(), getBubble(), KEYBOARDSND, lastmess, localuser, MESS_LEN, message, WObject::noh, Sound::playSound(), PROPMSG, and WObject::toDelete().
Referenced by Messages::actionCB().
whenIntersect()
bool User::whenIntersect (WObject * pcur, WObject * pold) virtual
When an other object intersects.
Reimplemented from WObject.
Definition at line 566 of file user.cpp.
References BALL_TYPE, BULLET_TYPE, COLLIDE_GHOST, WObject::copyPositionAndBB(), DART_TYPE, WObject::getInstance(), GOTHROUGH, hit, WObject::isBehavior(), WObject::names, WObject::noh, notice(), OUILLESND, Sound::playSound(), WObject::pos, Projectile::PROPHIT, RUPSSND, NetObject::sendDelta(), Ball::SHIFTX, Ball::SHIFTY, STEP_TYPE, THING_TYPE, WObject::toDelete(), Names::type, WObject::type, WObject::updatePositionAndGrid(), USER_TYPE, Pos::x, and Pos::y.
Friends And Related Function Documentation
WObject
friend class WObject friend
Definition at line 65 of file user.hpp.
Referenced by elementaryUserMovement().
Member Data Documentation
android
class Android* User::android
Android avatar model.
Definition at line 61 of file user.hpp.
Referenced by defaults(), Solid::displayMirroredScene(), and makeSolid().
ASPEED
const float User::ASPEED = 1. static
Definition at line 49 of file user.hpp.
Referenced by defaultAngularSpeed(), defaults(), and Navig::keyPressCB().
aspeed
float User::aspeed protected
angular speed.
Definition at line 67 of file user.hpp.
Referenced by changePositionOneDir(), decreaseAngularSpeed(), defaultAngularSpeed(), defaults(), increaseAngularSpeed(), and setAspeed().
back
char* User::back protected
url body back.
Definition at line 73 of file user.hpp.
Referenced by get_mapback(), getMemory(), makeSolid(), put_mapback(), User(), and ~User().
baps
char* User::baps protected
vaps server.
Definition at line 85 of file user.hpp.
Referenced by getMemory(), and makeSolid().
bubble
Bubble* User::bubble
bubble text.
Definition at line 115 of file user.hpp.
Referenced by defaults(), get_msg(), getBubble(), World::init(), resetBubble(), and userWriting().
bust
char* User::bust protected
bust color.
Definition at line 83 of file user.hpp.
Referenced by get_bust(), getMemory(), makeSolid(), put_bust(), and ~User().
carrier
Carrier* User::carrier
Carrier.
Definition at line 113 of file user.hpp.
Referenced by changePositionOneDir(), defaults(), inits(), Carrier::leaveControl(), WObject::moveObject(), specialAction(), and Carrier::takeControl().
cart
Cart* User::cart
Cart.
Definition at line 114 of file user.hpp.
Referenced by defaults(), Thing::dropIntoBasket(), inits(), and Gui::removeCart().
cname
char* User::cname
RTP cname.
Definition at line 106 of file user.hpp.
color
char* User::color protected
color.
Definition at line 84 of file user.hpp.
Referenced by get_color(), getMemory(), makeSolid(), put_color(), and ~User().
current_view
uint8_t User::current_view
current_view.
Definition at line 116 of file user.hpp.
Referenced by defaults(), inits(), and setView().
DEFAULTDEPTH
const float User::DEFAULTDEPTH = 0.16 static
Definition at line 46 of file user.hpp.
Referenced by defaults(), and User().
DEFAULTHEIGHT
const float User::DEFAULTHEIGHT = 1.70 static
Definition at line 47 of file user.hpp.
Referenced by defaults(), and User().
DEFAULTWIDTH
const float User::DEFAULTWIDTH = 0.26 static
Definition at line 45 of file user.hpp.
Referenced by defaults(), and User().
DELTAZ
const float User::DELTAZ = 0.02 static
Definition at line 50 of file user.hpp.
Referenced by updateToNetwork().
DENSITY
const float User::DENSITY = 1. static
Definition at line 55 of file user.hpp.
depth
float User::depth protected
body depth.
Definition at line 69 of file user.hpp.
Referenced by defaults(), and makeSolid().
email
char* User::email
user's email.
Definition at line 108 of file user.hpp.
Referenced by get_rtcpemail(), getMemory(), put_rtcpemail(), setRtcp(), setUser(), and User().
face
char* User::face protected
url face.
Definition at line 79 of file user.hpp.
Referenced by get_face(), getMemory(), makeSolid(), put_face(), User(), and ~User().
FAR
const float User::FAR = 300. static
Definition at line 54 of file user.hpp.
Referenced by Render::clickDirection(), decreaseZoom(), defaultZoom(), increaseZoom(), setCamera(), setRayDirection(), and setZoom().
FOVY
const float User::FOVY = 26. static
Definition at line 52 of file user.hpp.
Referenced by defaultZoom(), Render::map(), and setCamera().
front
char* User::front protected
url body front.
Definition at line 72 of file user.hpp.
Referenced by get_mapfront(), getMemory(), makeSolid(), put_mapfront(), User(), and ~User().
goingup
bool User::goingup protected
flag go up.
Definition at line 95 of file user.hpp.
Referenced by defaults(), and setGoingup().
GOTHROUGH
const float User::GOTHROUGH = 0.05 static
Definition at line 51 of file user.hpp.
Referenced by whenIntersect().
guy
class Guy* User::guy
Guy avatar model.
Definition at line 60 of file user.hpp.
Referenced by changePosition(), defaults(), Solid::displayMirroredScene(), and makeSolid().
head
class Head* User::head
Head avatar model.
Definition at line 62 of file user.hpp.
Referenced by defaults(), get_head(), hasHead(), makeSolid(), put_head(), and setView().
headurl
char* User::headurl protected
url head.
Definition at line 81 of file user.hpp.
Referenced by getMemory(), makeSolid(), and ~User().
height
float User::height
body height.
Definition at line 110 of file user.hpp.
Referenced by Book::approach(), Bullet::Bullet(), Lift::call(), Render::cameraPosition(), Android::changePermanent(), Head::changePermanent(), Step::changePermanent(), Board::click(), Vrelet::click(), Render::clickDirection(), Dart::Dart(), defaults(), Solid::displayMirroredScene(), Ground::Ground(), Cloth::inits(), makeSolid(), put_ray(), Entry::query(), resetPosition(), Bubble::setPosition(), Solid::setRay(), setRayDirection(), and WObject::updateCamera().
hit
uint8_t User::hit
hit.
Definition at line 112 of file user.hpp.
Referenced by defaults(), and whenIntersect().
host
char* User::host protected
url host.
Definition at line 77 of file user.hpp.
kpdur_s
time_t User::kpdur_s[MAXKEYS]
key press duration from starting time sec.
Definition at line 121 of file user.hpp.
Referenced by changeKey(), clearKeyTab(), updateKeysTimes(), and updateTime().
kpdur_u
time_t User::kpdur_u[MAXKEYS]
key press duration from starting time usec.
Definition at line 122 of file user.hpp.
Referenced by changeKey(), clearKeyTab(), updateKeysTimes(), and updateTime().
kpressed
bool User::kpressed[MAXKEYS]
is the key pressed ?
Definition at line 118 of file user.hpp.
Referenced by changeKey(), changePosition(), clearKeyTab(), and updateKeysTimes().
kpstart_s
time_t User::kpstart_s[MAXKEYS]
key press starting time (sec).
Definition at line 119 of file user.hpp.
Referenced by changeKey(), clearKeyTab(), and updateKeysTimes().
kpstart_u
time_t User::kpstart_u[MAXKEYS]
key press starting time (usec).
Definition at line 120 of file user.hpp.
Referenced by changeKey(), clearKeyTab(), and updateKeysTimes().
lastDistance
float User::lastDistance protected
Definition at line 88 of file user.hpp.
LASTING
const float User::LASTING = 0.015 static
Definition at line 44 of file user.hpp.
Referenced by inits().
lastmess
int User::lastmess protected
last message number.
Definition at line 93 of file user.hpp.
Referenced by get_msg(), put_msg(), userRequesting(), and userWriting().
lastrequest
int User::lastrequest protected
Definition at line 94 of file user.hpp.
lastSelected
WObject* User::lastSelected protected
Definition at line 87 of file user.hpp.
left
char* User::left protected
url body left.
Definition at line 74 of file user.hpp.
Referenced by get_mapleft(), getMemory(), makeSolid(), put_mapleft(), and ~User().
LSPEED
const float User::LSPEED = 2. static
Definition at line 48 of file user.hpp.
Referenced by defaultLinearSpeed(), defaults(), gotoXYZ(), Navig::keyPressCB(), Motion::move(), and WObject::moveUserToObject().
lspeed
float User::lspeed protected
linear speed.
Definition at line 66 of file user.hpp.
Referenced by changePositionOneDir(), decreaseLinearSpeed(), defaultLinearSpeed(), defaults(), increaseLinearSpeed(), and setLspeed().
man
class Man* User::man
Man avatar model.
Definition at line 59 of file user.hpp.
Referenced by changePosition(), defaults(), Solid::displayList(), Solid::displayMirroredScene(), makeSolid(), and Solid::solidParser().
mensuration
char User::mensuration[MENSURATIONLEN] protected
Definition at line 90 of file user.hpp.
Referenced by get_mensuration(), makeSolid(), put_mensuration(), and User().
MENSURATIONLEN
const uint8_t User::MENSURATIONLEN = 64 static
Definition at line 57 of file user.hpp.
MESS_LEN
const uint8_t User::MESS_LEN = 255 static
Definition at line 56 of file user.hpp.
Referenced by get_msg(), userRequesting(), and userWriting().
message
char User::message[MESS_LEN] protected
message buffer.
Definition at line 91 of file user.hpp.
Referenced by put_msg(), and userWriting().
model
char* User::model protected
url model.
Definition at line 78 of file user.hpp.
Referenced by get_model(), getMemory(), makeSolid(), put_model(), User(), and ~User().
NEAR
const float User::NEAR = 0.1 static
Definition at line 53 of file user.hpp.
Referenced by Render::clickDirection(), defaultZoom(), setCamera(), and Solid::setRay().
oclass
const OClass User::oclass static
class variable.
Definition at line 157 of file user.hpp.
Referenced by getOClass().
ray
V3 User::ray
ray extremity.
Definition at line 111 of file user.hpp.
Referenced by defaults(), get_ray(), put_ray(), Solid::resetRay(), Solid::setRay(), and setRayDirection().
request
char User::request[MESS_LEN] protected
Definition at line 92 of file user.hpp.
Referenced by userRequesting().
right
char* User::right protected
url body right.
Definition at line 75 of file user.hpp.
Referenced by get_mapright(), getMemory(), makeSolid(), put_mapright(), and ~User().
rtcpname
char* User::rtcpname
RTCP name.
Definition at line 107 of file user.hpp.
Referenced by get_rtcpname(), getMemory(), put_rtcpname(), setRtcp(), setUser(), and User().
sex
char* User::sex protected
sex.
Definition at line 80 of file user.hpp.
Referenced by get_sex(), getMemory(), makeSolid(), put_sex(), and ~User().
skin
char* User::skin protected
skin color.
Definition at line 82 of file user.hpp.
Referenced by get_skin(), getMemory(), makeSolid(), put_skin(), and ~User().
ssrc
uint32_t User::ssrc protected
ssrc id.
Definition at line 71 of file user.hpp.
Referenced by get_ssrc(), put_ssrc(), setRtcp(), and User().
tool
char* User::tool
tool used.
Definition at line 109 of file user.hpp.
Referenced by getMemory(), setRtcp(), and setUser().
vre
char* User::vre protected
url vre.
Definition at line 76 of file user.hpp.
Referenced by get_vre(), getMemory(), makeSolid(), put_vre(), User(), and ~User().
web
char* User::web
url web.
Definition at line 105 of file user.hpp.
Referenced by get_web(), getMemory(), makeSolid(), put_web(), setUser(), User(), and ~User().
width
float User::width protected
body width.
Definition at line 68 of file user.hpp.
Referenced by defaults(), and makeSolid().
The documentation for this class was generated from the following files:
src/wo/user.hpp
src/wo/move.cpp
src/wo/user.cpp