VREng: Water Class Reference
Water Class Reference
Water class.
#include <water.hpp>
Public Member Functions
virtual const OClass * getOClass ()
Water (char *l)
Constructor.
virtual void changePermanent (float lasting)
Changes the position during a permanent movement.
virtual bool whenIntersect (WObject *pcur, WObject *pold)
Handles an ingoing collision with another object.
virtual bool whenIntersectOut (WObject *pcur, WObject *pold)
Handles an outgoing collision with another object.
virtual void render ()
Makes special rendering.
Public Member Functions inherited from WObject
WObject ()
Constructor.
virtual ~WObject ()
Destructor.
virtual uint8_t typeId ()
Abstrct class.
virtual const char * typeName ()
WCreator * getCreator ()
WReplicator * getReplicator ()
virtual bool isMoving ()
Checks weither object is moving.
virtual void changePosition (float lasting)
Changes the position after a triggered movement.
virtual void updateTime (time_t sec, time_t usec, float *lasting)
Updates remaining times of the movement.
virtual bool updateToNetwork (const Pos &oldpos)
Publishes changes to the network.
virtual bool updatePosToNetwork (const Pos &oldpos, int propxy, int propz, int propaz, int propax, int propay)
Publishes position changes to the network.
virtual void whenWallsIntersect (WObject *pold, V3 *norm)
Handles collisions with walls.
virtual void lighting ()
Makes special lighting.
virtual void quit ()
Makes all thing when leaving the object.
const solidList & solids () const
solidlist address.
uint32_t countOfSolids () const
virtual class Solid * getSolid () const
Returns first solid.
virtual void addSolid (class Solid *solid)
Adds to solidList.
virtual void deleteSolids ()
Deletes solids from solidList.
virtual int interAABB (WObject *o1, WObject *o2)
virtual bool haveAction ()
Checks weither have actions.
virtual uint8_t numberAction ()
Number of actions.
virtual bool runAction (const char *action)
Runs action everwhere if available.
virtual void setType (int type)
Sets object type.
virtual int getType ()
Gets object type.
virtual int getNumber ()
Gets object number.
virtual uint16_t getNum ()
Gets a new object number.
virtual void getPosition (M4 &mpos)
Gives solid's position.
virtual void getRelativeBB (V3 &center, V3 &size)
virtual void getDim (V3 &dim)
virtual void getCenter (V3 &center)
virtual void getAbsoluteBB (V3 &center, V3 &size)
Gets relative or absolute center and size of solid.
virtual uint8_t getFrames ()
Gets number of frames of this solid.
virtual uint8_t getFrame ()
Gets index of current frame of this solid.
virtual void setFrame (uint8_t _frame)
Sets current frame.
virtual bool isValid () const
Checks if valid object type.
virtual bool isPermanent () const
Checks if permanent object.
virtual const char * named () const
Gets names.named.
virtual const char * getInstance () const
Gets names.instance.
virtual const char * urlName () const
Gets names.url.
virtual const char * ownerName () const
Gets names.owner.
virtual const char * worldName () const
Gets names.owner.
virtual bool explicitName () const
Checks wether the object is explicitly named.
virtual void toDelete ()
Delete this object latter.
virtual bool removeFromScene ()
Removes an object.
virtual bool isOwner () const
Returns true if owner.
virtual void setOwner (const char *_owner)
Initialize owner.
virtual void setOwner ()
Initialize local user as owner.
virtual void click (GLint x, GLint y)
Execute an object's click method if it's defined.
virtual void click (V3 norm)
Intercepts a click.
virtual char * tokenize (char *l)
Tokenizes the line <object ...
virtual Parse * parse ()
Gets current parse.
void setWObjectId ()
Sets the WObjectid.
void copyNoid (class Noid _noid)
Copies the NetObjectid in WObjectId.
void setSrcId (uint32_t src_id)
Sets the SrcId.
void setPortId (uint16_t port_id)
Sets the PortId.
void setObjId (uint16_t obj_id)
Sets the ObjId.
uint32_t getSrcId () const
Gets the SrcId.
uint16_t getPortId () const
Gets the PortId.
uint16_t getObjId () const
Gets the ObjId.
virtual void update3D (Pos &pos)
Updates object in the 3D.
virtual void updateAll3D (Pos &pos)
Updates object in the 3D.
virtual void updateCamera (Pos &pos)
Updates camera in the 3D.
virtual void getSurfVecs (Pos &pos, V3 *v, V3 *w, V3 *norm)
Returns two vectors that describe the object's surface and a normal vector to that surface.
virtual void updateBB ()
Updates object's Bounding Box.
virtual void getMaterials (GLfloat *dif, GLfloat *amb, GLfloat *spe, GLfloat *emi, GLint *shi, GLfloat *alpha)
virtual void insertIntoGrid ()
Adds an object into the grid.
virtual void deleteFromGrid ()
Deletes an object from the grid.
virtual void updateGrid (const float *bbminnew, const float *bbmaxnew, const float *bbminold, const float *bbmaxold)
Updates an object in the grid.
virtual void updateGrid (const Pos &oldpos)
virtual void updateGrid (const WObject *pold)
Updates an object into the grid.
virtual void addToList (std::list< WObject * > &olist)
virtual OList * addToList (OList *olist)
Adds an object pointer into a olist.
virtual void addToList ()
Adds an object pointer into a olist.
virtual void addToStill ()
Adds an object pointer into stillList.
virtual void addToMobile ()
Adds an object pointer into mobileList.
virtual void addToInvisible ()
Adds an object pointer into invisibleList.
virtual void addToRender ()
Adds an object pointer into renderList.
virtual void delFromMobile ()
Deletes an object pointer from mobileList.
virtual void clearList ()
Clears an olist.
virtual void clearList (std::list< WObject * > &olist)
Clears an olist.
virtual void addToListOnce (std::list< WObject * > &olist)
virtual OList * addToListOnce (OList *olist)
Adds an object pointer into a list only once time.
virtual void delFromList (std::list< WObject * > &olist)
virtual OList * delFromList (OList *olist)
Deletes an object pointer from a olist.
virtual void delFromList ()
Deletes an object pointer from a olist.
virtual OList * getVicinityList (const WObject *pold)
Returns list of pointers on objects touching cell where is the object.
virtual OList * addListToList (OList *list1, OList *list2)
Concatenation (test of "ispointed") of list pointers on an object.
virtual bool isStill ()
Checks an object exists in the stilllist.
virtual bool isMobile ()
virtual bool isEphemeral ()
Checks an object exists in the mobilelist.
virtual WObject * byWObject (WObject *po)
Gets a WObject from the lists.
virtual void checkVicinity (WObject *pold)
< Gets an object by its num.
virtual void imposedMovement (time_t sec, time_t usec)
Handles an object movement.
virtual void elementaryImposedMovement (float lasting)
Handles an elementary object movement.
virtual void enableImposedMovement ()
Enables movement on an object.
virtual void enablePermanentMovement ()
Enables permanent movement on an object.
virtual void disablePermanentMovement ()
Disables movement on an object.
virtual void enablePermanentMovement (float speed)
Enables permanent movement on an object.
virtual void initImposedMovement (float lasting)
Initializes movement on an object.
virtual float diffTime (time_t sec, time_t usec)
Updates times on an object.
virtual void stopImposedMovement ()
Stops a movement on an object.
virtual void permanentMovement (time_t sec, time_t usec)
Handles a permanent object movement.
virtual void elementaryPermanentMovement (float lasting)
Handles an elementary permanent object movement.
virtual void setLasting (float maxlast)
Sets the max lasting time of an object.
virtual float getLasting () const
Gets the lasting time of an object.
virtual bool testMoving ()
Tests if object is moving.
virtual bool updateLasting (time_t sec, time_t usec, float *lasting)
Updates remaining times of the movement.
virtual void moveUserToObject (float val, float _lttl, float _attl)
Moves the user to the object.
virtual void setObjectName (const char *str)
Sets an object name.
virtual WObject * getObjectByName (const char *str)
Gets an object by its name.
virtual void updateNames ()
Updates names.
virtual void initializeObject (uint8_t mode)
Initializes object.
virtual void initializeMobileObject (float last)
virtual void initializeEphemeralObject (float last)
Initializes mobile object.
virtual void initializeStillObject ()
Initializes still object.
void createPermanentNetObject (uint8_t props, uint16_t oid)
Creates local permanent NetObject.
void createVolatileNetObject (uint8_t props)
Creates local volatile NetObject.
void replicateVolatileNetObject (uint8_t props, class Noid _noid)
Replicate distant volatile NetObject.
virtual void enableBehavior (uint32_t flag)
Enables behavior.
virtual void disableBehavior (uint32_t flag)
Disables behavior.
virtual bool isBehavior (uint32_t flag) const
Checks weither this behavior is on.
virtual bool bbBehavior () const
Checks weither BBox behavior is on.
virtual bool isSeen ()
Checks weither the object is in the sight view of the user.
virtual void setVisible (bool flag)
Sets visible or not the 3D object.
virtual bool isVisible ()
Checks weither the object is visible.
virtual void setFlashy (float *color)
Sets flashy the 3D object.
virtual void setFlashy ()
Sets flashy the 3D object.
virtual void resetFlashy ()
Resets flashy the 3D object.
virtual void setRay (GLint wx, GLint wy)
virtual void resetRay ()
Resets Ray on the 3D object.
virtual void setReflexive (bool flag)
virtual bool isSelectable () const
Checks weither 3D selectable behavior is on.
virtual uint32_t collideBehavior () const
Returns collide behavior.
virtual void setRenderPrior (uint8_t _prior)
Sets render priority.
virtual uint8_t getRenderPrior () const
Gets render priority.
void generalIntersect (WObject *pold, OList *vicinityList)
General intersection of objects.
bool ingoingNeighbor (WObject *pold, WObject *neighbor)
bool outgoingNeighbor (WObject *pold, WObject *neighbor)
Checks ingoing intersection with a neighbor.
void ingoingWalls (WObject *pold)
Checks outgoing intersection with a neighbor.
virtual void copyPosAndBB (Pos &newpos)
Checks ingoing intersection with walls.
virtual void copyPositionAndBB (WObject *o)
Copy object position and Bounding Box.
virtual bool projectPosition (WObject *pcur, WObject *pold)
Projects object position.
virtual int projectPositionOnObstacle (Pos &pcur, Pos &pold, Pos &obstacle)
Projects object position on an obstacle.
virtual void initPosition ()
Init 3D and grid position.
virtual void updatePosition ()
Updating 3D.
virtual void updatePositionAndGrid (Pos &oldpos)
Updating 3D and grid position.
virtual void updatePositionAndGrid (WObject *pold)
Updating 3D and grid position.
virtual void computeNormal (WObject *mobil, V3 *normal)
Computes the normal of an object.
virtual void computeNormal (Pos &mobil, Pos &stil, V3 *normal)
Computes the normal of still object.
virtual void bounceTrajectory (WObject *pold, V3 *norm)
Intersects with wall.
void getProperty (uint8_t prop_id, class Payload *pp)
Gets the local copy property from the payload (pp->data).
void putProperty (uint8_t prop_id, class Payload *pp)
Puts the local copy property in the payload.
virtual void deleteReplica ()
Deletes a replicated object.
virtual struct GuiItem * getGui () const
Gets the GUI handle.
virtual bool isGui () const
Checks the GUI handle.
virtual void resetGui ()
Resets the GUI handle.
virtual void clearObjectBar ()
Clears the ObjectBar in the GUI.
virtual void specialAction (int action, void *data, time_t sec, time_t usec)
Calls methods dedicated to each object.
void getObjectHumanName (char **classname, char **instancename, char **actionnames)
Gives object's class_name & action names.
virtual void getMySqlPosition ()
Checks if position is managed by MySql and get it.
virtual void updateMySqlPosition ()
Checks if position is managed by MySql and update it.
virtual int16_t getMySqlState ()
Gets state from MySql.
virtual void updateMySqlPosZ ()
Checks if posZ is managed by MySql.
virtual void updateMySqlState (int16_t state)
Updates state for MySql.
virtual void flushMySqlPosition ()
Flushes position for MySql.
virtual void quitMySql ()
Quits MySql.
Static Public Member Functions
static void funcs ()
init funclist.
static WObject *() creator (char *l)
Creates from fileline.
Static Public Member Functions inherited from WObject
static int interAABB (V3 center1, V3 size1, V3 center2, V3 size2)
Computes intersection between 2 AABB (Axis Aligned Bounding Box).
static int interAABBVertical (V3 center1, V3 size1, V3 center2, V3 size2)
static int interAABBHorizontal (V3 center1, V3 size1, V3 center2, V3 size2)
static void show (const char *name)
Snaps position (debug).
static WObject * byNum (uint16_t num)
static void moveObject (WObject *po, void *d, time_t s, time_t u)
User moves the object.
static void getObjectNameById (uint8_t type_id, char *name)
Gets a name by its id.
static void resetObjectsNumber ()
Resets object seq.
static uint32_t getObjectsNumber ()
Gets current object sequence number.
Static Public Attributes
static const float DEF_TRANSP = 0.8
static const float DEF_HEIGHT = 0.15
static const float DEF_AMPLITUDE = 0.05
static const float DEF_FREQ = 1.
static const float DEF_PHASE = 0.0001
static const float INCR_AMPLITUDE = 0.01
static const float INCR_FREQ = 1.
static const float INCR_PHASE = 0.00005
static const float INCR_TRANSP = 0.05
static const OClass oclass
class variable.
Private Member Functions
virtual void parser (char *l)
Parses file line.
virtual void defaults ()
Sets default values.
virtual void behavior ()
Sets behaviors.
virtual void inits ()
Makes initializations.
virtual void draw ()
Draws geometry.
virtual void sound ()
Static Private Member Functions
static void sound_continue (int sig)
static void moreAmplitude (Water *o, void *d, time_t s, time_t u)
static void lessAmplitude (Water *o, void *d, time_t s, time_t u)
static void moreFrequence (Water *o, void *d, time_t s, time_t u)
static void lessFrequence (Water *o, void *d, time_t s, time_t u)
static void morePhase (Water *o, void *d, time_t s, time_t u)
static void lessPhase (Water *o, void *d, time_t s, time_t u)
static void moreTransp (Water *o, void *d, time_t s, time_t u)
static void lessTransp (Water *o, void *d, time_t s, time_t u)
static void reset (Water *o, void *d, time_t s, time_t u)
Private Attributes
float rotx
float roty
float rotz
rotations x y z
float width
float depth
float height
dimensions
float off
offset
bool play
flag play
float amplitude
wave amplitude
float freq
number of waves
float phase
wave speed
float transparency
water transparency
Static Private Attributes
static const uint16_t RATE = 10
static const float MAX_OFF = 20.
static const uint8_t MESH = 64
Additional Inherited Members
Public Types inherited from WObject
enum {
STILL, MOBILE, EPHEMERAL, INVISIBLE,
MOBILEINVISIBLE, MODE_MAX
}
enum {
DELETED = -1, NONE = 0, INACTIVE = 0, ACTIVE,
PLAYING, TAKEN, DROPPED, MOVED,
CARRYING, IN_CART, ENDSTATE
}
enum { RENDER_LOW, RENDER_NORMAL, RENDER_HIGH }
typedef std::list< class Solid * > solidList
Public Attributes inherited from WObject
solidList _solids
list of solids.
class NetObject * noh
reserved field for network.
struct GuiItem * guip
reserved field for GUI.
uint8_t type
object type.
uint8_t mode
object world mode.
uint16_t num
object sequence number.
uint32_t behavior
behavior flags.
Names names
names.
Pos pos
position in the space.
Move move
movement specific.
class WObjectId noid
WObject Id.
bool is_in_a_list
true if it is already in an OList.
bool removed
flag removed or not.
int16_t state
current state.
int8_t prior
render priority.
char * geometry
geometry string.
class Solid * solid
solid pointer
char chan [CHAN_LEN]
channel.
class Flare * flare
flare instance
Static Protected Member Functions inherited from WObject
static void get_xy (WObject *po, class Payload *pp)
static void get_z (WObject *po, class Payload *pp)
static void get_az (WObject *po, class Payload *pp)
static void get_ay (WObject *po, class Payload *pp)
static void get_ax (WObject *po, class Payload *pp)
static void get_hname (WObject *po, class Payload *pp)
static void put_xy (WObject *po, class Payload *pp)
static void put_z (WObject *po, class Payload *pp)
static void put_az (WObject *po, class Payload *pp)
static void put_ay (WObject *po, class Payload *pp)
static void put_ax (WObject *po, class Payload *pp)
static void put_hname (WObject *po, class Payload *pp)
Protected Attributes inherited from WObject
bool objectbar
true if object bar is active.
Detailed Description
Water class.
Definition at line 33 of file water.hpp.
Constructor & Destructor Documentation
Water()
Water::Water (char * l)
Constructor.
Definition at line 117 of file water.cpp.
References behavior(), inits(), and parser().
Referenced by creator().
Member Function Documentation
behavior()
void Water::behavior () private virtual
Sets behaviors.
Definition at line 92 of file water.cpp.
References WObject::enableBehavior(), NO_ELEMENTARY_MOVE, and SPECIFIC_RENDER.
Referenced by Water().
changePermanent()
void Water::changePermanent (float lasting) virtual
Changes the position during a permanent movement.
Reimplemented from WObject.
Definition at line 152 of file water.cpp.
References Times::checkRate(), g, play, RATE, and Global::times.
creator()
WObject * Water::creator (char * l) static
Creates from fileline.
Definition at line 51 of file water.cpp.
References Water().
defaults()
void Water::defaults () private virtual
Sets default values.
Definition at line 56 of file water.cpp.
References amplitude, DEF_AMPLITUDE, DEF_FREQ, DEF_HEIGHT, DEF_PHASE, DEF_TRANSP, first, freq, height, phase, play, and transparency.
Referenced by parser().
draw()
void Water::draw () private virtual
Draws geometry.
Definition at line 124 of file water.cpp.
References amplitude, d, freq, M_2PI, MAX_OFF, MESH, off, phase, play, and Sin().
Referenced by render().
funcs()
void Water::funcs () static
init funclist.
Definition at line 287 of file water.cpp.
References lessAmplitude(), lessFrequence(), lessPhase(), lessTransp(), moreAmplitude(), moreFrequence(), morePhase(), moreTransp(), reset(), setActionFunc(), WATER_TYPE, and WO_ACTION.
getOClass()
virtual const OClass* Water::getOClass () inline virtual
Reimplemented from WObject.
Definition at line 62 of file water.hpp.
References oclass.
inits()
void Water::inits () private virtual
Makes initializations.
Definition at line 98 of file water.cpp.
References Pos::bbcenter, Pos::bbsize, DBG_WO, depth, WObject::enablePermanentMovement(), WObject::initializeMobileObject(), WObject::pos, WObject::RENDER_HIGH, WObject::RENDER_LOW, rotx, roty, rotz, WObject::setRenderPrior(), trace(), V3::v, and width.
Referenced by Water().
lessAmplitude()
void Water::lessAmplitude (Water * o, void * d, time_t s, time_t u) static private
Definition at line 233 of file water.cpp.
References amplitude, and INCR_AMPLITUDE.
Referenced by funcs().
lessFrequence()
void Water::lessFrequence (Water * o, void * d, time_t s, time_t u) static private
Definition at line 245 of file water.cpp.
References freq, and INCR_FREQ.
Referenced by funcs().
lessPhase()
void Water::lessPhase (Water * o, void * d, time_t s, time_t u) static private
Definition at line 257 of file water.cpp.
References INCR_PHASE, and phase.
Referenced by funcs().
lessTransp()
void Water::lessTransp (Water * o, void * d, time_t s, time_t u) static private
Definition at line 271 of file water.cpp.
References INCR_TRANSP, MIN, tcolor, and transparency.
Referenced by funcs().
moreAmplitude()
void Water::moreAmplitude (Water * o, void * d, time_t s, time_t u) static private
Definition at line 228 of file water.cpp.
References amplitude, and INCR_AMPLITUDE.
Referenced by funcs().
moreFrequence()
void Water::moreFrequence (Water * o, void * d, time_t s, time_t u) static private
Definition at line 240 of file water.cpp.
References freq, and INCR_FREQ.
Referenced by funcs().
morePhase()
void Water::morePhase (Water * o, void * d, time_t s, time_t u) static private
Definition at line 252 of file water.cpp.
References INCR_PHASE, and phase.
Referenced by funcs().
moreTransp()
void Water::moreTransp (Water * o, void * d, time_t s, time_t u) static private
Definition at line 264 of file water.cpp.
References INCR_TRANSP, MAX, tcolor, and transparency.
Referenced by funcs().
parser()
void Water::parser (char * l) private virtual
Parses file line.
Definition at line 67 of file water.cpp.
References amplitude, begin_while_parse, DEF_AMPLITUDE, DEF_PHASE, defaults(), end_while_parse, freq, height, WObject::parse(), Parse::parseAttributes(), Parse::parseFloat(), phase, stringcmp(), and WObject::tokenize().
Referenced by Water().
render()
void Water::render () virtual
Makes special rendering.
Reimplemented from WObject.
Definition at line 157 of file water.cpp.
References depth, draw(), height, WObject::pos, rotx, roty, rotz, tcolor, width, Pos::x, Pos::y, and Pos::z.
reset()
void Water::reset (Water * o, void * d, time_t s, time_t u) static private
Definition at line 278 of file water.cpp.
References amplitude, DEF_AMPLITUDE, DEF_FREQ, DEF_PHASE, DEF_TRANSP, freq, phase, tcolor, and transparency.
Referenced by funcs().
sound()
void Water::sound () private virtual
Definition at line 222 of file water.cpp.
References BUBBLESSND, Sound::playSound(), and sound_continue().
Referenced by whenIntersect().
sound_continue()
void Water::sound_continue (int sig) static private
Definition at line 216 of file water.cpp.
References BUBBLESSND, and Sound::playSound().
Referenced by sound().
whenIntersect()
bool Water::whenIntersect (WObject * pcur, WObject * pold) virtual
Handles an ingoing collision with another object.
Reimplemented from WObject.
Definition at line 180 of file water.cpp.
References amplitude, Pos::ay, BALL_TYPE, Pos::bbcenter, Pos::bbsize, CAULDRON_TYPE, COLLIDE_ONCE, DBG_WO, DEG2RAD, Ball::DELTAZ, WObject::disableBehavior(), WObject::enableBehavior(), first, freq, MAX_OFF, off, WObject::pos, sound(), trace(), WObject::type, WObject::updatePosition(), USER_TYPE, V3::v, and Pos::z.
whenIntersectOut()
bool Water::whenIntersectOut (WObject * pcur, WObject * pold) virtual
Handles an outgoing collision with another object.
Reimplemented from WObject.
Definition at line 210 of file water.cpp.
References WObject::type, and USER_TYPE.
Member Data Documentation
amplitude
float Water::amplitude private
wave amplitude
Definition at line 45 of file water.hpp.
Referenced by defaults(), draw(), lessAmplitude(), moreAmplitude(), parser(), reset(), and whenIntersect().
DEF_AMPLITUDE
const float Water::DEF_AMPLITUDE = 0.05 static
Definition at line 53 of file water.hpp.
Referenced by defaults(), parser(), and reset().
DEF_FREQ
const float Water::DEF_FREQ = 1. static
Definition at line 54 of file water.hpp.
Referenced by defaults(), and reset().
DEF_HEIGHT
const float Water::DEF_HEIGHT = 0.15 static
Definition at line 52 of file water.hpp.
Referenced by defaults().
DEF_PHASE
const float Water::DEF_PHASE = 0.0001 static
Definition at line 55 of file water.hpp.
Referenced by defaults(), parser(), and reset().
DEF_TRANSP
const float Water::DEF_TRANSP = 0.8 static
Definition at line 51 of file water.hpp.
Referenced by defaults(), and reset().
depth
float Water::depth private
Definition at line 41 of file water.hpp.
Referenced by inits(), and render().
freq
float Water::freq private
number of waves
Definition at line 46 of file water.hpp.
Referenced by defaults(), draw(), lessFrequence(), moreFrequence(), parser(), reset(), and whenIntersect().
height
float Water::height private
dimensions
Definition at line 41 of file water.hpp.
Referenced by defaults(), parser(), and render().
INCR_AMPLITUDE
const float Water::INCR_AMPLITUDE = 0.01 static
Definition at line 56 of file water.hpp.
Referenced by lessAmplitude(), and moreAmplitude().
INCR_FREQ
const float Water::INCR_FREQ = 1. static
Definition at line 57 of file water.hpp.
Referenced by lessFrequence(), and moreFrequence().
INCR_PHASE
const float Water::INCR_PHASE = 0.00005 static
Definition at line 58 of file water.hpp.
Referenced by lessPhase(), and morePhase().
INCR_TRANSP
const float Water::INCR_TRANSP = 0.05 static
Definition at line 59 of file water.hpp.
Referenced by lessTransp(), and moreTransp().
MAX_OFF
const float Water::MAX_OFF = 20. static private
Definition at line 37 of file water.hpp.
Referenced by draw(), and whenIntersect().
MESH
const uint8_t Water::MESH = 64 static private
Definition at line 38 of file water.hpp.
Referenced by draw().
oclass
const OClass Water::oclass static
class variable.
Definition at line 61 of file water.hpp.
Referenced by getOClass().
off
float Water::off private
offset
Definition at line 42 of file water.hpp.
Referenced by draw(), and whenIntersect().
phase
float Water::phase private
wave speed
Definition at line 47 of file water.hpp.
Referenced by defaults(), draw(), lessPhase(), morePhase(), parser(), and reset().
play
bool Water::play private
flag play
Definition at line 43 of file water.hpp.
Referenced by changePermanent(), defaults(), and draw().
RATE
const uint16_t Water::RATE = 10 static private
Definition at line 36 of file water.hpp.
Referenced by changePermanent().
rotx
float Water::rotx private
Definition at line 40 of file water.hpp.
Referenced by inits(), and render().
roty
float Water::roty private
Definition at line 40 of file water.hpp.
Referenced by inits(), and render().
rotz
float Water::rotz private
rotations x y z
Definition at line 40 of file water.hpp.
Referenced by inits(), and render().
transparency
float Water::transparency private
water transparency
Definition at line 48 of file water.hpp.
Referenced by defaults(), lessTransp(), moreTransp(), and reset().
width
float Water::width private
Definition at line 41 of file water.hpp.
Referenced by inits(), and render().
The documentation for this class was generated from the following files:
src/wo/water.hpp
src/wo/water.cpp