VREng: Vnc Class Reference
Vnc Class Reference
Vnc class.
#include <vnc.hpp>
Public Member Functions
virtual const OClass * getOClass ()
Vnc (char *l)
Constructor.
virtual void changePermanent (float lasting)
Called each frame - check if ths texture has to be updated.
virtual void render ()
Render the object.
virtual void quit ()
Called when the object is destroy.
virtual bool mouseEvent (int16_t x, int16_t y, uint8_t button)
Redirect mouse events to VNC Server.
virtual bool keyEvent (const char *key, bool is_down)
Redirect keyboard events to VNC Server.
virtual void convert (const char *server, const char *port, const char *passwd)
updates server parameters from UStr from the dialog window
Public Member Functions inherited from WObject
WObject ()
Constructor.
virtual ~WObject ()
Destructor.
virtual uint8_t typeId ()
Abstrct class.
virtual const char * typeName ()
WCreator * getCreator ()
WReplicator * getReplicator ()
virtual bool isMoving ()
Checks weither object is moving.
virtual void changePosition (float lasting)
Changes the position after a triggered movement.
virtual void updateTime (time_t sec, time_t usec, float *lasting)
Updates remaining times of the movement.
virtual bool updateToNetwork (const Pos &oldpos)
Publishes changes to the network.
virtual bool updatePosToNetwork (const Pos &oldpos, int propxy, int propz, int propaz, int propax, int propay)
Publishes position changes to the network.
virtual bool whenIntersect (WObject *pcur, WObject *pold)
Handles an ingoing collision with another object.
virtual bool whenIntersectOut (WObject *pcur, WObject *pold)
Handles an outgoing collision with another object.
virtual void whenWallsIntersect (WObject *pold, V3 *norm)
Handles collisions with walls.
virtual void lighting ()
Makes special lighting.
const solidList & solids () const
solidlist address.
uint32_t countOfSolids () const
virtual class Solid * getSolid () const
Returns first solid.
virtual void addSolid (class Solid *solid)
Adds to solidList.
virtual void deleteSolids ()
Deletes solids from solidList.
virtual int interAABB (WObject *o1, WObject *o2)
virtual bool haveAction ()
Checks weither have actions.
virtual uint8_t numberAction ()
Number of actions.
virtual bool runAction (const char *action)
Runs action everwhere if available.
virtual void setType (int type)
Sets object type.
virtual int getType ()
Gets object type.
virtual int getNumber ()
Gets object number.
virtual uint16_t getNum ()
Gets a new object number.
virtual void getPosition (M4 &mpos)
Gives solid's position.
virtual void getRelativeBB (V3 &center, V3 &size)
virtual void getDim (V3 &dim)
virtual void getCenter (V3 &center)
virtual void getAbsoluteBB (V3 &center, V3 &size)
Gets relative or absolute center and size of solid.
virtual uint8_t getFrames ()
Gets number of frames of this solid.
virtual uint8_t getFrame ()
Gets index of current frame of this solid.
virtual void setFrame (uint8_t _frame)
Sets current frame.
virtual bool isValid () const
Checks if valid object type.
virtual bool isPermanent () const
Checks if permanent object.
virtual const char * named () const
Gets names.named.
virtual const char * getInstance () const
Gets names.instance.
virtual const char * urlName () const
Gets names.url.
virtual const char * ownerName () const
Gets names.owner.
virtual const char * worldName () const
Gets names.owner.
virtual bool explicitName () const
Checks wether the object is explicitly named.
virtual void toDelete ()
Delete this object latter.
virtual bool removeFromScene ()
Removes an object.
virtual bool isOwner () const
Returns true if owner.
virtual void setOwner (const char *_owner)
Initialize owner.
virtual void setOwner ()
Initialize local user as owner.
virtual void click (GLint x, GLint y)
Execute an object's click method if it's defined.
virtual void click (V3 norm)
Intercepts a click.
virtual char * tokenize (char *l)
Tokenizes the line <object ...
virtual Parse * parse ()
Gets current parse.
void setWObjectId ()
Sets the WObjectid.
void copyNoid (class Noid _noid)
Copies the NetObjectid in WObjectId.
void setSrcId (uint32_t src_id)
Sets the SrcId.
void setPortId (uint16_t port_id)
Sets the PortId.
void setObjId (uint16_t obj_id)
Sets the ObjId.
uint32_t getSrcId () const
Gets the SrcId.
uint16_t getPortId () const
Gets the PortId.
uint16_t getObjId () const
Gets the ObjId.
virtual void update3D (Pos &pos)
Updates object in the 3D.
virtual void updateAll3D (Pos &pos)
Updates object in the 3D.
virtual void updateCamera (Pos &pos)
Updates camera in the 3D.
virtual void getSurfVecs (Pos &pos, V3 *v, V3 *w, V3 *norm)
Returns two vectors that describe the object's surface and a normal vector to that surface.
virtual void updateBB ()
Updates object's Bounding Box.
virtual void getMaterials (GLfloat *dif, GLfloat *amb, GLfloat *spe, GLfloat *emi, GLint *shi, GLfloat *alpha)
virtual void insertIntoGrid ()
Adds an object into the grid.
virtual void deleteFromGrid ()
Deletes an object from the grid.
virtual void updateGrid (const float *bbminnew, const float *bbmaxnew, const float *bbminold, const float *bbmaxold)
Updates an object in the grid.
virtual void updateGrid (const Pos &oldpos)
virtual void updateGrid (const WObject *pold)
Updates an object into the grid.
virtual void addToList (std::list< WObject * > &olist)
virtual OList * addToList (OList *olist)
Adds an object pointer into a olist.
virtual void addToList ()
Adds an object pointer into a olist.
virtual void addToStill ()
Adds an object pointer into stillList.
virtual void addToMobile ()
Adds an object pointer into mobileList.
virtual void addToInvisible ()
Adds an object pointer into invisibleList.
virtual void addToRender ()
Adds an object pointer into renderList.
virtual void delFromMobile ()
Deletes an object pointer from mobileList.
virtual void clearList ()
Clears an olist.
virtual void clearList (std::list< WObject * > &olist)
Clears an olist.
virtual void addToListOnce (std::list< WObject * > &olist)
virtual OList * addToListOnce (OList *olist)
Adds an object pointer into a list only once time.
virtual void delFromList (std::list< WObject * > &olist)
virtual OList * delFromList (OList *olist)
Deletes an object pointer from a olist.
virtual void delFromList ()
Deletes an object pointer from a olist.
virtual OList * getVicinityList (const WObject *pold)
Returns list of pointers on objects touching cell where is the object.
virtual OList * addListToList (OList *list1, OList *list2)
Concatenation (test of "ispointed") of list pointers on an object.
virtual bool isStill ()
Checks an object exists in the stilllist.
virtual bool isMobile ()
virtual bool isEphemeral ()
Checks an object exists in the mobilelist.
virtual WObject * byWObject (WObject *po)
Gets a WObject from the lists.
virtual void checkVicinity (WObject *pold)
< Gets an object by its num.
virtual void imposedMovement (time_t sec, time_t usec)
Handles an object movement.
virtual void elementaryImposedMovement (float lasting)
Handles an elementary object movement.
virtual void enableImposedMovement ()
Enables movement on an object.
virtual void enablePermanentMovement ()
Enables permanent movement on an object.
virtual void disablePermanentMovement ()
Disables movement on an object.
virtual void enablePermanentMovement (float speed)
Enables permanent movement on an object.
virtual void initImposedMovement (float lasting)
Initializes movement on an object.
virtual float diffTime (time_t sec, time_t usec)
Updates times on an object.
virtual void stopImposedMovement ()
Stops a movement on an object.
virtual void permanentMovement (time_t sec, time_t usec)
Handles a permanent object movement.
virtual void elementaryPermanentMovement (float lasting)
Handles an elementary permanent object movement.
virtual void setLasting (float maxlast)
Sets the max lasting time of an object.
virtual float getLasting () const
Gets the lasting time of an object.
virtual bool testMoving ()
Tests if object is moving.
virtual bool updateLasting (time_t sec, time_t usec, float *lasting)
Updates remaining times of the movement.
virtual void moveUserToObject (float val, float _lttl, float _attl)
Moves the user to the object.
virtual void setObjectName (const char *str)
Sets an object name.
virtual WObject * getObjectByName (const char *str)
Gets an object by its name.
virtual void updateNames ()
Updates names.
virtual void initializeObject (uint8_t mode)
Initializes object.
virtual void initializeMobileObject (float last)
virtual void initializeEphemeralObject (float last)
Initializes mobile object.
virtual void initializeStillObject ()
Initializes still object.
void createPermanentNetObject (uint8_t props, uint16_t oid)
Creates local permanent NetObject.
void createVolatileNetObject (uint8_t props)
Creates local volatile NetObject.
void replicateVolatileNetObject (uint8_t props, class Noid _noid)
Replicate distant volatile NetObject.
virtual void enableBehavior (uint32_t flag)
Enables behavior.
virtual void disableBehavior (uint32_t flag)
Disables behavior.
virtual bool isBehavior (uint32_t flag) const
Checks weither this behavior is on.
virtual bool bbBehavior () const
Checks weither BBox behavior is on.
virtual bool isSeen ()
Checks weither the object is in the sight view of the user.
virtual void setVisible (bool flag)
Sets visible or not the 3D object.
virtual bool isVisible ()
Checks weither the object is visible.
virtual void setFlashy (float *color)
Sets flashy the 3D object.
virtual void setFlashy ()
Sets flashy the 3D object.
virtual void resetFlashy ()
Resets flashy the 3D object.
virtual void setRay (GLint wx, GLint wy)
virtual void resetRay ()
Resets Ray on the 3D object.
virtual void setReflexive (bool flag)
virtual bool isSelectable () const
Checks weither 3D selectable behavior is on.
virtual uint32_t collideBehavior () const
Returns collide behavior.
virtual void setRenderPrior (uint8_t _prior)
Sets render priority.
virtual uint8_t getRenderPrior () const
Gets render priority.
void generalIntersect (WObject *pold, OList *vicinityList)
General intersection of objects.
bool ingoingNeighbor (WObject *pold, WObject *neighbor)
bool outgoingNeighbor (WObject *pold, WObject *neighbor)
Checks ingoing intersection with a neighbor.
void ingoingWalls (WObject *pold)
Checks outgoing intersection with a neighbor.
virtual void copyPosAndBB (Pos &newpos)
Checks ingoing intersection with walls.
virtual void copyPositionAndBB (WObject *o)
Copy object position and Bounding Box.
virtual bool projectPosition (WObject *pcur, WObject *pold)
Projects object position.
virtual int projectPositionOnObstacle (Pos &pcur, Pos &pold, Pos &obstacle)
Projects object position on an obstacle.
virtual void initPosition ()
Init 3D and grid position.
virtual void updatePosition ()
Updating 3D.
virtual void updatePositionAndGrid (Pos &oldpos)
Updating 3D and grid position.
virtual void updatePositionAndGrid (WObject *pold)
Updating 3D and grid position.
virtual void computeNormal (WObject *mobil, V3 *normal)
Computes the normal of an object.
virtual void computeNormal (Pos &mobil, Pos &stil, V3 *normal)
Computes the normal of still object.
virtual void bounceTrajectory (WObject *pold, V3 *norm)
Intersects with wall.
void getProperty (uint8_t prop_id, class Payload *pp)
Gets the local copy property from the payload (pp->data).
void putProperty (uint8_t prop_id, class Payload *pp)
Puts the local copy property in the payload.
virtual void deleteReplica ()
Deletes a replicated object.
virtual struct GuiItem * getGui () const
Gets the GUI handle.
virtual bool isGui () const
Checks the GUI handle.
virtual void resetGui ()
Resets the GUI handle.
virtual void clearObjectBar ()
Clears the ObjectBar in the GUI.
virtual void specialAction (int action, void *data, time_t sec, time_t usec)
Calls methods dedicated to each object.
void getObjectHumanName (char **classname, char **instancename, char **actionnames)
Gives object's class_name & action names.
virtual void getMySqlPosition ()
Checks if position is managed by MySql and get it.
virtual void updateMySqlPosition ()
Checks if position is managed by MySql and update it.
virtual int16_t getMySqlState ()
Gets state from MySql.
virtual void updateMySqlPosZ ()
Checks if posZ is managed by MySql.
virtual void updateMySqlState (int16_t state)
Updates state for MySql.
virtual void flushMySqlPosition ()
Flushes position for MySql.
virtual void quitMySql ()
Quits MySql.
Static Public Member Functions
static void funcs ()
init funclist
static WObject *() creator (char *l)
Creates from fileline.
Static Public Member Functions inherited from WObject
static int interAABB (V3 center1, V3 size1, V3 center2, V3 size2)
Computes intersection between 2 AABB (Axis Aligned Bounding Box).
static int interAABBVertical (V3 center1, V3 size1, V3 center2, V3 size2)
static int interAABBHorizontal (V3 center1, V3 size1, V3 center2, V3 size2)
static void show (const char *name)
Snaps position (debug).
static WObject * byNum (uint16_t num)
static void moveObject (WObject *po, void *d, time_t s, time_t u)
User moves the object.
static void getObjectNameById (uint8_t type_id, char *name)
Gets a name by its id.
static void resetObjectsNumber ()
Resets object seq.
static uint32_t getObjectsNumber ()
Gets current object sequence number.
Static Public Attributes
static const OClass oclass
class variable
Private Member Functions
virtual void parser (char *l)
Parses.
virtual void defaults ()
Set the defaults.
virtual void getVncCoords (int16_t &x, int16_t &y)
Convert VReng screen coordinates to VNC screen coordinates.
virtual void setTexture (bool mipmap)
Build a texture.
virtual void defaultPixmap ()
Build the default pixmap.
virtual void displayScreen ()
Draw the screen.
virtual void buildScreen ()
Build the screen.
virtual void connectServer ()
Static Private Member Functions
static void takeFocus (Vnc *o, void *d, time_t s, time_t u)
static void leaveFocus (Vnc *o, void *d, time_t s, time_t u)
static void disconnectServer (Vnc *o, void *d, time_t s, time_t u)
static void reconnectServer (Vnc *o, void *d, time_t s, time_t u)
Private Attributes
VNCClientTextured * vncClient
vnc client
GLuint texture
texture number
uint16_t tex_width
texture width
uint16_t tex_height
texture height
GLfloat u
GLfloat v
witdh and height screen ratios
GLubyte * def_pixmap
default texture pixmap
GLubyte * tex_pixmap
current pixmap
GLfloat vertices [4 *3]
screen geometry
GLint viewport [4]
current viewport
GLdouble modelmat [16]
modelisation matrix
GLdouble projmat [16]
projection data coordinates
bool serverdefined
flag server defined or not
bool connected
flag connected or not
bool focus
flag have focus or not
uint16_t port
Vnc server port.
char servername [64]
Vnc server name.
char passwdfile [64]
server connection data
Static Private Attributes
static const uint16_t DEF_PORT = 5901
Additional Inherited Members
Public Types inherited from WObject
enum {
STILL, MOBILE, EPHEMERAL, INVISIBLE,
MOBILEINVISIBLE, MODE_MAX
}
enum {
DELETED = -1, NONE = 0, INACTIVE = 0, ACTIVE,
PLAYING, TAKEN, DROPPED, MOVED,
CARRYING, IN_CART, ENDSTATE
}
enum { RENDER_LOW, RENDER_NORMAL, RENDER_HIGH }
typedef std::list< class Solid * > solidList
Public Attributes inherited from WObject
solidList _solids
list of solids.
class NetObject * noh
reserved field for network.
struct GuiItem * guip
reserved field for GUI.
uint8_t type
object type.
uint8_t mode
object world mode.
uint16_t num
object sequence number.
uint32_t behavior
behavior flags.
Names names
names.
Pos pos
position in the space.
Move move
movement specific.
class WObjectId noid
WObject Id.
bool is_in_a_list
true if it is already in an OList.
bool removed
flag removed or not.
int16_t state
current state.
int8_t prior
render priority.
char * geometry
geometry string.
class Solid * solid
solid pointer
char chan [CHAN_LEN]
channel.
class Flare * flare
flare instance
Static Protected Member Functions inherited from WObject
static void get_xy (WObject *po, class Payload *pp)
static void get_z (WObject *po, class Payload *pp)
static void get_az (WObject *po, class Payload *pp)
static void get_ay (WObject *po, class Payload *pp)
static void get_ax (WObject *po, class Payload *pp)
static void get_hname (WObject *po, class Payload *pp)
static void put_xy (WObject *po, class Payload *pp)
static void put_z (WObject *po, class Payload *pp)
static void put_az (WObject *po, class Payload *pp)
static void put_ay (WObject *po, class Payload *pp)
static void put_ax (WObject *po, class Payload *pp)
static void put_hname (WObject *po, class Payload *pp)
Protected Attributes inherited from WObject
bool objectbar
true if object bar is active.
Detailed Description
Vnc class.
Definition at line 54 of file vnc.hpp.
Constructor & Destructor Documentation
Vnc()
Vnc::Vnc (char * l)
Constructor.
Definition at line 89 of file vnc.cpp.
References buildScreen(), COLLIDE_NEVER, connectServer(), WObject::enableBehavior(), WObject::initializeMobileObject(), NO_ELEMENTARY_MOVE, parser(), WObject::RENDER_NORMAL, WObject::setRenderPrior(), SPECIFIC_RENDER, and WObject::updatePosition().
Referenced by creator().
Member Function Documentation
buildScreen()
void Vnc::buildScreen () private virtual
Build the screen.
Definition at line 105 of file vnc.cpp.
References WObject::_solids, dim, WObject::getDim(), MAX, MIN, tex_height, tex_width, u, v, and vertices.
Referenced by Vnc().
changePermanent()
void Vnc::changePermanent (float lasting) virtual
Called each frame - check if ths texture has to be updated.
Reimplemented from WObject.
Definition at line 183 of file vnc.cpp.
References connected, error(), VNCClient::getSock(), VNCClient::handleRFBServerMessage(), setTexture(), and vncClient.
connectServer()
void Vnc::connectServer () private virtual
Definition at line 299 of file vnc.cpp.
References connected, DBG_VNC, WObject::enablePermanentMovement(), VNCClient::fbHeight, VNCClient::fbWidth, VNCClient::framebuffer, notice(), passwdfile, port, VNCClientTextured::realScreenHeight, VNCClientTextured::realScreenWidth, VNCClient::sendFramebufferUpdateRequest(), serverdefined, servername, setTexture(), tex_height, tex_pixmap, tex_width, trace(), u, v, vncClient, VNCClientTextured::VNCInit(), and warning().
Referenced by convert(), and Vnc().
convert()
void Vnc::convert (const char * server, const char * port, const char * passwd) virtual
updates server parameters from UStr from the dialog window
Definition at line 361 of file vnc.cpp.
References connectServer(), passwdfile, port, servername, vncEncryptAndStorePasswd(), and warning().
Referenced by VncDialog::convert().
creator()
WObject * Vnc::creator (char * l) static
Creates from fileline.
Definition at line 34 of file vnc.cpp.
References Vnc().
defaultPixmap()
void Vnc::defaultPixmap () private virtual
Build the default pixmap.
Definition at line 137 of file vnc.cpp.
References def_pixmap, tex_height, tex_pixmap, and tex_width.
Referenced by defaults().
defaults()
void Vnc::defaults () private virtual
Set the defaults.
Definition at line 39 of file vnc.cpp.
References connected, def_pixmap, DEF_PORT, defaultPixmap(), focus, passwdfile, port, serverdefined, servername, setTexture(), tex_height, tex_pixmap, tex_width, texture, u, and v.
Referenced by parser().
disconnectServer()
void Vnc::disconnectServer (Vnc * o, void * d, time_t s, time_t u) static private
Definition at line 338 of file vnc.cpp.
References connected, error(), g, Global::gui, serverdefined, Gui::setToVnc(), vncClient, and VNCClient::VNCClose().
Referenced by funcs().
displayScreen()
void Vnc::displayScreen () private virtual
Draw the screen.
Definition at line 207 of file vnc.cpp.
References u, v, and vertices.
Referenced by render().
funcs()
void Vnc::funcs () static
init funclist
Definition at line 454 of file vnc.cpp.
References disconnectServer(), gotoFront(), leaveFocus(), reconnectServer(), setActionFunc(), takeFocus(), VNC_TYPE, and WO_ACTION.
getOClass()
virtual const OClass* Vnc::getOClass () inline virtual
Reimplemented from WObject.
Definition at line 82 of file vnc.hpp.
References oclass.
getVncCoords()
void Vnc::getVncCoords (int16_t & x, int16_t & y) private virtual
Convert VReng screen coordinates to VNC screen coordinates.
Definition at line 254 of file vnc.cpp.
References gluUnProject(), modelmat, projmat, VNCClientTextured::realScreenHeight, VNCClientTextured::realScreenWidth, vertices, viewport, and vncClient.
Referenced by mouseEvent().
keyEvent()
bool Vnc::keyEvent (const char * key, bool is_down) virtual
Redirect keyboard events to VNC Server.
Definition at line 402 of file vnc.cpp.
References connected, VNCClient::sendRFBEvent(), and vncClient.
Referenced by Navig::keyPressCB(), and Navig::keyReleaseCB().
leaveFocus()
void Vnc::leaveFocus (Vnc * o, void * d, time_t s, time_t u) static private
Definition at line 445 of file vnc.cpp.
References focus, g, Global::gui, notice(), and Gui::setToVnc().
Referenced by funcs(), and quit().
mouseEvent()
bool Vnc::mouseEvent (int16_t x, int16_t y, uint8_t button) virtual
Redirect mouse events to VNC Server.
Redirects events to the Vnc object.
Definition at line 377 of file vnc.cpp.
References connected, getVncCoords(), VNCClient::sendRFBEvent(), and vncClient.
Referenced by Navig::mouseMoveCB(), Navig::mousePressCB(), and Navig::mouseReleaseCB().
parser()
void Vnc::parser (char * l) private virtual
Parses.
Definition at line 60 of file vnc.cpp.
References begin_while_parse, DEF_PORT, defaults(), end_while_parse, Global::env, g, WObject::parse(), Parse::parseAttributes(), Parse::parseString(), Parse::parseUInt16(), Env::passwd(), passwdfile, port, serverdefined, servername, stringcmp(), WObject::tokenize(), and vncEncryptAndStorePasswd().
Referenced by Vnc().
quit()
void Vnc::quit () virtual
Called when the object is destroy.
Reimplemented from WObject.
Definition at line 419 of file vnc.cpp.
References connected, def_pixmap, leaveFocus(), vncClient, and VNCClient::VNCClose().
reconnectServer()
void Vnc::reconnectServer (Vnc * o, void * d, time_t s, time_t u) static private
Definition at line 352 of file vnc.cpp.
References connected, g, Global::gui, Gui::launchVncConnect(), serverdefined, and warning().
Referenced by funcs().
render()
void Vnc::render () virtual
Render the object.
Reimplemented from WObject.
Definition at line 217 of file vnc.cpp.
References Pos::az, displayScreen(), WObject::getPosition(), M4toV16(), modelmat, WObject::pos, projmat, RAD2DEG, texture, WObject::updatePosition(), viewport, and vncClient.
setTexture()
void Vnc::setTexture (bool mipmap) private virtual
Build a texture.
Definition at line 152 of file vnc.cpp.
References gluBuild2DMipmaps(), tex_height, tex_pixmap, tex_width, and texture.
Referenced by changePermanent(), connectServer(), and defaults().
takeFocus()
void Vnc::takeFocus (Vnc * o, void * d, time_t s, time_t u) static private
Definition at line 435 of file vnc.cpp.
References focus, g, Global::gui, notice(), and Gui::setToVnc().
Referenced by funcs().
Member Data Documentation
connected
bool Vnc::connected private
flag connected or not
Definition at line 73 of file vnc.hpp.
Referenced by changePermanent(), connectServer(), defaults(), disconnectServer(), keyEvent(), mouseEvent(), quit(), and reconnectServer().
def_pixmap
GLubyte* Vnc::def_pixmap private
default texture pixmap
Definition at line 66 of file vnc.hpp.
Referenced by defaultPixmap(), defaults(), and quit().
DEF_PORT
const uint16_t Vnc::DEF_PORT = 5901 static private
Definition at line 57 of file vnc.hpp.
Referenced by defaults(), and parser().
focus
bool Vnc::focus private
flag have focus or not
Definition at line 74 of file vnc.hpp.
Referenced by defaults(), leaveFocus(), and takeFocus().
modelmat
GLdouble Vnc::modelmat[16] private
modelisation matrix
Definition at line 70 of file vnc.hpp.
Referenced by getVncCoords(), and render().
oclass
const OClass Vnc::oclass static
class variable
Definition at line 80 of file vnc.hpp.
Referenced by getOClass().
passwdfile
char Vnc::passwdfile[64] private
server connection data
Definition at line 77 of file vnc.hpp.
Referenced by connectServer(), convert(), defaults(), and parser().
port
uint16_t Vnc::port private
Vnc server port.
Definition at line 75 of file vnc.hpp.
Referenced by connectServer(), convert(), defaults(), and parser().
projmat
GLdouble Vnc::projmat[16] private
projection data coordinates
Definition at line 71 of file vnc.hpp.
Referenced by getVncCoords(), and render().
serverdefined
bool Vnc::serverdefined private
flag server defined or not
Definition at line 72 of file vnc.hpp.
Referenced by connectServer(), defaults(), disconnectServer(), parser(), and reconnectServer().
servername
char Vnc::servername[64] private
Vnc server name.
Definition at line 76 of file vnc.hpp.
Referenced by connectServer(), convert(), defaults(), and parser().
tex_height
uint16_t Vnc::tex_height private
texture height
Definition at line 64 of file vnc.hpp.
Referenced by buildScreen(), connectServer(), defaultPixmap(), defaults(), and setTexture().
tex_pixmap
GLubyte* Vnc::tex_pixmap private
current pixmap
Definition at line 67 of file vnc.hpp.
Referenced by connectServer(), defaultPixmap(), defaults(), and setTexture().
tex_width
uint16_t Vnc::tex_width private
texture width
Definition at line 63 of file vnc.hpp.
Referenced by buildScreen(), connectServer(), defaultPixmap(), defaults(), and setTexture().
texture
GLuint Vnc::texture private
texture number
Definition at line 62 of file vnc.hpp.
Referenced by defaults(), render(), and setTexture().
u
GLfloat Vnc::u private
Definition at line 65 of file vnc.hpp.
Referenced by buildScreen(), connectServer(), defaults(), and displayScreen().
v
GLfloat Vnc::v private
witdh and height screen ratios
Definition at line 65 of file vnc.hpp.
Referenced by buildScreen(), connectServer(), defaults(), and displayScreen().
vertices
GLfloat Vnc::vertices[4 *3] private
screen geometry
Definition at line 68 of file vnc.hpp.
Referenced by buildScreen(), displayScreen(), and getVncCoords().
viewport
GLint Vnc::viewport[4] private
current viewport
Definition at line 69 of file vnc.hpp.
Referenced by getVncCoords(), and render().
vncClient
VNCClientTextured* Vnc::vncClient private
vnc client
Definition at line 60 of file vnc.hpp.
Referenced by changePermanent(), connectServer(), disconnectServer(), getVncCoords(), keyEvent(), mouseEvent(), quit(), and render().
The documentation for this class was generated from the following files:
src/wo/vnc.hpp
src/wo/vnc.cpp