VREng: Vrelet Class Reference
Vrelet Class Reference
Vrelet class.
#include <vrelet.hpp>
Public Member Functions
virtual const OClass * getOClass ()
virtual inst. method
Vrelet (char *l)
Constructor.
virtual bool isMoving ()
Returns yes if the child has sent a delta request.
virtual void changePosition (float lasting)
Propagates the last deltas to the object's position.
virtual void updateTime (time_t s, time_t us, float *lasting)
Dummy: always say we need to move.
virtual bool whenIntersect (WObject *pcur, WObject *pold)
Notify the controler that an ingoing intersection occured.
virtual bool whenIntersectOut (WObject *pcur, WObject *pold)
Notify the controler that an outgoing intersection occured.
virtual void render ()
Displays.
virtual void click (V3 dir)
React to a user click on our surface.
virtual void quit ()
Turn the child on (start it up)
Public Member Functions inherited from WObject
WObject ()
Constructor.
virtual ~WObject ()
Destructor.
virtual uint8_t typeId ()
Abstrct class.
virtual const char * typeName ()
WCreator * getCreator ()
WReplicator * getReplicator ()
virtual void changePermanent (float lasting)
Changes the position during a permanent movement.
virtual bool updateToNetwork (const Pos &oldpos)
Publishes changes to the network.
virtual bool updatePosToNetwork (const Pos &oldpos, int propxy, int propz, int propaz, int propax, int propay)
Publishes position changes to the network.
virtual void whenWallsIntersect (WObject *pold, V3 *norm)
Handles collisions with walls.
virtual void lighting ()
Makes special lighting.
const solidList & solids () const
solidlist address.
uint32_t countOfSolids () const
virtual class Solid * getSolid () const
Returns first solid.
virtual void addSolid (class Solid *solid)
Adds to solidList.
virtual void deleteSolids ()
Deletes solids from solidList.
virtual int interAABB (WObject *o1, WObject *o2)
virtual bool haveAction ()
Checks weither have actions.
virtual uint8_t numberAction ()
Number of actions.
virtual bool runAction (const char *action)
Runs action everwhere if available.
virtual void setType (int type)
Sets object type.
virtual int getType ()
Gets object type.
virtual int getNumber ()
Gets object number.
virtual uint16_t getNum ()
Gets a new object number.
virtual void getPosition (M4 &mpos)
Gives solid's position.
virtual void getRelativeBB (V3 &center, V3 &size)
virtual void getDim (V3 &dim)
virtual void getCenter (V3 &center)
virtual void getAbsoluteBB (V3 &center, V3 &size)
Gets relative or absolute center and size of solid.
virtual uint8_t getFrames ()
Gets number of frames of this solid.
virtual uint8_t getFrame ()
Gets index of current frame of this solid.
virtual void setFrame (uint8_t _frame)
Sets current frame.
virtual bool isValid () const
Checks if valid object type.
virtual bool isPermanent () const
Checks if permanent object.
virtual const char * named () const
Gets names.named.
virtual const char * getInstance () const
Gets names.instance.
virtual const char * urlName () const
Gets names.url.
virtual const char * ownerName () const
Gets names.owner.
virtual const char * worldName () const
Gets names.owner.
virtual bool explicitName () const
Checks wether the object is explicitly named.
virtual void toDelete ()
Delete this object latter.
virtual bool removeFromScene ()
Removes an object.
virtual bool isOwner () const
Returns true if owner.
virtual void setOwner (const char *_owner)
Initialize owner.
virtual void setOwner ()
Initialize local user as owner.
virtual void click (GLint x, GLint y)
Execute an object's click method if it's defined.
virtual char * tokenize (char *l)
Tokenizes the line <object ...
virtual Parse * parse ()
Gets current parse.
void setWObjectId ()
Sets the WObjectid.
void copyNoid (class Noid _noid)
Copies the NetObjectid in WObjectId.
void setSrcId (uint32_t src_id)
Sets the SrcId.
void setPortId (uint16_t port_id)
Sets the PortId.
void setObjId (uint16_t obj_id)
Sets the ObjId.
uint32_t getSrcId () const
Gets the SrcId.
uint16_t getPortId () const
Gets the PortId.
uint16_t getObjId () const
Gets the ObjId.
virtual void update3D (Pos &pos)
Updates object in the 3D.
virtual void updateAll3D (Pos &pos)
Updates object in the 3D.
virtual void updateCamera (Pos &pos)
Updates camera in the 3D.
virtual void getSurfVecs (Pos &pos, V3 *v, V3 *w, V3 *norm)
Returns two vectors that describe the object's surface and a normal vector to that surface.
virtual void updateBB ()
Updates object's Bounding Box.
virtual void getMaterials (GLfloat *dif, GLfloat *amb, GLfloat *spe, GLfloat *emi, GLint *shi, GLfloat *alpha)
virtual void insertIntoGrid ()
Adds an object into the grid.
virtual void deleteFromGrid ()
Deletes an object from the grid.
virtual void updateGrid (const float *bbminnew, const float *bbmaxnew, const float *bbminold, const float *bbmaxold)
Updates an object in the grid.
virtual void updateGrid (const Pos &oldpos)
virtual void updateGrid (const WObject *pold)
Updates an object into the grid.
virtual void addToList (std::list< WObject * > &olist)
virtual OList * addToList (OList *olist)
Adds an object pointer into a olist.
virtual void addToList ()
Adds an object pointer into a olist.
virtual void addToStill ()
Adds an object pointer into stillList.
virtual void addToMobile ()
Adds an object pointer into mobileList.
virtual void addToInvisible ()
Adds an object pointer into invisibleList.
virtual void addToRender ()
Adds an object pointer into renderList.
virtual void delFromMobile ()
Deletes an object pointer from mobileList.
virtual void clearList ()
Clears an olist.
virtual void clearList (std::list< WObject * > &olist)
Clears an olist.
virtual void addToListOnce (std::list< WObject * > &olist)
virtual OList * addToListOnce (OList *olist)
Adds an object pointer into a list only once time.
virtual void delFromList (std::list< WObject * > &olist)
virtual OList * delFromList (OList *olist)
Deletes an object pointer from a olist.
virtual void delFromList ()
Deletes an object pointer from a olist.
virtual OList * getVicinityList (const WObject *pold)
Returns list of pointers on objects touching cell where is the object.
virtual OList * addListToList (OList *list1, OList *list2)
Concatenation (test of "ispointed") of list pointers on an object.
virtual bool isStill ()
Checks an object exists in the stilllist.
virtual bool isMobile ()
virtual bool isEphemeral ()
Checks an object exists in the mobilelist.
virtual WObject * byWObject (WObject *po)
Gets a WObject from the lists.
virtual void checkVicinity (WObject *pold)
< Gets an object by its num.
virtual void imposedMovement (time_t sec, time_t usec)
Handles an object movement.
virtual void elementaryImposedMovement (float lasting)
Handles an elementary object movement.
virtual void enableImposedMovement ()
Enables movement on an object.
virtual void enablePermanentMovement ()
Enables permanent movement on an object.
virtual void disablePermanentMovement ()
Disables movement on an object.
virtual void enablePermanentMovement (float speed)
Enables permanent movement on an object.
virtual void initImposedMovement (float lasting)
Initializes movement on an object.
virtual float diffTime (time_t sec, time_t usec)
Updates times on an object.
virtual void stopImposedMovement ()
Stops a movement on an object.
virtual void permanentMovement (time_t sec, time_t usec)
Handles a permanent object movement.
virtual void elementaryPermanentMovement (float lasting)
Handles an elementary permanent object movement.
virtual void setLasting (float maxlast)
Sets the max lasting time of an object.
virtual float getLasting () const
Gets the lasting time of an object.
virtual bool testMoving ()
Tests if object is moving.
virtual bool updateLasting (time_t sec, time_t usec, float *lasting)
Updates remaining times of the movement.
virtual void moveUserToObject (float val, float _lttl, float _attl)
Moves the user to the object.
virtual void setObjectName (const char *str)
Sets an object name.
virtual WObject * getObjectByName (const char *str)
Gets an object by its name.
virtual void updateNames ()
Updates names.
virtual void initializeObject (uint8_t mode)
Initializes object.
virtual void initializeMobileObject (float last)
virtual void initializeEphemeralObject (float last)
Initializes mobile object.
virtual void initializeStillObject ()
Initializes still object.
void createPermanentNetObject (uint8_t props, uint16_t oid)
Creates local permanent NetObject.
void createVolatileNetObject (uint8_t props)
Creates local volatile NetObject.
void replicateVolatileNetObject (uint8_t props, class Noid _noid)
Replicate distant volatile NetObject.
virtual void enableBehavior (uint32_t flag)
Enables behavior.
virtual void disableBehavior (uint32_t flag)
Disables behavior.
virtual bool isBehavior (uint32_t flag) const
Checks weither this behavior is on.
virtual bool bbBehavior () const
Checks weither BBox behavior is on.
virtual bool isSeen ()
Checks weither the object is in the sight view of the user.
virtual void setVisible (bool flag)
Sets visible or not the 3D object.
virtual bool isVisible ()
Checks weither the object is visible.
virtual void setFlashy (float *color)
Sets flashy the 3D object.
virtual void setFlashy ()
Sets flashy the 3D object.
virtual void resetFlashy ()
Resets flashy the 3D object.
virtual void setRay (GLint wx, GLint wy)
virtual void resetRay ()
Resets Ray on the 3D object.
virtual void setReflexive (bool flag)
virtual bool isSelectable () const
Checks weither 3D selectable behavior is on.
virtual uint32_t collideBehavior () const
Returns collide behavior.
virtual void setRenderPrior (uint8_t _prior)
Sets render priority.
virtual uint8_t getRenderPrior () const
Gets render priority.
void generalIntersect (WObject *pold, OList *vicinityList)
General intersection of objects.
bool ingoingNeighbor (WObject *pold, WObject *neighbor)
bool outgoingNeighbor (WObject *pold, WObject *neighbor)
Checks ingoing intersection with a neighbor.
void ingoingWalls (WObject *pold)
Checks outgoing intersection with a neighbor.
virtual void copyPosAndBB (Pos &newpos)
Checks ingoing intersection with walls.
virtual void copyPositionAndBB (WObject *o)
Copy object position and Bounding Box.
virtual bool projectPosition (WObject *pcur, WObject *pold)
Projects object position.
virtual int projectPositionOnObstacle (Pos &pcur, Pos &pold, Pos &obstacle)
Projects object position on an obstacle.
virtual void initPosition ()
Init 3D and grid position.
virtual void updatePosition ()
Updating 3D.
virtual void updatePositionAndGrid (Pos &oldpos)
Updating 3D and grid position.
virtual void updatePositionAndGrid (WObject *pold)
Updating 3D and grid position.
virtual void computeNormal (WObject *mobil, V3 *normal)
Computes the normal of an object.
virtual void computeNormal (Pos &mobil, Pos &stil, V3 *normal)
Computes the normal of still object.
virtual void bounceTrajectory (WObject *pold, V3 *norm)
Intersects with wall.
void getProperty (uint8_t prop_id, class Payload *pp)
Gets the local copy property from the payload (pp->data).
void putProperty (uint8_t prop_id, class Payload *pp)
Puts the local copy property in the payload.
virtual void deleteReplica ()
Deletes a replicated object.
virtual struct GuiItem * getGui () const
Gets the GUI handle.
virtual bool isGui () const
Checks the GUI handle.
virtual void resetGui ()
Resets the GUI handle.
virtual void clearObjectBar ()
Clears the ObjectBar in the GUI.
virtual void specialAction (int action, void *data, time_t sec, time_t usec)
Calls methods dedicated to each object.
void getObjectHumanName (char **classname, char **instancename, char **actionnames)
Gives object's class_name & action names.
virtual void getMySqlPosition ()
Checks if position is managed by MySql and get it.
virtual void updateMySqlPosition ()
Checks if position is managed by MySql and update it.
virtual int16_t getMySqlState ()
Gets state from MySql.
virtual void updateMySqlPosZ ()
Checks if posZ is managed by MySql.
virtual void updateMySqlState (int16_t state)
Updates state for MySql.
virtual void flushMySqlPosition ()
Flushes position for MySql.
virtual void quitMySql ()
Quits MySql.
Static Public Member Functions
static void funcs ()
init funclist
static WObject *() creator (char *l)
Creates from fileline.
Static Public Member Functions inherited from WObject
static int interAABB (V3 center1, V3 size1, V3 center2, V3 size2)
Computes intersection between 2 AABB (Axis Aligned Bounding Box).
static int interAABBVertical (V3 center1, V3 size1, V3 center2, V3 size2)
static int interAABBHorizontal (V3 center1, V3 size1, V3 center2, V3 size2)
static void show (const char *name)
Snaps position (debug).
static WObject * byNum (uint16_t num)
static void moveObject (WObject *po, void *d, time_t s, time_t u)
User moves the object.
static void getObjectNameById (uint8_t type_id, char *name)
Gets a name by its id.
static void resetObjectsNumber ()
Resets object seq.
static uint32_t getObjectsNumber ()
Gets current object sequence number.
Public Attributes
int incrx
int incry
increments x y
float fx
float fy
ratios x y
char app [VRELET_NAME_LEN]
class name
char url [VRELET_NAME_LEN]
codebase URL
V3 posDelta
V3 angDelta
requested deltas, (x,y,z) and (az,ay,ax)
tObject2D * o2
List of 2D Objects this Vrelet has.
Public Attributes inherited from WObject
solidList _solids
list of solids.
class NetObject * noh
reserved field for network.
struct GuiItem * guip
reserved field for GUI.
uint8_t type
object type.
uint8_t mode
object world mode.
uint16_t num
object sequence number.
uint32_t behavior
behavior flags.
Names names
names.
Pos pos
position in the space.
Move move
movement specific.
class WObjectId noid
WObject Id.
bool is_in_a_list
true if it is already in an OList.
bool removed
flag removed or not.
int16_t state
current state.
int8_t prior
render priority.
char * geometry
geometry string.
class Solid * solid
solid pointer
char chan [CHAN_LEN]
channel.
class Flare * flare
flare instance
Static Public Attributes
static const OClass oclass
class variable
Private Member Functions
virtual void defaults ()
Default values.
virtual void parser (char *l)
Vrelet parser.
virtual void draw ()
Make sure our asynch sockets are open if they need to be.
virtual void sendPos (WObject *po)
Send some object's position to the child.
virtual void sendPosError (int type, int ssrc, int port, int id)
Same as sendPos, except that no position is sent.
virtual void sendIntersect (WObject *po, WObject *old, int inOrOut)
Send the client a notification that a thing just entered/exited its bounding box.
virtual void answerTypeQuery (int type)
Answer a child's query.
virtual void processClient ()
Deal with input from the client app.
virtual void setPos (WObject *po)
Set initial position of this object.
virtual void deltaPos (WObject *po)
Update position of this object.
virtual void sendClick (int x, int y)
Send a notification to the child saying a click occured.
tObject2D * newObject2D (tObject2D *list, int type, int tag, V3 color)
tObject2D * removeObject2D (tObject2D *list, int type, int tag)
void addPoint (tObject2D *, V3 pt)
void freeObject2D (tObject2D *)
void freeObject2DList (tObject2D *)
void freePointList (tPointList *)
Private Attributes
int wantDelta
true if the child has requested a position delta
bool needRedraw
true if a new shape has been added/removed to the list of 2D objects
GLint dlist
OpenGL displaylist constructed from the above list.
Additional Inherited Members
Public Types inherited from WObject
enum {
STILL, MOBILE, EPHEMERAL, INVISIBLE,
MOBILEINVISIBLE, MODE_MAX
}
enum {
DELETED = -1, NONE = 0, INACTIVE = 0, ACTIVE,
PLAYING, TAKEN, DROPPED, MOVED,
CARRYING, IN_CART, ENDSTATE
}
enum { RENDER_LOW, RENDER_NORMAL, RENDER_HIGH }
typedef std::list< class Solid * > solidList
Static Protected Member Functions inherited from WObject
static void get_xy (WObject *po, class Payload *pp)
static void get_z (WObject *po, class Payload *pp)
static void get_az (WObject *po, class Payload *pp)
static void get_ay (WObject *po, class Payload *pp)
static void get_ax (WObject *po, class Payload *pp)
static void get_hname (WObject *po, class Payload *pp)
static void put_xy (WObject *po, class Payload *pp)
static void put_z (WObject *po, class Payload *pp)
static void put_az (WObject *po, class Payload *pp)
static void put_ay (WObject *po, class Payload *pp)
static void put_ax (WObject *po, class Payload *pp)
static void put_hname (WObject *po, class Payload *pp)
Protected Attributes inherited from WObject
bool objectbar
true if object bar is active.
Detailed Description
Vrelet class.
Definition at line 52 of file vrelet.hpp.
Constructor & Destructor Documentation
Vrelet()
Vrelet::Vrelet (char * l)
Constructor.
Definition at line 96 of file vrelet.cpp.
References COLLIDE_GHOST, g, Global::gui, Gui::setToVrelet(), SPECIFIC_RENDER, and Vjc::startApp().
Member Function Documentation
addPoint()
void Vrelet::addPoint (tObject2D * _o2, V3 pt) private
Definition at line 476 of file vrelet.cpp.
References copyV3(), DBG_IFC, tPointList::next, tPointList::point, tObject2D::points, trace(), and V3::v.
answerTypeQuery()
void Vrelet::answerTypeQuery (int type) private virtual
Answer a child's query.
Right now, the only query available is a query to the list of mobile objects, asking for a given type of WObject. A list of all the object ids is returned to the child.
Definition at line 146 of file vrelet.cpp.
References localuser, mobileList, VjcMessage::put32(), VjcMessage::putOID(), VjcMessage::sendData(), VJC_MSGT_QUERY, and VJC_MSGV_QANS.
changePosition()
void Vrelet::changePosition (float lasting) virtual
Propagates the last deltas to the object's position.
Reimplemented from WObject.
Definition at line 352 of file vrelet.cpp.
References VJC_MSGV_SET, and VJC_MSGV_UPD.
click()
void Vrelet::click (V3 dir) virtual
React to a user click on our surface.
Reimplemented from WObject.
Definition at line 286 of file vrelet.cpp.
References calcV3(), DBG_IFC, det(), detV3(), User::height, localuser, newV3(), WObject::pos, trace(), V3::v, warning(), Pos::x, Pos::y, and Pos::z.
creator()
WObject * Vrelet::creator (char * l) static
Creates from fileline.
Definition at line 38 of file vrelet.cpp.
defaults()
void Vrelet::defaults () private virtual
Default values.
Definition at line 43 of file vrelet.cpp.
References dlist.
deltaPos()
void Vrelet::deltaPos (WObject * po) private virtual
Update position of this object.
Definition at line 334 of file vrelet.cpp.
References Pos::ax, Pos::ay, Pos::az, WObject::pos, Pos::x, Pos::y, and Pos::z.
draw()
void Vrelet::draw () private virtual
Make sure our asynch sockets are open if they need to be.
If they are, see if the client said something between now and the last render call. Finally, draw this Vrelet's 2D object list.
Definition at line 487 of file vrelet.cpp.
References Cos(), DBG_IFC, dlist, M_2PI, tPointList::next, tPointList::point, Sin(), trace(), V3::v, VJC_MSGV_CIRCLE, VJC_MSGV_FILL, VJC_MSGV_LINE, and VJC_MSGV_LOOP.
freeObject2D()
void Vrelet::freeObject2D (tObject2D * _o2) private
Definition at line 452 of file vrelet.cpp.
References tObject2D::points, and warning().
freeObject2DList()
void Vrelet::freeObject2DList (tObject2D * o2l) private
Definition at line 463 of file vrelet.cpp.
References tObject2D::next.
freePointList()
void Vrelet::freePointList (tPointList * pts) private
Definition at line 441 of file vrelet.cpp.
References tPointList::next.
funcs()
void Vrelet::funcs () static
init funclist
Definition at line 34 of file vrelet.cpp.
getOClass()
virtual const OClass* Vrelet::getOClass () inline virtual
virtual inst. method
Reimplemented from WObject.
Definition at line 65 of file vrelet.hpp.
References oclass.
isMoving()
bool Vrelet::isMoving () virtual
Returns yes if the child has sent a delta request.
Reimplemented from WObject.
Definition at line 345 of file vrelet.cpp.
newObject2D()
tObject2D * Vrelet::newObject2D (tObject2D * list, int type, int tag, V3 color) private
Definition at line 406 of file vrelet.cpp.
References tObject2D::color, copyV3(), tObject2D::next, tObject2D::points, tObject2D::tag, and tObject2D::type.
parser()
void Vrelet::parser (char * l) private virtual
Vrelet parser.
Configuration line structure:
(name)
position (X Y Z AZ AX)
geometry (see solid.cc)
incrx and incry of the main surface (coordinates passed to the client will be in the range ([-incrx;incrx], [-incry;incry])
x and y aspect ratio (client incrx/object width)
java class for the client (must implement fr.enst.vreng.<VrengClient>)
codebase URL for that class (optional)
Definition at line 54 of file vrelet.cpp.
References Url::abs(), begin_while_parse, Universe::current(), World::current(), DEF_URL_JAR, end_while_parse, parse, Parse::parseAttributes(), Parse::parseFloat(), Parse::parseInt(), Parse::parseString(), stringcmp(), and URL_LEN.
processClient()
void Vrelet::processClient () private virtual
Deal with input from the client app.
This function is called at every render phase. The client socket is probed for incoming packets, with an empty timeout. If no packets were queued, the function returns immediatly. No more than one packet is dealt with in one go. Messages dealt with:
MSGT_ADD: adds 2D objects to this object's rendering
MSGT_DEL: removes one or all of the existing 2d objects
MSGT_POS: MSGV_ASK: sends the queried object's position back to the client MSGV_SET: sets this object's position to the parameters passed in MSGV_UPD: considers the params passed as deltas on the object's position
MSGT_QUERY: Answers to type queries (returns a list of mobile objects)
Definition at line 167 of file vrelet.cpp.
References color, WObject::copyPositionAndBB(), copyV3(), DBG_IFC, OList::findInMobile(), WObject::generalIntersect(), Vjc::getData(), VjcMessage::getHeader(), WObject::getVicinityList(), VjcMessage::hasData(), localuser, tVjcHeader::msg_id, tVjcHeader::msg_type, newV3(), VjcMessage::read16(), VjcMessage::read32(), VjcMessage::read8(), VjcMessage::readDelta(), VjcMessage::readPoint2D(), VjcMessage::readPoint3D(), OList::remove(), src, trace(), WObject::updateCamera(), WObject::updatePositionAndGrid(), VJC_MSGT_ADD, VJC_MSGT_DEL, VJC_MSGT_POS, VJC_MSGT_QUERY, VJC_MSGV_ASK, VJC_MSGV_CIRCLE, VJC_MSGV_DELALL, VJC_MSGV_FILL, VJC_MSGV_LINE, VJC_MSGV_LOOP, VJC_MSGV_QTYPE, VJC_MSGV_SET, and VJC_MSGV_UPD.
quit()
void Vrelet::quit () virtual
Turn the child on (start it up)
Reimplemented from WObject.
Definition at line 394 of file vrelet.cpp.
References dlist, g, Global::gui, Gui::setToVrelet(), and Vjc::stopApp().
removeObject2D()
tObject2D * Vrelet::removeObject2D (tObject2D * list, int type, int tag) private
Definition at line 418 of file vrelet.cpp.
References tObject2D::next, and warning().
render()
void Vrelet::render () virtual
Displays.
Reimplemented from WObject.
Definition at line 542 of file vrelet.cpp.
References dlist, and M4toV16().
sendClick()
void Vrelet::sendClick (int x, int y) private virtual
Send a notification to the child saying a click occured.
The coordinates sent are relative to the object's main surface (which would be described by the vectors (1,0,0), (0,1,0), and a normal of (0,0,1)). This only works well if the object is very thin. Clicks hitting the other surface (norm=(0,0,-1)) are ignored. Packet contents:
signed 32bit x
signed 32bit y
Definition at line 112 of file vrelet.cpp.
References VjcMessage::put32(), VjcMessage::sendData(), VJC_MSGT_CLICK, and VJC_MSGV_CLICK.
sendIntersect()
void Vrelet::sendIntersect (WObject * po, WObject * old, int inOrOut) private virtual
Send the client a notification that a thing just entered/exited its bounding box.
Definition at line 367 of file vrelet.cpp.
References VjcMessage::putOID(), VjcMessage::putPos(), VjcMessage::sendData(), and VJC_MSGT_ISEC.
sendPos()
void Vrelet::sendPos (WObject * po) private virtual
Send some object's position to the child.
If the position is that of the current object, the type is set to 0, otherwise it's set to the object's real type. Packet contents:
signed 8bit type
signed 32bit net object id
signed 16bit port id and object id
signed 32bit x, y, z
signed 32bit az, ax, 0 All position/angle variables are multiplied by 1000 (sending floats is not currently possible)
Definition at line 122 of file vrelet.cpp.
References VjcMessage::putOID(), VjcMessage::putPos(), VjcMessage::sendData(), VJC_MSGT_POS, and VJC_MSGV_SET.
sendPosError()
void Vrelet::sendPosError (int type, int ssrc, int port, int id) private virtual
Same as sendPos, except that no position is sent.
This is to indicate to the controler application that the object it's working on no longer exists.
Definition at line 133 of file vrelet.cpp.
References VjcMessage::put16(), VjcMessage::put32(), VjcMessage::put8(), VjcMessage::sendData(), VJC_MSGT_POS, and VJC_MSGV_ERROR.
setPos()
void Vrelet::setPos (WObject * po) private virtual
Set initial position of this object.
Definition at line 324 of file vrelet.cpp.
References Pos::ax, Pos::ay, Pos::az, WObject::pos, Pos::x, Pos::y, and Pos::z.
updateTime()
void Vrelet::updateTime (time_t s, time_t us, float * lasting) virtual
Dummy: always say we need to move.
Reimplemented from WObject.
Definition at line 319 of file vrelet.cpp.
whenIntersect()
bool Vrelet::whenIntersect (WObject * pcur, WObject * pold) virtual
Notify the controler that an ingoing intersection occured.
Reimplemented from WObject.
Definition at line 380 of file vrelet.cpp.
References VJC_MSGV_ISECIN.
whenIntersectOut()
bool Vrelet::whenIntersectOut (WObject * pcur, WObject * pold) virtual
Notify the controler that an outgoing intersection occured.
Reimplemented from WObject.
Definition at line 387 of file vrelet.cpp.
References VJC_MSGV_ISECOUT.
Member Data Documentation
angDelta
V3 Vrelet::angDelta
requested deltas, (x,y,z) and (az,ay,ax)
Definition at line 60 of file vrelet.hpp.
app
char Vrelet::app[VRELET_NAME_LEN]
class name
Definition at line 58 of file vrelet.hpp.
Referenced by Vjc::startApp().
dlist
GLint Vrelet::dlist private
OpenGL displaylist constructed from the above list.
Definition at line 101 of file vrelet.hpp.
fx
float Vrelet::fx
Definition at line 57 of file vrelet.hpp.
fy
float Vrelet::fy
ratios x y
Definition at line 57 of file vrelet.hpp.
incrx
int Vrelet::incrx
Definition at line 56 of file vrelet.hpp.
Referenced by Vjc::startApp().
incry
int Vrelet::incry
increments x y
Definition at line 56 of file vrelet.hpp.
Referenced by Vjc::startApp().
needRedraw
bool Vrelet::needRedraw private
true if a new shape has been added/removed to the list of 2D objects
Definition at line 100 of file vrelet.hpp.
o2
tObject2D* Vrelet::o2
List of 2D Objects this Vrelet has.
Definition at line 61 of file vrelet.hpp.
oclass
const OClass Vrelet::oclass static
class variable
Definition at line 63 of file vrelet.hpp.
Referenced by getOClass().
posDelta
V3 Vrelet::posDelta
Definition at line 60 of file vrelet.hpp.
url
char Vrelet::url[VRELET_NAME_LEN]
codebase URL
Definition at line 59 of file vrelet.hpp.
Referenced by Vjc::startApp().
wantDelta
int Vrelet::wantDelta private
true if the child has requested a position delta
Definition at line 99 of file vrelet.hpp.
The documentation for this class was generated from the following files:
src/wo/vrelet.hpp
src/wo/vrelet.cpp