VREng: Session Class Reference
Session Class Reference
Session class Structure of a RTP session.
#include <session.hpp>
Public Member Functions
Session ()
Constructor.
virtual ~Session ()
Destructor.
virtual uint32_t create (uint32_t group, uint16_t port, uint8_t ttl, uint32_t ssrc)
creates a new session, called by channel
virtual void buildRtpHeader (rtp_hdr_t *pkt, uint32_t ssrc)
builds a RTP header
virtual void buildRTCPcommon (rtcp_common_t *prtcp_hdr, uint8_t pt)
Builds RTCP commun header.
virtual int buildSR (rtcp_common_t *prtcp_hdr, uint8_t *pkt)
Builds a SR RTCP packet.
virtual int buildSDES (rtcp_common_t *prtcp_hdr, uint8_t *pkt)
Builds a SDES packet.
virtual int buildBYE (rtcp_common_t *prtcp_hdr, uint8_t *pkt)
Builds a BYE packet.
virtual int sendRTCPPacket (const struct sockaddr_in *to, uint8_t pt)
Sends a RTCP packet.
virtual int sendSRSDES (const struct sockaddr_in *to)
Sends a RTCP compound packet (SR + SDES)
virtual void deleteSourceBySsrc (uint32_t ssrc)
virtual void incrSources ()
virtual void createMySdes ()
creates my SDES item
virtual void refreshMySdes ()
refreshes my SDES item
virtual void freeMySdes ()
virtual void dump ()
virtual void stat ()
Static Public Member Functions
static Session * current ()
Gets the current session.
static void deleteSessionBySsrc (uint32_t ssrc)
static void clearList ()
static Session * getList ()
static void dumpAll ()
Public Attributes
uint32_t ssrc
RTP ssrc id.
uint32_t group
multicast address
uint16_t rtp_port
RTP port.
uint16_t rtcp_port
RTCP port.
uint8_t ttl
ttl
uint8_t mode
WORLD, MANAGER.
rtp_hdr_t rtp_hdr
session RTP header
uint16_t rtp_seq
RTP sequence number.
rtcp_sr_t sr
RTCP sender report.
class Source * source
informations on sources
uint16_t nbsources
amount of sources
SdesItem * mysdes
my own RTCP SDES
Session * next
next session
Detailed Description
Session class Structure of a RTP session.
Definition at line 31 of file session.hpp.
Constructor & Destructor Documentation
Session()
Session::Session ()
Constructor.
creates a new Session
Definition at line 82 of file session.cpp.
References currentSession, group, mode, mysdes, nbsources, new_session, next, rtcp_port, rtp_port, sessionList, source, sr, and ttl.
~Session()
Session::~Session () virtual
Destructor.
Session destructor.
Definition at line 212 of file session.cpp.
References DBG_RTP, del_session, deleteSourceBySsrc(), freeMySdes(), NetObject::getMySsrcId(), and trace().
Member Function Documentation
buildBYE()
int Session::buildBYE (rtcp_common_t * prtcp_hdr, uint8_t * pkt) virtual
Builds a BYE packet.
Definition at line 383 of file session.cpp.
References buildRTCPcommon(), rtcp_common_t::count, DBG_RTP, rtcp_common_t::length, RTCP_BYE, ssrc, and trace().
Referenced by sendRTCPPacket().
buildRTCPcommon()
void Session::buildRTCPcommon (rtcp_common_t * prtcp_hdr, uint8_t pt) virtual
Builds RTCP commun header.
Builds common part of rtcp packet.
Definition at line 310 of file session.cpp.
References rtcp_common_t::pt, RTP_VERSION, and rtcp_common_t::version.
Referenced by buildBYE(), buildSDES(), and buildSR().
buildRtpHeader()
void Session::buildRtpHeader (rtp_hdr_t * pkt, uint32_t ssrc) virtual
builds a RTP header
Definition at line 58 of file session.cpp.
References rtp_hdr_t::cc, DBG_RTP, gettimeofday(), rtp_hdr_t::m, rtp_hdr_t::p, rtp_hdr_t::pt, rtp_hdr, rtp_seq, RTP_VERSION, RTP_VREP_TYPE, rtp_hdr_t::seq, rtp_hdr_t::ssrc, trace(), rtp_hdr_t::ts, rtp_hdr_t::version, and rtp_hdr_t::x.
Referenced by Payload::sendPayload().
buildSDES()
int Session::buildSDES (rtcp_common_t * prtcp_hdr, uint8_t * pkt) virtual
Builds a SDES packet.
Fills rtcp buffer and return length.
Definition at line 344 of file session.cpp.
References buildRTCPcommon(), rtcp_common_t::count, DBG_RTP, rtcp_common_t::length, mysdes, PKTSIZE, RTCP_SDES, RTCP_SDES_END, SdesItem::si_next, ssrc, and trace().
Referenced by sendRTCPPacket(), and sendSRSDES().
buildSR()
int Session::buildSR (rtcp_common_t * prtcp_hdr, uint8_t * pkt) virtual
Builds a SR RTCP packet.
Builds a SR packet.
Definition at line 320 of file session.cpp.
References buildRTCPcommon(), rtcp_common_t::count, DBG_RTP, NetObject::getMySsrcId(), gettimeofday(), rtcp_common_t::length, RTCP_SR, sr, and trace().
Referenced by sendRTCPPacket(), and sendSRSDES().
clearList()
void Session::clearList () static
Definition at line 113 of file session.cpp.
References sessionList.
Referenced by Channel::init().
create()
uint32_t Session::create (uint32_t group, uint16_t port, uint8_t ttl, uint32_t ssrc) virtual
creates a new session, called by channel
initialize variables for a session already allocated, return local ssrc
Definition at line 132 of file session.cpp.
References createMySdes(), Rtp::createSeq(), Rtp::createSsrc(), DBG_RTP, group, Source::incrSourcesNumber(), Rtp::initSource(), nbsources, rtcp_port, rtp_hdr, rtp_port, rtp_seq, Source::s, source, sr, rtp_hdr_t::ssrc, ssrc, trace(), and ttl.
createMySdes()
void Session::createMySdes () virtual
creates my SDES item
Definition at line 223 of file session.cpp.
References Rtp::allocSdesItem(), World::current(), DBG_RTP, Email, World::getName(), Rtp::getRtcpEmail(), Rtp::getRtcpName(), Rtp::getRtcpTool(), MANAGER_NAME, mysdes, Name, RTCP_SDES_CNAME, RTCP_SDES_EMAIL, RTCP_SDES_LOC, RTCP_SDES_NAME, RTCP_SDES_TOOL, SdesItem::si_len, SdesItem::si_next, SdesItem::si_str, SdesItem::si_type, Tool, and trace().
Referenced by create().
current()
Session * Session::current () static
Gets the current session.
Definition at line 108 of file session.cpp.
References currentSession.
deleteSessionBySsrc()
void Session::deleteSessionBySsrc (uint32_t ssrc) static
Definition at line 165 of file session.cpp.
References DBG_RTP, error(), next, Source::next, sessionList, and trace().
deleteSourceBySsrc()
void Session::deleteSourceBySsrc (uint32_t ssrc) virtual
Definition at line 180 of file session.cpp.
References DBG_RTP, Source::decrSourcesNumber(), nbsources, Source::next, setLostPackets(), source, and trace().
Referenced by Rtp::recvRTCPPacket(), and ~Session().
dump()
void Session::dump () virtual
Definition at line 461 of file session.cpp.
References group, mysdes, RTCP_SDES_END, RTCP_SDES_SOURCE, rtp_port, SdesItem::si_len, SdesItem::si_next, SdesItem::si_str, SdesItem::si_type, and ttl.
dumpAll()
void Session::dumpAll () static
Definition at line 474 of file session.cpp.
References next, and sessionList.
freeMySdes()
void Session::freeMySdes () virtual
Definition at line 296 of file session.cpp.
References mysdes, and SdesItem::si_next.
Referenced by ~Session().
getList()
Session * Session::getList () static
Definition at line 118 of file session.cpp.
References sessionList.
Referenced by Source::dumpAll(), Source::getMembersNumber(), and Rtp::getSdesItemBySsrc().
incrSources()
void Session::incrSources () virtual
Definition at line 123 of file session.cpp.
References DBG_RTP, Source::incrSourcesNumber(), nbsources, and trace().
Referenced by Source::getSource().
refreshMySdes()
void Session::refreshMySdes () virtual
refreshes my SDES item
Definition at line 274 of file session.cpp.
References World::current(), DBG_RTP, World::getName(), MANAGER_NAME, mysdes, RTCP_SDES_LOC, SdesItem::si_len, SdesItem::si_next, SdesItem::si_str, SdesItem::si_type, and trace().
Referenced by Payload::sendPayload().
sendRTCPPacket()
int Session::sendRTCPPacket (const struct sockaddr_in * to, uint8_t pt) virtual
Sends a RTCP packet.
Definition at line 401 of file session.cpp.
References buildBYE(), buildSDES(), buildSR(), error(), Channel::getFdSendRTCP(), Channel::getSaRTCP(), PKTSIZE, RTCP_BYE, RTCP_SDES, RTCP_SR, Rtp::sendPacket(), and statSendRTCP().
sendSRSDES()
int Session::sendSRSDES (const struct sockaddr_in * to) virtual
Sends a RTCP compound packet (SR + SDES)
Definition at line 434 of file session.cpp.
References buildSDES(), buildSR(), DBG_RTP, error(), Channel::getFdSendRTCP(), Channel::getSaRTCP(), PKTSIZE, Rtp::sendPacket(), statSendRTCP(), and trace().
Referenced by Payload::sendPayload().
stat()
void Session::stat () virtual
Definition at line 480 of file session.cpp.
References World::current(), Source::lost, nbsources, Source::next, sourceInfos::received, Source::s, source, sr, Source::ssrc, and writelog().
Referenced by statSessionRTP().
Member Data Documentation
group
uint32_t Session::group
multicast address
Definition at line 35 of file session.hpp.
Referenced by create(), dump(), and Session().
mode
uint8_t Session::mode
WORLD, MANAGER.
Definition at line 39 of file session.hpp.
Referenced by Source::dumpAll(), Source::getMembersNumber(), Rtp::getSdesItemBySsrc(), and Session().
mysdes
SdesItem* Session::mysdes
my own RTCP SDES
Definition at line 45 of file session.hpp.
Referenced by buildSDES(), createMySdes(), dump(), freeMySdes(), refreshMySdes(), and Session().
nbsources
uint16_t Session::nbsources
amount of sources
Definition at line 44 of file session.hpp.
Referenced by create(), deleteSourceBySsrc(), incrSources(), Session(), and stat().
next
Session* Session::next
next session
Definition at line 46 of file session.hpp.
Referenced by deleteSessionBySsrc(), dumpAll(), and Session().
rtcp_port
uint16_t Session::rtcp_port
RTCP port.
Definition at line 37 of file session.hpp.
Referenced by create(), and Session().
rtp_hdr
rtp_hdr_t Session::rtp_hdr
session RTP header
Definition at line 40 of file session.hpp.
Referenced by buildRtpHeader(), and create().
rtp_port
uint16_t Session::rtp_port
RTP port.
Definition at line 36 of file session.hpp.
Referenced by create(), dump(), and Session().
rtp_seq
uint16_t Session::rtp_seq
RTP sequence number.
Definition at line 41 of file session.hpp.
Referenced by buildRtpHeader(), and create().
source
class Source* Session::source
informations on sources
Definition at line 43 of file session.hpp.
Referenced by create(), deleteSourceBySsrc(), Source::getSource(), Session(), and stat().
sr
rtcp_sr_t Session::sr
RTCP sender report.
Definition at line 42 of file session.hpp.
Referenced by buildSR(), create(), Payload::sendPayload(), Session(), and stat().
ssrc
uint32_t Session::ssrc
RTP ssrc id.
Definition at line 34 of file session.hpp.
Referenced by buildBYE(), buildSDES(), and create().
ttl
uint8_t Session::ttl
ttl
Definition at line 38 of file session.hpp.
Referenced by create(), dump(), and Session().
The documentation for this class was generated from the following files:
src/net/session.hpp
src/net/session.cpp