VREng: Noid Class Reference
Noid Class Reference
Noid class.
#include <noid.hpp>
Public Member Functions
class NetObject * getNetObject ()
Gets a NetObject by name, returns NULL if netobject doesn't exist.
char * getNetNameById ()
Builds a concatened string name.
void sendQueryNoid (const struct sockaddr_in *sender)
Send a Query '0x03' packet toi the unicast sender.
void sendDeleteNoid (const struct sockaddr_in *sender)
Send a Delete '0x04' packet toi the unicast sender.
Public Attributes
uint32_t src_id
IPaddr src.
uint16_t port_id
port
uint16_t obj_id
object id – network format
Protected Member Functions
bool equalNoid (Noid noid2) const
Returns 0 if differents, other if equals.
int filterQuery ()
Heuristic to avoid to send bunch of Query.
Friends
class NetObject
Detailed Description
Noid class.
A Noid identifies a distributed netobject on 64 bits (src_id + port_id + obj_id)
Definition at line 31 of file noid.hpp.
Member Function Documentation
equalNoid()
bool Noid::equalNoid (Noid noid2) const protected
Returns 0 if differents, other if equals.
Definition at line 47 of file noid.cpp.
References obj_id, port_id, and src_id.
filterQuery()
int Noid::filterQuery () protected
Heuristic to avoid to send bunch of Query.
Definition at line 76 of file noid.cpp.
getNetNameById()
char * Noid::getNetNameById ()
Builds a concatened string name.
Definition at line 38 of file noid.cpp.
Referenced by Payload::incomingCreate(), Payload::incomingDelete(), Payload::incomingDelta(), and Payload::incomingQuery().
getNetObject()
NetObject * Noid::getNetObject ()
Gets a NetObject by name, returns NULL if netobject doesn't exist.
Header vers noid se fait en lisant directement dans la struct Naming is done by create or createNetObjectFromString.
Definition at line 53 of file noid.cpp.
References error(), NetObject::getList(), OClass::isValidType(), netobjectList, NetObject::next, NetObject::noid, and NetObject::type.
Referenced by Payload::incomingCreate(), Payload::incomingDelete(), Payload::incomingDelta(), and Payload::incomingQuery().
sendDeleteNoid()
void Noid::sendDeleteNoid (const struct sockaddr_in * sender)
Send a Delete '0x04' packet toi the unicast sender.
Definition at line 106 of file noid.cpp.
References DBG_NET, inet4_ntop(), Payload::putPayload(), Payload::sendPayload(), trace(), and VREP_DELETE.
Referenced by Payload::incomingQuery().
sendQueryNoid()
void Noid::sendQueryNoid (const struct sockaddr_in * sender)
Send a Query '0x03' packet toi the unicast sender.
We try to avoid to send too many. Format: '0x03' (c), netobject name (n). Called by incomingDelta.
Definition at line 95 of file noid.cpp.
References DBG_NET, inet4_ntop(), Payload::putPayload(), Payload::sendPayload(), trace(), and VREP_QUERY.
Referenced by Payload::incomingDelta().
Friends And Related Function Documentation
NetObject
friend class NetObject friend
Definition at line 32 of file noid.hpp.
Member Data Documentation
obj_id
uint16_t Noid::obj_id
object id – network format
Definition at line 37 of file noid.hpp.
Referenced by WObject::copyNoid(), NetObject::equalNoid(), equalNoid(), Payload::getPayload(), and Payload::putPayload().
port_id
uint16_t Noid::port_id
port
Definition at line 36 of file noid.hpp.
Referenced by WObject::copyNoid(), NetObject::equalNoid(), equalNoid(), Payload::getPayload(), Payload::incomingQuery(), and Payload::putPayload().
src_id
uint32_t Noid::src_id
IPaddr src.
Definition at line 35 of file noid.hpp.
Referenced by WObject::copyNoid(), NetObject::equalNoid(), equalNoid(), Payload::getPayload(), and Payload::putPayload().
The documentation for this class was generated from the following files:
src/net/noid.hpp
src/net/noid.cpp