VREng: NetProperty Class Reference
NetProperty Class Reference
NetProperty class.
#include <netprop.hpp>
Public Member Functions
NetProperty ()
Constructor.
virtual ~NetProperty ()
Destructor.
virtual void resetDates ()
Computes a new date for the assume_at of the property and sets the last_seen at "now".
virtual void setResponsible (bool flag)
Static Public Member Functions
static uint8_t getPropertiesNumber (uint8_t _type_id)
static void setPropertiesNumber (uint8_t _type_id, uint8_t _nbprop)
static void addToDate (struct timeval *t, double d)
Adds d seconds to the date.
Public Attributes
bool responsible
flag responsibility
int16_t version
version number
struct timeval last_seen
last seen date
struct timeval assume_at
assume at date
float min_assume_delay
min in secs
float max_assume_delay
max in secs
Detailed Description
NetProperty class.
Definition at line 27 of file netprop.hpp.
Constructor & Destructor Documentation
NetProperty()
NetProperty::NetProperty ()
Constructor.
Definition at line 27 of file netprop.cpp.
References DEF_REFRESH_TIMEOUT, max_assume_delay, min_assume_delay, and new_netproperty.
~NetProperty()
NetProperty::~NetProperty () virtual
Destructor.
Definition at line 40 of file netprop.cpp.
References del_netproperty.
Member Function Documentation
addToDate()
void NetProperty::addToDate (struct timeval * t, double d) static
Adds d seconds to the date.
Definition at line 58 of file netprop.cpp.
References d.
Referenced by resetDates().
getPropertiesNumber()
uint8_t NetProperty::getPropertiesNumber (uint8_t _type_id) static
Definition at line 46 of file netprop.cpp.
References getPropertiesnumber().
Referenced by NetObject::getPropertiesNumber(), and NetObject::initProperties().
resetDates()
void NetProperty::resetDates () virtual
Computes a new date for the assume_at of the property and sets the last_seen at "now".
Definition at line 74 of file netprop.cpp.
References addToDate(), assume_at, gettimeofday(), last_seen, max_assume_delay, min_assume_delay, and RAND_MAX.
Referenced by Payload::incomingDelta(), NetObject::initProperties(), and NetObject::sendDelta().
setPropertiesNumber()
void NetProperty::setPropertiesNumber (uint8_t _type_id, uint8_t _nbprop) static
Definition at line 52 of file netprop.cpp.
References setPropertiesnumber().
Referenced by NetObject::setPropertiesNumber().
setResponsible()
void NetProperty::setResponsible (bool flag) virtual
Definition at line 35 of file netprop.cpp.
References responsible.
Referenced by NetObject::declareObjDelta(), Payload::incomingDelta(), and NetObject::sendDelta().
Member Data Documentation
assume_at
struct timeval NetProperty::assume_at
assume at date
Definition at line 30 of file netprop.hpp.
Referenced by NetTimeout(), and resetDates().
last_seen
struct timeval NetProperty::last_seen
last seen date
Definition at line 30 of file netprop.hpp.
Referenced by NetTimeout(), and resetDates().
max_assume_delay
float NetProperty::max_assume_delay
max in secs
Definition at line 34 of file netprop.hpp.
Referenced by NetProperty(), and resetDates().
min_assume_delay
float NetProperty::min_assume_delay
min in secs
Definition at line 33 of file netprop.hpp.
Referenced by NetProperty(), and resetDates().
responsible
bool NetProperty::responsible
flag responsibility
Definition at line 29 of file netprop.hpp.
Referenced by Payload::incomingDelta(), NetObject::initProperties(), NetTimeout(), and setResponsible().
version
int16_t NetProperty::version
version number
Definition at line 30 of file netprop.hpp.
Referenced by NetObject::declareObjDelta(), Payload::incomingCreate(), Payload::incomingDelta(), NetObject::initProperties(), NetTimeout(), and NetObject::sendDelta().
The documentation for this class was generated from the following files:
src/net/netprop.hpp
src/net/netprop.cpp