VREng: Channel Class Reference
Channel Class Reference
Channel class.
#include <channel.hpp>
Public Types
enum { MANAGER_MODE, WORLD_MODE }
Public Member Functions
Channel ()
Constructor.
virtual ~Channel ()
Destructor.
virtual int create (const char *chanstr, int **fds)
Create a Channel channel string is given by decode channel structure is given bye Channel return number of fd to survey.
virtual void naming ()
Channel naming init my_host_id, my_port_id, my_obj_id.
virtual void addToList ()
Adds a channel into a list.
virtual void deleteFromList ()
Deletes a channel from a list.
virtual void quit ()
Quits a channel.
virtual int createMcastRecvSocket (struct sockaddr_in *sa)
Creates a Multicast listen socket on the channel defined by group/port.
virtual void closeMcastSocket ()
Closes Multicast sockets.
virtual void closeUcastSocket ()
Closes Unicast sockets.
virtual void sendBYE ()
Sends a BYE RTCP.
virtual int joinGroup (int sock)
Joins group (IP_ADD_MEMBERSHIP).
virtual int leaveGroup (int sock)
Leaves group (IP_DROP_MEMBERSHIP).
Static Public Member Functions
static void init ()
Network Initialization.
static void initReflector ()
Reflector Initialization.
static void clearList ()
Clears channelList.
static Channel * getList ()
Gets list pointer.
static void decode (const char *chan_str, uint32_t *group, uint16_t *port, uint8_t *ttl)
Decodes the string format "group[/port[/ttl]]".
static bool join (char *chan_str)
Joins the channel and return the new channel string.
static bool joinManager (char *manager_str, const char *chan_str)
Only for vreng client.
static Channel * current ()
Gets current channel instance.
static Channel * getManager ()
Gets manager channel.
static Channel * getbysa (const struct sockaddr_in *sa)
get a channel by sockaddr_in
static int getFdSendRTP (const struct sockaddr_in *sa)
static int getFdSendRTCP (const struct sockaddr_in *sa)
static struct sockaddr_in * getSaRTCP (const struct sockaddr_in *sa)
static int getfdbysa (const struct sockaddr_in *sa, int sd)
get a socket fd by sockaddr_in
static struct sockaddr_in * getsabysa (const struct sockaddr_in *sa, int sd)
get a socket address by sockaddr_in
static void getGroup (const char *chanstr, char *group)
static uint16_t getPort (const char *chanstr)
static uint8_t getTtl (const char *chanstr)
static uint8_t currentTtl ()
static void newChanStr (char *chan_str)
Public Attributes
uint32_t ssrc
ssrcid
uint32_t group
group address
uint16_t port
RTP port.
uint8_t ttl
ttl scope
uint8_t cntfds
fd numbers
int sd [5]
sockets descriptors
struct sockaddr_in * sa [5]
sockets addresses
struct sockaddr_in sa_rtp
RTP data.
struct sockaddr_in sa_rtcp
RTCP data.
struct sockaddr_in sa_rtp_r
RTP data reflector.
struct sockaddr_in sa_rtcp_r
RTCP data reflector.
struct sockaddr_in sa_data
UDP datas.
struct ip_mreq mreq
IGMPv2.
class Session * session
RTP session.
Static Private Attributes
static list< Channel * > channelList
Detailed Description
Channel class.
Definition at line 30 of file channel.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
MANAGER_MODE
WORLD_MODE
Definition at line 51 of file channel.hpp.
Constructor & Destructor Documentation
Channel()
Channel::Channel ()
Constructor.
Create a new Channel.
Definition at line 85 of file channel.cpp.
References new_channel.
~Channel()
Channel::~Channel () virtual
Destructor.
Channel destructor.
Definition at line 413 of file channel.cpp.
References channel, channelCount, Socket::closeDatagram(), cntFd, DBG_IPMC, del_channel, g, Global::gui, Gui::removeChannelSources(), tabFd, and trace().
Member Function Documentation
addToList()
void Channel::addToList () virtual
Adds a channel into a list.
Definition at line 108 of file channel.cpp.
clearList()
void Channel::clearList () static
Clears channelList.
Definition at line 98 of file channel.cpp.
Referenced by init().
closeMcastSocket()
void Channel::closeMcastSocket () virtual
Closes Multicast sockets.
Definition at line 146 of file channel.cpp.
References Socket::closeDatagram(), SD_R_RTCP, SD_R_RTP, SD_W_RTCP, and SD_W_RTP.
closeUcastSocket()
void Channel::closeUcastSocket () virtual
Closes Unicast sockets.
Definition at line 161 of file channel.cpp.
References Socket::closeDatagram(), and SD_R_UDP.
create()
int Channel::create (const char * chanstr, int ** fds) virtual
Create a Channel channel string is given by decode channel structure is given bye Channel return number of fd to survey.
Create a Channel.
Usage: int *fds; int count = createChannel(chan_str, &fds); for (i=0; i < count; i++) { addThisFdToWatchList(fds[i]); } create sockets mcast_recv_rtp and mcast_send_rtp sockets mcast_recv_rtcp and mcast_send_rtcp
Definition at line 236 of file channel.cpp.
References cntFd, Socket::createSendSocket(), World::current(), DBG_RTP, error(), g, World::getSsrc(), inet4_pton(), managerChannel, Global::pref, Pref::reflector, SA_RTCP, SA_RTCP_R, SA_RTP, SA_RTP_R, SA_UDP, SD_R_RTCP, SD_R_RTP, SD_W_RTCP, SD_W_RTP, World::setGroupAdr(), NetObject::setMyMgrSsrcId(), NetObject::setMySsrcId(), World::setSsrc(), trace(), vrum_addr, VRUM_PORT_OFFSET, warning(), and World::worldByGroup().
Referenced by Aoi::aoiEnter(), join(), and joinManager().
createMcastRecvSocket()
int Channel::createMcastRecvSocket (struct sockaddr_in * sa) virtual
Creates a Multicast listen socket on the channel defined by group/port.
Create a Multicast listen socket on the channel defined by group/port.
Returns sock else -1 if problem.
Definition at line 131 of file channel.cpp.
References error(), Socket::openDatagram(), and Socket::reuseAddr().
current()
Channel * Channel::current () static
Gets current channel instance.
Definition at line 167 of file channel.cpp.
References channel.
Referenced by Aoi::aoiQuit(), World::call(), NetObject::declareDeletion(), NetObject::declareObjCreation(), Gate::enter(), Source::getSource(), Gui::gotoWorld(), Widgets::homeCB(), Global::quitVreng(), Rtp::recvRTCPPacket(), sandboxCB(), NetObject::sendDelta(), and Payload::sendPayload().
currentTtl()
uint8_t Channel::currentTtl () static
Definition at line 583 of file channel.cpp.
References Universe::current(), and Universe::ttl.
Referenced by Clip::contRtp(), Gate::enter(), Audio::getnewchan(), Video::getnewchan(), Wb::getnewchan(), Widgets::homeCB(), Clip::pauseRtp(), Audio::start(), Video::start(), Clip::startRtp(), and Clip::stopRtp().
decode()
void Channel::decode (const char * chan_str, uint32_t * group, uint16_t * port, uint8_t * ttl) static
Decodes the string format "group[/port[/ttl]]".
Decode the string format "group[/port[/ttl]]".
Returns group, port, ttl. If chan_str == "" or NULL, we get the default values.
Definition at line 178 of file channel.cpp.
deleteFromList()
void Channel::deleteFromList () virtual
Deletes a channel from a list.
Delete from channelList.
Definition at line 389 of file channel.cpp.
References DBG_NET, error(), managerChannel, and trace().
getbysa()
Channel * Channel::getbysa (const struct sockaddr_in * sa) static
get a channel by sockaddr_in
Definition at line 518 of file channel.cpp.
References DBG_NET, error(), SA_RTCP, SA_RTP, SA_UDP, and trace().
Referenced by Payload::sendPayload().
getfdbysa()
int Channel::getfdbysa (const struct sockaddr_in * sa, int sd) static
get a socket fd by sockaddr_in
Definition at line 470 of file channel.cpp.
References DBG_NET, error(), SA_RTCP, SA_RTP, and trace().
getFdSendRTCP()
int Channel::getFdSendRTCP (const struct sockaddr_in * sa) static
Definition at line 496 of file channel.cpp.
References SD_W_RTCP.
Referenced by Session::sendRTCPPacket(), and Session::sendSRSDES().
getFdSendRTP()
int Channel::getFdSendRTP (const struct sockaddr_in * sa) static
Definition at line 491 of file channel.cpp.
References SD_W_RTP.
Referenced by Payload::sendPayload().
getGroup()
void Channel::getGroup (const char * chanstr, char * group) static
Definition at line 536 of file channel.cpp.
References DBG_IPMC, error(), GROUP_LEN, trace(), and warning().
Referenced by World::call(), Android::connectToBapServer(), Clip::contRtp(), Audio::getnewchan(), Video::getnewchan(), Wb::getnewchan(), World::init(), Android::initReceiver(), Clip::pauseRtp(), Video::start(), Clip::startRtp(), Clip::stopRtp(), and Universe::Universe().
getList()
Channel * Channel::getList () static
Gets list pointer.
Definition at line 103 of file channel.cpp.
getManager()
Channel * Channel::getManager () static
Gets manager channel.
Definition at line 172 of file channel.cpp.
References managerChannel.
Referenced by Global::quitVreng().
getPort()
uint16_t Channel::getPort (const char * chanstr) static
Definition at line 568 of file channel.cpp.
References DBG_IPMC, DEF_VRE_MPORT, and trace().
Referenced by Clip::contRtp(), Audio::getnewchan(), Video::getnewchan(), Wb::getnewchan(), World::init(), Android::inits(), Clip::pauseRtp(), Video::start(), Clip::startRtp(), and Clip::stopRtp().
getsabysa()
struct sockaddr_in * Channel::getsabysa (const struct sockaddr_in * sa, int sd) static
get a socket address by sockaddr_in
Definition at line 502 of file channel.cpp.
References error(), SA_RTCP, and SA_RTP.
getSaRTCP()
struct sockaddr_in * Channel::getSaRTCP (const struct sockaddr_in * sa) static
Definition at line 512 of file channel.cpp.
References SA_RTCP.
Referenced by Session::sendRTCPPacket(), and Session::sendSRSDES().
getTtl()
uint8_t Channel::getTtl (const char * chanstr) static
Definition at line 589 of file channel.cpp.
References DBG_IPMC, DEF_VRE_TTL, and trace().
Referenced by Android::connectToBapServer(), and Universe::Universe().
init()
void Channel::init () static
Network Initialization.
Definition at line 70 of file channel.cpp.
References clearList(), NetObject::clearList(), Session::clearList(), first, g, Times::net, ProfileTime::start(), and Global::times.
Referenced by Global::startCB().
initReflector()
void Channel::initReflector () static
Reflector Initialization.
Find the VRUM address and check if the MBone works.
Definition at line 56 of file channel.cpp.
References DEF_VRUM_SERVER, g, inet4_ntop(), Sap::init(), my_free_hostent(), my_gethostbyname(), Global::pref, Pref::reflector, and vrum_addr.
join()
bool Channel::join (char * chan_str) static
Joins the channel and return the new channel string.
join the channel and return the new channel string
Sets the global variables: currentChannel, cntFd, tabFd
Definition at line 433 of file channel.cpp.
References Gui::addChannelSources(), channel, channelCount, create(), DBG_IPMC, g, Global::gui, tabFd, and trace().
Referenced by World::call(), Gate::enter(), and World::setChanAndJoin().
joinGroup()
int Channel::joinGroup (int sock) virtual
Joins group (IP_ADD_MEMBERSHIP).
Join group.
"group" in network format, returns sock if OK, else -1.
Definition at line 114 of file channel.cpp.
References Socket::addMembership().
joinManager()
bool Channel::joinManager (char * manager_str, const char * chan_str) static
Only for vreng client.
joinManagerChannel: only for vreng client
Sets the global variables: managerChannel, cntManagerFd, tabManagerFd.
Definition at line 453 of file channel.cpp.
References Gui::addChannelSources(), create(), DBG_INIT, g, Global::gui, managerChannel, tabManagerFd, and trace().
Referenced by World::setManagerChanAndJoin().
leaveGroup()
int Channel::leaveGroup (int sock) virtual
Leaves group (IP_DROP_MEMBERSHIP).
Leave group.
Returns sock if OK, else -1.
Definition at line 124 of file channel.cpp.
References Socket::dropMembership().
naming()
void Channel::naming () virtual
Channel naming init my_host_id, my_port_id, my_obj_id.
Channel naming.
Definition at line 202 of file channel.cpp.
References DBG_NET, NetObject::getMyPortId(), NetObject::getMySsrcId(), Socket::getSrcPort(), MAXHOSTNAMELEN, my_free_hostent(), my_gethostbyname(), SA_RTCP, SA_RTP, SD_W_RTP, Payload::sendPayload(), NetObject::setMyHostId(), NetObject::setMyObjId(), NetObject::setMyPortId(), and trace().
newChanStr()
void Channel::newChanStr (char * chan_str) static
Definition at line 605 of file channel.cpp.
References CHAN_LEN, DBG_IPMC, GROUP_LEN, trace(), and warning().
quit()
void Channel::quit () virtual
Quits a channel.
Definition at line 398 of file channel.cpp.
References DBG_RTP, managerChannel, and trace().
sendBYE()
void Channel::sendBYE () virtual
Sends a BYE RTCP.
Definition at line 379 of file channel.cpp.
References DBG_NET, RTCP_BYE, RTCP_SR, SA_RTCP, and trace().
Member Data Documentation
channelList
list< Channel * > Channel::channelList static private
Definition at line 32 of file channel.hpp.
cntfds
uint8_t Channel::cntfds
fd numbers
Definition at line 39 of file channel.hpp.
group
uint32_t Channel::group
group address
Definition at line 36 of file channel.hpp.
mreq
struct ip_mreq Channel::mreq
IGMPv2.
Definition at line 41 of file channel.hpp.
port
uint16_t Channel::port
RTP port.
Definition at line 37 of file channel.hpp.
sa
struct sockaddr_in* Channel::sa[5]
sockets addresses
Definition at line 41 of file channel.hpp.
Referenced by NetObject::declareDeletion(), NetObject::declareObjCreation(), and NetObject::sendDelta().
sa_data
struct sockaddr_in Channel::sa_data
UDP datas.
Definition at line 41 of file channel.hpp.
sa_rtcp
struct sockaddr_in Channel::sa_rtcp
RTCP data.
Definition at line 41 of file channel.hpp.
sa_rtcp_r
struct sockaddr_in Channel::sa_rtcp_r
RTCP data reflector.
Definition at line 41 of file channel.hpp.
sa_rtp
struct sockaddr_in Channel::sa_rtp
RTP data.
Definition at line 41 of file channel.hpp.
sa_rtp_r
struct sockaddr_in Channel::sa_rtp_r
RTP data reflector.
Definition at line 41 of file channel.hpp.
sd
int Channel::sd[5]
sockets descriptors
Definition at line 40 of file channel.hpp.
Referenced by Payload::sendPayload().
session
class Session* Channel::session
RTP session.
Definition at line 48 of file channel.hpp.
Referenced by Source::getSource(), Rtp::recvRTCPPacket(), and Payload::sendPayload().
ssrc
uint32_t Channel::ssrc
ssrcid
Definition at line 35 of file channel.hpp.
Referenced by Payload::sendPayload().
ttl
uint8_t Channel::ttl
ttl scope
Definition at line 38 of file channel.hpp.
The documentation for this class was generated from the following files:
src/net/channel.hpp
src/net/channel.cpp