VREng: NetObject Class Reference
NetObject Class Reference
NetObject class.
#include <netobj.hpp>
Public Types
enum { NET_VOLATILE, NET_PERMANENT }
Public Member Functions
NetObject ()
Constructor for local.
NetObject (WObject *po, uint8_t nprop, uint16_t oid)
Constructor for local ppermanent with args.
NetObject (WObject *po, uint8_t nprop)
Constructor for local volatile with args.
NetObject (WObject *po, uint8_t nprop, class Noid _noid)
Constructor for replica.
virtual ~NetObject ()
Destructor.
virtual void defaults ()
Common to constructors.
virtual void addToList ()
Inserts netobject in head of NetObject list.
virtual void deleteFromList ()
Removes the NetObject from the list.
virtual void create (bool netbehave)
Creates a new local netobject.
virtual void setNoid ()
Initializes a new NetObject.
virtual void buildNoidFromString (const char *str, bool netbehave)
Build a NetObject name from a string "scene_id/obj_id", both uint16_t > 0 Used by getNetObject and declareObjDelta.
virtual void declareObjCreation ()
We assume the header yet initialized, should (perfs) be called after the NetObject naming create() and the initialization of properties.
virtual void declareObjDelta (uint8_t prop_id)
Update netobject version.
virtual void declareDeletion ()
Destroy the netobject (local copy), netobject must be valid (name).
virtual void setSrcId (uint32_t src_id)
virtual void setPortId (uint16_t port_id)
virtual void setObjId (uint16_t obj_id)
virtual uint32_t getSrcId () const
virtual uint16_t getPortId () const
virtual uint16_t getObjId () const
virtual void sendCreate (const struct sockaddr_in *to)
Send a '0x01' packet to mentionned unicast address for the current object we don't touch version and dates Format: '0x01' (c), netobject type (c), netobject name (n), netbehave (c) then the initialization payload, obtained by a putAllProperties() then the version vector (nprop *pn).
virtual void sendDelta (uint8_t prop_id)
Send a multicast packet of type '0x02' = Delta, on the property prop_id of the netobject.
virtual void sendDelete (const struct sockaddr_in *to)
Send a Delete '0x04' packet to the unicast sender.
virtual void initProperties (bool responsible)
Initializes responsibilities (false=no, true=yes).
virtual uint8_t getPropertiesNumber () const
virtual void setPropertiesNumber (uint8_t _nbprop)
virtual void getProperty (uint8_t prop, class Payload *pp) const
Modifies the property (its local copy) get from Network.
virtual void putProperty (uint8_t prop, class Payload *pp)
Puts the property (its local copy) to be sent to Network.
virtual void getAllProperties (class Payload *pp) const
Gets all properties from the network.
virtual void putAllProperties (class Payload *pp)
Puts all properties of this netobject.
virtual void requestDeletionFromNetwork ()
Supprime object du monde, si object n'est pas le local user The sequence must include deleteNetObject.
virtual WObject * getWObjectByNoid () const
Finds a WObject pointer by its noid.
virtual bool isResponsible () const
virtual bool isPermanent () const
NetObject * getNetObject ()
Gets a NetObject by name, returns NULL if netobject doesn't exist.
char * getNetNameById ()
Builds a concatened string name.
void sendQueryNoid (const struct sockaddr_in *sender)
Send a Query '0x03' packet toi the unicast sender.
void sendDeleteNoid (const struct sockaddr_in *sender)
Send a Delete '0x04' packet toi the unicast sender.
Static Public Member Functions
static void setMySsrcId (uint32_t ssrc_id)
static void setMyMgrSsrcId (uint32_t ssrc_id)
static void setMyHostId (uint32_t host_id)
static void setMyPortId (uint16_t port_id)
static void setMyObjId (uint16_t obj_id)
static uint32_t getMySsrcId ()
static uint32_t getMyMgrSsrcId ()
static uint32_t getMyHostId ()
static uint16_t getMyPortId ()
static uint16_t getMyObjId ()
static uint8_t getPropertiesNumber (uint8_t type_id)
Returns le number of properties for this type.
static void setPropertiesNumber (uint8_t type_id, uint8_t _nbprop)
Sets the number of properties for this type.
static NetObject * getList ()
Gets th NetObject list.
static void clearList ()
Clears th NetObject list.
static NetObject * replicateObject (uint8_t type, class Noid noid, class Payload *pp)
Dispatching the replicated object.
Public Attributes
class Noid noid
NetObject id.
uint8_t type
NetObject type.
uint8_t permanent
permanent or valatile (not a true bool)
uint8_t nbprop
number of properties
class WObject * pobject
pointer on the WObject
class NetProperty * netprop
netobject properties
NetObject * next
next
NetObject * prev
prev
Static Public Attributes
static NetObject * netObjectList
netobject list
Protected Member Functions
bool equalNoid (class Noid noid2) const
Returns 0 if differents, other if equals.
int filterQuery ()
Heuristic to avoid to send bunch of Query.
Static Private Attributes
static uint32_t mySsrcId = 0
ssrc network format
static uint32_t myHostId = 0
addr_IP network format
static uint16_t myPortId = 0
port network format
static uint16_t myObjId = 0
new object'id (naming), fmt host
static uint32_t myMgrSsrcId = 0
manager ssrc network format
Friends
class Payload
class Noid
Detailed Description
NetObject class.
Definition at line 33 of file netobj.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
NET_VOLATILE
NET_PERMANENT
Definition at line 55 of file netobj.hpp.
Constructor & Destructor Documentation
NetObject() [1/4]
NetObject::NetObject ()
Constructor for local.
Definition at line 69 of file netobj.cpp.
NetObject() [2/4]
NetObject::NetObject (WObject * po, uint8_t nprop, uint16_t oid)
Constructor for local ppermanent with args.
Definition at line 79 of file netobj.cpp.
References DBG_NET, oid, trace(), and WObject::typeId().
NetObject() [3/4]
NetObject::NetObject (WObject * po, uint8_t nprop)
Constructor for local volatile with args.
Definition at line 94 of file netobj.cpp.
References WObject::type.
NetObject() [4/4]
NetObject::NetObject (WObject * po, uint8_t nprop, class Noid _noid)
Constructor for replica.
Definition at line 106 of file netobj.cpp.
References WObject::type.
~NetObject()
NetObject::~NetObject () virtual
Destructor.
Definition at line 341 of file netobj.cpp.
References del_netobject.
Member Function Documentation
addToList()
void NetObject::addToList () virtual
Inserts netobject in head of NetObject list.
Definition at line 219 of file netobj.cpp.
References netobjectList, and prev.
Referenced by Payload::incomingCreate().
buildNoidFromString()
void NetObject::buildNoidFromString (const char * str, bool netbehave) virtual
Build a NetObject name from a string "scene_id/obj_id", both uint16_t > 0 Used by getNetObject and declareObjDelta.
A declareObjCreation on such netobject produces a fatal.
Definition at line 294 of file netobj.cpp.
References error(), and warning().
clearList()
void NetObject::clearList () static
Clears th NetObject list.
Definition at line 128 of file netobj.cpp.
References netobjectList.
Referenced by Channel::init().
create()
void NetObject::create (bool netbehave) virtual
Creates a new local netobject.
Then we can do getNetObject, declareObjDelta. One declareObjCreation is wish latter, when props are set.
Definition at line 281 of file netobj.cpp.
Referenced by Aoi::aoiEnter().
declareDeletion()
void NetObject::declareDeletion () virtual
Destroy the netobject (local copy), netobject must be valid (name).
To call when we want destroy the object before a deleteNetObject.
Definition at line 499 of file netobj.cpp.
References Channel::current(), Channel::sa, SA_RTP, and warning().
Referenced by Aoi::aoiQuit(), World::quit(), and User::~User().
declareObjCreation()
void NetObject::declareObjCreation () virtual
We assume the header yet initialized, should (perfs) be called after the NetObject naming create() and the initialization of properties.
To call for each new objects.
Definition at line 462 of file netobj.cpp.
References Channel::current(), Channel::sa, and SA_RTP.
Referenced by Aoi::aoiEnter(), Bullet::Bullet(), Dart::Dart(), and Cart::leaveIntoWorld().
declareObjDelta()
void NetObject::declareObjDelta (uint8_t prop_id) virtual
Update netobject version.
To call at each modification, eg. after a property value changes.
Definition at line 478 of file netobj.cpp.
References error(), NetProperty::setResponsible(), NetProperty::version, and VREP_VERS_JUMP.
Referenced by Payload::incomingDelta(), Solid::resetRay(), Solid::setRay(), User::setRayDirection(), Button::updateToNetwork(), Door::updateToNetwork(), Lift::updateToNetwork(), Projectile::updateToNetwork(), User::updateToNetwork(), User::userRequesting(), and User::userWriting().
defaults()
void NetObject::defaults () virtual
Common to constructors.
Definition at line 61 of file netobj.cpp.
References new_netobject.
deleteFromList()
void NetObject::deleteFromList () virtual
Removes the NetObject from the list.
To do necessarly before the final delete.
Definition at line 319 of file netobj.cpp.
References error(), netobjectList, next, and prev.
Referenced by Aoi::aoiQuit(), and World::quit().
equalNoid()
bool NetObject::equalNoid (class Noid noid2) const protected
Returns 0 if differents, other if equals.
Definition at line 529 of file netobj.cpp.
References Noid::obj_id, Noid::port_id, and Noid::src_id.
Referenced by Payload::incomingCreate().
filterQuery()
int NetObject::filterQuery () protected
Heuristic to avoid to send bunch of Query.
Definition at line 561 of file netobj.cpp.
getAllProperties()
void NetObject::getAllProperties (class Payload * pp) const virtual
Gets all properties from the network.
Definition at line 384 of file netobj.cpp.
Referenced by Ball::Ball(), Bullet::Bullet(), Dart::Dart(), and Icon::Icon().
getList()
NetObject * NetObject::getList () static
Gets th NetObject list.
Definition at line 122 of file netobj.cpp.
References netobjectList.
Referenced by Noid::getNetObject(), and NetTimeout().
getMyHostId()
uint32_t NetObject::getMyHostId () static
Definition at line 163 of file netobj.cpp.
Referenced by NetIncoming(), and Payload::recvPayload().
getMyMgrSsrcId()
uint32_t NetObject::getMyMgrSsrcId () static
Definition at line 142 of file netobj.cpp.
getMyObjId()
uint16_t NetObject::getMyObjId () static
Definition at line 183 of file netobj.cpp.
Referenced by WObject::setWObjectId().
getMyPortId()
uint16_t NetObject::getMyPortId () static
Definition at line 173 of file netobj.cpp.
Referenced by Channel::naming(), NetIncoming(), and WObject::setWObjectId().
getMySsrcId()
uint32_t NetObject::getMySsrcId () static
Definition at line 153 of file netobj.cpp.
Referenced by Session::buildSR(), Channel::naming(), Payload::recvPayload(), VjcMessage::sendData(), User::setRtcp(), WObject::setWObjectId(), Vjc::Vjc(), VjcMessage::VjcMessage(), and Session::~Session().
getNetNameById()
char * NetObject::getNetNameById ()
Builds a concatened string name.
Definition at line 520 of file netobj.cpp.
Referenced by Payload::incomingCreate(), and Payload::incomingQuery().
getNetObject()
NetObject * NetObject::getNetObject ()
Gets a NetObject by name, returns NULL if netobject doesn't exist.
Header vers noid se fait en lisant directement dans la struct Naming is done by create or createNetObjectFromString.
Definition at line 537 of file netobj.cpp.
References error(), OClass::isValidType(), netobjectList, next, noid, and type.
getObjId()
uint16_t NetObject::getObjId () const virtual
Definition at line 213 of file netobj.cpp.
getPortId()
uint16_t NetObject::getPortId () const virtual
Definition at line 203 of file netobj.cpp.
getPropertiesNumber() [1/2]
uint8_t NetObject::getPropertiesNumber () const virtual
Definition at line 249 of file netobj.cpp.
References NetProperty::getPropertiesNumber().
Referenced by Payload::incomingCreate(), Payload::incomingDelta(), NetTimeout(), and User::User().
getPropertiesNumber() [2/2]
uint8_t NetObject::getPropertiesNumber (uint8_t type_id) static
Returns le number of properties for this type.
Numbered from 0 to propertiesnumber-1. Typically called after an incomingCreate.
Definition at line 255 of file netobj.cpp.
References NetProperty::getPropertiesNumber().
getProperty()
void NetObject::getProperty (uint8_t prop, class Payload * pp) const virtual
Modifies the property (its local copy) get from Network.
The new value is in the payload. We must return the new read position given by getPayload. Typically called after an incomingDelta.
Definition at line 373 of file netobj.cpp.
Referenced by Payload::incomingDelta(), and User::User().
getSrcId()
uint32_t NetObject::getSrcId () const virtual
Definition at line 193 of file netobj.cpp.
getWObjectByNoid()
WObject * NetObject::getWObjectByNoid () const virtual
Finds a WObject pointer by its noid.
Definition at line 362 of file netobj.cpp.
References mobileList.
initProperties()
void NetObject::initProperties (bool responsible) virtual
Initializes responsibilities (false=no, true=yes).
Dates handled by resetDates.
Definition at line 230 of file netobj.cpp.
References DBG_NET, NetProperty::getPropertiesNumber(), NetProperty::resetDates(), NetProperty::responsible, trace(), and NetProperty::version.
Referenced by Payload::incomingCreate().
isPermanent()
bool NetObject::isPermanent () const virtual
Definition at line 351 of file netobj.cpp.
isResponsible()
bool NetObject::isResponsible () const virtual
Definition at line 356 of file netobj.cpp.
Referenced by WObject::imposedMovement(), and WObject::permanentMovement().
putAllProperties()
void NetObject::putAllProperties (class Payload * pp) virtual
Puts all properties of this netobject.
The payload is initialized before, and filled here. Called to known the Payload after one declareObjCreation.
Definition at line 391 of file netobj.cpp.
putProperty()
void NetObject::putProperty (uint8_t prop, class Payload * pp) virtual
Puts the property (its local copy) to be sent to Network.
Then we must write the payload which return the written length. Typically called to fill a payload before a sendDelta.
Definition at line 379 of file netobj.cpp.
replicateObject()
NetObject * NetObject::replicateObject (uint8_t type, class Noid noid, class Payload * pp) static
Dispatching the replicated object.
Creates a replication (local copy) of the object. All its fields will be intilisalized by the WObject itself using appropriated getProperty(). Typically called after an incomingCreate().
Definition at line 404 of file netobj.cpp.
References error(), WObject::noh, and OClass::replicatorInstance().
Referenced by Payload::incomingCreate().
requestDeletionFromNetwork()
void NetObject::requestDeletionFromNetwork () virtual
Supprime object du monde, si object n'est pas le local user The sequence must include deleteNetObject.
1) faire le menage et afficher tout ce qui est necessaire. 2) si la decision a ete prise localement: declareDeletion 3) deleteNetObject le nom devient invalide, plus aucun declare n'est possible 4) faire le delete object final
Definition at line 398 of file netobj.cpp.
Referenced by Payload::incomingDelete().
sendCreate()
void NetObject::sendCreate (const struct sockaddr_in * to) virtual
Send a '0x01' packet to mentionned unicast address for the current object we don't touch version and dates Format: '0x01' (c), netobject type (c), netobject name (n), netbehave (c) then the initialization payload, obtained by a putAllProperties() then the version vector (nprop *pn).
Definition at line 444 of file netobj.cpp.
References DBG_NET, Payload::dumpPayload(), inet4_ntop(), Payload::putPayload(), Payload::sendPayload(), trace(), and VREP_CREATE.
Referenced by Payload::incomingQuery().
sendDelete()
void NetObject::sendDelete (const struct sockaddr_in * to) virtual
Send a Delete '0x04' packet to the unicast sender.
Format: '0x04' (c), netobject name (n).
Definition at line 511 of file netobj.cpp.
References DBG_NET, inet4_ntop(), Payload::putPayload(), Payload::sendPayload(), trace(), and VREP_DELETE.
sendDeleteNoid()
void NetObject::sendDeleteNoid (const struct sockaddr_in * sender)
Send a Delete '0x04' packet toi the unicast sender.
Definition at line 591 of file netobj.cpp.
References DBG_NET, inet4_ntop(), Payload::putPayload(), Payload::sendPayload(), trace(), and VREP_DELETE.
sendDelta()
void NetObject::sendDelta (uint8_t prop_id) virtual
Send a multicast packet of type '0x02' = Delta, on the property prop_id of the netobject.
We do a resetDates (not version). Format: '0x02' (c), netobject name (n), property number (c), version (h), netobject's properties.
Definition at line 418 of file netobj.cpp.
References Channel::current(), error(), Payload::putPayload(), NetProperty::resetDates(), Channel::sa, SA_RTP, Payload::sendPayload(), NetProperty::setResponsible(), NetProperty::version, and VREP_DELTA.
Referenced by User::whenIntersect().
sendQueryNoid()
void NetObject::sendQueryNoid (const struct sockaddr_in * sender)
Send a Query '0x03' packet toi the unicast sender.
We try to avoid to send too many. Format: '0x03' (c), netobject name (n). Called by incomingDelta.
Definition at line 580 of file netobj.cpp.
References DBG_NET, inet4_ntop(), Payload::putPayload(), Payload::sendPayload(), trace(), and VREP_QUERY.
setMyHostId()
void NetObject::setMyHostId (uint32_t host_id) static
Definition at line 158 of file netobj.cpp.
Referenced by Channel::naming().
setMyMgrSsrcId()
void NetObject::setMyMgrSsrcId (uint32_t ssrc_id) static
Definition at line 137 of file netobj.cpp.
Referenced by Channel::create().
setMyObjId()
void NetObject::setMyObjId (uint16_t obj_id) static
Definition at line 178 of file netobj.cpp.
Referenced by Channel::naming(), and WObject::setWObjectId().
setMyPortId()
void NetObject::setMyPortId (uint16_t port_id) static
Definition at line 168 of file netobj.cpp.
Referenced by Channel::naming().
setMySsrcId()
void NetObject::setMySsrcId (uint32_t ssrc_id) static
Definition at line 147 of file netobj.cpp.
Referenced by Channel::create().
setNoid()
void NetObject::setNoid () virtual
Initializes a new NetObject.
Assigns a unique identifier to each Vreng local netobject whether if be a networked object or not. Now we can do getObjId and declareObjDelta. It is preferable (perfs) to do a declareObjCreation when all the properties are initialized.
Definition at line 273 of file netobj.cpp.
setObjId()
void NetObject::setObjId (uint16_t obj_id) virtual
Definition at line 208 of file netobj.cpp.
setPortId()
void NetObject::setPortId (uint16_t port_id) virtual
Definition at line 198 of file netobj.cpp.
setPropertiesNumber() [1/2]
void NetObject::setPropertiesNumber (uint8_t _nbprop) virtual
Definition at line 261 of file netobj.cpp.
References NetProperty::setPropertiesNumber().
setPropertiesNumber() [2/2]
void NetObject::setPropertiesNumber (uint8_t type_id, uint8_t _nbprop) static
Sets the number of properties for this type.
Definition at line 267 of file netobj.cpp.
References NetProperty::setPropertiesNumber().
setSrcId()
void NetObject::setSrcId (uint32_t src_id) virtual
Definition at line 188 of file netobj.cpp.
Friends And Related Function Documentation
Noid
friend class Noid friend
Definition at line 35 of file netobj.hpp.
Payload
friend class Payload friend
Definition at line 34 of file netobj.hpp.
Member Data Documentation
myHostId
uint32_t NetObject::myHostId = 0 static private
addr_IP network format
Definition at line 40 of file netobj.hpp.
myMgrSsrcId
uint32_t NetObject::myMgrSsrcId = 0 static private
manager ssrc network format
Definition at line 43 of file netobj.hpp.
myObjId
uint16_t NetObject::myObjId = 0 static private
new object'id (naming), fmt host
Definition at line 42 of file netobj.hpp.
myPortId
uint16_t NetObject::myPortId = 0 static private
port network format
Definition at line 41 of file netobj.hpp.
mySsrcId
uint32_t NetObject::mySsrcId = 0 static private
ssrc network format
Definition at line 39 of file netobj.hpp.
nbprop
uint8_t NetObject::nbprop
number of properties
Definition at line 49 of file netobj.hpp.
netObjectList
NetObject* NetObject::netObjectList static
netobject list
Definition at line 249 of file netobj.hpp.
netprop
class NetProperty* NetObject::netprop
netobject properties
Definition at line 51 of file netobj.hpp.
Referenced by Payload::incomingCreate(), and Payload::incomingDelta().
next
NetObject* NetObject::next
next
Definition at line 52 of file netobj.hpp.
Referenced by deleteFromList(), getNetObject(), Noid::getNetObject(), and NetTimeout().
noid
class Noid NetObject::noid
NetObject id.
Definition at line 43 of file netobj.hpp.
Referenced by getNetObject(), Noid::getNetObject(), and Payload::incomingCreate().
permanent
uint8_t NetObject::permanent
permanent or valatile (not a true bool)
Definition at line 48 of file netobj.hpp.
Referenced by Payload::incomingCreate().
pobject
class WObject* NetObject::pobject
pointer on the WObject
Definition at line 50 of file netobj.hpp.
prev
NetObject* NetObject::prev
prev
Definition at line 53 of file netobj.hpp.
Referenced by addToList(), and deleteFromList().
type
uint8_t NetObject::type
NetObject type.
Definition at line 47 of file netobj.hpp.
Referenced by getNetObject(), Noid::getNetObject(), Payload::incomingCreate(), and Payload::incomingDelta().
The documentation for this class was generated from the following files:
src/net/netobj.hpp
src/net/netobj.cpp