VREng: WObject Class Reference
WObject Class Reference
WObject Class.
#include <wobject.hpp>
Inherited by Android, Animator, AnimX3d, Aoi, Area, Ball, Bgcolor, Board, Book, Button, Carrier, Cart, Cauldron, Clip, Clock, Cloth, Cloud, Doc, Door, Entry, Fire, Flag, Fractal, Ftp, Gate, Ground, Guide, Guy, Hairs, Head, Host, Icon, Lift, Light, Mech, Mirage, Mirror, Model, Movie, Music, Particle, Plane, Projectile, River, Sheet, Stars, Step, Sun, Template, Terrain, Text, Thing, Thunder, Transform, User, Vjc, Vnc, Vrelet, Wall, Walls, Water, Web, Widget, and Wind.
Public Types
enum {
STILL, MOBILE, EPHEMERAL, INVISIBLE,
MOBILEINVISIBLE, MODE_MAX
}
enum {
DELETED = -1, NONE = 0, INACTIVE = 0, ACTIVE,
PLAYING, TAKEN, DROPPED, MOVED,
CARRYING, IN_CART, ENDSTATE
}
enum { RENDER_LOW, RENDER_NORMAL, RENDER_HIGH }
typedef std::list< class Solid * > solidList
Public Member Functions
WObject ()
Constructor.
virtual ~WObject ()
Destructor.
virtual const OClass * getOClass ()
virtual uint8_t typeId ()
Abstrct class.
virtual const char * typeName ()
WCreator * getCreator ()
WReplicator * getReplicator ()
virtual bool isMoving ()
Checks weither object is moving.
virtual void changePosition (float lasting)
Changes the position after a triggered movement.
virtual void changePermanent (float lasting)
Changes the position during a permanent movement.
virtual void updateTime (time_t sec, time_t usec, float *lasting)
Updates remaining times of the movement.
virtual bool updateToNetwork (const Pos &oldpos)
Publishes changes to the network.
virtual bool updatePosToNetwork (const Pos &oldpos, int propxy, int propz, int propaz, int propax, int propay)
Publishes position changes to the network.
virtual bool whenIntersect (WObject *pcur, WObject *pold)
Handles an ingoing collision with another object.
virtual bool whenIntersectOut (WObject *pcur, WObject *pold)
Handles an outgoing collision with another object.
virtual void whenWallsIntersect (WObject *pold, V3 *norm)
Handles collisions with walls.
virtual void render ()
Makes special rendering.
virtual void lighting ()
Makes special lighting.
virtual void quit ()
Makes all thing when leaving the object.
const solidList & solids () const
solidlist address.
uint32_t countOfSolids () const
virtual class Solid * getSolid () const
Returns first solid.
virtual void addSolid (class Solid *solid)
Adds to solidList.
virtual void deleteSolids ()
Deletes solids from solidList.
virtual int interAABB (WObject *o1, WObject *o2)
virtual bool haveAction ()
Checks weither have actions.
virtual uint8_t numberAction ()
Number of actions.
virtual bool runAction (const char *action)
Runs action everwhere if available.
virtual void setType (int type)
Sets object type.
virtual int getType ()
Gets object type.
virtual int getNumber ()
Gets object number.
virtual uint16_t getNum ()
Gets a new object number.
virtual void getPosition (M4 &mpos)
Gives solid's position.
virtual void getRelativeBB (V3 &center, V3 &size)
virtual void getDim (V3 &dim)
virtual void getCenter (V3 &center)
virtual void getAbsoluteBB (V3 &center, V3 &size)
Gets relative or absolute center and size of solid.
virtual uint8_t getFrames ()
Gets number of frames of this solid.
virtual uint8_t getFrame ()
Gets index of current frame of this solid.
virtual void setFrame (uint8_t _frame)
Sets current frame.
virtual bool isValid () const
Checks if valid object type.
virtual bool isPermanent () const
Checks if permanent object.
virtual const char * named () const
Gets names.named.
virtual const char * getInstance () const
Gets names.instance.
virtual const char * urlName () const
Gets names.url.
virtual const char * ownerName () const
Gets names.owner.
virtual const char * worldName () const
Gets names.owner.
virtual bool explicitName () const
Checks wether the object is explicitly named.
virtual void toDelete ()
Delete this object latter.
virtual bool removeFromScene ()
Removes an object.
virtual bool isOwner () const
Returns true if owner.
virtual void setOwner (const char *_owner)
Initialize owner.
virtual void setOwner ()
Initialize local user as owner.
virtual void click (GLint x, GLint y)
Execute an object's click method if it's defined.
virtual void click (V3 norm)
Intercepts a click.
virtual char * tokenize (char *l)
Tokenizes the line <object ...
virtual Parse * parse ()
Gets current parse.
void setWObjectId ()
Sets the WObjectid.
void copyNoid (class Noid _noid)
Copies the NetObjectid in WObjectId.
void setSrcId (uint32_t src_id)
Sets the SrcId.
void setPortId (uint16_t port_id)
Sets the PortId.
void setObjId (uint16_t obj_id)
Sets the ObjId.
uint32_t getSrcId () const
Gets the SrcId.
uint16_t getPortId () const
Gets the PortId.
uint16_t getObjId () const
Gets the ObjId.
virtual void update3D (Pos &pos)
Updates object in the 3D.
virtual void updateAll3D (Pos &pos)
Updates object in the 3D.
virtual void updateCamera (Pos &pos)
Updates camera in the 3D.
virtual void getSurfVecs (Pos &pos, V3 *v, V3 *w, V3 *norm)
Returns two vectors that describe the object's surface and a normal vector to that surface.
virtual void updateBB ()
Updates object's Bounding Box.
virtual void getMaterials (GLfloat *dif, GLfloat *amb, GLfloat *spe, GLfloat *emi, GLint *shi, GLfloat *alpha)
virtual void insertIntoGrid ()
Adds an object into the grid.
virtual void deleteFromGrid ()
Deletes an object from the grid.
virtual void updateGrid (const float *bbminnew, const float *bbmaxnew, const float *bbminold, const float *bbmaxold)
Updates an object in the grid.
virtual void updateGrid (const Pos &oldpos)
virtual void updateGrid (const WObject *pold)
Updates an object into the grid.
virtual void addToList (std::list< WObject * > &olist)
virtual OList * addToList (OList *olist)
Adds an object pointer into a olist.
virtual void addToList ()
Adds an object pointer into a olist.
virtual void addToStill ()
Adds an object pointer into stillList.
virtual void addToMobile ()
Adds an object pointer into mobileList.
virtual void addToInvisible ()
Adds an object pointer into invisibleList.
virtual void addToRender ()
Adds an object pointer into renderList.
virtual void delFromMobile ()
Deletes an object pointer from mobileList.
virtual void clearList ()
Clears an olist.
virtual void clearList (std::list< WObject * > &olist)
Clears an olist.
virtual void addToListOnce (std::list< WObject * > &olist)
virtual OList * addToListOnce (OList *olist)
Adds an object pointer into a list only once time.
virtual void delFromList (std::list< WObject * > &olist)
virtual OList * delFromList (OList *olist)
Deletes an object pointer from a olist.
virtual void delFromList ()
Deletes an object pointer from a olist.
virtual OList * getVicinityList (const WObject *pold)
Returns list of pointers on objects touching cell where is the object.
virtual OList * addListToList (OList *list1, OList *list2)
Concatenation (test of "ispointed") of list pointers on an object.
virtual bool isStill ()
Checks an object exists in the stilllist.
virtual bool isMobile ()
virtual bool isEphemeral ()
Checks an object exists in the mobilelist.
virtual WObject * byWObject (WObject *po)
Gets a WObject from the lists.
virtual void checkVicinity (WObject *pold)
< Gets an object by its num.
virtual void imposedMovement (time_t sec, time_t usec)
Handles an object movement.
virtual void elementaryImposedMovement (float lasting)
Handles an elementary object movement.
virtual void enableImposedMovement ()
Enables movement on an object.
virtual void enablePermanentMovement ()
Enables permanent movement on an object.
virtual void disablePermanentMovement ()
Disables movement on an object.
virtual void enablePermanentMovement (float speed)
Enables permanent movement on an object.
virtual void initImposedMovement (float lasting)
Initializes movement on an object.
virtual float diffTime (time_t sec, time_t usec)
Updates times on an object.
virtual void stopImposedMovement ()
Stops a movement on an object.
virtual void permanentMovement (time_t sec, time_t usec)
Handles a permanent object movement.
virtual void elementaryPermanentMovement (float lasting)
Handles an elementary permanent object movement.
virtual void setLasting (float maxlast)
Sets the max lasting time of an object.
virtual float getLasting () const
Gets the lasting time of an object.
virtual bool testMoving ()
Tests if object is moving.
virtual bool updateLasting (time_t sec, time_t usec, float *lasting)
Updates remaining times of the movement.
virtual void moveUserToObject (float val, float _lttl, float _attl)
Moves the user to the object.
virtual void setObjectName (const char *str)
Sets an object name.
virtual WObject * getObjectByName (const char *str)
Gets an object by its name.
virtual void updateNames ()
Updates names.
virtual void initializeObject (uint8_t mode)
Initializes object.
virtual void initializeMobileObject (float last)
virtual void initializeEphemeralObject (float last)
Initializes mobile object.
virtual void initializeStillObject ()
Initializes still object.
void createPermanentNetObject (uint8_t props, uint16_t oid)
Creates local permanent NetObject.
void createVolatileNetObject (uint8_t props)
Creates local volatile NetObject.
void replicateVolatileNetObject (uint8_t props, class Noid _noid)
Replicate distant volatile NetObject.
virtual void enableBehavior (uint32_t flag)
Enables behavior.
virtual void disableBehavior (uint32_t flag)
Disables behavior.
virtual bool isBehavior (uint32_t flag) const
Checks weither this behavior is on.
virtual bool bbBehavior () const
Checks weither BBox behavior is on.
virtual bool isSeen ()
Checks weither the object is in the sight view of the user.
virtual void setVisible (bool flag)
Sets visible or not the 3D object.
virtual bool isVisible ()
Checks weither the object is visible.
virtual void setFlashy (float *color)
Sets flashy the 3D object.
virtual void setFlashy ()
Sets flashy the 3D object.
virtual void resetFlashy ()
Resets flashy the 3D object.
virtual void setRay (GLint wx, GLint wy)
virtual void resetRay ()
Resets Ray on the 3D object.
virtual void setReflexive (bool flag)
virtual bool isSelectable () const
Checks weither 3D selectable behavior is on.
virtual uint32_t collideBehavior () const
Returns collide behavior.
virtual void setRenderPrior (uint8_t _prior)
Sets render priority.
virtual uint8_t getRenderPrior () const
Gets render priority.
void generalIntersect (WObject *pold, OList *vicinityList)
General intersection of objects.
bool ingoingNeighbor (WObject *pold, WObject *neighbor)
bool outgoingNeighbor (WObject *pold, WObject *neighbor)
Checks ingoing intersection with a neighbor.
void ingoingWalls (WObject *pold)
Checks outgoing intersection with a neighbor.
virtual void copyPosAndBB (Pos &newpos)
Checks ingoing intersection with walls.
virtual void copyPositionAndBB (WObject *o)
Copy object position and Bounding Box.
virtual bool projectPosition (WObject *pcur, WObject *pold)
Projects object position.
virtual int projectPositionOnObstacle (Pos &pcur, Pos &pold, Pos &obstacle)
Projects object position on an obstacle.
virtual void initPosition ()
Init 3D and grid position.
virtual void updatePosition ()
Updating 3D.
virtual void updatePositionAndGrid (Pos &oldpos)
Updating 3D and grid position.
virtual void updatePositionAndGrid (WObject *pold)
Updating 3D and grid position.
virtual void computeNormal (WObject *mobil, V3 *normal)
Computes the normal of an object.
virtual void computeNormal (Pos &mobil, Pos &stil, V3 *normal)
Computes the normal of still object.
virtual void bounceTrajectory (WObject *pold, V3 *norm)
Intersects with wall.
void getProperty (uint8_t prop_id, class Payload *pp)
Gets the local copy property from the payload (pp->data).
void putProperty (uint8_t prop_id, class Payload *pp)
Puts the local copy property in the payload.
virtual void deleteReplica ()
Deletes a replicated object.
virtual struct GuiItem * getGui () const
Gets the GUI handle.
virtual bool isGui () const
Checks the GUI handle.
virtual void resetGui ()
Resets the GUI handle.
virtual void clearObjectBar ()
Clears the ObjectBar in the GUI.
virtual void specialAction (int action, void *data, time_t sec, time_t usec)
Calls methods dedicated to each object.
void getObjectHumanName (char **classname, char **instancename, char **actionnames)
Gives object's class_name & action names.
virtual void getMySqlPosition ()
Checks if position is managed by MySql and get it.
virtual void updateMySqlPosition ()
Checks if position is managed by MySql and update it.
virtual int16_t getMySqlState ()
Gets state from MySql.
virtual void updateMySqlPosZ ()
Checks if posZ is managed by MySql.
virtual void updateMySqlState (int16_t state)
Updates state for MySql.
virtual void flushMySqlPosition ()
Flushes position for MySql.
virtual void quitMySql ()
Quits MySql.
Static Public Member Functions
static int interAABB (V3 center1, V3 size1, V3 center2, V3 size2)
Computes intersection between 2 AABB (Axis Aligned Bounding Box).
static int interAABBVertical (V3 center1, V3 size1, V3 center2, V3 size2)
static int interAABBHorizontal (V3 center1, V3 size1, V3 center2, V3 size2)
static void show (const char *name)
Snaps position (debug).
static WObject * byNum (uint16_t num)
static void moveObject (WObject *po, void *d, time_t s, time_t u)
User moves the object.
static void getObjectNameById (uint8_t type_id, char *name)
Gets a name by its id.
static void resetObjectsNumber ()
Resets object seq.
static uint32_t getObjectsNumber ()
Gets current object sequence number.
Public Attributes
solidList _solids
list of solids.
class NetObject * noh
reserved field for network.
struct GuiItem * guip
reserved field for GUI.
uint8_t type
object type.
uint8_t mode
object world mode.
uint16_t num
object sequence number.
uint32_t behavior
behavior flags.
Names names
names.
Pos pos
position in the space.
Move move
movement specific.
class WObjectId noid
WObject Id.
bool is_in_a_list
true if it is already in an OList.
bool removed
flag removed or not.
int16_t state
current state.
int8_t prior
render priority.
char * geometry
geometry string.
class Solid * solid
solid pointer
char chan [CHAN_LEN]
channel.
class Flare * flare
flare instance
Static Protected Member Functions
static void get_xy (WObject *po, class Payload *pp)
static void get_z (WObject *po, class Payload *pp)
static void get_az (WObject *po, class Payload *pp)
static void get_ay (WObject *po, class Payload *pp)
static void get_ax (WObject *po, class Payload *pp)
static void get_hname (WObject *po, class Payload *pp)
static void put_xy (WObject *po, class Payload *pp)
static void put_z (WObject *po, class Payload *pp)
static void put_az (WObject *po, class Payload *pp)
static void put_ay (WObject *po, class Payload *pp)
static void put_ax (WObject *po, class Payload *pp)
static void put_hname (WObject *po, class Payload *pp)
Protected Attributes
bool objectbar
true if object bar is active.
Detailed Description
WObject Class.
Common class for all the objects.
Definition at line 126 of file wobject.hpp.
Member Typedef Documentation
solidList
typedef std::list<class Solid*> WObject::solidList
Definition at line 128 of file wobject.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
STILL
MOBILE
EPHEMERAL
INVISIBLE
MOBILEINVISIBLE
MODE_MAX
Definition at line 158 of file wobject.hpp.
anonymous enum
anonymous enum
Enumerator
DELETED
NONE
INACTIVE
ACTIVE
PLAYING
TAKEN
DROPPED
MOVED
CARRYING
IN_CART
ENDSTATE
Definition at line 168 of file wobject.hpp.
anonymous enum
anonymous enum
Enumerator
RENDER_LOW
RENDER_NORMAL
RENDER_HIGH
Definition at line 183 of file wobject.hpp.
Constructor & Destructor Documentation
WObject()
WObject::WObject ()
Constructor.
Definition at line 47 of file wobject.cpp.
References new_wobject, newV3(), and NONE.
Referenced by elementaryImposedMovement(), elementaryPermanentMovement(), Carrier::mouseEvent(), and Web::pivot().
~WObject()
WObject::~WObject () virtual
Destructor.
Definition at line 105 of file wobject.cpp.
References COLLIDE_NEVER, and del_wobject.
Member Function Documentation
addListToList()
OList * WObject::addListToList (OList * list1, OList * list2) virtual
Concatenation (test of "ispointed") of list pointers on an object.
Definition at line 1071 of file wobject.cpp.
References addToListOnce(), is_in_a_list, isValid(), OList::next, and OList::pobject.
Referenced by getVicinityList().
addSolid()
void WObject::addSolid (class Solid * solid) virtual
Adds to solidList.
Definition at line 414 of file wobject.cpp.
References Solid::numrel, and Solid::wobject.
Referenced by Parse::parseSolid().
addToInvisible()
void WObject::addToInvisible () virtual
Adds an object pointer into invisibleList.
Definition at line 923 of file wobject.cpp.
References invisibleList.
Referenced by Sun::behavior().
addToList() [1/3]
void WObject::addToList () virtual
Adds an object pointer into a olist.
Reimplemented in Cloth.
Definition at line 884 of file wobject.cpp.
References invisibleList, mobileList, and stillList.
Referenced by Sun::inits(), and Light::Light().
addToList() [2/3]
OList * WObject::addToList (OList * olist) virtual
Adds an object pointer into a olist.
Definition at line 950 of file wobject.cpp.
References OList::next, and OList::pobject.
addToList() [3/3]
virtual void WObject::addToList (std::list< WObject * > & olist) virtual
addToListOnce() [1/2]
OList * WObject::addToListOnce (OList * olist) virtual
Adds an object pointer into a list only once time.
Definition at line 968 of file wobject.cpp.
References OList::next.
addToListOnce() [2/2]
virtual void WObject::addToListOnce (std::list< WObject * > & olist) virtual
Referenced by addListToList(), insertIntoGrid(), and updateGrid().
addToMobile()
void WObject::addToMobile () virtual
Adds an object pointer into mobileList.
Definition at line 913 of file wobject.cpp.
References mobileList.
Referenced by Cart::leaveIntoWorld().
addToRender()
void WObject::addToRender () virtual
Adds an object pointer into renderList.
Definition at line 928 of file wobject.cpp.
addToStill()
void WObject::addToStill () virtual
Adds an object pointer into stillList.
Definition at line 918 of file wobject.cpp.
References stillList.
bbBehavior()
bool WObject::bbBehavior () const virtual
Checks weither BBox behavior is on.
Definition at line 235 of file wobject.cpp.
References NO_BBABLE.
bounceTrajectory()
void WObject::bounceTrajectory (WObject * pold, V3 * norm) virtual
Intersects with wall.
Bounce position, we do not change the position, we only change the deltas.
Definition at line 350 of file col.cpp.
References copyPositionAndBB(), Move::lspeed, move, and V3::v.
Referenced by Plane::whenIntersect(), Ball::whenWallsIntersect(), and Projectile::whenWallsIntersect().
byNum()
WObject * WObject::byNum (uint16_t num) static
Definition at line 1042 of file wobject.cpp.
References mobileList, and stillList.
Referenced by Vicinity::analyseVisual(), Render::getDrawedObjects(), Widgets::getPointedObject(), and Render::getVisiblePosition().
byWObject()
WObject * WObject::byWObject (WObject * po) virtual
Gets a WObject from the lists.
Definition at line 1032 of file wobject.cpp.
References mobileList, and stillList.
changePermanent()
virtual void WObject::changePermanent (float lasting) inline virtual
Changes the position during a permanent movement.
Reimplemented in Wings, Widget, Water, Vnc, Vjc, User, Thunder, Template, Sun, Step, Stars, Snow, Rain, Particle, Movie, Model, Mirage, Mech, Icon, Head, Hairs, Guy, Guide, Flag, Fire, Cloud, Cloth, Clock, Cauldron, Ball, Android, Accessory, Smoke, Smoke, Smoke, and Smoke.
Definition at line 212 of file wobject.hpp.
Referenced by elementaryPermanentMovement().
changePosition()
virtual void WObject::changePosition (float lasting) inline virtual
Changes the position after a triggered movement.
Reimplemented in Web, Vrelet, User, Slider, Sheet, Projectile, Lift, Icon, Guide, Fractal, Firework, Door, Door, Door, Bumper, Bubble, Book, Ball, and Animator.
Definition at line 209 of file wobject.hpp.
Referenced by elementaryImposedMovement().
checkVicinity()
void WObject::checkVicinity (WObject * pold) virtual
< Gets an object by its num.
Checks weither vicinity.
Definition at line 309 of file move.cpp.
References generalIntersect(), getVicinityList(), and OList::remove().
Referenced by elementaryImposedMovement(), elementaryPermanentMovement(), and User::elementaryUserMovement().
clearList() [1/2]
void WObject::clearList () virtual
Clears an olist.
Reimplemented in Step.
Definition at line 904 of file wobject.cpp.
References invisibleList, mobileList, and stillList.
clearList() [2/2]
virtual void WObject::clearList (std::list< WObject * > & olist) virtual
Clears an olist.
clearObjectBar()
void WObject::clearObjectBar () virtual
Clears the ObjectBar in the GUI.
Definition at line 830 of file wobject.cpp.
References Gui::clearInfoBar(), g, and Global::gui.
Referenced by Ball::destroy(), and Gate::quit().
click() [1/2]
void WObject::click (GLint x, GLint y) virtual
Execute an object's click method if it's defined.
By Mathieu Seigneurin
Definition at line 864 of file wobject.cpp.
References Render::clickDirection(), g, and Global::render.
click() [2/2]
virtual void WObject::click (V3 norm) inline virtual
Intercepts a click.
Reimplemented in Vrelet, and Board.
Definition at line 355 of file wobject.hpp.
collideBehavior()
uint32_t WObject::collideBehavior () const virtual
Returns collide behavior.
Definition at line 285 of file wobject.cpp.
References COLLIDE_GHOST, COLLIDE_NEVER, and COLLIDE_ONCE.
Referenced by generalIntersect().
computeNormal() [1/2]
void WObject::computeNormal (Pos & mobil, Pos & stil, V3 * normal) virtual
Computes the normal of still object.
Definition at line 291 of file col.cpp.
References Pos::bbcenter, Pos::bbsize, and V3::v.
computeNormal() [2/2]
void WObject::computeNormal (WObject * mobil, V3 * normal) virtual
Computes the normal of an object.
Returns normal vectors 'normal' of still object.
Definition at line 265 of file col.cpp.
References Pos::bbcenter, Pos::bbsize, pos, and V3::v.
Referenced by projectPositionOnObstacle(), and Plane::whenIntersect().
copyNoid()
void WObject::copyNoid (class Noid _noid)
Copies the NetObjectid in WObjectId.
Definition at line 555 of file wobject.cpp.
References Noid::obj_id, Noid::port_id, and Noid::src_id.
Referenced by Ball::Ball(), Bullet::Bullet(), Dart::Dart(), Icon::Icon(), and User::User().
copyPosAndBB()
void WObject::copyPosAndBB (Pos & newpos) virtual
Checks ingoing intersection with walls.
Saves last position and Bounding Box of an object.
Copy object position and Bounding Box.
Definition at line 39 of file col.cpp.
References pos.
Referenced by imposedMovement(), Man::Man(), permanentMovement(), projectPosition(), User::userMovement(), Ground::whenIntersect(), Plane::whenIntersect(), and Wall::whenIntersect().
copyPositionAndBB()
void WObject::copyPositionAndBB (WObject * o) virtual
Copy object position and Bounding Box.
Saves last position, Bounding Box and type of an object.
Definition at line 45 of file col.cpp.
References behavior, mode, num, pos, and type.
Referenced by bounceTrajectory(), elementaryImposedMovement(), elementaryPermanentMovement(), User::elementaryUserMovement(), ingoingWalls(), Carrier::mouseEvent(), Web::pivot(), Vrelet::processClient(), Animator::whenIntersect(), AnimX3d::whenIntersect(), Ball::whenIntersect(), Cauldron::whenIntersect(), Clip::whenIntersect(), Doc::whenIntersect(), Door::whenIntersect(), Gate::whenIntersect(), Ground::whenIntersect(), Guide::whenIntersect(), Host::whenIntersect(), Icon::whenIntersect(), Lift::whenIntersect(), Mirror::whenIntersect(), Movie::whenIntersect(), Music::whenIntersect(), Projectile::whenIntersect(), Step::whenIntersect(), Thing::whenIntersect(), and User::whenIntersect().
countOfSolids()
uint32_t WObject::countOfSolids () const
Definition at line 363 of file wobject.cpp.
Referenced by Fire::makeSolid(), Firework::makeSolid(), and Fractal::makeSolid().
createPermanentNetObject()
void WObject::createPermanentNetObject (uint8_t props, uint16_t oid)
Creates local permanent NetObject.
Definition at line 563 of file wobject.cpp.
References oid.
Referenced by Animator::Animator(), Bubble::behavior(), Bumper::behavior(), Escalator::behavior(), Gate::behavior(), Head::behavior(), Mirror::behavior(), Slider::behavior(), Stair::behavior(), Thing::behavior(), Travelator::behavior(), Board::Board(), Book::Book(), Button::Button(), Doc::Doc(), Door::Door(), Guide::Guide(), Host::Host(), Accessory::init(), Lift::Lift(), Music::Music(), Plane::Plane(), Sheet::Sheet(), Hat::wear(), and Web::Web().
createVolatileNetObject()
void WObject::createVolatileNetObject (uint8_t props)
Creates local volatile NetObject.
Definition at line 569 of file wobject.cpp.
Referenced by Ball::Ball(), Bullet::Bullet(), Dart::Dart(), Icon::Icon(), and User::inits().
deleteFromGrid()
void WObject::deleteFromGrid () virtual
Deletes an object from the grid.
Deletes an object in the grid.
Definition at line 436 of file col.cpp.
References Pos::bbcenter, Pos::bbsize, World::current(), delFromList(), dim, World::grid, World::gridList, indiceGrid(), pos, and V3::v.
Referenced by Cart::addToCart(), and updateGrid().
deleteReplica()
void WObject::deleteReplica () virtual
Deletes a replicated object.
Definition at line 1220 of file wobject.cpp.
References g, Global::gui, localuser, Gui::removeUser(), USER_TYPE, and warning().
deleteSolids()
void WObject::deleteSolids () virtual
Deletes solids from solidList.
Definition at line 425 of file wobject.cpp.
Referenced by Plane::makeSolid().
delFromList() [1/3]
void WObject::delFromList () virtual
Deletes an object pointer from a olist.
Reimplemented in Cloth.
Definition at line 894 of file wobject.cpp.
References invisibleList, mobileList, and stillList.
Referenced by deleteFromGrid(), and updateGrid().
delFromList() [2/3]
OList * WObject::delFromList (OList * olist) virtual
Deletes an object pointer from a olist.
Definition at line 983 of file wobject.cpp.
References error(), and OList::next.
delFromList() [3/3]
virtual void WObject::delFromList (std::list< WObject * > & olist) virtual
Referenced by Web::pivot().
delFromMobile()
void WObject::delFromMobile () virtual
Deletes an object pointer from mobileList.
Definition at line 932 of file wobject.cpp.
References mobileList.
Referenced by Cart::addToCart().
diffTime()
float WObject::diffTime (time_t sec, time_t usec) virtual
Updates times on an object.
Definition at line 257 of file move.cpp.
References move, Move::sec, and Move::usec.
Referenced by updateLasting(), Bumper::updateTime(), Slider::updateTime(), and Animator::updateTime().
disableBehavior()
void WObject::disableBehavior (uint32_t flag) virtual
Disables behavior.
Definition at line 221 of file wobject.cpp.
References UNVISIBLE.
Referenced by Escalator::build(), Travelator::build(), Icon::carry(), Board::leave(), User::setView(), and Water::whenIntersect().
disablePermanentMovement()
void WObject::disablePermanentMovement () virtual
Disables movement on an object.
Definition at line 295 of file move.cpp.
References move, Move::perm_sec, and Move::perm_usec.
Referenced by Icon::carry(), Icon::Icon(), Icon::pin(), Icon::pull(), Icon::push(), Movie::stop(), Ball::take(), Icon::turn(), Ground::whenIntersect(), and Plane::whenIntersect().
elementaryImposedMovement()
void WObject::elementaryImposedMovement (float lasting) virtual
Handles an elementary object movement.
Definition at line 369 of file move.cpp.
References changePosition(), checkVicinity(), COLLIDE_NEVER, copyPositionAndBB(), isBehavior(), pos, update3D(), updatePosition(), and WObject().
Referenced by imposedMovement().
elementaryPermanentMovement()
void WObject::elementaryPermanentMovement (float lasting) virtual
Handles an elementary permanent object movement.
Definition at line 422 of file move.cpp.
References changePermanent(), checkVicinity(), COLLIDE_NEVER, copyPositionAndBB(), isBehavior(), pos, update3D(), updatePosition(), and WObject().
Referenced by permanentMovement().
enableBehavior()
void WObject::enableBehavior (uint32_t flag) virtual
Enables behavior.
Definition at line 199 of file wobject.cpp.
References COLLIDE_GHOST, COLLIDE_NEVER, COLLIDE_ONCE, and UNVISIBLE.
Referenced by Animator::Animator(), Area::Area(), Ball::Ball(), Accessory::behavior(), Bubble::behavior(), Bumper::behavior(), Cloud::behavior(), Escalator::behavior(), Fire::behavior(), Flag::behavior(), Fractal::behavior(), Gate::behavior(), Guy::behavior(), Head::behavior(), Mirage::behavior(), Mirror::behavior(), Model::behavior(), Movie::behavior(), Particle::behavior(), River::behavior(), Slider::behavior(), Smoke::behavior(), Spiral::behavior(), Stair::behavior(), Sun::behavior(), Template::behavior(), Terrain::behavior(), Text::behavior(), Thing::behavior(), Thunder::behavior(), Travelator::behavior(), Water::behavior(), Widget::behavior(), Android::behaviour(), Board::Board(), Book::Book(), Bullet::Bullet(), Button::Button(), Clip::Clip(), Clock::Clock(), Dart::Dart(), Doc::Doc(), Door::Door(), Board::draw(), Icon::drop(), endMovement(), Ftp::Ftp(), Ground::Ground(), Guide::Guide(), Hairs::Hairs(), Host::Host(), Icon::Icon(), Cart::leaveIntoWorld(), Lift::Lift(), Light::Light(), Mech::Mech(), Mirage::Mirage(), Model::Model(), Music::Music(), Icon::pin(), Plane::Plane(), Icon::pull(), Icon::push(), User::setView(), Sheet::Sheet(), Stars::Stars(), Icon::stick(), Thing::Thing(), Transform::Transform(), Vnc::Vnc(), Wall::Wall(), Walls::Walls(), Wings::wear(), Web::Web(), Water::whenIntersect(), Ball::whenWallsIntersect(), Projectile::whenWallsIntersect(), and Wings::Wings().
enableImposedMovement()
void WObject::enableImposedMovement () virtual
Enables movement on an object.
Definition at line 262 of file move.cpp.
References gettimeofday(), move, Move::sec, and Move::usec.
Referenced by Animator::Animator(), initImposedMovement(), Bumper::whenIntersect(), and Slider::whenIntersect().
enablePermanentMovement() [1/2]
void WObject::enablePermanentMovement () virtual
Enables permanent movement on an object.
Definition at line 287 of file move.cpp.
References gettimeofday(), move, Move::perm_sec, and Move::perm_usec.
Referenced by Ball::Ball(), Cloud::behavior(), Fire::behavior(), Flag::behavior(), Guy::behavior(), Head::behavior(), Mirage::behavior(), Particle::behavior(), Smoke::behavior(), Sun::behavior(), Thunder::behavior(), Android::behaviour(), Escalator::build(), Travelator::build(), Cauldron::Cauldron(), Vnc::connectServer(), Ball::drop(), Icon::drop(), enablePermanentMovement(), Guide::Guide(), Hairs::Hairs(), Accessory::init(), User::inits(), Water::inits(), Clock::initTime(), Mech::Mech(), Movie::play(), Stars::Stars(), and Vjc::Vjc().
enablePermanentMovement() [2/2]
void WObject::enablePermanentMovement (float speed) virtual
Enables permanent movement on an object.
Definition at line 301 of file move.cpp.
References enablePermanentMovement(), Move::lspeed, move, and V3::v.
explicitName()
bool WObject::explicitName () const virtual
Checks wether the object is explicitly named.
Definition at line 347 of file wobject.cpp.
Referenced by Head::delMysql(), Head::getMysql(), Mirage::Mirage(), Head::setMysql(), User::setName(), and Thing::Thing().
flushMySqlPosition()
void WObject::flushMySqlPosition () virtual
Flushes position for MySql.
Flushes position for MySql if it is the case, get position and update it.
Definition at line 755 of file wobject.cpp.
References DYNAMIC, and PERSISTENT.
Referenced by Accessory::quit(), Animator::quit(), Ball::quit(), Board::quit(), Book::quit(), Bumper::quit(), Clip::quit(), Doc::quit(), Dress::quit(), Escalator::quit(), Ftp::quit(), Gate::quit(), Ground::quit(), Guy::quit(), Halo::quit(), Hat::quit(), Head::quit(), Host::quit(), Lift::quit(), Mech::quit(), Mirage::quit(), Mirror::quit(), Model::quit(), Movie::quit(), Music::quit(), Plane::quit(), Slider::quit(), Spiral::quit(), Stair::quit(), Thing::quit(), Travelator::quit(), Web::quit(), and Wings::quit().
generalIntersect()
void WObject::generalIntersect (WObject * pold, OList * vicinityList)
General intersection of objects.
Definition at line 183 of file col.cpp.
References AOI_TYPE, Aoi::aoiEnter(), behavior, COLLIDE_GHOST, COLLIDE_NEVER, COLLIDE_ONCE, collideBehavior(), currentAoi, error(), getInstance(), ingoingNeighbor(), ingoingWalls(), isBehavior(), isValid(), localuser, outgoingNeighbor(), OList::pobject, type, whenIntersect(), and whenIntersectOut().
Referenced by checkVicinity(), Carrier::mouseEvent(), and Vrelet::processClient().
get_ax()
void WObject::get_ax (WObject * po, class Payload * pp) static protected
Definition at line 1168 of file wobject.cpp.
References Pos::ax, Payload::getPayload(), pos, and updatePositionAndGrid().
Referenced by Ball::funcs(), Book::funcs(), Doc::funcs(), Dress::funcs(), Gate::funcs(), Halo::funcs(), Hat::funcs(), Head::funcs(), Host::funcs(), Icon::funcs(), Music::funcs(), Thing::funcs(), Web::funcs(), Wings::funcs(), and User::u_get_ax().
get_ay()
void WObject::get_ay (WObject * po, class Payload * pp) static protected
Definition at line 1161 of file wobject.cpp.
References Pos::ay, Payload::getPayload(), pos, and updatePositionAndGrid().
Referenced by Ball::funcs(), Book::funcs(), Doc::funcs(), Dress::funcs(), Gate::funcs(), Halo::funcs(), Hat::funcs(), Head::funcs(), Host::funcs(), Icon::funcs(), Music::funcs(), Thing::funcs(), Web::funcs(), Wings::funcs(), and User::u_get_ay().
get_az()
void WObject::get_az (WObject * po, class Payload * pp) static protected
Definition at line 1154 of file wobject.cpp.
References Pos::az, Payload::getPayload(), pos, and updatePositionAndGrid().
Referenced by Ball::funcs(), Book::funcs(), Doc::funcs(), Door::funcs(), Dress::funcs(), Gate::funcs(), Halo::funcs(), Hat::funcs(), Head::funcs(), Host::funcs(), Icon::funcs(), Music::funcs(), Plane::funcs(), Sheet::funcs(), Thing::funcs(), Web::funcs(), Wings::funcs(), and User::u_get_az().
get_hname()
void WObject::get_hname (WObject * po, class Payload * pp) static protected
Definition at line 1175 of file wobject.cpp.
References Payload::getPayload(), names, and Names::type.
Referenced by Ball::funcs(), Book::funcs(), Bullet::funcs(), Dart::funcs(), Doc::funcs(), Door::funcs(), Dress::funcs(), Gate::funcs(), Halo::funcs(), Hat::funcs(), Head::funcs(), Host::funcs(), Icon::funcs(), Lift::funcs(), Music::funcs(), Plane::funcs(), Sheet::funcs(), Thing::funcs(), Web::funcs(), and Wings::funcs().
get_xy()
void WObject::get_xy (WObject * po, class Payload * pp) static protected
Definition at line 1140 of file wobject.cpp.
References Payload::getPayload(), pos, updatePositionAndGrid(), Pos::x, and Pos::y.
Referenced by Ball::funcs(), Book::funcs(), Bullet::funcs(), Dart::funcs(), Doc::funcs(), Door::funcs(), Dress::funcs(), Gate::funcs(), Halo::funcs(), Hat::funcs(), Head::funcs(), Host::funcs(), Icon::funcs(), Music::funcs(), Plane::funcs(), Sheet::funcs(), Thing::funcs(), Web::funcs(), Wings::funcs(), and User::u_get_xy().
get_z()
void WObject::get_z (WObject * po, class Payload * pp) static protected
Definition at line 1147 of file wobject.cpp.
References Payload::getPayload(), pos, updatePositionAndGrid(), and Pos::z.
Referenced by Ball::funcs(), Book::funcs(), Doc::funcs(), Door::funcs(), Dress::funcs(), Gate::funcs(), Halo::funcs(), Hat::funcs(), Head::funcs(), Host::funcs(), Icon::funcs(), Lift::funcs(), Music::funcs(), Plane::funcs(), Sheet::funcs(), Thing::funcs(), Web::funcs(), Wings::funcs(), and User::u_get_z().
getAbsoluteBB()
void WObject::getAbsoluteBB (V3 & center, V3 & size) virtual
Gets relative or absolute center and size of solid.
Definition at line 464 of file wobject.cpp.
References size.
getCenter()
void WObject::getCenter (V3 & center) virtual
Definition at line 458 of file wobject.cpp.
getCreator()
WCreator* WObject::getCreator () inline
Definition at line 200 of file wobject.hpp.
References OClass::creator, and getOClass().
getDim()
void WObject::getDim (V3 & dim) virtual
Definition at line 452 of file wobject.cpp.
References dim.
Referenced by Book::approach(), Book::Book(), Vnc::buildScreen(), Widget::buildScreen(), Fire::inits(), Fractal::inits(), Firework::makeSolid(), Plane::makeSolid(), Book::nextSheet(), Web::pivot(), Book::prevSheet(), Sheet::pullNext(), Sheet::pullPrev(), and Sheet::Sheet().
getFrame()
uint8_t WObject::getFrame () virtual
Gets index of current frame of this solid.
Definition at line 477 of file wobject.cpp.
Referenced by Bumper::changePosition().
getFrames()
uint8_t WObject::getFrames () virtual
Gets number of frames of this solid.
Definition at line 470 of file wobject.cpp.
Referenced by Animator::changePosition(), and Bumper::changePosition().
getGui()
struct GuiItem * WObject::getGui () const virtual
Gets the GUI handle.
Definition at line 584 of file wobject.cpp.
Referenced by Gui::removeCart(), Gui::removeUser(), and Gui::updateUser().
getInstance()
const char * WObject::getInstance () const virtual
Gets names.instance.
Definition at line 327 of file wobject.cpp.
Referenced by Gui::addCart(), Cart::addToCart(), Gui::addUser(), Aoi::aoiEnter(), User::checkMysql(), generalIntersect(), Bullet::get_hit(), Dart::get_hit(), User::get_msg(), Render::getVisiblePosition(), Icon::Icon(), World::init(), Cart::leaveIntoWorld(), Navig::mousePressB1orB3(), Solid::parser(), Icon::put_gname(), Icon::quit(), Gui::removeCart(), Cart::removeFromCart(), Gui::removeUser(), Ball::setName(), Mirage::setName(), Thing::setName(), Cloth::setName(), Head::setName(), User::setRtcp(), setUser(), Render::solids(), Vjc::startApp(), Carrier::take(), Gui::updateCart(), Gui::updateUser(), User::User(), Vicinity::Vicinity(), Gate::whenIntersect(), Projectile::whenIntersect(), and User::whenIntersect().
getLasting()
float WObject::getLasting () const virtual
Gets the lasting time of an object.
Definition at line 252 of file move.cpp.
References getMaxLastings(), and type.
Referenced by imposedMovement(), permanentMovement(), and User::userMovement().
getMaterials()
void WObject::getMaterials (GLfloat * dif, GLfloat * amb, GLfloat * spe, GLfloat * emi, GLint * shi, GLfloat * alpha) virtual
Definition at line 440 of file wobject.cpp.
References alpha.
Referenced by Plane::makeSolid().
getMySqlPosition()
void WObject::getMySqlPosition () virtual
Checks if position is managed by MySql and get it.
Checks whether position is managed by MySql if it is, get position.
Definition at line 688 of file wobject.cpp.
getMySqlState()
int16_t WObject::getMySqlState () virtual
Gets state from MySql.
Definition at line 725 of file wobject.cpp.
References DBG_SQL, and trace().
Referenced by Door::Door().
getNum()
uint16_t WObject::getNum () virtual
Gets a new object number.
Definition at line 316 of file wobject.cpp.
References objectNum.
Referenced by Mirage::setName(), and Thing::setName().
getNumber()
virtual int WObject::getNumber () inline virtual
Gets object number.
Definition at line 288 of file wobject.hpp.
References num.
getObjectByName()
WObject * WObject::getObjectByName (const char * str) virtual
Gets an object by its name.
Definition at line 77 of file names.cpp.
References World::current(), DBG_WO, hash_name(), hashtable, hash_elt::name, NAME_HASH_SIZE, OBJNAME_LEN, hash_elt::po, and trace().
Referenced by Button::commut(), and Button::parser().
getObjectHumanName()
void WObject::getObjectHumanName (char ** classname, char ** instancename, char ** actionnames)
Gives object's class_name & action names.
Gives instance or class and method names of an object if it exists called by GUI for infoBar.
Called by GUI.
Definition at line 839 of file wobject.cpp.
References ACTIONNAME_LEN, ACTIONSNUMBER, copyActionName(), DBG_WO, isActionName(), and trace().
getObjectNameById()
void WObject::getObjectNameById (uint8_t type_id, char * name) static
Gets a name by its id.
Definition at line 308 of file wobject.cpp.
References OClass::getOClass(), OClass::type_name, and warning().
getObjectsNumber()
uint32_t WObject::getObjectsNumber () static
Gets current object sequence number.
Definition at line 265 of file wobject.cpp.
References objectNum.
Referenced by Render::solids().
getObjId()
uint16_t WObject::getObjId () const
Gets the ObjId.
Definition at line 540 of file wobject.cpp.
Referenced by VjcMessage::isForObject(), and VjcMessage::putOID().
getOClass()
virtual const OClass* WObject::getOClass () inline virtual
Reimplemented in Wings, Wind, Widget, Web, Waterfall, Water, Walls, Wall, Vrelet, Vnc, Vjc, User, Travelator, Transform, Thunder, Thing, Text, Terrain, Template, Sun, Step, Stars, Stair, Spiral, Snow, Smoke, Smoke, Smoke, Smoke, Slider, Sheet, River, Rain, Plane, Particle, Music, Movie, Model, Mirror, Mirage, Mech, Light, Lift, Icon, Host, Head, Hat, Halo, Hairs, Guy, Guide, Ground, Gate, Gate, Gate, Ftp, Fractal, Fountain, Flag, Firework, Fire, Escalator, Entry, Dress, Door, Door, Door, Doc, Dart, Cloud, Cloth, Clock, Clip, Cauldron, Cart, Carrier, Button, Bumper, Bullet, Bubble, Book, Board, Bgcolor, Ball, Area, Aoi, AnimX3d, Animator, Android, and Accessory.
Definition at line 195 of file wobject.hpp.
Referenced by getCreator(), getReplicator(), typeId(), and typeName().
getPortId()
uint16_t WObject::getPortId () const
Gets the PortId.
Definition at line 530 of file wobject.cpp.
Referenced by VjcMessage::isForObject(), and VjcMessage::putOID().
getPosition()
void WObject::getPosition (M4 & mpos) virtual
Gives solid's position.
Definition at line 435 of file wobject.cpp.
Referenced by Board::render(), Vnc::render(), and Widget::render().
getProperty()
void WObject::getProperty (uint8_t prop_id, class Payload * pp)
Gets the local copy property from the payload (pp->data).
Gets property from Network.
Il faut renvoyer la position de lecture de la suite, (utiliser getPayload et sa valeur de retour). Typically called after a Delta reception.
Definition at line 1202 of file wobject.cpp.
References error(), isGetPropertyFunc(), and runGetPropertyFunc().
getRelativeBB()
void WObject::getRelativeBB (V3 & center, V3 & size) virtual
Definition at line 446 of file wobject.cpp.
References size.
Referenced by Door::Door().
getRenderPrior()
uint8_t WObject::getRenderPrior () const virtual
Gets render priority.
Definition at line 250 of file wobject.cpp.
getReplicator()
WReplicator* WObject::getReplicator () inline
Definition at line 201 of file wobject.hpp.
References getOClass(), and OClass::replicator.
getSolid()
Solid * WObject::getSolid () const virtual
Returns first solid.
Definition at line 369 of file wobject.cpp.
Referenced by Vicinity::analyseVisual(), Solid::displayMirroredScene(), User::get_ray(), and User::setRayDirection().
getSrcId()
uint32_t WObject::getSrcId () const
Gets the SrcId.
Definition at line 520 of file wobject.cpp.
Referenced by VjcMessage::isForObject(), and VjcMessage::putOID().
getSurfVecs()
void WObject::getSurfVecs (Pos & pos, V3 * v, V3 * w, V3 * norm) virtual
Returns two vectors that describe the object's surface and a normal vector to that surface.
Definition at line 81 of file vr2gl.cpp.
References Pos::ax, Pos::az, MulM4(), MulM4V3(), newV3(), pos, RotateM4(), UX, and UZ.
Referenced by Board::click().
getType()
virtual int WObject::getType () inline virtual
Gets object type.
Definition at line 285 of file wobject.hpp.
References type.
getVicinityList()
OList * WObject::getVicinityList (const WObject * pold) virtual
Returns list of pointers on objects touching cell where is the object.
retourne la liste des pointeurs sur les objets touchants la case des grilles intersectees par la BB englobante des 2 objets
Definition at line 543 of file col.cpp.
References addListToList(), Pos::bbcenter, Pos::bbsize, OList::clearIspointedFlag(), World::current(), World::gridList, indiceGrid(), MAX, MIN, obj, pos, and V3::v.
Referenced by checkVicinity(), Carrier::mouseEvent(), Vrelet::processClient(), and Vicinity::show().
haveAction()
bool WObject::haveAction () virtual
Checks weither have actions.
Definition at line 790 of file wobject.cpp.
References isAction().
Referenced by Solid::parser().
imposedMovement()
void WObject::imposedMovement (time_t sec, time_t usec) virtual
Handles an object movement.
Definition at line 385 of file move.cpp.
References copyPosAndBB(), World::current(), elementaryImposedMovement(), error(), getLasting(), isBehavior(), isMoving(), NetObject::isResponsible(), isValid(), MIN_LASTING, NO_ELEMENTARY_MOVE, noh, pos, type, updatePositionAndGrid(), updateTime(), and updateToNetwork().
ingoingNeighbor()
bool WObject::ingoingNeighbor (WObject * pold, WObject * neighbor)
Definition at line 146 of file col.cpp.
References Pos::ax, Pos::az, Pos::bbcenter, Pos::bbsize, interAABB(), NO_INTER, pos, and RAD2DEG.
Referenced by generalIntersect().
ingoingWalls()
void WObject::ingoingWalls (WObject * pold)
Checks outgoing intersection with a neighbor.
Definition at line 116 of file col.cpp.
References Pos::bbcenter, Pos::bbsize, copyPositionAndBB(), pos, updatePositionAndGrid(), V3::v, Walls::whenIntersect(), Pos::x, and Pos::y.
Referenced by generalIntersect().
initializeEphemeralObject()
void WObject::initializeEphemeralObject (float last) virtual
Initializes mobile object.
Definition at line 187 of file wobject.cpp.
Referenced by Thunder::behavior().
initializeMobileObject()
void WObject::initializeMobileObject (float last) virtual
Definition at line 180 of file wobject.cpp.
Referenced by Animator::Animator(), AnimX3d::AnimX3d(), Aoi::aoiEnter(), Ball::Ball(), Bubble::behavior(), Bumper::behavior(), Cloud::behavior(), Escalator::behavior(), Fire::behavior(), Flag::behavior(), Fractal::behavior(), Gate::behavior(), Guy::behavior(), Head::behavior(), Mirage::behavior(), Mirror::behavior(), Model::behavior(), Particle::behavior(), Slider::behavior(), Smoke::behavior(), Stair::behavior(), Sun::behavior(), Template::behavior(), Thing::behavior(), Thunder::behavior(), Travelator::behavior(), Widget::behavior(), Android::behaviour(), Board::Board(), Book::Book(), Bullet::Bullet(), Button::Button(), Cauldron::Cauldron(), Clip::Clip(), Clock::Clock(), Dart::Dart(), Doc::Doc(), Door::Door(), Ftp::Ftp(), Ground::Ground(), Guide::Guide(), Hairs::Hairs(), Host::Host(), Icon::Icon(), Accessory::init(), Movie::init(), User::inits(), Water::inits(), Lift::Lift(), Mech::Mech(), Music::Music(), Plane::Plane(), Sheet::Sheet(), Stars::Stars(), User::User(), Vnc::Vnc(), Wall::Wall(), and Web::Web().
initializeObject()
void WObject::initializeObject (uint8_t mode) virtual
Initializes object.
Definition at line 124 of file wobject.cpp.
References COLLIDE_NEVER, error(), NO_BBABLE, NO_ELEMENTARY_MOVE, objectNum, PERSISTENT, SPECIFIC_RENDER, and UNSELECTABLE.
Referenced by Area::Area(), Bgcolor::Bgcolor(), Entry::Entry(), Light::Light(), Transform::Transform(), Vjc::Vjc(), and Wind::Wind().
initializeStillObject()
void WObject::initializeStillObject () virtual
Initializes still object.
Definition at line 194 of file wobject.cpp.
Referenced by River::behavior(), Spiral::behavior(), Terrain::behavior(), Text::behavior(), Ground::Ground(), and Walls::Walls().
initImposedMovement()
void WObject::initImposedMovement (float lasting) virtual
Initializes movement on an object.
Definition at line 270 of file move.cpp.
References enableImposedMovement(), move, Move::next, Move::ttl, and Move::without_col.
Referenced by Book::approach(), Bubble::behavior(), Bullet::Bullet(), Lift::call(), Icon::carry(), Door::close(), Dart::Dart(), Lift::down(), Ball::drop(), Icon::drop(), Firework::Firework(), Fractal::Fractal(), gotoXYZ(), Icon::Icon(), Icon::leave(), moveUserToObject(), Door::open(), Icon::pin(), Web::pivot(), Ball::pull(), Icon::pull(), Sheet::pullNext(), Sheet::pullPrev(), Ball::push(), Icon::push(), Sheet::pushNext(), Sheet::pushPrev(), Ball::shoot(), Ball::take(), Carrier::take(), Ball::turn(), Icon::turn(), Sheet::turnNext(), Sheet::turnPrev(), Ball::up(), Lift::up(), Ball::whenIntersect(), and Thing::whenIntersect().
initPosition()
void WObject::initPosition () virtual
Init 3D and grid position.
Definition at line 647 of file wobject.cpp.
insertIntoGrid()
void WObject::insertIntoGrid () virtual
Adds an object into the grid.
Adds an object in the grid.
Definition at line 412 of file col.cpp.
References addToListOnce(), Pos::bbcenter, Pos::bbsize, World::current(), World::grid, World::gridList, indiceGrid(), pos, and V3::v.
interAABB() [1/2]
int WObject::interAABB (V3 center1, V3 size1, V3 center2, V3 size2) static
Computes intersection between 2 AABB (Axis Aligned Bounding Box).
Definition at line 63 of file col.cpp.
References ABSF, IN1, IN2, INTERSECT, NO_INTER, and V3::v.
interAABB() [2/2]
int WObject::interAABB (WObject * o1, WObject * o2) virtual
Definition at line 57 of file col.cpp.
References Pos::bbcenter, Pos::bbsize, and pos.
Referenced by Slider::changePosition(), ingoingNeighbor(), and outgoingNeighbor().
interAABBHorizontal()
int WObject::interAABBHorizontal (V3 center1, V3 size1, V3 center2, V3 size2) static
Definition at line 100 of file col.cpp.
References ABSF, IN1, IN2, INTERSECT, NO_INTER, and V3::v.
interAABBVertical()
int WObject::interAABBVertical (V3 center1, V3 size1, V3 center2, V3 size2) static
Definition at line 88 of file col.cpp.
References ABSF, IN1, IN2, INTERSECT, NO_INTER, and V3::v.
isBehavior()
bool WObject::isBehavior (uint32_t flag) const virtual
Checks weither this behavior is on.
Definition at line 230 of file wobject.cpp.
Referenced by elementaryImposedMovement(), elementaryPermanentMovement(), generalIntersect(), imposedMovement(), Carrier::mouseEvent(), permanentMovement(), and User::whenIntersect().
isEphemeral()
bool WObject::isEphemeral () virtual
Checks an object exists in the mobilelist.
Definition at line 1024 of file wobject.cpp.
References mobileList.
isGui()
bool WObject::isGui () const virtual
Checks the GUI handle.
Definition at line 589 of file wobject.cpp.
Referenced by Gui::removeCart(), Gui::removeUser(), and Gui::updateUser().
isMobile()
bool WObject::isMobile () virtual
Definition at line 1017 of file wobject.cpp.
References mobileList.
isMoving()
virtual bool WObject::isMoving () inline virtual
Checks weither object is moving.
Reimplemented in Vrelet, Slider, Model, Icon, Bumper, Ball, and Animator.
Definition at line 206 of file wobject.hpp.
References testMoving().
Referenced by imposedMovement().
isOwner()
bool WObject::isOwner () const virtual
Returns true if owner.
Definition at line 290 of file wobject.cpp.
References Names::instance, localuser, and names.
isPermanent()
bool WObject::isPermanent () const virtual
Checks if permanent object.
Definition at line 275 of file wobject.cpp.
Referenced by Cart::addToCart(), and Cart::leaveIntoWorld().
isSeen()
bool WObject::isSeen () virtual
Checks weither the object is in the sight view of the user.
Definition at line 280 of file wobject.cpp.
References g, Render::getVisiblePosition(), Global::render, and V3::v.
isSelectable()
bool WObject::isSelectable () const virtual
Checks weither 3D selectable behavior is on.
Definition at line 240 of file wobject.cpp.
References UNSELECTABLE.
Referenced by Render::setzname().
isStill()
bool WObject::isStill () virtual
Checks an object exists in the stilllist.
Definition at line 1010 of file wobject.cpp.
References stillList.
isValid()
bool WObject::isValid () const virtual
Checks if valid object type.
Definition at line 255 of file wobject.cpp.
References OClass::isValidType().
Referenced by addListToList(), World::compute(), Solid::displayList(), generalIntersect(), imposedMovement(), Navig::mouseDragCB(), Navig::mouseMoveCB(), Navig::mousePressB1orB3(), Navig::mousePressB2(), Solid::object(), permanentMovement(), Render::setzname(), and User::userMovement().
isVisible()
bool WObject::isVisible () virtual
Checks weither the object is visible.
Definition at line 391 of file wobject.cpp.
Referenced by Widgets::getPointedObject().
lighting()
virtual void WObject::lighting () inline virtual
Makes special lighting.
Reimplemented in Sun, and Light.
Definition at line 236 of file wobject.hpp.
moveObject()
void WObject::moveObject (WObject * po, void * d, time_t s, time_t u) static
User moves the object.
Definition at line 676 of file wobject.cpp.
References User::carrier, localuser, and Carrier::take().
Referenced by Animator::funcs(), Board::funcs(), Book::funcs(), Clip::funcs(), Doc::funcs(), Ftp::funcs(), Gate::funcs(), Ground::funcs(), Guy::funcs(), Host::funcs(), Icon::funcs(), Mech::funcs(), Mirage::funcs(), Model::funcs(), Movie::funcs(), Music::funcs(), Plane::funcs(), Thing::funcs(), Wall::funcs(), and Web::funcs().
moveUserToObject()
void WObject::moveUserToObject (float val, float _lttl, float _attl) virtual
Moves the user to the object.
Definition at line 480 of file move.cpp.
References Move::aspeed, Pos::ay, Pos::az, Pos::bbsize, clearV3(), Cos(), d, deltaAngle(), initImposedMovement(), localuser, User::LSPEED, Move::lspeed, MAX, move, Move::next, pos, RATIO_GOTO, Sin(), Move::ttl, V3::v, Move::without_col, Pos::x, Pos::y, and Pos::z.
Referenced by gotoBehind(), and gotoFront().
named()
const char * WObject::named () const virtual
Gets names.named.
Definition at line 322 of file wobject.cpp.
Referenced by World::compute(), Icon::get_gname(), User::get_username(), Cart::leaveIntoWorld(), and User::put_username().
numberAction()
uint8_t WObject::numberAction () virtual
Number of actions.
Definition at line 782 of file wobject.cpp.
References isAction().
outgoingNeighbor()
bool WObject::outgoingNeighbor (WObject * pold, WObject * neighbor)
Checks ingoing intersection with a neighbor.
Definition at line 168 of file col.cpp.
References Pos::bbcenter, Pos::bbsize, interAABB(), NO_INTER, and pos.
Referenced by generalIntersect().
ownerName()
const char * WObject::ownerName () const virtual
Gets names.owner.
Definition at line 337 of file wobject.cpp.
Referenced by Cart::addToCart(), and Icon::Icon().
parse()
Parse * WObject::parse () virtual
Gets current parse.
Definition at line 873 of file wobject.cpp.
References Parse::getParse().
Referenced by AnimX3d::AnimX3d(), Ball::Ball(), Gate::Gate(), Solid::getFramesNumber(), Ground::Ground(), Icon::Icon(), Body::loadBodyParts(), Android::makeSolid(), Ball::makeSolid(), Bubble::makeSolid(), Bullet::makeSolid(), Cloud::makeSolid(), Dart::makeSolid(), Dress::makeSolid(), Fire::makeSolid(), Firework::makeSolid(), Fractal::makeSolid(), Guy::makeSolid(), Halo::makeSolid(), Hat::makeSolid(), Head::makeSolid(), Icon::makeSolid(), Mech::makeSolid(), Model::makeSolid(), Plane::makeSolid(), Sun::makeSolid(), Text::makeSolid(), User::makeSolid(), Wings::makeSolid(), Mirage::Mirage(), Solid::parseFrame(), Solid::parser(), Accessory::parser(), Android::parser(), Animator::parser(), AnimX3d::parser(), Area::parser(), Ball::parser(), Bgcolor::parser(), Board::parser(), Book::parser(), Bumper::parser(), Button::parser(), Cauldron::parser(), Clip::parser(), Clock::parser(), Cloud::parser(), Doc::parser(), Door::parser(), Dress::parser(), Entry::parser(), Escalator::parser(), Fire::parser(), Firework::parser(), Flag::parser(), Fountain::parser(), Fractal::parser(), Ftp::parser(), Gate::parser(), Ground::parser(), Guide::parser(), Guy::parser(), Hairs::parser(), Halo::parser(), Hat::parser(), Head::parser(), Host::parser(), Icon::parser(), Lift::parser(), Light::parser(), Mech::parser(), Mirage::parser(), Mirror::parser(), Model::parser(), Movie::parser(), Music::parser(), Particle::parser(), Plane::parser(), Rain::parser(), River::parser(), Sheet::parser(), Slider::parser(), Smoke::parser(), Snow::parser(), Spiral::parser(), Stair::parser(), Stars::parser(), Sun::parser(), Template::parser(), Terrain::parser(), Text::parser(), Thing::parser(), Thunder::parser(), Travelator::parser(), Vjc::parser(), Vnc::parser(), Wall::parser(), Walls::parser(), Water::parser(), Waterfall::parser(), Web::parser(), Widget::parser(), Wind::parser(), Wings::parser(), Solid::parseShape(), Solid::solidParser(), Solid::statueParser(), Thing::Thing(), tokenize(), Transform::Transform(), User::User(), and Wall::Wall().
permanentMovement()
void WObject::permanentMovement (time_t sec, time_t usec) virtual
Handles a permanent object movement.
Definition at line 438 of file move.cpp.
References copyPosAndBB(), World::current(), elementaryPermanentMovement(), error(), getLasting(), isBehavior(), NetObject::isResponsible(), isValid(), localuser, MIN, MIN_LASTING, MIN_MOVES, move, NO_ELEMENTARY_MOVE, noh, Move::perm_sec, Move::perm_usec, pos, type, updateCamera(), updatePositionAndGrid(), and updateToNetwork().
projectPosition()
bool WObject::projectPosition (WObject * pcur, WObject * pold) virtual
Projects object position.
Project position on the obstacle.
Definition at line 339 of file col.cpp.
References copyPosAndBB(), pos, projectPositionOnObstacle(), and updatePositionAndGrid().
Referenced by Board::whenIntersect(), Book::whenIntersect(), Bumper::whenIntersect(), Door::whenIntersect(), Gate::whenIntersect(), Icon::whenIntersect(), Mirror::whenIntersect(), Plane::whenIntersect(), Sheet::whenIntersect(), Wall::whenIntersect(), and Web::whenIntersect().
projectPositionOnObstacle()
int WObject::projectPositionOnObstacle (Pos & pcur, Pos & pold, Pos & obstacle) virtual
Projects object position on an obstacle.
Definition at line 314 of file col.cpp.
References ABSF, computeNormal(), V3::v, Pos::x, Pos::y, and Pos::z.
Referenced by projectPosition().
put_ax()
void WObject::put_ax (WObject * po, class Payload * pp) static protected
Definition at line 1195 of file wobject.cpp.
References Pos::ax, pos, and Payload::putPayload().
Referenced by Ball::funcs(), Book::funcs(), Doc::funcs(), Dress::funcs(), Gate::funcs(), Halo::funcs(), Hat::funcs(), Head::funcs(), Host::funcs(), Icon::funcs(), Music::funcs(), Thing::funcs(), User::funcs(), Web::funcs(), and Wings::funcs().
put_ay()
void WObject::put_ay (WObject * po, class Payload * pp) static protected
Definition at line 1192 of file wobject.cpp.
References Pos::ay, pos, and Payload::putPayload().
Referenced by Ball::funcs(), Book::funcs(), Doc::funcs(), Dress::funcs(), Gate::funcs(), Halo::funcs(), Hat::funcs(), Head::funcs(), Host::funcs(), Icon::funcs(), Music::funcs(), Thing::funcs(), User::funcs(), Web::funcs(), and Wings::funcs().
put_az()
void WObject::put_az (WObject * po, class Payload * pp) static protected
Definition at line 1189 of file wobject.cpp.
References Pos::az, pos, and Payload::putPayload().
Referenced by Ball::funcs(), Book::funcs(), Doc::funcs(), Door::funcs(), Dress::funcs(), Gate::funcs(), Halo::funcs(), Hat::funcs(), Head::funcs(), Host::funcs(), Icon::funcs(), Music::funcs(), Plane::funcs(), Sheet::funcs(), Thing::funcs(), User::funcs(), Web::funcs(), and Wings::funcs().
put_hname()
void WObject::put_hname (WObject * po, class Payload * pp) static protected
Definition at line 1198 of file wobject.cpp.
References names, Payload::putPayload(), and Names::type.
Referenced by Ball::funcs(), Book::funcs(), Bullet::funcs(), Dart::funcs(), Doc::funcs(), Door::funcs(), Dress::funcs(), Gate::funcs(), Halo::funcs(), Hat::funcs(), Head::funcs(), Host::funcs(), Icon::funcs(), Lift::funcs(), Music::funcs(), Plane::funcs(), Sheet::funcs(), Thing::funcs(), Web::funcs(), and Wings::funcs().
put_xy()
void WObject::put_xy (WObject * po, class Payload * pp) static protected
Definition at line 1183 of file wobject.cpp.
References pos, Payload::putPayload(), Pos::x, and Pos::y.
Referenced by Ball::funcs(), Book::funcs(), Bullet::funcs(), Dart::funcs(), Doc::funcs(), Door::funcs(), Dress::funcs(), Gate::funcs(), Halo::funcs(), Hat::funcs(), Head::funcs(), Host::funcs(), Icon::funcs(), Music::funcs(), Plane::funcs(), Sheet::funcs(), Thing::funcs(), User::funcs(), Web::funcs(), and Wings::funcs().
put_z()
void WObject::put_z (WObject * po, class Payload * pp) static protected
Definition at line 1186 of file wobject.cpp.
References pos, Payload::putPayload(), and Pos::z.
Referenced by Ball::funcs(), Book::funcs(), Doc::funcs(), Door::funcs(), Dress::funcs(), Gate::funcs(), Halo::funcs(), Hat::funcs(), Head::funcs(), Host::funcs(), Icon::funcs(), Lift::funcs(), Music::funcs(), Plane::funcs(), Sheet::funcs(), Thing::funcs(), User::funcs(), Web::funcs(), and Wings::funcs().
putProperty()
void WObject::putProperty (uint8_t prop_id, class Payload * pp)
Puts the local copy property in the payload.
Puts property to Network.
Il faut ecrire pp->data et renvoyer la longueur ecrite Typically called before a Delta emission.
Definition at line 1212 of file wobject.cpp.
References error(), isPutPropertyFunc(), and runPutPropertyFunc().
quit()
virtual void WObject::quit () inline virtual
Makes all thing when leaving the object.
Reimplemented in Wings, Wind, Widget, Web, Walls, Vrelet, Vnc, Vjc, Travelator, Transform, Thunder, Thing, Text, Terrain, Template, Sun, Step, Stars, Stair, Spiral, Slider, Sheet, River, Plane, Particle, Music, Movie, Model, Mirror, Mirage, Mech, Light, Lift, Icon, Host, Head, Hat, Halo, Hairs, Guy, Guide, Ground, Gate, Gate, Gate, Ftp, Fire, Escalator, Entry, Dress, Door, Door, Door, Doc, Cloud, Cloth, Clock, Clip, Cart, Button, Bumper, Bubble, Book, Board, Bgcolor, Ball, Animator, Android, and Accessory.
Definition at line 239 of file wobject.hpp.
quitMySql()
void WObject::quitMySql () virtual
Quits MySql.
Definition at line 770 of file wobject.cpp.
Referenced by Cart::quit(), and Door::quit().
removeFromScene()
bool WObject::removeFromScene () virtual
Removes an object.
Definition at line 599 of file wobject.cpp.
References notice().
Referenced by Icon::destroy(), Mirage::destroy(), Thing::destroy(), Wall::destroy(), and Step::destroy_cb().
render()
virtual void WObject::render () inline virtual
Makes special rendering.
Reimplemented in Wings, Widget, Water, Walls, Vrelet, Vnc, Transform, Thunder, Text, Terrain, Template, Sun, Stars, Smoke, Smoke, River, Particle, Model, Mech, Head, Hairs, Guy, Guide, Fractal, Flag, Firework, Fire, Cloud, Board, AnimX3d, and Android.
Definition at line 233 of file wobject.hpp.
Referenced by User::thirdPersonView_Far(), User::thirdPersonView_Near(), User::thirdPersonView_RotD(), and User::thirdPersonView_RotU().
replicateVolatileNetObject()
void WObject::replicateVolatileNetObject (uint8_t props, class Noid _noid)
Replicate distant volatile NetObject.
Definition at line 575 of file wobject.cpp.
Referenced by Ball::Ball(), Bullet::Bullet(), Dart::Dart(), Icon::Icon(), and User::User().
resetFlashy()
void WObject::resetFlashy () virtual
Resets flashy the 3D object.
Definition at line 506 of file wobject.cpp.
Referenced by Icon::carry(), AnimX3d::funcs(), Cart::leaveIntoWorld(), Navig::mouseDragCB(), Navig::mouseMoveCB(), Navig::mousePressB1orB3(), Navig::mousePressB2(), and Icon::pull().
resetGui()
void WObject::resetGui () virtual
Resets the GUI handle.
Definition at line 594 of file wobject.cpp.
Referenced by Gui::removeCart(), and Gui::removeUser().
resetObjectsNumber()
void WObject::resetObjectsNumber () static
Resets object seq.
number.
Definition at line 270 of file wobject.cpp.
References objectNum.
Referenced by World::quit().
resetRay()
void WObject::resetRay () virtual
Resets Ray on the 3D object.
Definition at line 402 of file wobject.cpp.
Referenced by Navig::mouseDragCB(), Navig::mouseMoveCB(), Navig::mousePressB1orB3(), and Navig::mouseReleaseCB().
runAction()
bool WObject::runAction (const char * action) virtual
Runs action everwhere if available.
Definition at line 818 of file wobject.cpp.
References ACTIONSNUMBER, doAction(), and getActionName().
setFlashy() [1/2]
void WObject::setFlashy () virtual
Sets flashy the 3D object.
Definition at line 493 of file wobject.cpp.
Referenced by AnimX3d::funcs().
setFlashy() [2/2]
void WObject::setFlashy (float * color) virtual
Sets flashy the 3D object.
Definition at line 488 of file wobject.cpp.
References color.
Referenced by Icon::stick().
setFrame()
void WObject::setFrame (uint8_t _frame) virtual
Sets current frame.
Definition at line 483 of file wobject.cpp.
Referenced by Animator::changePosition(), Bumper::changePosition(), and Animator::get_frame().
setLasting()
void WObject::setLasting (float maxlast) virtual
Sets the max lasting time of an object.
Definition at line 247 of file move.cpp.
References setMaxLastings(), and type.
Referenced by Ground::whenIntersect(), and Plane::whenIntersect().
setObjectName()
void WObject::setObjectName (const char * str) virtual
Sets an object name.
Definition at line 58 of file names.cpp.
References World::current(), hash_name(), hashtable, hash_elt::name, NAME_DELETED, NAME_HASH_SIZE, World::namecnt, OBJNAME_LEN, and hash_elt::po.
setObjId()
void WObject::setObjId (uint16_t obj_id)
Sets the ObjId.
Definition at line 535 of file wobject.cpp.
setOwner() [1/2]
void WObject::setOwner () virtual
Initialize local user as owner.
Definition at line 301 of file wobject.cpp.
References Names::instance, localuser, and names.
Referenced by Dress::Dress(), Halo::Halo(), Hat::Hat(), Head::Head(), Icon::Icon(), Mirage::Mirage(), Model::Model(), Thing::Thing(), Wall::Wall(), Dress::wear(), Halo::wear(), Hat::wear(), Wings::wear(), and Wings::Wings().
setOwner() [2/2]
void WObject::setOwner (const char * _owner) virtual
Initialize owner.
Definition at line 296 of file wobject.cpp.
Referenced by Cart::leaveIntoWorld().
setPortId()
void WObject::setPortId (uint16_t port_id)
Sets the PortId.
Definition at line 525 of file wobject.cpp.
setRay()
void WObject::setRay (GLint wx, GLint wy) virtual
Definition at line 397 of file wobject.cpp.
setReflexive()
void WObject::setReflexive (bool flag) virtual
Definition at line 407 of file wobject.cpp.
Referenced by Mirror::behavior(), Mirror::mirrorOff(), and Mirror::mirrorOn().
setRenderPrior()
void WObject::setRenderPrior (uint8_t _prior) virtual
Sets render priority.
Definition at line 245 of file wobject.cpp.
Referenced by Animator::Animator(), AnimX3d::AnimX3d(), Ball::Ball(), Accessory::behavior(), Bubble::behavior(), Bumper::behavior(), Cloud::behavior(), Escalator::behavior(), Fire::behavior(), Flag::behavior(), Fractal::behavior(), Gate::behavior(), Guy::behavior(), Head::behavior(), Mirage::behavior(), Movie::behavior(), Particle::behavior(), River::behavior(), Slider::behavior(), Smoke::behavior(), Spiral::behavior(), Stair::behavior(), Template::behavior(), Terrain::behavior(), Text::behavior(), Thing::behavior(), Thunder::behavior(), Travelator::behavior(), Widget::behavior(), Android::behaviour(), Board::Board(), Book::Book(), Bullet::Bullet(), Button::Button(), Cauldron::Cauldron(), Clip::Clip(), Clock::Clock(), Dart::Dart(), Doc::Doc(), Door::Door(), Ftp::Ftp(), Ground::Ground(), Guide::Guide(), Hairs::Hairs(), Host::Host(), Icon::Icon(), User::inits(), Water::inits(), Lift::Lift(), Mech::Mech(), Model::Model(), Music::Music(), Plane::Plane(), Rain::Rain(), Sheet::Sheet(), Stars::Stars(), Animator::stop(), Vnc::Vnc(), Wall::Wall(), Walls::Walls(), Web::Web(), and Bumper::whenIntersect().
setSrcId()
void WObject::setSrcId (uint32_t src_id)
Sets the SrcId.
Definition at line 515 of file wobject.cpp.
setType()
void WObject::setType (int type) virtual
Sets object type.
Definition at line 260 of file wobject.cpp.
Referenced by Ball::Ball(), Bullet::Bullet(), Dart::Dart(), and Icon::Icon().
setVisible()
void WObject::setVisible (bool flag) virtual
Sets visible or not the 3D object.
Definition at line 386 of file wobject.cpp.
Referenced by Cart::addToCart(), and Cart::leaveIntoWorld().
setWObjectId()
void WObject::setWObjectId ()
Sets the WObjectid.
Assigns a unique identifier to each Vreng object whether if be a networked object or not.
Definition at line 546 of file wobject.cpp.
References NetObject::getMyObjId(), NetObject::getMyPortId(), NetObject::getMySsrcId(), and NetObject::setMyObjId().
show()
void WObject::show (const char * name) static
Snaps position (debug).
Definition at line 1089 of file wobject.cpp.
References DBG_FORCE, stillList, and trace().
solids()
const WObject::solidList & WObject::solids () const
solidlist address.
Definition at line 358 of file wobject.cpp.
specialAction()
void WObject::specialAction (int action, void * data, time_t sec, time_t usec) virtual
Calls methods dedicated to each object.
Calls special methods for each object called by GUI.
Called by GUI.
Reimplemented in User.
Definition at line 813 of file wobject.cpp.
References doAction(), and isAction().
Referenced by objectActionCB().
stopImposedMovement()
void WObject::stopImposedMovement () virtual
Stops a movement on an object.
Definition at line 278 of file move.cpp.
References move, Move::next, Move::sec, Move::ttl, Move::usec, and Move::without_col.
Referenced by Web::changePosition(), and updateLasting().
testMoving()
bool WObject::testMoving () virtual
Tests if object is moving.
Definition at line 86 of file move.cpp.
References move, and Move::ttl.
Referenced by Ball::isMoving(), Icon::isMoving(), Model::isMoving(), and isMoving().
toDelete()
void WObject::toDelete () virtual
Delete this object latter.
Definition at line 797 of file wobject.cpp.
References deleteList.
Referenced by Ball::destroy(), Hat::destroy(), Sheet::destroy(), User::get_msg(), Cart::removeFromCart(), Bubble::updateTime(), Projectile::updateTime(), User::userWriting(), Gate::whenIntersect(), Projectile::whenIntersect(), User::whenIntersect(), and Wall::whenIntersect().
tokenize()
char * WObject::tokenize (char * l) virtual
Tokenizes the line <object ...
>.
Definition at line 513 of file parse.cpp.
References geometry, parse(), SEP, Parse::TAG_LEN, and Parse::tagobj.
Referenced by Accessory::parser(), Android::parser(), Animator::parser(), AnimX3d::parser(), Area::parser(), Ball::parser(), Bgcolor::parser(), Board::parser(), Book::parser(), Bumper::parser(), Button::parser(), Cart::parser(), Cauldron::parser(), Clip::parser(), Clock::parser(), Cloud::parser(), Doc::parser(), Door::parser(), Dress::parser(), Entry::parser(), Escalator::parser(), Fire::parser(), Firework::parser(), Flag::parser(), Fountain::parser(), Fractal::parser(), Ftp::parser(), Gate::parser(), Ground::parser(), Guide::parser(), Guy::parser(), Hairs::parser(), Halo::parser(), Hat::parser(), Head::parser(), Host::parser(), Icon::parser(), Lift::parser(), Light::parser(), Mech::parser(), Mirage::parser(), Mirror::parser(), Model::parser(), Movie::parser(), Music::parser(), Particle::parser(), Plane::parser(), Rain::parser(), River::parser(), Sheet::parser(), Slider::parser(), Smoke::parser(), Snow::parser(), Spiral::parser(), Stair::parser(), Stars::parser(), Sun::parser(), Template::parser(), Terrain::parser(), Text::parser(), Thing::parser(), Thunder::parser(), Travelator::parser(), Vjc::parser(), Vnc::parser(), Wall::parser(), Walls::parser(), Water::parser(), Waterfall::parser(), Web::parser(), Widget::parser(), Wind::parser(), Wings::parser(), and Transform::Transform().
typeId()
virtual uint8_t WObject::typeId () inline virtual
Abstrct class.
Definition at line 198 of file wobject.hpp.
References getOClass(), and OClass::type_id.
Referenced by NetObject::NetObject().
typeName()
virtual const char* WObject::typeName () inline virtual
Definition at line 199 of file wobject.hpp.
References getOClass(), and OClass::type_name.
Referenced by World::compute(), Dress::Dress(), Halo::Halo(), Hat::Hat(), Head::Head(), Cart::leaveIntoWorld(), Mirage::Mirage(), Head::setName(), Thing::Thing(), update3D(), and Wings::Wings().
update3D()
void WObject::update3D (Pos & pos) virtual
Updates object in the 3D.
Definition at line 45 of file vr2gl.cpp.
References _solids, Pos::ax, Pos::az, error(), MulM4(), pos, RotateM4(), solid, TranslateM4(), typeName(), UX, UZ, Pos::x, Pos::y, and Pos::z.
Referenced by elementaryImposedMovement(), and elementaryPermanentMovement().
updateAll3D()
void WObject::updateAll3D (Pos & pos) virtual
Updates object in the 3D.
Definition at line 29 of file vr2gl.cpp.
References _solids, Pos::ax, Pos::ay, Pos::az, MulM4(), pos, RotateM4(), solid, TranslateM4(), UX, UY, UZ, Pos::x, Pos::y, and Pos::z.
updateBB()
void WObject::updateBB () virtual
Updates object's Bounding Box.
Definition at line 639 of file wobject.cpp.
updateCamera()
void WObject::updateCamera (Pos & pos) virtual
Updates camera in the 3D.
Definition at line 64 of file vr2gl.cpp.
References Pos::ax, Pos::ay, Pos::az, g, User::height, localuser, M_PI_2, MulM4(), pos, Global::render, RotateM4(), Render::setCameraPosition(), TranslateM4(), UX, UY, UZ, Pos::x, Pos::y, and Pos::z.
Referenced by Aoi::aoiEnter(), Lift::changePosition(), permanentMovement(), Vrelet::processClient(), User::u_get_ax(), User::u_get_ay(), User::u_get_az(), User::u_get_xy(), User::u_get_z(), and User::userMovement().
updateGrid() [1/3]
void WObject::updateGrid (const float * bbminnew, const float * bbmaxnew, const float * bbminold, const float * bbmaxold) virtual
Updates an object in the grid.
Definition at line 476 of file col.cpp.
References addToListOnce(), World::current(), deleteFromGrid(), delFromList(), World::grid, World::gridList, and indiceGrid().
Referenced by Carrier::mouseEvent(), and updateGrid().
updateGrid() [2/3]
void WObject::updateGrid (const Pos & oldpos) virtual
Definition at line 527 of file col.cpp.
References Pos::bbcenter, Pos::bbsize, pos, updateGrid(), and V3::v.
updateGrid() [3/3]
void WObject::updateGrid (const WObject * pold) virtual
Updates an object into the grid.
Definition at line 515 of file col.cpp.
References Pos::bbcenter, Pos::bbsize, obj, pos, updateGrid(), and V3::v.
updateLasting()
bool WObject::updateLasting (time_t sec, time_t usec, float * lasting) virtual
Updates remaining times of the movement.
Definition at line 109 of file move.cpp.
References DBG_WO, diffTime(), endMovement(), move, Move::next, Move::perm_sec, Move::perm_usec, Move::sec, stopImposedMovement(), trace(), Move::ttl, Move::usec, and Move::without_col.
Referenced by Ball::updateTime(), Firework::updateTime(), Fractal::updateTime(), Bubble::updateTime(), Sheet::updateTime(), Thing::updateTime(), Projectile::updateTime(), User::updateTime(), Guide::updateTime(), Lift::updateTime(), Web::updateTime(), Book::updateTime(), Icon::updateTime(), and Door::updateTime().
updateMySqlPosition()
void WObject::updateMySqlPosition () virtual
Checks if position is managed by MySql and update it.
Definition at line 698 of file wobject.cpp.
References g, Times::mysql, progression(), ProfileTime::start(), ProfileTime::stop(), and Global::times.
updateMySqlPosZ()
void WObject::updateMySqlPosZ () virtual
Checks if posZ is managed by MySql.
Definition at line 711 of file wobject.cpp.
References g, Times::mysql, progression(), ProfileTime::start(), ProfileTime::stop(), and Global::times.
updateMySqlState()
void WObject::updateMySqlState (int16_t state) virtual
Updates state for MySql.
Definition at line 739 of file wobject.cpp.
References g, Times::mysql, progression(), ProfileTime::start(), ProfileTime::stop(), and Global::times.
Referenced by Door::close(), Thing::dropIntoBasket(), Door::lock(), Door::open(), and Door::unlock().
updateNames()
void WObject::updateNames () virtual
Updates names.
Definition at line 617 of file wobject.cpp.
References World::current(), World::getName(), and OBJNAME_LEN.
Referenced by User::inits(), Cart::leaveIntoWorld(), Mirage::setName(), Thing::setName(), and Head::setName().
updatePosition()
void WObject::updatePosition () virtual
Updating 3D.
Definition at line 657 of file wobject.cpp.
Referenced by Aoi::aoiEnter(), Ball::Ball(), Template::behavior(), Widget::behavior(), Bubble::Bubble(), Accessory::changePermanent(), Android::changePermanent(), Guy::changePermanent(), Head::changePermanent(), Mirage::changePermanent(), Step::changePermanent(), Wings::changePermanent(), Guide::changePosition(), Lift::changePosition(), Slider::changePosition(), User::decreasePitch(), User::decreaseRoll(), elementaryImposedMovement(), elementaryPermanentMovement(), User::elementaryUserMovement(), User::flyaway(), Gate::Gate(), Ground::Ground(), User::increasePitch(), User::increaseRoll(), Head::inits(), User::inits(), Cart::leaveIntoWorld(), Mirage::Mirage(), Model::Model(), Guide::motion(), Template::render(), Vnc::render(), Widget::render(), Icon::stick(), Thing::Thing(), User::toland(), Vnc::Vnc(), Wall::Wall(), Guide::whenIntersect(), and Water::whenIntersect().
updatePositionAndGrid() [1/2]
void WObject::updatePositionAndGrid (Pos & oldpos) virtual
Updating 3D and grid position.
Definition at line 664 of file wobject.cpp.
Referenced by get_ax(), get_ay(), get_az(), Button::get_bstate(), Animator::get_frame(), Bullet::get_hit(), Dart::get_hit(), Animator::get_nb_frames(), Animator::get_ttl(), get_xy(), get_z(), imposedMovement(), ingoingWalls(), Guide::motion(), Carrier::mouseEvent(), permanentMovement(), Vrelet::processClient(), projectPosition(), Guide::restore(), User::userMovement(), Ball::whenIntersect(), Cauldron::whenIntersect(), Gate::whenIntersect(), Ground::whenIntersect(), Guide::whenIntersect(), Icon::whenIntersect(), Lift::whenIntersect(), Plane::whenIntersect(), Step::whenIntersect(), User::whenIntersect(), and Lift::whenIntersectOut().
updatePositionAndGrid() [2/2]
void WObject::updatePositionAndGrid (WObject * pold) virtual
Updating 3D and grid position.
Definition at line 670 of file wobject.cpp.
updatePosToNetwork()
bool WObject::updatePosToNetwork (const Pos & oldpos, int propxy, int propz, int propaz, int propax, int propay) virtual
Publishes position changes to the network.
Definition at line 1110 of file wobject.cpp.
References ABSF, Pos::ax, Pos::ay, Pos::az, Pos::x, Pos::y, and Pos::z.
Referenced by Ball::updateToNetwork(), Board::updateToNetwork(), Book::updateToNetwork(), Bubble::updateToNetwork(), Doc::updateToNetwork(), Gate::updateToNetwork(), Guide::updateToNetwork(), Host::updateToNetwork(), Icon::updateToNetwork(), Mirror::updateToNetwork(), Music::updateToNetwork(), Sheet::updateToNetwork(), and Thing::updateToNetwork().
updateTime()
virtual void WObject::updateTime (time_t sec, time_t usec, float * lasting) inline virtual
Updates remaining times of the movement.
Reimplemented in Door, Door, Door, Icon, Book, Animator, Web, Slider, Lift, Guide, Bumper, User, Projectile, Vrelet, Thing, Step, Sheet, Bubble, Fractal, Firework, Clock, and Ball.
Definition at line 215 of file wobject.hpp.
Referenced by imposedMovement().
updateToNetwork()
virtual bool WObject::updateToNetwork (const Pos & oldpos) inline virtual
Publishes changes to the network.
Reimplemented in User, Thing, Step, Sheet, Projectile, Music, Mirror, Lift, Icon, Host, Guide, Gate, Gate, Gate, Door, Door, Door, Doc, Button, Bubble, Book, Board, and Ball.
Definition at line 218 of file wobject.hpp.
Referenced by imposedMovement(), and permanentMovement().
urlName()
const char * WObject::urlName () const virtual
Gets names.url.
Definition at line 332 of file wobject.cpp.
Referenced by Hairs::httpReader(), and Icon::Icon().
whenIntersect()
virtual bool WObject::whenIntersect (WObject * pcur, WObject * pold) inline virtual
Handles an ingoing collision with another object.
Reimplemented in Web, Water, Wall, Vrelet, User, Thing, Step, Slider, Sheet, Projectile, Plane, Music, Movie, Mirror, Lift, Icon, Host, Guide, Ground, Gate, Gate, Gate, Door, Door, Door, Doc, Clip, Cauldron, Bumper, Book, Board, Ball, Area, AnimX3d, and Animator.
Definition at line 224 of file wobject.hpp.
Referenced by generalIntersect().
whenIntersectOut()
virtual bool WObject::whenIntersectOut (WObject * pcur, WObject * pold) inline virtual
Handles an outgoing collision with another object.
Reimplemented in Water, Vrelet, Step, Lift, Guide, Gate, Gate, Gate, and Area.
Definition at line 227 of file wobject.hpp.
Referenced by generalIntersect().
whenWallsIntersect()
virtual void WObject::whenWallsIntersect (WObject * pold, V3 * norm) inline virtual
Handles collisions with walls.
Reimplemented in Projectile, and Ball.
Definition at line 230 of file wobject.hpp.
worldName()
const char * WObject::worldName () const virtual
Gets names.owner.
Definition at line 342 of file wobject.cpp.
Referenced by Gui::addUser(), Icon::destroy(), Icon::quit(), Gui::removeUser(), and Gui::updateUser().
Member Data Documentation
_solids
solidList WObject::_solids
list of solids.
Definition at line 129 of file wobject.hpp.
Referenced by Vnc::buildScreen(), Widget::buildScreen(), update3D(), and updateAll3D().
behavior
uint32_t WObject::behavior
behavior flags.
Definition at line 140 of file wobject.hpp.
Referenced by copyPositionAndBB(), endMovement(), and generalIntersect().
chan
char WObject::chan[CHAN_LEN]
channel.
Definition at line 151 of file wobject.hpp.
Referenced by Gate::enter(), and Gate::parser().
flare
class Flare* WObject::flare
flare instance
Definition at line 155 of file wobject.hpp.
Referenced by Solid::displayFlary(), and Mirage::Mirage().
geometry
char* WObject::geometry
geometry string.
Definition at line 149 of file wobject.hpp.
Referenced by Escalator::build(), Spiral::build(), Stair::build(), Travelator::build(), Cart::leaveIntoWorld(), Mirage::Mirage(), Thing::Thing(), and tokenize().
guip
struct GuiItem* WObject::guip
reserved field for GUI.
Definition at line 136 of file wobject.hpp.
Referenced by User::addGui(), and Cart::addToCart().
is_in_a_list
bool WObject::is_in_a_list
true if it is already in an OList.
Definition at line 145 of file wobject.hpp.
Referenced by addListToList().
mode
uint8_t WObject::mode
object world mode.
Definition at line 138 of file wobject.hpp.
Referenced by Cart::addToCart(), copyPositionAndBB(), and Carrier::take().
move
Move WObject::move
movement specific.
Definition at line 143 of file wobject.hpp.
Referenced by Book::approach(), bounceTrajectory(), Bullet::Bullet(), Ball::changePosition(), Book::changePosition(), Bumper::changePosition(), Door::changePosition(), Guide::changePosition(), Icon::changePosition(), Projectile::changePosition(), Sheet::changePosition(), User::changePosition(), Web::changePosition(), Door::close(), World::compute(), Dart::Dart(), diffTime(), disablePermanentMovement(), enableImposedMovement(), enablePermanentMovement(), endMovement(), gotoXYZ(), initImposedMovement(), Cart::leaveIntoWorld(), moveUserToObject(), Door::open(), permanentMovement(), Icon::pin(), Web::pivot(), Ball::pull(), Icon::pull(), Sheet::pullNext(), Sheet::pullPrev(), Ball::push(), Icon::push(), Sheet::pushNext(), Sheet::pushPrev(), Sheet::Sheet(), Ball::shoot(), Animator::start(), stopImposedMovement(), Carrier::take(), testMoving(), Ball::turn(), Icon::turn(), Sheet::turnNext(), Sheet::turnPrev(), Ball::up(), updateLasting(), Sheet::updateTime(), Bumper::updateTime(), Slider::updateTime(), Animator::updateTime(), Door::updateTime(), Ball::whenIntersect(), Guide::whenIntersect(), and Thing::whenIntersect().
names
Names WObject::names
names.
Definition at line 141 of file wobject.hpp.
Referenced by AnimX3d::AnimX3d(), Aoi::aoiEnter(), Movie::aviInit(), Ball::Ball(), Clip::Clip(), Host::connect(), Android::defaults(), Bubble::defaults(), Text::defaults(), Head::delMysql(), Icon::destroy(), Dress::Dress(), Gate::enter(), Music::format(), Ftp::get(), get_hname(), User::get_infos(), Icon::get_url(), Guy::getUrl(), Walls::getUrl(), Guy::Guy(), Hairs::Hairs(), Halo::Halo(), Hat::Hat(), Head::Head(), Icon::Icon(), Android::inits(), Guy::inits(), Head::inits(), Movie::inits(), isOwner(), Cart::leaveIntoWorld(), Model::loader(), Text::loadFont(), Mirage::Mirage(), Model::Model(), Carrier::mouseEvent(), Navig::mousePressB1orB3(), Movie::mpegInit(), Icon::open(), Web::open_cb(), Parse::parseAttributes(), Android::parser(), AnimX3d::parser(), Cart::parser(), Clip::parser(), Doc::parser(), Ftp::parser(), Gate::parser(), Guy::parser(), Hairs::parser(), Head::parser(), Host::parser(), Icon::parser(), Model::parser(), Movie::parser(), Music::parser(), Text::parser(), Walls::parser(), Web::parser(), Clip::play(), Music::play(), Doc::print_cb(), put_hname(), User::put_infos(), Icon::put_url(), Icon::quit(), Icon::save(), Ball::setName(), Mirage::setName(), Model::setName(), Thing::setName(), User::setName(), Head::setName(), setOwner(), setUser(), Clip::startRtp(), Thing::Thing(), Gui::updateCart(), User::User(), Doc::view_cb(), Walls::Walls(), Gate::whenIntersect(), User::whenIntersect(), and Wings::Wings().
noh
class NetObject* WObject::noh
reserved field for network.
Definition at line 135 of file wobject.hpp.
Referenced by Cart::addToCart(), Aoi::aoiEnter(), Aoi::aoiQuit(), Ball::Ball(), Bullet::Bullet(), Dart::Dart(), Icon::Icon(), imposedMovement(), Cart::leaveIntoWorld(), permanentMovement(), World::quit(), NetObject::replicateObject(), Solid::resetRay(), Solid::setRay(), User::setRayDirection(), Button::updateToNetwork(), Door::updateToNetwork(), Lift::updateToNetwork(), Projectile::updateToNetwork(), User::updateToNetwork(), User::User(), User::userRequesting(), User::userWriting(), User::whenIntersect(), and User::~User().
noid
class WObjectId WObject::noid
WObject Id.
Definition at line 143 of file wobject.hpp.
Referenced by Ball::replicator(), Bullet::replicator(), Dart::replicator(), and Icon::replicator().
num
uint16_t WObject::num
object sequence number.
Definition at line 139 of file wobject.hpp.
Referenced by copyPositionAndBB(), getNumber(), Render::setzname(), and Txf::Txf().
objectbar
bool WObject::objectbar protected
true if object bar is active.
Definition at line 132 of file wobject.hpp.
pos
Pos WObject::pos
position in the space.
Definition at line 142 of file wobject.hpp.
Referenced by Book::approach(), Ball::Ball(), Book::Book(), Cloud::build(), Escalator::build(), Spiral::build(), Stair::build(), Travelator::build(), Bullet::Bullet(), Lift::call(), Accessory::changePermanent(), Android::changePermanent(), Ball::changePermanent(), Cauldron::changePermanent(), Clock::changePermanent(), Cloth::changePermanent(), Cloud::changePermanent(), Guide::changePermanent(), Guy::changePermanent(), Head::changePermanent(), Icon::changePermanent(), Mirage::changePermanent(), Model::changePermanent(), Rain::changePermanent(), Snow::changePermanent(), Step::changePermanent(), Sun::changePermanent(), User::changePermanent(), Wings::changePermanent(), User::changePosition(), Ball::changePosition(), Book::changePosition(), Bumper::changePosition(), Door::changePosition(), Guide::changePosition(), Icon::changePosition(), Lift::changePosition(), Projectile::changePosition(), Sheet::changePosition(), Slider::changePosition(), Web::changePosition(), User::changePositionOneDir(), Board::click(), Vrelet::click(), Render::clickDirection(), Door::close(), Button::commut(), Render::computeCameraProjection(), Vicinity::computeDistance(), computeNormal(), Vicinity::computeSize(), copyPosAndBB(), copyPositionAndBB(), Dart::Dart(), User::decreasePitch(), User::decreaseRoll(), User::defaults(), deleteFromGrid(), Vrelet::deltaPos(), Solid::displayFlary(), Solid::displayList(), Solid::displayMirroredScene(), Door::Door(), Lift::down(), Thunder::draw(), elementaryImposedMovement(), elementaryPermanentMovement(), Entry::Entry(), User::flyaway(), Accessory::follow(), Gate::Gate(), Firework::generate(), Particle::generate(), get_ax(), get_ay(), get_az(), Button::get_bstate(), Animator::get_frame(), Bullet::get_hit(), Dart::get_hit(), Animator::get_nb_frames(), Animator::get_ttl(), get_xy(), get_z(), getSurfVecs(), getVicinityList(), Render::getVisiblePosition(), gotoXYZ(), Ground::Ground(), Guide::Guide(), Icon::Icon(), imposedMovement(), User::increasePitch(), User::increaseRoll(), ingoingNeighbor(), ingoingWalls(), Cloth::inits(), Cloud::inits(), Flag::inits(), Head::inits(), Sun::inits(), Water::inits(), insertIntoGrid(), interAABB(), Carrier::leave(), Cart::leaveIntoWorld(), Lift::Lift(), Light::Light(), Door::lock(), Plane::makeSolid(), Mech::Mech(), Mirage::Mirage(), Model::Model(), Guide::motion(), Carrier::mouseEvent(), moveUserToObject(), Book::nextSheet(), Door::open(), outgoingNeighbor(), Parse::parseAttributes(), Button::parser(), Guide::parser(), Mirage::parser(), permanentMovement(), Icon::pin(), Web::pivot(), Plane::Plane(), Stars::pointed(), Model::preRender(), Book::prevSheet(), projectPosition(), Ball::pull(), Icon::pull(), Sheet::pullNext(), Ball::push(), Icon::push(), put_ax(), put_ay(), put_az(), Button::put_bstate(), User::put_ray(), put_xy(), put_z(), VjcMessage::putPos(), Entry::query(), Icon::quit(), Cloud::rebuild(), Particle::regenerate(), Android::render(), AnimX3d::render(), Fire::render(), Firework::render(), Flag::render(), Guy::render(), Hairs::render(), Head::render(), Mech::render(), Model::render(), Particle::render(), River::render(), Smoke::render(), Stars::render(), Sun::render(), Terrain::render(), Text::render(), Vnc::render(), Water::render(), Widget::render(), Wings::render(), _3ds::render(), Flare::render(), User::resetPosition(), Guide::restore(), Vrelet::setPos(), Bubble::setPosition(), Solid::setRay(), User::setRayDirection(), User::setRoll(), Vicinity::setUserSize(), Sheet::Sheet(), Ball::shoot(), Stars::show(), Step::Step(), Icon::stick(), Thing::Thing(), User::toland(), User::u_get_ax(), User::u_get_ay(), User::u_get_az(), User::u_get_xy(), User::u_get_z(), Door::unlock(), Lift::up(), update3D(), updateAll3D(), updateCamera(), updateGrid(), Scene::updateHud(), Sheet::updateTime(), Door::updateTime(), Button::updateToNetwork(), Door::updateToNetwork(), Lift::updateToNetwork(), Projectile::updateToNetwork(), User::updateToNetwork(), User::userMovement(), Wall::Wall(), Web::Web(), Ball::whenIntersect(), Bumper::whenIntersect(), Cauldron::whenIntersect(), Gate::whenIntersect(), Ground::whenIntersect(), Guide::whenIntersect(), Icon::whenIntersect(), Lift::whenIntersect(), Plane::whenIntersect(), Step::whenIntersect(), Thing::whenIntersect(), User::whenIntersect(), Wall::whenIntersect(), Water::whenIntersect(), and Wings::Wings().
prior
int8_t WObject::prior
render priority.
Definition at line 148 of file wobject.hpp.
removed
bool WObject::removed
flag removed or not.
Definition at line 146 of file wobject.hpp.
solid
class Solid* WObject::solid
solid pointer
Definition at line 150 of file wobject.hpp.
Referenced by Sun::inits(), Mirage::Mirage(), Navig::mousePressB1orB3(), Navig::mousePressB2(), update3D(), and updateAll3D().
state
int16_t WObject::state
current state.
Definition at line 147 of file wobject.hpp.
Referenced by Animator::Animator(), Book::backwardSheet(), Book::Book(), Bubble::Bubble(), Lift::call(), Android::changePermanent(), Cloud::changePermanent(), Movie::changePermanent(), Particle::changePermanent(), Rain::changePermanent(), Snow::changePermanent(), Thunder::changePermanent(), Bubble::changePosition(), Bumper::changePosition(), Lift::changePosition(), Slider::changePosition(), Clip::Clip(), Door::close(), Book::close(), Music::cont(), Clip::contRtp(), Android::defaults(), Animator::defaults(), Board::defaults(), Book::defaults(), Bubble::defaults(), Cloud::defaults(), Model::defaults(), Movie::defaults(), Music::defaults(), Slider::defaults(), Sun::defaults(), Text::defaults(), Thing::defaults(), Thunder::defaults(), Web::defaults(), Android::disconnectFromBapServer(), Door::Door(), Thing::dropIntoBasket(), Book::forwardSheet(), Firework::generate(), Board::import(), Animator::isMoving(), Bumper::isMoving(), Slider::isMoving(), Door::lock(), Movie::loop(), Music::loop(), Book::nextSheet(), Door::open(), Book::open(), Animator::parser(), Particle::Particle(), Fountain::pause(), Movie::pause(), Music::pause(), Waterfall::pause(), Cloud::pause_cb(), Step::pause_cb(), Clip::pauseRtp(), Web::pivot(), Movie::play(), Music::play(), Book::prevSheet(), Clip::quit(), Firework::render(), Particle::render(), Text::render(), Thunder::render(), Android::reset(), Movie::rewind(), Android::sendPlayToBapServer(), Sheet::Sheet(), Animator::start(), Clip::startRtp(), Animator::stop(), Movie::stop(), Music::stop(), Rain::stop_cb(), Snow::stop_cb(), Clip::stopRtp(), Door::unlock(), Firework::updateTime(), Bubble::updateTime(), Door::updateTime(), Board::wb_cb(), Book::whenIntersect(), Bumper::whenIntersect(), Lift::whenIntersect(), Slider::whenIntersect(), and Lift::whenIntersectOut().
type
uint8_t WObject::type
object type.
Definition at line 137 of file wobject.hpp.
Referenced by Carrier::Carrier(), copyPositionAndBB(), Cart::defaults(), Solid::displayList(), generalIntersect(), getLasting(), getType(), imposedMovement(), NetObject::NetObject(), Button::parser(), permanentMovement(), VjcMessage::putOID(), setLasting(), User::specialAction(), User::User(), User::userMovement(), Area::whenIntersect(), Ball::whenIntersect(), Bumper::whenIntersect(), Cauldron::whenIntersect(), Door::whenIntersect(), Gate::whenIntersect(), Ground::whenIntersect(), Guide::whenIntersect(), Icon::whenIntersect(), Lift::whenIntersect(), Mirror::whenIntersect(), Plane::whenIntersect(), Projectile::whenIntersect(), Step::whenIntersect(), Thing::whenIntersect(), User::whenIntersect(), Wall::whenIntersect(), Water::whenIntersect(), Web::whenIntersect(), Area::whenIntersectOut(), Gate::whenIntersectOut(), Guide::whenIntersectOut(), Step::whenIntersectOut(), and Water::whenIntersectOut().
The documentation for this class was generated from the following files:
src/wo/wobject.hpp
src/wo/col.cpp
src/wo/move.cpp
src/wo/names.cpp
src/wo/parse.cpp
src/wo/vr2gl.cpp
src/wo/wobject.cpp