VREng: Rtp Class Reference
Rtp Class Reference
Rtp class.
#include <rtp.hpp>
Static Public Member Functions
static uint16_t createSeq ()
static uint32_t createSsrc (int value)
static void initSource (sourceInfos *s, uint16_t seq)
static int updateSeq (sourceInfos *s, uint16_t seq)
static int sendPacket (int fd, const uint8_t *pkt, int pkt_len, const struct sockaddr_in *to)
Sends a packet Returns result of sendto(): -1 if error, else >=0.
static int recvRTCPPacket (struct sockaddr_in *from, uint8_t *pkt, int pkt_len)
Receive a RTCP packet.
static const char * getRtpName (char *name)
static void getRtcpName (char *name)
static void getRtcpEmail (char *email)
static void getRtcpTool (char *tool)
static SdesItem * allocSdesItem ()
static bool isSdesType (uint8_t sdes_type)
static void getSdesItemBySsrc (uint8_t type, uint32_t ssrc, char *itemstr)
static void getRtcpNameBySsrc (uint32_t ssrc, char *rtpname)
static void getRtcpEmailBySsrc (uint32_t ssrc, char *email)
static void getRtcpToolBySsrc (uint32_t ssrc, char *tool)
Static Public Attributes
static const uint8_t RTPNAME_LEN = 128
static const uint8_t EMAIL_LEN = 255
static const uint8_t TOOL_LEN = 16
Detailed Description
Rtp class.
Definition at line 243 of file rtp.hpp.
Member Function Documentation
allocSdesItem()
SdesItem * Rtp::allocSdesItem () static
Definition at line 272 of file rtp.cpp.
Referenced by Session::createMySdes().
createSeq()
uint16_t Rtp::createSeq () static
Definition at line 37 of file rtp.cpp.
Referenced by Session::create().
createSsrc()
uint32_t Rtp::createSsrc (int value) static
Definition at line 45 of file rtp.cpp.
References random32().
Referenced by Session::create().
getRtcpEmail()
void Rtp::getRtcpEmail (char * email) static
Definition at line 169 of file rtp.cpp.
References EMAIL_LEN, MAXHOSTNAMELEN, my_free_hostent(), and my_gethostbyname_r().
Referenced by Session::createMySdes(), getRtcpName(), and User::setRtcp().
getRtcpEmailBySsrc()
void Rtp::getRtcpEmailBySsrc (uint32_t ssrc, char * email) static
Definition at line 262 of file rtp.cpp.
References getSdesItemBySsrc(), and RTCP_SDES_EMAIL.
getRtcpName()
void Rtp::getRtcpName (char * name) static
Definition at line 195 of file rtp.cpp.
References getRtcpEmail(), getRtpName(), and RTPNAME_LEN.
Referenced by Session::createMySdes(), and User::setRtcp().
getRtcpNameBySsrc()
void Rtp::getRtcpNameBySsrc (uint32_t ssrc, char * rtpname) static
Definition at line 257 of file rtp.cpp.
References getSdesItemBySsrc(), and RTCP_SDES_NAME.
getRtcpTool()
void Rtp::getRtcpTool (char * tool) static
Definition at line 208 of file rtp.cpp.
Referenced by Session::createMySdes(), and User::setRtcp().
getRtcpToolBySsrc()
void Rtp::getRtcpToolBySsrc (uint32_t ssrc, char * tool) static
Definition at line 267 of file rtp.cpp.
References getSdesItemBySsrc(), and RTCP_SDES_TOOL.
getRtpName()
const char * Rtp::getRtpName (char * name) static
Definition at line 145 of file rtp.cpp.
References File::closeFile(), and File::openFile().
Referenced by getRtcpName().
getSdesItemBySsrc()
void Rtp::getSdesItemBySsrc (uint8_t type, uint32_t ssrc, char * itemstr) static
Definition at line 226 of file rtp.cpp.
References error(), Session::getList(), isSdesType(), Session::mode, Source::next, SdesItem::si_len, SdesItem::si_next, SdesItem::si_str, SdesItem::si_type, and Channel::WORLD_MODE.
Referenced by getRtcpEmailBySsrc(), getRtcpNameBySsrc(), and getRtcpToolBySsrc().
initSource()
void Rtp::initSource (sourceInfos * s, uint16_t seq) static
Definition at line 76 of file rtp.cpp.
References sourceInfos::bad_seq, sourceInfos::base_seq, sourceInfos::cycles, sourceInfos::max_seq, sourceInfos::received, and RTP_SEQ_MOD.
Referenced by Session::create(), and updateSeq().
isSdesType()
bool Rtp::isSdesType (uint8_t sdes_type) static
Definition at line 213 of file rtp.cpp.
References RTCP_SDES_CNAME, RTCP_SDES_EMAIL, RTCP_SDES_LOC, RTCP_SDES_NAME, and RTCP_SDES_TOOL.
Referenced by getSdesItemBySsrc().
recvRTCPPacket()
int Rtp::recvRTCPPacket (struct sockaddr_in * from, uint8_t * pkt, int pkt_len) static
Receive a RTCP packet.
Receives a RTCP packet.
Definition at line 307 of file rtp.cpp.
References rtcp_t::common, Channel::current(), DBG_FORCE, DBG_RTP, Session::deleteSourceBySsrc(), end, error(), Source::getSource(), rtcp_common_t::length, rtcp_common_t::pt, RTCP_APP, RTCP_BYE, RTCP_SDES, RTCP_SDES_END, RTCP_SR, RTP_VERSION, Source::sdes, Channel::session, SdesItem::si_len, SdesItem::si_next, SdesItem::si_str, SdesItem::si_type, Source::sr, and trace().
Referenced by Payload::recvPayload().
sendPacket()
int Rtp::sendPacket (int fd, const uint8_t * pkt, int pkt_len, const struct sockaddr_in * to) static
Sends a packet Returns result of sendto(): -1 if error, else >=0.
Sends a packet.
Definition at line 284 of file rtp.cpp.
References error(), and statSendPacket().
Referenced by Payload::sendPayload(), Session::sendRTCPPacket(), and Session::sendSRSDES().
updateSeq()
int Rtp::updateSeq (sourceInfos * s, uint16_t seq) static
Definition at line 85 of file rtp.cpp.
References sourceInfos::bad_seq, sourceInfos::cycles, initSource(), sourceInfos::max_seq, sourceInfos::probation, sourceInfos::received, and RTP_SEQ_MOD.
Referenced by Payload::recvPayload().
Member Data Documentation
EMAIL_LEN
const uint8_t Rtp::EMAIL_LEN = 255 static
Definition at line 247 of file rtp.hpp.
Referenced by User::getMemory(), getRtcpEmail(), and User::setRtcp().
RTPNAME_LEN
const uint8_t Rtp::RTPNAME_LEN = 128 static
Definition at line 246 of file rtp.hpp.
Referenced by User::getMemory(), getRtcpName(), and User::setRtcp().
TOOL_LEN
const uint8_t Rtp::TOOL_LEN = 16 static
Definition at line 248 of file rtp.hpp.
Referenced by User::getMemory(), and User::setRtcp().
The documentation for this class was generated from the following files:
src/net/rtp.hpp
src/net/rtp.cpp