VREng: Payload Class Reference
Payload Class Reference
Payload class.
#include <payload.hpp>
Public Member Functions
Payload ()
Constructor.
virtual ~Payload ()
Destructor.
virtual int putPayload (const char *format,...)
Fills the payload in sprintf style Returns 0 if OK, else -1 if err.
virtual int getPayload (const char *format,...)
Gets the payload in scanf style Returns 0 if OK, else -1 if err.
virtual bool isValidPayload ()
Checks payload validity.
virtual Payload * resetPayload ()
Resets the payload, sets offset at the begining of the payload to call before using.
virtual void dumpPayload (FILE *fp)
Dumps payload in a file pointed by fp.
virtual void seekPayload (const uint16_t idx)
Seeks pos inside the payload.
virtual uint16_t tellPayload ()
Returns current offset inside the payload.
virtual int tellStrInPayload (const char *str)
Returns current offset of string "str" inside the payload.
virtual int sendPayload (const struct sockaddr_in *to)
Sends a payload packet to the network.
virtual int recvPayload (const int fd, struct sockaddr_in *sender)
Receives a payload packet from the network.
virtual void incomingDelta (const struct sockaddr_in *sender)
Incoming Delta: format (3 bytes) noid (8 bytes: 4 + 2 + 2) prop_id (1 byte) version_id (2 bytes) total (14 bytes)
virtual void incomingCreate (const struct sockaddr_in *sender)
Incoming Create: format (3 bytes) type_id (1 byte) noid (8 bytes: 4 + 2 + 2) permanent_flag (1 byte) properties (nprop * 20 bytes: 2 + 2 + 8 + 8) Create the object's local copy if it doesn't exist.
virtual void incomingQuery (const struct sockaddr_in *sender)
Incoming Query: format (1 byte) noid (8 bytes: 4 + 2 + 2) total (9 bytes)
virtual void incomingDelete (const struct sockaddr_in *sender)
Incoming Delete: format (1 byte) noid (8 bytes: 4 + 2 + 2) total (9 bytes)
virtual void incomingOther (const struct sockaddr_in *sender, const int len)
Incoming not identified.
Public Attributes
uint16_t len
length
uint16_t idx
current offset
uint8_t vrep
vrep version
bool gzipped
if compression
uint8_t data [PAYLOAD_LEN]
data
Detailed Description
Payload class.
Definition at line 33 of file payload.hpp.
Constructor & Destructor Documentation
Payload()
Payload::Payload ()
Constructor.
Definition at line 34 of file payload.cpp.
References gzipped, idx, len, new_payload, vrep, and VREP_VERSION_V3.
~Payload()
Payload::~Payload () virtual
Destructor.
Definition at line 43 of file payload.cpp.
References del_payload.
Member Function Documentation
dumpPayload()
void Payload::dumpPayload (FILE * fp) virtual
Dumps payload in a file pointed by fp.
Definition at line 399 of file payload.cpp.
References data, idx, and len.
Referenced by getPayload(), putPayload(), NetObject::sendCreate(), and tellStrInPayload().
getPayload()
int Payload::getPayload (const char * format, ...) virtual
Gets the payload in scanf style Returns 0 if OK, else -1 if err.
Definition at line 179 of file payload.cpp.
References d, data, DBG_FORCE, dumpPayload(), error(), idx, isValidPayload(), len, Noid::obj_id, Noid::port_id, Noid::src_id, and trace().
Referenced by WObject::get_ax(), WObject::get_ay(), WObject::get_az(), Button::get_bstate(), User::get_bust(), User::get_color(), User::get_face(), Animator::get_frame(), Icon::get_gname(), User::get_head(), Bullet::get_hit(), Dart::get_hit(), WObject::get_hname(), User::get_infos(), User::get_mapback(), User::get_mapfront(), User::get_mapleft(), User::get_mapright(), User::get_mensuration(), User::get_model(), User::get_msg(), Animator::get_nb_frames(), User::get_ray(), User::get_rtcpemail(), User::get_rtcpname(), User::get_sex(), User::get_skin(), User::get_ssrc(), Icon::get_tex(), Animator::get_ttl(), Icon::get_url(), User::get_username(), User::get_vre(), User::get_web(), WObject::get_xy(), WObject::get_z(), incomingCreate(), incomingDelete(), incomingDelta(), incomingQuery(), and NetIncoming().
incomingCreate()
void Payload::incomingCreate (const struct sockaddr_in * sender) virtual
Incoming Create: format (3 bytes) type_id (1 byte) noid (8 bytes: 4 + 2 + 2) permanent_flag (1 byte) properties (nprop * 20 bytes: 2 + 2 + 8 + 8) Create the object's local copy if it doesn't exist.
Definition at line 716 of file payload.cpp.
References NetObject::addToList(), DBG_NET, NetObject::equalNoid(), error(), NetObject::getNetNameById(), Noid::getNetNameById(), Noid::getNetObject(), getPayload(), NetObject::getPropertiesNumber(), NetObject::initProperties(), NetObject::netprop, NetObject::noid, NetObject::permanent, NetObject::replicateObject(), trace(), NetObject::type, and NetProperty::version.
Referenced by NetIncoming().
incomingDelete()
void Payload::incomingDelete (const struct sockaddr_in * sender) virtual
Incoming Delete: format (1 byte) noid (8 bytes: 4 + 2 + 2) total (9 bytes)
Definition at line 784 of file payload.cpp.
References DBG_NET, Noid::getNetNameById(), Noid::getNetObject(), getPayload(), inet4_ntop(), NetObject::requestDeletionFromNetwork(), and trace().
Referenced by NetIncoming().
incomingDelta()
void Payload::incomingDelta (const struct sockaddr_in * sender) virtual
Incoming Delta: format (3 bytes) noid (8 bytes: 4 + 2 + 2) prop_id (1 byte) version_id (2 bytes) total (14 bytes)
Definition at line 659 of file payload.cpp.
References d, DBG_NET, NetObject::declareObjDelta(), error(), Noid::getNetNameById(), Noid::getNetObject(), getPayload(), NetObject::getPropertiesNumber(), NetObject::getProperty(), inet4_ntop(), NetObject::netprop, NetProperty::resetDates(), NetProperty::responsible, Noid::sendQueryNoid(), NetProperty::setResponsible(), trace(), NetObject::type, NetProperty::version, and warning().
Referenced by NetIncoming().
incomingOther()
void Payload::incomingOther (const struct sockaddr_in * sender, const int len) virtual
Incoming not identified.
Definition at line 797 of file payload.cpp.
References data, DBG_NET, error(), size, and trace().
Referenced by NetIncoming().
incomingQuery()
void Payload::incomingQuery (const struct sockaddr_in * sender) virtual
Incoming Query: format (1 byte) noid (8 bytes: 4 + 2 + 2) total (9 bytes)
Definition at line 757 of file payload.cpp.
References DBG_NET, error(), NetObject::getNetNameById(), Noid::getNetNameById(), Noid::getNetObject(), getPayload(), inet4_ntop(), Noid::port_id, NetObject::sendCreate(), Noid::sendDeleteNoid(), trace(), and warning().
Referenced by NetIncoming().
isValidPayload()
bool Payload::isValidPayload () virtual
Checks payload validity.
Definition at line 56 of file payload.cpp.
References idx, len, and PAYLOAD_LEN.
Referenced by getPayload(), putPayload(), and sendPayload().
putPayload()
int Payload::putPayload (const char * format, ...) virtual
Fills the payload in sprintf style Returns 0 if OK, else -1 if err.
Definition at line 62 of file payload.cpp.
References d, data, DBG_NET, dumpPayload(), error(), idx, isValidPayload(), len, Noid::obj_id, PAYLOAD_LEN, Noid::port_id, Noid::src_id, and trace().
Referenced by User::bulletPutHit(), User::dartPutHit(), WObject::put_ax(), WObject::put_ay(), WObject::put_az(), Button::put_bstate(), User::put_bust(), User::put_color(), User::put_face(), Animator::put_frame(), Icon::put_gname(), User::put_head(), WObject::put_hname(), User::put_infos(), User::put_mapback(), User::put_mapfront(), User::put_mapleft(), User::put_mapright(), User::put_mensuration(), User::put_model(), User::put_msg(), Animator::put_nb_frames(), User::put_ray(), User::put_rtcpemail(), User::put_rtcpname(), User::put_sex(), User::put_skin(), User::put_ssrc(), Icon::put_tex(), Animator::put_ttl(), Icon::put_url(), User::put_username(), User::put_vre(), User::put_web(), WObject::put_xy(), WObject::put_z(), NetObject::sendCreate(), NetObject::sendDelete(), NetObject::sendDeleteNoid(), Noid::sendDeleteNoid(), NetObject::sendDelta(), NetObject::sendQueryNoid(), and Noid::sendQueryNoid().
recvPayload()
int Payload::recvPayload (const int fd, struct sockaddr_in * sender) virtual
Receives a payload packet from the network.
Receives a Payload packet.
Definition at line 518 of file payload.cpp.
References sourceInfos::base_seq, sourceInfos::cycles, data, DBG_NET, error(), Source::expected, Source::extended_max, NetObject::getMyHostId(), NetObject::getMySsrcId(), Source::getSource(), gzipped, rtcp_rr_t::last_seq, len, rtcp_rr_t::lost, Source::lost, sourceInfos::max_seq, PKTSIZE, rtp_hdr_t::pt, rtcp_common_t::pt, sourceInfos::received, Rtp::recvRTCPPacket(), resetPayload(), Source::rr, RTCP_APP, RTCP_BYE, RTCP_RR, RTCP_SDES, RTCP_SR, RTP_HDR_SIZE, RTP_VERSION, RTP_VREP_TYPE, RTP_VREP_TYPE_V1, Source::s, rtp_hdr_t::seq, rtp_hdr_t::ssrc, statReceivePacket(), trace(), Rtp::updateSeq(), rtp_hdr_t::version, rtcp_common_t::version, vrep, VREP_GZIP_MASK, VREP_HDR_FLAGS, VREP_HDR_PLLEN, VREP_HDR_PLLEN_V1, VREP_HDR_PORTID_V1, VREP_HDR_SIZE_V1, VREP_HDR_SIZE_V2, VREP_HDR_SIZE_V3, VREP_HDR_SRCID_V1, VREP_HDR_VERSION, VREP_VERSION_V2, and VREP_VERSION_V3.
Referenced by NetIncoming().
resetPayload()
Payload * Payload::resetPayload () virtual
Resets the payload, sets offset at the begining of the payload to call before using.
Definition at line 48 of file payload.cpp.
References idx, and len.
Referenced by recvPayload().
seekPayload()
void Payload::seekPayload (const uint16_t idx) virtual
Seeks pos inside the payload.
Definition at line 331 of file payload.cpp.
References idx.
Referenced by User::User().
sendPayload()
int Payload::sendPayload (const struct sockaddr_in * to) virtual
Sends a payload packet to the network.
Sends a payload.
TODO: add vrep_version argument
Definition at line 434 of file payload.cpp.
References Session::buildRtpHeader(), Channel::current(), data, DBG_NET, error(), Channel::getbysa(), Channel::getFdSendRTP(), getSentPackets(), isValidPayload(), len, PKTSIZE, Session::refreshMySdes(), RTP_HDR_SIZE, Channel::sd, SD_W_RTP, Rtp::sendPacket(), Session::sendSRSDES(), Channel::session, Session::sr, Channel::ssrc, statSendRTP(), trace(), vrep, VREP_HDR_FLAGS, VREP_HDR_IP, VREP_HDR_PLLEN, VREP_HDR_SIZE_V2, VREP_HDR_SIZE_V3, VREP_HDR_VERSION, VREP_VERSION_V2, and VREP_VERSION_V3.
Referenced by Channel::naming(), NetObject::sendCreate(), NetObject::sendDelete(), NetObject::sendDeleteNoid(), Noid::sendDeleteNoid(), NetObject::sendDelta(), NetObject::sendQueryNoid(), and Noid::sendQueryNoid().
tellPayload()
uint16_t Payload::tellPayload () virtual
Returns current offset inside the payload.
Definition at line 336 of file payload.cpp.
References idx.
Referenced by User::User().
tellStrInPayload()
int Payload::tellStrInPayload (const char * str) virtual
Returns current offset of string "str" inside the payload.
Definition at line 341 of file payload.cpp.
References data, dumpPayload(), error(), idx, and len.
Referenced by User::User().
Member Data Documentation
data
uint8_t Payload::data[PAYLOAD_LEN]
data
Definition at line 40 of file payload.hpp.
Referenced by dumpPayload(), getPayload(), incomingOther(), putPayload(), recvPayload(), sendPayload(), and tellStrInPayload().
gzipped
bool Payload::gzipped
if compression
Definition at line 39 of file payload.hpp.
Referenced by Payload(), and recvPayload().
idx
uint16_t Payload::idx
current offset
Definition at line 37 of file payload.hpp.
Referenced by dumpPayload(), getPayload(), isValidPayload(), Payload(), putPayload(), resetPayload(), seekPayload(), tellPayload(), and tellStrInPayload().
len
uint16_t Payload::len
length
Definition at line 36 of file payload.hpp.
Referenced by dumpPayload(), getPayload(), isValidPayload(), NetIncoming(), Payload(), putPayload(), recvPayload(), resetPayload(), sendPayload(), and tellStrInPayload().
vrep
uint8_t Payload::vrep
vrep version
Definition at line 38 of file payload.hpp.
Referenced by Payload(), recvPayload(), and sendPayload().
The documentation for this class was generated from the following files:
src/net/payload.hpp
src/net/payload.cpp