VREng: Vac Class Reference
Vac Class Reference
Vac class.
#include <vac.hpp>
Public Member Functions
Vac ()
Constructor.
virtual ~Vac ()
virtual bool getList ()
Destructor.
virtual bool resolveWorldUrl (const char *_url, char *chanstr)
Resolves an Url and retrieves a channel string.
virtual bool getChannel (const char *_url, char *chanstr)
Gets a channel by its url from the list.
virtual bool getUrlAndChannel (const char *name, char *_url, char *chanstr)
Gets an url and its channel by its world name from the list.
virtual bool isConnected ()
Returns true if connected else false.
Static Public Member Functions
static Vac * current ()
Returns vac instance.
static Vac * init ()
Init vac.
Public Attributes
char url [URL_LEN]
world url
char channel [CHAN_LEN]
mapped channel
Vac * next
next entry
bool connected
int sdvac
x true if connect established
Private Member Functions
virtual bool connectVac ()
Establishes a connection with the Vacs server.
Static Private Member Functions
static void * connectThread (void *)
Establishes a connection with the Vacs server.
Detailed Description
Vac class.
Definition at line 27 of file vac.hpp.
Constructor & Destructor Documentation
Vac()
Vac::Vac ()
Constructor.
Definition at line 33 of file vac.cpp.
References channel, connected, next, sdvac, and url.
Referenced by getList(), init(), and resolveWorldUrl().
~Vac()
virtual Vac::~Vac () inline virtual
Definition at line 38 of file vac.hpp.
Member Function Documentation
connectThread()
void * Vac::connectThread (void *) static private
Establishes a connection with the Vacs server.
Thread.
Definition at line 77 of file vac.cpp.
References DEF_VACS_SERVER, error(), my_free_hostent(), my_gethostbyname(), Socket::openStream(), sdvac, and VACS_PORT.
Referenced by connectVac().
connectVac()
bool Vac::connectVac () private virtual
Establishes a connection with the Vacs server.
Connect to the VACS server: return false if connect fails.
Definition at line 62 of file vac.cpp.
References connected, and connectThread().
Referenced by getList(), and resolveWorldUrl().
current()
Vac * Vac::current () static
Returns vac instance.
Definition at line 51 of file vac.cpp.
References vac.
Referenced by Gate::enter(), Gui::gotoWorld(), and Pref::parse().
getChannel()
bool Vac::getChannel (const char * _url, char * chanstr) virtual
Gets a channel by its url from the list.
Definition at line 227 of file vac.cpp.
References next, url, and vacList.
Referenced by Gate::enter().
getList()
bool Vac::getList () virtual
Destructor.
Gets the whole cache and put it into an internal list
Definition at line 114 of file vac.cpp.
References channel, Socket::closeStream(), connected, connectVac(), DBG_INIT, DEF_MANAGER_CHANNEL, MANAGER_NAME, next, read, sdvac, trace(), url, vac, Vac(), vacList, VRE_VERSION, and write.
Referenced by init().
getUrlAndChannel()
bool Vac::getUrlAndChannel (const char * name, char * _url, char * chanstr) virtual
Gets an url and its channel by its world name from the list.
Definition at line 240 of file vac.cpp.
References next, url, and vacList.
Referenced by Gui::gotoWorld().
init()
Vac * Vac::init () static
Init vac.
Initialization.
Definition at line 43 of file vac.cpp.
References getList(), vac, and Vac().
Referenced by Global::startCB().
isConnected()
bool Vac::isConnected () virtual
Returns true if connected else false.
Definition at line 56 of file vac.cpp.
References connected.
resolveWorldUrl()
bool Vac::resolveWorldUrl (const char * _url, char * chanstr) virtual
Resolves an Url and retrieves a channel string.
Definition at line 175 of file vac.cpp.
References CHAN_LEN, channel, Socket::closeStream(), connected, connectVac(), DEF_VRE_CHANNEL, error(), next, read, sdvac, url, URL_LEN, vac, Vac(), vacList, and write.
Referenced by Gate::enter(), Gui::gotoWorld(), and Pref::parse().
Member Data Documentation
channel
char Vac::channel[CHAN_LEN]
mapped channel
Definition at line 31 of file vac.hpp.
Referenced by getList(), resolveWorldUrl(), and Vac().
connected
bool Vac::connected
Definition at line 33 of file vac.hpp.
Referenced by connectVac(), getList(), isConnected(), resolveWorldUrl(), and Vac().
next
Vac* Vac::next
next entry
Definition at line 32 of file vac.hpp.
Referenced by getChannel(), getList(), getUrlAndChannel(), resolveWorldUrl(), and Vac().
sdvac
int Vac::sdvac
x true if connect established
file descriptor
Definition at line 34 of file vac.hpp.
Referenced by connectThread(), getList(), resolveWorldUrl(), and Vac().
url
char Vac::url[URL_LEN]
world url
Definition at line 30 of file vac.hpp.
Referenced by getChannel(), getList(), getUrlAndChannel(), resolveWorldUrl(), and Vac().
The documentation for this class was generated from the following files:
src/net/vac.hpp
src/net/vac.cpp