VREng: Solid Class Reference
Solid Class Reference
Solid class.
#include <solid.hpp>
Public Types
enum rendering_mode { PLAIN, TEXTURED, WIRED, ZBUFSELECT }
enum render_order { OPAQUE, TRANSLUCID, FLASHRAY, LOCALUSER }
enum display_mode {
NORMAL, VIRTUAL, FLASHY, REFLEXIVE,
PROGRESS
}
Public Member Functions
Solid ()
constructor.
virtual ~Solid ()
destructor.
virtual WObject * object ()
Returns the associated WObject.
virtual void getAbsoluteBB (V3 &bbcent, V3 &bbsize)
Returns a bounding box for this solid.
virtual void getRelativeBB (V3 &bbcent, V3 &bbsize) const
virtual void getDim (V3 &bbsize) const
virtual void getCenter (V3 &bbcent) const
Returns relative bounding-box.
virtual void updateBB (GLfloat az)
Updates BB according to its orientation.
virtual void getMaterials (GLfloat *diff, GLfloat *amb, GLfloat *spe, GLfloat *emi, GLint *shi, GLfloat *alpha)
virtual void setPosition (const M4 &mpos)
Updates the solid position.
virtual void getPosition (M4 &mpos)
Gives solid's position.
virtual void setVisible (bool v)
Sets the solid visible (true) or invisible (false).
virtual bool isVisible ()
Return if the solid should be drawn or not.
virtual bool isOpaque ()
Return if the solid is opaque or not.
virtual void display3D (rendering_mode mode, uint8_t layer)
Issue the OpenGL commands to draw the solid in the given mode.
virtual char * parser (char *l)
Parser commun.
virtual char * parseFrame (char *l)
virtual char * parseShape (char *l)
virtual int statueParser (char *l, V3 &bbmax, V3 &bbmin)
virtual int solidParser (char *l, V3 &bbmax, V3 &bbmin)
virtual uint8_t getFrames () const
Gets the number of frames.
virtual uint8_t getFrame () const
Gets the index of current frames.
virtual void setFrame (uint16_t frame)
Changes the "frame" of the solid (ie its geometry).
virtual bool isBlinking () const
Checks if blinking.
virtual bool toggleBlinking ()
Checks if rendering of a blinking solid must be done.
virtual void setRay (GLint x, GLint y)
Makes a ray between user'eyes and the center of the object.
virtual void resetRay ()
Resets ray.
virtual void setFlashyEdges (const GLfloat *_flashcolor)
Sets the solid edges flashy with this color.
virtual void resetFlashyEdges ()
Resets the solid edges flashy.
virtual void setReflexive (bool flag)
Sets the solid reflexive.
virtual bool isReflexive () const
Checks whether the solid is reflexive.
virtual void setFlary (bool flag)
Sets the solid flary.
virtual bool isFlary () const
Checks whether the solid is flary.
virtual void setFlashyEdges (bool flag)
Sets the solid edges flashy.
virtual char * getFramesNumber (char *l)
Parses frames number.
virtual int displayList (int rendertype)
Renders a solid in display-list.
virtual int displayNormal ()
Renders a normal solid.
virtual int displayReflexive ()
Renders a reflexive solid.
virtual int displayVirtual ()
Renders a reflexive solid.
virtual void displayFlary ()
Renders attached flare to a solid.
virtual int displayFlashy ()
Renders a solid flashy.
virtual void displayRay ()
Displays ray.
virtual char * skipEqual (char *p)
virtual void vr2gl ()
Skips '=' character.
Public Attributes
uint8_t shape
basic shape.
uint8_t numrel
relative solid number.
uint16_t nbframes
number of frames of this solid.
uint16_t frame
frame number.
uint16_t curframe
current frame.
bool framed
flag framed.
bool isflashy
flag flashy.
bool isflashable
flag flashable.
bool isreflexive
flag reflexive.
bool isflary
flag flary.
bool isblinking
flag blinking.
bool blink
flag blink.
GLint ray_dlist
ray display list.
GLfloat flashcolor [3]
flash color.
GLfloat rel [5]
relative position/orientation.
char name [HNAME_LEN]
solid name.
Protected Attributes
class WObject * wobject
WObject parent.
class Texture * texture
GLint * dlists
cached display list.
M4 position
position matrix.
V3 rel_bbcent
relative center of BB.
V3 rel_bbsize
relative half sizes of BB.
V3 abs_bbcent
absolute center of BB.
V3 abs_bbsize
absolute half sizes of BB.
bool is_visible
should this solid be drawn ?.
bool is_opaque
set if the solid is totaly opaque.
GLfloat mat_diffuse [4]
GLfloat mat_ambient [4]
GLfloat mat_specular [4]
GLfloat mat_emission [4]
GLint mat_shininess [1]
GLfloat mat_alpha
GLfloat scale
GLfloat scalex
GLfloat scaley
GLfloat scalez
Private Member Functions
virtual void setFlashable (bool flag)
Sets the solid flashable.
virtual void setBlinking (bool flag)
Sets the solid blinking.
virtual void preDraw (int texid, GLfloat alpha, GLfloat *fog, bool cull=false)
Begins transforms before drawing.
virtual void postDraw (int texid, GLfloat alpha, GLfloat *fog)
Ends transforms after drawing.
virtual void getBB (V3 &max, V3 &min, bool framed) const
Gets BB.
virtual void setBB (GLfloat w, GLfloat d, GLfloat h)
Sets BB.
virtual void testRelative (bool flag)
Makes transforms if relative postion.
virtual void testScale (bool flag)
Makes scaling operations.
virtual void testBlend (bool flag, GLfloat alpha)
Makes blending operations if alpha.
virtual void testFog (bool flag, GLfloat *fog)
Makes fog operations if fog.
virtual void testTexture (bool flag, int texid)
Makes texture binding.
virtual char * getTok (char *l, uint16_t *tok)
virtual void displayMirroredScene ()
Gets current token.
Friends
class WObject
class Texture
Detailed Description
Solid class.
Definition at line 37 of file solid.hpp.
Member Enumeration Documentation
display_mode
enum Solid::display_mode
Enumerator
NORMAL
VIRTUAL
FLASHY
REFLEXIVE
PROGRESS
Definition at line 76 of file solid.hpp.
render_order
enum Solid::render_order
Enumerator
OPAQUE
TRANSLUCID
FLASHRAY
LOCALUSER
Definition at line 68 of file solid.hpp.
rendering_mode
enum Solid::rendering_mode
Enumerator
PLAIN
render surfaces with plain colors.
TEXTURED
render surfaces with their textures.
WIRED
don't render surfaces, only render edges.
ZBUFSELECT
only fill the Z-buffer (for selection).
Definition at line 61 of file solid.hpp.
Constructor & Destructor Documentation
Solid()
Solid::Solid ()
constructor.
Definition at line 287 of file solid.cpp.
References abs_bbcent, abs_bbsize, blink, curframe, dlists, flashcolor, frame, framed, is_opaque, is_visible, isblinking, isflary, isflashable, isflashy, isreflexive, nbframes, new_solid, newV3(), numrel, ray_dlist, rel, rel_bbcent, rel_bbsize, shape, STOK_BOX, and wobject.
~Solid()
Solid::~Solid () virtual
destructor.
Definition at line 316 of file solid.cpp.
References del_solid, dlists, g, Render::removeSolidFromList(), and Global::render.
Member Function Documentation
display3D()
void Solid::display3D (rendering_mode mode, uint8_t layer) virtual
Issue the OpenGL commands to draw the solid in the given mode.
It is called several times with "layer" increasing from 0 to ? in order to allow drawing at different layers.
Definition at line 1385 of file solid.cpp.
References DBG_VGL, displayFlary(), displayFlashy(), displayNormal(), displayRay(), displayReflexive(), FLASHRAY, isBlinking(), isflary, isflashy, isreflexive, isVisible(), LOCALUSER, OPAQUE, ray_dlist, toggleBlinking(), trace2(), TRANSLUCID, and ZBUFSELECT.
displayFlary()
void Solid::displayFlary () virtual
Renders attached flare to a solid.
Definition at line 1474 of file solid.cpp.
References Pos::az, displayNormal(), WObject::flare, localuser, object(), WObject::pos, RAD2DEG, Flare::render(), and vr2gl().
Referenced by display3D().
displayFlashy()
int Solid::displayFlashy () virtual
Renders a solid flashy.
Definition at line 1469 of file solid.cpp.
References displayList(), and FLASHY.
Referenced by display3D().
displayList()
int Solid::displayList (int rendertype = NORMAL) virtual
Renders a solid in display-list.
Definition at line 1492 of file solid.cpp.
References Pos::ax, Pos::ay, Pos::az, curframe, displayMirroredScene(), dlists, error(), flashcolor, FLASHY, g, Render::haveStencil(), WObject::isValid(), User::man, NORMAL, Man::pos, WObject::pos, RAD2DEG, REFLEXIVE, Global::render, WObject::type, USER_TYPE, VIRTUAL, vr2gl(), and wobject.
Referenced by displayFlashy(), displayNormal(), displayReflexive(), and displayVirtual().
displayMirroredScene()
void Solid::displayMirroredScene () private virtual
Gets current token.
Displays the mirrored scene
Definition at line 1603 of file solid.cpp.
References User::android, Android::body, displayVirtual(), g, WObject::getSolid(), User::guy, User::height, localuser, User::man, WObject::pos, RAD2DEG, Body::render(), Global::render, Render::solidList, Pos::x, Pos::y, and Pos::z.
Referenced by displayList().
displayNormal()
int Solid::displayNormal () virtual
Renders a normal solid.
Definition at line 1454 of file solid.cpp.
References displayList(), and NORMAL.
Referenced by display3D(), and displayFlary().
displayRay()
void Solid::displayRay () virtual
Displays ray.
Definition at line 1441 of file solid.cpp.
References ray_dlist.
Referenced by display3D().
displayReflexive()
int Solid::displayReflexive () virtual
Renders a reflexive solid.
Definition at line 1459 of file solid.cpp.
References displayList(), and REFLEXIVE.
Referenced by display3D().
displayVirtual()
int Solid::displayVirtual () virtual
Renders a reflexive solid.
Definition at line 1464 of file solid.cpp.
References displayList(), and VIRTUAL.
Referenced by displayMirroredScene().
getAbsoluteBB()
void Solid::getAbsoluteBB (V3 & bbcent, V3 & bbsize) virtual
Returns a bounding box for this solid.
The bounding box is aligned with the world reference.
Definition at line 1180 of file solid.cpp.
References abs_bbcent, abs_bbsize, MAX, MIN, MulM4V3(), position, rel_bbcent, rel_bbsize, size, and V3::v.
getBB()
void Solid::getBB (V3 & max, V3 & min, bool framed) const private virtual
Gets BB.
Definition at line 1034 of file solid.cpp.
References framed, g, Render::getBB(), and Global::render.
Referenced by solidParser(), and statueParser().
getCenter()
void Solid::getCenter (V3 & bbcent) const virtual
Returns relative bounding-box.
Definition at line 1159 of file solid.cpp.
References rel_bbcent.
getDim()
void Solid::getDim (V3 & bbsize) const virtual
Definition at line 1153 of file solid.cpp.
References dim, and rel_bbsize.
getFrame()
uint8_t Solid::getFrame () const virtual
Gets the index of current frames.
Definition at line 1372 of file solid.cpp.
References curframe.
getFrames()
uint8_t Solid::getFrames () const virtual
Gets the number of frames.
Definition at line 1367 of file solid.cpp.
References nbframes.
getFramesNumber()
char * Solid::getFramesNumber (char * l) virtual
Parses frames number.
Definition at line 352 of file solid.cpp.
References nbframes, WObject::parse(), Parse::parseUInt16(), stringcmp(), and wobject.
Referenced by parser().
getMaterials()
void Solid::getMaterials (GLfloat * diff, GLfloat * amb, GLfloat * spe, GLfloat * emi, GLint * shi, GLfloat * alpha) virtual
Definition at line 1165 of file solid.cpp.
References alpha, mat_alpha, mat_ambient, mat_diffuse, mat_emission, mat_shininess, and mat_specular.
getPosition()
void Solid::getPosition (M4 & mpos) virtual
Gives solid's position.
Definition at line 1234 of file solid.cpp.
References position.
getRelativeBB()
void Solid::getRelativeBB (V3 & bbcent, V3 & bbsize) const virtual
Definition at line 1146 of file solid.cpp.
References rel_bbcent, rel_bbsize, and size.
getTok()
char * Solid::getTok (char * l, uint16_t * tok) private virtual
Definition at line 330 of file solid.cpp.
References error(), skipEqual(), STOK_ERR, stokens, sStokens::tokalias, sStokens::tokid, and sStokens::tokstr.
Referenced by solidParser(), and statueParser().
isBlinking()
bool Solid::isBlinking () const virtual
Checks if blinking.
Definition at line 1342 of file solid.cpp.
References isblinking.
Referenced by display3D().
isFlary()
bool Solid::isFlary () const virtual
Checks whether the solid is flary.
Definition at line 1362 of file solid.cpp.
References isflary.
isOpaque()
bool Solid::isOpaque () virtual
Return if the solid is opaque or not.
Definition at line 1249 of file solid.cpp.
References is_opaque.
Referenced by Vicinity::analyseVisual().
isReflexive()
bool Solid::isReflexive () const virtual
Checks whether the solid is reflexive.
Definition at line 1352 of file solid.cpp.
References isreflexive.
isVisible()
bool Solid::isVisible () virtual
Return if the solid should be drawn or not.
Definition at line 1244 of file solid.cpp.
References is_visible.
Referenced by display3D().
object()
WObject * Solid::object () virtual
Returns the associated WObject.
Definition at line 1217 of file solid.cpp.
References WObject::isValid(), and wobject.
Referenced by displayFlary().
parseFrame()
char * Solid::parseFrame (char * l) virtual
Definition at line 359 of file solid.cpp.
References framed, Parse::nextToken(), WObject::parse(), stringcmp(), and wobject.
Referenced by parser().
parser()
char * Solid::parser (char * l) virtual
Parser commun.
Definition at line 394 of file solid.cpp.
References Render::addSolidInList(), dlists, error(), frame, g, getFramesNumber(), WObject::getInstance(), WObject::haveAction(), IdM4(), nbframes, newV3(), Parse::nextToken(), WObject::parse(), parseFrame(), parseShape(), position, Parse::printNumline(), rel_bbcent, rel_bbsize, Global::render, setFlashable(), shape, solidParser(), statueParser(), STOK_ANDROID, STOK_BBOX, STOK_BOX, STOK_BSPHERE, STOK_CAR, STOK_CIRCLE, STOK_CONE, STOK_CONE_DISK, STOK_CROSS, STOK_DISK, STOK_ELLIPSE, STOK_GUY, STOK_HELIX, STOK_LINE, STOK_MAN, STOK_MODEL, STOK_POINT, STOK_PYRAMID, STOK_RECT, STOK_SPHERE, STOK_SPHERE_DISK, STOK_SPHERE_TORUS, STOK_STATUE, STOK_TEAPOT, STOK_TORUS, STOK_TRIANGLE, STOK_WHEEL, V3::v, and wobject.
Referenced by Parse::parseSolid().
parseShape()
char * Solid::parseShape (char * l) virtual
Definition at line 374 of file solid.cpp.
References error(), WObject::parse(), Parse::parseString(), shape, stokens, stringcmp(), sStokens::tokalias, sStokens::tokid, sStokens::tokstr, and wobject.
Referenced by parser().
postDraw()
void Solid::postDraw (int texid, GLfloat alpha, GLfloat * fog) private virtual
Ends transforms after drawing.
Definition at line 1135 of file solid.cpp.
References alpha, testBlend(), testFog(), testRelative(), testScale(), and testTexture().
Referenced by solidParser().
preDraw()
void Solid::preDraw (int texid, GLfloat alpha, GLfloat * fog, bool cull = false) private virtual
Begins transforms before drawing.
Definition at line 1125 of file solid.cpp.
References alpha, testBlend(), testFog(), testRelative(), testScale(), and testTexture().
Referenced by solidParser().
resetFlashyEdges()
void Solid::resetFlashyEdges () virtual
Resets the solid edges flashy.
Definition at line 1320 of file solid.cpp.
References isflashy.
resetRay()
void Solid::resetRay () virtual
Resets ray.
Definition at line 1294 of file solid.cpp.
References NetObject::declareObjDelta(), localuser, newV3(), WObject::noh, User::PROPRAY, User::ray, and ray_dlist.
setBB()
void Solid::setBB (GLfloat w, GLfloat d, GLfloat h) private virtual
Sets BB.
Definition at line 1040 of file solid.cpp.
References d, g, Global::render, and Render::setBB().
Referenced by solidParser().
setBlinking()
void Solid::setBlinking (bool flag) private virtual
Sets the solid blinking.
Definition at line 1337 of file solid.cpp.
References isblinking.
Referenced by solidParser().
setFlary()
void Solid::setFlary (bool flag) virtual
Sets the solid flary.
Definition at line 1357 of file solid.cpp.
References isflary.
Referenced by Sun::inits(), and Mirage::Mirage().
setFlashable()
void Solid::setFlashable (bool flag) private virtual
Sets the solid flashable.
Definition at line 1304 of file solid.cpp.
References isflashable.
Referenced by parser().
setFlashyEdges() [1/2]
void Solid::setFlashyEdges (bool flag) virtual
Sets the solid edges flashy.
Definition at line 1309 of file solid.cpp.
References isflashy.
setFlashyEdges() [2/2]
void Solid::setFlashyEdges (const GLfloat * _flashcolor) virtual
Sets the solid edges flashy with this color.
Definition at line 1314 of file solid.cpp.
References flashcolor, and isflashy.
setFrame()
void Solid::setFrame (uint16_t frame) virtual
Changes the "frame" of the solid (ie its geometry).
Definition at line 1377 of file solid.cpp.
References curframe, and nbframes.
setPosition()
void Solid::setPosition (const M4 & mpos) virtual
Updates the solid position.
The position is defined by the matrix 4x4 'mpos' which gives the transformation todo on local coords towards world coords.
Definition at line 1229 of file solid.cpp.
References position.
setRay()
void Solid::setRay (GLint x, GLint y) virtual
Makes a ray between user'eyes and the center of the object.
Draws a ray between user'eyes and the object's impact window: +--> x viewport: y | ^ v | y +--> x.
Definition at line 1260 of file solid.cpp.
References color, NetObject::declareObjDelta(), g, Scene::getCoords(), Gui::getScene(), gluUnProject(), Global::gui, User::height, localuser, User::NEAR, newV3(), WObject::noh, WObject::pos, User::PROPRAY, Draw::ray(), User::ray, ray_dlist, Color::white, wobject, Pos::x, Pos::y, and Pos::z.
setReflexive()
void Solid::setReflexive (bool flag) virtual
Sets the solid reflexive.
Definition at line 1347 of file solid.cpp.
References isreflexive.
setVisible()
void Solid::setVisible (bool v) virtual
Sets the solid visible (true) or invisible (false).
Definition at line 1239 of file solid.cpp.
References is_visible.
skipEqual()
char * Solid::skipEqual (char * p) virtual
Definition at line 324 of file solid.cpp.
Referenced by getTok().
solidParser()
int Solid::solidParser (char * l, V3 & bbmax, V3 & bbmin) virtual
draw solids
Definition at line 477 of file solid.cpp.
References Draw::bbox(), Pref::bbox, blink, Draw::box(), Draw::cylinder(), DEF_ALPHA, DEF_CONE_SLICES, DEF_CONE_STACKS, DEF_DISK_LOOPS, DEF_DISK_SLICES, DEF_FOG, DEF_SCALE, DEF_SHININESS, DEF_SPHERE_SLICES, DEF_SPHERE_STACKS, DEF_TORUS_CIRCLES, DEF_TORUS_CYLINDERS, DEF_WHEEL_SPOKES, dim, Draw::disk(), dlist, dlists, Man::draw(), Car::draw(), Teapot::draw(), Draw::ellipse(), error(), Render::first_bbox, frame, g, getBB(), Texture::getFromCache(), getTok(), Draw::helix(), Texture::id, Draw::line(), localuser, M_SQRT1_2, M_SQRT2, User::man, mat_alpha, mat_ambient, mat_diffuse, mat_emission, mat_shininess, mat_specular, newV3(), numrel, Texture::object, WObject::parse(), Parse::parseFloat(), Parse::parseInt(), Parse::parseString(), Parse::parseUInt8(), Parse::parseVector3f(), Parse::parseVector3fv(), Parse::parseVector5f(), Draw::point(), postDraw(), preDraw(), Global::pref, Draw::pyramid(), Draw::rect(), rel, Global::render, scale, scalex, scaley, scalez, setBB(), setBlinking(), shape, Texture::solid, Draw::sphere(), STOK_ALPHA, STOK_AMBIENT, STOK_ANDROID, STOK_BBOX, STOK_BLINK, STOK_BOX, STOK_BSPHERE, STOK_CAR, STOK_CIRCLE, STOK_CIRCLES, STOK_CONE, STOK_CONE_DISK, STOK_CONSTANT_ATTENUAT, STOK_CROSS, STOK_CYLINDERS, STOK_DIFFUSE, STOK_DISK, STOK_ELLIPSE, STOK_EMISSION, STOK_FACE, STOK_FOG, STOK_GUY, STOK_HEIGHT, STOK_HELIX, STOK_LENGTH, STOK_LINE, STOK_LINEAR_ATTENUAT, STOK_MAN, STOK_POINT, STOK_PTSIZE, STOK_PYRAMID, STOK_QUADRATIC_ATTENUAT, STOK_RADIUS, STOK_RADIUS2, STOK_RADIUS3, STOK_RECT, STOK_REL, STOK_SCALE, STOK_SCALEX, STOK_SCALEY, STOK_SCALEZ, STOK_SHININESS, STOK_SIDE, STOK_SIZE, STOK_SLICES, STOK_SOLID, STOK_SPECULAR, STOK_SPHERE, STOK_SPHERE_DISK, STOK_SPHERE_TORUS, STOK_SPOKES, STOK_SPOT_CUTOFF, STOK_SPOT_DIRECTION, STOK_STACKS, STOK_STYLE, STOK_TEAPOT, STOK_TEX_XN, STOK_TEX_XN_R, STOK_TEX_XN_RS, STOK_TEX_XN_RT, STOK_TEX_XP, STOK_TEX_XP_R, STOK_TEX_XP_RS, STOK_TEX_XP_RT, STOK_TEX_YN, STOK_TEX_YN_R, STOK_TEX_YN_RS, STOK_TEX_YN_RT, STOK_TEX_YP, STOK_TEX_YP_R, STOK_TEX_YP_RS, STOK_TEX_YP_RT, STOK_TEX_ZN, STOK_TEX_ZN_R, STOK_TEX_ZN_RS, STOK_TEX_ZN_RT, STOK_TEX_ZP, STOK_TEX_ZP_R, STOK_TEX_ZP_RS, STOK_TEX_ZP_RT, STOK_TEXTURE, STOK_TEXTURE_R, STOK_TEXTURE_RS, STOK_TEXTURE_RT, STOK_THICK, STOK_TORUS, STOK_TRIANGLE, STOK_URL, STOK_WHEEL, STOK_WIDTH, Draw::STYLE_FILL, Texture, texture, Draw::torus(), URL_LEN, and wobject.
Referenced by parser().
statueParser()
int Solid::statueParser (char * l, V3 & bbmax, V3 & bbmin) virtual
Definition at line 933 of file solid.cpp.
References DEF_ALPHA, DEF_SCALE, Md2::displaylist(), dlists, error(), Render::first_bbox, FRAME_MAX, framed, g, getBB(), Texture::getFromCache(), Format::getModelByUrl(), getTok(), Texture::id, mat_alpha, mat_ambient, mat_diffuse, mat_specular, MODEL_MD2, MODEL_OBJ, nbframes, obj, Texture::object, WObject::parse(), Parse::parseFloat(), Parse::parseString(), Parse::parseUInt16(), Parse::parseVector3f(), Global::render, scale, Md2::setScale(), STOK_ALPHA, STOK_AMBIENT, STOK_BEGINFRAME, STOK_DIFFUSE, STOK_ENDFRAME, STOK_MODEL, STOK_SCALE, STOK_SOLID, STOK_SPECULAR, STOK_TEXTURE, STOK_URL, Texture, texture, URL_LEN, and wobject.
Referenced by parser().
testBlend()
void Solid::testBlend (bool flag, GLfloat alpha) private virtual
Makes blending operations if alpha.
Definition at line 1076 of file solid.cpp.
References alpha, and is_opaque.
Referenced by postDraw(), and preDraw().
testFog()
void Solid::testFog (bool flag, GLfloat * fog) private virtual
Makes fog operations if fog.
Definition at line 1093 of file solid.cpp.
Referenced by postDraw(), and preDraw().
testRelative()
void Solid::testRelative (bool flag) private virtual
Makes transforms if relative postion.
Definition at line 1045 of file solid.cpp.
References numrel, RAD2DEG, and rel.
Referenced by postDraw(), and preDraw().
testScale()
void Solid::testScale (bool flag) private virtual
Makes scaling operations.
Definition at line 1062 of file solid.cpp.
References scale, scalex, scaley, and scalez.
Referenced by postDraw(), and preDraw().
testTexture()
void Solid::testTexture (bool flag, int texid) private virtual
Makes texture binding.
Definition at line 1110 of file solid.cpp.
Referenced by postDraw(), and preDraw().
toggleBlinking()
bool Solid::toggleBlinking () virtual
Checks if rendering of a blinking solid must be done.
Definition at line 1325 of file solid.cpp.
References blink.
Referenced by display3D().
updateBB()
void Solid::updateBB (GLfloat az) virtual
Updates BB according to its orientation.
Definition at line 1211 of file solid.cpp.
References g, Global::render, and Render::updateBB().
vr2gl()
void Solid::vr2gl () virtual
Skips '=' character.
Transposes vreng coordinates in opengl coordinates.
Definition at line 1434 of file solid.cpp.
References M4toV16(), and position.
Referenced by displayFlary(), and displayList().
Friends And Related Function Documentation
Texture
friend class Texture friend
Definition at line 39 of file solid.hpp.
Referenced by solidParser(), and statueParser().
WObject
friend class WObject friend
Definition at line 38 of file solid.hpp.
Member Data Documentation
abs_bbcent
V3 Solid::abs_bbcent protected
absolute center of BB.
Definition at line 48 of file solid.hpp.
Referenced by getAbsoluteBB(), and Solid().
abs_bbsize
V3 Solid::abs_bbsize protected
absolute half sizes of BB.
Definition at line 49 of file solid.hpp.
Referenced by getAbsoluteBB(), and Solid().
blink
bool Solid::blink
flag blink.
Definition at line 95 of file solid.hpp.
Referenced by Solid(), solidParser(), and toggleBlinking().
curframe
uint16_t Solid::curframe
current frame.
Definition at line 88 of file solid.hpp.
Referenced by displayList(), getFrame(), setFrame(), and Solid().
dlists
GLint* Solid::dlists protected
cached display list.
Definition at line 44 of file solid.hpp.
Referenced by displayList(), parser(), Solid(), solidParser(), statueParser(), and ~Solid().
flashcolor
GLfloat Solid::flashcolor[3]
flash color.
Definition at line 97 of file solid.hpp.
Referenced by displayList(), setFlashyEdges(), and Solid().
frame
uint16_t Solid::frame
frame number.
Definition at line 87 of file solid.hpp.
Referenced by parser(), Solid(), and solidParser().
framed
bool Solid::framed
flag framed.
Definition at line 89 of file solid.hpp.
Referenced by getBB(), parseFrame(), Solid(), and statueParser().
is_opaque
bool Solid::is_opaque protected
set if the solid is totaly opaque.
Definition at line 51 of file solid.hpp.
Referenced by isOpaque(), Solid(), and testBlend().
is_visible
bool Solid::is_visible protected
should this solid be drawn ?.
Definition at line 50 of file solid.hpp.
Referenced by isVisible(), setVisible(), and Solid().
isblinking
bool Solid::isblinking
flag blinking.
Definition at line 94 of file solid.hpp.
Referenced by isBlinking(), setBlinking(), and Solid().
isflary
bool Solid::isflary
flag flary.
Definition at line 93 of file solid.hpp.
Referenced by display3D(), isFlary(), setFlary(), and Solid().
isflashable
bool Solid::isflashable
flag flashable.
Definition at line 91 of file solid.hpp.
Referenced by setFlashable(), and Solid().
isflashy
bool Solid::isflashy
flag flashy.
Definition at line 90 of file solid.hpp.
Referenced by display3D(), resetFlashyEdges(), setFlashyEdges(), and Solid().
isreflexive
bool Solid::isreflexive
flag reflexive.
Definition at line 92 of file solid.hpp.
Referenced by display3D(), isReflexive(), setReflexive(), and Solid().
mat_alpha
GLfloat Solid::mat_alpha protected
Definition at line 57 of file solid.hpp.
Referenced by getMaterials(), solidParser(), and statueParser().
mat_ambient
GLfloat Solid::mat_ambient[4] protected
Definition at line 53 of file solid.hpp.
Referenced by getMaterials(), solidParser(), and statueParser().
mat_diffuse
GLfloat Solid::mat_diffuse[4] protected
Definition at line 52 of file solid.hpp.
Referenced by getMaterials(), solidParser(), and statueParser().
mat_emission
GLfloat Solid::mat_emission[4] protected
Definition at line 55 of file solid.hpp.
Referenced by getMaterials(), and solidParser().
mat_shininess
GLint Solid::mat_shininess[1] protected
Definition at line 56 of file solid.hpp.
Referenced by getMaterials(), and solidParser().
mat_specular
GLfloat Solid::mat_specular[4] protected
Definition at line 54 of file solid.hpp.
Referenced by getMaterials(), solidParser(), and statueParser().
name
char Solid::name[HNAME_LEN]
solid name.
Definition at line 99 of file solid.hpp.
nbframes
uint16_t Solid::nbframes
number of frames of this solid.
Definition at line 86 of file solid.hpp.
Referenced by getFrames(), getFramesNumber(), parser(), setFrame(), Solid(), and statueParser().
numrel
uint8_t Solid::numrel
relative solid number.
Definition at line 85 of file solid.hpp.
Referenced by WObject::addSolid(), Solid(), solidParser(), and testRelative().
position
M4 Solid::position protected
position matrix.
Definition at line 45 of file solid.hpp.
Referenced by getAbsoluteBB(), getPosition(), parser(), setPosition(), and vr2gl().
ray_dlist
GLint Solid::ray_dlist
ray display list.
Definition at line 96 of file solid.hpp.
Referenced by display3D(), displayRay(), User::get_ray(), resetRay(), setRay(), and Solid().
rel
GLfloat Solid::rel[5]
relative position/orientation.
Definition at line 98 of file solid.hpp.
Referenced by Solid(), solidParser(), and testRelative().
rel_bbcent
V3 Solid::rel_bbcent protected
relative center of BB.
Definition at line 46 of file solid.hpp.
Referenced by getAbsoluteBB(), getCenter(), getRelativeBB(), parser(), and Solid().
rel_bbsize
V3 Solid::rel_bbsize protected
relative half sizes of BB.
Definition at line 47 of file solid.hpp.
Referenced by getAbsoluteBB(), getDim(), getRelativeBB(), parser(), and Solid().
scale
GLfloat Solid::scale protected
Definition at line 58 of file solid.hpp.
Referenced by solidParser(), statueParser(), and testScale().
scalex
GLfloat Solid::scalex protected
Definition at line 58 of file solid.hpp.
Referenced by solidParser(), and testScale().
scaley
GLfloat Solid::scaley protected
Definition at line 58 of file solid.hpp.
Referenced by solidParser(), and testScale().
scalez
GLfloat Solid::scalez protected
Definition at line 58 of file solid.hpp.
Referenced by solidParser(), and testScale().
shape
uint8_t Solid::shape
basic shape.
Definition at line 84 of file solid.hpp.
Referenced by parser(), parseShape(), Solid(), and solidParser().
texture
class Texture* Solid::texture protected
Definition at line 43 of file solid.hpp.
Referenced by solidParser(), and statueParser().
wobject
class WObject* Solid::wobject protected
WObject parent.
Definition at line 42 of file solid.hpp.
Referenced by WObject::addSolid(), displayList(), getFramesNumber(), object(), parseFrame(), parser(), parseShape(), setRay(), Solid(), solidParser(), and statueParser().
The documentation for this class was generated from the following files:
src/vgl/solid.hpp
src/vgl/solid.cpp