VREng: Avi Class Reference
Avi Class Reference
Avi class.
#include <avi.hpp>
Public Member Functions
Avi ()
Avi (const char *url)
virtual ~Avi ()
virtual void write_header (int width, int height, int norm, int audio, int stereo, int size, int rate)
virtual void add_frame (const char *jpeg_data, int32_t length)
virtual void add_audio (const char *audio_data, int32_t length)
virtual FILE * getInfos (uint16_t *_width, uint16_t *_height, float *_fps) const
virtual FILE * getFile () const
virtual int32_t read_header ()
virtual int32_t read_data (uint8_t *vidbuf, uint32_t max_vid, int32_t *retlen)
virtual int32_t read_data (uint8_t *vidbuf, uint32_t max_vid, uint8_t *audbuf, uint32_t max_aud, int32_t *retlen)
Static Public Member Functions
static void httpReader (void *_avi, class Http *http)
Private Member Functions
virtual const char * getUrl () const
virtual void defaults ()
virtual void download (const char *url)
virtual int32_t tell (int fd)
virtual void out4cc (const char *s)
virtual void outlong (int32_t n)
virtual void outshrt (int32_t n)
virtual void start_list (const char *name)
virtual void finish_list (const char *name)
virtual void open_output_file (const char *filename)
Private Attributes
FILE * file
char * url
uint32_t frames
uint32_t audio_samples
uint32_t n_idx
int idx [MAXIDX]
char list_name [MAX_LIST_DEPTH][4]
uint32_t list_pos [MAX_LIST_DEPTH]
uint32_t list_depth
double fps
uint16_t width
uint16_t height
uint16_t a_chans
uint16_t a_rate
uint16_t a_bits
Detailed Description
Avi class.
Definition at line 82 of file avi.hpp.
Constructor & Destructor Documentation
Avi() [1/2]
Avi::Avi ()
Definition at line 67 of file avi.cpp.
References defaults().
Avi() [2/2]
Avi::Avi (const char * url)
Definition at line 72 of file avi.cpp.
References defaults(), and download().
~Avi()
Avi::~Avi () virtual
Definition at line 78 of file avi.cpp.
References File::closeFile(), file, and url.
Member Function Documentation
add_audio()
void Avi::add_audio (const char * audio_data, int32_t length) virtual
Definition at line 600 of file avi.cpp.
References audio_samples, error(), file, idx, MAKEFOURCC, MAXIDX, n_idx, out4cc(), and outlong().
add_frame()
void Avi::add_frame (const char * jpeg_data, int32_t length) virtual
Definition at line 583 of file avi.cpp.
References error(), file, frames, idx, MAKEFOURCC, MAXIDX, n_idx, out4cc(), and outlong().
defaults()
void Avi::defaults () private virtual
Definition at line 51 of file avi.cpp.
References a_bits, a_chans, a_rate, audio_samples, file, fps, frames, height, list_depth, n_idx, url, and width.
Referenced by Avi().
download()
void Avi::download (const char * url) private virtual
Definition at line 87 of file avi.cpp.
References Http::httpOpen(), httpReader(), and url.
Referenced by Avi().
finish_list()
void Avi::finish_list (const char * name) private virtual
Definition at line 387 of file avi.cpp.
References error(), file, list_depth, list_name, list_pos, and outlong().
Referenced by write_header().
getFile()
FILE * Avi::getFile () const virtual
Definition at line 108 of file avi.cpp.
References file.
getInfos()
FILE * Avi::getInfos (uint16_t * _width, uint16_t * _height, float * _fps) const virtual
Definition at line 113 of file avi.cpp.
References file, fps, height, and width.
Referenced by Movie::aviInit().
getUrl()
const char * Avi::getUrl () const private virtual
Definition at line 94 of file avi.cpp.
References url.
Referenced by httpReader().
httpReader()
void Avi::httpReader (void * _avi, class Http * http) static
Definition at line 99 of file avi.cpp.
References file, getUrl(), and Cache::openCache().
Referenced by download().
open_output_file()
void Avi::open_output_file (const char * filename) private virtual
Definition at line 406 of file avi.cpp.
References DATASTART, error(), file, File::openFile(), and start_list().
out4cc()
void Avi::out4cc (const char * s) private virtual
Definition at line 356 of file avi.cpp.
References file.
Referenced by add_audio(), add_frame(), start_list(), and write_header().
outlong()
void Avi::outlong (int32_t n) private virtual
Definition at line 361 of file avi.cpp.
References file.
Referenced by add_audio(), add_frame(), finish_list(), start_list(), and write_header().
outshrt()
void Avi::outshrt (int32_t n) private virtual
Definition at line 366 of file avi.cpp.
References file.
Referenced by write_header().
read_data() [1/2]
int Avi::read_data (uint8_t * vidbuf, uint32_t max_vid, int32_t * retlen) virtual
Definition at line 248 of file avi.cpp.
References error(), file, MAKEFOURCC, and SWAPL.
Referenced by Movie::changePermanent().
read_data() [2/2]
int Avi::read_data (uint8_t * vidbuf, uint32_t max_vid, uint8_t * audbuf, uint32_t max_aud, int32_t * retlen) virtual
Definition at line 295 of file avi.cpp.
References error(), file, MAKEFOURCC, and SWAPL.
read_header()
int32_t Avi::read_header () virtual
Definition at line 127 of file avi.cpp.
References a_bits, a_chans, a_rate, ERR_NO_AVI, ERR_NO_MJPG, ERR_NO_VIDS, error(), file, fps, height, LISTtag, MAKEFOURCC, RIFFtag, strftag, strhtag, SWAPL, and width.
Referenced by Movie::aviInit().
start_list()
void Avi::start_list (const char * name) private virtual
Definition at line 373 of file avi.cpp.
References error(), file, list_depth, list_name, list_pos, MAX_LIST_DEPTH, out4cc(), and outlong().
Referenced by open_output_file(), and write_header().
tell()
int32_t Avi::tell (int fd) private virtual
Definition at line 351 of file avi.cpp.
References file.
write_header()
void Avi::write_header (int width, int height, int norm, int audio, int stereo, int size, int rate) virtual
Definition at line 427 of file avi.cpp.
References audio_samples, File::closeFile(), DATASTART, error(), file, finish_list(), frames, height, idx, n_idx, out4cc(), outlong(), outshrt(), size, start_list(), VIDEO_MODE_PAL, WAVE_FORMAT_PCM, and width.
Member Data Documentation
a_bits
uint16_t Avi::a_bits private
Definition at line 123 of file avi.hpp.
Referenced by defaults(), and read_header().
a_chans
uint16_t Avi::a_chans private
Definition at line 121 of file avi.hpp.
Referenced by defaults(), and read_header().
a_rate
uint16_t Avi::a_rate private
Definition at line 122 of file avi.hpp.
Referenced by defaults(), and read_header().
audio_samples
uint32_t Avi::audio_samples private
Definition at line 107 of file avi.hpp.
Referenced by add_audio(), defaults(), and write_header().
file
FILE* Avi::file private
Definition at line 104 of file avi.hpp.
Referenced by add_audio(), add_frame(), defaults(), finish_list(), getFile(), getInfos(), httpReader(), open_output_file(), out4cc(), outlong(), outshrt(), read_data(), read_header(), start_list(), tell(), write_header(), and ~Avi().
fps
double Avi::fps private
Definition at line 118 of file avi.hpp.
Referenced by defaults(), getInfos(), and read_header().
frames
uint32_t Avi::frames private
Definition at line 106 of file avi.hpp.
Referenced by add_frame(), defaults(), and write_header().
height
uint16_t Avi::height private
Definition at line 120 of file avi.hpp.
Referenced by defaults(), getInfos(), read_header(), and write_header().
idx
int Avi::idx[MAXIDX] private
Definition at line 110 of file avi.hpp.
Referenced by add_audio(), add_frame(), and write_header().
list_depth
uint32_t Avi::list_depth private
Definition at line 115 of file avi.hpp.
Referenced by defaults(), finish_list(), and start_list().
list_name
char Avi::list_name[MAX_LIST_DEPTH][4] private
Definition at line 113 of file avi.hpp.
Referenced by finish_list(), and start_list().
list_pos
uint32_t Avi::list_pos[MAX_LIST_DEPTH] private
Definition at line 114 of file avi.hpp.
Referenced by finish_list(), and start_list().
n_idx
uint32_t Avi::n_idx private
Definition at line 108 of file avi.hpp.
Referenced by add_audio(), add_frame(), defaults(), and write_header().
url
char* Avi::url private
Definition at line 105 of file avi.hpp.
Referenced by defaults(), download(), getUrl(), and ~Avi().
width
uint16_t Avi::width private
Definition at line 119 of file avi.hpp.
Referenced by defaults(), getInfos(), read_header(), and write_header().
The documentation for this class was generated from the following files:
src/texture/avi.hpp
src/texture/avi.cpp