VREng: Flare Class Reference
Flare Class Reference
Flare class.
#include <flare.hpp>
Public Member Functions
Flare ()
constructor
Flare (uint8_t number, float _scale, GLfloat *color)
virtual ~Flare ()
destructor
virtual void setNumber (uint8_t number)
Sets number of flares.
virtual void setScale (float scale)
Sets new scale for flares.
virtual void setColor (GLfloat *color)
Sets unique color for all flares.
virtual void render ()
virtual void render (struct Pos &from)
virtual void render (float *from)
virtual void render (float delta)
virtual void render (float *from, float delta)
Renders flare + shine.
Private Member Functions
virtual void defaults ()
Sets default values.
virtual tFlare set (int type, float location, float scale, const GLfloat *color, float colorScale)
Sets each flare.
virtual void inits ()
Initializes flares.
virtual void setTexture (GLuint texid)
Sets textures.
virtual void loadTextures ()
Load needed textures.
virtual void vnorm (float *vec)
virtual float vdot (float *a, float *b)
virtual void vdiff (float *dst, float *a, float *b)
virtual void vadd (float *dst, float *a, float *b)
virtual void vcopy (float *dst, float *src)
virtual void vscale (float *dst, float *src, float scale)
virtual void vcross (float *cross, const float *v1, const float *v2)
Private Attributes
tFlare flares [16]
array of flares
GLuint * shineTex
texid for shines
GLuint * flareTex
texid for flares
uint8_t num_shine
number of shines
uint8_t num_flares
number of flares
float scale
global scale
Static Private Attributes
static const GLfloat white [3]
static const GLfloat red [3] = {1, 0, 0}
static const GLfloat green [3] = {0, 1, 0}
static const GLfloat blue [3] = {0, 0, 1}
static uint8_t MAX_SHINE = 10
static uint8_t MAX_FLARE = 6
static uint8_t DEF_SCALE = 1
static uint8_t DEF_FLARES = 12
Detailed Description
Flare class.
Definition at line 37 of file flare.hpp.
Constructor & Destructor Documentation
Flare() [1/2]
Flare::Flare ()
constructor
Definition at line 47 of file flare.cpp.
References defaults(), and inits().
Flare() [2/2]
Flare::Flare (uint8_t number, float _scale, GLfloat * color)
Definition at line 54 of file flare.cpp.
References color, DEF_FLARES, defaults(), inits(), num_flares, scale, and setColor().
~Flare()
Flare::~Flare () virtual
destructor
Definition at line 64 of file flare.cpp.
References flareTex, and shineTex.
Member Function Documentation
defaults()
void Flare::defaults () private virtual
Sets default values.
Definition at line 39 of file flare.cpp.
References DEF_FLARES, DEF_SCALE, num_flares, num_shine, and scale.
Referenced by Flare().
inits()
void Flare::inits () private virtual
Initializes flares.
Definition at line 83 of file flare.cpp.
References blue, flares, green, loadTextures(), red, and set().
Referenced by Flare().
loadTextures()
void Flare::loadTextures () private virtual
Load needed textures.
Definition at line 252 of file flare.cpp.
References flareTex, Texture::getFromCache(), MAX_FLARE, MAX_SHINE, setTexture(), shineTex, and URL_LEN.
Referenced by inits().
render() [1/5]
void Flare::render () virtual
Definition at line 123 of file flare.cpp.
Referenced by Solid::displayFlary(), Sun::render(), and render().
render() [2/5]
void Flare::render (float * from) virtual
Definition at line 132 of file flare.cpp.
References render().
render() [3/5]
void Flare::render (float * from, float delta) virtual
Renders flare + shine.
Definition at line 157 of file flare.cpp.
References color, flares, flareTex, localuser, MAX_SHINE, near, num_flares, num_shine, WObject::pos, scale, shineTex, vadd(), vcopy(), vcross(), vdiff(), vdot(), vnorm(), vscale(), Pos::x, Pos::y, and Pos::z.
render() [4/5]
void Flare::render (float delta) virtual
Definition at line 150 of file flare.cpp.
References render().
render() [5/5]
void Flare::render (struct Pos & from) virtual
Definition at line 139 of file flare.cpp.
References render(), Pos::x, Pos::y, and Pos::z.
set()
tFlare Flare::set (int type, float location, float scale, const GLfloat * color, float colorScale) private virtual
Sets each flare.
Definition at line 70 of file flare.cpp.
References tFlare::color, tFlare::loc, tFlare::scale, and tFlare::type.
Referenced by inits().
setColor()
void Flare::setColor (GLfloat * color) virtual
Sets unique color for all flares.
Definition at line 114 of file flare.cpp.
References color, tFlare::color, flares, and num_flares.
Referenced by Sun::changePermanent(), and Flare().
setNumber()
void Flare::setNumber (uint8_t number) virtual
Sets number of flares.
Definition at line 104 of file flare.cpp.
References num_flares.
setScale()
void Flare::setScale (float scale) virtual
Sets new scale for flares.
Definition at line 109 of file flare.cpp.
References scale.
setTexture()
void Flare::setTexture (GLuint texid) private virtual
Sets textures.
Definition at line 235 of file flare.cpp.
References Texture::getEntryById(), Img::height, Texture::img, Img::pixmap, and Img::width.
Referenced by loadTextures().
vadd()
void Flare::vadd (float * dst, float * a, float * b) private virtual
Definition at line 290 of file flare.cpp.
Referenced by render().
vcopy()
void Flare::vcopy (float * dst, float * src) private virtual
Definition at line 297 of file flare.cpp.
References src.
Referenced by render(), and vcross().
vcross()
void Flare::vcross (float * cross, const float * v1, const float * v2) private virtual
Definition at line 311 of file flare.cpp.
References vcopy().
Referenced by render().
vdiff()
void Flare::vdiff (float * dst, float * a, float * b) private virtual
Definition at line 283 of file flare.cpp.
Referenced by render().
vdot()
float Flare::vdot (float * a, float * b) private virtual
Definition at line 278 of file flare.cpp.
Referenced by render().
vnorm()
void Flare::vnorm (float * vec) private virtual
Definition at line 271 of file flare.cpp.
Referenced by render().
vscale()
void Flare::vscale (float * dst, float * src, float scale) private virtual
Definition at line 304 of file flare.cpp.
References scale, and src.
Referenced by render().
Member Data Documentation
blue
const GLfloat Flare::blue = {0, 0, 1} static private
Definition at line 43 of file flare.hpp.
Referenced by inits().
DEF_FLARES
uint8_t Flare::DEF_FLARES = 12 static private
Definition at line 47 of file flare.hpp.
Referenced by defaults(), and Flare().
DEF_SCALE
uint8_t Flare::DEF_SCALE = 1 static private
Definition at line 46 of file flare.hpp.
Referenced by defaults().
flares
tFlare Flare::flares[16] private
array of flares
Definition at line 49 of file flare.hpp.
Referenced by inits(), render(), and setColor().
flareTex
GLuint* Flare::flareTex private
texid for flares
Definition at line 51 of file flare.hpp.
Referenced by loadTextures(), render(), and ~Flare().
green
const GLfloat Flare::green = {0, 1, 0} static private
Definition at line 42 of file flare.hpp.
Referenced by inits().
MAX_FLARE
uint8_t Flare::MAX_FLARE = 6 static private
Definition at line 45 of file flare.hpp.
Referenced by loadTextures().
MAX_SHINE
uint8_t Flare::MAX_SHINE = 10 static private
Definition at line 44 of file flare.hpp.
Referenced by loadTextures(), and render().
num_flares
uint8_t Flare::num_flares private
number of flares
Definition at line 53 of file flare.hpp.
Referenced by defaults(), Flare(), render(), setColor(), and setNumber().
num_shine
uint8_t Flare::num_shine private
number of shines
Definition at line 52 of file flare.hpp.
Referenced by defaults(), and render().
red
const GLfloat Flare::red = {1, 0, 0} static private
Definition at line 41 of file flare.hpp.
Referenced by inits().
scale
float Flare::scale private
global scale
Definition at line 54 of file flare.hpp.
Referenced by defaults(), Flare(), render(), setScale(), and vscale().
shineTex
GLuint* Flare::shineTex private
texid for shines
Definition at line 50 of file flare.hpp.
Referenced by loadTextures(), render(), and ~Flare().
white
const GLfloat Flare::white[3] static private
Definition at line 40 of file flare.hpp.
The documentation for this class was generated from the following files:
src/vgl/flare.hpp
src/vgl/flare.cpp