VREng: Wheel Class Reference
Wheel Class Reference
Wheel class.
#include <wheel.hpp>
Public Member Functions
Wheel (uint8_t teeth, GLfloat r, const GLfloat *color)
constructor.
Wheel ()
constructor.
virtual ~Wheel ()
destructor.
virtual void render ()
Renders wheel.
Static Public Member Functions
static Wheel * current ()
accessor.
Private Member Functions
virtual void defaults ()
Sets default values.
virtual void draw (uint8_t teeth, GLfloat r, const GLfloat *color)
Draws wheel.
virtual void spoke (GLfloat r)
virtual void dial (GLfloat a, GLfloat r, const GLfloat *color)
virtual void needle (uint8_t teeth, GLfloat r)
virtual void needle_displaylist (uint8_t teeth, GLfloat r)
virtual void displaylist (uint8_t teeth, GLfloat r, const GLfloat *color)
Private Attributes
GLint wheel_dlist
GLint needle_dlist
float needle_angle
Detailed Description
Wheel class.
Definition at line 27 of file wheel.hpp.
Constructor & Destructor Documentation
Wheel() [1/2]
Wheel::Wheel (uint8_t teeth, GLfloat r, const GLfloat * color)
constructor.
Definition at line 41 of file wheel.cpp.
References color, defaults(), displaylist(), needle_displaylist(), and pwheel.
Wheel() [2/2]
Wheel::Wheel ()
constructor.
Definition at line 49 of file wheel.cpp.
References color, defaults(), displaylist(), needle_displaylist(), and pwheel.
~Wheel()
Wheel::~Wheel () virtual
destructor.
Definition at line 59 of file wheel.cpp.
References needle_dlist, pwheel, and wheel_dlist.
Member Function Documentation
current()
Wheel * Wheel::current () static
accessor.
Definition at line 67 of file wheel.cpp.
References pwheel.
Referenced by Universe::runWheel().
defaults()
void Wheel::defaults () private virtual
Sets default values.
Definition at line 35 of file wheel.cpp.
References needle_angle.
Referenced by Wheel().
dial()
void Wheel::dial (GLfloat a, GLfloat r, const GLfloat * color) private virtual
Definition at line 89 of file wheel.cpp.
References color, and spoke().
Referenced by draw(), and needle().
displaylist()
void Wheel::displaylist (uint8_t teeth, GLfloat r, const GLfloat * color) private virtual
Definition at line 143 of file wheel.cpp.
References color, draw(), and wheel_dlist.
Referenced by Wheel().
draw()
void Wheel::draw (uint8_t teeth, GLfloat r, const GLfloat * color) private virtual
Draws wheel.
Definition at line 131 of file wheel.cpp.
References color, and dial().
Referenced by displaylist().
needle()
void Wheel::needle (uint8_t teeth, GLfloat r) private virtual
Definition at line 100 of file wheel.cpp.
References dial().
Referenced by needle_displaylist().
needle_displaylist()
void Wheel::needle_displaylist (uint8_t teeth, GLfloat r) private virtual
Definition at line 122 of file wheel.cpp.
References needle(), and needle_dlist.
Referenced by Wheel().
render()
void Wheel::render () virtual
Renders wheel.
Definition at line 151 of file wheel.cpp.
References g, Pref::height3D, needle_angle, needle_dlist, Global::pref, wheel_dlist, and Pref::width3D.
Referenced by Universe::runWheel().
spoke()
void Wheel::spoke (GLfloat r) private virtual
Definition at line 73 of file wheel.cpp.
Referenced by dial().
Member Data Documentation
needle_angle
float Wheel::needle_angle private
Definition at line 32 of file wheel.hpp.
Referenced by defaults(), and render().
needle_dlist
GLint Wheel::needle_dlist private
Definition at line 31 of file wheel.hpp.
Referenced by needle_displaylist(), render(), and ~Wheel().
wheel_dlist
GLint Wheel::wheel_dlist private
Definition at line 30 of file wheel.hpp.
Referenced by displaylist(), render(), and ~Wheel().
The documentation for this class was generated from the following files:
src/vgl/wheel.hpp
src/vgl/wheel.cpp