VREng: Grid Class Reference
Grid Class Reference
Grid class.
#include <grid.hpp>
Public Member Functions
Grid ()
Constructor.
virtual ~Grid ()
virtual void render ()
Destructor.
virtual void init (int depth, int width, int height)
Intilialization.
virtual class UBox * buildBox ()
Builds a dialog box.
virtual void toggleGrid ()
virtual void toggleGrid3d ()
virtual void toggleOverlap ()
virtual void toggleBehavior (int new_behavior)
Static Public Member Functions
static Grid * grid ()
Returns grid instance.
Private Types
enum { STICK, FOLLOW, SFOLLOW }
Private Member Functions
virtual void setWidth (UEvent &v)
virtual void setHeight (UEvent &v)
virtual void setDepth (UEvent &v)
virtual void setRed (UEvent &v)
virtual void setGreen (UEvent &v)
virtual void setBlue (UEvent &v)
virtual void setPosX (UEvent &v)
virtual void setPosY (UEvent &v)
virtual void setPosZ (UEvent &v)
virtual void setRotX (UEvent &v)
virtual void setRotY (UEvent &v)
virtual void setRotZ (UEvent &v)
virtual void draw ()
draws grids
virtual void defaults ()
default values
virtual void genScrollbar ()
Private Attributes
bool visible
GLint dlist
gl display list
float posx
float posy
float posz
float rotx
float roty
float rotz
int grid_width
int grid_depth
int grid_height
int inter_width
int inter_depth
int inter_height
GLfloat red
GLfloat green
GLfloat blue
GLfloat alpha
int behavior
grid behavior
bool overlap
loverlapped grid
bool grid_3d
grid 3D
GLfloat glmat [16]
default matrix projection
UScrollbar * s_width
UScrollbar * s_height
UScrollbar * s_depth
UScrollbar * s_red
UScrollbar * s_green
UScrollbar * s_blue
UScrollbar * s_x
UScrollbar * s_y
UScrollbar * s_z
UScrollbar * s_rotx
UScrollbar * s_roty
UScrollbar * s_rotz
Static Private Attributes
static const uint8_t GRID_WIDTH = 20
static const uint8_t GRID_DEPTH = 20
static const uint8_t GRID_HEIGHT = 10
static const uint8_t GRID_SLICE = 5
static const uint8_t SCROLL_MAX = 100
static const uint8_t SCROLL_INCR = 1
Detailed Description
Grid class.
3D help to visualize, displays grids 2D/3D
Definition at line 32 of file grid.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
STICK
FOLLOW
SFOLLOW
Definition at line 58 of file grid.hpp.
Constructor & Destructor Documentation
Grid()
Grid::Grid ()
Constructor.
Definition at line 47 of file grid.cpp.
References behavior, dlist, grid_3d, overlap, STICK, and visible.
~Grid()
virtual Grid::~Grid () inline virtual
Definition at line 68 of file grid.hpp.
Member Function Documentation
buildBox()
UBox * Grid::buildBox () virtual
Builds a dialog box.
Called by the GUI.
Definition at line 236 of file grid.cpp.
References behavior, defaults(), FOLLOW, genScrollbar(), s_blue, s_depth, s_green, s_height, s_red, s_rotx, s_roty, s_rotz, s_width, s_x, s_y, s_z, SFOLLOW, STICK, toggleBehavior(), toggleGrid(), toggleGrid3d(), and toggleOverlap().
defaults()
void Grid::defaults () private virtual
default values
Definition at line 56 of file grid.cpp.
References alpha, blue, green, GRID_HEIGHT, grid_height, GRID_SLICE, inter_depth, inter_height, inter_width, posx, posy, posz, red, rotx, roty, and rotz.
Referenced by buildBox(), and init().
draw()
void Grid::draw () private virtual
draws grids
Definition at line 88 of file grid.cpp.
References alpha, blue, dlist, g, Gui::getScene(), green, grid_3d, grid_depth, grid_height, grid_width, Global::gui, inter_depth, inter_height, inter_width, Scene::isInitialized(), and red.
Referenced by init(), setBlue(), setDepth(), setGreen(), setHeight(), setRed(), setWidth(), and toggleGrid3d().
genScrollbar()
void Grid::genScrollbar () private virtual
Definition at line 178 of file grid.cpp.
References GRID_SLICE, s_blue, s_depth, s_green, s_height, s_red, s_rotx, s_roty, s_rotz, s_width, s_x, s_y, s_z, SCROLL_MAX, setBlue(), setDepth(), setGreen(), setHeight(), setPosX(), setPosY(), setPosZ(), setRed(), setRotX(), setRotY(), setRotZ(), and setWidth().
Referenced by buildBox().
grid()
Grid * Grid::grid () static
Returns grid instance.
Definition at line 41 of file grid.cpp.
References _grid.
Referenced by World::compute(), Widgets::createGridDialog(), Render::render(), and toggleGridCB().
init()
void Grid::init (int depth, int width, int height) virtual
Intilialization.
Definition at line 67 of file grid.cpp.
References defaults(), draw(), glmat, grid_depth, and grid_width.
Referenced by World::compute().
render()
void Grid::render () virtual
Destructor.
Renders grid
Definition at line 138 of file grid.cpp.
References behavior, dlist, glmat, overlap, posx, posy, posz, rotx, roty, rotz, SFOLLOW, STICK, and visible.
Referenced by Render::render().
setBlue()
void Grid::setBlue (UEvent & v) private virtual
Definition at line 351 of file grid.cpp.
References blue, draw(), and SCROLL_MAX.
Referenced by genScrollbar().
setDepth()
void Grid::setDepth (UEvent & v) private virtual
Definition at line 334 of file grid.cpp.
References draw(), and inter_depth.
Referenced by genScrollbar().
setGreen()
void Grid::setGreen (UEvent & v) private virtual
Definition at line 346 of file grid.cpp.
References draw(), green, and SCROLL_MAX.
Referenced by genScrollbar().
setHeight()
void Grid::setHeight (UEvent & v) private virtual
Definition at line 327 of file grid.cpp.
References draw(), and inter_height.
Referenced by genScrollbar().
setPosX()
void Grid::setPosX (UEvent & v) private virtual
Definition at line 357 of file grid.cpp.
References posx.
Referenced by genScrollbar().
setPosY()
void Grid::setPosY (UEvent & v) private virtual
Definition at line 361 of file grid.cpp.
References posy.
Referenced by genScrollbar().
setPosZ()
void Grid::setPosZ (UEvent & v) private virtual
Definition at line 365 of file grid.cpp.
References posz.
Referenced by genScrollbar().
setRed()
void Grid::setRed (UEvent & v) private virtual
Definition at line 341 of file grid.cpp.
References draw(), red, and SCROLL_MAX.
Referenced by genScrollbar().
setRotX()
void Grid::setRotX (UEvent & v) private virtual
Definition at line 370 of file grid.cpp.
References rotx.
Referenced by genScrollbar().
setRotY()
void Grid::setRotY (UEvent & v) private virtual
Definition at line 374 of file grid.cpp.
References roty.
Referenced by genScrollbar().
setRotZ()
void Grid::setRotZ (UEvent & v) private virtual
Definition at line 378 of file grid.cpp.
References rotz.
Referenced by genScrollbar().
setWidth()
void Grid::setWidth (UEvent & v) private virtual
Definition at line 319 of file grid.cpp.
References draw(), and inter_width.
Referenced by genScrollbar().
toggleBehavior()
void Grid::toggleBehavior (int new_behavior) virtual
Definition at line 303 of file grid.cpp.
References behavior.
Referenced by buildBox().
toggleGrid()
void Grid::toggleGrid () virtual
Definition at line 309 of file grid.cpp.
References visible.
Referenced by buildBox(), and toggleGridCB().
toggleGrid3d()
void Grid::toggleGrid3d () virtual
Definition at line 312 of file grid.cpp.
References draw(), and grid_3d.
Referenced by buildBox(), and toggleGridCB().
toggleOverlap()
void Grid::toggleOverlap () virtual
Definition at line 306 of file grid.cpp.
References overlap.
Referenced by buildBox(), and toggleGridCB().
Member Data Documentation
alpha
GLfloat Grid::alpha private
Definition at line 52 of file grid.hpp.
Referenced by defaults(), and draw().
behavior
int Grid::behavior private
grid behavior
Definition at line 53 of file grid.hpp.
Referenced by buildBox(), Grid(), render(), and toggleBehavior().
blue
GLfloat Grid::blue private
Definition at line 52 of file grid.hpp.
Referenced by defaults(), draw(), and setBlue().
dlist
GLint Grid::dlist private
gl display list
Definition at line 43 of file grid.hpp.
Referenced by draw(), Grid(), and render().
glmat
GLfloat Grid::glmat[16] private
default matrix projection
Definition at line 56 of file grid.hpp.
Referenced by init(), and render().
green
GLfloat Grid::green private
Definition at line 52 of file grid.hpp.
Referenced by defaults(), draw(), and setGreen().
grid_3d
bool Grid::grid_3d private
grid 3D
Definition at line 55 of file grid.hpp.
Referenced by draw(), Grid(), and toggleGrid3d().
GRID_DEPTH
const uint8_t Grid::GRID_DEPTH = 20 static private
Definition at line 36 of file grid.hpp.
grid_depth
int Grid::grid_depth private
Definition at line 50 of file grid.hpp.
Referenced by draw(), and init().
GRID_HEIGHT
const uint8_t Grid::GRID_HEIGHT = 10 static private
Definition at line 37 of file grid.hpp.
Referenced by defaults().
grid_height
int Grid::grid_height private
Definition at line 50 of file grid.hpp.
Referenced by defaults(), and draw().
GRID_SLICE
const uint8_t Grid::GRID_SLICE = 5 static private
Definition at line 38 of file grid.hpp.
Referenced by defaults(), and genScrollbar().
GRID_WIDTH
const uint8_t Grid::GRID_WIDTH = 20 static private
Definition at line 35 of file grid.hpp.
grid_width
int Grid::grid_width private
Definition at line 50 of file grid.hpp.
Referenced by draw(), and init().
inter_depth
int Grid::inter_depth private
Definition at line 51 of file grid.hpp.
Referenced by defaults(), draw(), and setDepth().
inter_height
int Grid::inter_height private
Definition at line 51 of file grid.hpp.
Referenced by defaults(), draw(), and setHeight().
inter_width
int Grid::inter_width private
Definition at line 51 of file grid.hpp.
Referenced by defaults(), draw(), and setWidth().
overlap
bool Grid::overlap private
loverlapped grid
Definition at line 54 of file grid.hpp.
Referenced by Grid(), render(), and toggleOverlap().
posx
float Grid::posx private
Definition at line 44 of file grid.hpp.
Referenced by defaults(), render(), and setPosX().
posy
float Grid::posy private
Definition at line 45 of file grid.hpp.
Referenced by defaults(), render(), and setPosY().
posz
float Grid::posz private
Definition at line 46 of file grid.hpp.
Referenced by defaults(), render(), and setPosZ().
red
GLfloat Grid::red private
Definition at line 52 of file grid.hpp.
Referenced by defaults(), draw(), and setRed().
rotx
float Grid::rotx private
Definition at line 47 of file grid.hpp.
Referenced by defaults(), render(), and setRotX().
roty
float Grid::roty private
Definition at line 48 of file grid.hpp.
Referenced by defaults(), render(), and setRotY().
rotz
float Grid::rotz private
Definition at line 49 of file grid.hpp.
Referenced by defaults(), render(), and setRotZ().
s_blue
UScrollbar * Grid::s_blue private
Definition at line 89 of file grid.hpp.
Referenced by buildBox(), and genScrollbar().
s_depth
UScrollbar * Grid::s_depth private
Definition at line 89 of file grid.hpp.
Referenced by buildBox(), and genScrollbar().
s_green
UScrollbar * Grid::s_green private
Definition at line 89 of file grid.hpp.
Referenced by buildBox(), and genScrollbar().
s_height
UScrollbar * Grid::s_height private
Definition at line 89 of file grid.hpp.
Referenced by buildBox(), and genScrollbar().
s_red
UScrollbar * Grid::s_red private
Definition at line 89 of file grid.hpp.
Referenced by buildBox(), and genScrollbar().
s_rotx
UScrollbar * Grid::s_rotx private
Definition at line 90 of file grid.hpp.
Referenced by buildBox(), and genScrollbar().
s_roty
UScrollbar * Grid::s_roty private
Definition at line 90 of file grid.hpp.
Referenced by buildBox(), and genScrollbar().
s_rotz
UScrollbar * Grid::s_rotz private
Definition at line 90 of file grid.hpp.
Referenced by buildBox(), and genScrollbar().
s_width
UScrollbar* Grid::s_width private
Definition at line 89 of file grid.hpp.
Referenced by buildBox(), and genScrollbar().
s_x
UScrollbar * Grid::s_x private
Definition at line 90 of file grid.hpp.
Referenced by buildBox(), and genScrollbar().
s_y
UScrollbar * Grid::s_y private
Definition at line 90 of file grid.hpp.
Referenced by buildBox(), and genScrollbar().
s_z
UScrollbar * Grid::s_z private
Definition at line 90 of file grid.hpp.
Referenced by buildBox(), and genScrollbar().
SCROLL_INCR
const uint8_t Grid::SCROLL_INCR = 1 static private
Definition at line 40 of file grid.hpp.
SCROLL_MAX
const uint8_t Grid::SCROLL_MAX = 100 static private
Definition at line 39 of file grid.hpp.
Referenced by genScrollbar(), setBlue(), setGreen(), and setRed().
visible
bool Grid::visible private
Definition at line 42 of file grid.hpp.
Referenced by Grid(), render(), and toggleGrid().
The documentation for this class was generated from the following files:
src/vgl/grid.hpp
src/vgl/grid.cpp