VREng: Source Class Reference
Source Class Reference
Source class Informations on a RTP source.
#include <source.hpp>
Public Member Functions
Source (uint32_t ssrc)
Constructor: creates a new source.
virtual ~Source ()
destructor
void dump ()
Static Public Member Functions
static Source * getSource (uint32_t ssrc)
finds source by its ssrc else creates a new source
static uint16_t getSourcesNumber ()
static uint16_t incrSourcesNumber ()
static uint16_t decrSourcesNumber ()
static uint16_t getMembersNumber ()
static void dumpAll ()
Public Attributes
uint32_t ssrc
ssrc id
uint32_t extended_max
extented max
uint32_t expected
expected packets
uint32_t lost
lost packets
sourceInfos s
source info
SdesItem sdes
sdes from the source, if we received it
rtcp_sr_t sr
sender report
rtcp_rr_t rr
receiver report
class Source * next
next source
Detailed Description
Source class Informations on a RTP source.
Definition at line 31 of file source.hpp.
Constructor & Destructor Documentation
Source()
Source::Source (uint32_t ssrc)
Constructor: creates a new source.
creates a new Source
Definition at line 39 of file source.cpp.
References expected, extended_max, lost, new_source, next, sdes, SdesItem::si_len, SdesItem::si_next, SdesItem::si_str, SdesItem::si_type, and ssrc.
Referenced by getSource().
~Source()
Source::~Source () virtual
destructor
Source destructor.
Definition at line 92 of file source.cpp.
References del_source.
Member Function Documentation
decrSourcesNumber()
uint16_t Source::decrSourcesNumber () static
Definition at line 107 of file source.cpp.
References sourcesCounter.
Referenced by Session::deleteSourceBySsrc().
dump()
void Source::dump ()
Definition at line 124 of file source.cpp.
References lost, next, RTCP_SDES_END, RTCP_SDES_SOURCE, sdes, SdesItem::si_len, SdesItem::si_next, SdesItem::si_str, SdesItem::si_type, and ssrc.
dumpAll()
void Source::dumpAll () static
Definition at line 142 of file source.cpp.
References Session::getList(), Session::mode, and next.
Referenced by statNetwork().
getMembersNumber()
uint16_t Source::getMembersNumber () static
Definition at line 112 of file source.cpp.
References Session::getList(), Session::mode, and next.
getSource()
Source * Source::getSource (uint32_t ssrc) static
finds source by its ssrc else creates a new source
Definition at line 56 of file source.cpp.
References Channel::current(), DBG_RTP, error(), Session::incrSources(), next, Channel::session, Session::source, Source(), sourcesCounter, ssrc, and trace().
Referenced by Payload::recvPayload(), and Rtp::recvRTCPPacket().
getSourcesNumber()
uint16_t Source::getSourcesNumber () static
Definition at line 97 of file source.cpp.
References sourcesCounter.
Referenced by NetTimeout().
incrSourcesNumber()
uint16_t Source::incrSourcesNumber () static
Definition at line 102 of file source.cpp.
References sourcesCounter.
Referenced by Session::create(), and Session::incrSources().
Member Data Documentation
expected
uint32_t Source::expected
expected packets
Definition at line 35 of file source.hpp.
Referenced by Payload::recvPayload(), and Source().
extended_max
uint32_t Source::extended_max
extented max
Definition at line 34 of file source.hpp.
Referenced by Payload::recvPayload(), and Source().
lost
uint32_t Source::lost
lost packets
Definition at line 36 of file source.hpp.
Referenced by dump(), Payload::recvPayload(), Source(), and Session::stat().
next
class Source* Source::next
next source
Definition at line 41 of file source.hpp.
Referenced by Session::deleteSessionBySsrc(), Session::deleteSourceBySsrc(), dump(), dumpAll(), getMembersNumber(), Rtp::getSdesItemBySsrc(), getSource(), Source(), and Session::stat().
rr
rtcp_rr_t Source::rr
receiver report
Definition at line 40 of file source.hpp.
Referenced by Payload::recvPayload().
s
sourceInfos Source::s
source info
Definition at line 37 of file source.hpp.
Referenced by Session::create(), Payload::recvPayload(), and Session::stat().
sdes
SdesItem Source::sdes
sdes from the source, if we received it
Definition at line 38 of file source.hpp.
Referenced by dump(), Rtp::recvRTCPPacket(), and Source().
sr
rtcp_sr_t Source::sr
sender report
Definition at line 39 of file source.hpp.
Referenced by Rtp::recvRTCPPacket().
ssrc
uint32_t Source::ssrc
ssrc id
Definition at line 33 of file source.hpp.
Referenced by dump(), getSource(), Source(), and Session::stat().
The documentation for this class was generated from the following files:
src/net/source.hpp
src/net/source.cpp