VREng: Axis Class Reference
Axis Class Reference
Axis class.
#include <axis.hpp>
Public Member Functions
Axis ()
Axis (GLfloat length)
Constructors.
virtual ~Axis ()
virtual void render ()
Destructor.
virtual void toggle ()
virtual void init ()
Static Public Member Functions
static Axis * axis ()
Returns axis instance.
Private Member Functions
virtual void draw ()
draws axis
virtual void defaults ()
sets default values
Private Attributes
bool visible
flag visible or not
GLint dlist
gl display list
GLfloat length
axis length
Static Private Attributes
static const GLfloat DEF_LENGTH = .1
static const GLbyte DEF_WIDTH = 2
Detailed Description
Axis class.
Definition at line 28 of file axis.hpp.
Constructor & Destructor Documentation
Axis() [1/2]
Axis::Axis ()
Definition at line 36 of file axis.cpp.
References DEF_LENGTH, defaults(), and length.
Axis() [2/2]
Axis::Axis (GLfloat length)
Constructors.
Definition at line 42 of file axis.cpp.
References defaults(), and length.
~Axis()
virtual Axis::~Axis () inline virtual
Definition at line 43 of file axis.hpp.
Member Function Documentation
axis()
Axis * Axis::axis () static
Returns axis instance.
Definition at line 55 of file axis.cpp.
References _axis.
Referenced by World::compute(), Render::render(), and toggleAxisCB().
defaults()
void Axis::defaults () private virtual
sets default values
Definition at line 48 of file axis.cpp.
References dlist, and visible.
Referenced by Axis().
draw()
void Axis::draw () private virtual
draws axis
Definition at line 65 of file axis.cpp.
References dlist, and length.
Referenced by init().
init()
void Axis::init () virtual
Definition at line 60 of file axis.cpp.
References draw().
Referenced by World::compute().
render()
void Axis::render () virtual
Destructor.
Renders axis
Definition at line 114 of file axis.cpp.
References DEF_WIDTH, dlist, and visible.
Referenced by Render::render().
toggle()
void Axis::toggle () virtual
Definition at line 134 of file axis.cpp.
References visible.
Referenced by toggleAxisCB().
Member Data Documentation
DEF_LENGTH
const GLfloat Axis::DEF_LENGTH = .1 static private
Definition at line 31 of file axis.hpp.
Referenced by Axis().
DEF_WIDTH
const GLbyte Axis::DEF_WIDTH = 2 static private
Definition at line 32 of file axis.hpp.
Referenced by render().
dlist
GLint Axis::dlist private
gl display list
Definition at line 35 of file axis.hpp.
Referenced by defaults(), draw(), and render().
length
GLfloat Axis::length private
axis length
Definition at line 36 of file axis.hpp.
Referenced by Axis(), and draw().
visible
bool Axis::visible private
flag visible or not
Definition at line 34 of file axis.hpp.
Referenced by defaults(), render(), and toggle().
The documentation for this class was generated from the following files:
src/vgl/axis.hpp
src/vgl/axis.cpp