VREng: Render Class Reference
Render Class Reference
Render class.
#include <render.hpp>
Classes
struct sCamera
Camera handling.
Public Types
enum view_mode {
VIEW_FIRST_PERSON, VIEW_THIRD_PERSON, VIEW_THIRD_PERSON_FAR, VIEW_VERTICAL,
VIEW_VERTICAL_FAR, VIEW_GROUND_LEVEL, VIEW_TURN_AROUND, VIEW_WIRED,
VIEW_SCISSOR, VIEW_NUMBER
}
Public Member Functions
Render ()
Constructor.
void config (bool _quality)
Initialization.
GLint haveDepth ()
GLint haveTextures ()
GLint haveStencil ()
GLint haveClips ()
Checks buffers.
void render ()
Renders the current scene in the current buffer.
void minirender ()
‍**< Issue the OpenGL commands to draw the solid in the given mode.
std::list< Solid * > getSolidList ()
return the rendering solid list.
void addSolidInList (Solid *solid)
add solid in rendering list.
void removeSolidFromList (Solid *solid)
remove solid from rendering list.
void getBB (V3 &bbmax, V3 &bbmin, bool _framed)
Gets min/max BB.
void setBB (GLfloat w, GLfloat d, GLfloat h)
void setBB (const GLfloat *v)
Sets min/max BB.
void updateBB (GLfloat az)
Updates BB according to its orientation.
void setViewMode (uint8_t mode)
Sets the view mode.
uint8_t getViewMode () const
Gets the current view mode.
void switchViewMap ()
Switchs the view map.
void setPitch (GLfloat angle)
Sets the pitch angle.
void camera ()
Repaint.
void setCameraPosition (M4 *vr_mat)
Sets camera position: Matrix given the camera position in the world, specify the orthogonal transformation to apply on world coordoninates to screen coordoninates.
void cameraProjection (GLfloat fovy, GLfloat near, GLfloat far)
Projection definition.
void computeCameraProjection ()
void calculateFov (GLfloat x, GLfloat y, GLfloat z, GLfloat az, char *filname)
calculate the FOV of the user on the position x,y,z and az.
void setCameraScissor (GLfloat posx, GLfloat posy, GLfloat posz, GLfloat rotz)
move the intelligente satellite camera to the good position.
void setFlash ()
accessor to flash.
void setAllTypeFlashy (char *object_type, int typeflash)
enable flashy for all same type object.
V3 getMapUserPos ()
return the x,y position of the user on the map and z is a bool what say if map is on/off.
uint16_t getBufferSelection (GLint x, GLint y, GLint zdepth)
Returns the solid's num displayed in (x,y) on the screen.
V3 getVisiblePosition (WObject *po)
get the 3D position of the object on the user screen.
WObject ** getVisibleTypedObjects (char **listetype, int nbr, int *nbrElemts)
Get the object list where each object have a type present in the given list.
WObject ** getDrawedObjects (int *nbr)
get All drawed Objects on the screen.
void analyseUserScene (char *nameObj)
void quit ()
Closes the 3d display.
void clickDirection (GLint x, GLint y, V3 *dir)
Converts (x,y) screen coord into a direction from eyes to the click.
void showSolidList ()
show all solid of the render list.
void cameraPosition ()
Set camera position.
void clearGLBuffer ()
Clear everything.
Static Public Member Functions
static void stat ()
Private Member Functions
void lighting ()
Set lights.
void materials ()
Set colors of materials.
void solids (bool select)
Render solids in display-list.
void solidsOpaque (bool zsel, list< Solid * >::iterator psu, uint8_t prior)
opaque solids
void solidsTranslucid (bool zsel, list< Solid * >::iterator psu, uint8_t prior)
translucid solids
void specific (uint32_t n, uint8_t order)
Special rendering.
void specificStill (uint32_t n, uint8_t order)
Special rendering.
void specificMobile (uint32_t n, uint8_t order)
Special rendering.
void specificInvisible (uint32_t n, uint8_t order)
Special rendering.
void setzname (WObject *po)
Sets name in buffer for selection.
void map ()
show the small map.
void satellite ()
show the satellite view.
Static Private Member Functions
static int compareHit (const void *t1, const void *t2)
Sorts all elements of the selection buffer.
Private Attributes
std::list< Solid * > solidList
rendering solids list.
V3 bbox_min
minimal bbox.
V3 bbox_max
maximal bbox.
M4 camera_pos
camera position.
bool first_bbox
first bbox.
bool quality
flag quality yes/no.
bool flash
flag flash.
GLfloat needle_angle
needle progression angle
uint8_t view
local user View type.
bool viewMap
local user Map.
bool viewSat
local user satellite view.
GLfloat thirdPerson_yRot
local user y rotation for Third Person view.
GLfloat thirdPerson_xRot
local user x rotation for Third Person view.
GLfloat thirdPerson_Near
local user distance for Third Person view.
GLfloat turnAround
local user rotation for Turn Around view.
GLfloat pitch
local user pitch rotation.
class Wheel * wheel
experimental
V3 satellitePos
V3 satelliteRot
V3 mapUserPos
int numberVisibleSolid
int numberBlinkSolid
int numberFlashySolid
Static Private Attributes
static const int SELECT_BUFSIZ = (4*256)
Friends
class User
access to many members.
class WObject
access to many members.
class Solid
access to many members.
Detailed Description
Render class.
OpenGL Graphic Context and Rendering
Definition at line 35 of file render.hpp.
Member Enumeration Documentation
view_mode
enum Render::view_mode
Enumerator
VIEW_FIRST_PERSON
VIEW_THIRD_PERSON
VIEW_THIRD_PERSON_FAR
VIEW_VERTICAL
VIEW_VERTICAL_FAR
VIEW_GROUND_LEVEL
VIEW_TURN_AROUND
VIEW_WIRED
VIEW_SCISSOR
VIEW_NUMBER
Definition at line 43 of file render.hpp.
Constructor & Destructor Documentation
Render()
Render::Render ()
Constructor.
Definition at line 50 of file render.cpp.
References first_bbox, flash, Texture::initCache(), pitch, thirdPerson_Near, thirdPerson_xRot, thirdPerson_yRot, turnAround, view, VIEW_FIRST_PERSON, viewMap, and viewSat.
Member Function Documentation
addSolidInList()
void Render::addSolidInList (Solid * solid)
add solid in rendering list.
Definition at line 614 of file render.cpp.
References solidList.
Referenced by Solid::parser().
analyseUserScene()
void Render::analyseUserScene (char * nameObj)
Definition at line 730 of file render.cpp.
References Vicinity::analyseUserScene().
calculateFov()
void Render::calculateFov (GLfloat x, GLfloat y, GLfloat z, GLfloat az, char * filname)
calculate the FOV of the user on the position x,y,z and az.
Definition at line 304 of file camera.cpp.
References clearGLBuffer(), Ogl::copyPixels(), g, Pref::height3D, Global::pref, RAD2DEG, render(), Img::saveJPG(), solids(), and Pref::width3D.
Referenced by Messages::postRequest().
camera()
void Render::camera ()
Repaint.
Definition at line 39 of file camera.cpp.
References cam_user, cameraProjection(), Render::sCamera::far, Render::sCamera::fovy, and Render::sCamera::near.
Referenced by config(), and Scene::paintCB().
cameraPosition()
void Render::cameraPosition ()
Set camera position.
Definition at line 99 of file camera.cpp.
References camera_pos, g, Times::getRate(), User::height, localuser, M4toV16(), M_PI, M_PI_2, MAX, MulM4(), pitch, RotateM4(), thirdPerson_Near, thirdPerson_xRot, thirdPerson_yRot, Global::times, TranslateM4(), turnAround, UX, UY, view, VIEW_FIRST_PERSON, VIEW_GROUND_LEVEL, VIEW_SCISSOR, VIEW_THIRD_PERSON, VIEW_THIRD_PERSON_FAR, VIEW_TURN_AROUND, VIEW_VERTICAL, VIEW_VERTICAL_FAR, and VIEW_WIRED.
Referenced by getBufferSelection(), getDrawedObjects(), minirender(), and render().
cameraProjection()
void Render::cameraProjection (GLfloat fovy, GLfloat near, GLfloat far)
Projection definition.
fovy: angle of field width (in degree)
near: distance between the eye and the projection plan
far : distance between the eye and the clipping plan
Definition at line 54 of file camera.cpp.
References cam_user, Render::sCamera::far, Render::sCamera::fovy, fovy, M_PI_180, Render::sCamera::near, near, and ratio.
Referenced by camera(), User::decreaseZoom(), User::defaultZoom(), User::increaseZoom(), User::setCamera(), and User::setZoom().
clearGLBuffer()
void Render::clearGLBuffer ()
Clear everything.
Definition at line 329 of file render.cpp.
References World::backgroundColor(), Bgcolor::color, World::current(), flash, g, Gui::getScene(), Global::gui, and Scene::setBackground().
Referenced by calculateFov(), map(), minirender(), render(), and satellite().
clickDirection()
void Render::clickDirection (GLint x, GLint y, V3 * dir)
Converts (x,y) screen coord into a direction from eyes to the click.
Definition at line 580 of file render.cpp.
References User::FAR, g, Scene::getCoords(), Gui::getScene(), gluUnProject(), Global::gui, User::height, localuser, MAX, MIN, User::NEAR, WObject::pos, V3::v, Pos::x, Pos::y, and Pos::z.
Referenced by WObject::click(), and User::setRayDirection().
compareHit()
int Render::compareHit (const void * t1, const void * t2) static private
Sorts all elements of the selection buffer.
Definition at line 511 of file render.cpp.
Referenced by getBufferSelection(), and getDrawedObjects().
computeCameraProjection()
void Render::computeCameraProjection ()
Definition at line 342 of file camera.cpp.
References Pos::az, cam_user, DBG_FORCE, Render::sCamera::far, Render::sCamera::fovy, fovy, localuser, Render::sCamera::near, near, WObject::pos, trace(), Pos::x, Pos::y, and Pos::z.
config()
void Render::config (bool _quality)
Initialization.
Definition at line 99 of file render.cpp.
References camera(), DBG_FORCE, g, haveClips(), haveDepth(), haveStencil(), haveTextures(), Pref::infogl, Global::pref, and trace().
Referenced by Scene::init().
getBB()
void Render::getBB (V3 & bbmax, V3 & bbmin, bool _framed)
Gets min/max BB.
Definition at line 522 of file render.cpp.
References bbox_max, bbox_min, MAX, MIN, and V3::v.
Referenced by Solid::getBB().
getBufferSelection()
uint16_t Render::getBufferSelection (GLint x, GLint y, GLint zdepth)
Returns the solid's num displayed in (x,y) on the screen.
We use here coordinates IN THE ZBUFFER and no in the display window.
Definition at line 448 of file render.cpp.
References cam_user, cameraPosition(), compareHit(), Pref::dbgtrace, error(), Render::sCamera::far, Render::sCamera::fovy, g, M_PI_180, Render::sCamera::near, Global::pref, ratio, selectbuf, and solids().
Referenced by Vicinity::analyseVisual(), Widgets::getPointedObject(), and getVisiblePosition().
getDrawedObjects()
WObject ** Render::getDrawedObjects (int * nbr)
get All drawed Objects on the screen.
Definition at line 663 of file render.cpp.
References WObject::byNum(), cam_user, cameraPosition(), compareHit(), Render::sCamera::far, Render::sCamera::fovy, M_PI_180, Render::sCamera::near, ratio, selectbuf, solids(), and strcasecmp().
Referenced by Vicinity::analyseVicinity(), Vicinity::analyseVisual(), and getVisibleTypedObjects().
getMapUserPos()
V3 Render::getMapUserPos () inline
return the x,y position of the user on the map and z is a bool what say if map is on/off.
Definition at line 175 of file render.hpp.
getSolidList()
std::list<Solid*> Render::getSolidList () inline
return the rendering solid list.
Definition at line 94 of file render.hpp.
Referenced by Vicinity::Vicinity().
getViewMode()
uint8_t Render::getViewMode () const
Gets the current view mode.
Definition at line 84 of file camera.cpp.
References view.
Referenced by User::switchView(), User::thirdPersonView_RotL(), User::thirdPersonView_RotR(), and User::toland().
getVisiblePosition()
V3 Render::getVisiblePosition (WObject * po)
get the 3D position of the object on the user screen.
Definition at line 262 of file camera.cpp.
References Pos::bbsize, WObject::byNum(), g, getBufferSelection(), Scene::getCoords(), WObject::getInstance(), Gui::getScene(), gluProject(), Global::gui, newV3(), WObject::pos, strcasecmp(), V3::v, Pos::x, Pos::y, and Pos::z.
Referenced by Vicinity::describeVisual(), WObject::isSeen(), and map().
getVisibleTypedObjects()
WObject ** Render::getVisibleTypedObjects (char ** listetype, int nbr, int * nbrElemts)
Get the object list where each object have a type present in the given list.
Definition at line 627 of file render.cpp.
References getDrawedObjects(), and strcasecmp().
haveClips()
GLint Render::haveClips ()
Checks buffers.
Definition at line 91 of file render.cpp.
Referenced by config().
haveDepth()
GLint Render::haveDepth ()
Definition at line 69 of file render.cpp.
Referenced by config().
haveStencil()
GLint Render::haveStencil ()
Definition at line 83 of file render.cpp.
Referenced by config(), and Solid::displayList().
haveTextures()
GLint Render::haveTextures ()
Definition at line 76 of file render.cpp.
Referenced by config().
lighting()
void Render::lighting () private
Set lights.
Definition at line 354 of file render.cpp.
References DBG_VGL, lightList, Light::lights(), and trace2().
Referenced by map(), render(), and satellite().
map()
void Render::map () private
show the small map.
Definition at line 177 of file camera.cpp.
References World::bbsize, clearGLBuffer(), World::current(), d, DEG2RAD, User::FOVY, g, Scene::getCoords(), Gui::getScene(), getVisiblePosition(), Global::gui, lighting(), localuser, M4toV16(), M_PI_2, mapUserPos, MAX, MulM4(), RotateM4(), Scene::setViewport(), solids(), TranslateM4(), UZ, V3::v, and viewMap.
Referenced by render().
materials()
void Render::materials () private
Set colors of materials.
Definition at line 144 of file render.cpp.
References color.
minirender()
void Render::minirender ()
‍**< Issue the OpenGL commands to draw the solid in the given mode.
Renders minimal.
Definition at line 438 of file render.cpp.
References cameraPosition(), clearGLBuffer(), and solids().
quit()
void Render::quit ()
Closes the 3d display.
Definition at line 755 of file render.cpp.
References Texture::closeCache().
Referenced by Global::quitVreng().
removeSolidFromList()
void Render::removeSolidFromList (Solid * solid)
remove solid from rendering list.
Definition at line 619 of file render.cpp.
References solidList.
Referenced by Solid::~Solid().
render()
void Render::render ()
Renders the current scene in the current buffer.
Definition at line 425 of file render.cpp.
References Axis::axis(), cameraPosition(), clearGLBuffer(), Grid::grid(), lighting(), map(), Axis::render(), Grid::render(), satellite(), solids(), and Texture::update().
Referenced by calculateFov(), Scene::paintScene(), and Parse::parseVreLines().
satellite()
void Render::satellite () private
show the satellite view.
Definition at line 217 of file camera.cpp.
References clearGLBuffer(), g, Scene::getCoords(), Gui::getScene(), Global::gui, lighting(), mapUserPos, RAD2DEG, satellitePos, satelliteRot, Scene::setViewport(), solids(), V3::v, view, and VIEW_SCISSOR.
Referenced by render().
setAllTypeFlashy()
void Render::setAllTypeFlashy (char * object_type, int typeflash)
enable flashy for all same type object.
Definition at line 409 of file render.cpp.
References solidList, and strcasecmp().
setBB() [1/2]
void Render::setBB (const GLfloat * v)
Sets min/max BB.
Definition at line 537 of file render.cpp.
References bbox_max, bbox_min, first_bbox, MAX, MIN, and V3::v.
setBB() [2/2]
void Render::setBB (GLfloat w, GLfloat d, GLfloat h)
Definition at line 555 of file render.cpp.
References bbox_max, bbox_min, d, and V3::v.
Referenced by Solid::setBB(), and Draw::vertex3fv().
setCameraPosition()
void Render::setCameraPosition (M4 * vr_mat)
Sets camera position: Matrix given the camera position in the world, specify the orthogonal transformation to apply on world coordoninates to screen coordoninates.
not fully implemented.
Definition at line 45 of file camera.cpp.
References camera_pos.
Referenced by WObject::updateCamera().
setCameraScissor()
void Render::setCameraScissor (GLfloat posx, GLfloat posy, GLfloat posz, GLfloat rotz)
move the intelligente satellite camera to the good position.
Definition at line 251 of file camera.cpp.
References satellitePos, satelliteRot, V3::v, view, VIEW_FIRST_PERSON, and VIEW_SCISSOR.
Referenced by moveSatCamera().
setFlash()
void Render::setFlash ()
accessor to flash.
Definition at line 139 of file render.cpp.
References flash.
Referenced by Capture::writeJPGImage().
setPitch()
void Render::setPitch (GLfloat angle)
Sets the pitch angle.
Definition at line 94 of file camera.cpp.
References pitch.
Referenced by User::setPitch().
setViewMode()
void Render::setViewMode (uint8_t mode)
Sets the view mode.
Definition at line 77 of file camera.cpp.
References thirdPerson_Near, thirdPerson_xRot, thirdPerson_yRot, view, and VIEW_THIRD_PERSON.
Referenced by User::setView().
setzname()
void Render::setzname (WObject * po) private
Sets name in buffer for selection.
Definition at line 155 of file render.cpp.
References WObject::isSelectable(), WObject::isValid(), and WObject::num.
Referenced by specificInvisible(), specificMobile(), and specificStill().
showSolidList()
void Render::showSolidList ()
show all solid of the render list.
Definition at line 737 of file render.cpp.
References DBG_FORCE, error(), solidList, strcasecmp(), and trace().
solids()
void Render::solids (bool select = false) private
Render solids in display-list.
Definition at line 263 of file render.cpp.
References DBG_VGL, Solid::FLASHRAY, WObject::getInstance(), WObject::getObjectsNumber(), Solid::LOCALUSER, localuser, Solid::PLAIN, WObject::RENDER_HIGH, WObject::RENDER_LOW, WObject::RENDER_NORMAL, solidList, solidsOpaque(), solidsTranslucid(), specific(), trace2(), and USER_TYPE.
Referenced by calculateFov(), getBufferSelection(), getDrawedObjects(), map(), minirender(), render(), and satellite().
solidsOpaque()
void Render::solidsOpaque (bool zsel, list< Solid * >::iterator psu, uint8_t prior) private
opaque solids
Definition at line 207 of file render.cpp.
References DBG_VGL, Solid::OPAQUE, Solid::PLAIN, solidList, SPECIFIC_RENDER, trace2(), and Solid::ZBUFSELECT.
Referenced by solids().
solidsTranslucid()
void Render::solidsTranslucid (bool zsel, list< Solid * >::iterator psu, uint8_t prior) private
translucid solids
Definition at line 221 of file render.cpp.
References DBG_VGL, Solid::PLAIN, solidList, SPECIFIC_RENDER, trace2(), Solid::TRANSLUCID, and Solid::ZBUFSELECT.
Referenced by solids().
specific()
void Render::specific (uint32_t n, uint8_t order) private
Special rendering.
Definition at line 237 of file render.cpp.
References WObject::RENDER_HIGH, WObject::RENDER_LOW, WObject::RENDER_NORMAL, specificInvisible(), specificMobile(), and specificStill().
Referenced by solids().
specificInvisible()
void Render::specificInvisible (uint32_t n, uint8_t order) private
Special rendering.
Definition at line 194 of file render.cpp.
References DBG_VGL, invisibleList, setzname(), SPECIFIC_RENDER, and trace2().
Referenced by specific().
specificMobile()
void Render::specificMobile (uint32_t n, uint8_t order) private
Special rendering.
Definition at line 177 of file render.cpp.
References DBG_VGL, materials, mobileList, setzname(), SPECIFIC_RENDER, and trace2().
Referenced by specific().
specificStill()
void Render::specificStill (uint32_t n, uint8_t order) private
Special rendering.
Definition at line 164 of file render.cpp.
References DBG_VGL, materials, setzname(), SPECIFIC_RENDER, stillList, and trace2().
Referenced by specific().
stat()
void Render::stat () static
Definition at line 133 of file render.cpp.
References DBG_FORCE, dlist, and trace().
Referenced by Global::printStats().
switchViewMap()
void Render::switchViewMap ()
Switchs the view map.
Definition at line 89 of file camera.cpp.
References viewMap.
Referenced by User::mapView().
updateBB()
void Render::updateBB (GLfloat az)
Updates BB according to its orientation.
Definition at line 566 of file render.cpp.
References bbox_max, bbox_min, and V3::v.
Referenced by Solid::updateBB().
Friends And Related Function Documentation
Solid
friend class Solid friend
access to many members.
Definition at line 38 of file render.hpp.
User
friend class User friend
access to many members.
Definition at line 36 of file render.hpp.
WObject
friend class WObject friend
access to many members.
Definition at line 37 of file render.hpp.
Member Data Documentation
bbox_max
V3 Render::bbox_max private
maximal bbox.
Definition at line 235 of file render.hpp.
Referenced by getBB(), setBB(), and updateBB().
bbox_min
V3 Render::bbox_min private
minimal bbox.
Definition at line 234 of file render.hpp.
Referenced by getBB(), setBB(), and updateBB().
camera_pos
M4 Render::camera_pos private
camera position.
Definition at line 236 of file render.hpp.
Referenced by cameraPosition(), and setCameraPosition().
first_bbox
bool Render::first_bbox private
first bbox.
Definition at line 237 of file render.hpp.
Referenced by Render(), setBB(), Solid::solidParser(), and Solid::statueParser().
flash
bool Render::flash private
flag flash.
Definition at line 239 of file render.hpp.
Referenced by clearGLBuffer(), Render(), and setFlash().
mapUserPos
V3 Render::mapUserPos private
Definition at line 255 of file render.hpp.
Referenced by map(), and satellite().
needle_angle
GLfloat Render::needle_angle private
needle progression angle
Definition at line 240 of file render.hpp.
numberBlinkSolid
int Render::numberBlinkSolid private
Definition at line 257 of file render.hpp.
numberFlashySolid
int Render::numberFlashySolid private
Definition at line 258 of file render.hpp.
numberVisibleSolid
int Render::numberVisibleSolid private
Definition at line 256 of file render.hpp.
pitch
GLfloat Render::pitch private
local user pitch rotation.
Definition at line 249 of file render.hpp.
Referenced by cameraPosition(), Render(), and setPitch().
quality
bool Render::quality private
flag quality yes/no.
Definition at line 238 of file render.hpp.
satellitePos
V3 Render::satellitePos private
Definition at line 253 of file render.hpp.
Referenced by satellite(), and setCameraScissor().
satelliteRot
V3 Render::satelliteRot private
Definition at line 254 of file render.hpp.
Referenced by satellite(), and setCameraScissor().
SELECT_BUFSIZ
const int Render::SELECT_BUFSIZ = (4*256) static private
Definition at line 230 of file render.hpp.
solidList
std::list<Solid*> Render::solidList private
rendering solids list.
Definition at line 232 of file render.hpp.
Referenced by addSolidInList(), Solid::displayMirroredScene(), removeSolidFromList(), setAllTypeFlashy(), showSolidList(), solids(), solidsOpaque(), and solidsTranslucid().
thirdPerson_Near
GLfloat Render::thirdPerson_Near private
local user distance for Third Person view.
Definition at line 247 of file render.hpp.
Referenced by cameraPosition(), Render(), and setViewMode().
thirdPerson_xRot
GLfloat Render::thirdPerson_xRot private
local user x rotation for Third Person view.
Definition at line 246 of file render.hpp.
Referenced by cameraPosition(), Render(), setViewMode(), User::thirdPersonView_RotL(), and User::thirdPersonView_RotR().
thirdPerson_yRot
GLfloat Render::thirdPerson_yRot private
local user y rotation for Third Person view.
Definition at line 245 of file render.hpp.
Referenced by cameraPosition(), Render(), and setViewMode().
turnAround
GLfloat Render::turnAround private
local user rotation for Turn Around view.
Definition at line 248 of file render.hpp.
Referenced by cameraPosition(), and Render().
view
uint8_t Render::view private
local user View type.
Definition at line 242 of file render.hpp.
Referenced by cameraPosition(), getViewMode(), Render(), satellite(), setCameraScissor(), and setViewMode().
viewMap
bool Render::viewMap private
local user Map.
Definition at line 243 of file render.hpp.
Referenced by map(), Render(), and switchViewMap().
viewSat
bool Render::viewSat private
local user satellite view.
Definition at line 244 of file render.hpp.
Referenced by Render().
wheel
class Wheel* Render::wheel private
experimental
Definition at line 251 of file render.hpp.
The documentation for this class was generated from the following files:
src/vgl/render.hpp
src/vgl/camera.cpp
src/vgl/render.cpp