VREng: Ogl Class Reference
Ogl Class Reference
Ogl class.
#include <ogl.hpp>
Static Public Member Functions
static uint8_t * copyPixels (GLint width, GLint height, GLenum mode)
Copies 3D buffer into a RGB pixmap Returns this pixmap.
static bool isGLextension (const char *ext)
Checks OpenGL extensions.
static void infosGL ()
Prints OpenGL infos.
static void printGLMatrix ()
Prints ModelView Matrix.
static void printGLError ()
Prints OpenGL error.
Detailed Description
Ogl class.
Definition at line 28 of file ogl.hpp.
Member Function Documentation
copyPixels()
uint8_t * Ogl::copyPixels (GLint width, GLint height, GLenum mode) static
Copies 3D buffer into a RGB pixmap Returns this pixmap.
Copies 3D buffer into a RGB pixmap and returns this pixmap.
Definition at line 26 of file ogl.cpp.
Referenced by Render::calculateFov(), and Capture::captureGl2jpg().
infosGL()
void Ogl::infosGL () static
Prints OpenGL infos.
Definition at line 87 of file ogl.cpp.
isGLextension()
bool Ogl::isGLextension (const char * ext) static
Checks OpenGL extensions.
Check if an OpenGL extension is supported.
Definition at line 58 of file ogl.cpp.
printGLError()
void Ogl::printGLError () static
Prints OpenGL error.
Definition at line 125 of file ogl.cpp.
References error().
printGLMatrix()
void Ogl::printGLMatrix () static
Prints ModelView Matrix.
Definition at line 112 of file ogl.cpp.
The documentation for this class was generated from the following files:
src/vgl/ogl.hpp
src/vgl/ogl.cpp