VREng: Car Class Reference
Car Class Reference
Car model.
#include <car.hpp>
Static Public Member Functions
static void draw (GLfloat width, GLfloat depth, GLfloat height, const int textures[], GLfloat rtex[6][2], uint8_t slices, uint8_t style)
Draws a car.
Static Private Member Functions
static void car (GLfloat adir, const int textures[], GLfloat rtex[6][2], uint8_t slices, uint8_t style)
static void rouederdte (GLfloat r, int p)
static void rouedergche (GLfloat r, int p)
static void roueavtdte (GLfloat r, GLfloat adir, int p)
static void roueavtgche (GLfloat r, GLfloat adir, int p)
static void roue (GLfloat r, int normale, int p)
static void roue (GLfloat r, int p)
static void cylindre (GLfloat height, GLfloat radius, int precision)
Detailed Description
Car model.
Definition at line 28 of file car.hpp.
Member Function Documentation
car()
void Car::car (GLfloat adir, const int textures[], GLfloat rtex[6][2], uint8_t slices, uint8_t style) static private
Definition at line 45 of file car.cpp.
References Draw::box(), roueavtdte(), roueavtgche(), rouederdte(), rouedergche(), and Draw::STYLE_FILL.
Referenced by draw().
cylindre()
void Car::cylindre (GLfloat height, GLfloat radius, int precision) static private
Definition at line 146 of file car.cpp.
References M_2PI.
Referenced by roueavtdte(), roueavtgche(), rouederdte(), and rouedergche().
draw()
void Car::draw (GLfloat width, GLfloat depth, GLfloat height, const int textures[], GLfloat rtex[6][2], uint8_t slices, uint8_t style) static
Draws a car.
Definition at line 26 of file car.cpp.
References car().
Referenced by Solid::solidParser().
roue() [1/2]
static void Car::roue (GLfloat r, int normale, int p) static private
Referenced by roueavtdte(), roueavtgche(), rouederdte(), and rouedergche().
roue() [2/2]
void Car::roue (GLfloat r, int p) static private
Definition at line 127 of file car.cpp.
References M_2PI.
roueavtdte()
void Car::roueavtdte (GLfloat r, GLfloat adir, int p) static private
Definition at line 100 of file car.cpp.
References cylindre(), and roue().
Referenced by car().
roueavtgche()
void Car::roueavtgche (GLfloat r, GLfloat adir, int p) static private
Definition at line 115 of file car.cpp.
References cylindre(), and roue().
Referenced by car().
rouederdte()
void Car::rouederdte (GLfloat r, int p) static private
Definition at line 77 of file car.cpp.
References cylindre(), and roue().
Referenced by car().
rouedergche()
void Car::rouedergche (GLfloat r, int p) static private
Definition at line 89 of file car.cpp.
References cylindre(), and roue().
Referenced by car().
The documentation for this class was generated from the following files:
src/vgl/car.hpp
src/vgl/car.cpp