VREng: Draw Class Reference
Draw Class Reference
Draw simple 3D shapes : points, lines, cube, sphere, cylinder...
#include <draw.hpp>
Public Types
enum { STYLE_FILL, STYLE_LINES, STYLE_POINTS }
Static Public Member Functions
static void vertex3fv (const GLfloat *v)
static void vertex3f (GLfloat x, GLfloat y, GLfloat z)
static void point (GLfloat x, GLfloat y, GLfloat z)
Draws a point.
static void line (GLfloat l, GLfloat w)
Draws a line.
static void rect (GLfloat w, GLfloat h, uint8_t style, GLfloat rTxs=1, GLfloat rTxt=1)
Draws a rectangle.
static void ellipse (GLfloat rx, GLfloat ry, uint8_t style)
Draws an ellipse.
static void triangle (GLfloat x1, GLfloat y1, GLfloat z1, GLfloat x2, GLfloat y2, GLfloat z2, GLfloat x3, GLfloat y3, GLfloat z3)
Draws a triangle.
static void bbox (GLfloat width, GLfloat depth, GLfloat height)
Draws a wired bounding box.
static void box (GLfloat width, GLfloat depth, GLfloat height, const int textures[], GLfloat rTx[6][2], uint8_t style)
Draws a textured box.
static void box (GLfloat width, GLfloat depth, GLfloat height)
Draws a box.
static void pyramid (GLfloat side, GLfloat height, uint8_t style)
Draws a pyramid.
static void octagon (GLfloat side, GLfloat height, uint8_t style)
Draws a octagon.
static void torus (GLfloat rc, uint8_t numc, GLfloat rt, uint8_t numt, uint8_t style)
Draws a torus.
static void sphere (GLfloat radius, uint8_t slices, uint8_t stacks, uint8_t style)
Draws a sphere.
static void cylinder (GLfloat baseR, GLfloat topR, GLfloat height, uint8_t slices, uint8_t stacks, uint8_t style)
Draws a cylinder or cone.
static void disk (GLfloat inR, GLfloat outR, uint8_t slices, uint8_t loops, uint8_t style)
Draws a disk.
static void ray (GLint *dl, GLfloat x1, GLfloat y1, GLfloat z1, GLfloat x2, GLfloat y2, GLfloat z2, const GLfloat *color, GLint stipple)
Draws a stipple beam in displaylist.
static void ray (GLint *dl, GLfloat x1, GLfloat y1, GLfloat z1, GLfloat x2, GLfloat y2, GLfloat z2)
Draws a full beam in displaylist.
static void helix (GLfloat r, GLfloat length, GLfloat height, GLfloat slices, GLfloat thick, GLfloat *color)
Detailed Description
Draw simple 3D shapes : points, lines, cube, sphere, cylinder...
Definition at line 28 of file draw.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
STYLE_FILL
STYLE_LINES
STYLE_POINTS
Definition at line 32 of file draw.hpp.
Member Function Documentation
bbox()
void Draw::bbox (GLfloat width, GLfloat depth, GLfloat height) static
Draws a wired bounding box.
Definition at line 121 of file draw.cpp.
References box().
Referenced by Solid::solidParser().
box() [1/2]
void Draw::box (GLfloat width, GLfloat depth, GLfloat height) static
Draws a box.
Definition at line 236 of file draw.cpp.
box() [2/2]
void Draw::box (GLfloat width, GLfloat depth, GLfloat height, const int textures[], GLfloat rTx[6][2], uint8_t style) static
Draws a textured box.
Definition at line 142 of file draw.cpp.
References faces, normals, STYLE_LINES, STYLE_POINTS, texcoords, and vertex3fv().
Referenced by bbox(), Car::car(), Mech::drawForeArm(), Mech::drawLowerLeg(), Mech::drawRocketPod(), Mech::drawShoulder(), Mech::drawTorso(), Mech::drawUpperArm(), Mech::drawUpperLeg(), and Solid::solidParser().
cylinder()
void Draw::cylinder (GLfloat baseR, GLfloat topR, GLfloat height, uint8_t slices, uint8_t stacks, uint8_t style) static
Draws a cylinder or cone.
Definition at line 449 of file draw.cpp.
References M_2PI, STYLE_FILL, STYLE_LINES, STYLE_POINTS, and vertex3f().
Referenced by Guy::draw_breath(), Guy::draw_bust(), Guy::draw_foot(), Guy::draw_larm(), Guy::draw_lleg(), Guy::draw_neck(), Guy::draw_uarm(), Guy::draw_uleg(), Mech::drawLowerLeg(), X3d::drawPrimitive(), Mech::drawRocketPod(), Mech::drawUpperArm(), Mech::drawUpperLeg(), Mech::drawVulcanGun(), and Solid::solidParser().
disk()
void Draw::disk (GLfloat inR, GLfloat outR, uint8_t slices, uint8_t loops, uint8_t style) static
Draws a disk.
Definition at line 547 of file draw.cpp.
References M_2PI, STYLE_FILL, STYLE_LINES, and STYLE_POINTS.
Referenced by Mech::drawLowerLeg(), X3d::drawPrimitive(), Mech::drawUpperArm(), Mech::drawUpperLeg(), Mech::drawVulcanGun(), and Solid::solidParser().
ellipse()
void Draw::ellipse (GLfloat rx, GLfloat ry, uint8_t style) static
Draws an ellipse.
Definition at line 97 of file draw.cpp.
References DEG2RAD, STYLE_FILL, STYLE_LINES, and STYLE_POINTS.
Referenced by Solid::solidParser().
helix()
void Draw::helix (GLfloat r, GLfloat length, GLfloat height, GLfloat slices, GLfloat thick, GLfloat * color) static
Definition at line 658 of file draw.cpp.
References color, and M_PI.
Referenced by Solid::solidParser().
line()
void Draw::line (GLfloat l, GLfloat w = 0) static
Draws a line.
Definition at line 51 of file draw.cpp.
Referenced by Solid::solidParser().
octagon()
void Draw::octagon (GLfloat side, GLfloat height, uint8_t style) static
Draws a octagon.
Definition at line 309 of file draw.cpp.
References M_PI_4, and STYLE_FILL.
Referenced by Mech::drawFoot(), and Mech::drawHip().
point()
void Draw::point (GLfloat x, GLfloat y, GLfloat z) static
Draws a point.
Definition at line 43 of file draw.cpp.
Referenced by Solid::solidParser().
pyramid()
void Draw::pyramid (GLfloat side, GLfloat height, uint8_t style) static
Draws a pyramid.
Definition at line 285 of file draw.cpp.
References STYLE_FILL.
Referenced by Solid::solidParser().
ray() [1/2]
void Draw::ray (GLint * dl, GLfloat x1, GLfloat y1, GLfloat z1, GLfloat x2, GLfloat y2, GLfloat z2) static
Draws a full beam in displaylist.
Definition at line 651 of file draw.cpp.
References color, Color::green, and ray().
ray() [2/2]
void Draw::ray (GLint * dl, GLfloat x1, GLfloat y1, GLfloat z1, GLfloat x2, GLfloat y2, GLfloat z2, const GLfloat * color, GLint stipple) static
Draws a stipple beam in displaylist.
Definition at line 630 of file draw.cpp.
References color.
Referenced by User::get_ray(), ray(), Solid::setRay(), and User::setRayDirection().
rect()
void Draw::rect (GLfloat w, GLfloat h, uint8_t style, GLfloat rTxs = 1, GLfloat rTxt = 1) static
Draws a rectangle.
Definition at line 64 of file draw.cpp.
References STYLE_FILL, STYLE_LINES, and STYLE_POINTS.
Referenced by Solid::solidParser().
sphere()
void Draw::sphere (GLfloat radius, uint8_t slices, uint8_t stacks, uint8_t style) static
Draws a sphere.
Definition at line 373 of file draw.cpp.
References M_2PI, M_PI, and vertex3f().
Referenced by Wings::draw(), Cloud::draw(), Guy::draw_foot(), Guy::draw_head(), Guy::draw_uarm(), Guy::draw_uleg(), Mech::drawHip(), Mech::drawLowerLeg(), X3d::drawPrimitive(), Mech::drawShoulder(), and Solid::solidParser().
torus()
void Draw::torus (GLfloat rc, uint8_t numc, GLfloat rt, uint8_t numt, uint8_t style) static
Draws a torus.
Definition at line 344 of file draw.cpp.
References M_2PI, STYLE_FILL, and vertex3f().
Referenced by Solid::solidParser().
triangle()
void Draw::triangle (GLfloat x1, GLfloat y1, GLfloat z1, GLfloat x2, GLfloat y2, GLfloat z2, GLfloat x3, GLfloat y3, GLfloat z3) static
Draws a triangle.
Definition at line 87 of file draw.cpp.
vertex3f()
void Draw::vertex3f (GLfloat x, GLfloat y, GLfloat z) static
Definition at line 34 of file draw.cpp.
References vertex3fv().
Referenced by cylinder(), Md2::draw(), sphere(), and torus().
vertex3fv()
void Draw::vertex3fv (const GLfloat * v) static
Definition at line 28 of file draw.cpp.
References g, Global::render, and Render::setBB().
Referenced by box(), and vertex3f().
The documentation for this class was generated from the following files:
src/vgl/draw.hpp
src/vgl/draw.cpp