VREng: Teapot Class Reference
Teapot Class Reference
Teapot model.
#include <teapot.hpp>
Public Member Functions
Teapot ()
constructor
virtual ~Teapot ()
destructor
virtual void draw (GLfloat width, GLfloat depth, GLfloat height, const int textures[], GLfloat rtex[6][2], uint8_t slices, uint8_t style)
Draws a teapot.
Private Member Functions
void transpose (point p[4][4])
void draw_patch (point p[4][4])
void divide_patch (point p[4][4], uint8_t n)
void divide_curve (point *c, point *r, point *l)
void normal (point n, point p, point q, point r)
Private Attributes
uint8_t level
point data [32][4][4]
Static Private Attributes
static const point vertices [306]
static const int indices [32][4][4]
Detailed Description
Teapot model.
Definition at line 30 of file teapot.hpp.
Constructor & Destructor Documentation
Teapot()
Teapot::Teapot ()
constructor
Definition at line 171 of file teapot.cpp.
References data, indices, level, and vertices.
~Teapot()
virtual Teapot::~Teapot () inline virtual
destructor
Definition at line 41 of file teapot.hpp.
Member Function Documentation
divide_curve()
void Teapot::divide_curve (point * c, point * r, point * l) private
Definition at line 194 of file teapot.cpp.
Referenced by divide_patch().
divide_patch()
void Teapot::divide_patch (point p[4][4], uint8_t n) private
Definition at line 223 of file teapot.cpp.
References divide_curve(), draw_patch(), and transpose().
Referenced by draw().
draw()
void Teapot::draw (GLfloat width, GLfloat depth, GLfloat height, const int textures[], GLfloat rtex[6][2], uint8_t slices, uint8_t style) virtual
Draws a teapot.
Definition at line 260 of file teapot.cpp.
References data, divide_patch(), and level.
Referenced by Solid::solidParser().
draw_patch()
void Teapot::draw_patch (point p[4][4]) private
Definition at line 246 of file teapot.cpp.
References normal().
Referenced by divide_patch().
normal()
void Teapot::normal (point n, point p, point q, point r) private
Definition at line 186 of file teapot.cpp.
Referenced by draw_patch().
transpose()
void Teapot::transpose (point p[4][4]) private
Definition at line 211 of file teapot.cpp.
Referenced by divide_patch().
Member Data Documentation
data
point Teapot::data[32][4][4] private
Definition at line 37 of file teapot.hpp.
Referenced by draw(), and Teapot().
indices
const int Teapot::indices static private
Definition at line 34 of file teapot.hpp.
Referenced by Teapot().
level
uint8_t Teapot::level private
Definition at line 36 of file teapot.hpp.
Referenced by draw(), and Teapot().
vertices
const point Teapot::vertices static private
Definition at line 33 of file teapot.hpp.
Referenced by Teapot().
The documentation for this class was generated from the following files:
src/vgl/teapot.hpp
src/vgl/teapot.cpp