VREng: Vicinity Class Reference
Vicinity Class Reference
Vicinity class.
#include <vicinity.hpp>
Public Member Functions
Vicinity ()
Vicinity (std::string _objectName)
virtual ~Vicinity ()
virtual std::string getObjectName ()
virtual WObject * getObject ()
virtual void analyseTopo ()
virtual void analyseVisual (int details)
Creer une structure des elements visibles pour l'utilisateur tel que : la proportion occupee par l'objet, son emplacement sur l'ecran.
virtual void analyseVicinity ()
virtual WObject * searchProximityObject (char **typeObj, int nbre)
virtual void analyseUserScene ()
describe the scene viewed by the user and use the vicinity list for the AOI
Static Public Member Functions
static void show ()
static void show (const char *str)
static int * getTypeFromAction (const char *actionName)
static char * translateNum2Type (int i)
Private Types
enum Distance {
DIST_INCL, DIST_INTER, DIST_STUCK, DIST_NEAR,
DIST_FAR
}
enum Size {
SIZE_TINY, SIZE_SMALL, SIZE_NORMAL, SIZE_LARGE,
SIZE_HUGE
}
Private Member Functions
virtual void sortByDistance ()
virtual void sortByInterest ()
virtual void sortVisual ()
virtual bool uselessType (WObject *obj)
virtual void describeTopo (Vicin tmp)
virtual void describeVisual ()
virtual void actionList ()
virtual void setUserSize (WObject *user)
Static Private Member Functions
static Distance computeDistance (WObject *obj1, WObject *obj2)
static Size computeSize (WObject *obj)
static int compareByDistance (const void *t1, const void *t2)
static int compareByInterest (const void *t1, const void *t2)
static int compare4Visual (const void *t1, const void *t2)
Private Attributes
WObject * refObject
std::string refObjectName
User * user
Distance userDistance
Size userSize
Size objectSize
Vicin * vicinList
visualPosition * visualList
std::list< Solid * > solidList
solids list
int listSize
int visualListSize
Friends
class User
access to many members
class Render
access to Rendering
Detailed Description
Vicinity class.
Definition at line 34 of file vicinity.hpp.
Member Enumeration Documentation
Distance
enum Vicinity::Distance private
Enumerator
DIST_INCL
DIST_INTER
DIST_STUCK
DIST_NEAR
DIST_FAR
Definition at line 39 of file vicinity.hpp.
Size
enum Vicinity::Size private
Enumerator
SIZE_TINY
SIZE_SMALL
SIZE_NORMAL
SIZE_LARGE
SIZE_HUGE
Definition at line 47 of file vicinity.hpp.
Constructor & Destructor Documentation
Vicinity() [1/2]
Vicinity::Vicinity ()
Definition at line 36 of file vicinity.cpp.
References computeDistance(), computeSize(), Vicin::dist, DIST_INCL, g, WObject::getInstance(), Render::getSolidList(), listSize, localuser, Vicin::object, objectSize, refObject, refObjectName, Global::render, setUserSize(), Vicin::size, solidList, uselessType(), user, userDistance, userSize, and vicinList.
Vicinity() [2/2]
Vicinity::Vicinity (std::string _objectName)
~Vicinity()
Vicinity::~Vicinity () virtual
Definition at line 110 of file vicinity.cpp.
References vicinList.
Member Function Documentation
actionList()
void Vicinity::actionList () private virtual
Definition at line 514 of file vicinity.cpp.
References ACTIONSNUMBER, DBG_FORCE, getActionMethod(), getActionName(), isActionName(), OBJECTSNUMBER, trace(), and translateNum2Type().
analyseTopo()
void Vicinity::analyseTopo () virtual
Definition at line 328 of file vicinity.cpp.
References describeTopo(), dist, error(), listSize, size, and vicinList.
Referenced by analyseUserScene().
analyseUserScene()
void Vicinity::analyseUserScene () virtual
describe the scene viewed by the user and use the vicinity list for the AOI
Definition at line 314 of file vicinity.cpp.
References analyseTopo(), analyseVicinity(), analyseVisual(), and sortByDistance().
Referenced by Render::analyseUserScene().
analyseVicinity()
void Vicinity::analyseVicinity () virtual
Definition at line 479 of file vicinity.cpp.
References error(), g, Render::getDrawedObjects(), refObject, Global::render, and uselessType().
Referenced by analyseUserScene().
analyseVisual()
void Vicinity::analyseVisual (int details) virtual
Creer une structure des elements visibles pour l'utilisateur tel que : la proportion occupee par l'objet, son emplacement sur l'ecran.
Tout a partir de l'ecran de visualisation de l'utilisateur
Definition at line 377 of file vicinity.cpp.
References WObject::byNum(), describeVisual(), g, Render::getBufferSelection(), Render::getDrawedObjects(), WObject::getSolid(), Pref::height3D, Solid::isOpaque(), visualPosition::nbrePixels, visualPosition::object, Global::pref, Global::render, sortVisual(), uselessType(), visualList, visualListSize, Pref::width3D, visualPosition::xmax, visualPosition::xmin, visualPosition::ymax, and visualPosition::ymin.
Referenced by analyseUserScene().
compare4Visual()
int Vicinity::compare4Visual (const void * t1, const void * t2) static private
Definition at line 356 of file vicinity.cpp.
References visualPosition::nbrePixels.
Referenced by sortVisual().
compareByDistance()
int Vicinity::compareByDistance (const void * t1, const void * t2) static private
Definition at line 223 of file vicinity.cpp.
References Vicin::dist, and Vicin::size.
Referenced by sortByDistance().
compareByInterest()
int Vicinity::compareByInterest (const void * t1, const void * t2) static private
Definition at line 241 of file vicinity.cpp.
References computeDistance(), Vicin::dist, localuser, Vicin::object, and Vicin::size.
Referenced by sortByInterest().
computeDistance()
Vicinity::Distance Vicinity::computeDistance (WObject * obj1, WObject * obj2) static private
Definition at line 116 of file vicinity.cpp.
References ABSF, Pos::bbsize, DIST_FAR, DIST_INCL, DIST_INTER, DIST_NEAR, DIST_STUCK, MIN, WObject::pos, V3::v, warning(), Pos::x, Pos::y, and Pos::z.
Referenced by compareByInterest(), and Vicinity().
computeSize()
Vicinity::Size Vicinity::computeSize (WObject * obj) static private
Definition at line 198 of file vicinity.cpp.
References Pos::bbsize, localuser, obj, WObject::pos, SIZE_HUGE, SIZE_LARGE, SIZE_NORMAL, SIZE_SMALL, SIZE_TINY, and V3::v.
Referenced by Vicinity().
describeTopo()
void Vicinity::describeTopo (Vicin tmp) private virtual
Definition at line 300 of file vicinity.cpp.
References Vicin::dist, DIST_FAR, DIST_INCL, DIST_INTER, DIST_NEAR, DIST_STUCK, error(), Vicin::object, and refObjectName.
Referenced by analyseTopo().
describeVisual()
void Vicinity::describeVisual () private virtual
Definition at line 453 of file vicinity.cpp.
References error(), g, Render::getVisiblePosition(), Global::pref, refObject, refObjectName, Global::render, V3::v, visualList, Pref::width3D, visualPosition::xmax, and visualPosition::xmin.
Referenced by analyseVisual().
getObject()
virtual WObject* Vicinity::getObject () inline virtual
Definition at line 121 of file vicinity.hpp.
References refObject.
getObjectName()
virtual std::string Vicinity::getObjectName () inline virtual
Definition at line 120 of file vicinity.hpp.
References refObjectName.
getTypeFromAction()
int * Vicinity::getTypeFromAction (const char * actionName) static
Definition at line 530 of file vicinity.cpp.
References ACTIONSNUMBER, getActionName(), isActionName(), OBJECTSNUMBER, and strcasecmp().
searchProximityObject()
WObject * Vicinity::searchProximityObject (char ** typeObj, int nbre) virtual
Definition at line 284 of file vicinity.cpp.
References Vicin::dist, DIST_NEAR, listSize, Vicin::object, sortByDistance(), strcasecmp(), and vicinList.
setUserSize()
void Vicinity::setUserSize (WObject * user) private virtual
Definition at line 88 of file vicinity.cpp.
References Pos::bbsize, WObject::pos, SIZE_HUGE, SIZE_LARGE, SIZE_NORMAL, SIZE_SMALL, SIZE_TINY, user, userSize, and V3::v.
Referenced by Vicinity().
show() [1/2]
void Vicinity::show () static
Definition at line 500 of file vicinity.cpp.
show() [2/2]
void Vicinity::show (const char * str) static
Definition at line 505 of file vicinity.cpp.
References DBG_FORCE, WObject::getVicinityList(), localuser, OList::pobject, and trace().
sortByDistance()
void Vicinity::sortByDistance () private virtual
Definition at line 236 of file vicinity.cpp.
References compareByDistance(), listSize, and vicinList.
Referenced by analyseUserScene(), and searchProximityObject().
sortByInterest()
void Vicinity::sortByInterest () private virtual
Definition at line 279 of file vicinity.cpp.
References compareByInterest(), listSize, and vicinList.
sortVisual()
void Vicinity::sortVisual () private virtual
Definition at line 367 of file vicinity.cpp.
References compare4Visual(), visualList, and visualListSize.
Referenced by analyseVisual().
translateNum2Type()
char * Vicinity::translateNum2Type (int i) static
Definition at line 548 of file vicinity.cpp.
References OBJECTSNUMBER, and OBJNAME_LEN.
Referenced by actionList().
uselessType()
bool Vicinity::uselessType (WObject * obj) private virtual
Definition at line 347 of file vicinity.cpp.
References obj, and strcasecmp().
Referenced by analyseVicinity(), analyseVisual(), and Vicinity().
Friends And Related Function Documentation
Render
friend class Render friend
access to Rendering
Definition at line 36 of file vicinity.hpp.
User
friend class User friend
access to many members
Definition at line 35 of file vicinity.hpp.
Member Data Documentation
listSize
int Vicinity::listSize private
Definition at line 87 of file vicinity.hpp.
Referenced by analyseTopo(), searchProximityObject(), sortByDistance(), sortByInterest(), and Vicinity().
objectSize
Size Vicinity::objectSize private
Definition at line 81 of file vicinity.hpp.
Referenced by Vicinity().
refObject
WObject* Vicinity::refObject private
Definition at line 75 of file vicinity.hpp.
Referenced by analyseVicinity(), describeVisual(), getObject(), and Vicinity().
refObjectName
std::string Vicinity::refObjectName private
Definition at line 76 of file vicinity.hpp.
Referenced by describeTopo(), describeVisual(), getObjectName(), and Vicinity().
solidList
std::list<Solid*> Vicinity::solidList private
solids list
Definition at line 86 of file vicinity.hpp.
Referenced by Vicinity().
user
User* Vicinity::user private
Definition at line 78 of file vicinity.hpp.
Referenced by setUserSize(), and Vicinity().
userDistance
Distance Vicinity::userDistance private
Definition at line 79 of file vicinity.hpp.
Referenced by Vicinity().
userSize
Size Vicinity::userSize private
Definition at line 80 of file vicinity.hpp.
Referenced by setUserSize(), and Vicinity().
vicinList
Vicin* Vicinity::vicinList private
Definition at line 83 of file vicinity.hpp.
Referenced by analyseTopo(), searchProximityObject(), sortByDistance(), sortByInterest(), Vicinity(), and ~Vicinity().
visualList
visualPosition* Vicinity::visualList private
Definition at line 84 of file vicinity.hpp.
Referenced by analyseVisual(), describeVisual(), and sortVisual().
visualListSize
int Vicinity::visualListSize private
Definition at line 88 of file vicinity.hpp.
Referenced by analyseVisual(), and sortVisual().
The documentation for this class was generated from the following files:
src/vgl/vicinity.hpp
src/vgl/vicinity.cpp