VREng: Hud Class Reference
Hud Class Reference
Hud class.
#include <hud.hpp>
Public Member Functions
Hud ()
Constructor.
virtual ~Hud ()
virtual bool isVisible ()
Destructor.
virtual void toggle ()
virtual void render (GLfloat r, GLfloat g, GLfloat b, GLfloat a, void *font, GLint x, GLint y, const char *s,...)
hud rendering
virtual void render (GLfloat r, GLfloat g, GLfloat b, GLfloat a, GLuint font, GLint x, GLint y, const char *s,...)
Static Public Member Functions
static Hud * hud ()
Returns hud instance.
Private Member Functions
void bitmap_output (int x, int y, const char *string, void *font)
Private Attributes
bool visible
Detailed Description
Hud class.
Definition at line 28 of file hud.hpp.
Constructor & Destructor Documentation
Hud()
Hud::Hud ()
Constructor.
Definition at line 32 of file hud.cpp.
References phud, and visible.
~Hud()
virtual Hud::~Hud () inline virtual
Definition at line 39 of file hud.hpp.
Member Function Documentation
bitmap_output()
void Hud::bitmap_output (int x, int y, const char * string, void * font) private
Definition at line 54 of file hud.cpp.
References DBG_FORCE, and trace().
Referenced by render().
hud()
Hud * Hud::hud () static
Returns hud instance.
Definition at line 39 of file hud.cpp.
References _hud.
isVisible()
bool Hud::isVisible () virtual
Destructor.
Checks if hud is visible
Definition at line 49 of file hud.cpp.
References visible.
render() [1/2]
void Hud::render (GLfloat r, GLfloat g, GLfloat b, GLfloat a, GLuint font, GLint x, GLint y, const char * s, ...) virtual
Definition at line 97 of file hud.cpp.
References DBG_FORCE, g, Pref::height3D, Global::pref, trace(), visible, and Pref::width3D.
render() [2/2]
void Hud::render (GLfloat r, GLfloat g, GLfloat b, GLfloat a, void * font, GLint x, GLint y, const char * s, ...) virtual
hud rendering
Definition at line 67 of file hud.cpp.
References bitmap_output(), DBG_FORCE, g, Pref::height3D, Global::pref, trace(), visible, and Pref::width3D.
toggle()
void Hud::toggle () virtual
Definition at line 44 of file hud.cpp.
References visible.
Member Data Documentation
visible
bool Hud::visible private
Definition at line 31 of file hud.hpp.
Referenced by Hud(), isVisible(), render(), and toggle().
The documentation for this class was generated from the following files:
src/vgl/hud.hpp
src/vgl/hud.cpp