VREng: Bap Class Reference
Bap Class Reference
Bap class Body Animator Parameter.
#include <bap.hpp>
Public Member Functions
Bap ()
constructor
virtual ~Bap ()
destructor
virtual uint8_t getType () const
Returns stream type.
virtual int readFrame (char *line)
Parses and reads header and data of a frame.
virtual bool is (int param) const
Checks bit indexed by param.
virtual GLfloat get (int param) const
Gets a Bap angle indexed by param.
virtual GLfloat getFap (int param) const
Gets a Fap angle indexed by param.
virtual void jpRX (int param, uint8_t model)
Rotates around X axis at this Joint Point.
virtual void jpRY (int param, uint8_t model)
Rotates around Y axis at this Joint Point.
virtual void jpRZ (int param, uint8_t model)
Rotates around Z axis at this Joint Point.
Protected Member Functions
virtual void resetMask (int num)
Resets bit mask.
virtual bool equalLast (int param)
Checks whether same bap value.
virtual void copyLast (int param)
Saves last bap.
Protected Attributes
int bit [NUM_BAPS_V32+1]
bap/fap bit mask
int ba [NUM_BAPS_V32+1]
baps angles
int balast [NUM_BAPS_V32+1]
last baps angles
int fa [NUM_FAPS+1]
faps angles
Private Attributes
int num_baps
number of bap
uint8_t bfflag
stream type bap-3.1, bap-3.2, fap
Detailed Description
Bap class Body Animator Parameter.
Definition at line 171 of file bap.hpp.
Constructor & Destructor Documentation
Bap()
Bap::Bap ()
constructor
Definition at line 30 of file bap.cpp.
References ba, balast, bfflag, bit, fa, num_baps, NUM_BAPS_V32, and NUM_FAPS.
~Bap()
virtual Bap::~Bap () inline virtual
destructor
Definition at line 179 of file bap.hpp.
Member Function Documentation
copyLast()
void Bap::copyLast (int param) protected virtual
Saves last bap.
Definition at line 74 of file bap.cpp.
References ba, and balast.
Referenced by jpRX(), jpRY(), and jpRZ().
equalLast()
bool Bap::equalLast (int param) protected virtual
Checks whether same bap value.
Definition at line 69 of file bap.cpp.
References ba, and balast.
get()
GLfloat Bap::get (int param) const virtual
Gets a Bap angle indexed by param.
Definition at line 59 of file bap.cpp.
References ba.
Referenced by Body::animate().
getFap()
GLfloat Bap::getFap (int param) const virtual
Gets a Fap angle indexed by param.
Definition at line 64 of file bap.cpp.
References fa.
Referenced by Android::changePermanent().
getType()
uint8_t Bap::getType () const virtual
Returns stream type.
Definition at line 49 of file bap.cpp.
References bfflag.
Referenced by Android::changePermanent().
is()
bool Bap::is (int param) const virtual
Checks bit indexed by param.
Definition at line 54 of file bap.cpp.
References bit.
Referenced by Body::animate(), and Android::changePermanent().
jpRX()
void Bap::jpRX (int param, uint8_t model) virtual
Rotates around X axis at this Joint Point.
Definition at line 79 of file bap.cpp.
References ba, copyLast(), MODEL_OBJ, and MODEL_OFF.
Referenced by Body::display().
jpRY()
void Bap::jpRY (int param, uint8_t model) virtual
Rotates around Y axis at this Joint Point.
Definition at line 92 of file bap.cpp.
References ba, copyLast(), MODEL_OBJ, and MODEL_OFF.
Referenced by Body::display().
jpRZ()
void Bap::jpRZ (int param, uint8_t model) virtual
Rotates around Z axis at this Joint Point.
Definition at line 105 of file bap.cpp.
References ba, copyLast(), MODEL_OBJ, and MODEL_OFF.
Referenced by Body::display().
readFrame()
int Bap::readFrame (char * line) virtual
Parses and reads header and data of a frame.
Definition at line 117 of file bap.cpp.
References ba, BAPV31_DIV, BAPV32_DIV, bfflag, bit, DBG_MAN, error(), fa, FAPV20_DIV, FAPV21_DIV, HEAD_BAP_V31, HEAD_BAP_V32, HEAD_FAP_V20, HEAD_FAP_V21, num_baps, NUM_BAPS_V31, NUM_BAPS_V32, NUM_FAPS, resetMask(), stringcmp(), TR_FRONTAL, TR_VERTICAL, trace(), TYPE_BAP_V31, TYPE_BAP_V32, TYPE_FAP_V20, and TYPE_FAP_V21.
Referenced by Android::changePermanent().
resetMask()
void Bap::resetMask (int num) protected virtual
Resets bit mask.
Definition at line 44 of file bap.cpp.
References bit.
Referenced by readFrame().
Member Data Documentation
ba
int Bap::ba[NUM_BAPS_V32+1] protected
baps angles
Definition at line 207 of file bap.hpp.
Referenced by Bap(), copyLast(), equalLast(), get(), jpRX(), jpRY(), jpRZ(), and readFrame().
balast
int Bap::balast[NUM_BAPS_V32+1] protected
last baps angles
Definition at line 208 of file bap.hpp.
Referenced by Bap(), copyLast(), and equalLast().
bfflag
uint8_t Bap::bfflag private
stream type bap-3.1, bap-3.2, fap
Definition at line 175 of file bap.hpp.
Referenced by Bap(), getType(), and readFrame().
bit
int Bap::bit[NUM_BAPS_V32+1] protected
bap/fap bit mask
Definition at line 206 of file bap.hpp.
Referenced by Bap(), is(), readFrame(), and resetMask().
fa
int Bap::fa[NUM_FAPS+1] protected
faps angles
Definition at line 209 of file bap.hpp.
Referenced by Bap(), getFap(), and readFrame().
num_baps
int Bap::num_baps private
number of bap
Definition at line 174 of file bap.hpp.
Referenced by Bap(), and readFrame().
The documentation for this class was generated from the following files:
src/model/bap.hpp
src/model/bap.cpp