VREng: Texture Class Reference
Texture Class Reference
Texture class describes a texture entry in the memory cache.
#include <texture.hpp>
Public Member Functions
Texture (const char *url)
Texture ()
Constructor.
virtual ~Texture ()
Destructor.
GLuint get (const char *url, WObject *wo)
Gets a texture from the cache.
void setMime (char *p)
copy mime type
Static Public Member Functions
static void httpReader (void *_tex, Http *_http)
Downloads a texture.
static void initCache ()
Initializes the texture cache.
static void closeCache ()
Close the texture cache.
static bool check (const char *url)
Check url integity.
static GLuint exist (const char *url)
Check existence of texture integity.
static GLuint getid ()
Gets texture id.
static GLuint getFromCache (const char *url)
Gets a texture from the cache.
static GLuint current ()
Gets current texture id.
static GLuint getIdByUrl (const char *url)
Gets a texture id by its url.
static GLuint getIdByObject (WObject *wo)
Gets a texture id by its object.
static Texture * getEntryByUrl (const char *url)
Gets a tc by its url.
static Texture * getEntryById (GLuint texid)
Gets a texture by its texture id.
static char * getUrlById (GLuint texid)
Gets a texture url by its texture id.
static void update ()
Updates textures (resizing)
static void listTextures ()
List textureList.
Public Attributes
GLuint id
texture id
class Http * http
http handle
class Img * img
img structure
class Solid * solid
class WObject * object
char url [URL_LEN]
url where is the texture
char mime [MIME_LEN]
mime type of the texture
Private Attributes
bool loaded
load flag
Friends
class HttpThread
class Solid
Detailed Description
Texture class describes a texture entry in the memory cache.
Definition at line 38 of file texture.hpp.
Constructor & Destructor Documentation
Texture() [1/2]
Texture::Texture (const char * url)
Definition at line 167 of file texture.cpp.
References Format::getLoaderByUrl(), Http::httpOpen(), IMG_GIF, last_texid, new_texture, and textureList.
Texture() [2/2]
Texture::Texture ()
Constructor.
Definition at line 190 of file texture.cpp.
References new_texture, and textureList.
~Texture()
Texture::~Texture () virtual
Destructor.
Definition at line 202 of file texture.cpp.
References del_texture.
Member Function Documentation
check()
bool Texture::check (const char * url) static
Check url integity.
Definition at line 207 of file texture.cpp.
References error().
closeCache()
void Texture::closeCache () static
Close the texture cache.
Definition at line 46 of file texture.cpp.
References default_img.
Referenced by Render::quit().
current()
GLuint Texture::current () static
Gets current texture id.
Definition at line 274 of file texture.cpp.
References last_texid.
Referenced by Flag::inits().
exist()
GLuint Texture::exist (const char * url) static
Check existence of texture integity.
Definition at line 219 of file texture.cpp.
References textureList.
get()
GLuint Texture::get (const char * url, WObject * wo)
Gets a texture from the cache.
Definition at line 229 of file texture.cpp.
getEntryById()
Texture * Texture::getEntryById (GLuint texid) static
Gets a texture by its texture id.
Definition at line 288 of file texture.cpp.
References textureList.
Referenced by Icon::Icon(), and Flare::setTexture().
getEntryByUrl()
Texture * Texture::getEntryByUrl (const char * url) static
Gets a tc by its url.
Definition at line 280 of file texture.cpp.
References textureList.
getFromCache()
GLuint Texture::getFromCache (const char * url) static
Gets a texture from the cache.
Definition at line 237 of file texture.cpp.
References Format::getLoaderByUrl(), Http::httpOpen(), IMG_GIF, last_texid, and texture.
Referenced by X3d::browseX3dTree(), Body::loadBodyParts(), _3ds::loadTexture(), Ase::loadTexture(), Obj::loadTexture(), Flare::loadTextures(), Model::parser(), Solid::solidParser(), and Solid::statueParser().
getid()
GLuint Texture::getid () static
Gets texture id.
Definition at line 258 of file texture.cpp.
References default_img, g, GL_CLAMP_TO_EDGE, Img::height, Img::pixmap, Global::pref, Pref::quality3D, and Img::width.
getIdByObject()
GLuint Texture::getIdByObject (WObject * wo) static
Gets a texture id by its object.
Definition at line 303 of file texture.cpp.
References textureList.
Referenced by Movie::inits().
getIdByUrl()
GLuint Texture::getIdByUrl (const char * url) static
Gets a texture id by its url.
Definition at line 295 of file texture.cpp.
References textureList.
Referenced by Icon::Icon().
getUrlById()
char * Texture::getUrlById (GLuint texid) static
Gets a texture url by its texture id.
Definition at line 310 of file texture.cpp.
References textureList.
Referenced by Movie::inits().
httpReader()
void Texture::httpReader (void * _tex, Http * _http) static
Downloads a texture.
Definition at line 121 of file texture.cpp.
References DBG_IMG, Format::getLoaderByMime(), Format::getLoaderByUrl(), http, img, IMG_BMP, IMG_DDS, IMG_GIF, IMG_JPG, IMG_NULL, IMG_PCX, IMG_PGM, IMG_PNG, IMG_PPM, IMG_PSD, IMG_SGI, IMG_TGA, IMG_TIF, IMG_XBM, IMG_XPM, Img::loadBMP(), Img::loadDDS(), loaded, Img::loadGIF(), Img::loadJPG(), Img::loadPCX(), Img::loadPGM(), Img::loadPNG(), Img::loadPPM(), Img::loadPSD(), Img::loadSGI(), Img::loadTGA(), Img::loadTIF(), Img::loadXBM(), Img::loadXPM(), lockMutex(), mime, readImg(), tex_pmutex, trace(), unlockMutex(), url, and warning().
initCache()
void Texture::initCache () static
Initializes the texture cache.
Definition at line 40 of file texture.cpp.
References default_img, Img::init(), initMutex(), and tex_pmutex.
Referenced by Render::Render().
listTextures()
void Texture::listTextures () static
List textureList.
Definition at line 327 of file texture.cpp.
References error(), and textureList.
setMime()
void Texture::setMime (char * p)
copy mime type
Definition at line 317 of file texture.cpp.
References error(), and MIME_LEN.
Referenced by HttpThread::connection().
update()
void Texture::update () static
Updates textures (resizing)
Definition at line 52 of file texture.cpp.
References error(), Img::height, lockMutex(), MAX, offset, Img::pixmap, Img::resize(), Img::RGB, Img::SIDE_SIZE, tex_pmutex, textureList, unlockMutex(), and Img::width.
Referenced by Render::render().
Friends And Related Function Documentation
HttpThread
friend class HttpThread friend
Definition at line 39 of file texture.hpp.
Solid
friend class Solid friend
Definition at line 40 of file texture.hpp.
Member Data Documentation
http
class Http* Texture::http
http handle
Definition at line 47 of file texture.hpp.
Referenced by Reader::downloadInCache(), httpReader(), Img::loadBMP(), Img::loadDDS(), Img::loadGIF(), Img::loadJPG(), Img::loadPCX(), Img::loadPGM(), Img::loadPNG(), Img::loadPPM(), Img::loadPSD(), Img::loadSGI(), Img::loadTGA(), Img::loadXBM(), Img::loadXPM(), and readImg().
id
GLuint Texture::id
texture id
Definition at line 46 of file texture.hpp.
Referenced by Solid::solidParser(), and Solid::statueParser().
img
class Img* Texture::img
img structure
Definition at line 48 of file texture.hpp.
Referenced by httpReader(), and Flare::setTexture().
loaded
bool Texture::loaded private
load flag
Definition at line 43 of file texture.hpp.
Referenced by httpReader().
mime
char Texture::mime[MIME_LEN]
mime type of the texture
Definition at line 52 of file texture.hpp.
Referenced by httpReader().
object
class WObject* Texture::object
Definition at line 50 of file texture.hpp.
Referenced by Solid::solidParser(), and Solid::statueParser().
solid
class Solid* Texture::solid
Definition at line 49 of file texture.hpp.
Referenced by Solid::solidParser().
url
char Texture::url[URL_LEN]
url where is the texture
Definition at line 51 of file texture.hpp.
Referenced by Reader::downloadInCache(), Reader::getFilename(), httpReader(), Icon::Icon(), Img::loadBMP(), Img::loadDDS(), Img::loadGIF(), Img::loadJPG(), Img::loadPCX(), Img::loadPGM(), Img::loadPNG(), Img::loadPPM(), Img::loadPSD(), Img::loadSGI(), Img::loadTGA(), Img::loadXBM(), and Img::loadXPM().
The documentation for this class was generated from the following files:
src/texture/texture.hpp
src/texture/texture.cpp