VREng: Txf Class Reference
Txf Class Reference
Txf class.
#include <txf.hpp>
Public Member Functions
Txf (const char *url)
constructor
virtual ~Txf ()
destructor
virtual void bindFontTexture ()
bind texture
virtual GLuint establishTexture (GLuint texobj, GLboolean setupMipmaps)
build texture
virtual void renderString (const char *string, int len)
render string
virtual Txf * getByUrl (const char *url)
get Txf by its url
virtual Txf * getByNumber (int num)
get Txf by its number
Static Public Member Functions
static Txf * getFromCache (const char *url)
get Txf from cache or downloading
static uint16_t getCurrentNumber ()
get Txf current font number
Private Member Functions
virtual void renderGlyph (int c)
render one character
virtual const char * getUrl () const
Gets url name.
virtual TexGlyphVertexInfo * getTCVI (int c)
Static Private Member Functions
static void httpReader (void *atexfont, class Http *http)
http texfont loader
static const char * errorString ()
Private Attributes
int num
Txf number.
char url [URL_LEN]
font url
Txf * next
next Txf
struct TexFont * texfont
texfont ptr
Static Private Attributes
static std::list< Txf * > txfList
txf list
Detailed Description
Txf class.
Definition at line 78 of file txf.hpp.
Constructor & Destructor Documentation
Txf()
Txf::Txf (const char * url)
constructor
Definition at line 39 of file txf.cpp.
References WObject::num, and txf_number.
~Txf()
Txf::~Txf () virtual
destructor
Definition at line 45 of file txf.cpp.
Member Function Documentation
bindFontTexture()
void Txf::bindFontTexture () virtual
bind texture
Definition at line 283 of file txf.cpp.
Referenced by Text::render().
errorString()
const char * Txf::errorString () static private
Definition at line 330 of file txf.cpp.
References lastError.
establishTexture()
GLuint Txf::establishTexture (GLuint texobj, GLboolean setupMipmaps) virtual
build texture
Definition at line 256 of file txf.cpp.
References gluBuild2DMipmaps(), and TexFont::texobj.
Referenced by Text::loadFont().
getByNumber()
Txf * Txf::getByNumber (int num) virtual
get Txf by its number
Definition at line 318 of file txf.cpp.
getByUrl()
Txf * Txf::getByUrl (const char * url) virtual
get Txf by its url
Definition at line 311 of file txf.cpp.
getCurrentNumber()
uint16_t Txf::getCurrentNumber () static
get Txf current font number
Definition at line 325 of file txf.cpp.
References txf_number.
getFromCache()
Txf * Txf::getFromCache (const char * url) static
get Txf from cache or downloading
Definition at line 58 of file txf.cpp.
References DBG_IMG, Http::httpOpen(), and trace().
Referenced by Text::loadFont().
getTCVI()
TexGlyphVertexInfo * Txf::getTCVI (int c) private virtual
Definition at line 230 of file txf.cpp.
References error(), TexFont::min_glyph, and TexFont::tgvi.
getUrl()
const char * Txf::getUrl () const private virtual
Gets url name.
Definition at line 77 of file txf.cpp.
Referenced by httpReader().
httpReader()
void Txf::httpReader (void * atexfont, class Http * http) static private
http texfont loader
Definition at line 82 of file txf.cpp.
References TexGlyphInfo::advance, TexGlyphVertexInfo::advance, TexGlyphInfo::c, File::closeFile(), DBG_IMG, error(), EXPECT, getUrl(), TexGlyphInfo::height, lastError, TexFont::lut, TexFont::max_ascent, TexFont::max_descent, TexFont::min_glyph, TexFont::num_glyphs, Cache::openCache(), TexFont::range, SWAPL, SWAPS, TexGlyphVertexInfo::t0, TexGlyphVertexInfo::t1, TexGlyphVertexInfo::t2, TexGlyphVertexInfo::t3, TexFont::tex_height, TexFont::tex_width, texfont, TexFont::teximage, TexFont::tgi, TexFont::tgvi, trace(), TXF_FORMAT_BITMAP, TXF_FORMAT_BYTE, TexGlyphVertexInfo::v0, TexGlyphVertexInfo::v1, TexGlyphVertexInfo::v2, TexGlyphVertexInfo::v3, TexGlyphInfo::width, TexGlyphInfo::x, TexGlyphInfo::xoffset, TexGlyphInfo::y, and TexGlyphInfo::yoffset.
renderGlyph()
void Txf::renderGlyph (int c) private virtual
render one character
Definition at line 288 of file txf.cpp.
References TexGlyphVertexInfo::advance, TexGlyphVertexInfo::t0, TexGlyphVertexInfo::t1, TexGlyphVertexInfo::t2, TexGlyphVertexInfo::t3, TexFont::tgvi, TexGlyphVertexInfo::v0, TexGlyphVertexInfo::v1, TexGlyphVertexInfo::v2, and TexGlyphVertexInfo::v3.
renderString()
void Txf::renderString (const char * string, int len) virtual
render string
Definition at line 306 of file txf.cpp.
Referenced by Text::render().
Member Data Documentation
next
Txf* Txf::next private
next Txf
Definition at line 85 of file txf.hpp.
num
int Txf::num private
Txf number.
Definition at line 83 of file txf.hpp.
texfont
struct TexFont* Txf::texfont private
texfont ptr
Definition at line 86 of file txf.hpp.
Referenced by httpReader().
txfList
list< Txf * > Txf::txfList static private
txf list
Definition at line 81 of file txf.hpp.
url
char Txf::url[URL_LEN] private
font url
Definition at line 84 of file txf.hpp.
The documentation for this class was generated from the following files:
src/texture/txf.hpp
src/texture/txf.cpp