VREng: Ase Class Reference
Ase Class Reference
This class holds all the data and function for loading in a .Ase file.
#include <ase.hpp>
Public Member Functions
Ase (const char *url)
Constructor.
virtual ~Ase ()
Destructor.
virtual void setScale (float scale)
Sets the scale.
virtual float getRadius ()
Gets the radius.
virtual GLint displaylist ()
Draws in displaylist.
virtual void render ()
Model rendering.
Private Member Functions
virtual void draw ()
Model drawing.
virtual bool loadFromFile (FILE *f)
File loader.
virtual const char * getUrl () const
get an Url
virtual bool importModel (tASEModel *pModel)
called to load in an .ase file by the file name
virtual bool importTextures ()
virtual int loadTexture (const char *imgFile)
virtual void bindTexture2D (int textureId)
virtual void readFile (tASEModel *pModel)
This is the main loop that parses the .ase file.
virtual int getObjectCount ()
This returns the number of objects in the .ase file.
virtual int getMaterialCount ()
This returns the number of materials in the .ase file.
virtual void getTextureInfo (tASEMaterialInfo *pTexture, int desiredMaterial)
This fills in the texture information for a desired texture.
virtual void moveToObject (int desiredObject)
This moves our file pointer to the desired object.
virtual float readFloat ()
This reads in a float from the file.
virtual void readObjectInfo (tASEObject *pObject, int desiredObject)
This reads a desired object's information (face, vertex and texture coord counts)
virtual void getTextureName (tASEMaterialInfo *pTexture)
This gets the name of the texture.
virtual void getMaterialName (tASEMaterialInfo *pTexture)
This gets the name of the material.
virtual void readObjectData (tASEModel *pModel, tASEObject *pObject, int desiredObject)
This loads all the data for the desired object.
virtual void getData (tASEModel *pModel, tASEObject *pObject, char *strDesiredData, int desiredObject)
This is the main load loop inside of readObjectData() that calls smaller load functions.
virtual void readVertex (tASEObject *pObject)
This reads in a vertice from the file.
virtual void readTextureVertex (tASEObject *pObject, tASEMaterialInfo texture)
This reads in a texture coordinate from the file.
virtual void readFace (tASEObject *pObject)
This reads in the vertex indices for a face.
virtual void readTextureFace (tASEObject *pObject)
This reads in texture coordinate indices for a face.
virtual void computeNormals (tASEModel *pModel)
This computes the vertex normals for our objects.
Static Private Member Functions
static void httpReader (void *aase, class Http *http)
Private Attributes
tASEModel ASEModel
model ptr
bool loaded
flag loaded or not
float currentScale
current scale
float desiredScale
desired scale
GLint dlist
display list
char * url
ase url
FILE * fp
file pointer to load the .ase file
Detailed Description
This class holds all the data and function for loading in a .Ase file.
Definition at line 94 of file ase.hpp.
Constructor & Destructor Documentation
Ase()
Ase::Ase (const char * url)
Constructor.
Definition at line 65 of file ase.cpp.
References displaylist(), Http::httpOpen(), httpReader(), and url.
~Ase()
Ase::~Ase () virtual
Destructor.
Definition at line 83 of file ase.cpp.
References ASEModel, dlist, tASEModel::numOfObjects, tASEModel::pObject, and url.
Member Function Documentation
bindTexture2D()
void Ase::bindTexture2D (int textureId) private virtual
Definition at line 113 of file ase.cpp.
Referenced by draw().
computeNormals()
void Ase::computeNormals (tASEModel * pModel) private virtual
This computes the vertex normals for our objects.
This function computes the normals and vertex normals of the objects.
Definition at line 656 of file ase.cpp.
References AddVector(), Cross(), DivideVectorByScaler(), Normalize(), tASEObject::numOfFaces, tASEModel::numOfObjects, tASEObject::numOfVerts, tASEObject::pFaces, tASEObject::pNormals, tASEModel::pObject, tASEObject::pVerts, Vector(), and tASEFace::vertIndex.
Referenced by importModel().
displaylist()
GLint Ase::displaylist () virtual
Draws in displaylist.
Definition at line 197 of file ase.cpp.
References dlist, and draw().
Referenced by Ase().
draw()
void Ase::draw () private virtual
Model drawing.
Definition at line 206 of file ase.cpp.
References ASEModel, tASEObject::bHasTexture, bindTexture2D(), tASEFace::coordIndex, currentScale, desiredScale, loaded, tASEObject::materialID, tASEObject::numOfFaces, tASEModel::numOfObjects, tASEObject::pFaces, tASEModel::pMaterials, tASEObject::pNormals, tASEModel::pObject, tASEObject::pTexVerts, tASEObject::pVerts, setScale(), tASEFace::vertIndex, Vec3::x, Vec2::x, Vec3::y, Vec2::y, and Vec3::z.
Referenced by displaylist().
getData()
void Ase::getData (tASEModel * pModel, tASEObject * pObject, char * strDesiredData, int desiredObject) private virtual
This is the main load loop inside of readObjectData() that calls smaller load functions.
loop for reading in the object data
Definition at line 537 of file ase.cpp.
References FACE, fp, MATERIAL_ID, tASEObject::materialID, moveToObject(), OBJECT, tASEModel::pMaterials, readFace(), readFloat(), readTextureFace(), readTextureVertex(), readVertex(), TFACE, TVERTEX, and VERTEX.
Referenced by readObjectData().
getMaterialCount()
int Ase::getMaterialCount () private virtual
This returns the number of materials in the .ase file.
returns the total material count for the .ase file
Definition at line 341 of file ase.cpp.
References fp, and MATERIAL_COUNT.
Referenced by readFile().
getMaterialName()
void Ase::getMaterialName (tASEMaterialInfo * pTexture) private virtual
This gets the name of the material.
reads in the material name of the object
Definition at line 499 of file ase.cpp.
References fp, and tASEMaterialInfo::strName.
Referenced by getTextureInfo().
getObjectCount()
int Ase::getObjectCount () private virtual
This returns the number of objects in the .ase file.
returns the total object count in the .ase file
Definition at line 325 of file ase.cpp.
References fp, and OBJECT.
Referenced by readFile().
getRadius()
float Ase::getRadius () virtual
Gets the radius.
Definition at line 134 of file ase.cpp.
References ASEModel, tASEObject::numOfFaces, tASEModel::numOfObjects, tASEObject::pFaces, tASEModel::pObject, tASEObject::pVerts, tASEFace::vertIndex, Vec3::x, Vec3::y, and Vec3::z.
Referenced by Model::scaler().
getTextureInfo()
void Ase::getTextureInfo (tASEMaterialInfo * pTexture, int desiredMaterial) private virtual
This fills in the texture information for a desired texture.
reads in the information about the desired material
Definition at line 360 of file ase.cpp.
References tASEMaterialInfo::fColor, fp, getMaterialName(), getTextureName(), MATERIAL, MATERIAL_COLOR, MATERIAL_NAME, readFloat(), TEXTURE, UTILE, tASEMaterialInfo::uTile, VTILE, and tASEMaterialInfo::vTile.
Referenced by readFile().
getTextureName()
void Ase::getTextureName (tASEMaterialInfo * pTexture) private virtual
This gets the name of the texture.
reads in the filename of the texture assigned to the object
Definition at line 492 of file ase.cpp.
References fp, and tASEMaterialInfo::strFile.
Referenced by getTextureInfo().
getUrl()
const char * Ase::getUrl () const private virtual
get an Url
Definition at line 172 of file ase.cpp.
References url.
Referenced by httpReader().
httpReader()
void Ase::httpReader (void * aase, class Http * http) static private
Definition at line 177 of file ase.cpp.
References getUrl(), loadFromFile(), and Cache::openCache().
Referenced by Ase().
importModel()
bool Ase::importModel (tASEModel * pModel) private virtual
called to load in an .ase file by the file name
Definition at line 265 of file ase.cpp.
References File::closeFile(), computeNormals(), fp, and readFile().
Referenced by loadFromFile().
importTextures()
bool Ase::importTextures () private virtual
Definition at line 95 of file ase.cpp.
References ASEModel, DBG_VGL, error(), loadTexture(), tASEModel::numOfMaterials, tASEModel::pMaterials, and trace().
Referenced by loadFromFile().
loadFromFile()
bool Ase::loadFromFile (FILE * f) private virtual
File loader.
Definition at line 74 of file ase.cpp.
References ASEModel, error(), fp, importModel(), importTextures(), loaded, and warning().
Referenced by httpReader().
loadTexture()
int Ase::loadTexture (const char * imgFile) private virtual
Definition at line 121 of file ase.cpp.
References DBG_VGL, end, Texture::getFromCache(), trace(), and url.
Referenced by importTextures().
moveToObject()
void Ase::moveToObject (int desiredObject) private virtual
This moves our file pointer to the desired object.
moves the filepointer in the .ase file to the desired object
Definition at line 420 of file ase.cpp.
References fp, and OBJECT.
Referenced by getData(), readFile(), and readObjectInfo().
readFace()
void Ase::readFace (tASEObject * pObject) private virtual
This reads in the vertex indices for a face.
reads in the indices to the array of vertices
Definition at line 628 of file ase.cpp.
References fp, tASEObject::pFaces, and tASEFace::vertIndex.
Referenced by getData().
readFile()
void Ase::readFile (tASEModel * pModel) private virtual
This is the main loop that parses the .ase file.
reads the data for every object and it's associated material
Definition at line 277 of file ase.cpp.
References getMaterialCount(), getObjectCount(), getTextureInfo(), moveToObject(), tASEModel::numOfMaterials, tASEModel::numOfObjects, tASEModel::pMaterials, tASEModel::pObject, readObjectData(), and readObjectInfo().
Referenced by importModel().
readFloat()
float Ase::readFloat () private virtual
This reads in a float from the file.
reads in and returns a float from the .ase file
Definition at line 444 of file ase.cpp.
References fp.
Referenced by getData(), and getTextureInfo().
readObjectData()
void Ase::readObjectData (tASEModel * pModel, tASEObject * pObject, int desiredObject) private virtual
This loads all the data for the desired object.
calls the functions that query and read in the desired data
Definition at line 506 of file ase.cpp.
References FACE, getData(), MATERIAL_ID, TEXTURE, TFACE, TVERTEX, UTILE, VERTEX, and VTILE.
Referenced by readFile().
readObjectInfo()
void Ase::readObjectInfo (tASEObject * pObject, int desiredObject) private virtual
This reads a desired object's information (face, vertex and texture coord counts)
reads in the information about the object, but not the data
Definition at line 453 of file ase.cpp.
References fp, moveToObject(), NUM_FACES, NUM_TVERTEX, NUM_VERTEX, tASEObject::numOfFaces, tASEObject::numOfVerts, tASEObject::numTexVertex, OBJECT, tASEObject::pFaces, tASEObject::pTexVerts, and tASEObject::pVerts.
Referenced by readFile().
readTextureFace()
void Ase::readTextureFace (tASEObject * pObject) private virtual
This reads in texture coordinate indices for a face.
reads in the indices to the texture coordinate array
Definition at line 642 of file ase.cpp.
References tASEFace::coordIndex, fp, and tASEObject::pFaces.
Referenced by getData().
readTextureVertex()
void Ase::readTextureVertex (tASEObject * pObject, tASEMaterialInfo texture) private virtual
This reads in a texture coordinate from the file.
reads in the texture coordinates
Definition at line 608 of file ase.cpp.
References tASEObject::bHasTexture, fp, tASEObject::pTexVerts, texture, Vec2::x, and Vec2::y.
Referenced by getData().
readVertex()
void Ase::readVertex (tASEObject * pObject) private virtual
This reads in a vertice from the file.
reads in the vertices for the object
Definition at line 589 of file ase.cpp.
References fp, tASEObject::pVerts, Vec3::x, Vec3::y, and Vec3::z.
Referenced by getData().
render()
void Ase::render () virtual
Model rendering.
Definition at line 186 of file ase.cpp.
References currentScale, dlist, and loaded.
Referenced by Model::render().
setScale()
void Ase::setScale (float scale) virtual
Sets the scale.
Definition at line 153 of file ase.cpp.
References ASEModel, currentScale, desiredScale, loaded, tASEModel::numOfObjects, tASEObject::numOfVerts, tASEModel::pObject, tASEObject::pVerts, Vec3::x, Vec3::y, and Vec3::z.
Referenced by draw(), and Model::scaler().
Member Data Documentation
ASEModel
tASEModel Ase::ASEModel private
model ptr
Definition at line 97 of file ase.hpp.
Referenced by draw(), getRadius(), importTextures(), loadFromFile(), setScale(), and ~Ase().
currentScale
float Ase::currentScale private
current scale
Definition at line 100 of file ase.hpp.
Referenced by draw(), render(), and setScale().
desiredScale
float Ase::desiredScale private
desired scale
Definition at line 101 of file ase.hpp.
Referenced by draw(), and setScale().
dlist
GLint Ase::dlist private
display list
Definition at line 102 of file ase.hpp.
Referenced by displaylist(), render(), and ~Ase().
fp
FILE* Ase::fp private
file pointer to load the .ase file
Definition at line 104 of file ase.hpp.
Referenced by getData(), getMaterialCount(), getMaterialName(), getObjectCount(), getTextureInfo(), getTextureName(), importModel(), loadFromFile(), moveToObject(), readFace(), readFloat(), readObjectInfo(), readTextureFace(), readTextureVertex(), and readVertex().
loaded
bool Ase::loaded private
flag loaded or not
Definition at line 99 of file ase.hpp.
Referenced by draw(), loadFromFile(), render(), and setScale().
url
char* Ase::url private
ase url
Definition at line 103 of file ase.hpp.
Referenced by Ase(), getUrl(), loadTexture(), and ~Ase().
The documentation for this class was generated from the following files:
src/model/ase.hpp
src/model/ase.cpp