VREng: Img Class Reference
Img Class Reference
Img class.
#include <img.hpp>
Public Types
enum internalchannel_t { BW = 1, LA, RGB, RGBA }
! we only deal with 8 bits RGB images
enum { FIX, ANIM }
Public Member Functions
Img (uint16_t width, uint16_t height, uint8_t channel)
Img constructor.
Img (uint16_t width, uint16_t height, uint8_t channel, int32_t nummipmaps, uint32_t size)
Constructors.
virtual ~Img ()
Destructor.
virtual bool wellSized ()
check if image is well sized or not.
Img * resize (uint16_t width_new, uint16_t height_new)
Resizes image.
Static Public Member Functions
static Img * init ()
set a default image.
static Img * loadPPM (void *tex, ImageReader rf)
Image readers.
static Img * loadPGM (void *tex, ImageReader rf)
static Img * loadGIF (void *tex, ImageReader rf)
static Img * loadJPG (void *tex, ImageReader rf)
HAVE_JPEG.
static Img * loadPNG (void *tex, ImageReader rf)
static Img * loadPCX (void *tex, ImageReader rf)
static Img * loadSGI (void *tex, ImageReader rf)
SGI loader.
static Img * loadBMP (void *tex, ImageReader rf)
Load a 24bpp BMP image.
static Img * loadTGA (void *tex, ImageReader rf)
TGA info typedef struct { char idlength; char colourmaptype; char datatypecode; short int colourmaporigin; short int colourmaplength; char colourmapdepth; short int x_origin; short int y_origin; short width; short height; char bitsperpixel; char imagedescriptor; } TGAINFO;.
static Img * loadDDS (void *tex, ImageReader rf)
DDS loader.
static Img * loadTIF (void *tex, ImageReader rf)
Load a TIFF image.
static Img * loadXPM (void *tex, ImageReader rf)
static Img * loadXBM (void *tex, ImageReader rf)
static Img * loadPSD (void *tex, ImageReader rf)
static void saveJPG (const char *file, GLint width, GLint height, GLint quality, const GLubyte *buffer)
Image writers.
static void savePNG (const char *file, GLint width, GLint height)
static void saveTGA (const char *file, GLint width, GLint height, const GLubyte *buffer)
static void savePPM (const char *file, GLenum mode)
Public Attributes
uint16_t width
image width in pixels.
uint16_t height
image height in pixels.
uint8_t channel
bytes per pixel.
int32_t nummipmaps
number of mipmaps.
uint8_t * pixmap
image data.
bool anim
flag still or anim.
Static Public Attributes
static const uint16_t SIDE_SIZE = 256
default image side size.
Private Member Functions
void defaults ()
Set defaults values.
Detailed Description
Img class.
Definition at line 37 of file img.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
FIX
ANIM
Definition at line 58 of file img.hpp.
internalchannel_t
enum Img::internalchannel_t
! we only deal with 8 bits RGB images
Enumerator
BW
black & white.
LA
luninance alpha.
RGB
red green blue.
RGBA
red green blue alpha.
Definition at line 42 of file img.hpp.
Constructor & Destructor Documentation
Img() [1/2]
Img::Img (uint16_t width, uint16_t height, uint8_t channel)
Img constructor.
Definition at line 37 of file img.cpp.
References channel, defaults(), error(), height, pixmap, and width.
Referenced by gifReadScreen(), init(), loadBMP(), loadDDS(), loadJPG(), loadPCX(), loadPGM(), loadPNG(), loadPPM(), loadPSD(), loadSGI(), loadTGA(), loadTIF(), loadXBM(), loadXPM(), and resize().
Img() [2/2]
Img::Img (uint16_t width, uint16_t height, uint8_t channel, int32_t nummipmaps, uint32_t size)
Constructors.
Definition at line 48 of file img.cpp.
References channel, defaults(), error(), height, nummipmaps, pixmap, size, and width.
~Img()
Img::~Img () virtual
Destructor.
Img destructor.
Definition at line 61 of file img.cpp.
References del_image, and pixmap.
Member Function Documentation
defaults()
void Img::defaults () private
Set defaults values.
Definition at line 28 of file img.cpp.
References anim, new_image, nummipmaps, and pixmap.
Referenced by Img().
init()
Img * Img::init () static
set a default image.
Definition at line 68 of file img.cpp.
References channel, default_img, Img(), pixmap, RGB, and SIDE_SIZE.
Referenced by Texture::initCache().
loadBMP()
Img * Img::loadBMP (void * tex, ImageReader rf) static
Load a 24bpp BMP image.
Definition at line 50 of file bmp.cpp.
References File::closeFile(), DBG_IMG, error(), Reader::getFilename(), Reader::getShort(), Reader::getUInt(), height, Texture::http, Img(), Cache::openCache(), pixmap, RGB, trace(), Texture::url, and width.
Referenced by Texture::httpReader().
loadDDS()
Img * Img::loadDDS (void * tex, ImageReader rf) static
DDS loader.
Definition at line 110 of file dds.cpp.
References dds_t::channel, DDSurfaceDesc::channel, File::closeFile(), DBG_IMG, DXT1, DXT3, DXT5, end, error(), DDPixelFormat::fourCC, dds_t::fp, Cache::getFilePath(), GL_COMPRESSED_RGBA_S3TC_DXT1_EXT, GL_COMPRESSED_RGBA_S3TC_DXT3_EXT, GL_COMPRESSED_RGBA_S3TC_DXT5_EXT, dds_t::height, DDSurfaceDesc::height, Texture::http, Img(), dds_t::internal_channel, DDSurfaceDesc::mipMapLevels, dds_t::numMipmaps, Cache::openCache(), pixmap, RGB, RGBA, size, dds_t::texels, trace(), Texture::url, dds_t::width, and DDSurfaceDesc::width.
Referenced by Texture::httpReader().
loadGIF()
Img * Img::loadGIF (void * tex, ImageReader rf) static
Definition at line 64 of file gif.cpp.
References File::closeFile(), g, gifReadBlocks(), gifReadScreen(), gifReadSignature(), Texture::http, Cache::openCache(), and Texture::url.
Referenced by Texture::httpReader().
loadJPG()
Img * Img::loadJPG (void * tex, ImageReader rf) static
HAVE_JPEG.
HAVE_JPEG
Definition at line 118 of file jpg.cpp.
References File::closeFile(), error(), Texture::http, Img(), Cache::openCache(), and Texture::url.
Referenced by Texture::httpReader().
loadPCX()
Img * Img::loadPCX (void * tex, ImageReader rf) static
Definition at line 53 of file pcx.cpp.
References File::closeFile(), error(), g, height, Texture::http, Img(), Cache::openCache(), pixmap, RGB, Texture::url, and width.
Referenced by Texture::httpReader().
loadPGM()
Img * Img::loadPGM (void * tex, ImageReader rf) static
Definition at line 28 of file pgm.cpp.
References File::closeFile(), height, Texture::http, Img(), Cache::openCache(), pixmap, RGB, Texture::url, and width.
Referenced by Texture::httpReader().
loadPNG()
Img * Img::loadPNG (void * tex, ImageReader rf) static
Definition at line 29 of file png.cpp.
References pngRawInfo::Alpha, File::closeFile(), pngRawInfo::Data, DBG_IMG, pngRawInfo::Depth, error(), pngRawInfo::Height, Texture::http, Img(), Cache::openCache(), pixmap, PNG_NOMIPMAP, PNG_SOLID, pngLoadF(), RGB, trace(), Texture::url, and pngRawInfo::Width.
Referenced by Texture::httpReader().
loadPPM()
Img * Img::loadPPM (void * tex, ImageReader rf) static
Image readers.
Definition at line 28 of file ppm.cpp.
References File::closeFile(), height, Texture::http, Img(), Cache::openCache(), pixmap, RGB, Texture::url, and width.
Referenced by Texture::httpReader().
loadPSD()
Img * Img::loadPSD (void * tex, ImageReader rf) static
Definition at line 256 of file psd.cpp.
References channel, File::closeFile(), height, Texture::http, Img(), stbi::img_file, Cache::openCache(), pixmap, psd_load(), RGB, Texture::url, and width.
Referenced by Texture::httpReader().
loadSGI()
Img * Img::loadSGI (void * tex, ImageReader rf) static
SGI loader.
Definition at line 112 of file sgi.cpp.
References bwtorgb(), SgiInfo::channel, File::closeFile(), File::convertLong(), File::convertShort(), DBG_IMG, SgiInfo::fp, getRow(), SgiInfo::height, Texture::http, SgiInfo::imagic, Img(), latorgb(), File::littleEndian(), Cache::openCache(), pixmap, RGB, rgbatorgb(), rgbtorgb(), SgiInfo::rleEnd, SgiInfo::rowSize, SgiInfo::rowStart, SgiInfo::tmp, trace(), SgiInfo::type, Texture::url, and SgiInfo::width.
Referenced by Texture::httpReader().
loadTGA()
Img * Img::loadTGA (void * tex, ImageReader rf) static
TGA info typedef struct { char idlength; char colourmaptype; char datatypecode; short int colourmaporigin; short int colourmaplength; char colourmapdepth; short int x_origin; short int y_origin; short width; short height; char bitsperpixel; char imagedescriptor; } TGAINFO;.
Definition at line 50 of file tga.cpp.
References channel, File::closeFile(), DBG_IMG, height, Texture::http, Img(), Cache::openCache(), pixmap, RGB, size, trace(), Texture::url, and width.
Referenced by Texture::httpReader().
loadTIF()
Img * Img::loadTIF (void * tex, ImageReader rf) static
Load a TIFF image.
Definition at line 33 of file tif.cpp.
References channel, DBG_IMG, Reader::downloadInCache(), error(), Reader::getFilename(), height, Img(), Reader::KEEP_CLOSE, pixmap, RGB, RGBA, trace(), and width.
Referenced by Texture::httpReader().
loadXBM()
Img * Img::loadXBM (void * tex, ImageReader rf) static
Definition at line 39 of file xbm.cpp.
References File::closeFile(), height, hexval(), Texture::http, Img(), Cache::openCache(), pixmap, RGB, Texture::url, and width.
Referenced by Texture::httpReader().
loadXPM()
Img * Img::loadXPM (void * tex, ImageReader rf) static
Definition at line 32 of file xpm.cpp.
References File::closeFile(), error(), Cache::getFilePath(), Texture::http, Img(), Cache::openCache(), pixmap, RGB, size, and Texture::url.
Referenced by Texture::httpReader().
resize()
Img * Img::resize (uint16_t width_new, uint16_t height_new)
Resizes image.
Resize image called by updateTextures TODO: more accurate resampling.
Definition at line 113 of file img.cpp.
References BW, channel, error(), height, Img(), interpol(), NORM16_BITS, NORM8_BITS, NORM_8, pixmap, RGB, RGBA, warning(), and width.
Referenced by Texture::update().
saveJPG()
void Img::saveJPG (const char * file, GLint width, GLint height, GLint quality, const GLubyte * buffer) static
Image writers.
HAVE_JPEG
Definition at line 168 of file jpg.cpp.
References File::closeFile(), height, File::openFile(), TRUE, and width.
Referenced by Render::calculateFov(), and Capture::captureGl2jpg().
savePNG()
void Img::savePNG (const char * file, GLint width, GLint height) static
Definition at line 60 of file png.cpp.
References File::closeFile(), error(), height, File::openFile(), and width.
Referenced by Capture::captureGl2png().
savePPM()
void Img::savePPM (const char * file, GLenum mode) static
Definition at line 62 of file ppm.cpp.
References File::closeFile(), height, File::openFile(), pixmap, RGB, and width.
saveTGA()
void Img::saveTGA (const char * file, GLint width, GLint height, const GLubyte * buffer) static
Definition at line 132 of file tga.cpp.
References File::closeFile(), height, File::openFile(), and width.
wellSized()
bool Img::wellSized () virtual
check if image is well sized or not.
Definition at line 84 of file img.cpp.
References height, SIDE_SIZE, and width.
Member Data Documentation
anim
bool Img::anim
flag still or anim.
Definition at line 56 of file img.hpp.
Referenced by defaults().
channel
uint8_t Img::channel
bytes per pixel.
Definition at line 53 of file img.hpp.
Referenced by Img(), init(), loadPSD(), loadTGA(), loadTIF(), and resize().
height
uint16_t Img::height
image height in pixels.
Definition at line 52 of file img.hpp.
Referenced by Texture::getid(), gifReadImage(), Img(), loadBMP(), loadPCX(), loadPGM(), loadPPM(), loadPSD(), loadTGA(), loadTIF(), loadXBM(), resize(), saveJPG(), savePNG(), savePPM(), saveTGA(), Flare::setTexture(), Texture::update(), and wellSized().
nummipmaps
int32_t Img::nummipmaps
number of mipmaps.
Definition at line 54 of file img.hpp.
Referenced by defaults(), and Img().
pixmap
uint8_t* Img::pixmap
image data.
Definition at line 55 of file img.hpp.
Referenced by defaults(), Texture::getid(), Img(), init(), loadBMP(), loadDDS(), loadPCX(), loadPGM(), loadPNG(), loadPPM(), loadPSD(), loadSGI(), loadTGA(), loadTIF(), loadXBM(), loadXPM(), resize(), savePPM(), Flare::setTexture(), Texture::update(), and ~Img().
SIDE_SIZE
const uint16_t Img::SIDE_SIZE = 256 static
default image side size.
Definition at line 49 of file img.hpp.
Referenced by init(), Texture::update(), and wellSized().
width
uint16_t Img::width
image width in pixels.
Definition at line 51 of file img.hpp.
Referenced by Texture::getid(), gifReadImage(), Img(), loadBMP(), loadPCX(), loadPGM(), loadPPM(), loadPSD(), loadTGA(), loadTIF(), loadXBM(), resize(), saveJPG(), savePNG(), savePPM(), saveTGA(), Flare::setTexture(), Texture::update(), and wellSized().
The documentation for this class was generated from the following files:
src/texture/img.hpp
src/texture/bmp.cpp
src/texture/dds.cpp
src/texture/gif.cpp
src/texture/img.cpp
src/texture/jpg.cpp
src/texture/pcx.cpp
src/texture/pgm.cpp
src/texture/png.cpp
src/texture/ppm.cpp
src/texture/psd.cpp
src/texture/sgi.cpp
src/texture/tga.cpp
src/texture/tif.cpp
src/texture/xbm.cpp
src/texture/xpm.cpp