VREng: _3ds Class Reference
_3ds Class Reference
_3ds class
#include <3ds.hpp>
Public Member Functions
_3ds (const char *url)
Constructor.
virtual ~_3ds ()
Destructor.
virtual void render (float *color)
virtual void render (const Pos &pos, float *color)
Model rendering.
virtual void setScale (float scale)
Changes scale.
virtual float getRadius ()
Gets spheric BB.
virtual GLint displaylist ()
Draws in display list.
Private Member Functions
virtual void draw ()
Model drawing.
virtual bool importModel (t3dsModel *pModel)
virtual bool importTextures ()
virtual int loadTexture (const char *imgFile)
virtual void bindTexture2D (int textureId)
virtual const char * getUrl () const
virtual bool loadFromFile (FILE *f)
virtual int getString (char *)
This reads in a string and saves it in the char array passed in.
virtual void readChunk (tChunk *)
This reads the next chunk.
virtual void processNextChunk (t3dsModel *pModel, tChunk *)
This reads the next large chunk.
virtual void processNextObjectChunk (t3dsModel *pModel, tObject *pObject, tChunk *)
This reads the object chunks.
virtual void processNextMaterialChunk (t3dsModel *pModel, tChunk *)
This reads the material chunks.
virtual void readColorChunk (t3dsMaterialInfo *pMaterial, tChunk *pChunk)
This reads the RGB value for the object's color.
virtual void readVertices (tObject *pObject, tChunk *)
This reads the objects vertices.
virtual void readVertexIndices (tObject *pObject, tChunk *)
This reads the objects face information.
virtual void readUVCoordinates (tObject *pObject, tChunk *)
This reads the texture coodinates of the object.
virtual void readObjectMaterial (t3dsModel *pModel, tObject *pObject, tChunk *pPreviousChunk)
This reads in the material name assigned to the object and sets the materialID.
virtual void computeNormals (t3dsModel *pModel)
This computes the vertex normals for the object (used for lighting)
Static Private Member Functions
static void httpReader (void *_3ds, class Http *http)
Private Attributes
t3dsModel _3dsModel
bool loaded
float currentScale
float desiredScale
GLint dlist
display list
char * url
3ds url
FILE * fp
The file pointer.
Detailed Description
_3ds class
Definition at line 111 of file 3ds.hpp.
Constructor & Destructor Documentation
_3ds()
_3ds::_3ds (const char * url)
Constructor.
Definition at line 70 of file 3ds.cpp.
References _3dsModel, displaylist(), fp, Http::httpOpen(), httpReader(), t3dsModel::numOfMaterials, t3dsModel::numOfObjects, and url.
~_3ds()
_3ds::~_3ds () virtual
Destructor.
Definition at line 83 of file 3ds.cpp.
References _3dsModel, dlist, t3dsModel::numOfObjects, t3dsModel::pObject, and url.
Member Function Documentation
bindTexture2D()
void _3ds::bindTexture2D (int textureId) private virtual
Definition at line 128 of file 3ds.cpp.
Referenced by draw().
computeNormals()
void _3ds::computeNormals (t3dsModel * pModel) private virtual
This computes the vertex normals for the object (used for lighting)
computes the normals and vertex normals of the objects
Definition at line 650 of file 3ds.cpp.
References AddVector(), Cross(), DivideVectorByScaler(), Normalize(), tObject::numOfFaces, t3dsModel::numOfObjects, tObject::numOfVerts, tObject::pFaces, tObject::pNormals, t3dsModel::pObject, tObject::pVerts, Vector(), and t3dsFace::vertIndex.
Referenced by importModel().
displaylist()
GLint _3ds::displaylist () virtual
Draws in display list.
Definition at line 240 of file 3ds.cpp.
References dlist, and draw().
Referenced by _3ds().
draw()
void _3ds::draw () private virtual
Model drawing.
Definition at line 250 of file 3ds.cpp.
References _3dsModel, tObject::bHasTexture, bindTexture2D(), currentScale, desiredScale, loaded, tObject::materialID, tObject::numOfFaces, t3dsModel::numOfObjects, tObject::pFaces, t3dsModel::pMaterials, tObject::pNormals, t3dsModel::pObject, tObject::pTexVerts, tObject::pVerts, setScale(), t3dsFace::vertIndex, Vec3::x, Vec2::x, Vec3::y, Vec2::y, and Vec3::z.
Referenced by displaylist().
getRadius()
float _3ds::getRadius () virtual
Gets spheric BB.
Definition at line 149 of file 3ds.cpp.
References _3dsModel, loaded, tObject::numOfFaces, t3dsModel::numOfObjects, tObject::pFaces, t3dsModel::pObject, tObject::pVerts, t3dsFace::vertIndex, Vec3::x, Vec3::y, and Vec3::z.
Referenced by Model::scaler().
getString()
int _3ds::getString (char * pBuffer) private virtual
This reads in a string and saves it in the char array passed in.
reads in a string of characters
Definition at line 504 of file 3ds.cpp.
References fp.
Referenced by processNextChunk(), and readObjectMaterial().
getUrl()
const char * _3ds::getUrl () const private virtual
Definition at line 190 of file 3ds.cpp.
References url.
Referenced by httpReader().
httpReader()
void _3ds::httpReader (void * _3ds, class Http * http) static private
Definition at line 195 of file 3ds.cpp.
References getUrl(), loadFromFile(), and Cache::openCache().
Referenced by _3ds().
importModel()
bool _3ds::importModel (t3dsModel * pModel) private virtual
Definition at line 304 of file 3ds.cpp.
References File::closeFile(), computeNormals(), error(), fp, tChunk::ID, PRIMARY, processNextChunk(), and readChunk().
Referenced by loadFromFile().
importTextures()
bool _3ds::importTextures () private virtual
Definition at line 104 of file 3ds.cpp.
References _3dsModel, error(), loadTexture(), t3dsModel::numOfMaterials, and t3dsModel::pMaterials.
Referenced by loadFromFile().
loadFromFile()
bool _3ds::loadFromFile (FILE * f) private virtual
Definition at line 95 of file 3ds.cpp.
References _3dsModel, error(), fp, importModel(), importTextures(), loaded, and warning().
Referenced by httpReader().
loadTexture()
int _3ds::loadTexture (const char * imgFile) private virtual
Definition at line 136 of file 3ds.cpp.
References DBG_VGL, end, Texture::getFromCache(), trace(), and url.
Referenced by importTextures().
processNextChunk()
void _3ds::processNextChunk (t3dsModel * pModel, tChunk * pPreviousChunk) private virtual
This reads the next large chunk.
reads the main sections of the .3DS file, then dives deeper with recursion
Definition at line 327 of file 3ds.cpp.
References tChunk::bytesRead, EDITKEYFRAME, error(), fp, getString(), tChunk::ID, tChunk::length, File::localEndian(), MATERIAL, t3dsModel::numOfMaterials, t3dsModel::numOfObjects, OBJECT, OBJECTINFO, t3dsModel::pMaterials, t3dsModel::pObject, processNextMaterialChunk(), processNextObjectChunk(), readChunk(), and VERSION_3DS.
Referenced by importModel().
processNextMaterialChunk()
void _3ds::processNextMaterialChunk (t3dsModel * pModel, tChunk * pPreviousChunk) private virtual
This reads the material chunks.
handles all the information about the material (Texture)
Definition at line 455 of file 3ds.cpp.
References tChunk::bytesRead, fp, tChunk::ID, tChunk::length, MATDIFFUSE, MATMAP, MATMAPFILE, MATNAME, t3dsModel::numOfMaterials, t3dsModel::pMaterials, readChunk(), and readColorChunk().
Referenced by processNextChunk().
processNextObjectChunk()
void _3ds::processNextObjectChunk (t3dsModel * pModel, tObject * pObject, tChunk * pPreviousChunk) private virtual
This reads the object chunks.
handles all the information about the objects in the file
Definition at line 410 of file 3ds.cpp.
References tChunk::bytesRead, fp, tChunk::ID, tChunk::length, OBJECT_FACES, OBJECT_MATERIAL, OBJECT_MESH, OBJECT_UV, OBJECT_VERTICES, readChunk(), readObjectMaterial(), readUVCoordinates(), readVertexIndices(), and readVertices().
Referenced by processNextChunk().
readChunk()
void _3ds::readChunk (tChunk * pChunk) private virtual
This reads the next chunk.
reads in a chunk ID and it's length in bytes
Definition at line 492 of file 3ds.cpp.
References tChunk::bytesRead, fp, tChunk::ID, tChunk::length, and File::localEndian().
Referenced by importModel(), processNextChunk(), processNextMaterialChunk(), processNextObjectChunk(), and readColorChunk().
readColorChunk()
void _3ds::readColorChunk (t3dsMaterialInfo * pMaterial, tChunk * pChunk) private virtual
This reads the RGB value for the object's color.
reads in the RGB color data
Definition at line 516 of file 3ds.cpp.
References tChunk::bytesRead, t3dsMaterialInfo::color, fp, tChunk::length, and readChunk().
Referenced by processNextMaterialChunk().
readObjectMaterial()
void _3ds::readObjectMaterial (t3dsModel * pModel, tObject * pObject, tChunk * pPreviousChunk) private virtual
This reads in the material name assigned to the object and sets the materialID.
reads in the material name assigned to the object and sets the materialID
Definition at line 613 of file 3ds.cpp.
References tObject::bHasTexture, tChunk::bytesRead, fp, getString(), tChunk::length, tObject::materialID, t3dsModel::numOfMaterials, and t3dsModel::pMaterials.
Referenced by processNextObjectChunk().
readUVCoordinates()
void _3ds::readUVCoordinates (tObject * pObject, tChunk * pPreviousChunk) private virtual
This reads the texture coodinates of the object.
reads in the UV coordinates for the object
Definition at line 555 of file 3ds.cpp.
References tChunk::bytesRead, fp, tChunk::length, File::localEndian(), tObject::numTexVertex, tObject::pTexVerts, Vec2::x, and Vec2::y.
Referenced by processNextObjectChunk().
readVertexIndices()
void _3ds::readVertexIndices (tObject * pObject, tChunk * pPreviousChunk) private virtual
This reads the objects face information.
reads in the indices for the vertex array
Definition at line 529 of file 3ds.cpp.
References tChunk::bytesRead, fp, File::localEndian(), tObject::numOfFaces, tObject::pFaces, and t3dsFace::vertIndex.
Referenced by processNextObjectChunk().
readVertices()
void _3ds::readVertices (tObject * pObject, tChunk * pPreviousChunk) private virtual
This reads the objects vertices.
reads in the vertices for the object
Definition at line 573 of file 3ds.cpp.
References tChunk::bytesRead, fp, tChunk::length, File::localEndian(), tObject::numOfVerts, tObject::pVerts, Vec3::x, Vec3::y, and Vec3::z.
Referenced by processNextObjectChunk().
render() [1/2]
void _3ds::render (const Pos & pos, float * color) virtual
Model rendering.
Definition at line 219 of file 3ds.cpp.
References Pos::ax, Pos::az, color, currentScale, dlist, loaded, WObject::pos, RAD2DEG, Pos::x, Pos::y, and Pos::z.
render() [2/2]
void _3ds::render (float * color) virtual
Definition at line 204 of file 3ds.cpp.
References color, currentScale, dlist, and loaded.
Referenced by Model::render().
setScale()
void _3ds::setScale (float scale) virtual
Changes scale.
Definition at line 171 of file 3ds.cpp.
References _3dsModel, currentScale, desiredScale, loaded, t3dsModel::numOfObjects, tObject::numOfVerts, t3dsModel::pObject, tObject::pVerts, Vec3::x, Vec3::y, and Vec3::z.
Referenced by draw(), and Model::scaler().
Member Data Documentation
_3dsModel
t3dsModel _3ds::_3dsModel private
Definition at line 114 of file 3ds.hpp.
Referenced by _3ds(), draw(), getRadius(), importTextures(), loadFromFile(), setScale(), and ~_3ds().
currentScale
float _3ds::currentScale private
Definition at line 117 of file 3ds.hpp.
Referenced by draw(), render(), and setScale().
desiredScale
float _3ds::desiredScale private
Definition at line 118 of file 3ds.hpp.
Referenced by draw(), and setScale().
dlist
GLint _3ds::dlist private
display list
Definition at line 119 of file 3ds.hpp.
Referenced by displaylist(), render(), and ~_3ds().
fp
FILE* _3ds::fp private
The file pointer.
Definition at line 121 of file 3ds.hpp.
Referenced by _3ds(), getString(), importModel(), loadFromFile(), processNextChunk(), processNextMaterialChunk(), processNextObjectChunk(), readChunk(), readColorChunk(), readObjectMaterial(), readUVCoordinates(), readVertexIndices(), and readVertices().
loaded
bool _3ds::loaded private
Definition at line 116 of file 3ds.hpp.
Referenced by draw(), getRadius(), loadFromFile(), render(), and setScale().
url
char* _3ds::url private
3ds url
Definition at line 120 of file 3ds.hpp.
Referenced by _3ds(), getUrl(), loadTexture(), and ~_3ds().
The documentation for this class was generated from the following files:
src/model/3ds.hpp
src/model/3ds.cpp