VREng: Chest Class Reference
Chest Class Reference
Chest class.
#include <body.hpp>
Public Member Functions
Chest ()
constructor
virtual ~Chest ()
destructor
virtual void bend (GLfloat a)
< Init chest
virtual void raise (GLfloat a)
Tilt chest.
virtual void twist (GLfloat a)
Turn chest.
Public Attributes
GLfloat length
chest length
GLfloat abend
chest bend angle
GLfloat araise
chest raise angle
GLfloat atwist
chest twist angle
Static Private Attributes
static const GLfloat CHEST_LEN = 0.30
Detailed Description
Chest class.
Definition at line 364 of file body.hpp.
Constructor & Destructor Documentation
Chest()
Chest::Chest ()
constructor
Chest.
Definition at line 297 of file body.cpp.
~Chest()
virtual Chest::~Chest () inline virtual
destructor
Definition at line 376 of file body.hpp.
Member Function Documentation
bend()
void Chest::bend (GLfloat a) virtual
< Init chest
Roll chest
Definition at line 300 of file body.cpp.
References abend.
Referenced by Body::animate().
raise()
void Chest::raise (GLfloat a) virtual
Tilt chest.
Definition at line 303 of file body.cpp.
References araise.
Referenced by Body::animate().
twist()
void Chest::twist (GLfloat a) virtual
Turn chest.
Definition at line 306 of file body.cpp.
References atwist.
Referenced by Body::animate().
Member Data Documentation
abend
GLfloat Chest::abend
chest bend angle
Definition at line 370 of file body.hpp.
Referenced by bend().
araise
GLfloat Chest::araise
chest raise angle
Definition at line 371 of file body.hpp.
Referenced by raise().
atwist
GLfloat Chest::atwist
chest twist angle
Definition at line 372 of file body.hpp.
Referenced by twist().
CHEST_LEN
const GLfloat Chest::CHEST_LEN = 0.30 static private
Definition at line 366 of file body.hpp.
length
GLfloat Chest::length
chest length
Definition at line 369 of file body.hpp.
The documentation for this class was generated from the following files:
src/model/body.hpp
src/model/body.cpp