VREng: Body Class Reference
Body Class Reference
Body class.
#include <body.hpp>
Public Types
enum {
HEAD, NECK, CHEST, HIPS,
L_ARM, L_FOREARM, L_HAND, R_ARM,
R_FOREARM, R_HAND, L_THIGH, L_SHIN,
L_FOOT, R_THIGH, R_SHIN, R_FOOT,
ABDOMEN, L_COLLAR, R_COLLAR, BELT,
L_THUMB, L_INDEX, L_MIDDLE, L_RING,
L_PINKY, R_THUMB, R_INDEX, R_MIDDLE,
R_RING, R_PINKY, SKIRT, MAX_PARTS
}
Public Member Functions
Body ()
Body.
Body (const char *url)
constructor.
virtual ~Body ()
destructor.
virtual void init ()
Inits body.
virtual void animate ()
Animates body.
virtual void render (Pos &pos)
Renders body and face.
virtual void loadBodyParts (FILE *f)
Loads body's drawable parts.
virtual void setJointPoint (int indice, float *_jp)
Sets one joint point for this indice.
virtual void setColors (float *_skin, float *_cloth)
Sets colors for skin and cloth.
Public Attributes
struct sJP jp
jointpoints.
class Bap * bap
bap ptr.
class Face * face
face ptr.
class WObject * wobject
wobject ptr.
Protected Types
enum {
UPPER_NECK, LOWER_NECK, SPINAL, PELVIC,
L_SHOULDER, L_ELBOW, L_WRIST, R_SHOULDER,
R_ELBOW, R_WRIST, L_HIP, L_KNEE,
L_ANKLE, R_HIP, R_KNEE, R_ANKLE,
MAX_JP
}
Protected Member Functions
virtual void load (const char *url)
Loads body joint points.
virtual void draw ()
Draws body's drawable parts in displaylists.
virtual void display ()
Displays body and face.
virtual void display (int part)
Displays a part of the body.
virtual bool isLoaded (int part)
Returns true if body part exists.
virtual void jpGo (int part)
Translates to the Joint Point.
virtual void jpBack (int part)
Translates reverse from the Joint Point.
virtual char * getTok (char *l, int *tok)
virtual char * skipEqual (char *l)
virtual const char * getUrl () const
Static Protected Member Functions
static void httpReader (void *o, class Http *http)
Reads joint points par Http.
Protected Attributes
uint8_t drawparts
number of drawable parts
uint8_t model_t
model type used (Off, Obj,...)
GLint dlist
body display-list
GLfloat tx
GLfloat ty
GLfloat tz
body translations
GLfloat rx
GLfloat ry
GLfloat rz
body rotations
GLfloat bscale
body scale factor
GLfloat skin [3]
skin color
GLfloat cloth [3]
cloth color
GLfloat color [3]
color
char * url
HeadBody * head
1 head
Neck * neck
1 neck
Chest * chest
1 chest
Thigh * thigh_r
right thigh
Thigh * thigh_l
left thigh
Shin * shin_r
right shin
Shin * shin_l
left shin
Foot * foot_r
right foot
Foot * foot_l
left foot
Shoulder * shoulder_r
right shoulder
Shoulder * shoulder_l
left shoulder
Arm * arm_r
right arm
Arm * arm_l
left arm
Forearm * forearm_r
right forearm
Forearm * forearm_l
left forearm
Hand * hand_r
right hand
Hand * hand_l
left hand
Finger * fingers_r [5]
5 right fingers
Finger * fingers_l [5]
5 left fingers
Phalanx2 * phalanx2 [10]
10 phalanx2
Phalanx * phalanx [10]
10 phalanx
struct sBodyParts * bodyparts
body parts array
Friends
class Bap
class Android
class Man
Detailed Description
Body class.
Definition at line 425 of file body.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
UPPER_NECK
LOWER_NECK
SPINAL
PELVIC
L_SHOULDER
L_ELBOW
L_WRIST
R_SHOULDER
R_ELBOW
R_WRIST
L_HIP
L_KNEE
L_ANKLE
R_HIP
R_KNEE
R_ANKLE
MAX_JP
Definition at line 433 of file body.hpp.
anonymous enum
anonymous enum
Enumerator
HEAD
NECK
CHEST
HIPS
L_ARM
L_FOREARM
L_HAND
R_ARM
R_FOREARM
R_HAND
L_THIGH
L_SHIN
L_FOOT
R_THIGH
R_SHIN
R_FOOT
ABDOMEN
L_COLLAR
R_COLLAR
BELT
L_THUMB
L_INDEX
L_MIDDLE
L_RING
L_PINKY
R_THUMB
R_INDEX
R_MIDDLE
R_RING
R_PINKY
SKIRT
MAX_PARTS
Definition at line 492 of file body.hpp.
Constructor & Destructor Documentation
Body() [1/2]
Body::Body ()
Body.
Definition at line 310 of file body.cpp.
References init().
Body() [2/2]
Body::Body (const char * url)
constructor.
Definition at line 313 of file body.cpp.
References error(), init(), and load().
~Body()
Body::~Body () virtual
destructor.
Definition at line 365 of file body.cpp.
References arm_l, arm_r, bodyparts, chest, dlist, drawparts, face, fingers_l, fingers_r, foot_l, foot_r, forearm_l, forearm_r, hand_l, hand_r, head, jp, neck, phalanx, phalanx2, shin_l, shin_r, shoulder_l, shoulder_r, thigh_l, thigh_r, url, sJP::x, sJP::y, and sJP::z.
Member Function Documentation
animate()
void Body::animate () virtual
Animates body.
Animates all body's articulations.
Definition at line 615 of file body.cpp.
References arm_l, arm_r, bap, Hand::bend(), Forearm::bend(), Arm::bend(), HeadBody::bend(), Neck::bend(), Foot::bend(), Shin::bend(), Thigh::bend(), Chest::bend(), C1_ROLL, C1_TILT, C1_TORSION, C4_ROLL, C4_TILT, C4_TORSION, chest, fingers_l, fingers_r, foot_l, foot_r, forearm_l, forearm_r, Bap::get(), hand_l, hand_r, head, Bap::is(), L_ANKLE_FLEXION, L_ANKLE_TWIST, L_ELBOW_FLEXION, L_HIP_ABDUCT, L_HIP_FLEXION, L_HIP_TWIST, L_INDEX_FLEXION1, L_KNEE_FLEXION, L_KNEE_TWIST, L_MIDDLE_FLEXION1, L_PINKY_FLEXION1, L_RING_FLEXION1, L_SHOULDER_ABDUCT, L_SHOULDER_FLEXION, L_SHOULDER_TWIST, L_THUMB_FLEXION1, L_WRIST_FLEXION, L_WRIST_PIVOT, L_WRIST_TWIST, MODEL_OBJ, MODEL_OFF, model_t, neck, PELVIC_ROLL, PELVIC_TILT, PELVIC_TORSION, R_ANKLE_FLEXION, R_ANKLE_TWIST, R_ELBOW_FLEXION, R_HIP_ABDUCT, R_HIP_FLEXION, R_HIP_TWIST, R_INDEX_FLEXION1, R_KNEE_FLEXION, R_KNEE_TWIST, R_MIDDLE_FLEXION1, R_PINKY_FLEXION1, R_RING_FLEXION1, R_SHOULDER_ABDUCT, R_SHOULDER_FLEXION, R_SHOULDER_TWIST, R_THUMB_FLEXION1, R_WRIST_FLEXION, R_WRIST_PIVOT, R_WRIST_TWIST, Finger::raise(), Hand::raise(), Arm::raise(), HeadBody::raise(), Neck::raise(), Thigh::raise(), Chest::raise(), RT_BODY_ROLL, RT_BODY_TILT, RT_BODY_TURN, rx, ry, rz, shin_l, shin_r, T1_ROLL, T1_TILT, T1_TORSION, thigh_l, thigh_r, TR_DIV, TR_FRONTAL, TR_LATERAL, TR_VERTICAL, Hand::twist(), Arm::twist(), HeadBody::twist(), Neck::twist(), Foot::twist(), Shin::twist(), Thigh::twist(), Chest::twist(), tx, ty, and tz.
Referenced by Android::changePermanent().
display() [1/2]
void Body::display () protected virtual
Displays body and face.
display body and face
Definition at line 810 of file body.cpp.
References ABDOMEN, bap, BELT, C1_ROLL, C1_TILT, C1_TORSION, C4_ROLL, C4_TILT, C4_TORSION, CHEST, face, HEAD, HIPS, isLoaded(), jpBack(), jpGo(), Bap::jpRX(), Bap::jpRY(), Bap::jpRZ(), L_ANKLE, L_ANKLE_FLEXION, L_ANKLE_TWIST, L_ARM, L_COLLAR, L_ELBOW, L_ELBOW_FLEXION, L_ELBOW_TWIST, L_FOOT, L_FOREARM, L_HAND, L_HIP, L_HIP_ABDUCT, L_HIP_FLEXION, L_HIP_TWIST, L_KNEE, L_KNEE_FLEXION, L_KNEE_TWIST, L_SHIN, L_SHOULDER, L_SHOULDER_ABDUCT, L_SHOULDER_FLEXION, L_SHOULDER_TWIST, L_THIGH, L_WRIST, L_WRIST_FLEXION, L_WRIST_PIVOT, L_WRIST_TWIST, LOWER_NECK, MODEL_OFF, model_t, NECK, PELVIC, PELVIC_ROLL, PELVIC_TILT, PELVIC_TORSION, R_ANKLE, R_ANKLE_FLEXION, R_ANKLE_TWIST, R_ARM, R_COLLAR, R_ELBOW, R_ELBOW_FLEXION, R_ELBOW_TWIST, R_FOOT, R_FOREARM, R_HAND, R_HIP, R_HIP_ABDUCT, R_HIP_FLEXION, R_HIP_TWIST, R_INDEX, R_INDEX_FLEXION1, R_KNEE, R_KNEE_FLEXION, R_KNEE_TWIST, R_MIDDLE, R_MIDDLE_FLEXION1, R_PINKY, R_PINKY_FLEXION1, R_RING, R_RING_FLEXION1, R_SHIN, R_SHOULDER, R_SHOULDER_ABDUCT, R_SHOULDER_FLEXION, R_SHOULDER_TWIST, R_THIGH, R_THUMB, R_THUMB_FLEXION1, R_WRIST, R_WRIST_FLEXION, R_WRIST_PIVOT, R_WRIST_TWIST, Face::render(), Face::SCALE, SKIRT, SPINAL, T5_ROLL, T5_TILT, T5_TORSION, and UPPER_NECK.
Referenced by render().
display() [2/2]
void Body::display (int part) protected virtual
Displays a part of the body.
Definition at line 787 of file body.cpp.
References bodyparts, color, dlist, and MAX_PARTS.
draw()
void Body::draw () protected virtual
Draws body's drawable parts in displaylists.
Definition at line 588 of file body.cpp.
References bodyparts, dlist, Obj::draw(), Off::draw(), drawparts, sBodyParts::loaded, MODEL_OBJ, MODEL_OFF, model_t, sBodyParts::obj, and sBodyParts::off.
Referenced by Android::inits().
getTok()
char * Body::getTok (char * l, int * tok) protected virtual
Definition at line 408 of file body.cpp.
References btokens, error(), sBodyToken::name, sBodyToken::num, and skipEqual().
Referenced by loadBodyParts().
getUrl()
const char * Body::getUrl () const protected virtual
Definition at line 433 of file body.cpp.
References url.
Referenced by httpReader().
httpReader()
void Body::httpReader (void * o, class Http * http) static protected
Reads joint points par Http.
load joint points (static)
Definition at line 439 of file body.cpp.
References error(), getUrl(), loadBodyParts(), and Cache::openCache().
Referenced by load().
init()
void Body::init () virtual
Inits body.
Definition at line 320 of file body.cpp.
References arm_l, arm_r, B_SCALE, bodyparts, bscale, chest, cloth, drawparts, face, fingers_l, fingers_r, foot_l, foot_r, forearm_l, forearm_r, hand_l, hand_r, head, jp, model_t, neck, phalanx, phalanx2, rx, ry, rz, shin_l, shin_r, shoulder_l, shoulder_r, skin, thigh_l, thigh_r, tx, ty, tz, sJP::x, sJP::y, and sJP::z.
Referenced by Body().
isLoaded()
bool Body::isLoaded (int part) protected virtual
Returns true if body part exists.
Definition at line 765 of file body.cpp.
References bodyparts, sBodyParts::loaded, and MAX_PARTS.
Referenced by display().
jpBack()
void Body::jpBack (int part) protected virtual
Translates reverse from the Joint Point.
Definition at line 779 of file body.cpp.
References jp, MAX_PARTS, MODEL_OBJ, model_t, sJP::x, sJP::y, and sJP::z.
Referenced by display().
jpGo()
void Body::jpGo (int part) protected virtual
Translates to the Joint Point.
Definition at line 771 of file body.cpp.
References jp, MAX_PARTS, MODEL_OBJ, model_t, sJP::x, sJP::y, and sJP::z.
Referenced by display().
load()
void Body::load (const char * url) protected virtual
Loads body joint points.
Definition at line 426 of file body.cpp.
References Http::httpOpen(), httpReader(), and url.
Referenced by Body(), and Android::inits().
loadBodyParts()
void Body::loadBodyParts (FILE * f) virtual
Loads body's drawable parts.
load body's parts
Definition at line 450 of file body.cpp.
References begin_while_parse, bodyparts, bscale, File::closeFile(), cloth, sBodyParts::color, color, DBG_MAN, drawparts, end_while_parse, Texture::getFromCache(), Format::getModelByUrl(), getTok(), HEAD, Http::httpOpen(), Obj::httpReader(), Off::httpReader(), jp, L_FOREARM, L_HAND, sBodyParts::loaded, MAX_PARTS, MODEL_OBJ, MODEL_OFF, sBodyParts::model_t, model_t, NECK, obj, sBodyParts::obj, sBodyParts::off, WObject::parse(), Parse::parseFloat(), Parse::parseString(), Parse::parseVector3f(), R_FOREARM, R_HAND, sBodyParts::scale, sBodyParts::scales, SEP, Obj::setScale(), skin, skipEqual(), stringcmp(), sBodyParts::texid, sBodyParts::texurl, trace(), sBodyParts::url, url, wobject, sJP::x, sJP::y, and sJP::z.
Referenced by httpReader().
render()
void Body::render (Pos & pos) virtual
Renders body and face.
Definition at line 1037 of file body.cpp.
References Pos::az, B_HEIGHT, bap, bscale, display(), MODEL_OBJ, MODEL_OFF, model_t, RAD2DEG, rx, ry, rz, tx, ty, tz, Pos::x, Pos::y, and Pos::z.
Referenced by Solid::displayMirroredScene(), and Android::render().
setColors()
void Body::setColors (float * _skin, float * _cloth) virtual
Sets colors for skin and cloth.
Definition at line 605 of file body.cpp.
References cloth, color, and skin.
Referenced by Android::inits().
setJointPoint()
void Body::setJointPoint (int indice, float * _jp) virtual
Sets one joint point for this indice.
Definition at line 578 of file body.cpp.
References jp, MAX_PARTS, warning(), sJP::x, sJP::y, and sJP::z.
skipEqual()
char * Body::skipEqual (char * l) protected virtual
Definition at line 402 of file body.cpp.
Referenced by getTok(), and loadBodyParts().
Friends And Related Function Documentation
Android
friend class Android friend
Definition at line 427 of file body.hpp.
Bap
friend class Bap friend
Definition at line 426 of file body.hpp.
Man
friend class Man friend
Definition at line 428 of file body.hpp.
Member Data Documentation
arm_l
Arm* Body::arm_l protected
left arm
Definition at line 477 of file body.hpp.
Referenced by animate(), init(), and ~Body().
arm_r
Arm* Body::arm_r protected
right arm
Definition at line 476 of file body.hpp.
Referenced by animate(), init(), and ~Body().
bap
class Bap* Body::bap
bap ptr.
Definition at line 528 of file body.hpp.
Referenced by animate(), display(), Android::inits(), and render().
bodyparts
struct sBodyParts* Body::bodyparts protected
body parts array
Definition at line 487 of file body.hpp.
Referenced by display(), draw(), init(), isLoaded(), loadBodyParts(), and ~Body().
bscale
GLfloat Body::bscale protected
body scale factor
Definition at line 458 of file body.hpp.
Referenced by init(), loadBodyParts(), and render().
chest
Chest* Body::chest protected
1 chest
Definition at line 467 of file body.hpp.
Referenced by animate(), init(), and ~Body().
cloth
GLfloat Body::cloth[3] protected
cloth color
Definition at line 460 of file body.hpp.
Referenced by init(), loadBodyParts(), and setColors().
color
GLfloat Body::color[3] protected
color
Definition at line 461 of file body.hpp.
Referenced by display(), loadBodyParts(), and setColors().
dlist
GLint Body::dlist protected
body display-list
Definition at line 455 of file body.hpp.
Referenced by display(), draw(), and ~Body().
drawparts
uint8_t Body::drawparts protected
number of drawable parts
Definition at line 453 of file body.hpp.
Referenced by draw(), init(), loadBodyParts(), and ~Body().
face
class Face* Body::face
face ptr.
Definition at line 529 of file body.hpp.
Referenced by Face::changeFace(), Face::changeMoveEyeL(), Face::changeMoveEyeR(), Face::changeMoveMouth(), Face::changeMoveNo(), Face::changeMoveNose(), Face::changeMoveSmile(), Face::changeMoveSulk(), Face::changeMoveYes(), Android::changePermanent(), display(), init(), Android::inits(), and ~Body().
fingers_l
Finger* Body::fingers_l[5] protected
5 left fingers
Definition at line 483 of file body.hpp.
Referenced by animate(), init(), and ~Body().
fingers_r
Finger* Body::fingers_r[5] protected
5 right fingers
Definition at line 482 of file body.hpp.
Referenced by animate(), init(), and ~Body().
foot_l
Foot* Body::foot_l protected
left foot
Definition at line 473 of file body.hpp.
Referenced by animate(), init(), and ~Body().
foot_r
Foot* Body::foot_r protected
right foot
Definition at line 472 of file body.hpp.
Referenced by animate(), init(), and ~Body().
forearm_l
Forearm* Body::forearm_l protected
left forearm
Definition at line 479 of file body.hpp.
Referenced by animate(), init(), and ~Body().
forearm_r
Forearm* Body::forearm_r protected
right forearm
Definition at line 478 of file body.hpp.
Referenced by animate(), init(), and ~Body().
hand_l
Hand* Body::hand_l protected
left hand
Definition at line 481 of file body.hpp.
Referenced by animate(), init(), and ~Body().
hand_r
Hand* Body::hand_r protected
right hand
Definition at line 480 of file body.hpp.
Referenced by animate(), init(), and ~Body().
head
HeadBody* Body::head protected
1 head
Definition at line 465 of file body.hpp.
Referenced by animate(), init(), and ~Body().
jp
struct sJP Body::jp
jointpoints.
Definition at line 487 of file body.hpp.
Referenced by init(), jpBack(), jpGo(), loadBodyParts(), setJointPoint(), and ~Body().
model_t
uint8_t Body::model_t protected
model type used (Off, Obj,...)
Definition at line 454 of file body.hpp.
Referenced by animate(), display(), draw(), init(), jpBack(), jpGo(), loadBodyParts(), and render().
neck
Neck* Body::neck protected
1 neck
Definition at line 466 of file body.hpp.
Referenced by animate(), init(), and ~Body().
phalanx
Phalanx* Body::phalanx[10] protected
10 phalanx
Definition at line 485 of file body.hpp.
Referenced by init(), and ~Body().
phalanx2
Phalanx2* Body::phalanx2[10] protected
10 phalanx2
Definition at line 484 of file body.hpp.
Referenced by init(), and ~Body().
rx
GLfloat Body::rx protected
Definition at line 457 of file body.hpp.
Referenced by animate(), init(), and render().
ry
GLfloat Body::ry protected
Definition at line 457 of file body.hpp.
Referenced by animate(), init(), and render().
rz
GLfloat Body::rz protected
body rotations
Definition at line 457 of file body.hpp.
Referenced by animate(), init(), and render().
shin_l
Shin* Body::shin_l protected
left shin
Definition at line 471 of file body.hpp.
Referenced by animate(), init(), and ~Body().
shin_r
Shin* Body::shin_r protected
right shin
Definition at line 470 of file body.hpp.
Referenced by animate(), init(), and ~Body().
shoulder_l
Shoulder* Body::shoulder_l protected
left shoulder
Definition at line 475 of file body.hpp.
Referenced by init(), and ~Body().
shoulder_r
Shoulder* Body::shoulder_r protected
right shoulder
Definition at line 474 of file body.hpp.
Referenced by init(), and ~Body().
skin
GLfloat Body::skin[3] protected
skin color
Definition at line 459 of file body.hpp.
Referenced by init(), loadBodyParts(), and setColors().
thigh_l
Thigh* Body::thigh_l protected
left thigh
Definition at line 469 of file body.hpp.
Referenced by animate(), init(), and ~Body().
thigh_r
Thigh* Body::thigh_r protected
right thigh
Definition at line 468 of file body.hpp.
Referenced by animate(), init(), and ~Body().
tx
GLfloat Body::tx protected
Definition at line 456 of file body.hpp.
Referenced by animate(), init(), and render().
ty
GLfloat Body::ty protected
Definition at line 456 of file body.hpp.
Referenced by animate(), init(), and render().
tz
GLfloat Body::tz protected
body translations
Definition at line 456 of file body.hpp.
Referenced by animate(), init(), and render().
url
char* Body::url protected
Definition at line 462 of file body.hpp.
Referenced by getUrl(), load(), loadBodyParts(), and ~Body().
wobject
class WObject* Body::wobject
wobject ptr.
Definition at line 530 of file body.hpp.
Referenced by Android::inits(), and loadBodyParts().
The documentation for this class was generated from the following files:
src/model/body.hpp
src/model/body.cpp