VREng: Hand Class Reference
Hand Class Reference
Hand class // Wrist.
#include <body.hpp>
Public Member Functions
Hand (Finger **finger)
constructor
virtual ~Hand ()
destructor
virtual int init ()
Init hand.
virtual void bend (GLfloat a)
Bend hand.
virtual void raise (GLfloat a)
Tilt hand.
virtual void twist (GLfloat a)
Turn hand.
Public Attributes
GLfloat length
hand length
GLfloat abend
hand bend angle
GLfloat araise
hand raise angle
GLfloat atwist
hand twist angle
class Finger * fingers [5]
five fingers
Static Private Attributes
static const GLfloat HAND_LEN = 0.10
Detailed Description
Hand class // Wrist.
Definition at line 107 of file body.hpp.
Constructor & Destructor Documentation
Hand()
Hand::Hand (Finger ** finger)
constructor
Hand.
Definition at line 123 of file body.cpp.
References abend, araise, atwist, fingers, HAND_LEN, and length.
~Hand()
virtual Hand::~Hand () inline virtual
destructor
Definition at line 119 of file body.hpp.
Member Function Documentation
bend()
void Hand::bend (GLfloat a) virtual
Bend hand.
Definition at line 137 of file body.cpp.
References abend.
Referenced by Body::animate().
init()
int Hand::init () virtual
Init hand.
Definition at line 134 of file body.cpp.
References fingers, and Finger::init().
Referenced by Forearm::init().
raise()
void Hand::raise (GLfloat a) virtual
Tilt hand.
Definition at line 140 of file body.cpp.
References araise.
Referenced by Body::animate().
twist()
void Hand::twist (GLfloat a) virtual
Turn hand.
Definition at line 143 of file body.cpp.
References atwist.
Referenced by Body::animate().
Member Data Documentation
abend
GLfloat Hand::abend
hand bend angle
Definition at line 113 of file body.hpp.
Referenced by bend(), and Hand().
araise
GLfloat Hand::araise
hand raise angle
Definition at line 114 of file body.hpp.
Referenced by Hand(), and raise().
atwist
GLfloat Hand::atwist
hand twist angle
Definition at line 115 of file body.hpp.
Referenced by Hand(), and twist().
fingers
class Finger* Hand::fingers[5]
five fingers
Definition at line 116 of file body.hpp.
Referenced by Hand(), and init().
HAND_LEN
const GLfloat Hand::HAND_LEN = 0.10 static private
Definition at line 109 of file body.hpp.
Referenced by Hand().
length
GLfloat Hand::length
hand length
Definition at line 112 of file body.hpp.
Referenced by Hand().
The documentation for this class was generated from the following files:
src/model/body.hpp
src/model/body.cpp