VREng: BoneList< BoneElem > Class Template Reference
BoneList< BoneElem > Class Template Reference
Class BoneList: la classe liste est la classe principale de gestion de la liste chainee.
#include <bonelist.hpp>
Public Member Functions
BoneList ()
Constructeur par defaut. Il initialise la liste comme une liste vide.
virtual ~BoneList ()
Le destructeur vide la liste de son contenu.
void empty ()
int count ()
BoneElem * getElemAt (int index)
void addElement (BoneElem *zeElement)
void addList (BoneList *zeList)
void removeElement (int index)
void removeElement (BoneElem *ptr)
BoneElem ** getNiceTable (int *count)
Private Member Functions
BoneNode< BoneElem > * getFirstNode ()
Recherche du premier noeud de la liste.
BoneNode< BoneElem > * getLastNode ()
Recherche du dernier noeud de la liste.
void rebuild ()
Compilation de la liste chainee en tableau Cette methode ne s'execute que si la liste a ete modifiee dans la passe (addElement ou removeElement).
void recursiveEmpty (BoneNode< BoneElem > *currentNode)
Fonction recursive de vidage de la liste, il s'agit de d'appeler le vidage du fils puis de liberer le fils.
Private Attributes
BoneNode< BoneElem > * listHead
Tete de la liste chainee.
BoneNode< BoneElem > * listEnd
Queue de la liste chainee.
BoneElem ** element
Table contenant les pointeur sur element lors de la compilation de la liste en tableau.
int elements
Nombre d'elements dans la table lors de la compilation de la liste en tableau.
int built
Masque disant si la liste est compilee ou non.
Detailed Description
template<class BoneElem>
class BoneList< BoneElem >
Class BoneList: la classe liste est la classe principale de gestion de la liste chainee.
Il stocke les noeuds contenant les pointeurs sur elements a la queu leu leu en commencant par 'listHead' Methodes : void empty (void) int count (void) void addElement (BoneElem * zeElement) void addList (BoneList * zeList) void removeElement (int index) void removeElement (BoneElem * ptr) BoneElem * getElemAt (int index) BoneElem ** getNiceTable (int * count)
Definition at line 101 of file bonelist.hpp.
Constructor & Destructor Documentation
BoneList()
template<class BoneElem > BoneList< BoneElem >::BoneList () inline
Constructeur par defaut. Il initialise la liste comme une liste vide.
Definition at line 145 of file bonelist.hpp.
~BoneList()
template<class BoneElem > virtual BoneList< BoneElem >::~BoneList () inline virtual
Le destructeur vide la liste de son contenu.
Definition at line 154 of file bonelist.hpp.
Member Function Documentation
addElement()
template<class BoneElem > void BoneList< BoneElem >::addElement (BoneElem * zeElement) inline
Definition at line 194 of file bonelist.hpp.
Referenced by BoneVertex::addChild(), BoneVertex::addLink(), Vertex::addLink(), BoneAnimator::addNodeAndChildren(), BoneMesh::addTriangle(), BoneMesh::addVertex(), Face::facesHttpReader(), and BoneAnimator::generateLinkList().
addList()
template<class BoneElem > void BoneList< BoneElem >::addList (BoneList< BoneElem > * zeList) inline
Definition at line 211 of file bonelist.hpp.
count()
template<class BoneElem > int BoneList< BoneElem >::count () inline
Definition at line 169 of file bonelist.hpp.
Referenced by Face::change(), Face::Face(), BoneList< BoneLink >::getNiceTable(), and BoneList< BoneLink >::rebuild().
empty()
template<class BoneElem > void BoneList< BoneElem >::empty () inline
Definition at line 158 of file bonelist.hpp.
Referenced by BoneAnimator::emptyLinkList(), Face::Face(), BoneAnimator::generateLinkList(), BoneList< BoneLink >::~BoneList(), and BoneVertex::~BoneVertex().
getElemAt()
template<class BoneElem > BoneElem* BoneList< BoneElem >::getElemAt (int index) inline
Definition at line 181 of file bonelist.hpp.
Referenced by Face::change(), and V3d::readV3Dfile().
getFirstNode()
template<class BoneElem > BoneNode<BoneElem>* BoneList< BoneElem >::getFirstNode () inline private
Recherche du premier noeud de la liste.
Definition at line 110 of file bonelist.hpp.
Referenced by BoneList< BoneLink >::addList().
getLastNode()
template<class BoneElem > BoneNode<BoneElem>* BoneList< BoneElem >::getLastNode () inline private
Recherche du dernier noeud de la liste.
Definition at line 113 of file bonelist.hpp.
getNiceTable()
template<class BoneElem > BoneElem** BoneList< BoneElem >::getNiceTable (int * count) inline
Definition at line 290 of file bonelist.hpp.
Referenced by BoneVertex::compileChildList(), BoneAnimator::compileLinkList(), BoneVertex::compileLinkList(), Vertex::compileLinkList(), BoneMesh::compileTriangleList(), BoneMesh::compileVertexList(), and BoneAnimator::generateLinkList().
rebuild()
template<class BoneElem > void BoneList< BoneElem >::rebuild () inline private
Compilation de la liste chainee en tableau Cette methode ne s'execute que si la liste a ete modifiee dans la passe (addElement ou removeElement).
Definition at line 120 of file bonelist.hpp.
Referenced by BoneList< BoneLink >::getNiceTable().
recursiveEmpty()
template<class BoneElem > void BoneList< BoneElem >::recursiveEmpty (BoneNode< BoneElem > * currentNode) inline private
Fonction recursive de vidage de la liste, il s'agit de d'appeler le vidage du fils puis de liberer le fils.
Definition at line 136 of file bonelist.hpp.
Referenced by BoneList< BoneLink >::empty(), and BoneList< BoneLink >::recursiveEmpty().
removeElement() [1/2]
template<class BoneElem > void BoneList< BoneElem >::removeElement (BoneElem * ptr) inline
Definition at line 260 of file bonelist.hpp.
removeElement() [2/2]
template<class BoneElem > void BoneList< BoneElem >::removeElement (int index) inline
Definition at line 228 of file bonelist.hpp.
Referenced by BoneVertex::removeChild(), BoneVertex::removeLink(), and Vertex::removeLink().
Member Data Documentation
built
template<class BoneElem > int BoneList< BoneElem >::built private
Masque disant si la liste est compilee ou non.
Definition at line 108 of file bonelist.hpp.
Referenced by BoneList< BoneLink >::addElement(), BoneList< BoneLink >::addList(), BoneList< BoneLink >::BoneList(), BoneList< BoneLink >::empty(), BoneList< BoneLink >::getNiceTable(), BoneList< BoneLink >::rebuild(), and BoneList< BoneLink >::removeElement().
element
template<class BoneElem > BoneElem** BoneList< BoneElem >::element private
Table contenant les pointeur sur element lors de la compilation de la liste en tableau.
Definition at line 106 of file bonelist.hpp.
Referenced by BoneList< BoneLink >::BoneList(), BoneList< BoneLink >::empty(), BoneList< BoneLink >::getNiceTable(), and BoneList< BoneLink >::rebuild().
elements
template<class BoneElem > int BoneList< BoneElem >::elements private
Nombre d'elements dans la table lors de la compilation de la liste en tableau.
Definition at line 107 of file bonelist.hpp.
Referenced by BoneList< BoneLink >::BoneList(), BoneList< BoneLink >::getNiceTable(), and BoneList< BoneLink >::rebuild().
listEnd
template<class BoneElem > BoneNode<BoneElem>* BoneList< BoneElem >::listEnd private
Queue de la liste chainee.
Definition at line 105 of file bonelist.hpp.
Referenced by BoneList< BoneLink >::addElement(), BoneList< BoneLink >::addList(), BoneList< BoneLink >::BoneList(), BoneList< BoneLink >::empty(), and BoneList< BoneLink >::getLastNode().
listHead
template<class BoneElem > BoneNode<BoneElem>* BoneList< BoneElem >::listHead private
Tete de la liste chainee.
Definition at line 104 of file bonelist.hpp.
Referenced by BoneList< BoneLink >::addElement(), BoneList< BoneLink >::addList(), BoneList< BoneLink >::BoneList(), BoneList< BoneLink >::count(), BoneList< BoneLink >::empty(), BoneList< BoneLink >::getElemAt(), BoneList< BoneLink >::getFirstNode(), BoneList< BoneLink >::rebuild(), and BoneList< BoneLink >::removeElement().
The documentation for this class was generated from the following file:
src/model/bonelist.hpp