VREng: BoneMesh Class Reference
BoneMesh Class Reference
BoneMesh class.
#include <bonemesh.hpp>
Public Member Functions
BoneMesh ()
virtual ~BoneMesh ()
virtual void addVertex (Vect3D &zePosition)
virtual void addVertex (Vect3D *zePosition)
virtual void addVertex (float ox, float oy, float oz)
virtual void addTriangle (int index1, int index2, int index3)
void compileVertexList ()
void compileTriangleList ()
virtual void rebuildNormals ()
virtual void scale (float sx, float sy, float sz)
virtual void projectLight ()
Public Member Functions inherited from Bonename
Bonename ()
Bonename (char *op)
Bonename (Bonename *op)
Bonename (Bonename &op)
virtual ~Bonename ()
virtual void setName (char *zeName)
virtual char * getName ()
Public Attributes
BoneList< Vertex > vertexList
Vertex ** vertex
int vertices
int vertexListCompiled
BoneList< Triangle > triangleList
Triangle ** triangle
int triangles
int triangleListCompiled
float minx
float miny
float minz
float maxx
float maxy
float maxz
Public Attributes inherited from Bonename
char * name
name
Detailed Description
BoneMesh class.
Definition at line 43 of file bonemesh.hpp.
Constructor & Destructor Documentation
BoneMesh()
BoneMesh::BoneMesh ()
Definition at line 34 of file bonemesh.cpp.
References Bonename::setName(), triangle, triangleListCompiled, triangles, vertex, vertexListCompiled, and vertices.
~BoneMesh()
BoneMesh::~BoneMesh () virtual
Definition at line 46 of file bonemesh.cpp.
References compileTriangleList(), compileVertexList(), triangle, triangleListCompiled, triangles, vertex, vertexListCompiled, and vertices.
Member Function Documentation
addTriangle()
void BoneMesh::addTriangle (int index1, int index2, int index3) virtual
Definition at line 73 of file bonemesh.cpp.
References BoneList< BoneElem >::addElement(), Triangle::addVertex(), compileVertexList(), triangleList, triangleListCompiled, vertex, and vertexListCompiled.
Referenced by V3d::readV3Dfile().
addVertex() [1/3]
void BoneMesh::addVertex (float ox, float oy, float oz) virtual
Definition at line 67 of file bonemesh.cpp.
References BoneList< BoneElem >::addElement(), vertexList, and vertexListCompiled.
addVertex() [2/3]
void BoneMesh::addVertex (Vect3D & zePosition) virtual
Definition at line 55 of file bonemesh.cpp.
References BoneList< BoneElem >::addElement(), vertexList, and vertexListCompiled.
Referenced by V3d::readV3Dfile().
addVertex() [3/3]
void BoneMesh::addVertex (Vect3D * zePosition) virtual
Definition at line 61 of file bonemesh.cpp.
References BoneList< BoneElem >::addElement(), vertexList, and vertexListCompiled.
compileTriangleList()
void BoneMesh::compileTriangleList ()
Definition at line 155 of file bonemesh.cpp.
References BoneList< BoneElem >::getNiceTable(), triangle, triangleList, triangleListCompiled, triangles, Vertex::u, Triangle::u1, Triangle::u2, Triangle::u3, Vertex::v, Triangle::v1, Triangle::v2, Triangle::v3, Triangle::vertex1, Triangle::vertex2, and Triangle::vertex3.
Referenced by projectLight(), rebuildNormals(), BoneAnimator::render(), and ~BoneMesh().
compileVertexList()
void BoneMesh::compileVertexList ()
Definition at line 149 of file bonemesh.cpp.
References BoneList< BoneElem >::getNiceTable(), vertex, vertexList, vertexListCompiled, and vertices.
Referenced by addTriangle(), BoneAnimator::generateLinkList(), rebuildNormals(), scale(), and ~BoneMesh().
projectLight()
void BoneMesh::projectLight () virtual
Definition at line 119 of file bonemesh.cpp.
References compileTriangleList(), CROP, Vect3D::dotProduct(), Triangle::finalBlue, Triangle::finalGreen, Triangle::finalRed, Vect3D::reset(), triangle, triangleListCompiled, triangles, Vect3D::x, Vect3D::y, and Vect3D::z.
Referenced by rebuildNormals().
rebuildNormals()
void BoneMesh::rebuildNormals () virtual
Definition at line 100 of file bonemesh.cpp.
References compileTriangleList(), compileVertexList(), Triangle::initialNormal, Vertex::initialNormal, projectLight(), Triangle::rebuildNormal(), triangle, triangleListCompiled, triangles, vertex, Triangle::vertex1, Triangle::vertex2, Triangle::vertex3, vertexListCompiled, and vertices.
Referenced by V3d::readV3Dfile().
scale()
void BoneMesh::scale (float sx, float sy, float sz) virtual
Definition at line 86 of file bonemesh.cpp.
References compileVertexList(), Vertex::currentPosition, Vertex::initialPosition, vertex, vertexListCompiled, vertices, Vect3D::x, Vect3D::y, and Vect3D::z.
Referenced by BoneAnimator::scale().
Member Data Documentation
maxx
float BoneMesh::maxx
Definition at line 60 of file bonemesh.hpp.
maxy
float BoneMesh::maxy
Definition at line 60 of file bonemesh.hpp.
maxz
float BoneMesh::maxz
Definition at line 60 of file bonemesh.hpp.
minx
float BoneMesh::minx
Definition at line 59 of file bonemesh.hpp.
miny
float BoneMesh::miny
Definition at line 59 of file bonemesh.hpp.
minz
float BoneMesh::minz
Definition at line 59 of file bonemesh.hpp.
triangle
Triangle** BoneMesh::triangle
Definition at line 54 of file bonemesh.hpp.
Referenced by BoneMesh(), compileTriangleList(), projectLight(), rebuildNormals(), BoneAnimator::render(), and ~BoneMesh().
triangleList
BoneList<Triangle> BoneMesh::triangleList
Definition at line 53 of file bonemesh.hpp.
Referenced by addTriangle(), compileTriangleList(), and V3d::readV3Dfile().
triangleListCompiled
int BoneMesh::triangleListCompiled
Definition at line 56 of file bonemesh.hpp.
Referenced by addTriangle(), BoneMesh(), compileTriangleList(), projectLight(), rebuildNormals(), BoneAnimator::render(), and ~BoneMesh().
triangles
int BoneMesh::triangles
Definition at line 55 of file bonemesh.hpp.
Referenced by BoneMesh(), compileTriangleList(), projectLight(), rebuildNormals(), BoneAnimator::render(), and ~BoneMesh().
vertex
Vertex** BoneMesh::vertex
Definition at line 48 of file bonemesh.hpp.
Referenced by addTriangle(), BoneAnimator::animate(), BoneMesh(), compileVertexList(), BoneAnimator::generateLinkList(), rebuildNormals(), scale(), and ~BoneMesh().
vertexList
BoneList< Vertex > BoneMesh::vertexList
Definition at line 47 of file bonemesh.hpp.
Referenced by addVertex(), and compileVertexList().
vertexListCompiled
int BoneMesh::vertexListCompiled
Definition at line 50 of file bonemesh.hpp.
Referenced by addTriangle(), addVertex(), BoneMesh(), compileVertexList(), BoneAnimator::generateLinkList(), rebuildNormals(), scale(), and ~BoneMesh().
vertices
int BoneMesh::vertices
Definition at line 49 of file bonemesh.hpp.
Referenced by BoneAnimator::animate(), BoneMesh(), compileVertexList(), BoneAnimator::generateLinkList(), rebuildNormals(), scale(), and ~BoneMesh().
The documentation for this class was generated from the following files:
src/model/bonemesh.hpp
src/model/bonemesh.cpp