VREng: BoneNode< BoneElem > Class Template Reference
BoneNode< BoneElem > Class Template Reference
La classe BoneNode represente un noeud de la liste chainee.
#include <bonelist.hpp>
Public Member Functions
BoneNode ()
Constructeur de noeud, initialise tous les pointeurs a NULL.
BoneNode (BoneNode &node)
Constructeur de noeud par recopie, recopie tous les champs du noeud passe en parametre.
virtual ~BoneNode ()
destructor
void setPrev (BoneNode *zePrev)
void setNext (BoneNode *zeNext)
void setElement (BoneElem *zeElement)
void setValue (BoneNode *zePrev, BoneNode *zeNext, BoneElem *zeElement)
BoneNode * getNext (void)
BoneNode * getPrev (void)
BoneElem * getElem (void)
Private Attributes
BoneNode * nextNode
Noeud precedent this dans la liste.
BoneNode * prevNode
Noeud suivant this dans la liste.
BoneElem * element
Element de la liste contenu dans this.
Detailed Description
template<class BoneElem>
class BoneNode< BoneElem >
La classe BoneNode represente un noeud de la liste chainee.
Elle contient:
un pointeur sur l'element stocke dans ce noeud
un pointeur sur le noeud suivant
un pointeur sur le noeud precedent Cette classe ne fait que gerer ces champs (lecture/ecriture).
Definition at line 42 of file bonelist.hpp.
Constructor & Destructor Documentation
BoneNode() [1/2]
template<class BoneElem > BoneNode< BoneElem >::BoneNode () inline
Constructeur de noeud, initialise tous les pointeurs a NULL.
Definition at line 50 of file bonelist.hpp.
BoneNode() [2/2]
template<class BoneElem > BoneNode< BoneElem >::BoneNode (BoneNode< BoneElem > & node) inline
Constructeur de noeud par recopie, recopie tous les champs du noeud passe en parametre.
Definition at line 57 of file bonelist.hpp.
~BoneNode()
template<class BoneElem > virtual BoneNode< BoneElem >::~BoneNode () inline virtual
destructor
Definition at line 67 of file bonelist.hpp.
Member Function Documentation
getElem()
template<class BoneElem > BoneElem* BoneNode< BoneElem >::getElem (void) inline
Definition at line 83 of file bonelist.hpp.
Referenced by BoneList< BoneLink >::getElemAt(), and BoneList< BoneLink >::removeElement().
getNext()
template<class BoneElem > BoneNode* BoneNode< BoneElem >::getNext (void) inline
Definition at line 81 of file bonelist.hpp.
Referenced by BoneList< BoneLink >::count(), BoneList< BoneLink >::getElemAt(), BoneList< BoneLink >::rebuild(), BoneList< BoneLink >::recursiveEmpty(), and BoneList< BoneLink >::removeElement().
getPrev()
template<class BoneElem > BoneNode* BoneNode< BoneElem >::getPrev (void) inline
Definition at line 82 of file bonelist.hpp.
Referenced by BoneList< BoneLink >::removeElement().
setElement()
template<class BoneElem > void BoneNode< BoneElem >::setElement (BoneElem * zeElement) inline
Definition at line 73 of file bonelist.hpp.
Referenced by BoneList< BoneLink >::addElement(), and BoneNode< BoneLink >::setValue().
setNext()
template<class BoneElem > void BoneNode< BoneElem >::setNext (BoneNode< BoneElem > * zeNext) inline
Definition at line 72 of file bonelist.hpp.
Referenced by BoneList< BoneLink >::removeElement(), and BoneNode< BoneLink >::setValue().
setPrev()
template<class BoneElem > void BoneNode< BoneElem >::setPrev (BoneNode< BoneElem > * zePrev) inline
Definition at line 71 of file bonelist.hpp.
Referenced by BoneList< BoneLink >::addElement(), BoneList< BoneLink >::addList(), BoneList< BoneLink >::removeElement(), and BoneNode< BoneLink >::setValue().
setValue()
template<class BoneElem > void BoneNode< BoneElem >::setValue (BoneNode< BoneElem > * zePrev, BoneNode< BoneElem > * zeNext, BoneElem * zeElement) inline
Definition at line 74 of file bonelist.hpp.
Member Data Documentation
element
template<class BoneElem > BoneElem* BoneNode< BoneElem >::element private
Element de la liste contenu dans this.
Definition at line 47 of file bonelist.hpp.
Referenced by BoneNode< BoneLink >::BoneNode(), BoneNode< BoneLink >::getElem(), and BoneNode< BoneLink >::setElement().
nextNode
template<class BoneElem > BoneNode* BoneNode< BoneElem >::nextNode private
Noeud precedent this dans la liste.
Definition at line 45 of file bonelist.hpp.
Referenced by BoneNode< BoneLink >::BoneNode(), BoneNode< BoneLink >::getNext(), and BoneNode< BoneLink >::setNext().
prevNode
template<class BoneElem > BoneNode* BoneNode< BoneElem >::prevNode private
Noeud suivant this dans la liste.
Definition at line 46 of file bonelist.hpp.
Referenced by BoneNode< BoneLink >::BoneNode(), BoneNode< BoneLink >::getPrev(), and BoneNode< BoneLink >::setPrev().
The documentation for this class was generated from the following file:
src/model/bonelist.hpp