VREng: HeadBody Class Reference
HeadBody Class Reference
HeadBody class.
#include <body.hpp>
Public Member Functions
HeadBody ()
constructor
virtual ~HeadBody ()
destructor
virtual int init ()
Init head.
virtual void bend (GLfloat a)
Bend head.
virtual void raise (GLfloat a)
Tilt head.
virtual void twist (GLfloat a)
Turn head.
Public Attributes
GLfloat radius
head radius
GLfloat abend
head bend angle
GLfloat araise
head raise angle
GLfloat atwist
head twist angle
Static Private Attributes
static const GLfloat HEAD_RAD = 0.075
Detailed Description
HeadBody class.
Definition at line 220 of file body.hpp.
Constructor & Destructor Documentation
HeadBody()
HeadBody::HeadBody ()
constructor
HeadBody.
Definition at line 202 of file body.cpp.
References abend, araise, atwist, HEAD_RAD, and radius.
~HeadBody()
virtual HeadBody::~HeadBody () inline virtual
destructor
Definition at line 231 of file body.hpp.
Member Function Documentation
bend()
void HeadBody::bend (GLfloat a) virtual
Bend head.
Definition at line 211 of file body.cpp.
References abend.
Referenced by Body::animate().
init()
int HeadBody::init () virtual
Init head.
Definition at line 208 of file body.cpp.
Referenced by Neck::init().
raise()
void HeadBody::raise (GLfloat a) virtual
Tilt head.
Definition at line 214 of file body.cpp.
References araise.
Referenced by Body::animate().
twist()
void HeadBody::twist (GLfloat a) virtual
Turn head.
Definition at line 217 of file body.cpp.
References atwist.
Referenced by Body::animate().
Member Data Documentation
abend
GLfloat HeadBody::abend
head bend angle
Definition at line 226 of file body.hpp.
Referenced by bend(), and HeadBody().
araise
GLfloat HeadBody::araise
head raise angle
Definition at line 227 of file body.hpp.
Referenced by HeadBody(), and raise().
atwist
GLfloat HeadBody::atwist
head twist angle
Definition at line 228 of file body.hpp.
Referenced by HeadBody(), and twist().
HEAD_RAD
const GLfloat HeadBody::HEAD_RAD = 0.075 static private
Definition at line 222 of file body.hpp.
Referenced by HeadBody().
radius
GLfloat HeadBody::radius
head radius
Definition at line 225 of file body.hpp.
Referenced by HeadBody().
The documentation for this class was generated from the following files:
src/model/body.hpp
src/model/body.cpp