VREng: Shin Class Reference
Shin Class Reference
Shin class // Knee.
#include <body.hpp>
Public Member Functions
Shin (Foot *foot)
constructor
virtual ~Shin ()
destructor
virtual int init ()
Init shin.
virtual void bend (GLfloat a)
Bend knee.
virtual void twist (GLfloat a)
Turn knee.
Public Attributes
GLfloat length
shin length
GLfloat abend
knee bend angle
GLfloat atwist
knee twist angle
class Foot * foot
foot ptr
Static Private Attributes
static const GLfloat SHIN_LEN = 0.265
Detailed Description
Shin class // Knee.
Definition at line 308 of file body.hpp.
Constructor & Destructor Documentation
Shin()
Shin::Shin (Foot * foot)
constructor
Shin / Knee.
Definition at line 260 of file body.cpp.
References abend, foot, length, and SHIN_LEN.
~Shin()
virtual Shin::~Shin () inline virtual
destructor
Definition at line 319 of file body.hpp.
Member Function Documentation
bend()
void Shin::bend (GLfloat a) virtual
Bend knee.
Definition at line 270 of file body.cpp.
References abend.
Referenced by Body::animate().
init()
int Shin::init () virtual
Init shin.
Definition at line 267 of file body.cpp.
References foot, and Foot::init().
Referenced by Thigh::init().
twist()
void Shin::twist (GLfloat a) virtual
Turn knee.
Definition at line 273 of file body.cpp.
References atwist.
Referenced by Body::animate().
Member Data Documentation
abend
GLfloat Shin::abend
knee bend angle
Definition at line 314 of file body.hpp.
Referenced by bend(), and Shin().
atwist
GLfloat Shin::atwist
knee twist angle
Definition at line 315 of file body.hpp.
Referenced by twist().
foot
class Foot* Shin::foot
foot ptr
Definition at line 316 of file body.hpp.
Referenced by init(), and Shin().
length
GLfloat Shin::length
shin length
Definition at line 313 of file body.hpp.
Referenced by Shin().
SHIN_LEN
const GLfloat Shin::SHIN_LEN = 0.265 static private
Definition at line 310 of file body.hpp.
Referenced by Shin().
The documentation for this class was generated from the following files:
src/model/body.hpp
src/model/body.cpp