VREng: BoneAnimator Class Reference
BoneAnimator Class Reference
This is the main class that is to animate the bones and the 3d mesh correctly...
#include <boneanim.hpp>
Public Member Functions
BoneAnimator ()
Constructor.
virtual ~BoneAnimator ()
Destructor.
virtual void registerMesh (BoneMesh *zeMesh)
virtual void registerSkeleton (BoneVertex *zeRoot)
virtual void scale (float sx, float sy, float sz)
virtual void compileLinkList ()
virtual void emptyLinkList ()
virtual void generateLinkList ()
float getLength (Vertex *vertex, BoneVertex *node)
float getWeight (Vertex *vertex, BoneVertex *node)
virtual void render ()
virtual void renderSkeletonNode (BoneVertex *node)
virtual void animate ()
virtual void animateSkeletonNode (BoneVertex *node)
Public Attributes
BoneMesh * meshToMove
BoneVertex * skeleton
BoneList< BoneLink > linkList
BoneLink ** link
int links
int linkListCompiled
Private Member Functions
void addNodeAndChildren (BoneVertex *boneVertex, BoneList< BoneVertex > *list)
Detailed Description
This is the main class that is to animate the bones and the 3d mesh correctly...
It creates the link between the different vertices and bones and calculates the new position each time you ask
Typical use of this class : myBoneAnimator.registerMesh (oneMesh); myBoneAnimator.registerSkeleton (oneSkeleton); myBoneAnimator.compileLinkList (); ... in loop ... change skeleton current pos myBoneAnimator.animate (); myBoneAnimator.render (); ... end loop ...
Definition at line 58 of file boneanim.hpp.
Constructor & Destructor Documentation
BoneAnimator()
BoneAnimator::BoneAnimator ()
Constructor.
Definition at line 41 of file boneanim.cpp.
References link, linkListCompiled, links, meshToMove, and skeleton.
~BoneAnimator()
BoneAnimator::~BoneAnimator () virtual
Destructor.
Definition at line 50 of file boneanim.cpp.
References emptyLinkList().
Member Function Documentation
addNodeAndChildren()
void BoneAnimator::addNodeAndChildren (BoneVertex * boneVertex, BoneList< BoneVertex > * list) private
Definition at line 525 of file boneanim.cpp.
References BoneList< BoneElem >::addElement(), BoneVertex::child, BoneVertex::childListCompiled, BoneVertex::children, and BoneVertex::compileChildList().
Referenced by generateLinkList().
animate()
void BoneAnimator::animate () virtual
Definition at line 447 of file boneanim.cpp.
References animateSkeletonNode(), boneEditing, Vertex::currentNormal, Vertex::currentPosition, BoneVertex::generateCurrentMatrix(), Vertex::initialNormal, Vertex::initialPosition, Vertex::links, meshToMove, Vect3D::reset(), skeleton, BoneMesh::vertex, and BoneMesh::vertices.
Referenced by Face::render().
animateSkeletonNode()
void BoneAnimator::animateSkeletonNode (BoneVertex * node) inline virtual
Definition at line 480 of file boneanim.cpp.
References BoneVertex::child, BoneVertex::children, BoneVertex::compileLinkList(), BoneVertex::currentMatrix, Vertex::currentNormal, Vertex::currentPosition, BoneVertex::currentRotMatrix, BoneVertex::initialMatrixInverted, Vertex::initialNormal, Vertex::initialPosition, BoneVertex::initialRotMatrixInverted, BoneVertex::link, BoneVertex::linkListCompiled, BoneVertex::links, BoneLink::vertex, and BoneLink::weight.
Referenced by animate().
compileLinkList()
void BoneAnimator::compileLinkList () virtual
Definition at line 87 of file boneanim.cpp.
References BoneList< BoneElem >::getNiceTable(), link, linkList, linkListCompiled, and links.
Referenced by emptyLinkList(), and generateLinkList().
emptyLinkList()
void BoneAnimator::emptyLinkList () virtual
Definition at line 93 of file boneanim.cpp.
References compileLinkList(), BoneList< BoneElem >::empty(), link, linkList, linkListCompiled, and links.
Referenced by generateLinkList(), and ~BoneAnimator().
generateLinkList()
void BoneAnimator::generateLinkList () virtual
Definition at line 168 of file boneanim.cpp.
References BoneList< BoneElem >::addElement(), addNodeAndChildren(), compileLinkList(), Vertex::compileLinkList(), BoneMesh::compileVertexList(), DBG_MAN, BoneList< BoneElem >::empty(), emptyLinkList(), BoneVertex::findChild(), BoneVertex::generateInitialMatrix(), BoneList< BoneElem >::getNiceTable(), getWeight(), BoneVertex::influenceScaleFactor, link, linkList, links, meshToMove, normalize(), progress, skeleton, trace(), BoneMesh::vertex, BoneMesh::vertexListCompiled, BoneMesh::vertices, and BoneLink::weight.
Referenced by Face::load(), and scale().
getLength()
float BoneAnimator::getLength (Vertex * vertex, BoneVertex * node) inline
Definition at line 103 of file boneanim.cpp.
References BoneVertex::initialMatrix, Vertex::initialPosition, and Vect3D::length().
getWeight()
float BoneAnimator::getWeight (Vertex * vertex, BoneVertex * node) inline
Definition at line 136 of file boneanim.cpp.
References BoneVertex::child, BoneVertex::children, dist, BoneVertex::father, getDistanceFromAndOnBone(), and BoneVertex::influenceScaleFactor.
Referenced by generateLinkList().
registerMesh()
void BoneAnimator::registerMesh (BoneMesh * zeMesh) virtual
Definition at line 61 of file boneanim.cpp.
References DBG_MAN, Bonename::getName(), meshToMove, and trace().
Referenced by Face::load().
registerSkeleton()
void BoneAnimator::registerSkeleton (BoneVertex * zeRoot) virtual
Definition at line 67 of file boneanim.cpp.
References DBG_MAN, Bonename::getName(), skeleton, and trace().
Referenced by Face::load().
render()
void BoneAnimator::render () virtual
Definition at line 340 of file boneanim.cpp.
References axisRendering, boneEditing, Triangle::colorBlue, Triangle::colorGreen, Triangle::colorRed, BoneMesh::compileTriangleList(), Vertex::currentNormal, Vertex::currentPosition, Triangle::finalBlue, Triangle::finalGreen, Triangle::finalRed, Triangle::initialNormal, meshToMove, plainRendering, renderOneBone(), renderSkeletonNode(), skeleton, BoneMesh::triangle, BoneMesh::triangleListCompiled, BoneMesh::triangles, Triangle::u1, Triangle::u2, Triangle::u3, Triangle::v1, Triangle::v2, Triangle::v3, Triangle::vertex1, Triangle::vertex2, Triangle::vertex3, Vect3D::x, Vect3D::y, and Vect3D::z.
Referenced by Face::render().
renderSkeletonNode()
void BoneAnimator::renderSkeletonNode (BoneVertex * node) virtual
Definition at line 428 of file boneanim.cpp.
References BoneVertex::child, BoneVertex::children, BoneVertex::currentAngle, BoneVertex::currentAxis, BoneVertex::currentPosition, Bonename::name, renderLocalCoordinate1(), renderLocalCoordinate2(), selectedNodeName, Vect3D::x, Vect3D::y, and Vect3D::z.
Referenced by render().
scale()
void BoneAnimator::scale (float sx, float sy, float sz) virtual
Definition at line 75 of file boneanim.cpp.
References generateLinkList(), meshToMove, BoneMesh::scale(), BoneVertex::scale(), and skeleton.
Member Data Documentation
link
BoneLink** BoneAnimator::link
Definition at line 67 of file boneanim.hpp.
Referenced by BoneAnimator(), compileLinkList(), emptyLinkList(), and generateLinkList().
linkList
BoneList< BoneLink > BoneAnimator::linkList
Definition at line 66 of file boneanim.hpp.
Referenced by compileLinkList(), emptyLinkList(), and generateLinkList().
linkListCompiled
int BoneAnimator::linkListCompiled
Definition at line 69 of file boneanim.hpp.
Referenced by BoneAnimator(), compileLinkList(), and emptyLinkList().
links
int BoneAnimator::links
Definition at line 68 of file boneanim.hpp.
Referenced by BoneAnimator(), compileLinkList(), emptyLinkList(), and generateLinkList().
meshToMove
BoneMesh* BoneAnimator::meshToMove
Definition at line 62 of file boneanim.hpp.
Referenced by animate(), BoneAnimator(), generateLinkList(), registerMesh(), render(), Face::render(), and scale().
skeleton
BoneVertex* BoneAnimator::skeleton
Definition at line 63 of file boneanim.hpp.
Referenced by animate(), BoneAnimator(), generateLinkList(), registerSkeleton(), render(), Face::render(), and scale().
The documentation for this class was generated from the following files:
src/model/boneanim.hpp
src/model/boneanim.cpp