VREng: Bonename Class Reference
Bonename Class Reference
BoneName class.
#include <bonename.hpp>
Public Member Functions
Bonename ()
Bonename (char *op)
Bonename (Bonename *op)
Bonename (Bonename &op)
virtual ~Bonename ()
virtual void setName (char *zeName)
virtual char * getName ()
Public Attributes
char * name
name
Detailed Description
BoneName class.
Definition at line 36 of file bonename.hpp.
Constructor & Destructor Documentation
Bonename() [1/4]
Bonename::Bonename ()
Definition at line 34 of file bonename.cpp.
References name, and setName().
Bonename() [2/4]
Bonename::Bonename (char * op)
Definition at line 40 of file bonename.cpp.
References name.
Bonename() [3/4]
Bonename::Bonename (Bonename * op)
Definition at line 46 of file bonename.cpp.
References name.
Bonename() [4/4]
Bonename::Bonename (Bonename & op)
Definition at line 52 of file bonename.cpp.
References name.
~Bonename()
Bonename::~Bonename () virtual
Definition at line 58 of file bonename.cpp.
References name.
Member Function Documentation
getName()
char * Bonename::getName () virtual
Definition at line 71 of file bonename.cpp.
References name.
Referenced by BoneVertex::findChild(), BoneAnimator::registerMesh(), and BoneAnimator::registerSkeleton().
setName()
void Bonename::setName (char * zeName) virtual
Definition at line 64 of file bonename.cpp.
References name.
Referenced by BoneMesh::BoneMesh(), Bonename(), BoneVertex::readFromFile(), and V3d::readV3Dfile().
Member Data Documentation
name
char* Bonename::name
name
Definition at line 38 of file bonename.hpp.
Referenced by Bonename(), getName(), BoneAnimator::renderSkeletonNode(), setName(), and ~Bonename().
The documentation for this class was generated from the following files:
src/model/bonename.hpp
src/model/bonename.cpp