VREng: Arm Class Reference
Arm Class Reference
Arm class.
#include <body.hpp>
Public Member Functions
Arm (Forearm *forearm)
constructor
virtual ~Arm ()
destructor
virtual int init ()
Init arm.
virtual void raise (GLfloat a)
Raise arm.
virtual void bend (GLfloat a)
Rote arm.
virtual void twist (GLfloat a)
Turn arm.
Public Attributes
GLfloat length
arm length
GLfloat abend
arm bend angle
GLfloat araise
arm raise angle
GLfloat atwist
arm twist angle
class Forearm * forearm
forearm ptr
Static Private Attributes
static const GLfloat ARM_LEN = 0.165
Detailed Description
Arm class.
Definition at line 164 of file body.hpp.
Constructor & Destructor Documentation
Arm()
Arm::Arm (Forearm * forearm)
constructor
Arm.
Definition at line 164 of file body.cpp.
References abend, araise, ARM_LEN, atwist, and length.
~Arm()
virtual Arm::~Arm () inline virtual
destructor
Definition at line 176 of file body.hpp.
Member Function Documentation
bend()
void Arm::bend (GLfloat a) virtual
Rote arm.
Definition at line 178 of file body.cpp.
References abend.
Referenced by Body::animate().
init()
int Arm::init () virtual
Init arm.
Definition at line 172 of file body.cpp.
References forearm, and Forearm::init().
Referenced by Shoulder::init().
raise()
void Arm::raise (GLfloat a) virtual
Raise arm.
Definition at line 175 of file body.cpp.
References araise.
Referenced by Body::animate().
twist()
void Arm::twist (GLfloat a) virtual
Turn arm.
Definition at line 181 of file body.cpp.
References atwist.
Referenced by Body::animate().
Member Data Documentation
abend
GLfloat Arm::abend
arm bend angle
Definition at line 170 of file body.hpp.
Referenced by Arm(), and bend().
araise
GLfloat Arm::araise
arm raise angle
Definition at line 171 of file body.hpp.
Referenced by Arm(), and raise().
ARM_LEN
const GLfloat Arm::ARM_LEN = 0.165 static private
Definition at line 166 of file body.hpp.
Referenced by Arm().
atwist
GLfloat Arm::atwist
arm twist angle
Definition at line 172 of file body.hpp.
Referenced by Arm(), and twist().
forearm
class Forearm* Arm::forearm
forearm ptr
Definition at line 173 of file body.hpp.
Referenced by init().
length
GLfloat Arm::length
arm length
Definition at line 169 of file body.hpp.
Referenced by Arm().
The documentation for this class was generated from the following files:
src/model/body.hpp
src/model/body.cpp