VREng: BoneLink Class Reference
BoneLink Class Reference
BoneLink class.
#include <bonelink.hpp>
Public Member Functions
BoneLink (Vertex *zeVertex, BoneVertex *zeBoneVertex, float zeWeight)
Constructor.
virtual ~BoneLink ()
Destructor.
virtual void setVertex (Vertex *zeVertex)
virtual void setBoneVertex (BoneVertex *zeBoneVertex)
virtual void notifyTarget ()
virtual void setWeight (float zeWeight)
Public Attributes
Vertex * vertex
vertex.
BoneVertex * boneVertex
BoneVertex.
float weight
weight.
Detailed Description
BoneLink class.
Definition at line 39 of file bonelink.hpp.
Constructor & Destructor Documentation
BoneLink()
BoneLink::BoneLink (Vertex * zeVertex, BoneVertex * zeBoneVertex = NULL, float zeWeight = 0.)
Constructor.
Definition at line 34 of file bonelink.cpp.
References boneVertex, setBoneVertex(), setVertex(), setWeight(), and vertex.
~BoneLink()
BoneLink::~BoneLink () virtual
Destructor.
Definition at line 43 of file bonelink.cpp.
References boneVertex, BoneVertex::removeLink(), Vertex::removeLink(), and vertex.
Member Function Documentation
notifyTarget()
void BoneLink::notifyTarget () virtual
Definition at line 61 of file bonelink.cpp.
References BoneVertex::addLink(), Vertex::addLink(), boneVertex, and vertex.
setBoneVertex()
void BoneLink::setBoneVertex (BoneVertex * zeBoneVertex) virtual
Definition at line 55 of file bonelink.cpp.
References boneVertex, and BoneVertex::removeLink().
Referenced by BoneLink().
setVertex()
void BoneLink::setVertex (Vertex * zeVertex) virtual
Definition at line 49 of file bonelink.cpp.
References Vertex::removeLink(), and vertex.
Referenced by BoneLink().
setWeight()
void BoneLink::setWeight (float zeWeight) virtual
Definition at line 67 of file bonelink.cpp.
References weight.
Referenced by BoneLink().
Member Data Documentation
boneVertex
BoneVertex* BoneLink::boneVertex
BoneVertex.
Definition at line 42 of file bonelink.hpp.
Referenced by BoneLink(), notifyTarget(), setBoneVertex(), and ~BoneLink().
vertex
Vertex* BoneLink::vertex
vertex.
Definition at line 41 of file bonelink.hpp.
Referenced by BoneAnimator::animateSkeletonNode(), BoneLink(), notifyTarget(), setVertex(), and ~BoneLink().
weight
float BoneLink::weight
weight.
Definition at line 43 of file bonelink.hpp.
Referenced by BoneAnimator::animateSkeletonNode(), BoneAnimator::generateLinkList(), normalize(), and setWeight().
The documentation for this class was generated from the following files:
src/model/bonelink.hpp
src/model/bonelink.cpp