VREng: BoneVertex Class Reference
BoneVertex Class Reference
BoneVertex class.
#include <bonevertex.hpp>
Public Member Functions
BoneVertex ()
BoneVertex (Vect3D &zePosition, float zeAngle, Vect3D &zeAxis)
BoneVertex (Vect3D *zePosition, float zeAngle, Vect3D *zeAxis)
virtual ~BoneVertex ()
void setInitialPosition (Vect3D &zePosition)
void setInitialPosition (Vect3D *zePosition)
void setInitialPosition (float ox, float oy, float oz)
void setInitialRotation (float zeAngle, Vect3D &zeAxis)
void setInitialRotation (float zeAngle, Vect3D *zeAxis)
void setInitialRotation (float zeAngle, float axisx, float axisy, float axisz)
void setCurrentPosition (Vect3D &zePosition)
void setCurrentPosition (Vect3D *zePosition)
void setCurrentPosition (float ox, float oy, float oz)
void setCurrentRotation (float zeAngle, Vect3D &zeAxis)
void setCurrentRotation (float zeAngle, Vect3D *zeAxis)
void setCurrentRotation (float zeAngle, float axisx, float axisy, float axisz)
void resetCurrentPosition (void)
void resetCurrentRotation (void)
void translateCurrentPosition (Vect3D &delta)
void translateCurrentPosition (Vect3D *delta)
void translateCurrentPosition (float dx, float dy, float dz)
void scaleCurrentPosition (float scalex, float scaley, float scalez)
void scaleCurrentPosition (float scale)
void scale (float sx, float sy, float sz)
void setFather (BoneVertex *zeFather)
void addChild (BoneVertex *newChild)
void removeChild (const char *zeName)
BoneVertex * findChild (const char *zeName)
void addLink (BoneLink *zeLink)
void removeLink (BoneLink *zeLink)
void compileChildList ()
void compileLinkList ()
void generateInitialMatrix ()
void generateCurrentMatrix ()
void read (char *filename, float size=1.)
void readFromFile (FILE *file, float size=1.)
Public Member Functions inherited from Bonename
Bonename ()
Bonename (char *op)
Bonename (Bonename *op)
Bonename (Bonename &op)
virtual ~Bonename ()
virtual void setName (char *zeName)
virtual char * getName ()
Public Attributes
Vect3D initialPosition
float initialAngle
Vect3D initialAxis
Vect3D currentPosition
float currentAngle
Vect3D currentAxis
BoneList< BoneVertex > childList
BoneVertex ** child
BoneVertex * father
int children
int childListCompiled
BoneList< BoneLink > linkList
BoneLink ** link
int links
int linkListCompiled
float initialMatrix [16]
float initialMatrixInverted [16]
float currentMatrix [16]
float initialRotMatrix [16]
float initialRotMatrixInverted [16]
float currentRotMatrix [16]
float influenceScaleFactor
int animated
Public Attributes inherited from Bonename
char * name
name
Detailed Description
BoneVertex class.
This class represents the extremity of a bone So a bone is made of one of this class (that contains translation/rotation) and a reference to it's father (the extremity it depends of) This extremity also has several children whom he'll be the father (see that like a tree)
Definition at line 50 of file bonevertex.hpp.
Constructor & Destructor Documentation
BoneVertex() [1/3]
BoneVertex::BoneVertex ()
Definition at line 36 of file bonevertex.cpp.
References animated, child, childListCompiled, children, currentAngle, currentAxis, currentPosition, father, influenceScaleFactor, initialAngle, initialAxis, initialPosition, link, linkListCompiled, links, and Vect3D::set().
Referenced by readFromFile().
BoneVertex() [2/3]
BoneVertex::BoneVertex (Vect3D & zePosition, float zeAngle, Vect3D & zeAxis)
Definition at line 57 of file bonevertex.cpp.
References animated, child, childListCompiled, children, currentAngle, currentAxis, currentPosition, father, initialAngle, initialAxis, initialPosition, link, linkListCompiled, and links.
BoneVertex() [3/3]
BoneVertex::BoneVertex (Vect3D * zePosition, float zeAngle, Vect3D * zeAxis)
Definition at line 76 of file bonevertex.cpp.
References animated, child, childListCompiled, children, currentAngle, currentAxis, currentPosition, father, initialAngle, initialAxis, initialPosition, link, linkListCompiled, and links.
~BoneVertex()
BoneVertex::~BoneVertex () virtual
Definition at line 95 of file bonevertex.cpp.
References child, childList, childListCompiled, children, compileChildList(), compileLinkList(), BoneList< BoneElem >::empty(), link, linkList, linkListCompiled, and links.
Member Function Documentation
addChild()
void BoneVertex::addChild (BoneVertex * newChild)
Definition at line 250 of file bonevertex.cpp.
References BoneList< BoneElem >::addElement(), childList, childListCompiled, and setFather().
Referenced by readFromFile().
addLink()
void BoneVertex::addLink (BoneLink * zeLink)
Definition at line 287 of file bonevertex.cpp.
References BoneList< BoneElem >::addElement(), linkList, and linkListCompiled.
Referenced by BoneLink::notifyTarget().
compileChildList()
void BoneVertex::compileChildList ()
Definition at line 301 of file bonevertex.cpp.
References child, childList, childListCompiled, children, and BoneList< BoneElem >::getNiceTable().
Referenced by BoneAnimator::addNodeAndChildren(), findChild(), generateCurrentMatrix(), generateInitialMatrix(), readFromFile(), scale(), and ~BoneVertex().
compileLinkList()
void BoneVertex::compileLinkList ()
Definition at line 307 of file bonevertex.cpp.
References BoneList< BoneElem >::getNiceTable(), link, linkList, linkListCompiled, and links.
Referenced by BoneAnimator::animateSkeletonNode(), and ~BoneVertex().
findChild()
BoneVertex * BoneVertex::findChild (const char * zeName)
Definition at line 270 of file bonevertex.cpp.
References child, childListCompiled, children, compileChildList(), findChild(), and Bonename::getName().
Referenced by Face::animate(), Face::animEyeBall(), Face::animEyeBrow(), Face::animEyeLid(), Face::animHead(), Face::animLip(), Face::animNose(), findChild(), BoneAnimator::generateLinkList(), and removeChild().
generateCurrentMatrix()
void BoneVertex::generateCurrentMatrix ()
Definition at line 372 of file bonevertex.cpp.
References child, childListCompiled, children, compileChildList(), currentAngle, currentAxis, currentMatrix, currentPosition, currentRotMatrix, Vect3D::x, Vect3D::y, and Vect3D::z.
Referenced by BoneAnimator::animate().
generateInitialMatrix()
void BoneVertex::generateInitialMatrix ()
Definition at line 314 of file bonevertex.cpp.
References child, childListCompiled, children, compileChildList(), initialAngle, initialAxis, initialMatrix, initialMatrixInverted, initialPosition, initialRotMatrix, initialRotMatrixInverted, Vect3D::x, Vect3D::y, and Vect3D::z.
Referenced by BoneAnimator::generateLinkList().
read()
void BoneVertex::read (char * filename, float size = 1.)
Definition at line 411 of file bonevertex.cpp.
References File::closeFile(), error(), File::openFile(), readFromFile(), and scale().
readFromFile()
void BoneVertex::readFromFile (FILE * file, float size = 1.)
Definition at line 422 of file bonevertex.cpp.
References addChild(), BoneVertex(), compileChildList(), readFloat(), readFromFile(), readInt(), readString(), scale(), setInitialPosition(), setInitialRotation(), and Bonename::setName().
Referenced by read(), readFromFile(), and V3d::readV3Dfile().
removeChild()
void BoneVertex::removeChild (const char * zeName)
Definition at line 258 of file bonevertex.cpp.
References childList, childListCompiled, findChild(), and BoneList< BoneElem >::removeElement().
removeLink()
void BoneVertex::removeLink (BoneLink * zeLink)
Definition at line 294 of file bonevertex.cpp.
References linkList, linkListCompiled, and BoneList< BoneElem >::removeElement().
Referenced by BoneLink::setBoneVertex(), and BoneLink::~BoneLink().
resetCurrentPosition()
void BoneVertex::resetCurrentPosition (void)
Definition at line 187 of file bonevertex.cpp.
References currentPosition, and initialPosition.
Referenced by Face::animate(), Face::animEyeBall(), Face::animEyeBrow(), Face::animEyeLid(), Face::animLip(), and Face::animNose().
resetCurrentRotation()
void BoneVertex::resetCurrentRotation (void)
Definition at line 192 of file bonevertex.cpp.
References currentAngle, currentAxis, initialAngle, and initialAxis.
scale()
void BoneVertex::scale (float sx, float sy, float sz)
Definition at line 228 of file bonevertex.cpp.
References child, childListCompiled, children, compileChildList(), currentPosition, initialPosition, Vect3D::x, Vect3D::y, and Vect3D::z.
Referenced by read(), readFromFile(), BoneAnimator::scale(), and scaleCurrentPosition().
scaleCurrentPosition() [1/2]
void BoneVertex::scaleCurrentPosition (float scale)
Definition at line 222 of file bonevertex.cpp.
References currentPosition, and scale().
scaleCurrentPosition() [2/2]
void BoneVertex::scaleCurrentPosition (float scalex, float scaley, float scalez)
Definition at line 215 of file bonevertex.cpp.
References currentPosition, Vect3D::x, Vect3D::y, and Vect3D::z.
Referenced by Face::animate(), Face::animEyeBall(), Face::animEyeLid(), and Face::animNose().
setCurrentPosition() [1/3]
void BoneVertex::setCurrentPosition (float ox, float oy, float oz)
Definition at line 162 of file bonevertex.cpp.
References currentPosition.
setCurrentPosition() [2/3]
void BoneVertex::setCurrentPosition (Vect3D & zePosition)
Definition at line 152 of file bonevertex.cpp.
References currentPosition.
setCurrentPosition() [3/3]
void BoneVertex::setCurrentPosition (Vect3D * zePosition)
Definition at line 157 of file bonevertex.cpp.
References currentPosition.
setCurrentRotation() [1/3]
void BoneVertex::setCurrentRotation (float zeAngle, float axisx, float axisy, float axisz)
Definition at line 179 of file bonevertex.cpp.
References currentAngle, and currentAxis.
setCurrentRotation() [2/3]
void BoneVertex::setCurrentRotation (float zeAngle, Vect3D & zeAxis)
Definition at line 167 of file bonevertex.cpp.
References currentAngle, and currentAxis.
Referenced by Face::animate(), Face::animEyeBall(), Face::animEyeBrow(), Face::animEyeLid(), Face::animHead(), and Face::animLip().
setCurrentRotation() [3/3]
void BoneVertex::setCurrentRotation (float zeAngle, Vect3D * zeAxis)
Definition at line 173 of file bonevertex.cpp.
References currentAngle, and currentAxis.
setFather()
void BoneVertex::setFather (BoneVertex * zeFather)
Definition at line 244 of file bonevertex.cpp.
References father.
Referenced by addChild().
setInitialPosition() [1/3]
void BoneVertex::setInitialPosition (float ox, float oy, float oz)
Definition at line 121 of file bonevertex.cpp.
References currentPosition, and initialPosition.
setInitialPosition() [2/3]
void BoneVertex::setInitialPosition (Vect3D & zePosition)
Definition at line 109 of file bonevertex.cpp.
References currentPosition, and initialPosition.
Referenced by readFromFile().
setInitialPosition() [3/3]
void BoneVertex::setInitialPosition (Vect3D * zePosition)
Definition at line 115 of file bonevertex.cpp.
References currentPosition, and initialPosition.
setInitialRotation() [1/3]
void BoneVertex::setInitialRotation (float zeAngle, float axisx, float axisy, float axisz)
Definition at line 143 of file bonevertex.cpp.
References currentAngle, currentAxis, initialAngle, and initialAxis.
setInitialRotation() [2/3]
void BoneVertex::setInitialRotation (float zeAngle, Vect3D & zeAxis)
Definition at line 127 of file bonevertex.cpp.
References currentAngle, currentAxis, initialAngle, and initialAxis.
Referenced by readFromFile().
setInitialRotation() [3/3]
void BoneVertex::setInitialRotation (float zeAngle, Vect3D * zeAxis)
Definition at line 135 of file bonevertex.cpp.
References currentAngle, currentAxis, initialAngle, and initialAxis.
translateCurrentPosition() [1/3]
void BoneVertex::translateCurrentPosition (float dx, float dy, float dz)
Definition at line 208 of file bonevertex.cpp.
References currentPosition, Vect3D::x, Vect3D::y, and Vect3D::z.
translateCurrentPosition() [2/3]
void BoneVertex::translateCurrentPosition (Vect3D & delta)
Definition at line 198 of file bonevertex.cpp.
References currentPosition.
Referenced by Face::animate(), Face::animEyeBrow(), and Face::animLip().
translateCurrentPosition() [3/3]
void BoneVertex::translateCurrentPosition (Vect3D * delta)
Definition at line 203 of file bonevertex.cpp.
References currentPosition.
Member Data Documentation
animated
int BoneVertex::animated
Definition at line 92 of file bonevertex.hpp.
Referenced by BoneVertex().
child
BoneVertex** BoneVertex::child
Definition at line 67 of file bonevertex.hpp.
Referenced by BoneAnimator::addNodeAndChildren(), BoneAnimator::animateSkeletonNode(), BoneVertex(), compileChildList(), findChild(), generateCurrentMatrix(), generateInitialMatrix(), BoneAnimator::getWeight(), renderOneBone(), BoneAnimator::renderSkeletonNode(), scale(), and ~BoneVertex().
childList
BoneList< BoneVertex > BoneVertex::childList
Definition at line 66 of file bonevertex.hpp.
Referenced by addChild(), compileChildList(), removeChild(), and ~BoneVertex().
childListCompiled
int BoneVertex::childListCompiled
Definition at line 70 of file bonevertex.hpp.
Referenced by addChild(), BoneAnimator::addNodeAndChildren(), BoneVertex(), compileChildList(), findChild(), generateCurrentMatrix(), generateInitialMatrix(), removeChild(), scale(), and ~BoneVertex().
children
int BoneVertex::children
Definition at line 69 of file bonevertex.hpp.
Referenced by BoneAnimator::addNodeAndChildren(), BoneAnimator::animateSkeletonNode(), BoneVertex(), compileChildList(), findChild(), generateCurrentMatrix(), generateInitialMatrix(), BoneAnimator::getWeight(), renderOneBone(), BoneAnimator::renderSkeletonNode(), scale(), and ~BoneVertex().
currentAngle
float BoneVertex::currentAngle
Definition at line 62 of file bonevertex.hpp.
Referenced by BoneVertex(), generateCurrentMatrix(), BoneAnimator::renderSkeletonNode(), resetCurrentRotation(), setCurrentRotation(), and setInitialRotation().
currentAxis
Vect3D BoneVertex::currentAxis
Definition at line 63 of file bonevertex.hpp.
Referenced by BoneVertex(), generateCurrentMatrix(), BoneAnimator::renderSkeletonNode(), resetCurrentRotation(), setCurrentRotation(), and setInitialRotation().
currentMatrix
float BoneVertex::currentMatrix[16]
Definition at line 82 of file bonevertex.hpp.
Referenced by BoneAnimator::animateSkeletonNode(), generateCurrentMatrix(), and renderOneBone().
currentPosition
Vect3D BoneVertex::currentPosition
Definition at line 61 of file bonevertex.hpp.
Referenced by BoneVertex(), generateCurrentMatrix(), BoneAnimator::renderSkeletonNode(), resetCurrentPosition(), scale(), scaleCurrentPosition(), setCurrentPosition(), setInitialPosition(), and translateCurrentPosition().
currentRotMatrix
float BoneVertex::currentRotMatrix[16]
Definition at line 86 of file bonevertex.hpp.
Referenced by BoneAnimator::animateSkeletonNode(), and generateCurrentMatrix().
father
BoneVertex* BoneVertex::father
Definition at line 68 of file bonevertex.hpp.
Referenced by BoneVertex(), BoneAnimator::getWeight(), renderOneBone(), and setFather().
influenceScaleFactor
float BoneVertex::influenceScaleFactor
Definition at line 89 of file bonevertex.hpp.
Referenced by BoneVertex(), BoneAnimator::generateLinkList(), and BoneAnimator::getWeight().
initialAngle
float BoneVertex::initialAngle
Definition at line 57 of file bonevertex.hpp.
Referenced by BoneVertex(), generateInitialMatrix(), resetCurrentRotation(), and setInitialRotation().
initialAxis
Vect3D BoneVertex::initialAxis
Definition at line 58 of file bonevertex.hpp.
Referenced by BoneVertex(), generateInitialMatrix(), resetCurrentRotation(), and setInitialRotation().
initialMatrix
float BoneVertex::initialMatrix[16]
Definition at line 80 of file bonevertex.hpp.
Referenced by generateInitialMatrix(), getDistanceFromAndOnBone(), and BoneAnimator::getLength().
initialMatrixInverted
float BoneVertex::initialMatrixInverted[16]
Definition at line 81 of file bonevertex.hpp.
Referenced by BoneAnimator::animateSkeletonNode(), and generateInitialMatrix().
initialPosition
Vect3D BoneVertex::initialPosition
Definition at line 56 of file bonevertex.hpp.
Referenced by BoneVertex(), generateInitialMatrix(), resetCurrentPosition(), scale(), and setInitialPosition().
initialRotMatrix
float BoneVertex::initialRotMatrix[16]
Definition at line 84 of file bonevertex.hpp.
Referenced by generateInitialMatrix().
initialRotMatrixInverted
float BoneVertex::initialRotMatrixInverted[16]
Definition at line 85 of file bonevertex.hpp.
Referenced by BoneAnimator::animateSkeletonNode(), and generateInitialMatrix().
link
BoneLink** BoneVertex::link
Definition at line 75 of file bonevertex.hpp.
Referenced by BoneAnimator::animateSkeletonNode(), BoneVertex(), compileLinkList(), and ~BoneVertex().
linkList
BoneList< BoneLink > BoneVertex::linkList
Definition at line 74 of file bonevertex.hpp.
Referenced by addLink(), compileLinkList(), removeLink(), and ~BoneVertex().
linkListCompiled
int BoneVertex::linkListCompiled
Definition at line 77 of file bonevertex.hpp.
Referenced by addLink(), BoneAnimator::animateSkeletonNode(), BoneVertex(), compileLinkList(), removeLink(), and ~BoneVertex().
links
int BoneVertex::links
Definition at line 76 of file bonevertex.hpp.
Referenced by BoneAnimator::animateSkeletonNode(), BoneVertex(), compileLinkList(), and ~BoneVertex().
The documentation for this class was generated from the following files:
src/model/bonevertex.hpp
src/model/bonevertex.cpp