VREng: Bvh Class Reference
Bvh Class Reference
#include <bvh.hpp>
Public Member Functions
Bvh (const char *url)
virtual ~Bvh ()
void recurs (bvhPart *some)
void process (string line)
void init (string bvhFile)
Static Public Member Functions
static void httpReader (void *_bvh, class Http *http)
Public Attributes
bvhPart * root
float frameTime
int framesNum
char * url
Private Types
enum mode {
NONE, OFFSET, CHANNELS, JOINT,
ROOT, End, Site, MOTION,
Frames, Frame, Time, MOTIONDATA
}
Private Member Functions
virtual void download (const char *url)
virtual const char * getUrl () const
Private Attributes
bool verbose
bvhPart * current
vector< bvhPart * > bvhPartsLinear
mode theMode
int vertIndex
uint32_t channelIndex
uint32_t partIndex
int data
uint32_t channelsNum
the channels vector will store it's own size, so this is just for error checking.
matrix16f tempMotion
matrix16f tempMotionY
matrix16f tempMotionX
matrix16f tempMotionZ
Detailed Description
Definition at line 522 of file bvh.hpp.
Member Enumeration Documentation
mode
enum Bvh::mode private
Enumerator
NONE
OFFSET
CHANNELS
JOINT
ROOT
End
Site
MOTION
Frames
Frame
Time
MOTIONDATA
Definition at line 524 of file bvh.hpp.
Constructor & Destructor Documentation
Bvh()
Bvh::Bvh (const char * url)
Definition at line 47 of file bvh.cpp.
References Cache::getCacheName().
~Bvh()
virtual Bvh::~Bvh () inline virtual
Definition at line 554 of file bvh.hpp.
Member Function Documentation
download()
void Bvh::download (const char * url) private virtual
Definition at line 56 of file bvh.cpp.
References Http::httpOpen().
getUrl()
const char * Bvh::getUrl () const private virtual
Definition at line 63 of file bvh.cpp.
Referenced by httpReader().
httpReader()
void Bvh::httpReader (void * _bvh, class Http * http) static
Definition at line 68 of file bvh.cpp.
References File::closeFile(), getUrl(), and Cache::openCache().
init()
void Bvh::init (string bvhFile)
Definition at line 322 of file bvh.cpp.
References error().
process()
void Bvh::process (string line)
Definition at line 78 of file bvh.cpp.
References bvhPart::child, DEG2RAD, error(), NONE, bvhPart::parent, bvhPart::Xpos, bvhPart::Xrot, bvhPart::Ypos, bvhPart::Yrot, bvhPart::Zpos, and bvhPart::Zrot.
recurs()
void Bvh::recurs (bvhPart * some)
Definition at line 305 of file bvh.cpp.
References bvhPart::child, matrix16f::identity(), bvhPart::motion, bvhPart::name, bvhPart::offset, matrix16f::translate(), and vector3f::vertex.
Member Data Documentation
bvhPartsLinear
vector<bvhPart*> Bvh::bvhPartsLinear private
Definition at line 535 of file bvh.hpp.
channelIndex
uint32_t Bvh::channelIndex private
Definition at line 540 of file bvh.hpp.
channelsNum
uint32_t Bvh::channelsNum private
the channels vector will store it's own size, so this is just for error checking.
Definition at line 545 of file bvh.hpp.
current
bvhPart* Bvh::current private
Definition at line 534 of file bvh.hpp.
data
int Bvh::data private
Definition at line 543 of file bvh.hpp.
framesNum
int Bvh::framesNum
Definition at line 556 of file bvh.hpp.
frameTime
float Bvh::frameTime
Definition at line 528 of file bvh.hpp.
partIndex
uint32_t Bvh::partIndex private
Definition at line 541 of file bvh.hpp.
root
bvhPart* Bvh::root
Definition at line 527 of file bvh.hpp.
tempMotion
matrix16f Bvh::tempMotion private
Definition at line 547 of file bvh.hpp.
tempMotionX
matrix16f Bvh::tempMotionX private
Definition at line 549 of file bvh.hpp.
tempMotionY
matrix16f Bvh::tempMotionY private
Definition at line 548 of file bvh.hpp.
tempMotionZ
matrix16f Bvh::tempMotionZ private
Definition at line 550 of file bvh.hpp.
theMode
mode Bvh::theMode private
Definition at line 537 of file bvh.hpp.
url
char* Bvh::url
Definition at line 557 of file bvh.hpp.
verbose
bool Bvh::verbose private
Definition at line 523 of file bvh.hpp.
vertIndex
int Bvh::vertIndex private
Definition at line 538 of file bvh.hpp.
The documentation for this class was generated from the following files:
src/model/bvh.hpp
src/model/bvh.cpp