VREng: movable Class Reference
movable Class Reference
Mostly virtual class for any entity in the scene.
#include <bvh.hpp>
Public Member Functions
movable ()
movable (string name)
virtual ~movable ()
void init ()
movable & operator= (const movable &other)
void update ()
void move (int pitch, int turn, int roll, float x, float y, float z)
void setName (string name)
virtual void getBoundingBox ()
void getAABB ()
void drawAABB ()
void drawBoundingBox ()
Public Attributes
float mass
physical constants
matrix9f Ibody
moment of inertia tensor
matrix9f IbodyInv
inverse of moi tensor
matrix16f location
state variable
matrix16f newLocation
string name
momentum
bool drawBB
bool BBcollided
vector3f centerBB
vector3f edgesBB
vector3f boundingBox [8]
vector3f oldCenterAABB
vector3f centerAABB
vector3f edgesAABB
vector3f AABB [8]
Detailed Description
Mostly virtual class for any entity in the scene.
It holds a lot of physical information that would be better off in a subclass where it would make sense, as lights and camera don't really need such properties.
Definition at line 155 of file bvh.hpp.
Constructor & Destructor Documentation
movable() [1/2]
movable::movable ()
Definition at line 593 of file bvh.cpp.
movable() [2/2]
movable::movable (string name)
Definition at line 598 of file bvh.cpp.
References error().
~movable()
virtual movable::~movable () inline virtual
Definition at line 160 of file bvh.hpp.
Member Function Documentation
drawAABB()
void movable::drawAABB ()
Definition at line 697 of file bvh.cpp.
References error().
drawBoundingBox()
void movable::drawBoundingBox ()
Definition at line 732 of file bvh.cpp.
References error().
getAABB()
void movable::getAABB ()
Definition at line 649 of file bvh.cpp.
References error(), offset, and vector3f::vertex.
getBoundingBox()
virtual void movable::getBoundingBox () inline virtual
Reimplemented in rigid, objloader, and light.
Definition at line 204 of file bvh.hpp.
init()
void movable::init ()
Definition at line 605 of file bvh.cpp.
References error(), and normalize().
move()
void movable::move (int pitch, int turn, int roll, float x, float y, float z)
Definition at line 638 of file bvh.cpp.
References error(), and ROTATE_SLOWNESS.
operator=()
movable & movable::operator= (const movable & other)
Definition at line 620 of file bvh.cpp.
References location.
setName()
void movable::setName (string name)
Definition at line 626 of file bvh.cpp.
References error().
update()
void movable::update () inline
Definition at line 166 of file bvh.hpp.
Member Data Documentation
AABB
vector3f movable::AABB[8]
Definition at line 222 of file bvh.hpp.
BBcollided
bool movable::BBcollided
Definition at line 214 of file bvh.hpp.
boundingBox
vector3f movable::boundingBox[8]
Definition at line 218 of file bvh.hpp.
centerAABB
vector3f movable::centerAABB
Definition at line 220 of file bvh.hpp.
centerBB
vector3f movable::centerBB
Definition at line 216 of file bvh.hpp.
drawBB
bool movable::drawBB
Definition at line 208 of file bvh.hpp.
edgesAABB
vector3f movable::edgesAABB
Definition at line 221 of file bvh.hpp.
edgesBB
vector3f movable::edgesBB
Definition at line 217 of file bvh.hpp.
Ibody
matrix9f movable::Ibody
moment of inertia tensor
Definition at line 174 of file bvh.hpp.
IbodyInv
matrix9f movable::IbodyInv
inverse of moi tensor
Definition at line 176 of file bvh.hpp.
location
matrix16f movable::location
state variable
Definition at line 178 of file bvh.hpp.
Referenced by operator=().
mass
float movable::mass
physical constants
Definition at line 172 of file bvh.hpp.
name
string movable::name
momentum
Definition at line 201 of file bvh.hpp.
newLocation
matrix16f movable::newLocation
Definition at line 179 of file bvh.hpp.
oldCenterAABB
vector3f movable::oldCenterAABB
Definition at line 219 of file bvh.hpp.
The documentation for this class was generated from the following files:
src/model/bvh.hpp
src/model/bvh.cpp