VREng: matrix16f Class Reference
matrix16f Class Reference
Array of 16 floats in OpenGL conformant style.
#include <bvh.hpp>
Public Member Functions
void reset ()
void identity ()
void print ()
void translate (float x, float y, float z)
void scale (float x, float y, float z)
void RotateX (int deg)
void RotateY (int deg)
void RotateZ (int deg)
void RotateX (float rad)
void RotateY (float rad)
void RotateZ (float rad)
void RotateXYZ (float x, float y, float z)
void Rotate (matrix16f m1)
void set (vector3f right, vector3f up, vector3f out)
matrix16f & operator= (const matrix16f &m1)
vector3f transform (vector3f point)
matrix16f FlipOrientation ()
void normalize ()
matrix16f ()
Public Attributes
float matrix [16]
Friends
matrix16f operator+ (const matrix16f &m1, const matrix16f &m2)
matrix16f operator+ (const matrix16f &m1, const vector3f &v2)
matrix16f operator- (const matrix16f &m1, const matrix16f &m2)
matrix16f operator* (const matrix16f &m1, const float scalar)
matrix16f operator* (const matrix16f &m1, const matrix16f &m2)
matrix16f operator/ (const matrix16f &m1, const float scalar)
bool operator== (const matrix16f &m1, const matrix16f &m2)
Detailed Description
Array of 16 floats in OpenGL conformant style.
Plenty of useful overloaded operators, including those for interacting with the matrix9f and vector3f classes.
Definition at line 54 of file bvh.hpp.
Constructor & Destructor Documentation
matrix16f()
matrix16f::matrix16f () inline
Definition at line 95 of file bvh.hpp.
Member Function Documentation
FlipOrientation()
matrix16f matrix16f::FlipOrientation ()
Definition at line 1018 of file bvh.cpp.
References matrix.
identity()
void matrix16f::identity ()
Definition at line 984 of file bvh.cpp.
Referenced by Bvh::recurs(), RotateX(), RotateY(), and RotateZ().
normalize()
void matrix16f::normalize ()
Definition at line 1029 of file bvh.cpp.
References crossProduct(), vector3f::length(), and vector3f::vertex.
operator=()
matrix16f & matrix16f::operator= (const matrix16f & m1)
Definition at line 1270 of file bvh.cpp.
References matrix.
print()
void matrix16f::print ()
Definition at line 1049 of file bvh.cpp.
reset()
void matrix16f::reset ()
Definition at line 979 of file bvh.cpp.
Rotate()
void matrix16f::Rotate (matrix16f m1)
Definition at line 1230 of file bvh.cpp.
References matrix.
RotateX() [1/2]
void matrix16f::RotateX (float rad)
Definition at line 1144 of file bvh.cpp.
References identity(), and matrix.
RotateX() [2/2]
void matrix16f::RotateX (int deg)
Definition at line 1061 of file bvh.cpp.
References DEG2RAD, identity(), and matrix.
RotateXYZ()
void matrix16f::RotateXYZ (float x, float y, float z)
Definition at line 1223 of file bvh.cpp.
RotateY() [1/2]
void matrix16f::RotateY (float rad)
Definition at line 1172 of file bvh.cpp.
References identity(), and matrix.
RotateY() [2/2]
void matrix16f::RotateY (int deg)
Definition at line 1089 of file bvh.cpp.
References DEG2RAD, identity(), and matrix.
RotateZ() [1/2]
void matrix16f::RotateZ (float rad)
Definition at line 1200 of file bvh.cpp.
References identity(), and matrix.
RotateZ() [2/2]
void matrix16f::RotateZ (int deg)
Definition at line 1117 of file bvh.cpp.
References DEG2RAD, identity(), and matrix.
scale()
void matrix16f::scale (float x, float y, float z)
Definition at line 1000 of file bvh.cpp.
set()
void matrix16f::set (vector3f right, vector3f up, vector3f out)
Definition at line 1254 of file bvh.cpp.
References vector3f::vertex.
transform()
vector3f matrix16f::transform (vector3f point)
Definition at line 1008 of file bvh.cpp.
References vector3f::vertex.
translate()
void matrix16f::translate (float x, float y, float z)
Definition at line 992 of file bvh.cpp.
Referenced by Bvh::recurs().
Friends And Related Function Documentation
operator* [1/2]
matrix16f operator* (const matrix16f & m1, const float scalar) friend
Definition at line 1307 of file bvh.cpp.
operator* [2/2]
matrix16f operator* (const matrix16f & m1, const matrix16f & m2) friend
Definition at line 1316 of file bvh.cpp.
operator+ [1/2]
matrix16f operator+ (const matrix16f & m1, const matrix16f & m2) friend
Definition at line 1277 of file bvh.cpp.
operator+ [2/2]
matrix16f operator+ (const matrix16f & m1, const vector3f & v2) friend
Definition at line 1287 of file bvh.cpp.
operator-
matrix16f operator- (const matrix16f & m1, const matrix16f & m2) friend
Definition at line 1298 of file bvh.cpp.
operator/
matrix16f operator/ (const matrix16f & m1, const float scalar) friend
Definition at line 1344 of file bvh.cpp.
operator==
bool operator== (const matrix16f & m1, const matrix16f & m2) friend
Definition at line 1353 of file bvh.cpp.
Member Data Documentation
matrix
float matrix16f::matrix[16]
Definition at line 56 of file bvh.hpp.
Referenced by FlipOrientation(), operator*(), operator+(), operator-(), operator/(), operator=(), operator==(), Rotate(), RotateX(), RotateY(), and RotateZ().
The documentation for this class was generated from the following files:
src/model/bvh.hpp
src/model/bvh.cpp