VREng: Dxf Class Reference
Dxf Class Reference
Dxf class.
#include <dxf.hpp>
Public Member Functions
Dxf (const char *url)
virtual ~Dxf ()
virtual void setScale (float scale)
Sets the scale.
virtual void setColor (int type, float *color)
Sets the color.
virtual float getRadius ()
Gets the radius.
virtual void bindTexture2D (int textureId)
Binds texture number.
virtual GLint displaylist ()
Draws in displaylist.
virtual bool draw (DXF_file *dxffile)
Draws.
virtual void render ()
Renders.
Static Public Member Functions
static void httpReader (void *adxf, class Http *http)
Downloads.
Public Attributes
DXF_file * dxffile
Private Member Functions
virtual const char * getUrl () const
get an Url
Private Attributes
bool loaded
flag loaded or not
float currentScale
current scale
float desiredScale
desired scale
GLint dlist
display list
char * url
dxf url
bool flgcolor
flag color setted
float mat_diffuse [4]
float mat_ambient [4]
float mat_specular [4]
int texture
Detailed Description
Dxf class.
Definition at line 360 of file dxf.hpp.
Constructor & Destructor Documentation
Dxf()
Dxf::Dxf (const char * url)
Definition at line 46 of file dxf.cpp.
References flgcolor, Http::httpOpen(), httpReader(), mat_ambient, mat_diffuse, mat_specular, and url.
~Dxf()
Dxf::~Dxf () virtual
Definition at line 61 of file dxf.cpp.
References deleteDXF(), dxffile, and url.
Member Function Documentation
bindTexture2D()
void Dxf::bindTexture2D (int textureId) virtual
Binds texture number.
Definition at line 91 of file dxf.cpp.
displaylist()
GLint Dxf::displaylist () virtual
Draws in displaylist.
Definition at line 203 of file dxf.cpp.
References dlist, draw(), and dxffile.
Referenced by Model::drawer().
draw()
bool Dxf::draw (DXF_file * dxffile) virtual
Draws.
Definition at line 143 of file dxf.cpp.
References copyPoint3D(), currentScale, deletePoint3D(), desiredScale, dxffile, error(), flgcolor, loaded, mat_ambient, mat_diffuse, mat_specular, newPoint3D(), SceneObj::num_objects, Polygon::num_points, PolyMeshObj::num_polygons, SceneObj::objects, DXF_file::objects, Polygon::points, PolyMeshObj::polygons, Polygon::refs, setScale(), subPoint3D(), Point3D::x, Point3D::y, and Point3D::z.
Referenced by displaylist().
getRadius()
float Dxf::getRadius () virtual
Gets the radius.
Definition at line 107 of file dxf.cpp.
References Polygon::num_points, PolyMeshObj::num_polygons, Polygon::points, PolyMeshObj::polygons, Polygon::refs, Point3D::x, Point3D::y, and Point3D::z.
Referenced by Model::scaler().
getUrl()
const char * Dxf::getUrl () const private virtual
get an Url
Definition at line 68 of file dxf.cpp.
References url.
Referenced by httpReader().
httpReader()
void Dxf::httpReader (void * adxf, class Http * http) static
Downloads.
Definition at line 74 of file dxf.cpp.
References dxffile, error(), DXF_file::fp, getUrl(), loaded, newDXF(), Cache::openCache(), PATH_LEN, readDXF(), and Cache::setCacheName().
Referenced by Dxf().
render()
void Dxf::render () virtual
Renders.
Definition at line 213 of file dxf.cpp.
References currentScale, and dlist.
Referenced by Model::render().
setColor()
void Dxf::setColor (int type, float * color) virtual
Sets the color.
Definition at line 132 of file dxf.cpp.
References color, flgcolor, mat_ambient, mat_diffuse, and mat_specular.
setScale()
void Dxf::setScale (float scale) virtual
Sets the scale.
Definition at line 99 of file dxf.cpp.
References currentScale, desiredScale, and loaded.
Referenced by draw(), and Model::scaler().
Member Data Documentation
currentScale
float Dxf::currentScale private
current scale
Definition at line 367 of file dxf.hpp.
Referenced by draw(), render(), and setScale().
desiredScale
float Dxf::desiredScale private
desired scale
Definition at line 368 of file dxf.hpp.
Referenced by draw(), and setScale().
dlist
GLint Dxf::dlist private
display list
Definition at line 369 of file dxf.hpp.
Referenced by displaylist(), and render().
dxffile
DXF_file* Dxf::dxffile
Definition at line 363 of file dxf.hpp.
Referenced by displaylist(), draw(), httpReader(), and ~Dxf().
flgcolor
bool Dxf::flgcolor private
flag color setted
Definition at line 371 of file dxf.hpp.
Referenced by draw(), Dxf(), and setColor().
loaded
bool Dxf::loaded private
flag loaded or not
Definition at line 366 of file dxf.hpp.
Referenced by draw(), httpReader(), and setScale().
mat_ambient
float Dxf::mat_ambient[4] private
Definition at line 373 of file dxf.hpp.
Referenced by draw(), Dxf(), and setColor().
mat_diffuse
float Dxf::mat_diffuse[4] private
Definition at line 372 of file dxf.hpp.
Referenced by draw(), Dxf(), and setColor().
mat_specular
float Dxf::mat_specular[4] private
Definition at line 374 of file dxf.hpp.
Referenced by draw(), Dxf(), and setColor().
texture
int Dxf::texture private
Definition at line 375 of file dxf.hpp.
url
char* Dxf::url private
dxf url
Definition at line 370 of file dxf.hpp.
Referenced by Dxf(), getUrl(), and ~Dxf().
The documentation for this class was generated from the following files:
src/model/dxf.hpp
src/model/dxf.cpp