VREng: rigid Class Reference
rigid Class Reference
Hold rigid body data, use objloader to load obj's.
#include <bvh.hpp>
Public Member Functions
rigid (const char *url)
virtual ~rigid ()
void draw ()
Virtual generic draw member, calls makeList.
void drawDim (vector< light * > lights)
Adjust light intensity per-vertex.
void makeList ()
Does nothing currently, put scripted movements here.
void getBoundingBox ()
Virtual member that finds the extrema of all the vertices.
Public Member Functions inherited from movable
movable ()
movable (string name)
virtual ~movable ()
void init ()
movable & operator= (const movable &other)
void update ()
void move (int pitch, int turn, int roll, float x, float y, float z)
void setName (string name)
void getAABB ()
void drawAABB ()
void drawBoundingBox ()
Static Public Member Functions
static void httpReader (void *_rigid, class Http *http)
Public Attributes
int counter
For scripted movements, unused currently.
char * url
Public Attributes inherited from movable
float mass
physical constants
matrix9f Ibody
moment of inertia tensor
matrix9f IbodyInv
inverse of moi tensor
matrix16f location
state variable
matrix16f newLocation
string name
momentum
bool drawBB
bool BBcollided
vector3f centerBB
vector3f edgesBB
vector3f boundingBox [8]
vector3f oldCenterAABB
vector3f centerAABB
vector3f edgesAABB
vector3f AABB [8]
Private Member Functions
virtual void download (const char *url)
virtual const char * getUrl () const
Private Attributes
objloader * theObj
temp
std::vector< vector3f > vertices
All surface vertices, independent of triangles they are part of.
std::vector< vector3f > normals
Normals for each vertice, same index should be corresponding vertice index.
std::vector< material * > mtls
The mtls hold material lighting information as well as indices of vertices in triangles.
vector3f centerOfMass
Set by findCenterOfMass in objloader.
int listNum
Which opengl call list, unsupported currently.
bool drawSurface
Toggles drawing of the surface triangles.
bool translucent
This is likely obsolete and should be gotten rid of.
Detailed Description
Hold rigid body data, use objloader to load obj's.
I thought this would be more memory efficient, to have specialized classes for loading and holding rigid body data.
Definition at line 455 of file bvh.hpp.
Constructor & Destructor Documentation
rigid()
rigid::rigid (const char * url)
Definition at line 361 of file bvh.cpp.
References error(), Cache::getCacheName(), and Cache::getFilePath().
~rigid()
virtual rigid::~rigid () inline virtual
Definition at line 458 of file bvh.hpp.
Member Function Documentation
download()
void rigid::download (const char * url) private virtual
Definition at line 383 of file bvh.cpp.
References Http::httpOpen().
draw()
void rigid::draw ()
Virtual generic draw member, calls makeList.
drawDim()
void rigid::drawDim (vector< light * > lights)
Adjust light intensity per-vertex.
getBoundingBox()
void rigid::getBoundingBox () virtual
Virtual member that finds the extrema of all the vertices.
Reimplemented from movable.
Definition at line 546 of file bvh.cpp.
References error(), and vertices.
getUrl()
const char * rigid::getUrl () const private virtual
Definition at line 391 of file bvh.cpp.
Referenced by httpReader().
httpReader()
void rigid::httpReader (void * _rigid, class Http * http) static
Definition at line 397 of file bvh.cpp.
References File::closeFile(), getUrl(), and Cache::openCache().
makeList()
void rigid::makeList ()
Does nothing currently, put scripted movements here.
Currently not using display lists, this just draws each triangle
Definition at line 519 of file bvh.cpp.
References error(), faces, normals, and vertices.
Member Data Documentation
centerOfMass
vector3f rigid::centerOfMass private
Set by findCenterOfMass in objloader.
Definition at line 488 of file bvh.hpp.
counter
int rigid::counter
For scripted movements, unused currently.
Definition at line 471 of file bvh.hpp.
drawSurface
bool rigid::drawSurface private
Toggles drawing of the surface triangles.
Definition at line 492 of file bvh.hpp.
listNum
int rigid::listNum private
Which opengl call list, unsupported currently.
Definition at line 490 of file bvh.hpp.
mtls
std::vector<material*> rigid::mtls private
The mtls hold material lighting information as well as indices of vertices in triangles.
Definition at line 486 of file bvh.hpp.
normals
std::vector<vector3f> rigid::normals private
Normals for each vertice, same index should be corresponding vertice index.
Definition at line 484 of file bvh.hpp.
theObj
objloader* rigid::theObj private
temp
Definition at line 479 of file bvh.hpp.
translucent
bool rigid::translucent private
This is likely obsolete and should be gotten rid of.
Definition at line 494 of file bvh.hpp.
url
char* rigid::url
Definition at line 473 of file bvh.hpp.
vertices
std::vector<vector3f> rigid::vertices private
All surface vertices, independent of triangles they are part of.
Definition at line 482 of file bvh.hpp.
The documentation for this class was generated from the following files:
src/model/bvh.hpp
src/model/bvh.cpp