VREng: matrix9f Class Reference
matrix9f Class Reference
Smaller matrix for storing orientation but no location information.
#include <bvh.hpp>
Public Member Functions
matrix9f ()
void reset ()
void identity ()
void RotateX (int deg)
void RotateY (int deg)
void RotateZ (int deg)
matrix9f & operator= (const matrix9f &m1)
matrix9f transpose ()
matrix9f inverse ()
Public Attributes
float matrix [9]
Friends
matrix9f Star (vector3f a)
matrix9f operator+ (const matrix9f &m1, const matrix9f &m2)
matrix16f operator+ (const matrix16f &m1, const matrix9f &m2)
matrix9f operator- (const matrix9f &m1, const matrix9f &m2)
matrix9f operator* (const matrix9f &m1, const float scalar)
matrix9f operator* (const matrix9f &m1, const matrix9f &m2)
vector3f operator* (const matrix9f &m1, const vector3f &v2)
matrix9f operator* (const matrix9f &m1, const matrix16f &m2)
matrix9f operator* (const matrix16f &m1, const matrix9f &m2)
matrix9f operator/ (const matrix9f &m1, const float scalar)
bool operator== (const matrix9f &m1, const matrix9f &m2)
Detailed Description
Smaller matrix for storing orientation but no location information.
The contents are puhttp://sdldoc.csn.ul.ie/sdlkey.phpblic for now.
Definition at line 102 of file bvh.hpp.
Constructor & Destructor Documentation
matrix9f()
matrix9f::matrix9f () inline
Definition at line 106 of file bvh.hpp.
Member Function Documentation
identity()
void matrix9f::identity ()
Definition at line 1399 of file bvh.cpp.
Referenced by RotateX(), RotateY(), and RotateZ().
inverse()
matrix9f matrix9f::inverse ()
Definition at line 1374 of file bvh.cpp.
References det(), matrix, and transpose().
operator=()
matrix9f & matrix9f::operator= (const matrix9f & m1)
Definition at line 1472 of file bvh.cpp.
References matrix.
reset()
void matrix9f::reset ()
Definition at line 1369 of file bvh.cpp.
RotateX()
void matrix9f::RotateX (int deg)
Definition at line 1432 of file bvh.cpp.
References DEG2RAD, identity(), and matrix.
RotateY()
void matrix9f::RotateY (int deg)
Definition at line 1447 of file bvh.cpp.
References DEG2RAD, identity(), and matrix.
RotateZ()
void matrix9f::RotateZ (int deg)
Definition at line 1462 of file bvh.cpp.
References DEG2RAD, identity(), and matrix.
transpose()
matrix9f matrix9f::transpose ()
Definition at line 1406 of file bvh.cpp.
References matrix.
Referenced by inverse().
Friends And Related Function Documentation
operator* [1/5]
matrix9f operator* (const matrix16f & m1, const matrix9f & m2) friend
Definition at line 1577 of file bvh.cpp.
operator* [2/5]
matrix9f operator* (const matrix9f & m1, const float scalar) friend
Definition at line 1518 of file bvh.cpp.
operator* [3/5]
matrix9f operator* (const matrix9f & m1, const matrix16f & m2) friend
Definition at line 1557 of file bvh.cpp.
operator* [4/5]
matrix9f operator* (const matrix9f & m1, const matrix9f & m2) friend
Definition at line 1537 of file bvh.cpp.
operator* [5/5]
vector3f operator* (const matrix9f & m1, const vector3f & v2) friend
Definition at line 1527 of file bvh.cpp.
operator+ [1/2]
matrix16f operator+ (const matrix16f & m1, const matrix9f & m2) friend
Definition at line 1488 of file bvh.cpp.
operator+ [2/2]
matrix9f operator+ (const matrix9f & m1, const matrix9f & m2) friend
Definition at line 1479 of file bvh.cpp.
operator-
matrix9f operator- (const matrix9f & m1, const matrix9f & m2) friend
Definition at line 1509 of file bvh.cpp.
operator/
matrix9f operator/ (const matrix9f & m1, const float scalar) friend
Definition at line 1597 of file bvh.cpp.
operator==
bool operator== (const matrix9f & m1, const matrix9f & m2) friend
Definition at line 1606 of file bvh.cpp.
Star
matrix9f Star (vector3f a) friend
Definition at line 1416 of file bvh.cpp.
Member Data Documentation
matrix
float matrix9f::matrix[9]
Definition at line 104 of file bvh.hpp.
Referenced by inverse(), operator*(), operator+(), operator-(), operator/(), operator=(), operator==(), RotateX(), RotateY(), RotateZ(), Star(), and transpose().
The documentation for this class was generated from the following files:
src/model/bvh.hpp
src/model/bvh.cpp