VREng: Face Class Reference
Face Class Reference
Face class.
#include <face.hpp>
Public Member Functions
Face ()
Constructor.
Face (const char *urlindex)
Constructor.
virtual ~Face ()
Destructor.
virtual void render ()
Render the face.
virtual void animate ()
virtual void animate (int fapn, int value)
Animate the face.
virtual void change ()
Change the face.
virtual void load (const char *url)
Load the face.
virtual void animEyeBall (float angle, const char *_side, int dir)
virtual void animEyeLid (float angle, const char *root1, const char *root2, const char *left, const char *right)
virtual void animEyeBrow (float angle, const char *_root, const char *_side)
virtual void animLip (float angle, const char *_side)
virtual void animNose (float angle, const char *_side)
virtual void animHead (float angle, int x, int y, int z)
Protected Attributes
BoneList< char > urlList
list of faces url
int currentUrl
current url
GLint textureId
texture id
bool index
flag if url index
bool moveYes
flag move yes
bool moveNo
flag move no
bool moveMouth
flag move mouth
bool moveSmile
flag move smile
bool moveSulk
flag move sulk
bool moveEyeL
flag move left eye
bool moveEyeR
flag move right eye
bool moveNose
flag love nose
char cachefile [64]
file path in cache
BoneMesh * mesh
mesh
BoneVertex * root
bone root
BoneAnimator animator
animator
Static Protected Attributes
static const float SCALE = 0.075
3/400
Private Member Functions
virtual void defaults ()
Sets default values.
Static Private Member Functions
static void httpReader (void *_url, Http *http)
Caching file.
static void facesHttpReader (void *_o, Http *http)
Download list of faces url.
static void changeMoveYes (class Android *o, void *d, time_t s, time_t u)
static void changeMoveNo (class Android *o, void *d, time_t s, time_t u)
static void changeMoveMouth (class Android *o, void *d, time_t s, time_t u)
static void changeMoveSmile (class Android *o, void *d, time_t s, time_t u)
static void changeMoveSulk (class Android *o, void *d, time_t s, time_t u)
static void changeMoveEyeR (class Android *o, void *d, time_t s, time_t u)
static void changeMoveEyeL (class Android *o, void *d, time_t s, time_t u)
static void changeMoveNose (class Android *o, void *d, time_t s, time_t u)
static void changeFace (class Android *o, void *d, time_t s, time_t u)
Friends
class Body
SCALE.
class Android
actions
Detailed Description
Face class.
Definition at line 42 of file face.hpp.
Constructor & Destructor Documentation
Face() [1/2]
Face::Face ()
Constructor.
Definition at line 88 of file face.cpp.
References defaults(), and index.
Face() [2/2]
Face::Face (const char * urlindex)
Constructor.
Definition at line 94 of file face.cpp.
References BoneList< BoneElem >::count(), currentUrl, defaults(), BoneList< BoneElem >::empty(), facesHttpReader(), Http::httpOpen(), index, and urlList.
~Face()
Face::~Face () virtual
Destructor.
Definition at line 103 of file face.cpp.
References mesh, and root.
Member Function Documentation
animate() [1/2]
void Face::animate () virtual
Definition at line 542 of file face.cpp.
References browRightL, browRightRoot, eyeLeftBotL, eyeLeftBotR, eyeLeftBotRoot, eyeLeftRoot, eyeLeftTopL, eyeLeftTopR, eyeLeftTopRoot, eyeRightBotL, eyeRightBotR, eyeRightBotRoot, eyeRightRoot, eyeRightTopL, eyeRightTopR, eyeRightTopRoot, BoneVertex::findChild(), headRoot, lipsBotL, lipsBotR, lipsRoot, lipsTopL, lipsTopR, moveEyeL, moveEyeR, moveMouth, moveNo, moveNose, moveSmile, moveSulk, moveYes, noseLeft, noseRight, noseRoot, BoneVertex::resetCurrentPosition(), root, BoneVertex::scaleCurrentPosition(), BoneVertex::setCurrentRotation(), and BoneVertex::translateCurrentPosition().
Referenced by Android::changePermanent().
animate() [2/2]
void Face::animate (int fapn, int value) virtual
Animate the face.
Definition at line 330 of file face.cpp.
References animEyeBrow(), animEyeLid(), animHead(), animLip(), animNose(), BEND_NOSE, browLeftRoot, browRightL, browRightR, browRightRoot, CLOSE_B_L_EYELID, CLOSE_B_R_EYELID, CLOSE_T_L_EYELID, CLOSE_T_R_EYELID, DBG_MAN, DEPRESS_CHIN, DILATE_L_PUPIL, DILATE_R_PUPIL, error(), EXPRESSION, eyeLeftBotL, eyeLeftBotR, eyeLeftBotRoot, eyeLeftRoot, eyeLeftTopL, eyeLeftTopR, eyeLeftTopRoot, eyeRightBotL, eyeRightBotR, eyeRightBotRoot, eyeRightRoot, eyeRightTopL, eyeRightTopR, eyeRightTopRoot, HEAD_PITCH, HEAD_ROLL, HEAD_YAW, LIFT_L_CHEEK, LIFT_R_CHEEK, lipsBotL, lipsBotR, lipsTopL, lipsTopR, LOWER_T_LIP_LM, LOWER_T_LIP_LM_O, LOWER_T_LIP_RM, LOWER_T_LIP_RM_O, LOWER_T_MIDLIP, LOWER_T_MIDLIP_O, noseLeft, noseRight, OPEN_JAW, PITCH_L_EYEBALL, PITCH_R_EYEBALL, PUFF_L_CHEEK, PUFF_R_CHEEK, PULL_L_EAR, PULL_R_EAR, PUSH_B_LIP, PUSH_T_LIP, RAISE_B_LIP_LM, RAISE_B_LIP_LM_O, RAISE_B_LIP_RM, RAISE_B_LIP_RM_O, RAISE_B_MIDLIP, RAISE_B_MIDLIP_O, RAISE_L_CORNERLIP, RAISE_L_CORNERLIP_O, RAISE_L_EAR, RAISE_L_I_EYEBROW, RAISE_L_M_EYEBROW, RAISE_L_O_EYEBROW, RAISE_NOSE, RAISE_R_CORNERLIP, RAISE_R_CORNERLIP_O, RAISE_R_EAR, RAISE_R_I_EYEBROW, RAISE_R_M_EYEBROW, RAISE_R_O_EYEBROW, RAISE_TONGUE, RAISE_TONGUE_TIP, SHIFT_JAW, SHIFT_TONGUE_TIP, SQUEEZE_L_EYEBROW, SQUEEZE_R_EYEBROW, STRETCH_L_CORNERLIP, STRETCH_L_CORNERLIP_O, STRETCH_L_NOSE, STRETCH_R_CORNERLIP, STRETCH_R_CORNERLIP_O, STRETCH_R_NOSE, THRUST_JAW, THRUST_L_EYEBALL, THRUST_R_EYEBALL, THRUST_TONGUE_TIP, TONGUE_ROLL, trace(), VISEME, YAW_L_EYEBALL, and YAW_R_EYEBALL.
animEyeBall()
void Face::animEyeBall (float angle, const char * _side, int dir) virtual
Definition at line 238 of file face.cpp.
References DBG_MAN, BoneVertex::findChild(), BoneVertex::resetCurrentPosition(), root, BoneVertex::scaleCurrentPosition(), BoneVertex::setCurrentRotation(), trace(), and warning().
animEyeBrow()
void Face::animEyeBrow (float angle, const char * _root, const char * _side) virtual
Definition at line 290 of file face.cpp.
References DBG_MAN, BoneVertex::findChild(), BoneVertex::resetCurrentPosition(), root, BoneVertex::setCurrentRotation(), trace(), BoneVertex::translateCurrentPosition(), and warning().
Referenced by animate().
animEyeLid()
void Face::animEyeLid (float angle, const char * root1, const char * root2, const char * left, const char * right) virtual
Definition at line 257 of file face.cpp.
References DBG_MAN, eyeLeftTopRoot, eyeRightTopRoot, BoneVertex::findChild(), BoneVertex::resetCurrentPosition(), root, BoneVertex::scaleCurrentPosition(), BoneVertex::setCurrentRotation(), trace(), and warning().
Referenced by animate().
animHead()
void Face::animHead (float angle, int x, int y, int z) virtual
Definition at line 208 of file face.cpp.
References DBG_MAN, BoneVertex::findChild(), headRoot, root, BoneVertex::setCurrentRotation(), trace(), and warning().
Referenced by animate().
animLip()
void Face::animLip (float angle, const char * _side) virtual
Definition at line 311 of file face.cpp.
References DBG_MAN, BoneVertex::findChild(), lipsRoot, BoneVertex::resetCurrentPosition(), root, BoneVertex::setCurrentRotation(), trace(), BoneVertex::translateCurrentPosition(), and warning().
Referenced by animate().
animNose()
void Face::animNose (float angle, const char * _side) virtual
Definition at line 222 of file face.cpp.
References DBG_MAN, BoneVertex::findChild(), noseRoot, BoneVertex::resetCurrentPosition(), root, BoneVertex::scaleCurrentPosition(), trace(), and warning().
Referenced by animate().
change()
void Face::change () virtual
Change the face.
Definition at line 152 of file face.cpp.
References BoneList< BoneElem >::count(), currentUrl, DBG_MAN, error(), BoneList< BoneElem >::getElemAt(), index, load(), trace(), and urlList.
Referenced by changeFace(), and render().
changeFace()
void Face::changeFace (class Android * o, void * d, time_t s, time_t u) static private
Definition at line 770 of file face.cpp.
References Android::body, change(), and Body::face.
Referenced by Android::funcs().
changeMoveEyeL()
void Face::changeMoveEyeL (class Android * o, void * d, time_t s, time_t u) static private
Definition at line 758 of file face.cpp.
References Android::body, Body::face, and moveEyeL.
Referenced by Android::funcs().
changeMoveEyeR()
void Face::changeMoveEyeR (class Android * o, void * d, time_t s, time_t u) static private
Definition at line 752 of file face.cpp.
References Android::body, Body::face, and moveEyeR.
changeMoveMouth()
void Face::changeMoveMouth (class Android * o, void * d, time_t s, time_t u) static private
Definition at line 734 of file face.cpp.
References Android::body, Body::face, and moveMouth.
Referenced by Android::funcs().
changeMoveNo()
void Face::changeMoveNo (class Android * o, void * d, time_t s, time_t u) static private
Definition at line 728 of file face.cpp.
References Android::body, Body::face, and moveNo.
Referenced by Android::funcs().
changeMoveNose()
void Face::changeMoveNose (class Android * o, void * d, time_t s, time_t u) static private
Definition at line 764 of file face.cpp.
References Android::body, Body::face, and moveNose.
changeMoveSmile()
void Face::changeMoveSmile (class Android * o, void * d, time_t s, time_t u) static private
Definition at line 740 of file face.cpp.
References Android::body, Body::face, and moveSmile.
changeMoveSulk()
void Face::changeMoveSulk (class Android * o, void * d, time_t s, time_t u) static private
Definition at line 746 of file face.cpp.
References Android::body, Body::face, and moveSulk.
changeMoveYes()
void Face::changeMoveYes (class Android * o, void * d, time_t s, time_t u) static private
Definition at line 722 of file face.cpp.
References Android::body, Body::face, and moveYes.
Referenced by Android::funcs().
defaults()
void Face::defaults () private virtual
Sets default values.
Definition at line 111 of file face.cpp.
References mesh, moveEyeL, moveEyeR, moveMouth, moveNo, moveNose, moveSmile, moveSulk, moveYes, and root.
Referenced by Face().
facesHttpReader()
void Face::facesHttpReader (void * _o, Http * http) static private
Download list of faces url.
Definition at line 136 of file face.cpp.
References BoneList< BoneElem >::addElement(), DBG_MAN, error(), Http::getLine(), Http::reset(), trace(), URL_LEN, and urlList.
Referenced by Face().
httpReader()
void Face::httpReader (void * _url, Http * http) static private
Caching file.
Definition at line 126 of file face.cpp.
References File::closeFile(), error(), and Cache::openCache().
Referenced by load().
load()
void Face::load (const char * url) virtual
Load the face.
Definition at line 168 of file face.cpp.
References animator, cachefile, error(), BoneAnimator::generateLinkList(), Http::httpOpen(), httpReader(), mesh, V3d::readV3Dfile(), BoneAnimator::registerMesh(), BoneAnimator::registerSkeleton(), root, and Cache::setCacheName().
Referenced by change(), and Android::inits().
render()
void Face::render () virtual
Render the face.
Definition at line 191 of file face.cpp.
References BoneAnimator::animate(), animator, change(), mesh, BoneAnimator::meshToMove, BoneAnimator::render(), and BoneAnimator::skeleton.
Referenced by Body::display().
Friends And Related Function Documentation
Android
friend class Android friend
actions
Definition at line 44 of file face.hpp.
Body
friend class Body friend
SCALE.
Definition at line 43 of file face.hpp.
Member Data Documentation
animator
BoneAnimator Face::animator protected
animator
Definition at line 66 of file face.hpp.
Referenced by load(), and render().
cachefile
char Face::cachefile[64] protected
file path in cache
Definition at line 62 of file face.hpp.
Referenced by load().
currentUrl
int Face::currentUrl protected
current url
Definition at line 51 of file face.hpp.
Referenced by change(), and Face().
index
bool Face::index protected
flag if url index
Definition at line 53 of file face.hpp.
Referenced by change(), and Face().
mesh
BoneMesh* Face::mesh protected
mesh
Definition at line 64 of file face.hpp.
Referenced by defaults(), load(), render(), and ~Face().
moveEyeL
bool Face::moveEyeL protected
flag move left eye
Definition at line 59 of file face.hpp.
Referenced by animate(), changeMoveEyeL(), and defaults().
moveEyeR
bool Face::moveEyeR protected
flag move right eye
Definition at line 60 of file face.hpp.
Referenced by animate(), changeMoveEyeR(), and defaults().
moveMouth
bool Face::moveMouth protected
flag move mouth
Definition at line 56 of file face.hpp.
Referenced by animate(), changeMoveMouth(), and defaults().
moveNo
bool Face::moveNo protected
flag move no
Definition at line 55 of file face.hpp.
Referenced by animate(), changeMoveNo(), and defaults().
moveNose
bool Face::moveNose protected
flag love nose
Definition at line 61 of file face.hpp.
Referenced by animate(), changeMoveNose(), and defaults().
moveSmile
bool Face::moveSmile protected
flag move smile
Definition at line 57 of file face.hpp.
Referenced by animate(), changeMoveSmile(), and defaults().
moveSulk
bool Face::moveSulk protected
flag move sulk
Definition at line 58 of file face.hpp.
Referenced by animate(), changeMoveSulk(), and defaults().
moveYes
bool Face::moveYes protected
flag move yes
Definition at line 54 of file face.hpp.
Referenced by animate(), changeMoveYes(), and defaults().
root
BoneVertex* Face::root protected
bone root
Definition at line 65 of file face.hpp.
Referenced by animate(), animEyeBall(), animEyeBrow(), animEyeLid(), animHead(), animLip(), animNose(), defaults(), load(), and ~Face().
SCALE
const float Face::SCALE = 0.075 static protected
3/400
Definition at line 47 of file face.hpp.
Referenced by Body::display().
textureId
GLint Face::textureId protected
texture id
Definition at line 52 of file face.hpp.
urlList
BoneList< char > Face::urlList protected
list of faces url
Definition at line 49 of file face.hpp.
Referenced by change(), Face(), and facesHttpReader().
The documentation for this class was generated from the following files:
src/model/face.hpp
src/model/face.cpp