VREng: Off Class Reference
Off Class Reference
Off class.
#include <off.hpp>
Public Member Functions
Off (float _scale)
constructor
Off (const char *url)
constructor
virtual ~Off ()
destructor
virtual GLint displaylist ()
Draws model Off into display list.
virtual void draw ()
Draws model Off.
virtual void setScale (float _scale)
Sets scale.
virtual void render (float *color)
virtual void render (const Pos &pos, float *color)
renders model Off
Static Public Member Functions
static void httpReader (void *aoff, class Http *http)
Off reader.
Private Member Functions
virtual const char * getUrl () const
void defaults ()
Static Private Member Functions
static void getOff3i (char *s, int *a, int *b, int *c)
static void getOff3f (char *s, float *a, float *b, float *c, float scale)
Private Attributes
int vn
Vertice number.
int nn
Normal number.
int pn
Polygon number.
float * v
Vertices.
float * n
Normals.
int * p
Polygons.
float scale
Scale.
GLint dlist
displaylist
char * url
url .off
Detailed Description
Off class.
Definition at line 29 of file off.hpp.
Constructor & Destructor Documentation
Off() [1/2]
Off::Off (float _scale)
constructor
Definition at line 38 of file off.cpp.
References defaults().
Off() [2/2]
Off::Off (const char * url)
constructor
Definition at line 43 of file off.cpp.
References defaults(), Http::httpOpen(), httpReader(), and url.
~Off()
Off::~Off () virtual
destructor
Definition at line 51 of file off.cpp.
References dlist, n, p, url, and v.
Member Function Documentation
defaults()
void Off::defaults () private
Definition at line 29 of file off.cpp.
References dlist, n, nn, p, pn, url, v, and vn.
Referenced by Off().
displaylist()
GLint Off::displaylist () virtual
Draws model Off into display list.
Definition at line 130 of file off.cpp.
References dlist, and draw().
Referenced by Model::drawer().
draw()
void Off::draw () virtual
Draws model Off.
Definition at line 139 of file off.cpp.
References n, p, pn, and v.
Referenced by displaylist(), and Body::draw().
getOff3f()
void Off::getOff3f (char * s, float * a, float * b, float * c, float scale) static private
Definition at line 206 of file off.cpp.
References scale.
Referenced by httpReader().
getOff3i()
void Off::getOff3i (char * s, int * a, int * b, int * c) static private
Definition at line 189 of file off.cpp.
Referenced by httpReader().
getUrl()
const char * Off::getUrl () const private virtual
Definition at line 75 of file off.cpp.
References url.
Referenced by httpReader().
httpReader()
void Off::httpReader (void * aoff, class Http * http) static
Off reader.
Off Reader - static.
Definition at line 81 of file off.cpp.
References File::closeFile(), getOff3f(), getOff3i(), getUrl(), n, nn, Cache::openCache(), p, pn, scale, v, and vn.
Referenced by Body::loadBodyParts(), and Off().
render() [1/2]
void Off::render (const Pos & pos, float * color) virtual
renders model Off
Definition at line 173 of file off.cpp.
References Pos::ax, Pos::az, color, dlist, RAD2DEG, Pos::x, Pos::y, and Pos::z.
render() [2/2]
void Off::render (float * color) virtual
Definition at line 160 of file off.cpp.
References color, and dlist.
Referenced by Model::render().
setScale()
void Off::setScale (float _scale) virtual
Sets scale.
Definition at line 60 of file off.cpp.
References n, nn, scale, v, and vn.
Referenced by Model::scaler().
Member Data Documentation
dlist
GLint Off::dlist private
displaylist
Definition at line 60 of file off.hpp.
Referenced by defaults(), displaylist(), render(), and ~Off().
n
float* Off::n private
Normals.
Definition at line 57 of file off.hpp.
Referenced by defaults(), draw(), httpReader(), setScale(), and ~Off().
nn
int Off::nn private
Normal number.
Definition at line 54 of file off.hpp.
Referenced by defaults(), httpReader(), and setScale().
p
int* Off::p private
Polygons.
Definition at line 58 of file off.hpp.
Referenced by defaults(), draw(), httpReader(), and ~Off().
pn
int Off::pn private
Polygon number.
Definition at line 55 of file off.hpp.
Referenced by defaults(), draw(), and httpReader().
scale
float Off::scale private
Scale.
Definition at line 59 of file off.hpp.
Referenced by getOff3f(), httpReader(), and setScale().
url
char* Off::url private
url .off
Definition at line 61 of file off.hpp.
Referenced by defaults(), getUrl(), Off(), and ~Off().
v
float* Off::v private
Vertices.
Definition at line 56 of file off.hpp.
Referenced by defaults(), draw(), httpReader(), setScale(), and ~Off().
vn
int Off::vn private
Vertice number.
Definition at line 53 of file off.hpp.
Referenced by defaults(), httpReader(), and setScale().
The documentation for this class was generated from the following files:
src/model/off.hpp
src/model/off.cpp