VREng: V3d Class Reference
V3d Class Reference
V3d class.
#include <v3d.hpp>
Public Member Functions
V3d ()
constructor
virtual ~V3d ()
destructor
Static Public Member Functions
static void readV3Dfile (BoneMesh *result, BoneVertex *skeletonRoot, char *filename, float size=1.)
Detailed Description
V3d class.
Definition at line 41 of file v3d.hpp.
Constructor & Destructor Documentation
V3d()
V3d::V3d () inline
constructor
Definition at line 44 of file v3d.hpp.
~V3d()
virtual V3d::~V3d () inline virtual
destructor
Definition at line 45 of file v3d.hpp.
Member Function Documentation
readV3Dfile()
void V3d::readV3Dfile (BoneMesh * result, BoneVertex * skeletonRoot, char * filename, float size = 1.) static
Definition at line 36 of file v3d.cpp.
References BoneMesh::addTriangle(), BoneMesh::addVertex(), File::closeFile(), DBG_MAN, g, BoneList< BoneElem >::getElemAt(), File::openFile(), readFloat(), BoneVertex::readFromFile(), readInt(), readString(), BoneMesh::rebuildNormals(), Triangle::setColor(), Bonename::setName(), trace(), BoneMesh::triangleList, Triangle::u1, Triangle::u2, Triangle::u3, Triangle::v1, Triangle::v2, Triangle::v3, and vertices.
Referenced by Face::load().
The documentation for this class was generated from the following files:
src/model/v3d.hpp
src/model/v3d.cpp