VREng: Lwo Class Reference
Lwo Class Reference
Lwo class.
#include <lwo.hpp>
Public Member Functions
Lwo (const char *url)
constructor.
virtual ~Lwo ()
destructor.
virtual void displaylist ()
virtual void render ()
virtual void render (const struct Pos &pos)
virtual float getRadius ()
virtual void setScale (float scale)
Private Member Functions
virtual void readSrfs (FILE *f, int nbytes)
virtual void readSurf (FILE *f, int nbytes)
virtual void readPols (FILE *f, int nbytes)
virtual void readPnts (FILE *f, int nbytes)
Static Private Member Functions
static void httpReader (void *_lwo, class Http *http)
Private Attributes
float * vertex
tFace * face
tMaterial * material
int vertex_count
int nbf
int nbm
GLint dlist
display list.
Detailed Description
Lwo class.
Definition at line 60 of file lwo.hpp.
Constructor & Destructor Documentation
Lwo()
Lwo::Lwo (const char * url)
constructor.
Definition at line 240 of file lwo.cpp.
References dlist, face, Http::httpOpen(), httpReader(), lwourl, nbf, nbm, vertex, and vertex_count.
~Lwo()
Lwo::~Lwo () virtual
destructor.
Definition at line 255 of file lwo.cpp.
References dlist, face, tFace::index, material, nbf, tFace::next, and vertex.
Member Function Documentation
displaylist()
void Lwo::displaylist () virtual
Definition at line 291 of file lwo.cpp.
References color, dlist, face, tFace::index, tFace::index_count, tFace::material, nbf, PX, PY, PZ, and vertex.
Referenced by Model::drawer().
getRadius()
float Lwo::getRadius () virtual
Definition at line 392 of file lwo.cpp.
References vertex, and vertex_count.
Referenced by Model::scaler().
httpReader()
void Lwo::httpReader (void * _lwo, class Http * http) static private
Definition at line 209 of file lwo.cpp.
References File::closeFile(), error(), ID_FORM, ID_LWOB, ID_PNTS, ID_POLS, ID_SRFS, ID_SURF, lwourl, Cache::openCache(), File::read_long(), readPnts(), readPols(), readSrfs(), readSurf(), and File::skip_byte().
Referenced by Lwo().
readPnts()
void Lwo::readPnts (FILE * f, int nbytes) private virtual
Definition at line 197 of file lwo.cpp.
References error(), File::read_float(), vertex, and vertex_count.
Referenced by httpReader().
readPols()
void Lwo::readPols (FILE * f, int nbytes) private virtual
Definition at line 121 of file lwo.cpp.
References error(), face, tFace::index, tFace::index_count, tFace::material, nbf, tFace::next, File::read_short(), and File::skip_byte().
Referenced by httpReader().
readSrfs()
void Lwo::readSrfs (FILE * f, int nbytes) private virtual
Definition at line 37 of file lwo.cpp.
References tMaterial::b, error(), tMaterial::g, LW_MAX_NAME_LEN, tMaterial::name, nbm, tMaterial::next, tMaterial::r, and File::read_string().
Referenced by httpReader().
readSurf()
void Lwo::readSurf (FILE * f, int nbytes) private virtual
Definition at line 80 of file lwo.cpp.
References tMaterial::a, tMaterial::b, tMaterial::g, ID_COLR, LW_MAX_NAME_LEN, tMaterial::name, nbm, tMaterial::next, tMaterial::r, File::read_char(), File::read_long(), File::read_short(), File::read_string(), and File::skip_byte().
Referenced by httpReader().
render() [1/2]
void Lwo::render () virtual
Definition at line 369 of file lwo.cpp.
References dlist.
Referenced by Model::render().
render() [2/2]
virtual void Lwo::render (const struct Pos & pos) virtual
setScale()
void Lwo::setScale (float scale) virtual
Definition at line 404 of file lwo.cpp.
References vertex, and vertex_count.
Referenced by Model::scaler().
Member Data Documentation
dlist
GLint Lwo::dlist private
display list.
Definition at line 69 of file lwo.hpp.
Referenced by displaylist(), Lwo(), render(), and ~Lwo().
face
tFace* Lwo::face private
Definition at line 64 of file lwo.hpp.
Referenced by displaylist(), Lwo(), readPols(), and ~Lwo().
material
tMaterial* Lwo::material private
Definition at line 65 of file lwo.hpp.
Referenced by ~Lwo().
nbf
int Lwo::nbf private
Definition at line 67 of file lwo.hpp.
Referenced by displaylist(), Lwo(), readPols(), and ~Lwo().
nbm
int Lwo::nbm private
Definition at line 68 of file lwo.hpp.
Referenced by Lwo(), readSrfs(), and readSurf().
vertex
float* Lwo::vertex private
Definition at line 63 of file lwo.hpp.
Referenced by displaylist(), getRadius(), Lwo(), readPnts(), setScale(), and ~Lwo().
vertex_count
int Lwo::vertex_count private
Definition at line 66 of file lwo.hpp.
Referenced by getRadius(), Lwo(), readPnts(), and setScale().
The documentation for this class was generated from the following files:
src/model/lwo.hpp
src/model/lwo.cpp