VREng: Man Class Reference
Man Class Reference
Man model.
#include <man.hpp>
Public Member Functions
Man (float width, float depth, float height)
constructor
virtual ~Man ()
destructor
virtual void draw ()
virtual void draw (float width, float depth, float height)
Public Attributes
Pos pos
position and BB
Static Private Member Functions
static void myMaterial (GLenum mode, float *f, float alpha)
static void setMaterial (int i)
Private Attributes
float width
float depth
float height
Detailed Description
Man model.
Definition at line 29 of file man.hpp.
Constructor & Destructor Documentation
Man()
Man::Man (float width, float depth, float height)
constructor
Definition at line 2906 of file man.cpp.
References WObject::copyPosAndBB(), depth, height, localuser, pos, and width.
~Man()
Man::~Man () virtual
destructor
Definition at line 2914 of file man.cpp.
Member Function Documentation
draw() [1/2]
void Man::draw () virtual
Definition at line 2940 of file man.cpp.
References depth, height, and width.
Referenced by Solid::solidParser().
draw() [2/2]
void Man::draw (float width, float depth, float height) virtual
Definition at line 2945 of file man.cpp.
References bodypart, faces, normals, tBody::part_count, setMaterial(), texcoords, and vertices.
myMaterial()
void Man::myMaterial (GLenum mode, float * f, float alpha) static private
Definition at line 2917 of file man.cpp.
References alpha, and rgb.
Referenced by setMaterial().
setMaterial()
void Man::setMaterial (int i) static private
Definition at line 2928 of file man.cpp.
References alpha, tMaterial::alpha, materials, and myMaterial().
Referenced by draw().
Member Data Documentation
depth
float Man::depth private
Definition at line 44 of file man.hpp.
Referenced by draw(), and Man().
height
float Man::height private
Definition at line 45 of file man.hpp.
Referenced by draw(), and Man().
pos
Pos Man::pos
position and BB
Definition at line 32 of file man.hpp.
Referenced by User::changePosition(), Solid::displayList(), and Man().
width
float Man::width private
Definition at line 43 of file man.hpp.
Referenced by draw(), and Man().
The documentation for this class was generated from the following files:
src/model/man.hpp
src/model/man.cpp