VREng: VectorTools Class Reference
VectorTools Class Reference
VectorTools class.
#include <x3d.hpp>
Static Public Member Functions
static bool parseFloats (const std::string str, float *outputs, uint32_t number)
returns true if succeeded, false else
static bool parseFloats (const std::string str, std::vector< float > *output)
static bool parseCertifiedVectors (const std::string str, std::vector< std::vector< float > > *outputs, uint32_t vectorLength=0, uint32_t numVector=0)
static bool parseVectors (const std::string str, std::vector< std::vector< float > > *outputs)
extracts vectors of floats, spearated by commas.
static void displayVector (std::vector< std::vector< float > > *outputs)
static void displayVector (std::vector< float > *outputs)
Detailed Description
VectorTools class.
Definition at line 70 of file x3d.hpp.
Member Function Documentation
displayVector() [1/2]
void VectorTools::displayVector (std::vector< float > * outputs) static
Definition at line 917 of file x3d.cpp.
displayVector() [2/2]
void VectorTools::displayVector (std::vector< std::vector< float > > * outputs) static
Definition at line 909 of file x3d.cpp.
Referenced by X3d::drawMesh(), and Interpolator::initArrays().
parseCertifiedVectors()
bool VectorTools::parseCertifiedVectors (const std::string str, std::vector< std::vector< float > > * outputs, uint32_t vectorLength = 0, uint32_t numVector = 0) static
Definition at line 824 of file x3d.cpp.
References error(), and parseVectors().
Referenced by X3d::browseX3dTree(), Interpolator::initArrays(), and parseFloats().
parseFloats() [1/2]
bool VectorTools::parseFloats (const std::string str, float * outputs, uint32_t number) static
returns true if succeeded, false else
Definition at line 790 of file x3d.cpp.
References parseCertifiedVectors().
Referenced by X3d::browseX3dTree(), Interpolator::initArrays(), and TimeSensor::initSensor().
parseFloats() [2/2]
bool VectorTools::parseFloats (const std::string str, std::vector< float > * output) static
Definition at line 808 of file x3d.cpp.
References parseCertifiedVectors().
parseVectors()
bool VectorTools::parseVectors (const std::string str, std::vector< std::vector< float > > * outputs) static
extracts vectors of floats, spearated by commas.
Detects only errors due to non-digit characters
Definition at line 845 of file x3d.cpp.
References error().
Referenced by X3d::browseX3dTree(), and parseCertifiedVectors().
The documentation for this class was generated from the following files:
src/model/x3d.hpp
src/model/x3d.cpp