VREng: Md2 Class Reference
Md2 Class Reference
Md2 class.
#include <md2.hpp>
Public Member Functions
Md2 (const char *url)
Constructor.
virtual ~Md2 ()
Destructor.
virtual int32_t displaylist (int frame, int texture)
Get display-lists from Md2 model.
virtual void setScale (float scale)
Sets scale of model.
virtual float getRadius ()
Gets radius of model.
virtual void render (struct Pos &pos)
Renders the model.
virtual void render (struct Pos &pos, uint16_t frame)
Renders one frame of the model.
Static Public Member Functions
static void httpReader (void *_md2, class Http *http)
Md2 http reader.
Public Attributes
int32_t numframes
number of frames
int32_t skinwidth
skin width
int32_t skinheight
skin height
Private Member Functions
virtual void defaults ()
Sets default values.
virtual bool loadFromHttp (Http *http)
Loads from http.
virtual bool loadFromFile (FILE *f)
Loads from file.
virtual const char * getUrl () const
get an Url
virtual int32_t getFrames (tMd2Header *md2_hdr, FILE *f)
virtual int32_t getFrames (tMd2Header *md2_hdr, class Http *http)
Get frames from Md2 model.
virtual int32_t getGLCmds (tMd2Header *md2_hdr, FILE *f)
we keep only the commands and the index in the glcommands we 'pre-parse' the texture coordinates do not ask me how I found this formula :-))
virtual int32_t getGLCmds (tMd2Header *md2_hdr, class Http *http)
Get GL commands from Md2 model.
virtual void updBbox (float x, float y, float z)
Updates BB.
virtual void draw (int32_t frame, int32_t nextfrm, float ratio, float scale)
Draw frames of Md2 Model.
virtual int32_t displaylist (int frame, int nextfrm, float inter, float scale, int texture)
Get display-lists from Md2 model.
Private Attributes
int32_t * glcmds
GL commands.
tMd2TexInfo * texinfo
texture infos
tMd2Frame * frames
frames
tBoundingBox bbox
bounding box
bool loaded
flag loaded or not
GLint * dlists
diplay list for frames
float desiredScale
scale
char * url
md2 url
Detailed Description
Md2 class.
Definition at line 129 of file md2.hpp.
Constructor & Destructor Documentation
Md2()
Md2::Md2 (const char * url)
Constructor.
Definition at line 35 of file md2.cpp.
References defaults(), Http::httpOpen(), httpReader(), and url.
~Md2()
Md2::~Md2 () virtual
Destructor.
Definition at line 43 of file md2.cpp.
References dlists, frames, glcmds, numframes, texinfo, and url.
Member Function Documentation
defaults()
void Md2::defaults () private virtual
Sets default values.
Definition at line 57 of file md2.cpp.
References desiredScale, dlists, frames, glcmds, loaded, numframes, skinheight, skinwidth, texinfo, and url.
Referenced by Md2().
displaylist() [1/2]
int32_t Md2::displaylist (int frame, int nextfrm, float inter, float scale, int texture) private virtual
Get display-lists from Md2 model.
Definition at line 455 of file md2.cpp.
References dlists, draw(), loaded, and texture.
displaylist() [2/2]
int32_t Md2::displaylist (int frame, int texture) virtual
Get display-lists from Md2 model.
Definition at line 450 of file md2.cpp.
References desiredScale, and texture.
Referenced by Model::drawer(), and Solid::statueParser().
draw()
void Md2::draw (int32_t frame, int32_t nextfrm, float ratio, float scale) private virtual
Draw frames of Md2 Model.
Definition at line 386 of file md2.cpp.
References error(), frames, glcmds, numframes, ratio, texinfo, updBbox(), tMd2Frame::vert_table, Draw::vertex3f(), tMd2Vertex::x, tMd2Vec3::x, tMd2Vertex::y, tMd2Vec3::y, tMd2Vertex::z, and tMd2Vec3::z.
Referenced by displaylist().
getFrames() [1/2]
int32_t Md2::getFrames (tMd2Header * md2_hdr, class Http * http) private virtual
Get frames from Md2 model.
Definition at line 227 of file md2.cpp.
References dlists, frames, Trivertex::normal, tMd2Header::num_xyz, numframes, Http::read_buf(), Http::read_char(), Http::read_float(), tMd2Frame::vert_table, tMd2Vertex::x, tMd2Vec3::x, Trivertex::x, tMd2Vertex::y, tMd2Vec3::y, Trivertex::y, tMd2Vertex::z, tMd2Vec3::z, and Trivertex::z.
getFrames() [2/2]
int32_t Md2::getFrames (tMd2Header * md2_hdr, FILE * f) private virtual
Definition at line 186 of file md2.cpp.
References dlists, frames, Trivertex::normal, tMd2Header::num_xyz, numframes, File::read_buf(), File::read_char(), File::read_float_le(), tMd2Frame::vert_table, tMd2Vertex::x, tMd2Vec3::x, Trivertex::x, tMd2Vertex::y, tMd2Vec3::y, Trivertex::y, tMd2Vertex::z, tMd2Vec3::z, and Trivertex::z.
Referenced by loadFromFile(), and loadFromHttp().
getGLCmds() [1/2]
int32_t Md2::getGLCmds (tMd2Header * md2_hdr, class Http * http) private virtual
Get GL commands from Md2 model.
Definition at line 316 of file md2.cpp.
References DBG_VGL, glcmds, tMd2Header::num_glcmds, tMd2Header::num_tris, Http::read_float(), Http::read_int(), tMd2TexInfo::s, tMd2TexInfo::t, texinfo, and trace().
getGLCmds() [2/2]
int32_t Md2::getGLCmds (tMd2Header * md2_hdr, FILE * f) private virtual
we keep only the commands and the index in the glcommands we 'pre-parse' the texture coordinates do not ask me how I found this formula :-))
Definition at line 273 of file md2.cpp.
References DBG_VGL, glcmds, tMd2Header::num_glcmds, tMd2Header::num_tris, File::read_float_le(), File::read_long_le(), tMd2TexInfo::s, tMd2TexInfo::t, texinfo, and trace().
Referenced by loadFromFile(), and loadFromHttp().
getRadius()
float Md2::getRadius () virtual
Gets radius of model.
Definition at line 369 of file md2.cpp.
References bbox, tBoundingBox::xmax, tBoundingBox::xmin, tBoundingBox::ymax, tBoundingBox::ymin, tBoundingBox::zmax, and tBoundingBox::zmin.
Referenced by Model::scaler().
getUrl()
const char * Md2::getUrl () const private virtual
get an Url
Definition at line 71 of file md2.cpp.
References url.
Referenced by httpReader().
httpReader()
void Md2::httpReader (void * _md2, class Http * http) static
Md2 http reader.
Md2 model http-reader.
Definition at line 77 of file md2.cpp.
References getUrl(), loadFromFile(), and Cache::openCache().
Referenced by Md2().
loadFromFile()
bool Md2::loadFromFile (FILE * f) private virtual
Loads from file.
Md2 model file-reader.
Definition at line 87 of file md2.cpp.
References tMd2Header::framesize, getFrames(), getGLCmds(), tMd2Header::ident, loaded, tMd2Header::num_frames, tMd2Header::num_glcmds, tMd2Header::num_skins, tMd2Header::num_st, tMd2Header::num_tris, tMd2Header::num_xyz, numframes, tMd2Header::ofs_end, tMd2Header::ofs_frames, tMd2Header::ofs_glcmds, tMd2Header::ofs_skins, tMd2Header::ofs_st, tMd2Header::ofs_tris, File::read_buf(), File::read_long_le(), tMd2Header::skinheight, skinheight, tMd2Header::skinwidth, skinwidth, File::skip_byte(), and tMd2Header::version.
Referenced by httpReader().
loadFromHttp()
bool Md2::loadFromHttp (Http * http) private virtual
Loads from http.
Md2 model http-reader.
Definition at line 138 of file md2.cpp.
References tMd2Header::framesize, getFrames(), getGLCmds(), tMd2Header::ident, loaded, tMd2Header::num_frames, tMd2Header::num_glcmds, tMd2Header::num_skins, tMd2Header::num_st, tMd2Header::num_tris, tMd2Header::num_xyz, numframes, tMd2Header::ofs_end, tMd2Header::ofs_frames, tMd2Header::ofs_glcmds, tMd2Header::ofs_skins, tMd2Header::ofs_st, tMd2Header::ofs_tris, Http::read_buf(), Http::read_int(), tMd2Header::skinheight, skinheight, tMd2Header::skinwidth, skinwidth, Http::skip(), and tMd2Header::version.
render() [1/2]
void Md2::render (struct Pos & pos) virtual
Renders the model.
Definition at line 473 of file md2.cpp.
Referenced by Model::render().
render() [2/2]
void Md2::render (struct Pos & pos, uint16_t frame) virtual
Renders one frame of the model.
Definition at line 478 of file md2.cpp.
References Pos::ax, Pos::ay, Pos::az, Pos::bbsize, dlists, V3::v, Pos::x, Pos::y, and Pos::z.
setScale()
void Md2::setScale (float scale) virtual
Sets scale of model.
Definition at line 381 of file md2.cpp.
References desiredScale.
Referenced by Model::scaler(), and Solid::statueParser().
updBbox()
void Md2::updBbox (float x, float y, float z) private virtual
Updates BB.
Definition at line 359 of file md2.cpp.
References bbox, tBoundingBox::xmax, tBoundingBox::xmin, tBoundingBox::ymax, tBoundingBox::ymin, tBoundingBox::zmax, and tBoundingBox::zmin.
Referenced by draw().
Member Data Documentation
bbox
tBoundingBox Md2::bbox private
bounding box
Definition at line 135 of file md2.hpp.
Referenced by getRadius(), and updBbox().
desiredScale
float Md2::desiredScale private
scale
Definition at line 138 of file md2.hpp.
Referenced by defaults(), displaylist(), and setScale().
dlists
GLint* Md2::dlists private
diplay list for frames
Definition at line 137 of file md2.hpp.
Referenced by defaults(), displaylist(), getFrames(), render(), and ~Md2().
frames
tMd2Frame* Md2::frames private
frames
Definition at line 134 of file md2.hpp.
Referenced by defaults(), draw(), getFrames(), and ~Md2().
glcmds
int32_t* Md2::glcmds private
GL commands.
Definition at line 132 of file md2.hpp.
Referenced by defaults(), draw(), getGLCmds(), and ~Md2().
loaded
bool Md2::loaded private
flag loaded or not
Definition at line 136 of file md2.hpp.
Referenced by defaults(), displaylist(), loadFromFile(), and loadFromHttp().
numframes
int32_t Md2::numframes
number of frames
Definition at line 142 of file md2.hpp.
Referenced by defaults(), draw(), getFrames(), loadFromFile(), loadFromHttp(), and ~Md2().
skinheight
int32_t Md2::skinheight
skin height
Definition at line 144 of file md2.hpp.
Referenced by defaults(), loadFromFile(), and loadFromHttp().
skinwidth
int32_t Md2::skinwidth
skin width
Definition at line 143 of file md2.hpp.
Referenced by defaults(), loadFromFile(), and loadFromHttp().
texinfo
tMd2TexInfo* Md2::texinfo private
texture infos
Definition at line 133 of file md2.hpp.
Referenced by defaults(), draw(), getGLCmds(), and ~Md2().
url
char* Md2::url private
md2 url
Definition at line 139 of file md2.hpp.
Referenced by defaults(), getUrl(), Md2(), and ~Md2().
The documentation for this class was generated from the following files:
src/model/md2.hpp
src/model/md2.cpp