VREng: Obj Class Reference
Obj Class Reference
Class Obj Model.
#include <obj.hpp>
Public Member Functions
Obj (const char *url, int flgpart)
Constructor.
virtual ~Obj ()
Destructor.
virtual void setScale (float scale)
Sets the scale.
virtual void setColor (int type, float *color)
Sets the color.
virtual float getRadius ()
Gets the radius.
virtual void bindTexture2D (int textureId)
Binds texture number.
virtual GLint displaylist ()
Draws in displaylist.
virtual void draw ()
Model drawing.
virtual void render (float *color)
virtual void render (const Pos &pos, float *color)
Model rendering.
Static Public Member Functions
static void httpReader (void *aobj, class Http *http)
Private Member Functions
virtual bool importModel (tOBJModel *pModel)
Just pass in your model that will hold the information.
virtual bool importTextures ()
virtual int loadTexture (const char *imgFile)
virtual void readFile (tOBJModel *pModel)
This is the main loading loop that gets called in importModel()
virtual void readVertexInfo ()
This is called in ReadObjFile() if we find a line starting with 'v'.
virtual void readFaceInfo ()
This is called in ReadObjFile() if we find a line starting with 'f'.
virtual void fillInObjectInfo (tOBJModel *pModel)
This is called when we are finished loading in the face information.
virtual void computeNormals (tOBJModel *pModel)
it's nice to have vertex normals for lighting
virtual bool loadFromFile (FILE *f)
File loader.
virtual const char * getUrl () const
get an Url
Private Attributes
tOBJModel OBJModel
model
bool loaded
flag loaded or not
float currentScale
current scale
float desiredScale
desired scale
int viewMode
We want the default drawing mode to be normal.
GLint dlist
displaylist
char * url
obj url
FILE * fp
file pointer to load the .obj file
int flgpart
flag display parts else body
bool flgcolor
flag color setted
float mat_diffuse [4]
float mat_ambient [4]
float mat_specular [4]
int textures [MAX_TEXTURES]
vector< Vec3 > pVertices
This is an STL vector that holds a list of vertices.
vector< tOBJFace > pFaces
This is an STL vector that holds a list of faces.
vector< Vec2 > pTextureCoords
This is an STL vector that holds a list of UV Coordinates.
bool bObjectHasUV
This tells us if the current object has texture coordinates.
bool bObjectHasNormal
This tells us if the current object has normal coordinates.
bool bJustReadAFace
This tells us if we just read in face data so we can keep track of multiple objects.
Detailed Description
Class Obj Model.
Definition at line 97 of file obj.hpp.
Constructor & Destructor Documentation
Obj()
Obj::Obj (const char * url, int flgpart)
Constructor.
Definition at line 47 of file obj.cpp.
References bJustReadAFace, bObjectHasNormal, bObjectHasUV, flgcolor, flgpart, Http::httpOpen(), httpReader(), mat_ambient, mat_diffuse, mat_specular, tOBJModel::numOfMaterials, tOBJModel::numOfObjects, OBJModel, url, and viewMode.
~Obj()
Obj::~Obj () virtual
Destructor.
Destructor: Free the faces, normals, vertices, and texture coordinates.
Definition at line 70 of file obj.cpp.
References dlist, tOBJModel::numOfObjects, OBJModel, tOBJModel::pObject, and url.
Member Function Documentation
bindTexture2D()
void Obj::bindTexture2D (int textureId) virtual
Binds texture number.
Definition at line 137 of file obj.cpp.
computeNormals()
void Obj::computeNormals (tOBJModel * pModel) private virtual
it's nice to have vertex normals for lighting
computes the normals and vertex normals of the objects
Definition at line 477 of file obj.cpp.
References AddVector(), Cross(), DivideVectorByScaler(), error(), Normalize(), tOBJObject::numOfFaces, tOBJModel::numOfObjects, tOBJObject::numOfVerts, tOBJObject::pFaces, tOBJObject::pNormals, tOBJModel::pObject, tOBJObject::pVerts, Vector(), and tOBJFace::vertIndex.
Referenced by importModel().
displaylist()
GLint Obj::displaylist () virtual
Draws in displaylist.
Definition at line 231 of file obj.cpp.
References dlist, and draw().
draw()
void Obj::draw () virtual
Model drawing.
Definition at line 240 of file obj.cpp.
References tOBJFace::coordIndex, currentScale, desiredScale, flgcolor, loaded, mat_ambient, mat_diffuse, mat_specular, tOBJObject::numOfFaces, tOBJModel::numOfObjects, tOBJObject::numOfVerts, OBJModel, tOBJObject::pFaces, tOBJObject::pNormals, tOBJModel::pObject, tOBJObject::pTexVerts, tOBJObject::pVerts, setScale(), SIDES, tOBJFace::vertIndex, viewMode, Vec3::x, Vec2::x, Vec3::y, Vec2::y, and Vec3::z.
Referenced by displaylist(), and Body::draw().
fillInObjectInfo()
void Obj::fillInObjectInfo (tOBJModel * pModel) private virtual
This is called when we are finished loading in the face information.
called after an object is read in to fill in the model structure
Definition at line 388 of file obj.cpp.
References tOBJObject::bHasTexture, bJustReadAFace, bObjectHasNormal, bObjectHasUV, tOBJFace::coordIndex, DBG_MAN, flgpart, tOBJObject::materialID, tOBJObject::numOfFaces, tOBJModel::numOfObjects, tOBJObject::numOfVerts, tOBJObject::numTexVertex, tOBJObject::pFaces, pFaces, tOBJModel::pObject, pTextureCoords, tOBJObject::pTexVerts, pVertices, tOBJObject::pVerts, SIDES, trace(), and tOBJFace::vertIndex.
Referenced by readFile().
getRadius()
float Obj::getRadius () virtual
Gets the radius.
Definition at line 145 of file obj.cpp.
References tOBJObject::numOfFaces, tOBJModel::numOfObjects, OBJModel, tOBJObject::pFaces, tOBJModel::pObject, tOBJObject::pVerts, tOBJFace::vertIndex, Vec3::x, Vec3::y, and Vec3::z.
Referenced by Model::scaler().
getUrl()
const char * Obj::getUrl () const private virtual
get an Url
Definition at line 102 of file obj.cpp.
References url.
httpReader()
void Obj::httpReader (void * aobj, class Http * http) static
Definition at line 82 of file obj.cpp.
References File::closeFile(), obj, and Cache::openCache().
Referenced by Body::loadBodyParts(), and Obj().
importModel()
bool Obj::importModel (tOBJModel * pModel) private virtual
Just pass in your model that will hold the information.
loads a .obj file into a specified model by a .obj file name
Definition at line 274 of file obj.cpp.
References computeNormals(), fp, and readFile().
Referenced by loadFromFile().
importTextures()
bool Obj::importTextures () private virtual
Definition at line 108 of file obj.cpp.
References error(), loadTexture(), tOBJModel::numOfMaterials, OBJModel, and tOBJModel::pMaterials.
Referenced by loadFromFile().
loadFromFile()
bool Obj::loadFromFile (FILE * f) private virtual
File loader.
Definition at line 93 of file obj.cpp.
References error(), fp, importModel(), importTextures(), loaded, OBJModel, and warning().
loadTexture()
int Obj::loadTexture (const char * imgFile) private virtual
Definition at line 125 of file obj.cpp.
References end, Texture::getFromCache(), and url.
Referenced by importTextures().
readFaceInfo()
void Obj::readFaceInfo () private virtual
This is called in ReadObjFile() if we find a line starting with 'f'.
reads in the face information ("f")
Definition at line 341 of file obj.cpp.
References bObjectHasNormal, bObjectHasUV, tOBJFace::coordIndex, fp, pFaces, and tOBJFace::vertIndex.
Referenced by readFile().
readFile()
void Obj::readFile (tOBJModel * pModel) private virtual
This is the main loading loop that gets called in importModel()
main loop for reading in the .obj file
Definition at line 285 of file obj.cpp.
References bJustReadAFace, fillInObjectInfo(), fp, readFaceInfo(), and readVertexInfo().
Referenced by importModel().
readVertexInfo()
void Obj::readVertexInfo () private virtual
This is called in ReadObjFile() if we find a line starting with 'v'.
reads in the vertex information ("v" vertex : "vt" UVCoord)
Definition at line 308 of file obj.cpp.
References bObjectHasNormal, bObjectHasUV, fp, pTextureCoords, pVertices, Vec3::x, Vec2::x, Vec3::y, Vec2::y, and Vec3::z.
Referenced by readFile().
render() [1/2]
void Obj::render (const Pos & pos, float * color) virtual
Model rendering.
Definition at line 210 of file obj.cpp.
References Pos::ax, Pos::az, color, currentScale, dlist, loaded, RAD2DEG, Pos::x, Pos::y, and Pos::z.
render() [2/2]
void Obj::render (float * color) virtual
Definition at line 194 of file obj.cpp.
References color, currentScale, dlist, and loaded.
Referenced by Model::render().
setColor()
void Obj::setColor (int type, float * color) virtual
Sets the color.
Definition at line 183 of file obj.cpp.
References color, flgcolor, mat_ambient, mat_diffuse, and mat_specular.
setScale()
void Obj::setScale (float scale) virtual
Sets the scale.
Definition at line 164 of file obj.cpp.
References currentScale, desiredScale, loaded, tOBJModel::numOfObjects, tOBJObject::numOfVerts, OBJModel, tOBJModel::pObject, tOBJObject::pVerts, Vec3::x, Vec3::y, and Vec3::z.
Referenced by draw(), Body::loadBodyParts(), and Model::scaler().
Member Data Documentation
bJustReadAFace
bool Obj::bJustReadAFace private
This tells us if we just read in face data so we can keep track of multiple objects.
Definition at line 161 of file obj.hpp.
Referenced by fillInObjectInfo(), Obj(), and readFile().
bObjectHasNormal
bool Obj::bObjectHasNormal private
This tells us if the current object has normal coordinates.
Definition at line 159 of file obj.hpp.
Referenced by fillInObjectInfo(), Obj(), readFaceInfo(), and readVertexInfo().
bObjectHasUV
bool Obj::bObjectHasUV private
This tells us if the current object has texture coordinates.
Definition at line 157 of file obj.hpp.
Referenced by fillInObjectInfo(), Obj(), readFaceInfo(), and readVertexInfo().
currentScale
float Obj::currentScale private
current scale
Definition at line 104 of file obj.hpp.
Referenced by draw(), render(), and setScale().
desiredScale
float Obj::desiredScale private
desired scale
Definition at line 105 of file obj.hpp.
Referenced by draw(), and setScale().
dlist
GLint Obj::dlist private
displaylist
Definition at line 107 of file obj.hpp.
Referenced by displaylist(), render(), and ~Obj().
flgcolor
bool Obj::flgcolor private
flag color setted
Definition at line 111 of file obj.hpp.
Referenced by draw(), Obj(), and setColor().
flgpart
int Obj::flgpart private
flag display parts else body
Definition at line 110 of file obj.hpp.
Referenced by fillInObjectInfo(), and Obj().
fp
FILE* Obj::fp private
file pointer to load the .obj file
Definition at line 109 of file obj.hpp.
Referenced by importModel(), loadFromFile(), readFaceInfo(), readFile(), and readVertexInfo().
loaded
bool Obj::loaded private
flag loaded or not
Definition at line 103 of file obj.hpp.
Referenced by draw(), loadFromFile(), render(), and setScale().
mat_ambient
float Obj::mat_ambient[4] private
Definition at line 113 of file obj.hpp.
Referenced by draw(), Obj(), and setColor().
mat_diffuse
float Obj::mat_diffuse[4] private
Definition at line 112 of file obj.hpp.
Referenced by draw(), Obj(), and setColor().
mat_specular
float Obj::mat_specular[4] private
Definition at line 114 of file obj.hpp.
Referenced by draw(), Obj(), and setColor().
OBJModel
tOBJModel Obj::OBJModel private
model
Definition at line 101 of file obj.hpp.
Referenced by draw(), getRadius(), importTextures(), loadFromFile(), Obj(), setScale(), and ~Obj().
pFaces
vector<tOBJFace> Obj::pFaces private
This is an STL vector that holds a list of faces.
Definition at line 151 of file obj.hpp.
Referenced by fillInObjectInfo(), and readFaceInfo().
pTextureCoords
vector<Vec2> Obj::pTextureCoords private
This is an STL vector that holds a list of UV Coordinates.
Definition at line 154 of file obj.hpp.
Referenced by fillInObjectInfo(), and readVertexInfo().
pVertices
vector<Vec3> Obj::pVertices private
This is an STL vector that holds a list of vertices.
Definition at line 148 of file obj.hpp.
Referenced by fillInObjectInfo(), and readVertexInfo().
textures
int Obj::textures[MAX_TEXTURES] private
Definition at line 115 of file obj.hpp.
url
char* Obj::url private
obj url
Definition at line 108 of file obj.hpp.
Referenced by getUrl(), loadTexture(), Obj(), and ~Obj().
viewMode
int Obj::viewMode private
We want the default drawing mode to be normal.
Definition at line 106 of file obj.hpp.
Referenced by draw(), and Obj().
The documentation for this class was generated from the following files:
src/model/obj.hpp
src/model/obj.cpp