VREng: Wav Class Reference
Wav Class Reference
Wav class.
#include <wav.hpp>
Static Public Member Functions
static void init (int toolid)
Init WAV tool.
static void start (const char *url, bool loop)
Start WAV tool.
static void stop ()
Stop WAV tool.
static void pause ()
Suspend WAV tool.
static void cont ()
Resume WAV tool.
Static Private Member Functions
static void launch (const char *tool, const char *url, bool loop)
Static Private Attributes
static int toolid = VLC_TOOL
Detailed Description
Wav class.
Definition at line 28 of file wav.hpp.
Member Function Documentation
cont()
void Wav::cont () static
Resume WAV tool.
Definition at line 94 of file wav.cpp.
References pid.
Referenced by Music::cont().
init()
void Wav::init (int toolid) static
Init WAV tool.
Definition at line 33 of file wav.cpp.
References toolid.
Referenced by Widgets::setPrefCB().
launch()
void Wav::launch (const char * tool, const char * url, bool loop) static private
Definition at line 38 of file wav.cpp.
References e_exec, e_fork, error(), pid, QUICKTIME_TOOL, toolid, and VLC_TOOL.
Referenced by start().
pause()
void Wav::pause () static
Suspend WAV tool.
Definition at line 89 of file wav.cpp.
References pid.
Referenced by Music::pause().
start()
void Wav::start (const char * url, bool loop) static
Start WAV tool.
Definition at line 68 of file wav.cpp.
References Url::abs(), e_tool, error(), launch(), QUICKTIME_TOOL, toolid, URL_LEN, and VLC_TOOL.
Referenced by Music::play().
stop()
void Wav::stop () static
Stop WAV tool.
Definition at line 84 of file wav.cpp.
References pid.
Referenced by Music::quit(), App::quitAllTools(), and Music::stop().
Member Data Documentation
toolid
int Wav::toolid = VLC_TOOL static private
Definition at line 47 of file wav.hpp.
Referenced by init(), launch(), and start().
The documentation for this class was generated from the following files:
src/app/wav.hpp
src/app/wav.cpp