VREng: Ps Class Reference
Ps Class Reference
Ps class.
#include <ps.hpp>
Static Public Member Functions
static void init (int toolid)
Init PS viewver.
static void view (const char *url)
Start PS viewver.
static void print (const char *url)
Launch PS printer.
static void quit ()
Quit PS viewver.
Static Private Member Functions
static void launch (const char *tool, const char *file)
static void launcha2ps (const char *tool, const char *file)
Static Private Attributes
static int toolid = GV_TOOL
Detailed Description
Ps class.
Definition at line 28 of file ps.hpp.
Member Function Documentation
init()
void Ps::init (int toolid) static
Init PS viewver.
Definition at line 33 of file ps.cpp.
References toolid.
Referenced by Widgets::setPrefCB().
launch()
void Ps::launch (const char * tool, const char * file) static private
Definition at line 38 of file ps.cpp.
References e_exec, e_fork, error(), and pid.
Referenced by view().
launcha2ps()
void Ps::launcha2ps (const char * tool, const char * file) static private
Definition at line 74 of file ps.cpp.
References e_exec, e_fork, error(), and pid.
Referenced by print().
print()
void Ps::print (const char * url) static
Launch PS printer.
Definition at line 90 of file ps.cpp.
References Cache::download(), launcha2ps(), and PATH_LEN.
Referenced by Doc::print_cb().
quit()
void Ps::quit () static
Quit PS viewver.
Definition at line 98 of file ps.cpp.
References pid.
Referenced by Doc::cancel_cb(), Doc::quit(), and App::quitAllTools().
view()
void Ps::view (const char * url) static
Start PS viewver.
Definition at line 57 of file ps.cpp.
References Cache::download(), e_tool, error(), GHOSTVIEW_TOOL, GV_TOOL, launch(), PATH_LEN, and toolid.
Referenced by Icon::open(), and Doc::view_cb().
Member Data Documentation
toolid
int Ps::toolid = GV_TOOL static private
Definition at line 45 of file ps.hpp.
Referenced by init(), and view().
The documentation for this class was generated from the following files:
src/app/ps.hpp
src/app/ps.cpp