VREng: VNCClientTextured Class Reference
VNCClientTextured Class Reference
class VNCClientTextured inherits everything from VNCClient the framebuffer allocated is bigger than the real VNC server screen size and has dimensions that are a power of 2 needed by OpenGL to map the texture
#include <client.hpp>
Public Member Functions
VNCClientTextured (char *server, int port, char *pass)
bool VNCInit ()
Public Member Functions inherited from VNCClient
VNCClient (char *server, int port, char *passFile)
constructor
int getSock ()
we might want to get the socket descriptor to listen to it
bool VNCInit ()
bool VNCClose ()
< VNCInit has to allocate memory for the framebuffer if everything goes fine
void sendRFBEvent (char **params, unsigned int *num_params)
bool sendIncrementalFramebufferUpdateRequest ()
bool sendFramebufferUpdateRequest (int x, int y, int w, int h, bool incremental)
messages from client to server
bool handleRFBServerMessage ()
handle the messages from the server
Public Attributes
uint16_t realScreenWidth
uint16_t realScreenHeight
here we keep what the real server screen size is
Public Attributes inherited from VNCClient
char * serverCutText
bool newServerCutText
for now, public attributes we keep to handle server cut texts
VNCRGB * framebuffer
uint16_t fbWidth
uint16_t fbHeight
here is our framebuffer
Additional Inherited Members
Public Types inherited from VNCClient
enum { BPP8, BPP16, BPP32 }
Protected Attributes inherited from VNCClient
VNCRFBproto rfbproto
the VNCRFBproto object implements all we need to to send and receive messages specified in the RFB protocol
Detailed Description
class VNCClientTextured inherits everything from VNCClient the framebuffer allocated is bigger than the real VNC server screen size and has dimensions that are a power of 2 needed by OpenGL to map the texture
Definition at line 131 of file client.hpp.
Constructor & Destructor Documentation
VNCClientTextured()
VNCClientTextured::VNCClientTextured (char * server, int port, char * pass)
Definition at line 63 of file client.cpp.
References realScreenHeight, and realScreenWidth.
Member Function Documentation
VNCInit()
bool VNCClientTextured::VNCInit ()
Definition at line 98 of file client.cpp.
References VNCRFBproto::connectToRFBServer(), DBG_VNC, error(), VNCClient::fbHeight, VNCClient::fbWidth, VNCClient::framebuffer, rfbServerInitMsg::framebufferHeight, rfbServerInitMsg::framebufferWidth, VNCRFBproto::initialiseRFBConnection(), realScreenHeight, realScreenWidth, VNCClient::rfbproto, VNCRFBproto::setFormatAndEncodings(), VNCRFBproto::setVisual32(), VNCRFBproto::si, trace(), and VNCClient::VNCClose().
Referenced by Vnc::connectServer().
Member Data Documentation
realScreenHeight
uint16_t VNCClientTextured::realScreenHeight
here we keep what the real server screen size is
Definition at line 136 of file client.hpp.
Referenced by Vnc::connectServer(), Vnc::getVncCoords(), VNCClientTextured(), and VNCInit().
realScreenWidth
uint16_t VNCClientTextured::realScreenWidth
Definition at line 135 of file client.hpp.
Referenced by Vnc::connectServer(), Vnc::getVncCoords(), VNCClientTextured(), and VNCInit().
The documentation for this class was generated from the following files:
src/vnc/client.hpp
src/vnc/client.cpp