VREng: Wget Class Reference
Wget Class Reference
Wget class.
#include <wget.hpp>
Static Public Member Functions
static int start (const char *url, char *cachepath, const char options[]=(char *)"-qO")
Launch wget on this url.
static void unlinktmp (const char *path)
Remove file in /tmp.
Detailed Description
Wget class.
Definition at line 28 of file wget.hpp.
Member Function Documentation
start()
int Wget::start (const char * url, char * cachepath, const char options[] = (char *)"-qO") static
Launch wget on this url.
Definition at line 30 of file wget.cpp.
References Url::abs(), e_exec, e_fork, error(), my_wait(), pid, pid_t, Cache::setCacheName(), stringcmp(), and URL_LEN.
Referenced by Cache::download().
unlinktmp()
void Wget::unlinktmp (const char * path) static
Remove file in /tmp.
Definition at line 92 of file wget.cpp.
References access.
The documentation for this class was generated from the following files:
src/app/wget.hpp
src/app/wget.cpp