VREng: Wb Class Reference
Wb Class Reference
Wb class.
#include <wb.hpp>
Static Public Member Functions
static void init (int toolid)
Init white-board tool.
static void start (const char *mc)
Launch white-board tool.
static void quit ()
Quit white-board tool.
Static Private Member Functions
static void getnewchan (const char *chan, char *newchan)
Static Private Attributes
static int toolid = WB_TOOL
Detailed Description
Wb class.
Definition at line 28 of file wb.hpp.
Member Function Documentation
getnewchan()
void Wb::getnewchan (const char * chan, char * newchan) static private
Definition at line 37 of file wb.cpp.
References Channel::currentTtl(), Channel::getGroup(), Channel::getPort(), GROUP_LEN, and WHITEBOARD_INCR_PORT.
Referenced by start().
init()
void Wb::init (int toolid) static
Init white-board tool.
Definition at line 32 of file wb.cpp.
References toolid.
Referenced by Widgets::setPrefCB().
quit()
void Wb::quit () static
Quit white-board tool.
Definition at line 93 of file wb.cpp.
References pid.
Referenced by Board::cancel_cb(), Board::quit(), App::quitTools(), Widgets::setWhiteboardCB(), and Board::wb_cb().
start()
void Wb::start (const char * mc) static
Launch white-board tool.
Definition at line 47 of file wb.cpp.
References CHAN_LEN, e_exec, e_fork, error(), getnewchan(), NTE_TOOL, pid, toolid, WB_TOOL, and WBD_TOOL.
Referenced by Widgets::setWhiteboardCB(), and Board::wb_cb().
Member Data Documentation
toolid
int Wb::toolid = WB_TOOL static private
Definition at line 42 of file wb.hpp.
Referenced by init(), and start().
The documentation for this class was generated from the following files:
src/app/wb.hpp
src/app/wb.cpp