VREng: TimeSensor Class Reference
TimeSensor Class Reference
TimeSensor class Object taking care of time for interpolators.
#include <x3d.hpp>
Public Member Functions
TimeSensor ()
virtual ~TimeSensor ()
bool initSensor (XMLNode *xmlnode)
gets the attributes of the sensor
void initTarget (Interpolator *interpolator)
adds an interpolator to the targets of the time event
void updateFraction (bool animationOn)
update the time for this timer
void resetFraction ()
resets animations to the initial state
std::string getName ()
Private Attributes
struct timeval previousTime
float fraction
current percentage of the loop
float cycleIntervalMs
length of the loop (i.e speed of the animation)
bool loop
if true : animation loops
std::string name
std::vector< Interpolator * > targets
targets of the time event
Detailed Description
TimeSensor class Object taking care of time for interpolators.
Definition at line 151 of file x3d.hpp.
Constructor & Destructor Documentation
TimeSensor()
TimeSensor::TimeSensor () inline
Definition at line 163 of file x3d.hpp.
References cycleIntervalMs, fraction, gettimeofday(), loop, and previousTime.
~TimeSensor()
virtual TimeSensor::~TimeSensor () inline virtual
Definition at line 170 of file x3d.hpp.
Member Function Documentation
getName()
std::string TimeSensor::getName () inline
Definition at line 184 of file x3d.hpp.
References name.
initSensor()
bool TimeSensor::initSensor (XMLNode * xmlnode)
gets the attributes of the sensor
Definition at line 1195 of file x3d.cpp.
References cycleIntervalMs, error(), X3d::isEqual(), loop, name, and VectorTools::parseFloats().
Referenced by X3d::browseX3dTree().
initTarget()
void TimeSensor::initTarget (Interpolator * interpolator)
adds an interpolator to the targets of the time event
Definition at line 1237 of file x3d.cpp.
References targets.
Referenced by X3d::setupInterpolators().
resetFraction()
void TimeSensor::resetFraction ()
resets animations to the initial state
Definition at line 1243 of file x3d.cpp.
References fraction, and targets.
updateFraction()
void TimeSensor::updateFraction (bool animationOn)
update the time for this timer
Definition at line 1251 of file x3d.cpp.
References cycleIntervalMs, error(), fraction, gettimeofday(), loop, previousTime, and targets.
Member Data Documentation
cycleIntervalMs
float TimeSensor::cycleIntervalMs private
length of the loop (i.e speed of the animation)
Definition at line 156 of file x3d.hpp.
Referenced by initSensor(), TimeSensor(), and updateFraction().
fraction
float TimeSensor::fraction private
current percentage of the loop
Definition at line 154 of file x3d.hpp.
Referenced by resetFraction(), TimeSensor(), and updateFraction().
loop
bool TimeSensor::loop private
if true : animation loops
Definition at line 157 of file x3d.hpp.
Referenced by initSensor(), TimeSensor(), and updateFraction().
name
std::string TimeSensor::name private
Definition at line 158 of file x3d.hpp.
Referenced by getName(), and initSensor().
previousTime
struct timeval TimeSensor::previousTime private
Definition at line 123 of file x3d.hpp.
Referenced by TimeSensor(), and updateFraction().
targets
std::vector<Interpolator*> TimeSensor::targets private
targets of the time event
Definition at line 160 of file x3d.hpp.
Referenced by initTarget(), resetFraction(), and updateFraction().
The documentation for this class was generated from the following files:
src/model/x3d.hpp
src/model/x3d.cpp