VREng: Interpolator Class Reference
Interpolator Class Reference
Interpolator class.
#include <x3d.hpp>
Public Member Functions
Interpolator ()
bool initArrays (XMLNode *xmlnode)
gets the attributes of the interpolator
bool initTarget (X3dShape *targetShape, X3DINField field)
adds a target field for the animated values
virtual ~Interpolator ()
std::string getName ()
void updateValue (float newFraction)
called by the timeSensor to update the interpolated values
Private Attributes
std::string name
InterpolatorType type
what kind of field does this animate ??
std::vector< float > keys
key frames used, value in percentage of the loop
std::vector< std::vector< float > > keyValues
values coresponding to these key frames
std::vector< float * > targets
float targets (rotation, scale, shininess...)
Detailed Description
Interpolator class.
Definition at line 228 of file x3d.hpp.
Constructor & Destructor Documentation
Interpolator()
Interpolator::Interpolator () inline
Definition at line 243 of file x3d.hpp.
References INTERPOLATORTYPENONE, and type.
~Interpolator()
virtual Interpolator::~Interpolator () inline virtual
Definition at line 253 of file x3d.hpp.
Member Function Documentation
getName()
std::string Interpolator::getName () inline
Definition at line 255 of file x3d.hpp.
References name.
initArrays()
bool Interpolator::initArrays (XMLNode * xmlnode)
gets the attributes of the interpolator
Definition at line 928 of file x3d.cpp.
References COLORINTERPOLATOR, VectorTools::displayVector(), error(), X3d::isEqual(), keys, keyValues, name, VectorTools::parseCertifiedVectors(), VectorTools::parseFloats(), POSITIONINTERPOLATOR, ROTATIONINTERPOLATOR, SCALARINTERPOLATOR, SCALEINTERPOLATOR, and type.
Referenced by X3d::browseX3dTree().
initTarget()
bool Interpolator::initTarget (X3dShape * targetShape, X3DINField field)
adds a target field for the animated values
Definition at line 1008 of file x3d.cpp.
References X3dShape::ambientIntensity, AMBIENTINTENSITY, X3dShape::ambientIntensityOn, COLORINTERPOLATOR, X3dShape::diffuse, DIFFUSECOLOR, X3dShape::diffuseOn, X3dShape::emissive, EMISSIVECOLOR, X3dShape::emissiveOn, error(), POSITIONINTERPOLATOR, X3dShape::rotation, ROTATION, ROTATIONINTERPOLATOR, X3dShape::rotationOn, SCALARINTERPOLATOR, X3dShape::scale, SCALE, SCALEINTERPOLATOR, X3dShape::scaleOn, X3dShape::shininess, SHININESS, X3dShape::shininessOn, X3dShape::specular, SPECULARCOLOR, X3dShape::specularOn, targets, X3dShape::translation, TRANSLATION, X3dShape::translationOn, X3dShape::transparency, TRANSPARENCY, X3dShape::transparencyOn, and type.
Referenced by X3d::setupInterpolators().
updateValue()
void Interpolator::updateValue (float newFraction)
called by the timeSensor to update the interpolated values
Definition at line 1094 of file x3d.cpp.
References COLORINTERPOLATOR, error(), keys, keyValues, name, POSITIONINTERPOLATOR, ROTATIONINTERPOLATOR, SCALARINTERPOLATOR, SCALEINTERPOLATOR, targets, and type.
Member Data Documentation
keys
std::vector<float> Interpolator::keys private
key frames used, value in percentage of the loop
Definition at line 235 of file x3d.hpp.
Referenced by initArrays(), and updateValue().
keyValues
std::vector<std::vector<float> > Interpolator::keyValues private
values coresponding to these key frames
Definition at line 237 of file x3d.hpp.
Referenced by initArrays(), and updateValue().
name
std::string Interpolator::name private
Definition at line 231 of file x3d.hpp.
Referenced by getName(), initArrays(), and updateValue().
targets
std::vector<float*> Interpolator::targets private
float targets (rotation, scale, shininess...)
Definition at line 239 of file x3d.hpp.
Referenced by initTarget(), and updateValue().
type
InterpolatorType Interpolator::type private
what kind of field does this animate ??
Definition at line 233 of file x3d.hpp.
Referenced by initArrays(), initTarget(), Interpolator(), and updateValue().
The documentation for this class was generated from the following files:
src/model/x3d.hpp
src/model/x3d.cpp