VREng: Route Class Reference
Route Class Reference
Route class temporary structure to prepare the initialization of the sensors and interpolators.
#include <x3d.hpp>
Public Member Functions
Route ()
virtual ~Route ()
bool initRoute (XMLNode *xmlnode)
inits the attributes of the temp Route
Public Attributes
std::string fromNode
std::string toNode
X3DOUTField fromField
X3DINField toField
Detailed Description
Route class temporary structure to prepare the initialization of the sensors and interpolators.
Definition at line 267 of file x3d.hpp.
Constructor & Destructor Documentation
Route()
Route::Route () inline
Definition at line 274 of file x3d.hpp.
References fromField, NOINX3DFIELD, NOOUTX3DFIELD, and toField.
~Route()
virtual Route::~Route () inline virtual
Definition at line 279 of file x3d.hpp.
Member Function Documentation
initRoute()
bool Route::initRoute (XMLNode * xmlnode)
inits the attributes of the temp Route
Definition at line 1287 of file x3d.cpp.
References AMBIENTINTENSITY, DIFFUSECOLOR, EMISSIVECOLOR, error(), FRACTION_CHANGED, fromField, fromNode, X3d::isEqual(), NOINX3DFIELD, NOOUTX3DFIELD, ROTATION, SCALE, SET_FRACTION, SHININESS, SPECULARCOLOR, toField, toNode, TRANSLATION, TRANSPARENCY, and VALUE_CHANGED.
Referenced by X3d::browseX3dTree().
Member Data Documentation
fromField
X3DOUTField Route::fromField
Definition at line 271 of file x3d.hpp.
Referenced by initRoute(), and Route().
fromNode
std::string Route::fromNode
Definition at line 270 of file x3d.hpp.
Referenced by initRoute().
toField
X3DINField Route::toField
Definition at line 272 of file x3d.hpp.
Referenced by initRoute(), and Route().
toNode
std::string Route::toNode
Definition at line 270 of file x3d.hpp.
Referenced by initRoute().
The documentation for this class was generated from the following files:
src/model/x3d.hpp
src/model/x3d.cpp