VREng: Mpeg Class Reference
Mpeg Class Reference
Mpeg class.
#include <mpeg.hpp>
Static Public Member Functions
static void init (int toolid)
Init MPEG tool.
static void start (const char *url)
Start MPEG tool.
static void stop ()
Stop MPEG tool.
static void pause ()
Suspend MPEG tool.
static void cont ()
Resume MPEG tool.
Static Private Member Functions
static void launch (const char *tool, const char *url, char *file)
Launch MPEG tool.
Static Private Attributes
static int toolid = MTVP_TOOL
Detailed Description
Mpeg class.
Definition at line 28 of file mpeg.hpp.
Member Function Documentation
cont()
void Mpeg::cont () static
Resume MPEG tool.
Definition at line 99 of file mpeg.cpp.
References pid.
Referenced by Clip::cont().
init()
void Mpeg::init (int toolid) static
Init MPEG tool.
Definition at line 38 of file mpeg.cpp.
References toolid.
Referenced by Widgets::setPrefCB().
launch()
void Mpeg::launch (const char * tool, const char * url, char * file) static private
Launch MPEG tool.
Definition at line 43 of file mpeg.cpp.
References e_exec, e_fork, error(), MPEGPLAY_TOOL, MTVP_TOOL, pid, QUICKTIME_TOOL, toolid, and VLC_TOOL.
Referenced by start().
pause()
void Mpeg::pause () static
Suspend MPEG tool.
Definition at line 94 of file mpeg.cpp.
References pid.
Referenced by Clip::pause().
start()
void Mpeg::start (const char * url) static
Start MPEG tool.
Definition at line 68 of file mpeg.cpp.
References Url::abs(), Cache::download(), e_tool, error(), launch(), MPEGPLAY_TOOL, MTVP_TOOL, PATH_LEN, QUICKTIME_TOOL, toolid, URL_LEN, and VLC_TOOL.
Referenced by Clip::play().
stop()
void Mpeg::stop () static
Stop MPEG tool.
Definition at line 89 of file mpeg.cpp.
References pid.
Referenced by Clip::quit(), App::quitAllTools(), and Clip::stop().
Member Data Documentation
toolid
int Mpeg::toolid = MTVP_TOOL static private
Definition at line 48 of file mpeg.hpp.
Referenced by init(), launch(), and start().
The documentation for this class was generated from the following files:
src/app/mpeg.hpp
src/app/mpeg.cpp