VREng: Midi Class Reference
Midi Class Reference
Midi class.
#include <midi.hpp>
Static Public Member Functions
static void init (int toolid)
Init Midi tool.
static void start (const char *url)
Start Midi tool.
static void stop ()
Stop Midi tool.
static void pause ()
Suspend Midi tool.
static void cont ()
Resume Midi tool.
Static Private Member Functions
static void launch (const char *tool, const char *url)
Launch Midi tool.
Static Private Attributes
static int toolid = TIMIDITY_TOOL
Detailed Description
Midi class.
Definition at line 28 of file midi.hpp.
Member Function Documentation
cont()
void Midi::cont () static
Resume Midi tool.
Definition at line 86 of file midi.cpp.
References pid.
Referenced by Music::cont().
init()
void Midi::init (int toolid) static
Init Midi tool.
Definition at line 38 of file midi.cpp.
References toolid.
launch()
void Midi::launch (const char * tool, const char * url) static private
Launch Midi tool.
Definition at line 43 of file midi.cpp.
References e_exec, e_fork, error(), pid, QUICKTIME_TOOL, TIMIDITY_TOOL, and toolid.
Referenced by start().
pause()
void Midi::pause () static
Suspend Midi tool.
Definition at line 81 of file midi.cpp.
References pid.
Referenced by Music::pause().
start()
void Midi::start (const char * url) static
Start Midi tool.
Definition at line 64 of file midi.cpp.
References Url::abs(), e_tool, error(), launch(), QUICKTIME_TOOL, TIMIDITY_TOOL, toolid, and URL_LEN.
Referenced by Icon::open(), and Music::play().
stop()
void Midi::stop () static
Stop Midi tool.
Definition at line 76 of file midi.cpp.
References pid.
Referenced by Music::quit(), App::quitAllTools(), and Music::stop().
Member Data Documentation
toolid
int Midi::toolid = TIMIDITY_TOOL static private
Definition at line 48 of file midi.hpp.
Referenced by init(), launch(), and start().
The documentation for this class was generated from the following files:
src/app/midi.hpp
src/app/midi.cpp