VREng: Browser Class Reference
Browser Class Reference
Browser class.
#include <browser.hpp>
Static Public Member Functions
static void init (int toolid)
init the default browser
static void start (const char *url, bool rewrite=true)
Start the default browser.
static void quit ()
Quit the default browser.
Static Private Member Functions
static void launchmozilla (const char *browser, const char *url)
static void launchsafari (const char *browser, const char *url)
static void launchchrome (const char *browser, const char *url)
static void launchnetscape (const char *browser, const char *url)
Static Private Attributes
static int toolid = FIREFOX_TOOL
Detailed Description
Browser class.
Definition at line 28 of file browser.hpp.
Member Function Documentation
init()
void Browser::init (int toolid) static
init the default browser
Definition at line 38 of file browser.cpp.
References toolid.
Referenced by Widgets::setPrefCB().
launchchrome()
void Browser::launchchrome (const char * browser, const char * url) static private
Definition at line 91 of file browser.cpp.
References e_exec, e_fork, error(), pid, and pid_t.
Referenced by start().
launchmozilla()
void Browser::launchmozilla (const char * browser, const char * url) static private
Definition at line 43 of file browser.cpp.
References e_exec, e_fork, error(), newwindow, pid, pid_t, and URL_LEN.
Referenced by start().
launchnetscape()
void Browser::launchnetscape (const char * browser, const char * url) static private
Definition at line 112 of file browser.cpp.
References e_exec, e_fork, error(), newwindow, pid, pid_t, and URL_LEN.
Referenced by start().
launchsafari()
void Browser::launchsafari (const char * browser, const char * url) static private
Definition at line 72 of file browser.cpp.
References e_exec, e_fork, error(), pid, and pid_t.
Referenced by start().
quit()
void Browser::quit () static
Quit the default browser.
Definition at line 183 of file browser.cpp.
References pid.
Referenced by App::quitAllTools().
start()
void Browser::start (const char * url, bool rewrite = true) static
Start the default browser.
Definition at line 164 of file browser.cpp.
References Url::abs(), CHROME_TOOL, e_tool, error(), FIREFOX_TOOL, IEXPLORER_TOOL, launchchrome(), launchmozilla(), launchnetscape(), launchsafari(), MOZILLA_TOOL, NETSCAPE_TOOL, OPERA_TOOL, SAFARI_TOOL, toolid, and URL_LEN.
Referenced by Book::lookLeft_cb(), Book::lookRight_cb(), Icon::open(), and Web::open_cb().
Member Data Documentation
toolid
int Browser::toolid = FIREFOX_TOOL static private
Definition at line 42 of file browser.hpp.
Referenced by init(), and start().
The documentation for this class was generated from the following files:
src/app/browser.hpp
src/app/browser.cpp