VREng: Pdf Class Reference
Pdf Class Reference
Pdf class.
#include <pdf.hpp>
Static Public Member Functions
static void init (int toolid)
Init PDF viewver.
static void start (const char *url)
Start PDF viewver.
static void quit ()
Quit PDF viewver.
Static Private Member Functions
static void launch (const char *tool, const char *file)
Static Private Attributes
static int toolid = ACROBAT_TOOL
Detailed Description
Pdf class.
Definition at line 28 of file pdf.hpp.
Member Function Documentation
init()
void Pdf::init (int toolid) static
Init PDF viewver.
Definition at line 37 of file pdf.cpp.
References toolid.
Referenced by Widgets::setPrefCB().
launch()
void Pdf::launch (const char * tool, const char * file) static private
Definition at line 42 of file pdf.cpp.
References e_exec, e_fork, error(), and pid.
Referenced by start().
quit()
void Pdf::quit () static
Quit PDF viewver.
Definition at line 81 of file pdf.cpp.
References pid.
Referenced by App::quitAllTools().
start()
void Pdf::start (const char * url) static
Start PDF viewver.
Definition at line 63 of file pdf.cpp.
References ACROBAT_TOOL, Cache::download(), e_tool, error(), EVINCE_TOOL, launch(), PATH_LEN, toolid, and XPDF_TOOL.
Referenced by Icon::open().
Member Data Documentation
toolid
int Pdf::toolid = ACROBAT_TOOL static private
Definition at line 42 of file pdf.hpp.
Referenced by init(), and start().
The documentation for this class was generated from the following files:
src/app/pdf.hpp
src/app/pdf.cpp