VREng: Audio Class Reference
Audio Class Reference
Audio class.
#include <audio.hpp>
Static Public Member Functions
static void init (int toolid)
Init audio tool.
static void start (const char *chanstr)
Start audio tool with this channel.
static void quit ()
Quit audio tool.
Static Private Member Functions
static void getnewchan (const char *, char *)
Static Private Attributes
static int toolid = RAT_TOOL
Detailed Description
Audio class.
Definition at line 28 of file audio.hpp.
Member Function Documentation
getnewchan()
void Audio::getnewchan (const char * chan, char * newchan) static private
Definition at line 46 of file audio.cpp.
References AUDIO_INCR_PORT, Channel::currentTtl(), Channel::getGroup(), Channel::getPort(), and GROUP_LEN.
Referenced by start().
init()
void Audio::init (int toolid) static
Init audio tool.
Definition at line 41 of file audio.cpp.
References toolid.
Referenced by Widgets::setPrefCB().
quit()
void Audio::quit () static
Quit audio tool.
Definition at line 108 of file audio.cpp.
References pid.
Referenced by App::quitTools(), Widgets::setAudioCB(), and Clip::stop().
start()
void Audio::start (const char * chanstr) static
Start audio tool with this channel.
Definition at line 57 of file audio.cpp.
References CHAN_LEN, Channel::currentTtl(), e_exec, e_fork, error(), FPHONE_TOOL, g, getnewchan(), pid, Global::pref, RAT_TOOL, Pref::silent, toolid, and VAT_TOOL.
Referenced by Gate::enter(), Gui::gotoWorld(), Widgets::homeCB(), Clip::play(), and Widgets::setAudioCB().
Member Data Documentation
toolid
int Audio::toolid = RAT_TOOL static private
Definition at line 42 of file audio.hpp.
Referenced by init(), and start().
The documentation for this class was generated from the following files:
src/app/audio.hpp
src/app/audio.cpp