VREng: Video Class Reference
Video Class Reference
Video class.
#include <video.hpp>
Static Public Member Functions
static void init (int toolid)
Init video tool.
static void start (const char *mc)
Start video tool.
static void quit ()
Quit video tool.
Static Private Member Functions
static void getnewchan (const char *chan, char *newchan)
Static Private Attributes
static int toolid = VIC_TOOL
Detailed Description
Video class.
Definition at line 28 of file video.hpp.
Member Function Documentation
getnewchan()
void Video::getnewchan (const char * chan, char * newchan) static private
Definition at line 51 of file video.cpp.
References Channel::currentTtl(), Channel::getGroup(), Channel::getPort(), GROUP_LEN, and VIDEO_INCR_PORT.
Referenced by start().
init()
void Video::init (int toolid) static
Init video tool.
Definition at line 46 of file video.cpp.
References toolid.
Referenced by Widgets::setPrefCB().
quit()
void Video::quit () static
Quit video tool.
Definition at line 101 of file video.cpp.
References pid.
Referenced by App::quitTools(), Widgets::setVideoCB(), and Clip::stop().
start()
void Video::start (const char * mc) static
Start video tool.
Definition at line 62 of file video.cpp.
References CHAN_LEN, Channel::currentTtl(), e_exec, e_fork, error(), Channel::getGroup(), getnewchan(), Channel::getPort(), GROUP_LEN, pid, toolid, VIC_TOOL, VIDEO_INCR_PORT, VIDEODEVICE, and VLCMC_TOOL.
Referenced by Clip::play(), and Widgets::setVideoCB().
Member Data Documentation
toolid
int Video::toolid = VIC_TOOL static private
Definition at line 42 of file video.hpp.
Referenced by init(), and start().
The documentation for this class was generated from the following files:
src/app/video.hpp
src/app/video.cpp