VREng: Modeler Class Reference
Modeler Class Reference
Modeler class.
#include <modeler.hpp>
Static Public Member Functions
static void init (int toolid)
Init vred modeler.
static void start ()
Start vred modeler.
static void quit ()
Quit vred modeler.
Static Private Attributes
static int toolid = VRED_TOOL
Detailed Description
Modeler class.
Definition at line 28 of file modeler.hpp.
Member Function Documentation
init()
void Modeler::init (int toolid) static
Init vred modeler.
Definition at line 32 of file modeler.cpp.
References toolid.
Referenced by Widgets::setPrefCB().
quit()
void Modeler::quit () static
Quit vred modeler.
Definition at line 66 of file modeler.cpp.
References pid.
Referenced by App::quitAllTools(), and Widgets::setModelerCB().
start()
void Modeler::start () static
Start vred modeler.
Definition at line 37 of file modeler.cpp.
References e_exec, e_fork, error(), pid, toolid, VRED_TOOL, and VREM_TOOL.
Referenced by Widgets::setModelerCB().
Member Data Documentation
toolid
int Modeler::toolid = VRED_TOOL static private
Definition at line 42 of file modeler.hpp.
Referenced by init(), and start().
The documentation for this class was generated from the following files:
src/app/modeler.hpp
src/app/modeler.cpp