VREng: Au Class Reference
Au Class Reference
Au class.
#include <au.hpp>
Static Public Member Functions
static void init (int toolid)
Init AU tool.
static void start (const char *url)
Start AU tool.
static void stop ()
Stop AU tool.
static void pause ()
Suspend AU tool.
static void cont ()
Resume AU tool.
Static Private Member Functions
static void launch (const char *tool, const char *url, char *file)
Launch AU tool.
Static Private Attributes
static int toolid = PLAY_TOOL
Detailed Description
Au class.
Definition at line 28 of file au.hpp.
Member Function Documentation
cont()
void Au::cont () static
Resume AU tool.
Definition at line 89 of file au.cpp.
References pid.
Referenced by Music::cont().
init()
void Au::init (int toolid) static
Init AU tool.
Definition at line 38 of file au.cpp.
References toolid.
launch()
void Au::launch (const char * tool, const char * url, char * file) static private
Launch AU tool.
Definition at line 43 of file au.cpp.
References e_exec, e_fork, error(), pid, PLAY_TOOL, QUICKTIME_TOOL, and toolid.
Referenced by start().
pause()
void Au::pause () static
Suspend AU tool.
Definition at line 84 of file au.cpp.
References pid.
Referenced by Music::pause().
start()
void Au::start (const char * url) static
Start AU tool.
Definition at line 64 of file au.cpp.
References Url::abs(), Cache::download(), e_tool, error(), launch(), PATH_LEN, PLAY_TOOL, QUICKTIME_TOOL, toolid, and URL_LEN.
Referenced by Music::play().
stop()
void Au::stop () static
Stop AU tool.
Definition at line 79 of file au.cpp.
References pid.
Referenced by Music::quit(), and Music::stop().
Member Data Documentation
toolid
int Au::toolid = PLAY_TOOL static private
Definition at line 48 of file au.hpp.
Referenced by init(), launch(), and start().
The documentation for this class was generated from the following files:
src/app/au.hpp
src/app/au.cpp