VREng: VNCClient Class Reference
VNCClient Class Reference
class VNCClient object will be used in VReng:
#include <client.hpp>
Public Types
enum { BPP8, BPP16, BPP32 }
Public Member Functions
VNCClient (char *server, int port, char *passFile)
constructor
int getSock ()
we might want to get the socket descriptor to listen to it
bool VNCInit ()
bool VNCClose ()
< VNCInit has to allocate memory for the framebuffer if everything goes fine
void sendRFBEvent (char **params, unsigned int *num_params)
bool sendIncrementalFramebufferUpdateRequest ()
bool sendFramebufferUpdateRequest (int x, int y, int w, int h, bool incremental)
messages from client to server
bool handleRFBServerMessage ()
handle the messages from the server
Public Attributes
char * serverCutText
bool newServerCutText
for now, public attributes we keep to handle server cut texts
VNCRGB * framebuffer
uint16_t fbWidth
uint16_t fbHeight
here is our framebuffer
Protected Attributes
VNCRFBproto rfbproto
the VNCRFBproto object implements all we need to to send and receive messages specified in the RFB protocol
Private Member Functions
void fillRect (int rx, int ry, int rw, int rh, VNCRGB pixel)
handling Rectangles we got from server
uint8_t rescalePixValue (uint32_t Pix, uint8_t Shift, uint16_t Max)
VNCRGB cardToVNCRGB (uint32_t Pixel)
bool handleRAW32 (int rx, int ry, int rw, int rh)
bool handleCR (int srcx, int srcy, int rx, int ry, int rw, int rh)
bool handleRRE32 (int rx, int ry, int rw, int rh)
bool handleCoRRE32 (int rx, int ry, int rw, int rh)
bool handleHextile32 (int rx, int ry, int rw, int rh)
Private Attributes
char rfbbuffer [RFB_BUF_SIZE]
this buffer is used to get Server MSGs
bool viewonly
do we want to forward events? (no if true)
Detailed Description
class VNCClient object will be used in VReng:
to connect to the VNC server
to handle its messages
to forward pointer and keyboard events to the server framebuffer is public
Definition at line 57 of file client.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
BPP8
BPP16
BPP32
Definition at line 101 of file client.hpp.
Constructor & Destructor Documentation
VNCClient()
VNCClient::VNCClient (char * server, int port, char * passFile)
constructor
Definition at line 53 of file client.cpp.
References fbHeight, fbWidth, framebuffer, newServerCutText, serverCutText, and viewonly.
Member Function Documentation
cardToVNCRGB()
VNCRGB VNCClient::cardToVNCRGB (uint32_t Pixel) private
Definition at line 209 of file client.cpp.
References rfbPixelFormat::blueMax, rfbPixelFormat::blueShift, rfbPixelFormat::greenMax, rfbPixelFormat::greenShift, VNCRFBproto::pixFormat, rfbPixelFormat::redMax, rfbPixelFormat::redShift, rescalePixValue(), and rfbproto.
Referenced by handleCoRRE32(), handleRAW32(), and handleRRE32().
fillRect()
void VNCClient::fillRect (int rx, int ry, int rw, int rh, VNCRGB pixel) private
handling Rectangles we got from server
Definition at line 259 of file client.cpp.
References DBG_VNC, fbWidth, framebuffer, and trace().
Referenced by handleCoRRE32(), handleHextile32(), and handleRRE32().
getSock()
int VNCClient::getSock ()
we might want to get the socket descriptor to listen to it
Definition at line 592 of file client.cpp.
References VNCRFBproto::getSock(), and rfbproto.
Referenced by Vnc::changePermanent(), and VNCClose().
handleCoRRE32()
bool VNCClient::handleCoRRE32 (int rx, int ry, int rw, int rh) private
Definition at line 310 of file client.cpp.
References cardToVNCRGB(), DBG_VNC, fillRect(), VNCSockets::ReadFromRFBServer(), rfbbuffer, rfbproto, swap32IfLE, sz_rfbRREHeader, trace(), and VNCRFBproto::VNC_sock.
Referenced by handleRFBServerMessage().
handleCR()
bool VNCClient::handleCR (int srcx, int srcy, int rx, int ry, int rw, int rh) private
Definition at line 234 of file client.cpp.
References fbWidth, framebuffer, and src.
Referenced by handleRFBServerMessage().
handleHextile32()
bool VNCClient::handleHextile32 (int rx, int ry, int rw, int rh) private
Definition at line 355 of file client.cpp.
References DBG_VNC, fillRect(), GET_PIXEL32, handleRAW32(), VNCSockets::ReadFromRFBServer(), rfbbuffer, rfbHextileAnySubrects, rfbHextileBackgroundSpecified, rfbHextileExtractH, rfbHextileExtractW, rfbHextileExtractX, rfbHextileExtractY, rfbHextileForegroundSpecified, rfbHextileRaw, rfbHextileSubrectsColoured, rfbproto, swap32IfLE, trace(), and VNCRFBproto::VNC_sock.
Referenced by handleRFBServerMessage().
handleRAW32()
bool VNCClient::handleRAW32 (int rx, int ry, int rw, int rh) private
Definition at line 219 of file client.cpp.
References cardToVNCRGB(), fbWidth, framebuffer, rfbbuffer, src, and swap32IfLE.
Referenced by handleHextile32(), and handleRFBServerMessage().
handleRFBServerMessage()
bool VNCClient::handleRFBServerMessage ()
handle the messages from the server
Definition at line 440 of file client.cpp.
References rfbPixelFormat::bitsPerPixel, error(), framebuffer, rfbServerInitMsg::framebufferHeight, rfbServerInitMsg::framebufferWidth, handleCoRRE32(), handleCR(), handleHextile32(), handleRAW32(), handleRRE32(), newServerCutText, VNCRFBproto::pixFormat, VNCSockets::ReadFromRFBServer(), rfbBell, rfbbuffer, rfbEncodingCopyRect, rfbEncodingCoRRE, rfbEncodingHextile, rfbEncodingRaw, rfbEncodingRRE, rfbFramebufferUpdate, rfbproto, rfbServerCutText, rfbSetColourMapEntries, rgb, sendIncrementalFramebufferUpdateRequest(), serverCutText, VNCRFBproto::si, rfbCopyRect::srcX, swap16IfLE, swap32IfLE, sz_rfbCopyRect, sz_rfbFramebufferUpdateMsg, sz_rfbFramebufferUpdateRectHeader, sz_rfbServerCutTextMsg, sz_rfbSetColourMapEntriesMsg, and VNCRFBproto::VNC_sock.
Referenced by Vnc::changePermanent().
handleRRE32()
bool VNCClient::handleRRE32 (int rx, int ry, int rw, int rh) private
Definition at line 272 of file client.cpp.
References cardToVNCRGB(), DBG_VNC, fillRect(), VNCSockets::ReadFromRFBServer(), rfbproto, swap16IfLE, swap32IfLE, sz_rfbRectangle, sz_rfbRREHeader, trace(), and VNCRFBproto::VNC_sock.
Referenced by handleRFBServerMessage().
rescalePixValue()
uint8_t VNCClient::rescalePixValue (uint32_t Pix, uint8_t Shift, uint16_t Max) private
Definition at line 203 of file client.cpp.
Referenced by cardToVNCRGB().
sendFramebufferUpdateRequest()
bool VNCClient::sendFramebufferUpdateRequest (int x, int y, int w, int h, bool incremental)
messages from client to server
Definition at line 602 of file client.cpp.
References rfbproto, and VNCRFBproto::sendFramebufferUpdateRequest().
Referenced by Vnc::connectServer().
sendIncrementalFramebufferUpdateRequest()
bool VNCClient::sendIncrementalFramebufferUpdateRequest ()
Definition at line 597 of file client.cpp.
References rfbproto, and VNCRFBproto::sendIncrementalFramebufferUpdateRequest().
Referenced by handleRFBServerMessage().
sendRFBEvent()
void VNCClient::sendRFBEvent (char ** params, unsigned int * num_params)
Definition at line 157 of file client.cpp.
References error(), framebuffer, rfbproto, VNCRFBproto::sendKeyEvent(), VNCRFBproto::sendPointerEvent(), strcasecmp(), strncasecmp(), and viewonly.
Referenced by Vnc::keyEvent(), and Vnc::mouseEvent().
VNCClose()
bool VNCClient::VNCClose ()
< VNCInit has to allocate memory for the framebuffer if everything goes fine
VNCClose has to free it
Definition at line 138 of file client.cpp.
References close, framebuffer, and getSock().
Referenced by Vnc::disconnectServer(), Vnc::quit(), VNCInit(), and VNCClientTextured::VNCInit().
VNCInit()
bool VNCClient::VNCInit ()
Definition at line 69 of file client.cpp.
References VNCRFBproto::connectToRFBServer(), error(), fbHeight, fbWidth, framebuffer, rfbServerInitMsg::framebufferHeight, rfbServerInitMsg::framebufferWidth, VNCRFBproto::initialiseRFBConnection(), rfbproto, VNCRFBproto::setFormatAndEncodings(), VNCRFBproto::setVisual32(), VNCRFBproto::si, and VNCClose().
Member Data Documentation
fbHeight
uint16_t VNCClient::fbHeight
here is our framebuffer
Definition at line 94 of file client.hpp.
Referenced by Vnc::connectServer(), VNCClient(), VNCInit(), and VNCClientTextured::VNCInit().
fbWidth
uint16_t VNCClient::fbWidth
Definition at line 93 of file client.hpp.
Referenced by Vnc::connectServer(), fillRect(), handleCR(), handleRAW32(), VNCClient(), VNCInit(), and VNCClientTextured::VNCInit().
framebuffer
VNCRGB* VNCClient::framebuffer
Definition at line 92 of file client.hpp.
Referenced by Vnc::connectServer(), fillRect(), handleCR(), handleRAW32(), handleRFBServerMessage(), sendRFBEvent(), VNCClient(), VNCClose(), VNCInit(), and VNCClientTextured::VNCInit().
newServerCutText
bool VNCClient::newServerCutText
for now, public attributes we keep to handle server cut texts
Definition at line 89 of file client.hpp.
Referenced by handleRFBServerMessage(), and VNCClient().
rfbbuffer
char VNCClient::rfbbuffer[RFB_BUF_SIZE] private
this buffer is used to get Server MSGs
Definition at line 60 of file client.hpp.
Referenced by handleCoRRE32(), handleHextile32(), handleRAW32(), and handleRFBServerMessage().
rfbproto
VNCRFBproto VNCClient::rfbproto protected
the VNCRFBproto object implements all we need to to send and receive messages specified in the RFB protocol
Definition at line 79 of file client.hpp.
Referenced by cardToVNCRGB(), getSock(), handleCoRRE32(), handleHextile32(), handleRFBServerMessage(), handleRRE32(), sendFramebufferUpdateRequest(), sendIncrementalFramebufferUpdateRequest(), sendRFBEvent(), VNCInit(), and VNCClientTextured::VNCInit().
serverCutText
char* VNCClient::serverCutText
Definition at line 88 of file client.hpp.
Referenced by handleRFBServerMessage(), and VNCClient().
viewonly
bool VNCClient::viewonly private
do we want to forward events? (no if true)
Definition at line 63 of file client.hpp.
Referenced by sendRFBEvent(), and VNCClient().
The documentation for this class was generated from the following files:
src/vnc/client.hpp
src/vnc/client.cpp