VREng: Mp3 Class Reference
Mp3 Class Reference
Mp3 class.
#include <mp3.hpp>
Static Public Member Functions
static void init (int toolid)
Init MP3 tool.
static void start (const char *url)
Start MP3 tool.
static void stop ()
Stop MP3 tool.
static void pause ()
Suspend MP3 tool.
static void cont ()
Resume MP3 tool.
Static Private Member Functions
static void launch (const char *tool, const char *url)
Launch MP3 tool.
Static Private Attributes
static int toolid = MPG123_TOOL
Detailed Description
Mp3 class.
Definition at line 28 of file mp3.hpp.
Member Function Documentation
cont()
void Mp3::cont () static
Resume MP3 tool.
Definition at line 101 of file mp3.cpp.
References pid.
Referenced by Music::cont().
init()
void Mp3::init (int toolid) static
Init MP3 tool.
Definition at line 39 of file mp3.cpp.
References toolid.
Referenced by Widgets::setPrefCB().
launch()
void Mp3::launch (const char * tool, const char * url) static private
Launch MP3 tool.
Definition at line 44 of file mp3.cpp.
References e_exec, e_fork, error(), FREEAMP_TOOL, MPG123_TOOL, pid, QUICKTIME_TOOL, toolid, VLC_TOOL, and XAUDIO_TOOL.
Referenced by start().
pause()
void Mp3::pause () static
Suspend MP3 tool.
Definition at line 96 of file mp3.cpp.
References pid.
Referenced by Music::pause().
start()
void Mp3::start (const char * url) static
Start MP3 tool.
Definition at line 70 of file mp3.cpp.
References Url::abs(), e_tool, error(), FREEAMP_TOOL, g, launch(), MPG123_TOOL, Global::pref, QUICKTIME_TOOL, Pref::silent, toolid, URL_LEN, VLC_TOOL, and XAUDIO_TOOL.
Referenced by Icon::open(), Music::play(), Sheet::turnNext(), and Sheet::turnPrev().
stop()
void Mp3::stop () static
Stop MP3 tool.
Definition at line 91 of file mp3.cpp.
References pid.
Referenced by Music::quit(), App::quitAllTools(), and Music::stop().
Member Data Documentation
toolid
int Mp3::toolid = MPG123_TOOL static private
Definition at line 47 of file mp3.hpp.
Referenced by init(), launch(), and start().
The documentation for this class was generated from the following files:
src/app/mp3.hpp
src/app/mp3.cpp