VREng: X3d Class Reference
X3d Class Reference
X3d class.
#include <x3d.hpp>
Public Member Functions
X3d (const char *url)
Constructor.
virtual ~X3d ()
Destructor.
const char * getUrl () const
void displayShape (X3dShape *mySHape)
void render ()
rendering.
void resetAnimations ()
for the "stop" button of the GUI.
void setFlashy ()
Sets flashy the X3d object.
void resetFlashy ()
Static Public Member Functions
static bool isEqual (const char *, const char *)
case insensitive equality betwen strings
Public Attributes
bool animationOn
is it animated or not at the moment ?
Private Member Functions
void defaults (const char *_url)
default values for class attributes
bool loadFromFile (char *f)
calls the functions to load the x3d tree and initialize everything
void browseX3dTree (XMLNode *xmlnode, X3dShape *shapeNode)
parses the whole xml file
void setupInterpolators ()
initializes the animations thanks to the ROUTE objects
GLuint drawPrimitive (X3dShapes Id)
draws the primitive and returns the calllist number
GLuint drawMesh (MeshInfos *meshInfos)
draws the complex shape and returns the calllist number
X3dShape * findShape (X3dShape *root, std::string name)
browses the X3d tree to find the name shape
template<class T >
T * findItem (std::vector< T > *tab, std::string name)
to find a named item in a vecto
X3dShapes isKnownPrimitive (XMLCSTR vredata)
sends back the vreng "solid" primitive corresponding to x3d
Static Private Member Functions
static void httpReader (void *x3d, class Http *http)
loader of the web file, manages the cache...
Private Attributes
char * url
X3dShape rootShape
root of the X3D tree
std::vector< Interpolator > interpolators
std::vector< TimeSensor > timeSensors
std::vector< Route > routes
temporary structures to create links
bool selected
flashy or not
Static Private Attributes
static ShapeToId knownPrimitives [KNOWNPRIMITIVESNUMBER]
array to do this
Detailed Description
X3d class.
Definition at line 289 of file x3d.hpp.
Constructor & Destructor Documentation
X3d()
X3d::X3d (const char * url)
Constructor.
Definition at line 39 of file x3d.cpp.
References defaults(), Http::httpOpen(), httpReader(), loadFromFile(), and url.
~X3d()
X3d::~X3d () virtual
Destructor.
Definition at line 47 of file x3d.cpp.
References url.
Member Function Documentation
browseX3dTree()
void X3d::browseX3dTree (XMLNode * xmlnode, X3dShape * shapeNode) private
parses the whole xml file
Definition at line 106 of file x3d.cpp.
References drawMesh(), drawPrimitive(), error(), Texture::getFromCache(), Interpolator::initArrays(), Route::initRoute(), TimeSensor::initSensor(), interpolators, isEqual(), isKnownPrimitive(), offset, VectorTools::parseCertifiedVectors(), VectorTools::parseFloats(), VectorTools::parseVectors(), routes, shape, timeSensors, and X3DNONE.
Referenced by loadFromFile().
defaults()
void X3d::defaults (const char * _url) private
default values for class attributes
Definition at line 30 of file x3d.cpp.
References animationOn, selected, and url.
Referenced by X3d().
displayShape()
void X3d::displayShape (X3dShape * mySHape)
Definition at line 579 of file x3d.cpp.
References X3dShape::ambientIntensity, X3dShape::ambientIntensityOn, X3dShape::diffuse, X3dShape::diffuseOn, X3dShape::emissive, X3dShape::emissiveOn, X3dShape::meshes, RAD2DEG, X3dShape::rotation, X3dShape::rotationOn, X3dShape::scale, X3dShape::scaleOn, selected, X3dShape::shininess, X3dShape::shininessOn, X3dShape::specular, X3dShape::specularOn, X3dShape::translation, X3dShape::translationOn, X3dShape::transparency, and X3dShape::transparencyOn.
Referenced by render().
drawMesh()
GLuint X3d::drawMesh (MeshInfos * meshInfos) private
draws the complex shape and returns the calllist number
Definition at line 447 of file x3d.cpp.
References MeshInfos::Color, MeshInfos::colorIndex, MeshInfos::colorPerVertex, MeshInfos::Coordinate, MeshInfos::coordIndex, VectorTools::displayVector(), error(), size, MeshInfos::texCoordIndex, and MeshInfos::TextureCoordinate.
Referenced by browseX3dTree().
drawPrimitive()
GLuint X3d::drawPrimitive (X3dShapes Id) private
draws the primitive and returns the calllist number
Definition at line 363 of file x3d.cpp.
References Draw::cylinder(), Draw::disk(), dlist, error(), Draw::sphere(), Draw::STYLE_FILL, X3DBOX, X3DCONE, X3DCYLINDER, and X3DSPHERE.
Referenced by browseX3dTree().
findItem()
template<class T > T * X3d::findItem (std::vector< T > * tab, std::string name) private
to find a named item in a vecto
Definition at line 356 of file x3d.cpp.
findShape()
X3dShape * X3d::findShape (X3dShape * root, std::string name) private
browses the X3d tree to find the name shape
Definition at line 343 of file x3d.cpp.
References X3dShape::childrenShapes, and X3dShape::getName().
Referenced by setupInterpolators().
getUrl()
const char * X3d::getUrl () const
Definition at line 53 of file x3d.cpp.
References url.
Referenced by httpReader().
httpReader()
void X3d::httpReader (void * x3d, class Http * http) static private
loader of the web file, manages the cache...
Definition at line 58 of file x3d.cpp.
References File::closeFile(), error(), getUrl(), Http::httpRead(), loadFromFile(), File::openFile(), PATH_LEN, and Cache::setCacheName().
Referenced by X3d().
isEqual()
bool X3d::isEqual (const char * str1, const char * str2) static
case insensitive equality betwen strings
Definition at line 747 of file x3d.cpp.
Referenced by browseX3dTree(), Interpolator::initArrays(), Route::initRoute(), TimeSensor::initSensor(), and isKnownPrimitive().
isKnownPrimitive()
X3dShapes X3d::isKnownPrimitive (XMLCSTR vredata) private
sends back the vreng "solid" primitive corresponding to x3d
Definition at line 737 of file x3d.cpp.
References ShapeToId::id, isEqual(), knownPrimitives, KNOWNPRIMITIVESNUMBER, shape, and X3DNONE.
Referenced by browseX3dTree().
loadFromFile()
bool X3d::loadFromFile (char * f) private
calls the functions to load the x3d tree and initialize everything
Definition at line 85 of file x3d.cpp.
References browseX3dTree(), interpolators, rootShape, and setupInterpolators().
Referenced by httpReader(), and X3d().
render()
void X3d::render ()
rendering.
Definition at line 646 of file x3d.cpp.
References animationOn, X3dShape::childrenShapes, X3dShape::diffuseOn, displayShape(), X3dShape::level, rootShape, X3dShape::texture, and timeSensors.
Referenced by AnimX3d::render().
resetAnimations()
void X3d::resetAnimations ()
for the "stop" button of the GUI.
Definition at line 779 of file x3d.cpp.
References timeSensors.
Referenced by AnimX3d::stop().
resetFlashy()
void X3d::resetFlashy ()
Definition at line 774 of file x3d.cpp.
References selected.
Referenced by AnimX3d::resetFlashy().
setFlashy()
void X3d::setFlashy ()
Sets flashy the X3d object.
Definition at line 769 of file x3d.cpp.
References selected.
Referenced by AnimX3d::setFlashy().
setupInterpolators()
void X3d::setupInterpolators () private
initializes the animations thanks to the ROUTE objects
Definition at line 313 of file x3d.cpp.
References error(), findShape(), FRACTION_CHANGED, TimeSensor::initTarget(), Interpolator::initTarget(), interpolators, rootShape, routes, SET_FRACTION, timeSensors, TRANSLATION, TRANSPARENCY, and VALUE_CHANGED.
Referenced by loadFromFile().
Member Data Documentation
animationOn
bool X3d::animationOn
is it animated or not at the moment ?
Definition at line 292 of file x3d.hpp.
Referenced by defaults(), AnimX3d::pause(), render(), AnimX3d::start(), and AnimX3d::stop().
interpolators
std::vector<Interpolator> X3d::interpolators private
Definition at line 315 of file x3d.hpp.
Referenced by browseX3dTree(), loadFromFile(), and setupInterpolators().
knownPrimitives
ShapeToId X3d::knownPrimitives static private
Initial value:
= {
  {"Sphere", X3DSPHERE},
  {"Cylinder", X3DCYLINDER},
  {"Cone", X3DCONE},
  {"Box", X3DBOX}
}
array to do this
Definition at line 351 of file x3d.hpp.
Referenced by isKnownPrimitive().
rootShape
X3dShape X3d::rootShape private
root of the X3D tree
Definition at line 313 of file x3d.hpp.
Referenced by loadFromFile(), render(), and setupInterpolators().
routes
std::vector<Route> X3d::routes private
temporary structures to create links
Definition at line 317 of file x3d.hpp.
Referenced by browseX3dTree(), and setupInterpolators().
selected
bool X3d::selected private
flashy or not
Definition at line 319 of file x3d.hpp.
Referenced by defaults(), displayShape(), resetFlashy(), and setFlashy().
timeSensors
std::vector<TimeSensor> X3d::timeSensors private
Definition at line 316 of file x3d.hpp.
Referenced by browseX3dTree(), render(), resetAnimations(), and setupInterpolators().
url
char* X3d::url private
Definition at line 311 of file x3d.hpp.
Referenced by defaults(), getUrl(), X3d(), and ~X3d().
The documentation for this class was generated from the following files:
src/model/x3d.hpp
src/model/x3d.cpp