VREng: Xterm Class Reference
Xterm Class Reference
Xterm class.
#include <xterm.hpp>
Static Public Member Functions
static void init (int toolid)
Init xterm.
static void start (const char *host)
Launch xterm.
static void quit ()
Quit xterm.
Static Private Attributes
static int toolid = SSH_TOOL
Detailed Description
Xterm class.
Definition at line 28 of file xterm.hpp.
Member Function Documentation
init()
void Xterm::init (int toolid) static
Init xterm.
Definition at line 31 of file xterm.cpp.
References toolid.
quit()
void Xterm::quit () static
Quit xterm.
Definition at line 55 of file xterm.cpp.
References pid.
Referenced by Host::disconnect(), Host::quit(), and App::quitTools().
start()
void Xterm::start (const char * host) static
Launch xterm.
Definition at line 36 of file xterm.cpp.
References e_exec, e_fork, error(), pid, SSH_TOOL, TELNET_TOOL, and toolid.
Referenced by Host::connect().
Member Data Documentation
toolid
int Xterm::toolid = SSH_TOOL static private
Definition at line 42 of file xterm.hpp.
Referenced by init(), and start().
The documentation for this class was generated from the following files:
src/app/xterm.hpp
src/app/xterm.cpp