VREng: VNCRFBproto Class Reference
VNCRFBproto Class Reference
#include <rfbproto.hpp>
Public Member Functions
VNCRFBproto (char *ServeurName, int Port, char *pswdFile)
constructors
void printPixelFormat (rfbPixelFormat *format)
Prints out the format for debugging.
void setVisual32 ()
default is 32 BPP
bool connectToRFBServer ()
connects to the server
bool initialiseRFBConnection ()
initialise the connection with this server
bool sendPointerEvent (int x, int y, int buttonMask)
bool sendKeyEvent (uint32_t key, bool down)
bool sendClientCutText (char *str, int len)
bool setFormatAndEncodings ()
sets the format of rfb messages and the way it will be encoded.
bool sendIncrementalFramebufferUpdateRequest ()
if incremental, updates the Framebuffer for all the screen
bool sendFramebufferUpdateRequest (int x, int y, int w, int h, bool incremental)
if not, updates only one rectangle
int getSock ()
get the used socket
Public Attributes
VNCSockets VNC_sock
rfbPixelFormat pixFormat
rfbServerInitMsg si
Private Attributes
char passwordFile [64]
Name of the file containing the encrypted password.
int buffered
size of what is stored in the buffer
bool ShareDesktop
indicates whether other connection on the server are allowed
char * desktopName
name of the distant desktop
Detailed Description
Definition at line 705 of file rfbproto.hpp.
Constructor & Destructor Documentation
VNCRFBproto()
VNCRFBproto::VNCRFBproto (char * ServeurName, int Port, char * pswdFile)
constructors
Constructors.
Definition at line 58 of file rfbproto.cpp.
References buffered, passwordFile, and ShareDesktop.
Member Function Documentation
connectToRFBServer()
bool VNCRFBproto::connectToRFBServer ()
connects to the server
ConnectToRFBServer.
Definition at line 70 of file rfbproto.cpp.
References VNCSockets::ConnectToTcpAddr(), error(), VNCSockets::SetNonBlocking(), and VNC_sock.
Referenced by VNCClient::VNCInit(), and VNCClientTextured::VNCInit().
getSock()
int VNCRFBproto::getSock ()
get the used socket
Definition at line 357 of file rfbproto.cpp.
References VNCSockets::GetSock(), and VNC_sock.
Referenced by VNCClient::getSock().
initialiseRFBConnection()
bool VNCRFBproto::initialiseRFBConnection ()
initialise the connection with this server
Definition at line 80 of file rfbproto.cpp.
References rfbPixelFormat::blueMax, CHALLENGESIZE, DBG_VNC, desktopName, error(), rfbServerInitMsg::format, rfbServerInitMsg::framebufferHeight, rfbServerInitMsg::framebufferWidth, rfbPixelFormat::greenMax, rfbServerInitMsg::nameLength, notice(), passwordFile, printPixelFormat(), VNCSockets::ReadFromRFBServer(), rfbPixelFormat::redMax, rfbConnFailed, rfbNoAuth, rfbProtocolMajorVersion, rfbProtocolMinorVersion, rfbProtocolVersionFormat, rfbVncAuth, rfbVncAuthFailed, rfbVncAuthOK, rfbVncAuthTooMany, rfbClientInitMsg::shared, ShareDesktop, si, swap16IfLE, swap32IfLE, sz_rfbClientInitMsg, sz_rfbProtocolVersionMsg, sz_rfbServerInitMsg, trace(), VNC_sock, vncDecryptPasswdFromFile(), vncEncryptBytes(), and VNCSockets::WriteExact().
Referenced by VNCClient::VNCInit(), and VNCClientTextured::VNCInit().
printPixelFormat()
void VNCRFBproto::printPixelFormat (rfbPixelFormat * format)
Prints out the format for debugging.
Definition at line 334 of file rfbproto.cpp.
References rfbPixelFormat::bigEndian, rfbPixelFormat::bitsPerPixel, rfbPixelFormat::blueMax, rfbPixelFormat::blueShift, DBG_VNC, rfbPixelFormat::greenMax, rfbPixelFormat::greenShift, rfbPixelFormat::redMax, rfbPixelFormat::redShift, trace(), and rfbPixelFormat::trueColour.
Referenced by initialiseRFBConnection().
sendClientCutText()
bool VNCRFBproto::sendClientCutText (char * str, int len)
Definition at line 298 of file rfbproto.cpp.
References rfbClientCutTextMsg::length, rfbClientCutText, serverCutText, swap32IfLE, sz_rfbClientCutTextMsg, rfbClientCutTextMsg::type, VNC_sock, and VNCSockets::WriteExact().
sendFramebufferUpdateRequest()
bool VNCRFBproto::sendFramebufferUpdateRequest (int x, int y, int w, int h, bool incremental)
if not, updates only one rectangle
Definition at line 258 of file rfbproto.cpp.
References rfbFramebufferUpdateRequestMsg::h, rfbFramebufferUpdateRequestMsg::incremental, rfbFramebufferUpdateRequest, swap16IfLE, sz_rfbFramebufferUpdateRequestMsg, rfbFramebufferUpdateRequestMsg::type, VNC_sock, rfbFramebufferUpdateRequestMsg::w, VNCSockets::WriteExact(), rfbFramebufferUpdateRequestMsg::x, and rfbFramebufferUpdateRequestMsg::y.
Referenced by VNCClient::sendFramebufferUpdateRequest(), and sendIncrementalFramebufferUpdateRequest().
sendIncrementalFramebufferUpdateRequest()
bool VNCRFBproto::sendIncrementalFramebufferUpdateRequest ()
if incremental, updates the Framebuffer for all the screen
Definition at line 252 of file rfbproto.cpp.
References rfbServerInitMsg::framebufferHeight, rfbServerInitMsg::framebufferWidth, sendFramebufferUpdateRequest(), and si.
Referenced by VNCClient::sendIncrementalFramebufferUpdateRequest().
sendKeyEvent()
bool VNCRFBproto::sendKeyEvent (uint32_t key, bool down)
Definition at line 288 of file rfbproto.cpp.
References rfbKeyEventMsg::down, rfbKeyEventMsg::key, rfbKeyEvent, swap32IfLE, sz_rfbKeyEventMsg, rfbKeyEventMsg::type, VNC_sock, and VNCSockets::WriteExact().
Referenced by VNCClient::sendRFBEvent().
sendPointerEvent()
bool VNCRFBproto::sendPointerEvent (int x, int y, int buttonMask)
Definition at line 275 of file rfbproto.cpp.
References rfbPointerEventMsg::buttonMask, rfbPointerEvent, swap16IfLE, sz_rfbPointerEventMsg, rfbPointerEventMsg::type, VNC_sock, VNCSockets::WriteExact(), rfbPointerEventMsg::x, and rfbPointerEventMsg::y.
Referenced by VNCClient::sendRFBEvent().
setFormatAndEncodings()
bool VNCRFBproto::setFormatAndEncodings ()
sets the format of rfb messages and the way it will be encoded.
Definition at line 214 of file rfbproto.cpp.
References rfbPixelFormat::blueMax, DBG_VNC, rfbSetPixelFormatMsg::format, rfbPixelFormat::greenMax, MAX_ENCODINGS, rfbSetEncodingsMsg::nEncodings, pixFormat, rfbPixelFormat::redMax, rfbEncodingCopyRect, rfbEncodingCoRRE, rfbEncodingHextile, rfbEncodingRaw, rfbEncodingRRE, rfbSetEncodings, rfbSetPixelFormat, VNCSockets::SameMachine(), swap16IfLE, swap32IfLE, sz_rfbSetEncodingsMsg, sz_rfbSetPixelFormatMsg, trace(), rfbSetPixelFormatMsg::type, rfbSetEncodingsMsg::type, VNC_sock, and VNCSockets::WriteExact().
Referenced by VNCClient::VNCInit(), and VNCClientTextured::VNCInit().
setVisual32()
void VNCRFBproto::setVisual32 ()
default is 32 BPP
initialise pixFormat qui donne le format de pixel que l'on veut que le serveur nous envoie.
initialise pour demander le RGB sur 3*8 bits = 24 bits A APPELER DANS LE CONSTRUCTEUR (mto)
Definition at line 319 of file rfbproto.cpp.
References rfbPixelFormat::bigEndian, rfbPixelFormat::bitsPerPixel, rfbPixelFormat::blueMax, rfbPixelFormat::blueShift, DBG_VNC, rfbPixelFormat::depth, rfbPixelFormat::greenMax, rfbPixelFormat::greenShift, pixFormat, rfbPixelFormat::redMax, rfbPixelFormat::redShift, trace(), and rfbPixelFormat::trueColour.
Referenced by VNCClient::VNCInit(), and VNCClientTextured::VNCInit().
Member Data Documentation
buffered
int VNCRFBproto::buffered private
size of what is stored in the buffer
Definition at line 711 of file rfbproto.hpp.
Referenced by VNCRFBproto().
desktopName
char* VNCRFBproto::desktopName private
name of the distant desktop
Definition at line 717 of file rfbproto.hpp.
Referenced by initialiseRFBConnection().
passwordFile
char VNCRFBproto::passwordFile[64] private
Name of the file containing the encrypted password.
Definition at line 708 of file rfbproto.hpp.
Referenced by initialiseRFBConnection(), and VNCRFBproto().
pixFormat
rfbPixelFormat VNCRFBproto::pixFormat
Definition at line 737 of file rfbproto.hpp.
Referenced by VNCClient::cardToVNCRGB(), VNCClient::handleRFBServerMessage(), setFormatAndEncodings(), and setVisual32().
ShareDesktop
bool VNCRFBproto::ShareDesktop private
indicates whether other connection on the server are allowed
Definition at line 714 of file rfbproto.hpp.
Referenced by initialiseRFBConnection(), and VNCRFBproto().
si
rfbServerInitMsg VNCRFBproto::si
Definition at line 739 of file rfbproto.hpp.
Referenced by VNCClient::handleRFBServerMessage(), initialiseRFBConnection(), sendIncrementalFramebufferUpdateRequest(), VNCClient::VNCInit(), and VNCClientTextured::VNCInit().
VNC_sock
VNCSockets VNCRFBproto::VNC_sock
Definition at line 722 of file rfbproto.hpp.
Referenced by connectToRFBServer(), getSock(), VNCClient::handleCoRRE32(), VNCClient::handleHextile32(), VNCClient::handleRFBServerMessage(), VNCClient::handleRRE32(), initialiseRFBConnection(), sendClientCutText(), sendFramebufferUpdateRequest(), sendKeyEvent(), sendPointerEvent(), and setFormatAndEncodings().
The documentation for this class was generated from the following files:
src/vnc/rfbproto.hpp
src/vnc/rfbproto.cpp