VREng: VNCSockets Class Reference
VNCSockets Class Reference
VNCSocket class.
#include <sockets.hpp>
Public Member Functions
VNCSockets ()
VNCSockets (const char *_servername, uint16_t _port)
VNCSockets (uint32_t IPAddr, uint16_t _port)
constructors
signed int ConnectToTcpAddr ()
Connects to the given TCP port.
bool SameMachine ()
Test if the other end of a socket is on the same machine.
bool SetNonBlocking ()
sets a socket into non-blocking mode.
bool ReadFromRFBServer (char *out, uint32_t n)
Read bytes from the sever and stores it in the buffer.
bool WriteExact (char *buf, int n)
Write an exact number of bytes, and don't return until you've sent them.
int GetSock ()
get the socket used
Private Member Functions
bool StringToIPAddr ()
stores the IP address of the server in ipaddr, returns false if unknown
Private Attributes
char ServerName [MAXHOSTNAMELEN]
name of the server
uint16_t port
port
uint32_t ipaddr
IP address of the server.
int rfbsock
the used socket
uint32_t buffered
uint8_t buf [VNC_BUF_SIZE]
uint8_t * bufoutptr
buffer
Detailed Description
VNCSocket class.
Definition at line 29 of file sockets.hpp.
Constructor & Destructor Documentation
VNCSockets() [1/3]
VNCSockets::VNCSockets () inline
Definition at line 53 of file sockets.hpp.
VNCSockets() [2/3]
VNCSockets::VNCSockets (const char * _servername, uint16_t _port = 5901)
Definition at line 47 of file sockets.cpp.
References buf, buffered, bufoutptr, error(), port, rfbsock, ServerName, and StringToIPAddr().
VNCSockets() [3/3]
VNCSockets::VNCSockets (uint32_t IPAddr, uint16_t _port = 5901)
constructors
Definition at line 57 of file sockets.cpp.
References buf, buffered, bufoutptr, error(), ipaddr, port, and rfbsock.
Member Function Documentation
ConnectToTcpAddr()
int VNCSockets::ConnectToTcpAddr ()
Connects to the given TCP port.
Returns the socket if connected, -1 if connection failed
Definition at line 181 of file sockets.cpp.
References Socket::closeStream(), DBG_VNC, error(), ipaddr, Socket::openStream(), port, rfbsock, ServerName, Socket::tcpNoDelay(), and trace().
Referenced by VNCRFBproto::connectToRFBServer().
GetSock()
int VNCSockets::GetSock ()
get the socket used
Definition at line 288 of file sockets.cpp.
References rfbsock.
Referenced by VNCRFBproto::getSock().
ReadFromRFBServer()
bool VNCSockets::ReadFromRFBServer (char * out, uint32_t n)
Read bytes from the sever and stores it in the buffer.
Definition at line 84 of file sockets.cpp.
References buf, buffered, bufoutptr, error(), read, and rfbsock.
Referenced by VNCClient::handleCoRRE32(), VNCClient::handleHextile32(), VNCClient::handleRFBServerMessage(), VNCClient::handleRRE32(), and VNCRFBproto::initialiseRFBConnection().
SameMachine()
bool VNCSockets::SameMachine ()
Test if the other end of a socket is on the same machine.
Definition at line 238 of file sockets.cpp.
References rfbsock.
Referenced by VNCRFBproto::setFormatAndEncodings().
SetNonBlocking()
bool VNCSockets::SetNonBlocking ()
sets a socket into non-blocking mode.
Definition at line 213 of file sockets.cpp.
References rfbsock, and Socket::setNoBlocking().
Referenced by VNCRFBproto::connectToRFBServer().
StringToIPAddr()
bool VNCSockets::StringToIPAddr () private
stores the IP address of the server in ipaddr, returns false if unknown
Definition at line 222 of file sockets.cpp.
References DBG_VNC, ipaddr, my_gethostbyname(), ServerName, and trace().
Referenced by VNCSockets().
WriteExact()
bool VNCSockets::WriteExact (char * buf, int n)
Write an exact number of bytes, and don't return until you've sent them.
Definition at line 148 of file sockets.cpp.
References buf, error(), rfbsock, and write.
Referenced by VNCRFBproto::initialiseRFBConnection(), VNCRFBproto::sendClientCutText(), VNCRFBproto::sendFramebufferUpdateRequest(), VNCRFBproto::sendKeyEvent(), VNCRFBproto::sendPointerEvent(), and VNCRFBproto::setFormatAndEncodings().
Member Data Documentation
buf
uint8_t VNCSockets::buf[VNC_BUF_SIZE] private
Definition at line 45 of file sockets.hpp.
Referenced by ReadFromRFBServer(), VNCSockets(), and WriteExact().
buffered
uint32_t VNCSockets::buffered private
Definition at line 44 of file sockets.hpp.
Referenced by ReadFromRFBServer(), and VNCSockets().
bufoutptr
uint8_t* VNCSockets::bufoutptr private
buffer
Definition at line 46 of file sockets.hpp.
Referenced by ReadFromRFBServer(), and VNCSockets().
ipaddr
uint32_t VNCSockets::ipaddr private
IP address of the server.
Definition at line 38 of file sockets.hpp.
Referenced by ConnectToTcpAddr(), StringToIPAddr(), and VNCSockets().
port
uint16_t VNCSockets::port private
port
Definition at line 35 of file sockets.hpp.
Referenced by ConnectToTcpAddr(), and VNCSockets().
rfbsock
int VNCSockets::rfbsock private
the used socket
Definition at line 41 of file sockets.hpp.
Referenced by ConnectToTcpAddr(), GetSock(), ReadFromRFBServer(), SameMachine(), SetNonBlocking(), VNCSockets(), and WriteExact().
ServerName
char VNCSockets::ServerName[MAXHOSTNAMELEN] private
name of the server
Definition at line 32 of file sockets.hpp.
Referenced by ConnectToTcpAddr(), StringToIPAddr(), and VNCSockets().
The documentation for this class was generated from the following files:
src/vnc/sockets.hpp
src/vnc/sockets.cpp