#! /bin/sh
#
# build [args...]
#
# - installs all requirements
# - launches needed servers
# - builds vreng
#
# Philippe Dax - 2024
#
mkdir log 2>&1 >/dev/null
date 2>&1 >log/$0.log

cd conf

# installs requirements
# via brew, apt-get, dnf, pkg, pacman
./rc.prerequisites

# launches X11 server
./rc.X11

# configures and launches local httpd server
./rc.httpd

# configures vreng
./autogen.sh "$@"

cd ..

# compiles source
make

date 2>&1 >>log/$0.log
cat log/$0.log
