#! /bin/sh
#
# build [args...]
#
# args are the same of ./configure
#
# - installs all requirements
# - launches needed servers
# - configures vreng
# - compiles vreng
#
# Philippe Dax - 2024
#
PATH=conf:$PATH export PATH

if [ ! -d log ]; then
  mkdir log >/dev/null 2>&1
fi
date 2>&1 >log/$(basename $0).log

# goto conf dir
cd conf

# installs requirements
# via brew, apt-get, dnf, yum, pacman, pkg...
./rc.prerequisites

# launches X11 server
./rc.X11

# configures and launches local httpd server
./rc.httpd

# configures vreng
./autogen.sh "$@"

# comes bak to top
cd ..

# compiles source
make

date 2>&1 >>log/$(basename $0).log
cat log/$0.log
