#! /bin/sh
#
# build [args...]
#
# args are the same of ./configure
#
# - installs all requirements
# - launches needed servers
# - configures vreng
# - compiles vreng
#
# Philippe Dax - 2024
#
PATH=conf:$PATH export PATH

mkdir log 2>&1 >/dev/null
date 2>&1 >log/$0.log

# goto conf dir
cd conf

# installs requirements
# via brew, apt-get, dnf, pkg, pacman
./rc.prerequisites

# launches X11 server
./rc.X11

# configures and launches local httpd server
./rc.httpd

# configures vreng
./autogen.sh "$@"

# comes bak to top
cd ..

# compiles source
make

date 2>&1 >>log/$0.log
cat log/$0.log
