#! /bin/sh
#
# clone
#
# Philippe Dax - jan 2021
#
p=$(basename $0)

case $# in
0)
  echo "usage: $p github | gitlab | bitbucket"
  ;;
1)
  case $1 in
  github)
    rm -rf github
    git clone https://github.com/philippedax/vreng.git github
    ;;
  gitlab)
    rm -rf gitlab
    git clone https://gitlab.freedesktop.org/philippedax/vreng.git gitlab
    ;;
  bitbucket)
    rm -rf bitbucket
    git clone https://bitbucket.org/philippedax/vreng/src/master/ bitbucket
    ;;
  *)
    echo "usage: $p github | gitlab | bitbucket"
    ;;
  esac
esac
