#! /bin/sh
#
# clone
#
# Philippe Dax - jan 2021
#
p=$(basename $0)

usage()
{
  echo "usage: $p github | gitlab | bitbucket"
}

case $# in
0)
  usage
  ;;
1)
  case $1 in
  github)
    cp -r $1 old
    rm -rf $1
    git clone https://github.com/philippedax/vreng.git $1
    ;;
  gitlab)
    cp -r $1 old
    rm -rf $1
    git clone https://gitlab.freedesktop.org/philippedax/vreng.git $1
    ;;
  bitbucket)
    cp -r $1 old
    rm -rf $1
    git clone https://bitbucket.org/philippedax/vreng/src/master/ $1
    ;;
  *)
    usage
    ;;
  esac
esac
