#! /bin/sh
#
# commit message
#
# Philippe Dax - avr 2017
#
p=$(basename $0)

case $# in
0)
  echo "usage: $p message"
  message="not significative"
  ;;
1)
  message=$1
  ;;
esac

#svn ci -m "$message"
#./.github
git commit -a -m "$message"
git push origin master
#./.gitlab
#git commit -a -m "$message"
#git push origin master
#./.github

log=git.log
if [ -f $log ] ; then
  last=$(tail -1 $log)
  num=$(echo $last | cut -f1 -d ' ')
  num=$[ $num + 1 ]
else
  num=0
  touch $log
fi
echo "$num $(date)	$message" >> $log
echo "$num $(date)	$message"
