#! /bin/sh
#
# commit message
#
# Philippe Dax - avr 2017
#
p=$(basename $0)

case $# in
0)
  echo "usage: $p message"
  exit 0
  ;;
esac

svn ci -m "$1"
support/github
git commit -a -m "$1"
git push origin master
support/gitlab
git commit -a -m "$1"
git push origin master
support/github
