#! /bin/sh
#
# vreng wrapper
#
# Philippe Dax - 2006
#
PATH=..:src/bin:bin:../bin:$PATH export PATH

case $# in
1)
  if test "$1" = "-D"; then
    lldb vreng
  else
    vreng $*
  fi
  ;;
*)
  vreng $*
  ;;
esac
