#! /bin/sh
#
# commit message
#
# Philippe Dax - avr 2017
#
p=$(basename $0)

case $# in
0)
  echo "usage: $p message"
  exit 0
  ;;
1)
  message=$1
  ;;
esac

mkdir log 2>/dev/null
log=conf/commit.log
chmod 644 $log
if [ -f $log ] ; then
  last=$(tail -1 $log)
  num=$(echo $last | cut -f1 -d ' ')
  num=$[ $num + 1 ]
else
  num=1
  touch $log
fi
echo "$num $(date)	$message" >> $log
echo "$num $(date)	$message"

# commit
git commit -a -m "$message"

# push to github
git push origin master
