//---------------------------------------------------------------------------
// VREng (Virtual Reality Engine)	https://github.com/philippedax/vreng
//
// Copyright (C) 1997-2011 Philippe Dax
// Telecom-Paris (Ecole Nationale Superieure des Telecommunications)
//
// VREng is a free software; you can redistribute it and/or modify it
// under the terms of the GNU General Public Licence as published by
// the Free Software Foundation; either version 2, or (at your option)
// any later version.
//
// VREng is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
//---------------------------------------------------------------------------
// dress.cpp
//
// Dress handling
//---------------------------------------------------------------------------
#include "vreng.hpp"
#include "dress.hpp"
#include "user.hpp"	// User


const OClass Dress::oclass(DRESS_TYPE, "Dress", Dress::creator);

//local
static uint16_t oid = 0;

struct sDress {
  uint8_t dress_id;
  const char dress_str[16];
};

static struct sDress dresss[] = {
  {Dress::SPIRES,  "spires"},
  {Dress::BANDS,   "bands"},
  {Dress::ROSES,   "roses"},
  {Dress::NODRESS, ""},
};


Object * Dress::creator(char *l)
{ 
  return new Dress(l);
}

void Dress::defaults()
{
  article = Cloth::DRESS;
  ttl = MAXFLOAT;
  dx = 0;
  dy = 0;
  dz = 0.10;	// hip +10
  dax = 0;
  day = 0;
  daz = 0;
  model = Dress::NODRESS;
}

/* solid geometry */
void Dress::geometry()
{
  char s[128];

  switch (model) {
  case Dress::SPIRES:
    sprintf(s,"solid shape=\"cone\" rb=\"%f\" rt=\"%f\" h=\"%f\" tx=\"%s\" />",.1,.3,-.45,"/gif/pyjama-spires.gif");
    parseSolid(s);
    sprintf(s,"solid shape=\"cone\" rb=\"%f\" rt=\"%f\" h=\"%f\" tx=\"%s\" />",.1,.15,.25,"/gif/pyjama-spires.gif");
    parseSolid(s);
    break;
  case Dress::BANDS:
    sprintf(s,"solid shape=\"cone\" rb=\"%f\" rt=\"%f\" h=\"%f\" tx=\"%s\" />",.1,.25,-.45,"/gif/redbands.gif");
    parseSolid(s);
    sprintf(s,"solid shape=\"cone\" rb=\"%f\" rt=\"%f\" h=\"%f\" tx=\"%s\" />",.1,.15,.25,"/gif/redbands.gif");
    parseSolid(s);
    break;
  case Dress::ROSES:
    sprintf(s,"solid shape=\"cone\" rb=\"%f\" rt=\"%f\" h=\"%f\" tx=\"%s\" />",.1,.2,-.45,"/gif/roses.gif");
    parseSolid(s);
    sprintf(s,"solid shape=\"cone\" rb=\"%f\" rt=\"%f\" h=\"%f\" tx=\"%s\" />",.1,.15,.25,"/gif/roses.gif");
    parseSolid(s);
    break;
  default:
    break;
  }
}

/* Created from file */
void Dress::parser(char *l)
{
  defaults();
  l = tokenize(l);
  begin_while_parse(l) {
    l = parseAttributes(l);	// <solid ... />
    if (!l) break;
    if (! stringcmp(l, "model=")) {
      l = parseString(l, modelname, "model");
      if      (! stringcmp(modelname, "spires")) model = SPIRES;
      else if (! stringcmp(modelname, "bands"))  model = BANDS;
      else if (! stringcmp(modelname, "roses"))  model = ROSES;
    }
  }
  end_while_parse(l);
}

uint8_t Dress::getModel(const char *name)
{
  struct sDress *pdresss = dresss;

  if (name) {
    for ( ; pdresss; pdresss++)
      if (! strcmp(name, pdresss->dress_str))
        return pdresss->dress_id;
  }
  return NODRESS;
}

void Dress::behaviors()
{
  enableBehavior(COLLIDE_NEVER);
  enableBehavior(TAKABLE);
  if (taken) {
    enableBehavior(DYNAMIC);
    enableBehavior(TRANSCIENT);
  }
}

/* sets position near the avatar */
void Dress::inits()
{
  initClothObject(ttl);
  if (taken)
    enablePermanentMovement();  // follows user

  if (! taken)  return;

  // save original position
  ox = pos.x; oy = pos.y; oz = pos.z;
  oax = pos.ax; oay = pos.ay; oaz = pos.az;

  // set new position
  if (localuser) {
    pos.x = localuser->pos.x + dx;
    pos.y = localuser->pos.y + dy;
    pos.z = localuser->pos.z + dz;
    pos.az = localuser->pos.az + daz;
  }
  pos.ax = dax;
  pos.ay = day;

  updatePosition();
}

/* Created from file */
Dress::Dress(char *l)
{
  model = Dress::SPIRES;
  strcpy(modelname, "spires");
  parser(l);
  taken = false;
  behaviors();
  inits();
}

/* Regenerated by world via VSql */
Dress::Dress(User *user, void *d, time_t s, time_t u)
{
  char *str = static_cast<char *>(d);       // name transmitted
  if (!str) return;

  strcpy(name.given, str);
  strcpy(name.type, typeName());     // need name.type for VSql
  char *p = strchr(str, '&');
  *p = '\0';
  strcpy(modelname, str);

  defaults();
  taken = true;
  model = getModel(modelname);
  setName(modelname);
  setOwner();
  getPersist();
  geometry();
  behaviors();
  inits();
}

void Dress::quit()
{
  oid = 0;
  savePersist();
}

/* wear */
void Dress::wear()
{
  if (taken) takeoff();

  taken = true;
  //model = getModel(modelname);
  //setName(modelname);
  setOwner();
  setPersist();
  behaviors();
  inits();
  createVolatile(PROPS);
  addWearList();
}

/* takeoff */
void Dress::takeoff()
{
  taken = false;
  restorePosition();	// restore original position
  delPersist();
  delWearList();
}

/* wear: indirectly called by user */
void Dress::wear_cb(Dress *dress, void *d, time_t s, time_t u)
{
  dress->wear();
}

/* takeoff: indirectly called by user */
void Dress::takeoff_cb(Dress *dress, void *d, time_t s, time_t u)
{
  dress->takeoff();
}

/* Creation: this method is invisible: called by the World */
void Dress::recreate_cb(User *pu, void *d, time_t s, time_t u)
{
  new Dress(pu, d, s, u);
}

void Dress::funcs()
{
  getPropFunc(DRESS_TYPE, PROPXY, _Payload get_xy);
  getPropFunc(DRESS_TYPE, PROPZ, _Payload get_z);
  getPropFunc(DRESS_TYPE, PROPAZ, _Payload get_az);
  getPropFunc(DRESS_TYPE, PROPAX, _Payload get_ax);
  getPropFunc(DRESS_TYPE, PROPAY, _Payload get_ay);
  getPropFunc(DRESS_TYPE, PROPHNAME, _Payload get_hname);

  putPropFunc(DRESS_TYPE, PROPXY, _Payload put_xy);
  putPropFunc(DRESS_TYPE, PROPZ, _Payload put_z); 
  putPropFunc(DRESS_TYPE, PROPAZ, _Payload put_az);
  putPropFunc(DRESS_TYPE, PROPAX, _Payload put_ax);
  putPropFunc(DRESS_TYPE, PROPAY, _Payload put_ay);
  putPropFunc(DRESS_TYPE, PROPHNAME, _Payload put_hname);

  setActionFunc(DRESS_TYPE, WEAR, _Action wear_cb, "Wear");
  setActionFunc(DRESS_TYPE, TAKEOFF, _Action takeoff_cb, "Takeoff");

  setActionFunc(DRESS_TYPE, RECREATE, _Action recreate_cb, "");
}
